### ISSUE TITLE
Dump SIL IR?

### ISSUE THREAD

**Issue by Isweet** [facebook/infer#1012]
Sorry if this is documented in a `--help` somewhere, I wasn't able to find it.

Is there a way, via one of the CLI tools, to dump the SIL IR associated with a particular program?

**Comment by jvillard** [comment]
If you run infer in debug mode it will dump a dotty representation of the file, eg:

```
infer -g -- clang -c examples/hello.c
xdot infer-out/captured/hello.c.f19e4797ddf4b23fd1ce68a7e60f3b03/icfg.dot
```

You can also see the IR instructions in the html debug output:

```
infer -g -- clang -c examples/hello.c
firefox infer-out/captured/hello.c.f19e4797ddf4b23fd1ce68a7e60f3b03.html
```

**Comment by Isweet** [comment]
Thanks, this is exactly what I needed!

**Comment by anwarmamat** [comment]
Can we dump SIL as a text file? Can I feed SIL code as source code to infer?

**Comment by jvillard** [comment]
@anwarmamat not really, at the moment we use OCaml's `Marshal` as the serialisation format for SIL on disk. What would be your use case for a text format?

**Comment by anwarmamat** [comment]
I want to do this. Take a new language, compile it into SIL IR, feed it into infer, and run static analysis on it. Is there an infer API that takes SIL IR  as an input, and runs analysis?

**Comment by mbouaziz** [comment]
@anwarmamat Not currently. But if you write such a feature, we'd be happy to review your pull request!
