### ISSUE TITLE
APK and IPA

### ISSUE THREAD

**Issue by juanduarte1927** [facebook/infer#1018]
Hello, 
I want analyze APK and IPA files, but i can´t find docs. Please help me.

**Comment by mbouaziz** [comment]
Infer doesn't analyze APK or IPA files.
Our APK optimizer, [Redex](https://github.com/facebook/redex), analyzes the APK directly.

**Comment by juanduarte1927** [comment]
Ok, I see Redex and try.
With infer, I need decompile the APK or have the project, after I can use "infer run -- gradle build"
Excuse me, but i cant find a lot docs.
