### ISSUE TITLE
'make -C infer java' failed ,help me please.

### ISSUE THREAD

**Issue by easternHong** [facebook/infer#102]
ubuntu 14.04 x64

sed -e 's/@MAJOR@/0/g' \
		-e 's/@MINOR@/1/g' \
		-e 's/@PATCH@/1/g' \
		-e 's/@GIT_COMMIT@/510fc4ed2504b31e942acf2d99cec93e55a1851a/g' \
		-e 's/@GIT_BRANCH@/master/g' \
		-e 's/@GIT_TAG@//g' \
		backend/version.ml.in > backend/version.ml
atdgen -t backend/jsonbug.atd -o backend/jsonbug
make[1]: atdgen：command not found
make[1]: *** [backend/jsonbug_t.ml] err 127

**Comment by jvillard** [comment]
> make[1]: atdgen：command not found

You are missing one of the dependencies. Make sure you follow the steps in [INSTALL.md](https://github.com/facebook/infer/blob/master/INSTALL.md#installation-instructions-1)
