### ISSUE TITLE
gradle build failed

### ISSUE THREAD

**Issue by little-newbie** [facebook/infer#1021]
Hi,
  Sorry to interrupt you.  I have some problems with infer.
  I used Release Version v0.15.0 of infer and run it on Ubuntu 16.04 LTS. When I built an gradle program with ' infer  -- gradle build', some error occured, and I couldn't get any solution from google.

Capturing in gradle mode...
Running and capturing gradle compilation...
12:55:49.449 [ERROR] [system.err] Note: /home/iss/work/test-source/Contacts/PhoneCommon/src/com/android/phone/common/dialpad/DialpadView.java uses or overrides a deprecated API.
12:55:49.449 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
12:55:52.469 [ERROR] [system.err] /home/iss/work/test-source/Contacts/src/com/android/contacts/ContactSaveService.java:1277: warning: non-varargs call of varargs method with inexact argument type for last parameter;
12:55:52.469 [ERROR] [system.err]                     R.string.contacts_deleted_one_named_toast, names);
12:55:52.469 [ERROR] [system.err]                                                                ^
12:55:52.469 [ERROR] [system.err]   cast to Object for a varargs call
12:55:52.469 [ERROR] [system.err]   cast to Object[] for a non-varargs call and to suppress this warning
12:55:52.470 [ERROR] [system.err] /home/iss/work/test-source/Contacts/src/com/android/contacts/ContactSaveService.java:1280: warning: non-varargs call of varargs method with inexact argument type for last parameter;
12:55:52.470 [ERROR] [system.err]                     R.string.contacts_deleted_two_named_toast, names);
12:55:52.470 [ERROR] [system.err]                                                                ^
12:55:52.470 [ERROR] [system.err]   cast to Object for a varargs call
12:55:52.470 [ERROR] [system.err]   cast to Object[] for a non-varargs call and to suppress this warning
12:55:52.470 [ERROR] [system.err] /home/iss/work/test-source/Contacts/src/com/android/contacts/ContactSaveService.java:1283: warning: non-varargs call of varargs method with inexact argument type for last parameter;
12:55:52.470 [ERROR] [system.err]                     R.string.contacts_deleted_many_named_toast, names);
12:55:52.470 [ERROR] [system.err]                                                                 ^
12:55:52.471 [ERROR] [system.err]   cast to Object for a varargs call
12:55:52.471 [ERROR] [system.err]   cast to Object[] for a non-varargs call and to suppress this warning
12:55:53.930 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
12:55:53.931 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
12:55:53.931 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
12:55:53.931 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
12:55:53.931 [ERROR] [system.err] 3 warnings
12:56:19.703 [ERROR] [system.err] Note: /home/iss/work/test-source/Contacts/PhoneCommon/src/com/android/phone/common/dialpad/DialpadView.java uses or overrides a deprecated API.
12:56:19.703 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
12:56:20.618 [ERROR] [system.err] /home/iss/work/test-source/Contacts/src/com/android/contacts/ContactSaveService.java:1277: warning: non-varargs call of varargs method with inexact argument type for last parameter;
12:56:20.618 [ERROR] [system.err]                     R.string.contacts_deleted_one_named_toast, names);
12:56:20.618 [ERROR] [system.err]                                                                ^
12:56:20.618 [ERROR] [system.err]   cast to Object for a varargs call
12:56:20.618 [ERROR] [system.err]   cast to Object[] for a non-varargs call and to suppress this warning
12:56:20.619 [ERROR] [system.err] /home/iss/work/test-source/Contacts/src/com/android/contacts/ContactSaveService.java:1280: warning: non-varargs call of varargs method with inexact argument type for last parameter;
12:56:20.619 [ERROR] [system.err]                     R.string.contacts_deleted_two_named_toast, names);
12:56:20.619 [ERROR] [system.err]                                                                ^
12:56:20.619 [ERROR] [system.err]   cast to Object for a varargs call
12:56:20.619 [ERROR] [system.err]   cast to Object[] for a non-varargs call and to suppress this warning
12:56:20.619 [ERROR] [system.err] /home/iss/work/test-source/Contacts/src/com/android/contacts/ContactSaveService.java:1283: warning: non-varargs call of varargs method with inexact argument type for last parameter;
12:56:20.619 [ERROR] [system.err]                     R.string.contacts_deleted_many_named_toast, names);
12:56:20.619 [ERROR] [system.err]                                                                 ^
12:56:20.619 [ERROR] [system.err]   cast to Object for a varargs call
12:56:20.620 [ERROR] [system.err]   cast to Object[] for a non-varargs call and to suppress this warning
12:56:21.950 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
12:56:21.950 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
12:56:21.950 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
12:56:21.950 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
12:56:21.950 [ERROR] [system.err] 3 warnings
12:58:39.251 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
12:58:39.251 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
12:58:39.252 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
12:58:39.252 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
12:58:39.252 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':lint'.
12:58:39.252 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Could not resolve all files for configuration ':lintClassPath'.
12:58:39.252 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > Could not download groovy-all.jar (org.codehaus.groovy:groovy-all:2.4.12)
12:58:39.252 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]       > Could not get resource 'https://jcenter.bintray.com/org/codehaus/groovy/groovy-all/2.4.12/groovy-all-2.4.12.jar'.
12:58:39.252 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]          > Could not GET 'https://jcenter.bintray.com/org/codehaus/groovy/groovy-all/2.4.12/groovy-all-2.4.12.jar'.
12:58:39.252 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]             > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/54.192.84.76, d29vzk4ow07wi7.cloudfront.net/54.192.84.210, d29vzk4ow07wi7.cloudfront.net/54.192.84.72, d29vzk4ow07wi7.cloudfront.net/54.192.84.175] failed: Read timed out
12:58:39.252 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
12:58:39.253 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
12:58:39.253 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.  Run with --scan to get full insights.
12:58:39.253 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
12:58:39.253 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
12:58:39.253 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] 
12:58:39.253 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 3m 19s
ERROR: couldn't run compilation command `[u'gradle', '--debug', u'build']`
Internal Error:   /home/iss/Tools/Analysis/infer-linux64-v0.15.0/lib/infer/infer/bin/../lib/python/infer.py
  -j 4 --project-root /home/iss/work/test-source/Contacts --out
  /home/iss/work/test-source/Contacts/infer-out -- gradle build:
  exited with code 1
Error backtrace:
Raised at file "base/Die.ml" (inlined), line 25, characters 6-36
Called from file "base/Logging.ml", line 314, characters 58-80
Called from file "integration/Driver.ml", line 159, characters 2-16
Called from file "integration/Driver.ml", line 280, characters 6-420
Called from file "infer.ml", line 20, characters 2-36
Called from file "infer.ml", line 130, characters 8-54

Run the command again with `--keep-going` to try and ignore this error.

Please give some help. It's an emergency. Tks a lot.

**Comment by little-newbie** [comment]
In the file named “config.log”， I found some fatal error. Are they important?
configure:2913: $? = 0
configure:2902: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:2913: $? = 1
configure:2902: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.

configure:3678: gcc -E  conftest.c
conftest.c:9:28: fatal error: ac_nonexistent.h: No such file or directory
compilation terminated.
configure:3678: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "Infer"
| #define PACKAGE_TARNAME "infer"
| #define PACKAGE_VERSION "0.15.0"
| #define PACKAGE_STRING "Infer 0.15.0"
| #define PACKAGE_BUGREPORT "https://github.com/facebook/infer/issues/"
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:3703: result: gcc -E
configure:3723: gcc -E  conftest.c
configure:3723: $? = 0
configure:3737: gcc -E  conftest.c
conftest.c:9:28: fatal error: ac_nonexistent.h: No such file or directory
compilation terminated.

**Comment by jvillard** [comment]
@little-newbie does `gradle build` on its own succeed? It looks like it's failing to download some resource from the internet:

>  12:58:39.252 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/54.192.84.76, d29vzk4ow07wi7.cloudfront.net/54.192.84.210, d29vzk4ow07wi7.cloudfront.net/54.192.84.72, d29vzk4ow07wi7.cloudfront.net/54.192.84.175] failed: Read timed out

The "config.log" file is generated by [autoconf](https://www.gnu.org/software/autoconf/autoconf.html) and is how infer inspects your system to know how to build itself. Errors are expected and that file is not used after infer has been built.

**Comment by little-newbie** [comment]
@jvillard Thanks for your reply. 
I have fixed this problem by fllowing steps.
firstly, install mpfr manally to fix the fatal error: mpfr.h: No such file or directory;
then install llvm manally to fix the fatal error: ac_nonexistent.h: No such file or directory;
finally, uninstall gradle and erase the path from my configure file and run gradlew to download and install gradle automatically.

After that, I run ‘infer -- gradle build’， and found some bugs  in infer-out directory.

**Comment by jvillard** [comment]
@little-newbie thanks for posting your steps to resolution!
