### ISSUE TITLE
Problem when running infer in MacOS Mojave

### ISSUE THREAD

**Issue by DboraSilva** [facebook/infer#1022]
The procedures are not analyzed, only the files. (View image attached)
I used the same files as the infer that is available in the browser: https://codeboard.io/projects/11587?view=2.1-21.0-22.0

Infer version v0.15.0
java version "11" 2018-09-25
Java(TM) SE Runtime Environment 18.9 (build 11+28)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11+28, mixed mode)
SO: macOs Mojave v10.14

[](url)![captura de tela 2018-11-12 as 22 26 42](https://user-images.githubusercontent.com/26068816/48384775-95742800-e6ca-11e8-8747-07f8c4d5e3a2.png)

**Comment by jvillard** [comment]
Looks like infer cannot parse the output of java 11 correctly. You can try by downgrading your version of Java to java 8 or 9.

**Comment by DboraSilva** [comment]
The problem is resolved.

Thanks :)

**Comment by DboraSilva** [comment]
The problem is resolved.

Thanks :)
