### ISSUE TITLE
Conflict between license declared in Maven (BSD) and the Github repo (MIT)

### ISSUE THREAD

**Issue by naddeoa** [facebook/infer#1025]
Looking at the [Maven page for infer-annotations 0.11.2](https://mvnrepository.com/artifact/com.facebook.infer.annotation/infer-annotation/0.11.2) (which links to this repo), it claims that the library is BSD, but this repo contains an MIT license.

Is the Maven repo out of date? If so, could it be updated?

**Comment by jvillard** [comment]
Thanks for pointing this out. This package points to infer version 11.2, which was released under BSD + patents. The change to MIT was made for [infer 0.15.0](https://github.com/facebook/infer/releases/tag/v0.15.0). I'll keep this issue open in an attempt to remember to update the license in the Maven repo next time we update it.

**Comment by artempyanykh** [comment]
Fixed now. The license is MIT now on [Maven Central](https://search.maven.org/artifact/com.facebook.infer.annotation/infer-annotation)
