### ISSUE TITLE
Infer Release

### ISSUE THREAD

**Issue by WishQi** [facebook/infer#1027]
When will the next version of infer release?

**Comment by jvillard** [comment]
Probably in the next 2-3 weeks, see https://github.com/facebook/infer/issues/871#issuecomment-441613919

At the moment the easiest way to get a recent version is to [build infer from source](https://github.com/facebook/infer/blob/91f115fcaa3eadaa616b47152eacdcd1e8023ce8/INSTALL.md#install-infer-from-source).
