### ISSUE TITLE
ObjC False Positive: weak properties included in RETAIN_CYCLE report

### ISSUE THREAD

**Issue by loufranco** [facebook/infer#103]
I am getting this RETAIN_CYCLE (type names and instance variables renamed to show weak/strong):

Retain cycle involving the following objects:  (1) an object of class TYPE_A  retaining another object via instance variable _varForWeakPropertyInA,  (2) an object of class TYPE_B  retaining another object via instance variable _varForStrongPropertyinB,  (3) an object of class TYPE_C  retaining another object via instance variable _varForWeakPropertyInC,   

So, in this cycle, two of the instance variables are for weak properties.  One thing that might be causing the problem is that the properties are declared this way in the `@interface` in the .h

`@property (nonatomic, readonly, weak) T *varForWeakPropertyInC;`

And, then in an anonymous category in the .m, it is changed like this:

`@property (nonatomic, weak) T *varForWeakPropertyInC;`

We do this to allow the class to write to its own property, but only expose a readonly property to other classes.  It's weak in both cases for both variables (I checked).

The actual code is hard to include with all of its context, but I can try to find a minimal example if you think weak properties work properly.  I can say that I am doing this on a very large codebase with tons of `weak` and block usage and this was the only RETAIN_CYCLE it found in the entire app (so I think it might be particular to this code).

**Comment by ddino** [comment]
hi  loufranco,

Infer normally understands the "weak" keyword and it should not report. It may be some corner case. 
If you could make a small example that reproduce the problem we'll try to see what's going wrong 
on that case.

Thanks,
Dino

**Comment by loufranco** [comment]
Thanks Dino, I will try.

**Comment by jvillard** [comment]
@loufranco feel free to re-open the issue if the bug is still present in Infer's latest version and you can provide more details.
