### ISSUE TITLE
Can't build infer and Can't clean

### ISSUE THREAD

**Issue by unioncomm** [facebook/infer#1032]
help me please~~~ I have the issue like this :

jhminiui-Mac-mini:~ jhmini$ sudo infer -- /Users/jhmini/Downloads/infer-master/examples/android_hello/gradlew build
Capturing in gradle mode...
Running and capturing gradle compilation...
Nothing to compile. Try cleaning the build first.
There was nothing to analyze.

jhminiui-Mac-mini:~ jhmini$ sudo /Users/jhmini/Downloads/infer-master/examples/android_hello/gradlew clean

FAILURE: Build failed with an exception.

What went wrong:
Task 'clean' not found in root project 'jhmini'.

Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.064 secs

Try cleaning the build first.???????? what kind of clean??? infer has clean?? help me plz!

**Comment by jeremydubreil** [comment]
Can you try first what the output is without `infer` using:
```
> cd /Users/jhmini/Downloads/infer-master/examples/android_hello/
> ./gradlew clean
> ./gradlew build
```

**Comment by unioncomm** [comment]
thank you! bout another problem is now!  

jhminiui-Mac-mini:android_hello jhmini$ ./gradlew clean

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed

jhminiui-Mac-mini:android_hello jhmini$ ./gradlew build
<=------------> 12% EXECUTING [1m 25s]
> :app:mergeDebugResources > Resolve dependencies of :app:_internal_aapt2_binary


FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:_internal_aapt2_binary'.
> Could not find com.android.tools.build:aapt2:3.2.1-4818971.
  Searched in the following locations:
      file:/Users/jhmini/Library/Android/sdk/extras/m2repository/com/android/tools/build/aapt2/3.2.1-4818971/aapt2-3.2.1-4818971.pom
      file:/Users/jhmini/Library/Android/sdk/extras/m2repository/com/android/tools/build/aapt2/3.2.1-4818971/aapt2-3.2.1-4818971-osx.jar
      file:/Users/jhmini/Library/Android/sdk/extras/google/m2repository/com/android/tools/build/aapt2/3.2.1-4818971/aapt2-3.2.1-4818971.pom
      file:/Users/jhmini/Library/Android/sdk/extras/google/m2repository/com/android/tools/build/aapt2/3.2.1-4818971/aapt2-3.2.1-4818971-osx.jar
      file:/Users/jhmini/Library/Android/sdk/extras/android/m2repository/com/android/tools/build/aapt2/3.2.1-4818971/aapt2-3.2.1-4818971.pom
      file:/Users/jhmini/Library/Android/sdk/extras/android/m2repository/com/android/tools/build/aapt2/3.2.1-4818971/aapt2-3.2.1-4818971-osx.jar
      https://jcenter.bintray.com/com/android/tools/build/aapt2/3.2.1-4818971/aapt2-3.2.1-4818971.pom
      https://jcenter.bintray.com/com/android/tools/build/aapt2/3.2.1-4818971/aapt2-3.2.1-4818971-osx.jar
  Required by:
      project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 26s
9 actionable tasks: 8 executed, 1 up-to-date

why dosen't work??? why?? help me please~~

**Comment by unioncomm** [comment]
i resolve my self!!

i added  google()
in gradle like this : 

allprojects {
    repositories {
        google()
    }
}

thank you good working now kkkk
