### ISSUE TITLE
Running out of the memory

### ISSUE THREAD

**Issue by teoring** [facebook/infer#1033]
Hello,
I am facing an issue while scanning big C++ project (around 5735744 lines of code). I have 16GB on my laptop and after like a few hours of scanning (is it normal it takes that long?) all the memory is taken and another 8GB of swap as well.

Eventually scan fails with Fatal error: exception Out of memory

I am running infer using compilation database, created from cmake
infer --compilation-database compile_commands.json

Infer version v0.15.0

**Comment by jvillard** [comment]
It shouldn't take several hours to analyse even a reasonably big project. Is the time spent doing the capture or the analysis? Some analyses have corner cases where they eat up a lot of memory, you can try turning them off. I think for 0.15.0 that would be quandary (taint analysis for security), so adding `--no-quandary` might help.

**Comment by jeremydubreil** [comment]
@teoring , closing now. Please re-open the task if this is still an issue.
