### ISSUE TITLE
After installing infer..while running C 

### ISSUE THREAD

**Issue by Vishrutidesai** [facebook/infer#1035]
Won't able to run
sudo make install 
I do from install from source

**Comment by jvillard** [comment]
Can you please provide more information? Please include:
- the version of infer used
- the command you used to run infer
- the full output that contains the error (please use https://gist.github.com/ or equivalent)

**Comment by Vishrutidesai** [comment]
can you provide the installation steps for opam?

**Comment by jeremydubreil** [comment]
@Vishrutidesai, the installation of opam depends on the platform. Please let us know if the installation steps here, https://github.com/facebook/infer/blob/master/INSTALL.md, are incomplete.

**Comment by Vishrutidesai** [comment]
i have installed opam 2.0..
now i am getting below error
 [ERROR] Missing dependencies -- the following commands are required for opam to
        operate:
  - bwrap: Sandboxing tool bwrap was not found. You should install
    'bubblewrap'. See
    http://opam.ocaml.org/doc/2.0/FAQ.html#Why-opam-asks-me-to-install-bwrap.

but no direct link for bubblewrap

**Comment by Vishrutidesai** [comment]
getting previous error while executing 

./build-infer.sh clang

**Comment by jeremydubreil** [comment]
Thanks. We will add Bubblewrap to the list of dependencies. Can you give more information about the error you get when running:
```
> ./build-infer.sh clang
```
?

**Comment by Vishrutidesai** [comment]
initializing opam...
[NOTE] Will configure from built-in defaults.
Checking for available remotes: rsync and local, git, mercurial, darcs.
Perfect!
[ERROR] Missing dependencies -- the following commands are required for
opam to operate:
  - bwrap: Sandboxing tool bwrap was not found. You should install
'bubblewrap'. See
    http://opam.ocaml.org/doc/2.0/FAQ.html#Why-opam-asks-me-to-install-bwrap
.

**Comment by jeremydubreil** [comment]
@Vishrutidesai , it seems that you need to install Bubblewrap in order to use opam 2

**Comment by jeremydubreil** [comment]
@Vishrutidesai , closing the issue for now. Please re-open if you are still getting the same issue after installing Bubblewarp
