### ISSUE TITLE
infer does not find any Java issues with OpenJDK-11 (jdk-11.0.1)

### ISSUE THREAD

**Issue by dmitris** [facebook/infer#1043]
I'm trying a simple Java case from https://fbinfer.com/docs/hello-world.html#hello-world-java.  `infer` finds the expected `NULL_DEREFERENCE` issue with the JDK being Java10 (or 8), but as soon as I switch to JDK11, I'm getting "No issues found."  Is it a known problem with jdk11?  I can imagine that the internal intermediate representation has changed with Java11.

**Comment by jvillard** [comment]
I think you're right that infer doesn't work on jdk-11 yet, although I haven't investigated why exactly. It could be that the format of the verbose output of `javac` has changed so infer doesn't pick up the names of the files involved anymore when [scanning it](https://github.com/facebook/infer/blob/05ec029e504d1c20c863e42b8121c85c868406ff/infer/src/java/jClasspath.ml#L113) (that was the case for Java 9 for instance and that function had to be updated).

**Comment by dmitris** [comment]
thanks @jvillard - I think this could be the issue - https://github.com/facebook/infer/blob/05ec029e504d1c20c863e42b8121c85c868406ff/infer/src/java/jClasspath.ml#L121
Comparing the verbose output of `javac 10.0.2` and `javac 11.0.1`, I see that javac 10 writes:
`[wrote SimpleFileObject[${BASEDIR}/java/helloworld/HelloWorld.class]]` (`${BASEDIR}` being actual full filepath, changed it) whereas javac 11 outputs only: `[wrote HelloWorld.class]`

**Comment by dmitris** [comment]
full output of javac verbose output from javac 10 and 11 (with the base directory changed to `${BASEDIR}`):
[out10.txt](https://github.com/facebook/infer/files/2742244/out10.txt)
[out11.txt](https://github.com/facebook/infer/files/2742245/out11.txt)

**Comment by jesmg** [comment]
I have the same problem trying to execute infer over the java examples

**Comment by ezgicicek** [comment]
Hi,
If you get the latest version of Infer, you should be able to get Infer to report on the Java examples with Java 11. I have added support for it in https://github.com/facebook/infer/commit/ce190547.

**Comment by jvillard** [comment]
The new version of infer does support java 11, but the current binary release has been built against java 8 so for now you'll need to build infer from source to get java 11 support.

**Comment by jvillard** [comment]
Closing since this is fixed in master.
