### ISSUE TITLE
`make test` fails in `build differential interesting paths filter test` on MacOS 10.14.2

### ISSUE THREAD

**Issue by dmitris** [facebook/infer#1045]
`make test` fails in `build differential interesting paths filter test` on MacOS 10.14.2 with the freshly updated code (`2cf4905c74f3f7bb3873b4993af236bc331418d7` - though not caused by the latest changes)

[outmod.txt](https://github.com/facebook/infer/files/2742462/outmod.txt)
\- output of `make test` (top infer directory path changed to `${INFERDIR})

**Comment by martintrojer** [comment]
Hello,

I can't replicate this error on my 10.14.2 mac.

What java version do you have? I tested with "1.8.0_181"

**Comment by dmitris** [comment]
I have `javac 10.0.2`.

When trying to reproduce again, I'm getting a different test failure (below) - going to close it for now and try to dig more myself.

```
[*ERROR**][92656] Test output (codetoanalyze/c/bufferoverrun/issues.exp.test) differs from expected test output codetoanalyze/c/bufferoverrun/issues.exp
[*ERROR**][92656] Run the following command to replace the expected test output with the new output:
[*ERROR**][92656]
[*ERROR**][92656]   make -C codetoanalyze/c/bufferoverrun replace
[*ERROR**][92656]
[*ERROR**][92656] make[1]: *** [test] Error 1
[*ERROR**][92656] *** stderr:
```
