### ISSUE TITLE
Will this work correctly for

### ISSUE THREAD

**Issue by proabiral** [facebook/infer#1047]
Will this work correctly for 

(1) Nested loops
(2) Loops with `break`/`continue`/`return`
(3) Loops inside of exceptional control-flow (e.g., `try { ... } catch (Exception _} { while (e1) { ... } }`)?

I ask (1)/(2) because the usual algorithm for computing loop heads in compilers is a bit more complicated than this; you need to compute the dominators of the graph first. I&amp;#39;m sure this simpler algorithm works in most cases, but for more complex loops I&amp;#39;m guessing you&amp;#39;ll need the classic algorithm.

I ask (3) because I think `Node.get_succs` only returns the non-exceptional successors of the current node, which might cause the algorithm to miss loop heads inside of exceptional control-flow.

_Originally posted by @sblackshear in https://github.com/facebook/infer/pull/549_

**Comment by ezgicicek** [comment]
(1) and (2): If one is only interested in finding loop headers, then Tarjan's DFS algorithm suffices and I think Dominators is an overkill. We are assuming that the CFG is reducible which is the case in most of the code we face in practice.
If you have specific examples in mind, let us know though.

(3): Good observation! If you look at the more recent code in https://github.com/facebook/infer/blob/master/infer/src/IR/Procdesc.ml#L653, you can see that we also get the exceptional nodes to take care of the problem you mentioned.
