### ISSUE TITLE
UnicodeDecodeError if run in a path with UTF-8 characters

### ISSUE THREAD

**Issue by MiloJiang** [facebook/infer#1049]
Same with #76, I can still reproduce it with v0.15.0

**Comment by martintrojer** [comment]
Hello, thanks for reporting. 

Can you provide more exact repro steps?

**Comment by mbouaziz** [comment]
Hi, the logic for our Python script encoding is here: https://github.com/facebook/infer/blob/master/infer/lib/python/inferlib/config.py#L15
with a fallback to ASCII.

What does `locale` outputs for you?

**Comment by MiloJiang** [comment]
Hi 

➜  ~ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
➜  ~

**Comment by mbouaziz** [comment]
Hi @MiloJiang,
It looks like `LC_CTYPE="UTF-8"` is not a valid setting.
Try `LC_CTYPE="en_US.UTF-8"` for example.

**Comment by jvillard** [comment]
Closing optimistically. Please re-open if @mbouaziz's suggestion wasn't enough.
