### ISSUE TITLE
[objective-c][false-positive] static-usage- I do not want to free my memory

### ISSUE THREAD

**Issue by GeekMin** [facebook/infer#105]
```
static QIMService* g_IMService = nil;
@implementation QIMService	
+ (QIMService*)getInstance
{
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        if (g_IMService == nil) {
            g_IMService = [[QIMService alloc] init];
        }	
    });
    return g_IMService;
}
- (id)init {
    if (self = [super init]) {
        _registerNoticationArray = [[NSMutableArray alloc] init];
         dispatch_async(dispatch_get_main_queue(), ^{
            CFRunLoopObserverContext context = {0, self, NULL, NULL, NULL};
            CFRunLoopObserverRef observer;
            if ([[MSFImagePool defaultPool] deviceVersion] == DeviceiPhoneLater) {
                observer = CFRunLoopObserverCreate(kCFAllocatorDefault, kCFRunLoopAllActivities, YES, 0, &notificationObserverCallBack, &context);
            } else {
                observer = CFRunLoopObserverCreate(kCFAllocatorDefault, kCFRunLoopBeforeWaiting, YES, 0, &notificationObserverCallBack, &context);
            }
            // here give me the waring: CFRunLoopAddObserver(CFRunLoopGetCurrent(), observer, kCFRunLoopDefaultMode); memory dynamically allocated to observer by call to CFRunLoopObserverCreate() at line 122, column 28 is not reachable after line 125, column 13
        });
    }
    return self;
}
```
origin code here... static usage, maybe it's not the memory leak instance ?so how can i do for this?

**Comment by dulmarod** [comment]
Could you please explain to me better what is the problem?
Normally, observer needs to be released with CFRelease(observer), that's what Infer is pointing out. 
I don't think that that changes if the variable is static, but maybe I'm wrong. 
If you are not sure, you could just add CFRelease(observer) in the place where Infer gives the warning to be on the safe side.

**Comment by GeekMin** [comment]
Normally, giving the warning there is right...
but here, g_IMService is treated as "singleton", so the coder wanna the observer alive along with my process ... so see it as the false-positive, am I right?

**Comment by dulmarod** [comment]
I checked with an expert and he said that, yes, you are right that because you are using a singleton there won't be a leak. So you can leave your code unchanged, but from the static analyser's perspective, you cannot know that init will only be called in that context. If you extend your program with a non-static call to init, then there will be a leak. So Infer is correct here to report the leak.
