### ISSUE TITLE
Bug in format string arguments checker in Java

### ISSUE THREAD

**Issue by shekyan** [facebook/infer#1050]
A format string containing left justification `"%-30s"` produces an error `CHECKERS_PRINTF_ARGS
  format string arguments don't mach provided arguments in printf(...)` on a `printf` call, e.g.
```java
String format = "%-30s";
System.out.printf(format, "a");
```

**Comment by martintrojer** [comment]
Hello, thanks for the report.

We have disabled this checker recently, so its unmaintained I'm afraid. 

PRs accepted :)
