### ISSUE TITLE
Get statistics from verification engine

### ISSUE THREAD

**Issue by slight-code** [facebook/infer#1051]
Is there any way to get the statistical data of verification processes from verification engine directly (e.g. verified procedures ) or turn infer into a sound verification tool?

BTW: How can I run infer on SPEC CPU 2000 whose building system is customized with a wrapper called runspec? It seems "--force-integration" doesn't work.

**Comment by jeremydubreil** [comment]
@slight-code, what kind of analysis are you interested in having the list of verified procedure?

**Comment by jeremydubreil** [comment]
> BTW: How can I run infer on SPEC CPU 2000 whose building system is customized with a wrapper called runspec? It seems "--force-integration" doesn't work.

Infer does not support third party build systems but we will happy to help with PRs adding this kind of integration.
