### ISSUE TITLE
Provide basic navigational WebUI

### ISSUE THREAD

**Issue by XVilka** [facebook/infer#1057]
Something like Coverity

![image](https://user-images.githubusercontent.com/203261/52122598-77c9b580-265e-11e9-909a-ea94d1404a66.png)

**Comment by jvillard** [comment]
Hi @XVilka. We're not planning on providing such an advanced UI from within Infer at the moment. Infer exports the analysis results as a json file which can be consumed by an external UI if one were to build one. There's also a `--pmd-xml` option to get an XML file in PMD's format for tools that already handle that format.
