### ISSUE TITLE
infer run -- mvn clean compile failed

### ISSUE THREAD

**Issue by polaris16** [facebook/infer#1063]
I‘ve installed infer on my mac, the infer version is v0.15.0.

I used "mvn compile" to compile the project successfully.

[INFO] Scanning for projects...
[INFO]
[INFO] -------------------< com.qding.sample:webmvc-dubbo >--------------------
[INFO] Building webmvc-dubbo 1.0-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ webmvc-dubbo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ webmvc-dubbo ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /Users/admin/IdeaProjects/webmvc-dubbo/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.824 s
[INFO] Finished at: 2019-02-21T15:02:31+08:00
[INFO] ------------------------------------------------------------------------

When running "infer run -- mvn clean compile", it failed.

Error while running epilogue "restoring Maven's pom.xml to its original state":
(Unix.Unix_error "No such file or directory" rename
 "((src /Users/admin/IdeaProjects/webmvc-dubbo/pom.xml.infer-orig) (dst /Users/admin/IdeaProjects/webmvc-dubbo/pom.xml))").
Powering through...

**Comment by martintrojer** [comment]
Does it work without the 'clean'?

**Comment by martintrojer** [comment]
Assuming this is now solved.
