### ISSUE TITLE
Issue in installing infer from docker in Linux

### ISSUE THREAD

**Issue by chethanursp** [facebook/infer#1064]
Getting error in installing infer in Linux using docker.
I am following the steps mentioned in this link - https://fbinfer.com/docs/getting-started.html

Infer version - 0.14.0
OS - Linux in Vm ware virtual machine
 Commands I executed : 
wget -O Dockerfile https://github.com/facebook/infer/blob/master/docker/0.14.0/Dockerfile
 wget -O run.sh https://github.com/facebook/infer/blob/master/docker/0.14.0/run.sh
sh run.sh

Output:
chethanp@ubuntu:~/infer$ sh run.sh 
run.sh: 8: run.sh: Syntax error: newline unexpected

I have attached the run.sh file.
 
Please help me in installing infer in Linux with docker.
[run.txt](https://github.com/facebook/infer/files/2892689/run.txt)

**Comment by chethanursp** [comment]
And when I executed the actual script by copying it from github directly - https://github.com/facebook/infer/blob/master/docker/0.14.0/run.sh

I am getting below error:
chethanp@ubuntu:~/infer$ sh run.sh 
Sending build context to Docker daemon  69.12kB
Error response from daemon: Dockerfile parse error line 7: unknown instruction: <!DOCTYPE

**Comment by rompic** [comment]
you most likely did not store the "raw" version of your link but saved a html site.
https://raw.githubusercontent.com/facebook/infer/master/docker/0.14.0/run.sh

open your run.sh file in an editor.

**Comment by martintrojer** [comment]
Assuming this is now solved.
