### ISSUE TITLE
Infer run failed: fails to link __inline functions in c

### ISSUE THREAD

**Issue by rovinyu** [facebook/infer#1065]
- infer --version:
    Infer version v0.15.0
    Copyright 2009 - present Facebook. All Rights Reserved.
- Operation System:
    16.04.1-Ubuntu
- It's c project, command to run is:
    infer run -- make
- Output [Compiling is OK, but it fails to link. Actually "hqPutMutexEnter" and "hqPutMutexLeave" are __inline functions in hqueue.c.  If I remove "__inline" key words, the link is also OK. ]
gcc -g -o onvifserver -L./openssl/lib/linux -L./libical/lib/linux   bm/word_analyse.o bm/util.o bm/sys_os.o bm/sys_log.o bm/sys_buf.o bm/ppstack.o bm/base64.o bm/sha1.o bm/linked_list.o bm/hqueue.o bm/rfc_md5.o bm/xml_node.o bm/hxml.o http/http_srv.o http/http_auth.o http/http_parse.o http/http_cln.o http/httpd.o onvif/soap.o onvif/onvif_probe.o onvif/onvif_pkt.o onvif/onvif.o onvif/soap_parser.o onvif/onvif_doorcontrol.o onvif/onvif_device.o onvif/onvif_timer.o onvif/onvif_event.o onvif/onvif_api.o onvif/onvif_ptz.o onvif/onvif_utils.o onvif/onvif_media.o onvif/onvif_image.o onvif/onvif_cm.o onvif/onvif_recording.o onvif/onvif_analytics.o onvif/onvif_cfg.o onvif/onvif_deviceio.o onvif/onvif_media2.o onvif/onvif_thermal.o onvif/onvif_credential.o onvif/onvif_accessrules.o onvif/onvif_schedule.o onvif/onvif_receiver.o main.o  -lpthread -ldl
bm/hqueue.o: In function `hqBufPut':
/home/rovinyu/code/happytimesoft/onvifserver/OnvifServer/bm/hqueue.c:103: undefined reference to `hqPutMutexEnter'
/home/rovinyu/code/happytimesoft/onvifserver/OnvifServer/bm/hqueue.c:119: undefined reference to `hqPutMutexLeave'
/home/rovinyu/code/happytimesoft/onvifserver/OnvifServer/bm/hqueue.c:126: undefined reference to `hqPutMutexLeave'
/home/rovinyu/code/happytimesoft/onvifserver/OnvifServer/bm/hqueue.c:141: undefined reference to `hqPutMutexLeave'
bm/hqueue.o: In function `hqBufPutPtrWait':
/home/rovinyu/code/happytimesoft/onvifserver/OnvifServer/bm/hqueue.c:263: undefined reference to `hqPutMutexEnter'
/home/rovinyu/code/happytimesoft/onvifserver/OnvifServer/bm/hqueue.c:279: undefined reference to `hqPutMutexLeave'
/home/rovinyu/code/happytimesoft/onvifserver/OnvifServer/bm/hqueue.c:285: undefined reference to `hqPutMutexLeave'
bm/hqueue.o: In function `hqBufPutPtrWaitPost':
/home/rovinyu/code/happytimesoft/onvifserver/OnvifServer/bm/hqueue.c:309: undefined reference to `hqPutMutexLeave'
Error: the following clang command did not run successfully:
    /usr/bin/ld -z relro --hash-style=gnu --eh-frame-hdr -m elf_x86_64
    -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o onvifserver
    /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../x86_64-linux-gnu/crt1.o
    /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../x86_64-linux-gnu/crti.o
    /usr/lib/gcc/x86_64-linux-gnu/5.4.0/crtbegin.o -L./openssl/lib/linux
    -L./libical/lib/linux -L/usr/lib/gcc/x86_64-linux-gnu/5.4.0
    -L/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../x86_64-linux-gnu
    -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu
    -L/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../..
    -L/opt/infer-linux64-v0.15.0/lib/infer/facebook-clang-plugins/clang/install/bin/../lib
    -L/lib -L/usr/lib bm/word_analyse.o bm/util.o bm/sys_os.o bm/sys_log.o
    bm/sys_buf.o bm/ppstack.o bm/base64.o bm/sha1.o bm/linked_list.o
    bm/hqueue.o bm/rfc_md5.o bm/xml_node.o bm/hxml.o http/http_srv.o
    http/http_auth.o http/http_parse.o http/http_cln.o http/httpd.o
    onvif/soap.o onvif/onvif_probe.o onvif/onvif_pkt.o onvif/onvif.o
    onvif/soap_parser.o onvif/onvif_doorcontrol.o onvif/onvif_device.o
    onvif/onvif_timer.o onvif/onvif_event.o onvif/onvif_api.o
    onvif/onvif_ptz.o onvif/onvif_utils.o onvif/onvif_media.o
    onvif/onvif_image.o onvif/onvif_cm.o onvif/onvif_recording.o
    onvif/onvif_analytics.o onvif/onvif_cfg.o onvif/onvif_deviceio.o
    onvif/onvif_media2.o onvif/onvif_thermal.o onvif/onvif_credential.o
    onvif/onvif_accessrules.o onvif/onvif_schedule.o onvif/onvif_receiver.o
    main.o -lpthread -ldl -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc
    --as-needed -lgcc_s --no-as-needed
    /usr/lib/gcc/x86_64-linux-gnu/5.4.0/crtend.o
    /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../x86_64-linux-gnu/crtn.o

**Comment by rovinyu** [comment]
In the original C code, there are the following format to define inline functions:
__inline void hqPutMutexEnter(HQUEUE * phq)
gcc building is OK.  However, it seems that infer clang has made some optimization for such inline functions which cause linking error. 
Now I made the following modification to prevent optimization:
static __inline void hqPutMutexEnter(HQUEUE * phq)

Now infer run -- make is OK to link the inline functions.  So I close this issue.

**Comment by jvillard** [comment]
Many thanks for your detailed report and the solution!
