### ISSUE TITLE
Can I get the docker image for ubuntu 64 bit machine

### ISSUE THREAD

**Issue by chethanursp** [facebook/infer#1068]
I am having issue building docker image in my ubuntu machine.
If anyone has built docker image, can I get the docker image?
OS version - Ubuntu running in VM ware

**Comment by martintrojer** [comment]
Hi, the dockerfiles live here; https://github.com/facebook/infer/tree/master/docker

Docker images can be found here; https://hub.docker.com/r/infer/infer
