### ISSUE TITLE
[objective-c] Imported file not found by Infer.

### ISSUE THREAD

**Issue by emkou** [facebook/infer#107]
Hello,

I am using infer 0.1.1 , command line tools installed. 
Whatever .m file i try to check I am getting the following warning for whatever the first #import is:

fatal error: 'NSUserDefaults+App.h' file not found
#import "NSUserDefaults+App.h"
        ^
1 error generated.

**Comment by dulmarod** [comment]
Could you give us some more context? Which command are you using? Does your code compiles with that command without the infer -- part?

**Comment by emkou** [comment]
Hello, 

I get this on both installations on my MacBook and MacMini with either of the commands:
infer -- clang -c FILENAME.m
clang -c FILENAME.m

Note, I also tested with 0.2.0 and getting the same error result.

**Comment by dulmarod** [comment]
Do you have XCode and the command line tools installed?

**Comment by jvillard** [comment]
It looks like `NSUserDefaults+App.h` is one of the files of your project, not a system header. Is this correct?

If so, you should add `-Ipath/where/NSUserDefaults+App.h/lives` to your clang command. You will probably need to include multiple directories in the same way. It will be easier to use Infer on your whole project, using a command that successfully builds your project.

**Comment by emkou** [comment]
@jvillard this alls appears with system headers like UIKit or Foundation.h. I agree that the best use here is to build the whole project via the infer command. @dulmarod yes, both xCode and command line tools are installed, Cocoapods is also used within the project.

**Comment by martinoluca** [comment]
Hello @emkou,
As @jvillard said, `NSUserDefaults+App.h` doesn't look like a system header, so I'd proceed as he suggested, by passing to Clang the path where this file lives, using the `-I` argument.

More in general, when `xcodebuild` builds each file of your codebase, it passes to Clang more arguments than just the source filename, and among those there's the `-isysroot` one, which tells Clang where your SDK lives.
For example, your iPhoneSimulator SDK should be located in:
```
`xcode-select -p`/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk
```
try passing `-isysroot <SDK_PATH>` to your Clang command.

**Comment by jvillard** [comment]
@emkou feel free to re-open if you have issues running infer on your code.
