### ISSUE TITLE
Link to project on fb open source website is wrong

### ISSUE THREAD

**Issue by gillyb** [facebook/infer#1070]
I assume this isn't the exact place to report this bug, but I couldn't find a more appropriate place -

The "Website" link on the [facebook opensource website](https://opensource.facebook.com/#android) is wrong, and leads to the website for "Profilo".
I also realised that many other libraries in the Android category have wrong "website" links (they link to different open source projects).

I would've went ahead and fixed this, but ironically enough, the "opensource" website isn't open source itself 😆 

![image](https://user-images.githubusercontent.com/1319502/53948841-64808e80-40d1-11e9-8097-b86dc78b6f3c.png)

**Comment by JoelMarcey** [comment]
This should be fixed now. Nice catch. Thank you!
