### ISSUE TITLE
returned non-zero exit status 2

### ISSUE THREAD

**Issue by since1987** [facebook/infer#108]
the console throws error when I run sudo make -C infer java

**Comment by dulmarod** [comment]
Could you please give us some more details? What is the error?

**Comment by since1987** [comment]
![66394591-4fcc-47a2-a3de-fe8151429991](https://cloud.githubusercontent.com/assets/9626161/8379581/9f5a7eea-1c53-11e5-9b90-fd4d1f310dc8.png)

I have installed opam and Installed the OCaml dependencies successfully,but the terminal throws errors when I executed the 'sudo make -C infer java' command on my mac.I don't understand the meanings of the error,could you give me some suggestions,thank you!

**Comment by jvillard** [comment]
@since1987 do you have a working java install? Please provide the outputs of

```shell
java -version
javac -version
```

Also, you do not need to run `make -C infer java` with `sudo`.

**Comment by since1987** [comment]
![0c30d7e2-3a86-4353-bddd-54f71ce03f77](https://cloud.githubusercontent.com/assets/9626161/8380474/830f5846-1c58-11e5-8e11-db990abc53ce.png)

**Comment by jeremydubreil** [comment]
The issue seems to be when building the models for Java.

@since1987 : what happen if you do not use `sudo`, and just `make -C infer java` ?

**Comment by since1987** [comment]
@jeremydubreil  permission denied.
I deleted my source and did the instructions again,this time also throw error when I execute 'make -C infer java
![aaea8463-3786-46ac-bdec-ff7e8a1eb7e8](https://cloud.githubusercontent.com/assets/9626161/8392568/58ca5454-1d21-11e5-8056-41345dc3e46d.png)
![a01ec9ea-6ae5-445a-b213-49d66dc0c6fb](https://cloud.githubusercontent.com/assets/9626161/8392573/7ec77150-1d21-11e5-8b5b-c465acebd175.png)

**Comment by akotulski** [comment]
@since1987 it looks like you need to adjust permissions in the directory where infer is located.

Regarding compilation errors - are you using non-english locale? If you do, please fetch newest code because https://github.com/facebook/infer/pull/94 might help you.

You could also try using our prebuilt binaries if you just want to try out infer:
https://github.com/facebook/infer/releases

**Comment by jvillard** [comment]
@since1987 is it ok to close this issue or is Infer still not working for you after upgrading?
