### ISSUE TITLE
How to add a custom model for android porject

### ISSUE THREAD

**Issue by liboshi** [facebook/infer#1084]
I would like to add a new model to exclude some NPE issues. 
I tried to add one following the [instructions](https://fbinfer.com/docs/adding-models.html), 

> To create a model for getStatus(), we need to add a class with the name and the same package as for the original method.

create a file infer/models/java/src/com/boush/test/utils/BoushManager.java with the following content:
```java
package com.boush.test.utils;

import com.facebook.infer.builtins.InferBuiltins;
import com.facebook.infer.builtins.InferUndefined;

public class BoushManager {

  public static BoushManager getInstance() {
    Object o = InferUndefined.object_undefined();
    InferBuiltins.assume_allocated(o);
    return (BoushManager)o;
  }
}
```
then recompile infer and analysis again, I found the model which I added doesn't work.

Could you give me some guidance?

Thanks in advance.

**Comment by martintrojer** [comment]
Assuming that you are modelling a function in a library you are using.

'we need to add a class with the name and the same package as for the original method', i.e. i needs to shadow the function you are modelling, or said another way; come earlier in the classpath than the jar file of the library.

**Comment by liboshi** [comment]
> Assuming that you are modelling a function in a library you are using.
> 
> 'we need to add a class with the name and the same package as for the original method', i.e. i needs to shadow the function you are modelling, or said another way; come earlier in the classpath than the jar file of the library.

Thanks for your reply.

When I try to add a method which is defined in one class for **Android** project, for example:
```java
public static BoushManager getInstance(FragmentActivity activity)
```
when I recompile infer, got an error 
> no symbol found for FragmentActivity.

How do I resolve this problem?

Thanks in advance.

**Comment by martintrojer** [comment]
You probably have to include the dependent classes (like the one used in function arguments).
