### ISSUE TITLE
what difference between analyzing a file and a procedure ?

### ISSUE THREAD

**Issue by bmwvvvv** [facebook/infer#1086]
v0.15.0
Fedora 25
infer -g -a checkers --no-filtering -- make
(Using infer to analyze C++ code)

**Comment by martintrojer** [comment]
'--filtering' means "Do not show the experimental and blacklisted issue types"

so '--no-filtering' means show experimental issue types, its mainly a flag used for infer development.

You can filter out files from analysis using the '--changed-files-index' flag.
