### ISSUE TITLE
How much space requirement to build facebook infer?

### ISSUE THREAD

**Issue by KCKH** [facebook/infer#1091]
I try to build facebook infer in Ubuntu 18.04.2 for c analyzers.

I follow instruction in 
https://github.com/facebook/infer/blob/master/INSTALL.md#install-infer-from-source-without-opam

Running ` ./configure --disable-java-analyzers && make` take me hours
And end up no more space to install.
I use vmware and I used **70GB** to run the above comment.
I seem to be like infinite run or I did something wrong.

**How much space do I need?** Thank you

**Comment by jeremydubreil** [comment]
Hi @KCKH 

Do you need to compile Infer locally, or using the binary release would be enough?

**Comment by KCKH** [comment]
Any option which able to run c analyzing. Is there binary release available? Please guide me. thank
