### ISSUE TITLE
brew install infer fails on bwrap but bwrap is installed

### ISSUE THREAD

**Issue by SteveTockey** [facebook/infer#1092]
Running Debian 9 (stretch) on a Pi 2B. bwrap claims to be installed:

pi@raspberrypi:~ $ opam install bwrap
[NOTE] Package bwrap is already installed (current version is 0.1).

However when I then try to install infer:

pi@raspberrypi:~ $ brew install infer
Updating Homebrew...
==> Cloning https://github.com/facebook/infer.git
Updating /home/pi/.cache/Homebrew/infer--git
==> Checking out tag v0.15.0
HEAD is now at 8bda23f... [release] preparing for binary releases
HEAD is now at 8bda23f [release] preparing for binary releases
Entering 'facebook-clang-plugins'
/home/pi/.cache/Homebrew/infer--git/facebook-clang-plugins
==> opam init --no-setup
Last 15 lines from /home/pi/.cache/Homebrew/Logs/infer/01.opam:
2019-04-25 16:05:15 -0700

opam
init
--no-setup

[NOTE] Will configure from built-in defaults.
Checking for available remotes: rsync and local, git, mercurial, darcs. Perfect!
[ERROR] Missing dependencies -- the following commands are required for opam to operate:
  - bwrap: Sandboxing tool bwrap was not found. You should install 'bubblewrap'. See http://opam.ocaml.org/doc/2.0/FAQ.html#Why-opam-asks-me-to-install-bwrap.

READ THIS: https://docs.brew.sh/Troubleshooting

pi@raspberrypi:~ $

Either opam is lying and bwrap is not installed, or bwrap is installed and brew can't find it. What is the next step?

**Comment by jeremydubreil** [comment]
Hi @SteveTockey, 

If you are trying to install Infer with Homebrew, you should not need to install opam. You would only need access opam to compile the code.

Also, we never tested installing Infer on Linux with Homebrew.  

Did you try using the Docker image: https://fbinfer.com/docs/getting-started.html ?

**Comment by SteveTockey** [comment]
Hi @jeremydubreil,
Thanks for looking in to this. It took three tries to find instructions that actually got Docker installed, this is the one that appeared to work:

https://linuxhint.com/install_docker_on_raspbian_os/

However, the sh run.sh script also failed:

#=== ERROR while installing yojson.1.4.1 ======================================#
Sys_error("rm -rf /root/.opam/4.06.1+flambda/lib/yojson: Cannot allocate memory")
Exception:
Reqs_error
 (Process_error
   ("opam install -y ANSITerminal.0.8 atd.1.12.0 atdgen.1.12.0 base.v0.11.0 base64.2.2.0 bin_prot.v0.11.0 biniou.1.2.0 camlp4.4.06+1 camlzip.1.07 cmdliner.1.0.2 conf-aclocal.1.0.0 conf-autoconf.0.1 conf-m4.1 conf-pkg-config.1.0 conf-which.1 configurator.v0.11.0 core.v0.11.0 core_kernel.v0.11.0 cppo.1."... (* string length 1442; truncated *),
   Unix.WEXITED 4)).

*** ERROR: `install_opam_deps` failed
The command '/bin/sh -c OCAML_VERSION=4.06.1+flambda;     cd /infer && ./build-infer.sh --opam-switch $OCAML_VERSION && rm -rf /root/.opam' returned a non-zero code: 1
pi@raspberrypi:~ $ 


This was on a second try while the script was running, here is what it said earlier:

#=== ERROR while installing topkg.0.9.1 =======================================#
Sys_error("rm -rf /root/.opam/4.06.1+flambda/lib/topkg: Cannot allocate memory")

The former state can be restored with:
    opam switch import
"~/.opam/4.06.1+flambda/backup/state-20190327062232.export"
Exception:
Reqs_error
 (Process_error
   ("opam install -y ANSITerminal.0.8 atd.1.12.0 atdgen.1.12.0 base.v0.11.0 base64.2.2.0 bin_prot.v0.11.0 biniou.1.2.0 camlp4.4.06+1 camlzip.1.07 cmdliner.1.0.2 conf-aclocal.1.0.0 conf-autoconf.0.1 conf-m4.1 conf-pkg-config.1.0 conf-which.1 configurator.v0.11.0 core.v0.11.0 core_kernel.v0.11.0 cppo.1."... (* string length 1442; truncated *),
   Unix.WEXITED 4)).

*** `install_opam_deps` failed
*** Updating opam then retrying


So attempting to  go the Docker route is also failing.

**Comment by jeremydubreil** [comment]
There may not be enough memory to install everything on Raspberry Pi. I don't think we ever tested it. Infer is essentially a server side tool normally deployed on the continuous integration infrastructure. For instance, Infer comes with its own version of Clang.

**Comment by SteveTockey** [comment]
Raspberry Pi 2B, 3B, and 3B+ have the most RAM of all Pi's but even that's only 1GB. So it looks like Infer won't be able to run on Raspbian unless a new model Pi comes out with more RAM. So now you know, it has been tested on a Pi and it doesn't work because no Pi has enough RAM. You might want to add that info to the installation instructions. Thanks again for looking into it.

**Comment by jeremydubreil** [comment]
If you are interested in the analysis of Java alone, you may be able to compile Infer from source by disabling the dependency on Clang using: `./build-infer.sh java` 

The instructions are here: https://github.com/facebook/infer/blob/master/INSTALL.md

**Comment by SteveTockey** [comment]
@jeremydubreil Thanks for the response, and apologies for my delayed reply as I was on business travel overseas. I would be happy to at least be able to have Infer check some Java code. Unfortunately that doesn't seem to work either. The git clone command apparently works fine. Beyond that, however, there's a problem. Here is the transcript:

pi@raspberrypi:~ $ git clone https://github.com/facebook/infer.git
Cloning into 'infer'...
remote: Enumerating objects: 190, done.
remote: Counting objects: 100% (190/190), done.
remote: Compressing objects: 100% (148/148), done.
remote: Total 104279 (delta 73), reused 87 (delta 39), pack-reused 104089
Receiving objects: 100% (104279/104279), 94.89 MiB | 3.72 MiB/s, done.
Resolving deltas: 100% (82936/82936), done.
Checking out files: 100% (2900/2900), done.
pi@raspberrypi:~ $ cd infer
pi@raspberrypi:~/infer $ ./build-infer.sh java
initializing opam... 
pi@raspberrypi:~/infer $ sudo make install
Makefile.config:15: Makefile.autoconf: No such file or directory
make: *** No rule to make target 'Makefile.autoconf'.  Stop.


Here is what's in the infer directory:

pi@raspberrypi:~/infer $ ls
autogen.sh          DEFS            facebook-clang-plugins  LICENSE               opam.locked
build-infer.sh      dependencies    FILES.md                m4                    PULL_REQUEST_TEMPLATE.md
CODE_OF_CONDUCT.md  docker          infer                   Makefile              README.md
configure.ac        Dockerfile      INSTALL.md              Makefile.autoconf.in  run.sh
CONTRIBUTING.md     dotbuckversion  install-sh              Makefile.config       scripts
CONTRIBUTORS        examples        ISSUE_TEMPLATE.md       opam                  sledge
