### ISSUE TITLE
Infer timeout on small function

### ISSUE THREAD

**Issue by julienhenry** [facebook/infer#1093]
Minimal example:
```
int dfaanalyze() {
  int *nullable;
  int *firstpos;
  int *lastpos;
  int * buf = 0;

  nullable = malloc(2*sizeof(int));
  firstpos = malloc(2*sizeof(int));
  lastpos = malloc(2*sizeof(int));

  for (int i = 0; i < 3; i++){}
  *buf = 1;

  nullable++;
  firstpos++;
  lastpos++;
}
```
This code has a null-pointer dereference at `*buf = 1`, that Infer should be able to find. Instead, it seems like Infer is timing out, the output contains:
```
FAILURE:SYMOPS TIMEOUT (1101) SYMOPS:1101 
```

- If removing the useless for loop, Infer finds the bug. note that the `i < 3` matters, the bug is actually found when replacing it with `i < 2`.
- The other `int*` pointers are also part of the issue: if we remove any of the operations on these pointers, the bug is found.

Infer version: 0.16.0
OS: Ubuntu 18.04
Command: 
```
infer --debug --print-logs --bufferoverrun --compute-analytics --biabduction --quandary -- make
```

The source code leading to identification of this bug was created using Bug-Injector, see https://arxiv.org/abs/1901.02819.

**Comment by jvillard** [comment]
Thanks for the report. The number of symops the biabduction can do before giving up is configurable with the `--symops-per-iteration` and `--iterations` command-line options (that you can also put in .inferconfig).

For instance, infer finds the bug in both these settings:

```
$ infer --biabduction-only --iterations 2 -- clang -c gh1093.c
$ infer --biabduction-only --symops-per-iteration 2000 -- clang -c gh1093.c
```

Hope that helps! Feel free to reopen if you have more questions.
