### ISSUE TITLE
fatal error while installing on MacOS (10.10.3)

### ISSUE THREAD

**Issue by GlenG1898** [facebook/infer#110]
I follow your "Install.ms" and when I started command "make -C infer" I get the following error:
wctype.c:10:10: fatal error: 'wctype.h' file not found
#include <wctype.h>
         ^
In file included from xlib.cIn file included from :glib.c9::
9:
./infer_builtins.h:./infer_builtins.h9::910::10 : fatal error: fatal error: 'stdlib.h' 'stdlib.h'file  filenot  notfound found

#include <stdlib.h>
#include <stdlib.h>         ^

         ^
In file included from infer_builtins.c:9:
./infer_builtins.h:9:10: fatal error: 'stdlib.h' file not found
In file included from wchar.c#include <stdlib.h>:
9:
         ^
./infer_builtins.h:9:10: In file included from fatal errormath.c: :9:
'stdlib.h' ./infer_builtins.hfile: 9not: 10found: 
fatal error: 'stdlib.h' file not found
#include <stdlib.h>
         ^
#include <stdlib.h>
         ^
In file included from libc_basic.c:25:
./infer_builtins.h:9:10: fatal error: 'stdlib.h' file not found
#include <stdlib.h>
         ^
1 error generated.
1 error generated.
1 error generated.
1 error generated.
make[3]: *** [xlib.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [glib.o] Error 1
make[3]: *** [infer_builtins.o] Error 1
1 error generated.
make[3]: *** [wctype.o] Error 1
1 error generated.
make[3]: *** [wchar.o] Error 1
1 error generated.
make[3]: *** [math.o] Error 1
make[3]: *** [libc_basic.o] Error 1
make[2]: *** [run_infer] Error 2
make[1]: *** [/Users/Gotlib/code/infer-master/infer/models/../lib/specs/c_models] Error 2
make: *** [clang] Error 2

This libelers are present on my MacOs but it says that it can't see it. And also after restarting this command i get a little different error. Every time I start "make -C infer" I get different error lists! Such as: 

In file included from In file included from In file included from xlib.cinfer_builtins.c:wchar.c9::9:
:
9:
./infer_builtins.h./infer_builtins.h::./infer_builtins.h99:::91010:::10  : fatal errorfatal error: : fatal error: 'stdlib.h''stdlib.h'  filefile'stdlib.h'   notnotfile   foundfoundnot 

found
#include <stdlib.h>#include <stdlib.h>#include <stdlib.h>

         ^         ^         ^

In file included from libc_basic.c:25:
./infer_builtins.h:9:10: fatal error: 'stdlib.h' file not found
wctype.c:10:10: fatal error: 'wctype.h' file not found
In file included from math.c:9:
./infer_builtins.h:9:10: fatal error: #include <wctype.h>'stdlib.h'
 file         ^ 
not found
#include <stdlib.h>
         ^
#include <stdlib.h>
         ^
In file included from glib.c:9:
./infer_builtins.h:9:10: fatal error: 'stdlib.h' file not found
#include <stdlib.h>
         ^
1 error generated.
1 error generated.
1 error generated.
1 error generated.
1 error generated.
make[3]: *** [xlib.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [infer_builtins.o] Error 1
make[3]: *** [glib.o] Error 1
make[3]: *** [wctype.o] Error 1
make[3]: *** [wchar.o] Error 1
1 error generated.
1 error generated.
make[3]: *** [libc_basic.o] Error 1

**Comment by jvillard** [comment]
Hi @GlenG1898, try installing the command-line tools with `xcode-select --install`.

**Comment by GlenG1898** [comment]
@jvillard It helps, Thanks!
