### ISSUE TITLE
Incorrect dead store message

### ISSUE THREAD

**Issue by TomMD** [facebook/infer#1104]
N.B.

```
int f(int *arr2)
{
    // The lines that trigger the bug
    const int x = 10;
    int arr[x];

    // Junk that does not reference `x`
    int i; for(i=0;i<10;i++) { arr2[i] = arr[i] = i; }
}
```

And

```
% infer run -- gcc -c infer-bug.c
<snip>

Found 1 issue

infer-bug.c:4: error: DEAD_STORE
  The value written to &x (type int) is never used.
  2.   {
  3.       // The lines that trigger the bug
  4. >     const int x = 10;
  5.       int arr[x];
  6.
```

**Comment by jvillard** [comment]
Thanks for the report, I can reproduce this locally.

**Comment by jvillard** [comment]
One issue with this is that the clang AST makes no mention of `x` during the initialisation of `arr`:

```
    |-DeclStmt 0x621c308 <line:4:5, col:21>
    | `-VarDecl 0x621c288 <col:5, col:19> col:15 used x 'const int' cinit
    |   `-IntegerLiteral 0x621c2e8 <col:19> 'int' 10
    |-DeclStmt 0x621c490 <line:5:5, col:15>
    | `-VarDecl 0x621c430 <col:5, col:14> col:9 used arr 'int [10]'
```

It might be tricky to coax clang into telling us the original expression in that case.

**Comment by Asoto37** [comment]
> One issue with this is that the clang AST makes no mention of `x` during the initialisation of `arr`:
> 
> ```
>     |-DeclStmt 0x621c308 <line:4:5, col:21>
>     | `-VarDecl 0x621c288 <col:5, col:19> col:15 used x 'const int' cinit
>     |   `-IntegerLiteral 0x621c2e8 <col:19> 'int' 10
>     |-DeclStmt 0x621c490 <line:5:5, col:15>
>     | `-VarDecl 0x621c430 <col:5, col:14> col:9 used arr 'int [10]'
> ```
> 
> It might be tricky to coax clang into telling us the original expression in that case.

**Comment by jvillard** [comment]
This is fixed in the current main branch.
