### ISSUE TITLE
Java build problem: javac plugin? javac command line?

### ISSUE THREAD

**Issue by hmijail** [facebook/infer#1105]
This happens when trying to build the Pantheon project (https://github.com/PegaSysEng/pantheon) with Infer.

The error message complains about the `-XepExcludedPaths` flag (used by the ErrorProne gradle plugin), but the shown command line doesn't work anyway because `-sourcepath` receives no files – though maybe that command line is only informative and not actually used internally?

Infer version v0.16.0-d37374dd8 (built from source)

macOS Mojave 10.14.5, java version "1.8.0_51"

Command run: `infer run -- ./gradlew build -x test`

Command output at https://gist.github.com/hmijail/12a3baa0e944a531b635c50c82cb36a2

**Comment by jvillard** [comment]
Thanks for the report. When you built infer were you using Java8 as well? You might want to run `./build-infer.sh` again to make sure. Currently infer is built differently for Java 8 and Java 11.

Note that the gradle integration is very fragile and just parses the verbose output of gradle looking for `javac` commands. It often parses these wrong since they lack escaping in the gradle output.

**Comment by hmijail** [comment]
(After a long time, I managed to get back to this. My original description was wrong, but I'm writing here since it's the same problem; let me know whether to close this and open a new issue.)

Infer version v1.0.0-671d9fa29
javac 11.0.5

When Infer gathers the javac CLI flags into its javac_args.tmp.xxxxx files, it does so by putting each new argument into a new line. But this causes the invokation to fail in the case of -Xplugin flags, since those need to be on the same line, as shown in the [ErrorProne plugin instructions](http://errorprone.info/docs/installation#command-line).

So, for example, this works:
```
javac ... \
'-Xplugin:ErrorProne  -Xep:EqualsGetClass:OFF' \
myfile.java
```

But this fails with `error: invalid flag: -Xep:EqualsGetClass:OFF`
```
javac ... \
-Xplugin:ErrorProne \
-Xep:EqualsGetClass:OFF \
myfile.java
```

**Comment by hmijail** [comment]
Closing because this same issue is better explained at  #1404.
