### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by NameOfSelf** [facebook/infer#1106]
- I can't figure out what's wrong with my option. Is anyone have the same problem?

 Information:
- [Version ] 0.15.0
- [Mac OS] 10.13.6 (17G65)
- [Xcode] Version 10.1 (10B61)
- [Command ] infer --keep-going --no-xcpretty -- xcodebuild -workspace emake.xcworkspace -scheme emake -configuration Debug -sdk iphonesimulator
- [Log] Capturing in xcodebuild mode...
Traceback (most recent call last):
  File "/usr/local/Cellar/infer/0.15.0/lib/infer/infer/bin/../lib/python/infer.py", line 203, in <module>
    main()
  File "/usr/local/Cellar/infer/0.15.0/lib/infer/infer/bin/../lib/python/infer.py", line 133, in main
    initial_args = initial_argparser.parse_args(to_parse)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1701, in parse_args
    args, argv = self.parse_known_args(args, namespace)
TypeError: 'NoneType' object is not iterable
Internal Error:   /usr/local/Cellar/infer/0.15.0/lib/infer/infer/bin/../lib/python/infer.py
  -j 8 --project-root /Users/guwei/Desktop/易智造工业品 --out
  /Users/guwei/Desktop/易智造工业品/infer-out -- xcodebuild -workspace
  emake.xcworkspace -scheme emake -configuration Debug -sdk iphonesimulator:
  exited with code 1
Error backtrace:
Raised at file "base/Die.ml" (inlined), line 25, characters 6-36
Called from file "base/Logging.ml", line 314, characters 58-80
Called from file "integration/Driver.ml", line 159, characters 2-16
Called from file "integration/Driver.ml", line 280, characters 6-420
Called from file "infer.ml", line 20, characters 2-36
Called from file "infer.ml", line 130, characters 8-54

**Comment by NameOfSelf** [comment]
> * I can't figure out what's wrong with my option. Is anyone have the same problem?
> 
> Information:
> 
> * [Version ] 0.15.0
> * [Mac OS] 10.13.6 (17G65)
> * [Xcode] Version 10.1 (10B61)
> * [Command ] infer --keep-going --no-xcpretty -- xcodebuild -workspace emake.xcworkspace -scheme emake -configuration Debug -sdk iphonesimulator
> * [Log] Capturing in xcodebuild mode...
>   Traceback (most recent call last):
>   File "/usr/local/Cellar/infer/0.15.0/lib/infer/infer/bin/../lib/python/infer.py", line 203, in 
>   main()
>   File "/usr/local/Cellar/infer/0.15.0/lib/infer/infer/bin/../lib/python/infer.py", line 133, in main
>   initial_args = initial_argparser.parse_args(to_parse)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1701, in parse_args
>   args, argv = self.parse_known_args(args, namespace)
>   TypeError: 'NoneType' object is not iterable
>   Internal Error:   /usr/local/Cellar/infer/0.15.0/lib/infer/infer/bin/../lib/python/infer.py
>   -j 8 --project-root /Users/guwei/Desktop/易智造工业品 --out
>   /Users/guwei/Desktop/易智造工业品/infer-out -- xcodebuild -workspace
>   emake.xcworkspace -scheme emake -configuration Debug -sdk iphonesimulator:
>   exited with code 1
>   Error backtrace:
>   Raised at file "base/Die.ml" (inlined), line 25, characters 6-36
>   Called from file "base/Logging.ml", line 314, characters 58-80
>   Called from file "integration/Driver.ml", line 159, characters 2-16
>   Called from file "integration/Driver.ml", line 280, characters 6-420
>   Called from file "infer.ml", line 20, characters 2-36
>   Called from file "infer.ml", line 130, characters 8-54

**Comment by NameOfSelf** [comment]
[Log.txt](https://github.com/facebook/infer/files/3231028/Log.txt)

**Comment by jvillard** [comment]
Sorry for the delay. I don't know why you get this error but the recommended way to analyse xcodebuild projects is via a compilation database, see https://fbinfer.com/docs/analyzing-apps-or-projects.html#xcodebuild

**Comment by jvillard** [comment]
Please re-open if you still experience issues running infer on your code.
