### ISSUE TITLE
Potential memory leaks in a file.

### ISSUE THREAD

**Issue by farziengineer** [facebook/infer#1107]
https://github.com/facebook/infer/blob/89040bee1c53f2fe67edb70717561fb370202502/infer/tests/codetoanalyze/cpp/shared/constructors/constructor_new.cpp#L27-L30

https://github.com/facebook/infer/blob/89040bee1c53f2fe67edb70717561fb370202502/infer/tests/codetoanalyze/cpp/shared/constructors/constructor_new.cpp#L32-L35

https://github.com/facebook/infer/blob/89040bee1c53f2fe67edb70717561fb370202502/infer/tests/codetoanalyze/cpp/shared/constructors/constructor_new.cpp#L37-L40

Not sure how often is this file used, but are these not  cases of potential Memory Leaks. Why are we creating pointer to the objects. Can we replace them with. 
```python
type variable_name(initial_value);
```
@jberdine

**Comment by jvillard** [comment]
These are tests meant to specifically test that infer understands the behaviour of `new()`. It doesn't matter that they are creating potential memory leaks.
