### ISSUE TITLE
"Failed to run InferAnalyze binary, exiting" in 0.2.0

### ISSUE THREAD

**Issue by Anakros** [facebook/infer#111]
OS X 10.10.3

Steps to reproduce:

1. download 0.2.0 release
2. extract it using tar
3. run infer without arguments `$ ./infer-linux64-v0.2.0/infer/infer/bin/infer`
4. got `Failed to run InferAnalyze binary, exiting`

When I tried to execute `bin/InferAnalyze`, I got `zsh: exec format error: ./infer-linux64-v0.2.0/infer/infer/bin/InferAnalyze`

**Comment by jvillard** [comment]
You're trying to run the Linux version from MacOS. Download the tarball for MacOS [here](https://github.com/facebook/infer/releases/latest/).

**Comment by Anakros** [comment]
@jvillard Yes, just noticed it. Sorry.

**Comment by jvillard** [comment]
@Anakros no worries, I just commented in case someone else gets the same error and ends up here :)

**Comment by forhot2000** [comment]
there are no MacOS version to download.

**Comment by liunuer** [comment]
Is there no MacOS version? But  I can see how to config in install.md. I want use ii in Mac

**Comment by kingangelTOT** [comment]
download infer-osx-v0.3.0.tar.xz 
/Users/kingangeltot/Downloads/infer-osx-v0.3.0/infer/bin/infer

and get Failed to run InferAnalyze binary, exiting

**Comment by IgorGanapolsky** [comment]
Any solution for this error.  I am still getting it on MacOS.

**Comment by YechengZhou** [comment]
any solution? I meet the same issue on MacOS and Mac release package

**Comment by jvillard** [comment]
For the record, the solution usually is to follow the instructions in the [Getting Started page](http://fbinfer.com/docs/getting-started.html). Please open a new issue if that doesn't work for you. Thanks!
