### ISSUE TITLE
Uninitialized memory (C) [bug] [false negative]

### ISSUE THREAD

**Issue by Isweet** [facebook/infer#1112]
Please make sure your issue is not addressed in the [FAQ](http://fbinfer.com/support.html#troubleshooting).

Please include the following information:
- The version of infer from `infer --version`.

```
Infer version v0.15.0
Copyright 2009 - present Facebook. All Rights Reserved.
```

- Your operating system and version, for example "Debian 9", "MacOS High Sierra", whether you are using Docker, etc.

```
OS: Ubuntu 18.04 LTS x86_64 
Host: Precision 7530 
Kernel: 4.15.0-1038-oem 
Uptime: 10 days, 3 hours, 27 mins 
Packages: 2464 
Shell: bash 4.4.19 
Resolution: 3240x5760, 3840x2160 
WM: i3 
Theme: Adwaita [GTK3] 
Icons: Adwaita [GTK3] 
Terminal: gnome-terminal 
CPU: Intel Xeon E-2176M (12) @ 4.400GHz 
GPU: Intel Integrated Graphics 
GPU: NVIDIA NVIDIA Corporation Device 1cbb 
Memory: 5576MiB / 64182MiB
```
- Which command you ran, for example `infer -- make`.

```
infer --no-filtering -- gcc -c main.c
```
- The full output in a paste, for instance a [gist](https://gist.github.com/).

```
Capturing in make/cc mode...
Found 1 source file to analyze in /home/ian/Projects/scratch/uninit/infer-out
Starting analysis...

legend:
  "F" analyzing a file
  "." analyzing a procedure

F.
  No issues found  
```

- If possible, a minimal example to reproduce your problem (for instance, some code where
    infer reports incorrectly, together with the way you run infer to reproduce the incorrect
    report).

```
$ cat main.c
int bad() {
  int x;
  int y = x + 2;
  return y;
}
```

**Comment by jvillard** [comment]
Thanks for the report. I can reproduce the issue locally.
