### ISSUE TITLE
infer: error while loading shared libraries

### ISSUE THREAD

**Issue by congtmbg** [facebook/infer#1116]
Please make sure your issue is not addressed in the [FAQ](http://fbinfer.com/support.html#troubleshooting).

Please include the following information:
- [ ] The version of infer from `infer --version`.
- [ ] Your operating system and version, for example "Debian 9", "MacOS High Sierra", whether you are using Docker, etc.
- [ ] Which command you ran, for example `infer -- make`.
- [ ] The full output in a paste, for instance a [gist](https://gist.github.com/).
- [ ] If possible, a minimal example to reproduce your problem (for instance, some code where
    infer reports incorrectly, together with the way you run infer to reproduce the incorrect
    report).

**Comment by congtmbg** [comment]
Dear every body,
I'm using Infer version 0.16.0 from https://github.com/facebook/infer/releases/tag/v0.16.0,file infer-linux64-v0.16.0.tar.xz .
I got file ans extract file to 1 folder on pc (ubuntu 16.04). And use "infer" run file in /home/cong/Desktop/infer-linux64-v0.16.0/bin.
But:
$ infer --version
infer: error while loading shared libraries: liboptpoly.so: cannot open shared object file: No such file or directory
Can you please tell me to fix that bug?
Thanks.

**Comment by jvillard** [comment]
Can you paste the result of `ldd /home/cong/Desktop/infer-linux64-v0.16.0/bin/infer`?

**Comment by congtmbg** [comment]
Dear jvillard,
1. I fixed that bugs, because i have to path (that bugs by me, sorry about that):
/home/cong/Desktop/infer-linux64-v0.16.0/bin
After that: ./infer --version, it is ok.
/*command*/
cong@cong-Inspiron-3470:~/Desktop/infer-linux64-v0.16.0/bin$ ./infer --version
Infer version v0.16.0
Copyright 2009 - present Facebook. All Rights Reserved.
cong@cong-Inspiron-3470:~/Desktop/infer-linux64-v0.16.0/bin$ 

2. I have just run command "infer run"
cong@cong-Inspiron-3470:~/Desktop/infer-linux64-v0.16.0/bin$ ./infer run -- clang -c /home/cong/Desktop/testmakefile_hello/hello/hello.c
Capturing in make/cc mode...
Found 1 source file to analyze in /home/cong/Desktop/infer-linux64-v0.16.0/bin/infer-out
...
I know that file "hello.c" compiled to object file .o.

3. "Facebook infer" have to compile files, after that "Facebook infer" analysis static source code .c,.h....
Is it true?
Have any way  "Facebook infer" needn't compile files,but "Facebook infer" analysis static source code?
As cppcheck tool:
http://cppcheck.sourceforge.net/
4. Further more, i want ask you:
"Facebook infer" can check all files .c , .h in a folder (include sub folder), can't it?
How to export .html  (bugs reports) in"Facebook infer"?
Can you tell me that command example to do that, please?
Thank you so much!

**Comment by jvillard** [comment]
> 3.
Correct, infer needs to compile the source code to analyse it. That's because it uses clang to parse source code.

> 4. "Facebook infer" can check all files .c , .h in a folder (include sub folder), can't it?

Yes, have a look at https://fbinfer.com/docs/analyzing-apps-or-projects.html

> 4.  How to export .html (bugs reports) in"Facebook infer"?

After `infer run ...` you can run `infer explore --html`.

**Comment by congtmbg** [comment]
> > 
> 
> Correct, infer needs to compile the source code to analyse it. That's because it uses clang to parse source code.
> 
> > 1. "Facebook infer" can check all files .c , .h in a folder (include sub folder), can't it?
> 
> Yes, have a look at https://fbinfer.com/docs/analyzing-apps-or-projects.html
> 
> > 1. How to export .html (bugs reports) in"Facebook infer"?
> 
> After `infer run ...` you can run `infer explore --html`.

Thank you.
If I have any problems, i need your helps! I hope you can help me.

**Comment by jvillard** [comment]
Happy to help! Closing the issue since it seems resolved.
