### ISSUE TITLE
Needs support for C++ project which is cross-compiled by CMake/GCC targeting 32bit arm platform...

### ISSUE THREAD

**Issue by chenzx** [facebook/infer#1117]
Env: Ubuntu 16, Infer latest, 0.16

Problem: I need to do infer analysis on a cross-compile C/C++ 32bit arm project, here is what i do:
1. The project uses CMake and GCC for cross-compiling, needs set 2 pats: rootfs, and cross-compile's path
2. Since CMake generates 32bit ARM cross-compiling Makefile, i need to to do a maunal fix:
2.1 add -D__ARM_PCS_VFP
2.2 add some -Ixxx to cross-compiler's internal include paths
3. generate a compilation database json then use infer

However there is something wrong here: i have done the same tricks and use clang-tidy from LLVM-8.0 latest, and it works ok, but when i use Infer-0.16 which uses LLVM-7.0 internally, something error happened:

```
In file included from .../prebuilts/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/5.3.1/climits:41:
In file included from .../rootfs/usr/include/limits.h:123:
In file included from /opt/infer-linux64-v0.16.0/lib/infer/facebook-clang-plugins/clang/install/lib/clang/7.0.1/include/limits.h:37:
/usr/include/limits.h:145:5: error: function-like macro '__GLIBC_USE' is not defined
#if __GLIBC_USE (IEC_60559_BFP_EXT)
    ^
```

The original CMake is for a GCC cross-compiling settings, how can i migrate to a Clang compile environment?

**Comment by jvillard** [comment]
Using one compiler toolchain (infer's) to compile a project that expects another compiler toolchain (your 32bit arm project) is often difficult. I don't know of a good systematic way to solve this issue, and the particular error in your issue is unknown to me. I would search for the errors you get on the web and try and patch the compilation commands on the fly to make them work with infer's clang, that's usually what we end up doing when needed.

**Comment by chenzx** [comment]
@jvillard you can see from the err msg above, that Infer incorrectly uses its internal "infer/facebook-clang-plugins/clang/install/lib/clang/7.0.1/include/limits.h", this is wierd, for in cross-compiling case, i have specify all the header files at command line options...

maybe i'll divide the task into 2 parts, first is to make the gcc-cross-compileable project to clang-compileable(but not linkable)? this may require a new custome CMakeLists.txt? then use infer... I'll have a try.

**Comment by jvillard** [comment]
>  Infer incorrectly uses its internal "infer/facebook-clang-plugins/clang/install/lib/clang/7.0.1/include/limits.h", this is wierd, for in cross-compiling case, i have specify all the header files at command line options...

Infer's clang will naturally use its own clang runtime. You could try to make it not do that with some combination of `-isystem` and/or `-internal-isystem` and/or `-resource-dir`, but to be honest I've never quite succeeded in changing its mind...

**Comment by chenzx** [comment]
@jvillard

1.  Maybe this is an old llvm-7.0 related bug?
2. Or, if use clang-tidy tool, will not depend on clang's own runtime?

But maybe i'm doing it wrong, i should use `-isystem` to indicate system headers, not use normal -I<path>

I'm puzzling what system headers mean. There are 3 potential explainations in cross-compiling scenarios: compiler's builtin headers, or libc++? or OS-platform specific includes?

**Comment by jvillard** [comment]
You can test 1. by building infer's current master from source as it uses clang-8.0 now. Maybe that will help.

**Comment by chenzx** [comment]
i have solved this problem by first  port project source code to clang x64 compile, then run infer.

**Comment by jvillard** [comment]
Thanks for the update!
