### ISSUE TITLE
Why Infer can't automated modeling?

### ISSUE THREAD

**Issue by dreaminplus** [facebook/infer#1121]
Up to now, when I meet with some library method that Infer built-in does not have, I have to create model manually, could I create some automated modeling method? Like Android/Spring boot, If it can be realized, I can detect issues in advance instead of afterwards?

**Comment by ngorogiannis** [comment]
The desired modelled behaviour is dependent on the analyser, so I don't think that part can be automated. 

For dispatch (procedure name matching) there is a lot of functionality in various places such as the [`ProcnameDispatcher`](https://github.com/facebook/infer/blob/master/infer/src/IR/ProcnameDispatcher.mli).

**Comment by dreaminplus** [comment]
Hmmm, like null dereference/resource leak/sql injection etc, before given the special pattern, maybe they can automated modeling? A bit Like [https://github.com/spotbugs/spotbugs/blob/master/spotbugs/src/main/java/edu/umd/cs/findbugs/detect/BuildUnconditionalParamDerefDatabase.java](url) .. they can be cached for further use...

**Comment by ngorogiannis** [comment]
We don't have any current plans for this. Feel free to re-open if necessary or have a pull request.
