### ISSUE TITLE
Homebrew tap for infer

### ISSUE THREAD

**Issue by Amar1729** [facebook/infer#1129]
Please make sure your issue is not addressed in the [FAQ](http://fbinfer.com/support.html#troubleshooting).

Please include the following information:
- [x] The version of infer from `infer --version`.
- [x] Your operating system and version, for example "Debian 9", "MacOS High Sierra", whether you are using Docker, etc.
- [ ] Which command you ran, for example `infer -- make`.
- [ ] The full output in a paste, for instance a [gist](https://gist.github.com/).
- [ ] If possible, a minimal example to reproduce your problem (for instance, some code where
    infer reports incorrectly, together with the way you run infer to reproduce the incorrect
    report).

Managed to make a homebrew formula and build bottles for infer 0.17.0 and facebook clang 8.0.0 here:
- https://github.com/Amar1729/homebrew-formulae/blob/69e164cd825387aaa9af28b70dd081202edf1961/infer.rb
- https://github.com/Amar1729/homebrew-formulae/blob/69e164cd825387aaa9af28b70dd081202edf1961/fb-clang.rb

You can install from my tap with `brew install infer`, which will install `infer 0.17.0`. I would recommend this organization hosting a tap itself rather than relying on mine, since I might easily miss releases of infer or fb clang. 

I wrote fb-clang as its own separate formula so that it can be prebuit as a bottle, speeding up compilation time of the infer build. It could also allow for adding a `head` directive to the formula so people can install with `brew install --HEAD infer`. Since `--HEAD` builds are built by the end user they would only have to wait ~15m instead of an hour and a half for compiling clang too.

This is mostly meant for reference (although it works). You could hosting it instead as, for example, `facebook/homebrew-infer`. Hosting as a tap rather than in brew-core allows you to not have to deal with figuring out how to patch opam to avoid an x11 dependency (and fix the other related problems that makes the build too complex for brew-core).

You hosting it could also help clear up the build process for clang and infer a bit, or just standardize the installation for people on darwin.  
- One possible improvement that may help is allowing an optional `--prefix` argument for clang's `./setup.sh` script to specify an install directory
  - current workaround to use a custom CLANG_PREFIX, since exporting CLANG_PREFIX by itself doesn't seem to work by itself:
```
    ENV["CLANG_PREFIX"] = Formula["fb-clang"].opt_prefix.to_s
    system "facebook-clang-plugins/clang/setup.sh", "-r"
    system "ln", "-s", ENV["CLANG_PREFIX"], "./facebook-clang-plugins/clang/install"
```

Going to @jvillard since I saw he contributed the original infer formula in homebrew.

**Comment by Amar1729** [comment]
I also noticed that during build of facebook clang, configure looks for certain ocaml libraries to setup ocaml support. That's why I'm using the `opam` and `opam.locked` files from infer to build clang, but it's a bit of a dirty workaround since I'm not sure which ocaml dependencies are needed.

**Comment by Amar1729** [comment]
I also just realized this prebuilt `fb-clang` does NOT run `strip` like the `setup.sh` for clang does. That could be updated too.

**Comment by Amar1729** [comment]
Updated revisions to be a bit more size efficient:  
- [infer](https://github.com/Amar1729/homebrew-formulae/blob/9e84fceb3bf3d8ff375895359341429524c84044/infer.rb)
- [fb-clang](https://github.com/Amar1729/homebrew-formulae/blob/9e84fceb3bf3d8ff375895359341429524c84044/fb-clang.rb)

**Comment by Amar1729** [comment]
@jvillard any word on including this as a `facebook/` repo? If that's not feasible, I can instead host these formula in a more specific `homebrew-infer` tap for people to easily install 0.17.0 from (if running at least Mojave).

**Comment by jvillard** [comment]
Thanks a lot for this, I think hosting this on your end is the right move for now. I still hope we can get a working formula for Homebrew but haven't had the time to look further into it as of late.

**Comment by Amar1729** [comment]
Sounds good.

I moved the repo to here: https://github.com/Amar1729/homebrew-infer

And I can make a PR updating the installation guidelines for macOS

**Comment by Amar1729** [comment]
Well @jvillard looks like my efforts were for naught - someone actually managed to fix up the infer formula in Homebrew-core and get it working properly (there have been a lot of efforts to look at old formulae with the python 3.8 bump in Homebrew over the last month).

https://github.com/Homebrew/homebrew-core/pull/47007

So I know we just updated the install instructions, but they can now just say `brew install infer` like they used to

**Comment by Amar1729** [comment]
Closed; homebrew has a working `infer` again.

#1217
