### ISSUE TITLE
 [ERROR] Error during capture phase, exiting when i run "infer -- gradle build"

### ISSUE THREAD

**Issue by sukeshsalian** [facebook/infer#113]
[INFO] Running command /Users/sukesh/Documents/infer-osx-v0.2.0/infer/infer/bin/infer -- gradle build
[INFO] Path to infer script /Users/sukesh/Documents/infer-osx-v0.2.0/infer/infer/bin/infer (/Users/sukesh/Documents/infer-osx-v0.2.0/infer/infer/bin/infer)
[INFO] Infer version v0.2.0
Copyright 2009 - present Facebook. All Rights Reserved.

[INFO] Platform: Darwin-14.3.0-x86_64-i386-64bit
[INFO] PATH=/Users/sukesh/Library/Android/sdk/tools/:/Users/sukesh/Library/Android/sdk/platform-tools:/Users/sukesh/.rbenv/shims:/Users/sukesh/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/sukesh/Documents/gradle-2.4/bin:/Users/sukesh/Documents/infer-osx-v0.2.0/infer/infer/bin:/Users/sukesh/.rvm/bin
[INFO] SHELL=/bin/bash
[INFO] PWD=/Users/sukesh/housing.android.mainnew
[INFO] Running with:

------------------------------------------------------------
Gradle 2.4
------------------------------------------------------------

Build time:   2015-05-05 08:09:24 UTC
Build number: none
Revision:     5c9c3bc20ca1c281ac7972643f1e2d190f2c943c

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.4 compiled on April 29 2014
JVM:          1.7.0_79 (Oracle Corporation 24.79-b02)
OS:           Mac OS X 10.10.3 x86_64

[ERROR] Error during capture phase, exiting

**Comment by mdelapenya** [comment]
Same happened to me using ANT:

```
infer --incremental --ant compile
```

I found a workaround executing clean before compile:

```
infer --incremental --ant clean compile
```

**Comment by mdelapenya** [comment]
I've just read the docs: http://fbinfer.com/docs/infer-workflow.html, where it's said:
```
Make sure your project is clean when you first run Infer on it (with make clean, or gradle clean, or ...).
```

**Comment by solome** [comment]
@mdelapenya you are right, need `gradle clean` first.

**Comment by jvillard** [comment]
@sukeshsalian can you try again with the latest version of Infer, and paste the contents of `infer-out/toplevel.log` somewhere?

**Comment by jvillard** [comment]
I'm assuming the problem has been solved, but please re-open this issue if this is not the case.
