### ISSUE TITLE
v0.15.0 exited with code 65

### ISSUE THREAD

**Issue by yuanqiuqian** [facebook/infer#1144]
Please make sure your issue is not addressed in the [FAQ](http://fbinfer.com/support.html#troubleshooting).

Please include the following information:
- [x] Infer version v0.15.0.
- [x] MacOS High Sierra
- [x] `xcodebuild clean -workspace appName.xcworkspace -scheme appName`
`infer run --keep-going --no-xcpretty -- xcodebuild -workspace appName.xcworkspace -scheme appName -configuration Release`
- [x] `*** clang: Caught sigint, time to die
error: unable to open dependencies file (/Users/xx/Library/Developer/Xcode/DerivedData/appName-cnukubqcgvoukggbfraplzcuhnzy/Build/Intermediates.noindex/appName.build/Release-iphoneos/appName.build/Objects-normal/armv7/IProtectionDetailTabView.d)Command CompileC emitted errors but did not return a nonzero exit code to indicate failure

** BUILD FAILED **

` 
`  exited with code 65
Error backtrace:
Raised at file "base/Die.ml" (inlined), line 25, characters 6-36
Called from file "base/Logging.ml", line 314, characters 58-80
Called from file "integration/Driver.ml", line 159, characters 2-16
Called from file "integration/Driver.ml", line 280, characters 6-420
Called from file "infer.ml", line 20, characters 2-36
Called from file "infer.ml", line 130, characters 8-54
`

**Comment by ngorogiannis** [comment]
Could you try 0.17.0?  There've been quite a few updates to the clang pipeline since 0.15.

**Comment by yuanqiuqian** [comment]
> Could you try 0.17.0? There've been quite a few updates to the clang pipeline since 0.15.

changed to 0.17.0, the error log is also changed.
`*** clang: Caught sigint, time to die
ERROR RUNNING CAPTURE: Uncaught Internal Error: (Sys_error "Bad file descriptor")
Error backtrace:
Raised by primitive operation at file "stdlib.ml", line 364, characters 7-40
Called from file "base/Logging.ml" (inlined), line 67, characters 8-41
Called from file "base/Logging.ml", line 73, characters 4-30
Called from file "format.ml" (inlined), line 287, characters 31-72
Called from file "format.ml", line 347, characters 4-28
Called from file "format.ml", line 477, characters 6-72
Called from file "format.ml", line 484, characters 6-24
Called from file "format.ml", line 1276, characters 4-20
Called from file "format.ml", line 1337, characters 20-38
Called from file "base/Utils.ml" (inlined), line 224, characters 13-22
Called from file "base/Utils.ml" (inlined), line 166, characters 8-12
Called from file "base/Utils.ml", line 226, characters 2-40
Re-raised at file "istd/IExn.ml", line 13, characters 2-50
Called from file "base/Utils.ml" (inlined), line 168, characters 6-141
Called from file "base/Utils.ml", line 226, characters 2-40
Called from file "clang/Capture.ml", line 139, characters 8-78
Called from file "clang/Capture.ml" (inlined), line 152, characters 15-43
Called from file "clang/Capture.ml" (inlined), line 174, characters 2-37
Called from file "clang/Capture.ml", line 204, characters 8-138
Called from file "clang/ClangWrapper.ml" (inlined), line 178, characters 15-45
Called from file "list.ml" (inlined), line 106, characters 12-15
Called from file "list.ml" (inlined), line 104, characters 13-64
Called from file "src/list0.ml" (inlined), line 26, characters 40-75
Called from file "clang/ClangWrapper.ml", line 178, characters 2-54
Called from file "integration/Driver.ml" (inlined), line 323, characters 2-29
Called from file "integration/Driver.ml", line 328, characters 62-89
Called from file "base/Utils.ml", line 398, characters 16-20
Called from file "scuba/ScubaLogging.ml", line 66, characters 29-44
Called from file "infer.ml", line 25, characters 6-40
Called from file "base/Utils.ml", line 166, characters 8-12
Re-raised at file "istd/IExn.ml", line 13, characters 2-50
Called from file "base/Utils.ml", line 168, characters 6-141
Called from file "base/Utils.ml", line 176, characters 16-54
Called from file "base/Utils.ml", line 398, characters 16-20
Called from file "scuba/ScubaLogging.ml", line 66, characters 29-44
Called from file "infer.ml" (inlined), line 31, characters 22-94
Called from file "infer.ml", line 149, characters 8-54

Bi_inbuf.End_of_input54350: Error while running epilogue "flushing logs and closing log file":
(Sys_error "Bad file descriptor").
Powering through...
Command CompileC failed with a nonzero exit code
`

**Comment by qzlh521** [comment]
I have the same error!

**Comment by Amar1729** [comment]
How did you build/install 0.17?  
At a glance the issue looks similar to [this one](https://github.com/facebook/infer/issues/1081#issuecomment-487512452)

**Comment by jvillard** [comment]
Please re-open with more details as per @Amar1729's question.
