### ISSUE TITLE
[Objective-C] [false-positive]?? buffer malloc-ed return null or malloc(0)

### ISSUE THREAD

**Issue by GeekMin** [facebook/infer#115]
```
@autoreleasepool {
// warning here: memory dynamically allocated by call to malloc() at pos A is not reachable after ***
    ...    
    Byte* buffer = (Byte*)malloc(length);    // pos A
    if (buffer == NULL || length == 0)   
        break;
   ...
}
```
when malloc-call returns null or malloc(0), should I invoke the free() call? My coder do not think so.. so false-positive produced here.~

**Comment by dulmarod** [comment]
When malloc returns null you don't need to invoke free(). However, I cannot reproduce what is the problem just based on your snippet of code. Could you paste a bit bigger snippet of code, so that I can see why Infer is reporting a leak there? Also, could you mention in which line is Infer reporting the leak?

**Comment by GeekMin** [comment]
a-ha... I think the question is here:
1. when malloc-ed length is zero, we need manually free the "malloc(0)" memory? IF malloc(0), system wont allocate the memory, free is non-necessary.. so maybe we think Infer gives the false-positive... ?
2. But in reality, finally, I think my coder's problem is here: bcoz now Infer do not have a very deep defect guideline to guide the programmer why defect here..  Below, skip the second branch, MEMORY_LEAK will happened?
```
do
                {
                    //原图
                    NSData *imageData = nil;
                    QINT64 length = [presentation size];
                    Byte*  buffer = (Byte*)malloc(length);
                    if (buffer == NULL || length == 0)
                    {
                        break;
                    }
                    
                    NSError* error = nil;
                    QINT64 readBytes = [presentation getBytes:buffer fromOffset:0 length:length error:&error];
                    if (error != nil || readBytes != length)
                    {
                        free(buffer);
                        break;
                    }
                    
                    imageData = [NSData dataWithBytesNoCopy:buffer length:length];
                    if ([imageData writeToFile:filePath atomically:YES] == NO)
                    {
                        break;
                    }
                    
                    //缩略图
                    NSString * thumbPath = [[self getThumbFolder] stringByAppendingString:[filePath GetFileShortName]];
                    if (![fileManager fileExistsAtPath:thumbPath])
                    {
                        fileMd5 = [SmartDeviceMsgCenter getFileMd5: filePath];
                        [self createThumbImageActual: filePath md5: fileMd5];
                    }
                }while (0);
```

**Comment by dulmarod** [comment]
In the man of malloc says: "If size is 0, then malloc() returns either NULL, or a unique pointer value that can later be successfully passed to free()." 

It looks like what you get from malloc(0) is implementation dependent, and it is always safe to pass that result to free. See http://stackoverflow.com/questions/8808303/c-freeing-malloc0.

Infer is complaining on that case, when length is 0. So yes, in that case you should call free to be on the safe side.

**Comment by GeekMin** [comment]
but not considering this point, in the following code, if not entering the second branch[ if (error**)], the buffer still not be freed~? From this point, Infer should give the warning, but as u know, the tool do do not give a whole issue roadmap(not like clang), I think the current error message may make the programmer being misunderstooooood?  Like here:
```
@autoreleasepool { // memory .....by call to malloc at pos A is not reachable after current line..
do
{
    Byte*  buffer = (Byte*)malloc(length);  // pos A
    if (buffer == NULL || length == 0)
    {
        break;
    }
    ...
    QINT64 readBytes = [presentation getBytes:buffer fromOffset:0 length:length error:&error];
    if (error != nil || readBytes != length)
    {
        free(buffer);
        break;
    }
    imageData = [NSData dataWithBytesNoCopy:buffer length:length];
    if ([imageData writeToFile:filePath atomically:YES] == NO)
    {
        break;
    }
    ...
}while (0);
}
```

**Comment by dulmarod** [comment]
The message of Infer is only part of the information it provides. There is also an error trace where it shows you the path that lead to the error. You could try using the command inferTraceBugs to see the trace.

**Comment by GeekMin** [comment]
I indeed manually parsed the report.json (equals to interTraceBugs -o report_json_dir), but I do not think the information is enough for me ~ like what I have said in the above post~

**Comment by dulmarod** [comment]
OK, thanks for the feedback. We'll take it into account.
