### ISSUE TITLE
fbinfer.com contains outdated information about registering checkers

### ISSUE THREAD

**Issue by Vetii** [facebook/infer#1152]
I am not certain this repo is the right to report to for issues with the documentation website, but I did not find a repo for the website. Apologies if this is not the right place!

I am trying to implement a simple checker, using the article [Simple intraprocedural checkers](https://fbinfer.com/docs/adding-checkers.html).

The article recommends to look at the file `infer/src/checkers.ml`, and to register the checker in `infer/src/checkers.mli`.

These two files have been deleted in the commit `4f54fabf`. 

The documentation also recommends looking at the file `infer/src/IR/Sil.rei`, which has been deleted in commit `bab3d91c`. I assume one should look at `/infer/src/IR/Sil.ml` instead.

- Infer version: v0.14.0

**Comment by jvillard** [comment]
Thanks for the report, we are in the process of updating our documentation in a way that would hopefully prevent it going out of date in the future.

This is the right place to report documentation issues as the website is actually taken from the gh-pages branch of this repo: https://github.com/facebook/infer/tree/gh-pages

**Comment by jvillard** [comment]
I've fixed the most glaring issues in that page but I think the [lab](https://github.com/facebook/infer/blob/master/infer/src/labs/README.md) is a better and more up to date source of documentation on how to write your own checker. We have some consolidating of documentation to do, stay tuned.
