### ISSUE TITLE
Getting Clang AST failed with Infer

### ISSUE THREAD

**Issue by qqbzg** [facebook/infer#1155]
Please make sure your issue is not addressed in the [FAQ](http://fbinfer.com/support.html#troubleshooting).

Please include the following information:
- [x] The version of infer from `infer --version`.

Infer version v0.17.0-807cc727b
Copyright 2009 - present Facebook. All Rights Reserved.

- [x] Your operating system and version, for example "Debian 9", "MacOS High Sierra", whether you are using Docker, etc.

MacOS High Sierra

- [x] Which command you ran, for example `infer -- make`.

I followed the official document of Infer, after running——
> **infer --debug -- clang -c hello.m** 
I got **hello.m.ast.sh**, then I run
> **bash hello.m.ast.sh**
it failed with the following output

- [x] The full output in a paste, for instance a [gist](https://gist.github.com/).

hello.m.ast.sh: line 3: bdump: command not found

the content of hello.m.ast.sh:

"/usr/local/lib/infer/facebook-clang-plugins/clang/install/bin/clang-8" "@/var/folders/m2/9__102d10sg0xgw9_bh4y3lr0000gn/T/clang_command_.tmp.7a06bf.txt" \
  > /Users/xxxx/Documents/0711/xxx/xxx/hello.m.ast.biniou
bdump -x -d "/usr/local/lib/infer/infer/bin/../etc/clang_ast.dict" -w '!!DUMMY!!' /Users/xxxx/Documents/0711/xxx/xxx/hello.m.ast.biniou \
  > /Users/xxxx/Documents/0711/xxx/xxx/hello.m.ast.bdump

- [ ] If possible, a minimal example to reproduce your problem (for instance, some code where
    infer reports incorrectly, together with the way you run infer to reproduce the incorrect
    report).

**Comment by jvillard** [comment]
The `bdump` executable is provided by the biniou opam package so you'll need to do `eval $(opam env)` to get it in your `PATH`. I've updated https://fbinfer.com/docs/linters.html#clang_ast to include this information. Thanks for the report!
