### ISSUE TITLE
Fatal error on MacOS Mojave: 'wchar.h' file not found.

### ISSUE THREAD

**Issue by milladgit** [facebook/infer#1157]
When I am trying to use infer on my MacOS Mojave, I get an error saying that it cannot find 'wchar.h' file. 

Here are the information of my environment:

infer version: 1.5
OS: MacOS Mojave - No Docker
Command I used: infer -- g++ f1.cpp     OR       infer -- clang f1.cpp
Full output: [output](https://gist.github.com/milladgit/7285c2251e3b5db9a6da7f36840305ff)
Minimal example to reproduce error: [example](https://gist.github.com/milladgit/d7e9b78b1ec40e148be8a366e2115cdd)

Note: the same thing will happen if I use clang as the compiler too.

**Comment by Amar1729** [comment]
This problem is due to using outdated infer 0.15.0 on Mojave.  
Upgrading to 0.17.0 fixes the problem for me.

**Comment by jvillard** [comment]
Please re-open if upgrading to 0.17.0 didn't fix your issue.
