### ISSUE TITLE
[Objective-C] [false-positive]?? CFReadStreamCopyError return null?

### ISSUE THREAD

**Issue by GeekMin** [facebook/infer#116]
```
- (void) handleStreamError
{
   ...
   NSError *underlyingError = NSMakeCollectable([(NSError*)CFReadStreamCopyError((CFReadStreamRef)[self readStream]) autorelease]);
   // warning here: memory dynamically allocated by call to CFReadStreamCopyError() at * is not reachable after *
   ...
}
```
Here giving me the Memory_Leak warning, How should I do? Is a false-positive?

**Comment by dulmarod** [comment]
Hi,
Thanks for reporting this. This is indeed a false positive. We will look into it.

**Comment by GeekMin** [comment]
@dulmarod: if CFReadStreamCopyError returns null...what will happened?

**Comment by dulmarod** [comment]
The Apple documentation says: "If cf is NULL, this will cause a runtime error and your application will crash."   as a description for CFMakeCollectable: https://developer.apple.com/library/mac/documentation/CoreFoundation/Reference/CFTypeRef/index.html#//apple_ref/c/func/CFMakeCollectable
and NSMakeCollectable is a wrapper around CFMakeCollectable.

So yes, your code doesn't have a leak but if CFReadStreamCopyError returns null, it will crash. You may want to add a check for null there.
