### ISSUE TITLE
exited with code 65  v0.15.0

### ISSUE THREAD

**Issue by chunyunwang** [facebook/infer#1163]
xcpretty 0.3.0
Infer v0.15.0

fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
*** clang++: Caught sigint, time to die
Command /usr/local/Cellar/infer/0.15.0/lib/infer/infer/lib/python/inferlib/../../../lib/wrappers/clang++ emitted errors but did not return a nonzero exit code to indicate failure

** BUILD FAILED **

The following build commands failed:
	CompileC /Users/cmcc/Library/Developer/Xcode/DerivedData/HardwareComponent-czxpznmmeyvosqemlexoksmflqhf/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/UniAppCommon.build/Objects-normal/x86_64/AFHTTPRequestOperationManager+KSAdapterNetWork.o /Users/cmcc/UniAppCommon/UniAppCommon/Classes/HYComponent/CommonComponent/HYNetworkPackage/NetworkAdapter/AFHTTPRequestOperationManager+KSAdapterNetWork.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Internal Error:   /usr/local/Cellar/infer/0.15.0/lib/infer/infer/bin/../lib/python/infer.py
  -j 4 --project-root /Users/cmcc/HardwareComponent/Example --out
  /Users/cmcc/HardwareComponent/Example/infer-out -- xcodebuild build -scheme
  HardwareComponent_Example -workspace HardwareComponent.xcworkspace
  -configuration Debug -sdk iphonesimulator:
  exited with code 65
Error backtrace:
Raised at file "base/Die.ml" (inlined), line 25, characters 6-36
Called from file "base/Logging.ml", line 314, characters 58-80
Called from file "integration/Driver.ml", line 159, characters 2-16
Called from file "integration/Driver.ml", line 280, characters 6-420
Called from file "infer.ml", line 20, characters 2-36
Called from file "infer.ml", line 130, characters 8-54

Any ideas for this？

**Comment by chunyunwang** [comment]
command line : 
xcodebuild clean -scheme HardwareComponent_Example -workspace HardwareComponent.xcworkspace -configuration Debug -sdk iphonesimulator

infer run --keep-going --no-xcpretty -- xcodebuild build -scheme  HardwareComponent_Example -workspace  HardwareComponent.xcworkspace -configuration Debug -sdk iphonesimulator

**Comment by caozhiyong** [comment]
same to you

**Comment by caozhiyong** [comment]
brew reinstall autoconf automake cmake opam pkg-config sqlite gmp mpfr
brew reinstall infer


please try.after this, worked.  I think there was some config changed after update macOS.

**Comment by chunyunwang** [comment]
> brew reinstall autoconf automake cmake opam pkg-config sqlite gmp mpfr
> brew reinstall infer
> 
> please try.after this, worked. I think there was some config changed after update macOS.
> open your fanqiang software.

Thanks ,i will try it!

**Comment by jvillard** [comment]
I hope this worked, closing optimistically. Please re-open if there is still an issue.
