### ISSUE TITLE
infer on RHEL  throws `GLIBCXX_3.4.22' not found

### ISSUE THREAD

**Issue by Raman535** [facebook/infer#1166]
Hi:
I have installed infer tool as suggested below
VERSION=0.XX.Y; \
curl -sSL "https://github.com/facebook/infer/releases/download/v$VERSION/infer-linux64-v$VERSION.tar.xz" \
| sudo tar -C /opt -xJ && \
ln -s "/opt/infer-linux64-v$VERSION/bin/infer" /usr/local/bin/infer

**OS**
bgl-ads-xxx> uname -r
3.10.0-693.11.6.el7.x86_64
bgl-ads-009:95> 

**Sample run:**
bgl-ads-xxx> infer run -- gcc raman.c 
Capturing in make/cc mode...
/opt/infer-linux64-v0.17.0/lib/infer/infer/bin/../../facebook-clang-plugins/clang/install/bin/clang: /lib64/libtinfo.so.5: no version information available (required by /opt/infer-linux64-v0.17.0/lib/infer/infer/bin/../../facebook-clang-plugins/clang/install/bin/clang)
/opt/infer-linux64-v0.17.0/lib/infer/infer/bin/../../facebook-clang-plugins/clang/install/bin/clang: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /opt/infer-linux64-v0.17.0/lib/infer/infer/bin/../../facebook-clang-plugins/clang/install/bin/clang)
/opt/infer-linux64-v0.17.0/lib/infer/infer/bin/../../facebook-clang-plugins/clang/install/bin/clang: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /opt/infer-linux64-v0.17.0/lib/infer/infer/bin/../../facebook-clang-plugins/clang/install/bin/clang)
/opt/infer-linux64-v0.17.0/lib/infer/infer/bin/../../facebook-clang-plugins/clang/install/bin/clang: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /opt/infer-linux64-v0.17.0/lib/infer/infer/bin/../../facebook-clang-plugins/clang/install/bin/clang)
/opt/infer-linux64-v0.17.0/lib/infer/infer/bin/../../facebook-clang-plugins/clang/install/bin/clang: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /opt/infer-linux64-v0.17.0/lib/infer/infer/bin/../../facebook-clang-plugins/clang/install/bin/clang)
External Error: Error executing: /opt/infer-linux64-v0.17.0/lib/infer/infer/bin/../../facebook-clang-plugins/clang/install/bin/clang raman.c
exited with code 1

Error backtrace:
Raised at file "format.ml" (inlined), line 242, characters 35-52
Called from file "format.ml", line 469, characters 8-33
Called from file "format.ml", line 484, characters 6-24
Re-raised at file "base/Die.ml" (inlined), line 26, characters 8-56
Called from file "base/Die.ml", line 30, characters 6-39
Called from file "integration/Driver.ml" (inlined), line 323, characters 2-29
Called from file "integration/Driver.ml", line 328, characters 62-89
Called from file "base/Utils.ml", line 398, characters 16-20
Called from file "scuba/ScubaLogging.ml", line 66, characters 29-44
Called from file "infer.ml", line 20, characters 2-36
Called from file "base/Utils.ml", line 398, characters 16-20
Called from file "scuba/ScubaLogging.ml", line 66, characters 29-44
Called from file "infer.ml" (inlined), line 25, characters 22-94
Called from file "infer.ml", line 137, characters 8-54

Please make sure your issue is not addressed in the [FAQ](http://fbinfer.com/support.html#troubleshooting).

Please include the following information:
- [ ] The version of infer from `infer --version`.
- [ ] Your operating system and version, for example "Debian 9", "MacOS High Sierra", whether you are using Docker, etc.
- [ ] Which command you ran, for example `infer -- make`.
- [ ] The full output in a paste, for instance a [gist](https://gist.github.com/).
- [ ] If possible, a minimal example to reproduce your problem (for instance, some code where
    infer reports incorrectly, together with the way you run infer to reproduce the incorrect
    report).

Thanks,
Raman

**Comment by jvillard** [comment]
Thanks for the report. The binary release cannot cover all distributions so given your error it looks like you will need to compile infer from source instead. Sorry about that. The relevant documentation is in [INSTALL.md](https://github.com/facebook/infer/blob/master/INSTALL.md#install-infer-from-source).
