### ISSUE TITLE
libtinfo.so.5: cannot open shared object file

### ISSUE THREAD

**Issue by NicholasLYang** [facebook/infer#1168]
Please include the following information:
- [x] The version of infer from `infer --version`.
Infer version v0.17.0
- [x] Your operating system and version, for example "Debian 9", "MacOS High Sierra", whether you are using Docker, etc.
Debian 10
- [x] Which command you ran, for example `infer -- make`.
`infer run -- make`
- [x] The full output in a paste, for instance a [gist](https://gist.github.com/).
[gist](https://gist.github.com/NicholasLYang/c8b351fa0e3df1b80df32cecfea1f7a1)
- [ ] If possible, a minimal example to reproduce your problem (for instance, some code where
    infer reports incorrectly, together with the way you run infer to reproduce the incorrect
    report).
This seems to be tied to my environment, not to any specific code.

Whenever I run `infer`, I get this same external error. From some basic searching, `libtinfo.so.5` appears to be tied to ncurses. I do have a `libtinfo.so.6` file which I tried symlinking to `libtinfo.so.5` but it appears that infer requires something called `NCURSES_TINFO_5.0.19991023`. Perhaps infer needs to be updated to libtinfo.so.6?

Thanks,
Nicholas

**Comment by jvillard** [comment]
Unfortunately making portable binaries is basically impossible so it looks like you will need to compile infer from source. Sorry about that. See also this similar issue: https://github.com/facebook/infer/issues/1166#issuecomment-550278347

**Comment by yangpeiyi** [comment]
If anyone is facing the same issue with version 0.17.0 or 1.0.0 - For me (ubuntu) simply installing libtinfo5 worked.
`sudo apt update && sudo apt install -y libtinfo5`

**Comment by danwt** [comment]
> If anyone is facing the same issue with version 0.17.0 or 1.0.0 - For me (ubuntu) simply installing libtinfo5 worked.
> `sudo apt update && sudo apt install -y libtinfo5`
> Got the idea here: [circleci/circleci-images#430](https://github.com/circleci/circleci-images/issues/430)
> I didn't do the soft link, though.

Installing libinfo through apt worked for me (env: vscode remote docker container)

Full command

```

```RUN set -eux; \
    echo "Installing Infer ..."; \
    # https://fbinfer.com/docs/getting-started/
    export DEBIAN_FRONTEND=noninteractive; \
    apt-get -y install --no-install-recommends \
    # https://github.com/facebook/infer/issues/1168#issuecomment-722381509
    libtinfo5 \
    python2.7; \
    DIR=/additional-deps/infer; \
    mkdir -p $DIR; \
    cd $DIR; \
    VERSION=1.0.0; \
    curl -sSL "https://github.com/facebook/infer/releases/download/v$VERSION/infer-linux64-v$VERSION.tar.xz" \
    | sudo tar -C /opt -xJ && \
    ln -s "/opt/infer-linux64-v$VERSION/bin/infer" /usr/local/bin/infer \
    ;
