### ISSUE TITLE
how to report xcodebuild warning.

### ISSUE THREAD

**Issue by helele90** [facebook/infer#1169]
How Can I capture these xcodebuild warning.

<img width="1167" alt="截屏2019-10-2710 06 44" src="https://user-images.githubusercontent.com/4125469/67628504-97b2a080-f8a1-11e9-9745-523f80a431c6.png">

```
warning: pointer is missing a nullability type specifier
      (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
```

<img width="1168" alt="截屏2019-10-2710 07 02" src="https://user-images.githubusercontent.com/4125469/67628506-9aad9100-f8a1-11e9-8be9-ca4eaa996766.png">

```
warning: this function declaration is not a prototype
      [-Wstrict-prototypes]
```

not in the bugs.txt.

Version: Infer version v0.15.0
System: MacOS Catalina
Command: infer run -- xcodebuild -target xxx -configuration Debug -sdk iphonesimulator

**Comment by jvillard** [comment]
Infer does its own analysis that is not the one from xcodebuild, so it reports different issues. You will need to collect the results from xcodebuild and infer separately.
