### ISSUE TITLE
Knobs to tune the analysis

### ISSUE THREAD

**Issue by keowang** [facebook/infer#1176]
Hi,

Can I ask if there are some knobs we can tune the analysis for catching null pointer dereference bugs?

Thanks

**Comment by jvillard** [comment]
There is no generic knob but depending on what you want to achieve there may be useful additional configuration options. Do you have specific examples of what you would want infer to do differently?

**Comment by keowang** [comment]
@jvillard thanks for the reply. We have a codebase that we are not ready to
share yet. Would you mind telling me how can I play with some other
configurations rather than the default?
