### ISSUE TITLE
[Clang Static Analyzer]  vs. [Infer] : osx.cocoa.RetainCount (ObjC) && NilArg && NonNullParamChecker && NullDereferenced

### ISSUE THREAD

**Issue by GeekMin** [facebook/infer#118]
I do some experiment  between "Infer" and "Clang Static Analyzer", theoretically, Clang has some corresponding rules, like these: 
```
{
osx.cocoa.RetainCount   <-> MEMORY_LEAK
(Simple)StreamChecker   <-> RESOURCE_LEAK
NilArg, NonNullParamChecker and NullDereferenced etc. <-> Nil | Null related Checker
}
```
but, in practice, the result is very different,  the result A that Clang has checked out is very different from the result B that Infer has checked out..... I think, though, they have the same starting-point(maybe here called defect pattern), but they really have different results.... A--ha--: Sounds, seemingly, very interesting...

I am sorry, till now, I do not have good knowledge to dive into the Infer or Clang source code... If I would do that, maybe I can explain to myself..so till now, I cannot...
Could you explain something about this~ or provide some places that I can have a good understanding about this point~

PS:
different result reasons that I think now:
1. different analyze-principles(one using simple AST or CFG, one using deep inter-inter-procedural)
2. different coverage (like cf method set..)
3. different starting-point(maybe Infer just wanna be the complement for the Clang [ do not rebuild the wheels? ] 
Thanks first, my bro or ~~

**Comment by dulmarod** [comment]
There are some docs on our website about how Infer compares to the CSA: http://fbinfer.com/support.html#faq

Moreover, there are other documents about how Infer works internally: 
http://fbinfer.com/docs/separation-logic-and-bi-abduction.html

You could take a look at those.

**Comment by ddino** [comment]
hi GeemMin,

Your question is interesting and it does not have a definite answer. But let me give you a bit of context.

Static analysis is an undecidable problem, therefore there are no algorithmic methods that can solve it perfectly for every instance. For this theoretical reason, all static analysis tools are obliged to use some heuristic algorithms trying to find an approximate solution to the problem.  Heuristics are imprecise 
therefore all existing static analyzers are imprecise. They work well in some programs and less well in others. 
That said, every static analyzer has its own heuristic and internal engine and therefore they will always
be differences in their results. One will find something and another wiill find something else. 
Sometimes two different analyzers find the same bug. But there is no general rule that can tell you 
who can find what. In general we can only make predictions. 
So even if on the surface two different analyzers say that they find the same category of bugs 
(for example null pointer dereference) in reality, their heuristic normally would fire in different situations.
For this  reason many large companies employing static analysis use more than one  analyzer on the same code to discover the same category of bugs.

A good article comparing different existing analyzers is the following:
http://www.jhuapl.edu/techdigest/TD/td3202/32_02-Pendergrass-Lee.pdf

I hope this helps!

**Comment by GeekMin** [comment]
@ddino thanks for you, of course, including @dulmarod's reply..But, another question introduced..  @ddino could u give me some examples to explain  "for example null pointer dereference", till I know,  I think Coverity do the most npe check.. findbugs analyzed result mostly is just its subset .. so “ For this reason many large companies employing static analysis use more than one analyzer on the same code to discover the same category of bugs.“ Like NPE，generally， using which which tools~?
I wanna get more feeling about the static analysis specially for "NPE"
