### ISSUE TITLE
Clang 9 support

### ISSUE THREAD

**Issue by panava** [facebook/infer#1184]
Is there any plan of making infer working with clang version 9? The reason I am asking this is because I would like to run infer on C code which runs on the atmega644 microcontroller, currently supported by clang 9-- however infer works with clang 8.

**Comment by martintrojer** [comment]
Hi, yes we are currently looking into clang9 support.

**Comment by martintrojer** [comment]
infer master is now on clang9.

**Comment by FlyingNoob** [comment]
> Hi, yes we are currently looking into clang9 support.

but infer master build error with object-c.
'Makefile.autoconf: No such file or directory'
