### ISSUE TITLE
FAILURE: Build failed with an exception

### ISSUE THREAD

**Issue by don59** [facebook/infer#119]
don@PC003-Ubuntu:~/workspace/BangBang-Android$ infer -- gradle build
	14:41:44.934 [ERROR] [org.gradle.BuildExceptionReporter] 
	14:41:44.937 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
	14:41:44.938 [ERROR] [org.gradle.BuildExceptionReporter] 
	14:41:44.938 [ERROR] [org.gradle.BuildExceptionReporter] * Where:
	14:41:44.939 [ERROR] [org.gradle.BuildExceptionReporter] Build file '/home/don/workspace/BangBang-Android/build.gradle' line: 13
	14:41:44.939 [ERROR] [org.gradle.BuildExceptionReporter] 
	14:41:44.940 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
	14:41:44.940 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred evaluating root project 'BangBang-Android'.
	14:41:44.940 [ERROR] [org.gradle.BuildExceptionReporter] > Could not find method jcenter() for arguments [] on repository container.
	14:41:44.943 [ERROR] [org.gradle.BuildExceptionReporter] 
	14:41:44.943 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
	14:41:44.944 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'BangBang-Android'.
	14:41:44.945 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:54)
	14:41:44.946 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:127)
	14:41:44.946 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.BuildScriptProcessor.evaluate(BuildScriptProcessor.java:38)
	14:41:44.947 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:43)
	14:41:44.947 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:466)
	14:41:44.947 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:77)
	14:41:44.948 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.ProjectEvaluationConfigurer.execute(ProjectEvaluationConfigurer.java:23)
	14:41:44.948 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.ProjectEvaluationConfigurer.execute(ProjectEvaluationConfigurer.java:21)
	14:41:44.949 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.Actions$CompositeAction.execute(Actions.java:78)
	14:41:44.949 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.Actions$TransformingActionAdapter.execute(Actions.java:130)
	14:41:44.949 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.AbstractProject.configure(AbstractProject.java:442)
	14:41:44.950 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.AbstractProject.allprojects(AbstractProject.java:437)
	14:41:44.950 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:40)
	14:41:44.951 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:142)
	14:41:44.951 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:113)
	14:41:44.952 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:81)
	14:41:44.952 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:38)
	14:41:44.953 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessGradleLauncherActionExecuter.execute(InProcessGradleLauncherActionExecuter.java:39)
	14:41:44.953 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessGradleLauncherActionExecuter.execute(InProcessGradleLauncherActionExecuter.java:25)
	14:41:44.954 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:50)
	14:41:44.954 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
	14:41:44.954 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:201)
	14:41:44.955 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:174)
	14:41:44.955 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:170)
	14:41:44.956 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:139)
	14:41:44.956 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	14:41:44.956 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	14:41:44.957 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.Main.doAction(Main.java:48)
	14:41:44.957 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	14:41:44.957 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.Main.main(Main.java:39)
	14:41:44.957 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:50)
	14:41:44.958 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:32)
	14:41:44.958 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.GradleMain.main(GradleMain.java:26)
	14:41:44.958 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.gradle.api.internal.MissingMethodException: Could not find method jcenter() for arguments [] on repository container.
	14:41:44.959 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:68)
	14:41:44.959 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:56)
	14:41:44.959 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:172)
	14:41:44.960 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler_Decorated.invokeMethod(Unknown Source)
	14:41:44.960 [ERROR] [org.gradle.BuildExceptionReporter]        at build_3ldp8p6lcjp6utl7tuaf6qp56v$_run_closure1_closure2.doCall(/home/don/workspace/BangBang-Android/build.gradle:13)
	14:41:44.960 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:58)
	14:41:44.961 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:133)
	14:41:44.961 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:113)
	14:41:44.961 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.DefaultArtifactRepositoryContainer.configure(DefaultArtifactRepositoryContainer.java:76)
	14:41:44.962 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.DefaultArtifactRepositoryContainer.configure(DefaultArtifactRepositoryContainer.java:44)
	14:41:44.962 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:50)
	14:41:44.962 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:133)
	14:41:44.963 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:94)
	14:41:44.963 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.AbstractProject.repositories(AbstractProject.java:889)
	14:41:44.963 [ERROR] [org.gradle.BuildExceptionReporter]        at build_3ldp8p6lcjp6utl7tuaf6qp56v$_run_closure1.doCall(/home/don/workspace/BangBang-Android/build.gradle:12)
	14:41:44.963 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:58)
	14:41:44.964 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:133)
	14:41:44.964 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:94)
	14:41:44.964 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.AbstractProject.configure(AbstractProject.java:874)
	14:41:44.965 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.AbstractProject.configure(AbstractProject.java:879)
	14:41:44.965 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.AbstractProject.allprojects(AbstractProject.java:866)
	14:41:44.965 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:216)
	14:41:44.966 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:122)
	14:41:44.966 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:147)
	14:41:44.966 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:83)
	14:41:44.967 [ERROR] [org.gradle.BuildExceptionReporter]        at build_3ldp8p6lcjp6utl7tuaf6qp56v.run(/home/don/workspace/BangBang-Android/build.gradle:11)
	14:41:44.967 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
	14:41:44.967 [ERROR] [org.gradle.BuildExceptionReporter]        ... 32 more
	14:41:44.968 [ERROR] [org.gradle.BuildExceptionReporter] 

There is build.gradle

	// Top-level build file where you can add configuration options common to all sub-projects/modules.
	buildscript {
	    repositories {
		mavenCentral()
	    }
	    dependencies {
		classpath 'com.android.tools.build:gradle:1.1.0'
		classpath 'com.github.dcendents:android-maven-plugin:1.2'
	    }
	}
	allprojects {
	    repositories {
		jcenter()
	    }
	}

**Comment by jvillard** [comment]
Hi @don59, does `gradle build` work on its own?

You need gradle version at least 1.7 for this build script (check with `gradle -version`).

**Comment by sblackshear** [comment]
Feel free to re-open if this builds with gradle, but not with Infer.
