### ISSUE TITLE
infer export with --html have no result 

### ISSUE THREAD

**Issue by lichanghong** [facebook/infer#1197]
xcodebuild 
how can I convert bugs.txt to bugs.html   ?
I have find 'finfer --html ' option, but have no effect.

**Comment by jvillard** [comment]
It's an option of `infer explore`, you can run `infer explore --html` after the analysis to generate the HTML report.

I agree that it is confusing and `infer --html -- xcodebuild ..` should also produce the HTML report. I'd very much welcome a PR to do that.

**Comment by lichanghong** [comment]
> explore

thank you for your help
