### ISSUE TITLE
RacerD: suppress reports on specific fields

### ISSUE THREAD

**Issue by mkruber** [facebook/infer#1199]
In Infer-0.17.0, when running RacerD, violations are being reported on fields (e.g., statistics) where the exact value is not expected. There is a `@ThreadSafe(enableChecks=false)` annotation for a method. Is there something available for annotating fields similarly?

**Comment by ngorogiannis** [comment]
> In Infer-0.17.0, when running RacerD, violations are being reported on fields (e.g., statistics) where the exact value is not expected. There is a @ThreadSafe(enableChecks=false) annotation for a method. Is there something available for annotating fields similarly?

I don't understand the first sentence.  If you are after an annotation that will hide all accesses to a specific field from RacerD, there is the `@ThreadConfined` annotation (which typically means that all accesses to that field happen on a single thread).

**Comment by mkruber** [comment]
As you point out, `@ThreadConfined` means that accesses happen on a single thread. However, there are instances where the field is accessed by multiple threads and there is a race among accesses. However, I want to discard such races as the cost of introducing synchronization is higher and the field value is not expected to be precise. In such cases, the `@ThreadConfined` annotation will be inappropriate even though it will suppress the race. Is there a different annotation, (e.g., similar to `@Threadsafe(enableChecks=false)` for methods) that can work on fields?

**Comment by ngorogiannis** [comment]
I see -- we don't have another annotation for that I'm afraid.  Marking the field `volatile` will also silence all reports, though that isn't just a syntactic change anymore.

**Comment by mkruber** [comment]
Thanks. Marking the field `volatile` will still introduce additional costs.
