### ISSUE TITLE
Library not found 

### ISSUE THREAD

**Issue by justvanbloom** [facebook/infer#12]
Please integrate .xcworkspace so dynamic librarys also loaded .. 
e.g. pods .. since there are nice pods out there

**Comment by yurikoles** [comment]
`infer -- xcodebuild -workspace AppName.xcworkspace -scheme AppName  -configuration Debug -sdk iphonesimulator`

**Comment by louiseyang** [comment]
I use `xcodebuild -workspace AppName.xcworkspace -scheme AppName -configuration Debug -sdk iphonesimulator` returns `** BUILD SUCCEEDED **`

But `infer -- xcodebuild -workspace AppName.xcworkspace -scheme AppName -configuration Debug -sdk iphonesimulator` returns 
```
/Users/louise/workspace/ios/Pods/pop/pop/POPVector.h:13:10: fatal error: 'iostream' file not found
#include <iostream>
         ^
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/louise/Library/Developer/Xcode/DerivedData/App-gqzswdekjpuqdcdldgboeqbvbprd/Build/Intermediates/Pods.build/Debug-iphoneos/Pods-pop.build/Objects-normal/armv7/POPAnimatableProperty.o pop/pop/POPAnimatableProperty.mm normal armv7 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

**Comment by Elmundo** [comment]
I tried out simple example of Infer;
`infer -- clang -c Hello.m`

and got this error.

    Hello.m:1:9: fatal error: 'Foundation/Foundation.h' file not found
    #import <Foundation/Foundation.h>
            ^
    1 error generated.

**Comment by martinoluca** [comment]
@Elmundo That example is meant to be executed on a Mac with Xcode installed (with the command line tools) and the iOS SDK.

**Comment by Elmundo** [comment]
i got a Mac which has Xcode installed with its command line tools and iOS SDK also. 

    Bariss-MacBook-Air:examples barisyilmaz$ xcode-select -p
    /Applications/Xcode.app/Contents/Developer
    Bariss-MacBook-Air:examples barisyilmaz$ gcc
    clang: error: no input files
    Bariss-MacBook-Air:examples barisyilmaz$ 

Still got this error.

**Comment by martinoluca** [comment]
@Elmundo what happens if you just run `clang -c Hello.m` does it work?

**Comment by Elmundo** [comment]
@martinoluca Just warnings, no error.

    $ clang -c Hello.m
    Hello.m:4:1: warning: no 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed
          [-Wobjc-property-no-attribute]
    @property NSString* s;
    ^
    Hello.m:4:1: warning: default property attribute 'assign' not appropriate for non-GC object
          [-Wobjc-property-no-attribute]
    2 warnings generated.

**Comment by markohlebar** [comment]
Hey @Elmundo, @martinoluca, I had the same issue...
Reinstalling command line tools has fixed it for me. 
I'm running OSX 10.11 (15A178w), and command line tools for Xcode 6.3.2. 
Xcode 7 beta command line tools break this in a completely different way for me.
