### ISSUE TITLE
Can infer analyze embedded C source code without attaching to a build?

### ISSUE THREAD

**Issue by p-ranav** [facebook/infer#1201]
I have an embedded C repository that I would like to analyze but I don't have a build system or cross-compiler setup. Can `infer` perform static code analysis of this source code without requiring a build?

**Comment by dulmarod** [comment]
No, Infer's analysis requires a build system integration because it takes the AST of the program from the compiler.

**Comment by p-ranav** [comment]
Okay! Thanks for your response. Closing this issue.
