### ISSUE TITLE
No rule to make target "install-with-libs"

### ISSUE THREAD

**Issue by XVilka** [facebook/infer#1207]
Running the same docker file as in https://github.com/facebook/infer/issues/1194 but based on the https://github.com/facebook/infer/commit/598a4d5a5579a92bf51ee5cad5dbe5a36edfa2d0

Please include the following information:
- [x] The version of infer is this commit https://github.com/facebook/infer/commit/598a4d5a5579a92bf51ee5cad5dbe5a36edfa2d0
- [x] Debian 10 "Buster" docker Slim
- [x] Building infer
  
![image](https://user-images.githubusercontent.com/203261/71354155-02d4d680-25b6-11ea-8fc0-77ceeeafa941.png)

**Comment by skcho** [comment]
Hello @XVilka. I will fix the docker build script. Thank you for reporting this.

The target `install-with-libs` has been removed 387ef518f995d7bd0254b3cf70c143eab891b10a, which was to install shared objects. For now, it should be good to run `make install` instead.

**Comment by XVilka** [comment]
Can be closed now, thanks!
