### ISSUE TITLE
Takes for ever on android repo

### ISSUE THREAD

**Issue by startthread** [facebook/infer#121]
It took me 10 hrs for 3241 files to be analyzed for an android repo, is this normal or am i missing something

**Comment by jeremydubreil** [comment]
@startthread: sounds like a lot of time indeed. Which build system are you using ?

**Comment by startthread** [comment]
I am using gradle wrapper to build

**Comment by jvillard** [comment]
Is the issue still present in the latest version of Infer? Maybe we can add some logging to Infer to narrow down the issue to eg a particular file or class in your project.

**Comment by sblackshear** [comment]
Please re-open if you are still experiencing this with the latest release.
