### ISSUE TITLE
Crash on C code with offsetof() builtin

### ISSUE THREAD

**Issue by thedrow** [facebook/infer#1212]
Please make sure your issue is not addressed in the [FAQ](http://fbinfer.com/support.html#troubleshooting).

Please include the following information:
- [x] The version of infer from `infer --version`: 0.17.0
- [x] Your operating system and version, for example "Debian 9", "MacOS High Sierra", whether you are using Docker, etc.: Ubuntu 18.04. No docker.
- [x] Which command you ran, for example `infer -- make`:
```
./autogen.sh
./configure
infer run -- make
```
- [x] The full output in a paste, for instance a [gist](https://gist.github.com/): https://gist.github.com/thedrow/8eb1e4782a26d6088bfc198424f02c1c
- [x] If possible, a minimal example to reproduce your problem (for instance, some code where
    infer reports incorrectly, together with the way you run infer to reproduce the incorrect
    report).

```
git clone https://git.kernel.org/pub/scm/utils/util-linux/util-linux.git
git checkout eae8661e686ebcb06ec60c1a6bb1616aaef88257
./autogen.sh
./configure
infer run -- make
```

**Comment by XVilka** [comment]
Looks very similar (at the the stackdump) to https://github.com/facebook/infer/issues/1178

**Comment by thedrow** [comment]
Yes it is similar although yours is longer.
Maybe util-linux exposes the problem earlier.

**Comment by artempyanykh** [comment]
Hi @thedrow. Thanks for reporting! 
Looks like our clang plugin chokes on `atari.c:209`:
```
    offsetof(struct atari_rootsector, part[i]),
```

It [expects an integer constant](https://github.com/facebook/facebook-clang-plugins/blob/master/libtooling/ASTExporter.h#L3647) while in fact it is
```
__builtin_offsetof(type, identifier(.identifier|[expr])*)
```

Let me see what I can do.

**Comment by XVilka** [comment]
@artempyanykh in that radare2 bug there is also an offsetof usage:

https://github.com/radareorg/radare2/blob/master/libr/debug/p/native/linux/linux_debug.c#L998

```
(void *)r_offsetof (struct user, u_debugreg[i]), 0);
```
which is defined as `#define r_offsetof(type, member) offsetof(type, member)`
So I think it is the same bug effectively.

**Comment by thedrow** [comment]
If you'd like to close this as a duplicate, feel free to do so.

**Comment by artempyanykh** [comment]
@XVilka yes, seems so. 
@thedrow I'll keep this one open since we already got some discussion here.

**Comment by XVilka** [comment]
Are there any updates on this issue? Nearly half of C projects I tried make use of the `offsetof(type, member)` construct.

BTW, maybe it's better to rename the title into something like "Crash on C code with offsetof() builtin"

**Comment by artempyanykh** [comment]
Hi @XVilka ! I have allocated last week of February to do various cleanups. With a bit of luck the fix will be ready sometime next week.

**Comment by artempyanykh** [comment]
Quick update: the fix is now under internal review, should become available in master shortly. 
The new build successfully finishes analysis of `util-linux`.

**Comment by artempyanykh** [comment]
The fix is in master. `infer run` finishes successfully on `util-linux`

**Comment by thedrow** [comment]
@artempyanykh When can I expect a new release?

**Comment by artempyanykh** [comment]
@thedrow I don't have immediate plans to do the public release (esp. given that to do it properly we need to figure out notarizing of binaries for MacOS Catalina and I don't have capacity for this now). 

If urgent, building from source is probably your best bet.

**Comment by thedrow** [comment]
@artempyanykh Hi, I hope everything is well.

Do you have a better ETA on a release?
