### ISSUE TITLE
Links on Getting Started point to non-existent files

### ISSUE THREAD

**Issue by champo** [facebook/infer#122]
http://fbinfer.com/docs/getting-started.html

Both download links show 404. Also, the 0.2.0 release notes show the md5sum for two .tar.xz files but there's not link to them.

**Comment by technion** [comment]
It would appear that binaries are no longer being shipped.

I'm not generally a fan of distributing binary releases of a product - but infer has an unusually complex build process and a lot of people would be happy to not have to install OCaml.

I'd appreciate if the binary builds could be reinstated somewhere.

**Comment by jvillard** [comment]
We're working on getting the binaries back up.

**Comment by rahulparsani** [comment]
Hey @jvillard anything we can do to help with this?

**Comment by jvillard** [comment]
We've solved at least parts of the issue with the [latest release](https://github.com/facebook/infer/releases/tag/v0.3.0). It ships the source of Infer together with binaries for the clang plugin, which was by far the longest step of the build process. You will still need to install OCaml though ;)

**Comment by champo** [comment]
That's awesome! My report was mostly about the links being broken rather than having binary releases uploaded. Thanks
