### ISSUE TITLE
Add Algolia DocSearch to Docusaurus website

### ISSUE THREAD

**Issue by yangshun** [facebook/infer#1228]
@s-pace we have moved fbinfer.com to Docusaurus 2. Would you be able to help set up the site for Algolia DocSearch and send in a PR? Much appreciated!

cc @jvillard

**Comment by s-pace** [comment]
Sure, [can you apply please](https://docsearch.algolia.com/apply/)?

**Comment by yangshun** [comment]
I've applied on behalf of @jvillard using his FB email.

**Comment by s-pace** [comment]
fbinfer (aac9e661e851db0d4b6e74802c3df9de) ✅

**Comment by yangshun** [comment]
@s-pace what would the index name be? Is it "infer"?
