### ISSUE TITLE
There was nothing to analyze, exiting

### ISSUE THREAD

**Issue by suojingchao** [facebook/infer#123]
TODO: print error message
TODO: print error message
There was nothing to analyze, exiting

gradle + infer to Android app in android studio.

**Comment by jvillard** [comment]
Please upgrade to the latest version of Infer. Without more context it is hard to know what went wrong, but several changes since the version of Infer you appear to be using may have addressed this.

**Comment by suojingchao** [comment]
I do it like this : git clone https://github.com/facebook/infer.git and use the infer/iner/bin

**Comment by jvillard** [comment]
@suhasjoshi to upgrade, please run these commands from the `infer/` directory you got from git:

```sh
opam update && opam upgrade
git pull
make -C infer clean java
```

**Comment by suojingchao** [comment]
I am in Ubuntu12.04

**Comment by jvillard** [comment]
@suojingchao You can try:

```sh
# go where you downloaded opam before this command
./opam update
./opam install sawja.1.5 atdgen.1.5.0 javalib.2.3a extlib.1.5.4
# go to the infer/ directory before the next two commands
git pull
make -C infer clean java
```

**Comment by suojingchao** [comment]
3Q， but It is no use
