### ISSUE TITLE
The links of manual and documentations are broken.

### ISSUE THREAD

**Issue by sangwoo-joh** [facebook/infer#1234]
In the [manual](https://fbinfer.com/docs/man-pages) page, none of the links are working.
Also, I found that the [link](https://fbinfer.com/static/odoc/0.15.0/index.html) of the bookmark that I've registered in my firefox ago was also broken.
Where can I find the documentation?

**Comment by jvillard** [comment]
Thanks for the report, we just migrated our website to a new framework and I missed this. I see that the links are pointing to static/man/..., but the pages are actually in man/.., eg https://fbinfer.com/man/infer-analyze.1.html

Same for the OCaml documentation, the static/ part goes away when the website is published: https://fbinfer.com/odoc/0.15.0/index.html

Let me see what's going on.

**Comment by sangwoo-joh** [comment]
@jvillard Thank you!

**Comment by jvillard** [comment]
Proper fix incoming, re-opening.

**Comment by imbsky** [comment]
Oh, I'm sorry! I didn't notice this!

**Comment by jvillard** [comment]
@imbsky I might have messed that up myself, these files somehow didn't make it to our internal phabricator when importing your PR! Anyhow, I didn't expect we would get away with migrating the entire website without needing some fixes here and there afterwards ;)

**Comment by imbsky** [comment]
Thank you for your kind words!
