### ISSUE TITLE
Infer error while loading shared libraries.

### ISSUE THREAD

**Issue by sangwoo-joh** [facebook/infer#1236]
- Build version: v0.17.0
 - Build OS: Ubuntu 18.04, Running OS: Ubuntu 16.04 (docker)
 - Every `infer` command failed with following message:

```
infer: error while loading shared libraries: liboptpoly.so: cannot open shared object file: No such file or directory.
```

I built infer in my desktop (Ubuntu 18.04), and installed it via `make install`.
Then, I found `infer` installed in `/usr/local/lib/infer/`, so I just zip this directory (with `tar -cvjf infer.tar.bz2 infer/`)  and copied it to the docker container (Ubuntu 16.04)
However, I cannot run `infer` in this docker container with the error message above.
I never had this issue with v0.15.0 before.
I found `liboptpoly` in `home/me/.opam/ocaml-variants.4.07.1+flambda/share/elina/lib/liboptpoly.so` using `mlocate`.

Is there any way to run in a different environment with only the directory installed in `/usr/local/lib`? What package should I install?

Thank you!

**Comment by sangwoo-joh** [comment]
I found that `liboptpoly.so` is not the only one that is missed.
All the `*.so` files of apron and elina packages are missed in infer's install directory.
In addition to this, `libmpfr.so.6` is missed, too.
With all these files in `LD_LIBRARY_PATH`, I can run the infer successfully.

Perhaps there is an intention I don't know. Are these files not included on some purpose? If so, is there any way to distribute standalone infer binary in a more convenient way?

Thank you!

**Comment by sangwoo-joh** [comment]
Oh, I found `install-with-libs` target in `Makefile` :sweat_smile: 
I will use this. Thank you!

**Comment by jvillard** [comment]
Right, `install-with-libs` is what you wanted. In the current master there is no dependency on these libraries anymore so the installation process should be smoother now (`make install` should be enough).
