### ISSUE TITLE
Error while trying to make infer.

### ISSUE THREAD

**Issue by Polyg0n** [facebook/infer#124]
##### *EDIT:*
OS Specs:
OS X 10.10.4 "Yosemite"

So I made sure I correctly followed the installation instructions, but this error arises when I try to use
```bash
make -C infer
```
Here is the error I get:
![screen shot 2015-07-03 at 3 40 03 pm](https://cloud.githubusercontent.com/assets/5068526/8505074/2235c388-219a-11e5-9638-0f4f26cf4a1f.png)

I can see that it's atdgen causing the issue, is this a simple "reinstall atdgen"? Or something else?

##### *EDIT:*
I tried uninstalling and reinstalling atdgen using opam. And still nothing. When I try to use the "atdgen" command in my terminal I get:
"-bash: atdgen: command not found"
I'm assuming this could be an issue of atdgen not being on my PATH. But then why would the output as shown in my screencap say "atdgen: No such file or directory"?

**Comment by Polyg0n** [comment]
Never mind! I got it to work! Apparently opam didn't add atdgen to my PATH. That's all I had to do!
Closing this issue.

**Comment by joshualan** [comment]
Have the same problem, where does OPAM install atdgen? Trying to find it to add it to my path.

**Comment by jvillard** [comment]
@joshualan you probably need to run `eval $(opam config env)` to add opam's to your PATH, etc.

To avoid doing this every time you open a new console, you can install opam:

```sh
opam config setup --all
```

**Comment by vinnybad** [comment]
@joshualan were you able to resolve the atdgen issue?  @Polyg0n - where did you find the atdgen path to add to PATH?
