### ISSUE TITLE
How do i view the issues in HTML report? for maven projects. Currently using Infer version v0.17.0-581af48 running on ubuntu. 

### ISSUE THREAD

**Issue by PradeepShetty14** [facebook/infer#1252]
Please make sure your issue is not addressed in the [FAQ](http://fbinfer.com/support.html#troubleshooting).

Please include the following information:
- [ ] The version of infer from `infer --version`.
- [ ] Your operating system and version, for example "Debian 9", "MacOS High Sierra", whether you are using Docker, etc.
- [ ] Which command you ran, for example `infer -- make`.
- [ ] The full output in a paste, for instance a [gist](https://gist.github.com/).
- [ ] If possible, a minimal example to reproduce your problem (for instance, some code where
    infer reports incorrectly, together with the way you run infer to reproduce the incorrect
    report).

**Comment by ezgicicek** [comment]
Hi,
You can run infer with debug option (`--debug` or shortcut `-g`) and then proceed to `<infer-out>/captured/<file-name>.html` to see the html output. 

I am not exactly sure for maven. I suppose you would need to look at the infer-out directory for your maven project.

**Comment by PradeepShetty14** [comment]
Hi,
If we use the --debug option then it provides a HTML file which contains the source file.
I don't need that. I need a summary of the entire projects and issues. 
https://fbinfer.com/docs/advanced-features/

**Comment by ezgicicek** [comment]
Ok, quoting from [https://fbinfer.com/docs/advanced-features/](https://fbinfer.com/docs/advanced-features/)

> this HTML file contains the source file. In each line of the file there are links to the nodes of the control flow graph that correspond to that line of code. So one can see what the translation looks like. Moreover, when you click on those links you can see details of the symbolic execution of that particular node. If the option --no_test is also passed to infer, then the page pointed to from the nodes contains the printout of the whole symbolic execution.

if you had the following simple example:

```
int null_deref_bad(){
  int* x = nullptr;
  return *x;
}
```

The html would look like the following: 

![Screenshot 2020-04-24 at 11 01 16](https://user-images.githubusercontent.com/6132408/80200726-f7082800-861a-11ea-9cbc-276bd7a699ce.png)

where you can click on the name of the function and see the Infer  "summary" (i.e. the abstract analysis result for the function) along with all the intermediate results. Moreover, it also inlines the issue infer found.

>  I need a summary of the entire projects and issues.

What exactly do you mean by the "summary" here? Do you wanna see all the issues found in the project? 

If so, refer to
> `report.txt` and `report.json` contain the Infer reports in text and JSON formats

**Comment by PradeepShetty14** [comment]
Yes the entire summary in an html report, i have worked on spotbugs and this can generate a summary.html file with all the details such as bugs, no of classes etc. So i was expecting the same kind of report from infer.

**Comment by PradeepShetty14** [comment]
Also is there a way we can integrate with gihub ? during pull request and if there is an issue then it dispays in the pull requests itself?

**Comment by jvillard** [comment]
Have a look at `infer explore --html`. Please re-open if this doesn't work for you.
