### ISSUE TITLE
CMake error at tools/clang/tools/clang-import-test/cmake_install.cmake:41 file INSTALL cannot copy file

### ISSUE THREAD

**Issue by XVilka** [facebook/infer#1259]
- [x] The version of infer is https://github.com/facebook/infer/commit/9d9060d213d7c9a0c92422df5aaf671f4d3db29f commit
- [x] Standard Ubuntu Docker image
- [x] Building the image

![image](https://user-images.githubusercontent.com/203261/81376622-84c53680-9136-11ea-8bd6-47599cab0a36.png)

**Comment by jvillard** [comment]
Did the image perhaps run out of disk space?

**Comment by XVilka** [comment]
Yes, that was indeed the case. Sorry for the noise.
