### ISSUE TITLE
Jenkins integration after removal of --pmd-xml option

### ISSUE THREAD

**Issue by tyrasd** [facebook/infer#1262]
After c73feb82b42fc7d8602d304d167acdd64f918954, integrating infer into a Jenkins workflow using the `--pmd-xml` switch (as suggested by @jvillard in https://github.com/facebook/infer/issues/396#issuecomment-235270263) doesn't work anymore. Is there a suggested workflow for Jenkins users to use infer >0.17.*?

**Comment by jvillard** [comment]
Ah, thanks for raising this issue. I guess we should re-implement that functionality in OCaml if it's used and it's not easy to replicate outside of infer.

**Comment by rompic** [comment]
we are using it as well.

**Comment by rompic** [comment]
More context:
We are using it with the warnings ng plugin
Which uses https://github.com/jenkinsci/analysis-model/blob/master/README.md
And with
violation-comments-to-github-plugin
Which uses 
https://github.com/tomasbjerre/violations-lib
To parse reports.

Maybe these could add support for the native format. However, it may make sense to support a more common output format.

**Comment by jvillard** [comment]
I've re-implemented the option, let me know if the behaviour has changed in a bad way.
