### ISSUE TITLE
infer analysis make project error

### ISSUE THREAD

**Issue by niuzhi** [facebook/infer#1263]
Hello, I use infer to analyze the C ++ project. The compilation script used in the project is as follows, 
![image](https://user-images.githubusercontent.com/33443724/82274721-7a673000-99b3-11ea-8e39-c06f8053e520.png)

but the infer analysis prompts no file compile, how should I deal with it?thanks
![image](https://user-images.githubusercontent.com/33443724/82274679-560b5380-99b3-11ea-85e3-7aa52634690a.png)

**Comment by sangwoo-joh** [comment]
Could you please try `make clean` and then run the script again? The message says that it cannot detect any compilation unit.

Also, in my experience, Infer cannot recognize the wrapped build script even though it invokes `make` in it (which is a little different from your case). If you're using `cmake` to generate build script, then make compilation database through `-DCMAKE_COMPILE_COMMANDS=ON` flag, and run `infer capture --compilation-database compile_commands.json`. It worked for my case.

**Comment by niuzhi** [comment]
The same result after the project is cleaned up, I try cmake to open -DCMAKE_COMPILE_COMMANDS = ON, thank you

**Comment by niuzhi** [comment]
The same result after the project is cleaned up, I try cmake to open -DCMAKE_COMPILE_COMMANDS = ON, thank you

**Comment by sangwoo-joh** [comment]
@niuzhi 
Oh, my mistake. It should be `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON`
