### ISSUE TITLE
infer analysis error

### ISSUE THREAD

**Issue by niuzhi** [facebook/infer#1264]
Infer analysis reported the following error, how to solve it? Thank you！

**Comment by sangwoo-joh** [comment]
Could you try with `--keep-going` flag again?
In my experience, Infer cannot recognize all the c/c++ code. But thanks to the bi-abduction, even it missed some files during analysis, the analysis result is somehow credible.

**Comment by niuzhi** [comment]
> Could you try with `--keep-going` flag again?
> In my experience, Infer cannot recognize all the c/c++ code. But thanks to the bi-abduction, even it missed some files during analysis, the analysis result is somehow credible.

I don't know how to use this parameter --keep-going, can you give a case? Thank you very much

**Comment by niuzhi** [comment]
@sangwoo-joh 
I don't know how to use this parameter --keep-going, can you give a case? Thank you very much

**Comment by sangwoo-joh** [comment]
@niuzhi 
You can run with `--keep-going` flag, e.g. `infer analyze --keep-going` or `infer capture --keep-going`.

**Comment by niuzhi** [comment]
@sangwoo-joh than you very muh!i will try again!
