### ISSUE TITLE
Experimental Checker for input variables analysis question.

### ISSUE THREAD

**Issue by Rui1995** [facebook/infer#1266]
Hi,  My name is Rui Ferreira and I'm a master's student at Instituto Superior Técnico (Lisbon).

As part of my master's thesis I've been studying the idea of creating a checker with Infer to detect and signal potential unused input data, in programs written in Java.
The approach would be similar to Lyra, created by Catherine Urban (for applications written in Python) (https://caterinaurban.github.io/pdf/esop2018.pdf). This approach tracks and classifies variables as {Used, Not Used, Bellow, Overwritten}, based on the relation between them, and is a backwards analysis.
I've been told the implementation may not be possible because Lyra uses a relational domain (the classification of a variable depends on its interaction with other variables). Would that be an actual problem to the implementation?
Are there any other obstacles to such implementation?
I'm sorry if this is a very complex question, but I've been struggling to answer them in the last few months. Any input on the matter would be highly appreciated.

Best Regards,
Rui Ferreira

**Comment by jvillard** [comment]
Hi Rui, infer doesn't put any constraint on your abstract domain, it can be whatever you want. We have many relational domains in infer already. Without looking at the analysis in details it's difficult for me to give more guidance. If you are looking for resources to get started writing checkers in infer please check out the labs: https://github.com/facebook/infer/blob/master/infer/src/labs/README.md

**Comment by Rui1995** [comment]
Thanks a lot!
