### ISSUE TITLE
SARIF (Static Analysis Results Interchange Format) format support

### ISSUE THREAD

**Issue by XVilka** [facebook/infer#1274]
It would amazing to have [SARIF](http://docs.oasis-open.org/sarif/sarif/v2.0/csprd01/sarif-v2.0-csprd01.html) (Static Analysis Results Interchange Format) format support, so, for example, Infer can be integrated right into the GitHub: https://help.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/uploading-a-sarif-file-to-github

After the upload to GitHub it would look similar to
![image](https://user-images.githubusercontent.com/203261/83507266-e93ba180-a4fa-11ea-8fb9-5febb8b1e6e4.png)

See also their repository: https://github.com/oasis-tcs/sarif-spec

**Comment by XVilka** [comment]
Seems that @GrammaTech implemented SARIF converted for Infer already, but I wasn't able to find any reference:
> As mentioned above, we have written adapters that convert Plist-form (Clang Static Analyzer and Cppcheck), and Facebook Infer output to SARIF. These have been contributed to the SARIF SDK on Github.

https://blogs.grammatech.com/static-analysis-results-a-format-and-a-protocol-sarif-sasp

**Comment by XVilka** [comment]
See also the example how they added SARIF output to the Clang Analyzer natively: https://reviews.llvm.org/D53814

**Comment by andrewvaughanj** [comment]
Looks like the SARIF SDK one is here: https://github.com/sarif-standard/sarif-sdk-typescript/blob/master/InferConverter.ts

**Comment by xi-liu-ds** [comment]
I am contributing a native SARIF exporter in this [PR](https://github.com/facebook/infer/pull/1487)

**Comment by jvillard** [comment]
fixed in #1487

**Comment by jiangxincode** [comment]
Preview unavailable: 
https://github.com/jiangxincode/ApkToolBoxGUI/security/code-scanning
