### ISSUE TITLE
Maintaining domain inside a conditional operator (Experimental Checker)

### ISSUE THREAD

**Issue by Rui1995** [facebook/infer#1275]
Hi,

I am creating a checker that analyzes variables and classifies them.  (https://gist.github.com/Rui1995/7ce7728dd9ea06efabe5041161d4b6dc)

My question is: can we preserve the same domain when we enter a conditional operator inside a certain procedure (I've noticed that the domain starts empty when we enter a conditional, for example a "if... then...else..", instead of maintaining the same domain as the rest of the analysis).
For example in this code (https://gist.github.com/Rui1995/9efa012cf0912609890acd05ea633da1) (even though it's not the best example) the domain is empty when the analysis enters the  conditional operator (in line 5 because it's a backwards analysis).

Any input would be appreciated. 

Best Regards

**Comment by jvillard** [comment]
Hi, the abstract state should be propagated along conditional nodes too. Line 5 is a `return` instruction so its only successor should be the exit node, hence it will start with the initial state. You can check the CFG of the procedure by looking for *.dot files in infer-out/captured/ when running in debug mode. The HTML debug files also contain predecessor/successor information between nodes.

Can you give more details about what state you observe, what state you expected, and at which node?

**Comment by Rui1995** [comment]
Hi, thanks a lot for your help. 
I figured out the error in my thinking. I was expecting in line 5  to see the same domain that carried out from line 7, which doesn't make sense since line 5 is a return (creating a new branch in the cfg). Didn't understand that from the HTML, but the CFG made it clear.

Best Regards
