### ISSUE TITLE
About labs

### ISSUE THREAD

**Issue by hyunsooda** [facebook/infer#1280]
Please make sure your issue is not addressed in the [FAQ](https://fbinfer.com/docs/support#troubleshooting).

Please include the following information:
- [latest] The version of infer from `infer --version`.
- [Ubuntu 18.04] Your operating system and version, for example "Debian 9", "MacOS High Sierra", whether you are using Docker, etc.
- [infer -- javac Leaks.java] Which command you ran, for example `infer -- make`.
- [ ] The full output in a paste, for instance a [gist](https://gist.github.com/).
- [ ] If possible, a minimal example to reproduce your problem (for instance, some code where
    infer reports incorrectly, together with the way you run infer to reproduce the incorrect
    report).

1. As description about the Java Resouce Leak, Infer should report 7 resource leaks when Infer is ran with default option such as `infer -- javac Leaks.java`, but my environment(latest version) does not reproduce any resource leaks.(infer-out/report.txt is empty)  Is there a some pre setup for this or am I missing something?
...............................................
` > infer -- javac Leaks.java          `                                                                                                                             
Capturing in javac mode...
Found 1 source file to analyze in /home/hyunsoo/infer/infer/tests/codetoanalyze/java/lab/infer-out
1/1 [################################################################################] 100% 77.805ms
**No issues found** 
...............................................

 ++++++++++++++++++++ update  ++++++++++++++++++++

I have clean everything and re-installed and now it works.

I just saw the checker for resource-leak in `base/Checker.ml`(doc is out-dated) and lab-resource-leak was not default-enabled but why it triggers the checker by default?

- Two commands show same result
     - `infer -- javac Leaks.java`
     -  `infer --resource-leak -- javac Leaks.java `

**Comment by jvillard** [comment]
Glad you resolved your issue. I've updated the documentation recently so the lab instructions should be up to date now. Please open an issue if you find other inconsistencies.
