### ISSUE TITLE
RETURN_VALUE_IGNORED not found

### ISSUE THREAD

**Issue by m1ghtym0** [facebook/infer#1285]
I'm running  infer version 0.17.0 on Ubuntu 20.04 with Java version 11.0.7
I wanted to test the RETURN_VALUE_IGNORED example from:
https://github.com/facebook/infer/blob/master/infer/tests/codetoanalyze/java/biabduction/ReturnValueIgnored.java

Running `infer run -g -F --enable-issue-type RETURN_VALUE_IGNORED -- javac ReturnValueIgnored.java` gives:

```
Logs in infer-out/logs
Execution ID 8301841769977208870
Capturing in javac mode...
Found 1 source file to analyze in infer-out


Analysis finished in 1.016ss

  No issues found
```

Shouldn't RETURN_VALUE_IGNORED be in the biabduction checker?
Could that be a problem with Java 11?
Is RETURN_VALUE_IGNORED supported for C/C++/Obj-C as well?

**Comment by jvillard** [comment]
The support for that issue type was removed in 2017 in 2a8e1922801e09180143f1b5a6917f6cab3ffb4e but only removed altogether recently in 090ce4edb96bb1ae99949c21b342958360279797. We should delete the test too.

**Comment by m1ghtym0** [comment]
Oh interesting, thanks!
What was the reason to remove this issue type?

**Comment by jvillard** [comment]
According to 2a8e192 it was because it was implemented as part of the "biabduction" analysis:

> Summary: Those are not particularly relevant for the biabduction analysis. It would be easy to have a dedicated checker for this if we happen to need one day.

This kind of almost-syntactic check seems a better fit for a compiler or an IDE than infer.

Was there a reason why you were looking into this issue type?
