### ISSUE TITLE
Can I have the documentation for Sil IR?

### ISSUE THREAD

**Issue by sangwoo-joh** [facebook/infer#1293]
Thank you for the great analysis tool.
I am currently trying to understand the internal, and so I want to check any documentation (or maybe paper?) regarding the language design of Sil IR.
Can I have this documentation? Or, is the source code the best materials to understand the Sil IR?
Thank you!

**Comment by skcho** [comment]
SIL is a graph with 5 kinds of instructions. The instructions are explained in the API document.
https://fbinfer.com/odoc/next/infer/IR/Sil/index.html#type-instr

Could you let us know which kinds of information about the IR you want?

**Comment by sangwoo-joh** [comment]
Thank you, I will check the documentation!
