### ISSUE TITLE
Build fails with "use of undeclared identifier '__FILE_NAME__'" with Xcode 12 only.

### ISSUE THREAD

**Issue by yousefhamza** [facebook/infer#1310]
I have just updated Xcode from 11.5 to Xcode 12 GM on CirlceCI and Infer started failing to build scheme with error:
```
error: use of undeclared identifier  '__FILE_NAME__'
    NSLog(@"print :%@", [NSString stringWithFormat:@"%s", __FILE_NAME__]);
```

I manage to reproduce this locally with an empty project with just this statement:
```
NSLog(@"print: %@", [NSString stringWithFormat:@"%s", __FILE_NAME__]);
```

Infer version: 0.17
OS: MacOS Catalina 10.15.6
Xcode: Xcode 12 GM
Command: `infer capture --keep-going -- xcodebuild -project SampleProject.xcodeproj -scheme SampleProject -sdk iphonesimulator`

**Comment by Huiz110** [comment]
I have the same problem, have you resolved it?

**Comment by yousefhamza** [comment]
We removed Infer from our CI, still waiting for a response.

**Comment by yousefhamza** [comment]
@Huiz110 We removed Infer from our CI, still waiting for a response.

**Comment by jvillard** [comment]
I think that means your project no longer builds with clang 9, which infer uses under the hood, and needs clang 10. Infer will soon ship with clang 10.

In the meantime, for this particular error you could define instruct infer to define `__FILE_NAME__` but there's a good chance you'll find more compatibility issues once that one is gone: `infer --Xclang -D__FILE_NAME__='"dummy.m"' -- xcodebuild ...`.

**Comment by yousefhamza** [comment]
@jvillard Thanks for the explanation and the workaround 👍 

I will wait for Infer with clang 10, Do you have an approximate date for that release?

**Comment by yousefhamza** [comment]
Hi @jvillard 👋. Do you have any updates or a timeline for this?

**Comment by Huiz110** [comment]
> Hi @jvillard 👋. Do you have any updates or a timeline for this?

update to version 1.0.0, it works now

**Comment by yousefhamza** [comment]
@Huiz110 just got to test it, it works 🥳. Thank you!

**Comment by WillieWu** [comment]
> > Hi @jvillard 👋. Do you have any updates or a timeline for this?
> 
> update to version 1.0.0, it works now

hi, Can infer v1.0.0 be installed using brew? Why is it always v0.17.0 on my side

**Comment by Huiz110** [comment]
> > > Hi @jvillard 👋. Do you have any updates or a timeline for this?
> > 
> > 
> > update to version 1.0.0, it works now
> 
> hi, Can infer v1.0.0 be installed using brew? Why is it always v0.17.0 on my side

see https://fbinfer.com/docs/getting-started/

install for mac:
```
VERSION=1.0.0; \
curl -sSL "https://github.com/facebook/infer/releases/download/v$VERSION/infer-osx-v$VERSION.tar.xz" \
| sudo tar -C /opt -xJ && \
ln -s "/opt/infer-osx-v$VERSION/bin/infer" /usr/local/bin/infer
```

**Comment by WillieWu** [comment]
> > > > Hi @jvillard 👋. Do you have any updates or a timeline for this?
> > > 
> > > 
> > > update to version 1.0.0, it works now
> > 
> > 
> > hi, Can infer v1.0.0 be installed using brew? Why is it always v0.17.0 on my side
> 
> see https://fbinfer.com/docs/getting-started/
> 
> install for mac:
> 
> ```
> VERSION=1.0.0; \
> curl -sSL "https://github.com/facebook/infer/releases/download/v$VERSION/infer-osx-v$VERSION.tar.xz" \
> | sudo tar -C /opt -xJ && \
> ln -s "/opt/infer-osx-v$VERSION/bin/infer" /usr/local/bin/infer
> ```

**ths**
