### ISSUE TITLE
infer does not run preprocessor, or possibly just doesn't recognize X-macros

### ISSUE THREAD

**Issue by ijustlovemath** [facebook/infer#1320]
Please make sure your issue is not addressed in the [FAQ](https://fbinfer.com/docs/support#troubleshooting).

Please include the following information:
- [ v0.17.0 ] The version of infer from `infer --version`.
- [ Debian 9 WSL] Your operating system and version, for example "Debian 9", "MacOS High Sierra", whether you are using Docker, etc.
- [ infer run --compilation-database ] Which command you ran, for example `infer -- make`.
- [ https://gist.github.com/ijustlovemath/18b734d4fe52169f44ffb0aac9c191c6 ] The full output in a paste, for instance a [gist](https://gist.github.com/).
- [ https://gist.github.com/ijustlovemath/ed1eb50d29e6e47def40a72e9de84f75 ] If possible, a minimal example to reproduce your problem (for instance, some code where
    infer reports incorrectly, together with the way you run infer to reproduce the incorrect
    report).

infer reports that the two variables `prev_rule_number` and `prev_rule_zone` were unused, even though they were used in the X-macro expansion.

**Comment by jvillard** [comment]
Infer is complaining about the last write to `prev_rule_zone` inside the expanded macro because the value stored in `prev_rule_zone` is never read after that (line 20 of your second paste).
