### ISSUE TITLE
Unable to run hello.c example

### ISSUE THREAD

**Issue by markrtuttle** [facebook/infer#1324]
Please make sure your issue is not addressed in the [FAQ](https://fbinfer.com/docs/support#troubleshooting).

Running the hello.c example with Infer 1.0 on Ubuntu 20 fails with the infer clang unable to find a system shared library.

Please include the following information:
- [ x] The version of infer from `infer --version`: Infer version v1.0.0
- [ x] Your operating system and version, for example "Debian 9", "MacOS High Sierra", whether you are using Docker, etc: Ubuntu 20
- [ x] Which command you ran, for example `infer -- make`: infer run -- gcc -c hello.c
- [ x] The full output in a paste, for instance a [gist](https://gist.github.com/): https://gist.github.com/markrtuttle/8ca197076d8f49dd59d1335b29521154
- [ x] If possible, a minimal example to reproduce your problem (for instance, some code where
    infer reports incorrectly, together with the way you run infer to reproduce the incorrect
    report).

**Comment by markrtuttle** [comment]
```
ubuntu20:~/infer ./lib/infer/facebook-clang-plugins/clang/install/bin/clang --version
./lib/infer/facebook-clang-plugins/clang/install/bin/clang: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```

**Comment by markrtuttle** [comment]
No trouble running on MacOS.

**Comment by jvillard** [comment]
Is libtinfo5 (no -dev version necessary I think) available on ubuntu 20?

**Comment by markrtuttle** [comment]
The problem is solved with `sudo apt install libtinfo5`.  

I recommend saying on the release page that the binary is built for ubuntu20 (say the build system explicitly) and may run on other systems, and saying that libtinfo5 is required (listing the dependencies).  

It is not that hard to build a binary-only debian package that installs dependencies automatically.  People could download that and install with 'dpkg -i blah.deb' and be completely done.

**Comment by jvillard** [comment]
I have added a note that the binary was built for Ubuntu 18 in the release notes.
