### ISSUE TITLE
version of python

### ISSUE THREAD

**Issue by royburns** [facebook/infer#133]
checking for python... /usr/bin/python
checking for python >= 2.7... not found
configure: error: found python 2.6.6 (/usr/bin/python); required >= 2.7

==============>
how to process the version of the python? is it support multi-version of python?
our machine installed python 2.6, then i install python 2.7, how to config the python interpreter?

**Comment by martinoluca** [comment]
Hi @royburns,
Could you please explain a bit more how to repro your issue?

Thanks

**Comment by jvillard** [comment]
Feel free to re-open if the issue is still current.
