### ISSUE TITLE
Unknown target CPU

### ISSUE THREAD

**Issue by sangwoo-joh** [facebook/infer#1330]
Hi.
My test machine has following status:
 - OS: Ubuntu 16.04
 - CPU: Intel Xeon E5-4627 v2 (32) @ 3.600GHz

Infer with 0433e95 works well on this machine. However, when I've tried on docker container, an error occurs:

```
ERROR RUNNING CAPTURE: Bi_inbuf.End_of_input
Raised at file "src/bi_inbuf.ml", line 49, characters 6-24
Called from file "src/bi_io.ml" (inlined), line 508, characters 12-35
Called from file "src/atd/clang_ast_b.ml", line 38396, characters 7-24
Called from file "atdgen-runtime/src/util.ml" (inlined), line 30, characters 4-11
Called from file "src/clang/Capture.ml", line 23, characters 2-113


error: : unknown target CPU 'armv8-a+crc+simd+crypto'
valid target CPU values are: nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cascadelake, cooperlake, cannonlake, icelake-client, icelake-server, knl, knm, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, znver2, x86-64
```

However, on another machine that has same OS/CPU and same container, infer works just fine.
Is this an error related to infer itself, or the clang frontend?
If you have any clue about this, please help me!
Thanks in advance.

**Comment by jvillard** [comment]
For some reason (I think just disk space) we don't include all architectures in the clang we build to go alongside infer. Maybe armv8 isn't included in the "ARM" architecture? It looks like what you're building is trying to compile to armv8 for some reason, maybe there's a way to not do that since you're able to build on another machine.

https://github.com/facebook/infer/blob/e3de7ce5dc72924055cd9c47761979abc0c88b79/facebook-clang-plugins/clang/setup.sh#L167

**Comment by sangwoo-joh** [comment]
@jvillard 
It is true, but for some reason, another machine that works fine has limited disk space so I want to work on this machine too.
I will build infer on the machine in question and then try it again!

**Comment by sangwoo-joh** [comment]
Ok, so I cannot even install `opam` version 2 on this problematic machine. It says: 
```
## Downloading opam 2.0.7 for linux on x86_64...
There may not yet be a binary release for your architecture or OS, sorry.
See https://github.com/ocaml/opam/releases/tag/2.0.7 for pre-compiled binaries,
or run 'make cold' from https://github.com/ocaml/opam/archive/2.0.7.tar.gz to build from scratch

```
.. even though it tries to download opam for "linux on x86_64" as it said on the first line.

But the only difference is its kernel version: 4.15.0-74-generic, whereas the well-working machine is 4.4.0-131-generic.
I have no clue about this issue, so maybe I should find to use the well-working machine anyhow...
Thank you, and I'll close this issue!
