### ISSUE TITLE
How can I write .inferconfig

### ISSUE THREAD

**Issue by xiongfengzhang** [facebook/infer#1337]
If I only want to use some checker，is it right？.inferconfig write as:

--enable-issue-type
  INFERBO_ALLOC_MAY_BE_NEGATIVE
  INFINITE_AUTORELEASEPOOL_SIZE

**Comment by zyh1121** [comment]
the other way is to do so in command line 
`infer run --enable-issue-type INFERBO_ALLOC_MAY_BE_NEGATIVE --enable-issue-type INFINITE_AUTORELEASEPOOL_SIZE -- gcc ...`

**Comment by jvillard** [comment]
The equivalent .inferconfig file would be:
```
{
  "enable-issue-type": [
    "INFERBO_ALLOC_MAY_BE_NEGATIVE",
    "INFINITE_AUTORELEASEPOOL_SIZE"
    ]
}
```

Please re-open if you have more questions.
