### ISSUE TITLE
"Internal Error: java_class_info should be present for Java classes" using "--eradicate"

### ISSUE THREAD

**Issue by baloghadamsoftware** [facebook/infer#1338]
Infer is crashing with "Internal Error: java_class_info should be present for Java classes" on any code using "--eradicate"

Infer version 1.0.0 (also tried on 0.17.0, there was no issue, everything worked fine). Operating system is Ubuntu 18.04, kernel version 4.5. The build command is:

infer --html -a checkers --eradicate --quandary -- mvn clean compile

The output is:

Internal Error: java_class_info should be present for Java classes 0% 55.528ms
Error backtrace:in/java/SER05-J-1.java: SER05J1_OuterSer$SER05J1_InnerSer.<init
Raised at Base__String.rindex_from_exn_internal in file "src/string.ml", line 127, characters 7-22/java/NUM01-J-6.java: void NUM01J6.method()
Called from Base__String.rsplit2_exn.rsplit2_exn in file "src/string.ml", line 620, characters 14-55java/OBJ05-J-2.java: OBJ05J2_MutableClass.<init>()
Called from Base__String.rsplit2 in file "src/string.ml", line 633, characters 11-330.0s] src/main/java/dataflow/DIV_BY_ZERO_1.java: DIV_BY_ZERO_1.<init>()
Re-raised at IBase__Die.raise_error.do_raise in file "src/base/Die.ml", line 26, characters 8-56ain/java/NUM14-J-3.java: NUM14J3.<init>()
Called from Nullsafe__ClassLevelAnalysis.analyze_nullsafe_annotations in file "src/nullsafe/ClassLevelAnalysis.ml", line 212, characters 12-50Connection()
Called from Nullsafe__FileLevelAnalysis.analyze_class_and_nested in file "src/nullsafe/FileLevelAnalysis.ml", line 31, characters 20-90
Called from Stdlib__list.fold_left in file "list.ml", line 121, characters 24-34
Called from Base__List0.fold in file "src/list0.ml" (inlined), line 21, characters 22-52
Called from Nullsafe__FileLevelAnalysis.analyze_file in file "src/nullsafe/FileLevelAnalysis.ml", line 58, characters 4-98
Called from Backend__Callbacks.iterate_file_callbacks_and_store_issues.(fun) in file "src/backend/callbacks.ml", line 77, characters 26-46
Called from Stdlib__list.iter in file "list.ml", line 110, characters 12-15
Called from Backend__Ondemand.analyze_procedures.(fun) in file "src/backend/ondemand.ml" (inlined), line 387, characters 6-92
Called from Base__Option.iter in file "src/option.ml" (inlined), line 94, characters 14-17
Called from Backend__Ondemand.analyze_procedures in file "src/backend/ondemand.ml", line 386, characters 2-147
Called from Backend__InferAnalyze.analyze_target.analyze_source_file.(fun) in file "src/backend/InferAnalyze.ml", line 52, characters 10-51
Called from IBase__Logging.task_progress in file "src/base/Logging.ml", line 240, characters 15-19
Called from IBase__ProcessPool.child_loop in file "src/base/ProcessPool.ml", line 356, characters 12-19
Re-raised at IStdlib__IExn.reraise_if in file "src/istd/IExn.ml", line 18, characters 15-63
Called from IBase__ProcessPool.child_loop in file "src/base/ProcessPool.ml", line 358, characters 10-427
Called from IBase__ProcessPool.fork_child in file "src/base/ProcessPool.ml", line 420, characters 6-99
Called from Stdlib__array.init in file "array.ml", line 56, characters 22-27
Called from IBase__ProcessPool.create in file "src/base/ProcessPool.ml", line 445, characters 4-189
Called from Backend__Tasks.Runner.create in file "src/backend/Tasks.ml", line 25, characters 6-286
Called from Backend__InferAnalyze.analyze in file "src/backend/InferAnalyze.ml", line 186, characters 6-130
Called from Integration__Driver.execute_analyze.(fun) in file "src/integration/Driver.ml", line 179, characters 2-34
Called from Backend__GCStats.log_f in file "src/backend/GCStats.ml", line 90, characters 10-14
Called from Integration__Driver.execute_analyze in file "src/integration/Driver.ml", line 176, characters 2-239
Called from IBase__Utils.timeit in file "src/base/Utils.ml", line 451, characters 16-20
Called from IBase__ScubaLogging.execute_with_time_logging in file "src/base/ScubaLogging.ml", line 79, characters 29-44
Called from Dune__exe__Infer.run in file "src/infer.ml", line 21, characters 2-47
Called from IBase__Utils.timeit in file "src/base/Utils.ml", line 451, characters 16-20
Called from IBase__ScubaLogging.execute_with_time_logging in file "src/base/ScubaLogging.ml", line 79, characters 29-44
Called from Dune__exe__Infer.run in file "src/infer.ml", line 25, characters 22-94

Run the command again with `--keep-going` to try and ignore this error.
Internal Error: Subprocess 5: see backtrace above
Error backtrace:
Raised at Core__Core_unix.improve in file "src/core_unix.ml", line 46, characters 4-43
Called from Core__Core_unix.wait_gen in file "src/core_unix.ml", line 942, characters 4-246
Called from Core__Core_unix.wait in file "src/core_unix.ml" (inlined), line 971, characters 2-34
Called from IBase__ProcessPool.killall.(fun) in file "src/base/ProcessPool.ml", line 189, characters 10-30
Re-raised at IBase__Die.raise_error.do_raise in file "src/base/Die.ml", line 26, characters 8-56
Called from Stdlib__list.iter in file "list.ml", line 110, characters 12-15
Called from Base__List0.iter in file "src/list0.ml" (inlined), line 25, characters 16-35
Called from IBase__ProcessPool.process_updates in file "src/base/ProcessPool.ml" (inlined), line 258, characters 5-1023
Called from IBase__ProcessPool.process_updates in file "src/base/ProcessPool.ml", line 257, characters 2-1023
Called from IBase__Utils.do_finally_swallow_timeout in file "src/base/Utils.ml", line 213, characters 8-12
Re-raised at IStdlib__IExn.reraise_after in file "src/istd/IExn.ml", line 13, characters 2-50
Called from IBase__Utils.do_finally_swallow_timeout in file "src/base/Utils.ml", line 215, characters 6-141
Called from IBase__Utils.try_finally_swallow_timeout in file "src/base/Utils.ml" (inlined), line 223, characters 16-54
Called from IBase__Utils.with_file_lock in file "src/base/Utils.ml", line 262, characters 2-41
Called from IBase__ProcessPool.run in file "src/base/ProcessPool.ml", line 462, characters 2-656
Called from Backend__InferAnalyze.analyze in file "src/backend/InferAnalyze.ml", line 189, characters 24-47
Called from Integration__Driver.execute_analyze.(fun) in file "src/integration/Driver.ml", line 179, characters 2-34
Called from Backend__GCStats.log_f in file "src/backend/GCStats.ml", line 90, characters 10-14
Called from Integration__Driver.execute_analyze in file "src/integration/Driver.ml", line 176, characters 2-239
Called from IBase__Utils.timeit in file "src/base/Utils.ml", line 451, characters 16-20
Called from IBase__ScubaLogging.execute_with_time_logging in file "src/base/ScubaLogging.ml", line 79, characters 29-44
Called from Dune__exe__Infer.run in file "src/infer.ml", line 21, characters 2-47
Called from IBase__Utils.timeit in file "src/base/Utils.ml", line 451, characters 16-20
Called from IBase__ScubaLogging.execute_with_time_logging in file "src/base/ScubaLogging.ml", line 79, characters 29-44
Called from Dune__exe__Infer.run in file "src/infer.ml", line 25, characters 22-94

[sources.zip](https://github.com/facebook/infer/files/5464108/sources.zip)

**Comment by jvillard** [comment]
Thanks for the report, @baloghadamsoftware!
