### ISSUE TITLE
Analyzing class files and src files(40k+) takes forever 

### ISSUE THREAD

**Issue by c3sivanarayanagaddam** [facebook/infer#1348]
Here is the command:
Mac: 64GB(RAM), 16 core
infer -j 16   --generated-classes  <path> --sourcepath  <path>

It just runs forever and I observed that it stops writing to results.db 

It seem to hung at `Capturing for Buck genrule compatibility...`

`
Called from IStdlib__MaximumSharing.Sharer.hash_and_normalize_block in file "src/istd/MaximumSharing.ml", line 173, characters 33-47
Called from IStdlib__MaximumSharing.Sharer.hash_and_normalize_block in file "src/istd/MaximumSharing.ml", line 173, characters 33-47
Called from IStdlib__MaximumSharing.Sharer.hash_and_normalize_block_fields in file "src/istd/MaximumSharing.ml", line 243, characters 8-81
Called from IStdlib__MaximumSharing.Sharer.hash_and_normalize_block in file "src/istd/MaximumSharing.ml", line 194, characters 16-146
Called from IStdlib__MaximumSharing.Sharer.hash_and_normalize_block_fields in file "src/istd/MaximumSharing.ml", line 243, characters 8-81
Called from IStdlib__MaximumSharing.Sharer.hash_and_normalize_block in file "src/istd/MaximumSharing.ml", line 194, characters 16-146
Called from IStdlib__MaximumSharing.Sharer.hash_and_normalize_block_fields in file "src/istd/MaximumSharing.ml", line 243, characters 8-81
Called from IStdlib__MaximumSharing.Sharer.hash_and_normalize_block in file "src/istd/MaximumSharing.ml", line 194, characters 16-146
Called from IStdlib__MaximumSharing.Sharer.hash_and_normalize_block_fields in file "src/istd/MaximumSharing.ml", line 243, characters 8-81
Called from IStdlib__MaximumSharing.Sharer.hash_and_normalize_block in file "src/istd/MaximumSharing.ml", line 194, characters 16-146
Called from IStdlib__MaximumSharing.Sharer.hash_and_normalize_block_fields in file "src/istd/MaximumSharing.ml", line 243, characters 8-81
Called from IStdlib__MaximumSharing.Sharer.hash_and_normalize_block in file "src/istd/MaximumSharing.ml", line 194, characters 16-146
Called from IStdlib__MaximumSharing.Sharer.hash_and_normalize_block_fields in file "src/istd/MaximumSharing.ml", line 243, characters 8-81
Called from IStdlib__MaximumSharing.Sharer.hash_and_normaUncaught Internal Error: (IBase.Epilogues.Sigint)`

**Comment by c3sivanarayanagaddam** [comment]
Am i missing something?

**Comment by ngorogiannis** [comment]
Hi. Capture when done like this is single-threaded, no matter what -j has been specified.

Can you try splitting the class files in batches somehow and for each batch do 
```
infer capture --continue -o <results-dir> --generated-classes <...> --sourcepath <...>
```
for each batch in parallel (up to the number of cores).

When the capture is finished you can do 
```
infer analyze -o <results-dir>
```

**Comment by venganesh** [comment]
Thanks @ngorogiannis. Batching would surely work. I had some success. 

Let me try running master build as well.

**Comment by c3sivanarayanagaddam** [comment]
Tried running `infer binary` from master build. Seems to be working fine now. Thanks @ngorogiannis
