### ISSUE TITLE
C false positive: confusion with strrchr() and/or ?: 

### ISSUE THREAD

**Issue by timdeegan** [facebook/infer#135]
Seen under Infer 0.2.0 on Ubuntu 14.10 x86_64.

Replacing strrchr() with an extern function with the same signature seems to fix this, as does replacing the '?:' with an explicit 'if (!p) p = "bar"'.  Some tangle between the two?

    #include <string.h>
    
    int f(void)
    {
        const char *s;
        s = strrchr("foo", 'f') ?: "bar";
    
        /* False positive: this is reported as a NULL_DEREFERENCE,
         * even though 's' cannot be NULL. */
    
        return (*s == 'f');
    }

**Comment by jvillard** [comment]
this has been fixed
