### ISSUE TITLE
Eradicate+standard checkers fail, but eradicate-only works

### ISSUE THREAD

**Issue by hmijail** [facebook/infer#1362]
When I run `infer analyze --eradicate` it fails with 
`Internal Error: java_class_info should be present for Java classes`

However, if I run `infer analyze --eradicate-only` or `infer --no-default-checkers   --eradicate` it does finish successfully.

Full output at https://gist.github.com/hmijail/53218668a8077f151141d54894595649

This sounds similar to #1338.

Infer version v1.0.0-0c6eedc83
MacOS Catalina 10.15.7 (19H114)

**Comment by hmijail** [comment]
FWIW, this exact error already happened at commit 7dcbacf69309d113e6374d03ee267fe2f7d44797 .

**Comment by jvillard** [comment]
Closing as this is addressed in #1363 and #1338. Fix for #1338 incoming.
