### ISSUE TITLE
Why can't I use the 'brew install infer' command to install infer v1.0.0

### ISSUE THREAD

**Issue by puyang0521** [facebook/infer#1364]
How to solve this problem?

**Comment by andrewvaughanj** [comment]
See here: https://github.com/facebook/infer/issues/1354

**Comment by andrewvaughanj** [comment]
Also, you could just download a binary release straight from GitHub rather than using `brew`: https://github.com/facebook/infer/issues/1354#issuecomment-737163890

**Comment by jvillard** [comment]
So far there are issues with updating the Homebrew formula to 1.0.0. Let's keep the discussion there: https://github.com/Homebrew/homebrew-core/pull/62862
