### ISSUE TITLE
What would be needed to extend this tool to more languages?

### ISSUE THREAD

**Issue by aekoch** [facebook/infer#1368]
Specifically higher level languages, like Kotlin or Swift, or untyped languages, like Javascript or Python.

Is there some intermediate interface that allows **infer** to share logic between the 4 currently supported language, or is it implemented separately for each one?  If someone were to implement the interface/model for Swift, would infer work out of the box or would it need to be tuned to the new language?

**Comment by rgrig** [comment]
Infer has an intermediate representation called [Sil](https://github.com/facebook/infer/tree/master/infer/src/IR). In theory, adding support for a new language means adding a frontend that converts to Sil.  In practice, there's probably a lot more that needs to be done to ensure high quality results for a new language. Support for C# is being added now, so you can see in that PR what adding support for a new language entails: https://github.com/facebook/infer/pull/1361/files

**Comment by jvillard** [comment]
Please re-open if you have more questions.
