### ISSUE TITLE
infer v1.0.0

### ISSUE THREAD

**Issue by WillieWu** [facebook/infer#1369]
hi, Can infer v1.0.0 be installed using brew? Why is it always v0.17.0 on my side

**Comment by ZilinXiang** [comment]
因为1.0版本 homebrew那边没法从源码编译成功。。。所以也就不能从brew安装到最新的release版本了

**Comment by WillieWu** [comment]
>   因为1.0版本 homebrew那边没法从源码编译构建成功。。。所以也就不能从brew安装到最新的release版本了

谢谢你的回复。不过我这边安装infer-osx-v1.0.0.tar.xz一直失败。不知道什么原因，电脑信息如下
Mac： Big sur 11.0.1
xcode: 12.3

**Comment by WillieWu** [comment]
> > 因为1.0版本 homebrew那边没法从源码编译构建成功。。。所以也就不能从brew安装到最新的release版本了
> 
> 谢谢你的回复。不过我这边安装infer-osx-v1.0.0.tar.xz一直失败。不知道什么原因，电脑信息如下
> Mac： Big sur 11.0.1
> xcode: 12.3

执行infer时，提示libsqlite.td损坏

**Comment by sunilluminate** [comment]
w

> > > 因为1.0版本 homebrew那边没法从源码编译构建成功。。。所以也就不能从brew安装到最新的release版本了
> > 
> > 
> > 谢谢你的回复。不过我这边安装infer-osx-v1.0.0.tar.xz一直失败。不知道什么原因，电脑信息如下
> > Mac： Big sur 11.0.1
> > xcode: 12.3
> 
> 执行infer时，提示libsqlite.td损坏

我也是，求解

**Comment by WillieWu** [comment]
VERSION=1.0.0; \
curl -sSL "https://github.com/facebook/infer/releases/download/v$VERSION/infer-osx-v$VERSION.tar.xz" \
| sudo tar -C /opt -xJ && \ 
ln -s "/opt/infer-osx-v$VERSION/bin/infer" /usr/local/bin/infer

试试这个

发自我的iPhone

**Comment by WillieWu** [comment]
棒的很
