### ISSUE TITLE
Curly brackets affect analysis results?

### ISSUE THREAD

**Issue by zyh1121** [facebook/infer#1373]
- [x] Please make sure your issue is not addressed in the [FAQ](https://fbinfer.com/docs/support#troubleshooting).

Please include the following information:
- [x] The version of infer from `infer --version`.
  ```
  $ infer --version
  Infer version v1.0.0-6eb79feaa
  ```
- [x] Your operating system and version, for example "Debian 9", "MacOS High Sierra", whether you are using Docker, etc.
  ```
  Linux ... 3.10.0-957.el7.x86_64
  Red Hat Enterprise Linux Server release 7.6 (Maipo)
  ```
- [x] Which command you ran, for example `infer -- make`.
```
infer --bufferoverrun --pulse --bo-field-depth-limit 3 --enable-issue-type BUFFER_OVERRUN_L5  run -- gcc -c $src_file
```
- [x] The full output in a paste, for instance a [gist](https://gist.github.com/).
- [x] If possible, a minimal example to reproduce your problem (for instance, some code where
    infer reports incorrectly, together with the way you run infer to reproduce the incorrect
    report).

  * Infer produced different results for two semantically equivalent snippets, where the differences are two brackets.
  * Infer says there is no bug in the version without brackets
    ```c
    main ( ) 
    { 
    int entity_4 ; 
    int entity_9 ; 
    entity_9 = 86 ; 
    char entity_1 [ 32 ] ; 
    for ( entity_4 = 73 ; entity_4 < entity_9 ; entity_4 ++ ) 
    entity_1 [ entity_4 ] 
    ; 
    }
    ```
    Infer output:
    ```
    $ infer --bufferoverrun --pulse --bo-field-depth-limit 3 --enable-issue-type BUFFER_OVERRUN_L5  run -- gcc -c 3.c 
    Capturing in make/cc mode...
    Found 1 source file to analyze in ..../infer-out
    1/1 [################################################################################] 100% 32.967ms

      No issues found  
    ```
  * Infer says there is a bug in the version with brackets
    ```c
    main ( ) 
    { 
    int entity_4 ; 
    int entity_9 ; 
    entity_9 = 86 ; 
    char entity_1 [ 32 ] ; 
    for ( entity_4 = 73 ; entity_4 < entity_9 ; entity_4 ++ ) {
    entity_1 [ entity_4 ] ;
    }
     
    }
    ```
    Infer output
    ```
    Input file: 4.c
    Capturing in make/cc mode...
    Found 1 source file to analyze in ..../infer-out
    1/1 [################################################################################] 100% 44.454ms
    
    4.c:8: error: Buffer Overrun L1
      Offset: [73, 85] Size: 32.
       6. char entity_1 [ 32 ] ; 
       7. for ( entity_4 = 73 ; entity_4 < entity_9 ; entity_4 ++ ) {
       8. entity_1 [ entity_4 ] ;
          ^
       9. }
      10.  
    
    
    Found 1 issue
                Issue Type(ISSUED_TYPE_ID): #
      Buffer Overrun L1(BUFFER_OVERRUN_L1): 1
    ```
  * There are more similar cases. For example, if we replace the `for` loop with a `while` loop, infer acts the same.

**Comment by jvillard** [comment]
Many thanks for the report, I have a fix coming.

**Comment by zyh1121** [comment]
@jvillard Thanks for the fix! It works now. 👍

**Comment by zyh1121** [comment]
@jvillard sorry to bug you again. we saw some strange behaviors when running infer on two similar snippets. I opened an issue here #1374. could you please take a look too? thanks!
