### ISSUE TITLE
unknown option '--incremental'

### ISSUE THREAD

**Issue by LONGDDSF** [facebook/infer#1377]
I do the work follow this article 'https://infer.liaohuqiu.net/docs/infer-workflow.html',
I  think all is ok ,but the commands
```
infer run --incremental --keep-going 
```
and
```
infer --incremental --keep-going 
```
do not work，the error info as below,
```
/Users/dy/Documents/iOS/Infer/infer-osx/bin/infer: unknown option '--incremental'.
Infer version v0.17.0
Copyright 2009 - present Facebook. All Rights Reserved.
Usage: infer command [options]
See `infer --help` for more information.
```
 My computer is iMac,10.15.4 (19E287).

How can I do increment analysis by infer？

**Comment by jvillard** [comment]
This page is not maintained by us. Unfortunately it is more than 5 years old and outdated. The incremental workflow uses `--reactive` now, see https://fbinfer.com/docs/infer-workflow

**Comment by LONGDDSF** [comment]
Many thanks!
It works well!
