### ISSUE TITLE
like this error

### ISSUE THREAD

**Issue by puyang0521** [facebook/infer#1380]
Mac 10.15.6
xcode 12.2
infer 1.0.0
code objective-c

This error only appears in some projects, but I don't know what code is causing this error. My other projects can use infer normally

---------------------------------------------------------------------------------------------

External Error: *** capture failed to execute: exited with code 65
Error backtrace:
Raised at Stdlib.input_line.scan in file "stdlib.ml", line 449, characters 14-31
Called from Stdio__In_channel.input_line_exn in file "src/in_channel.ml" (inlined), line 68, characters 13-30
Called from IBase__Utils.with_channel_in in file "src/base/Utils.ml", line 252, characters 11-44
Re-raised at IBase__Die.raise_error.do_raise in file "src/base/Die.ml" (inlined), line 26, characters 8-56
Called from IBase__Logging.die.(fun) in file "src/base/Logging.ml", line 347, characters 6-39
Called from Integration__Driver.capture in file "src/integration/Driver.ml", line 166, characters 6-36
Called from IBase__Utils.timeit in file "src/base/Utils.ml", line 421, characters 16-20
Called from IBase__ScubaLogging.execute_with_time_logging in file "src/base/ScubaLogging.ml" (inlined), line 79, characters 29-44
Called from Integration__Driver.capture.(fun) in file "src/integration/Driver.ml", line 180, characters 2-233
Called from Backend__GCStats.log_f in file "src/backend/GCStats.ml" (inlined), line 90, characters 10-14
Called from Integration__Driver.capture in file "src/integration/Driver.ml", line 178, characters 2-288
Called from Dune__exe__Infer.run in file "src/infer.ml" (inlined), line 20, characters 2-36
Called from IBase__Utils.timeit in file "src/base/Utils.ml" (inlined), line 421, characters 16-20
Called from IBase__ScubaLogging.execute_with_time_logging in file "src/base/ScubaLogging.ml" (inlined), line 79, characters 29-44
Called from Dune__exe__Infer.run in file "src/infer.ml", line 25, characters 22-94

----------------------------------------------------------------------------------------------

**Comment by zzzworm** [comment]
Hi, I have same problem on my project.Did you fix the problem? How do you fix this isssue? @puyang0521

**Comment by rthenmozhis** [comment]
Hi @puyang0521  - can you please share the steps on how you fixed this issue. I have same problem.

**Comment by huajingtong** [comment]
我也遇到了，怎么解决啊 求助

**Comment by lizhaobomb** [comment]
有解决方案吗？xcode版本的锅吗？

**Comment by huajingtong** [comment]
> 有解决方案吗？xcode版本的锅吗？
咱们加个微信 交流一下吧 18810967642

**Comment by erduoniba** [comment]
这个错误和你执行的命令有关，请拆分使用这两个命令来info扫描：
1、先编译数据database

xcodebuild -workspace pgWebViewModule.xcworkspace -scheme pgWebViewModule_Example -sdk iphoneos14.4 | tee xcodebuild.log | xcpretty -r json-compilation-database -o compile_commands.json
2、再执行infer指令

infer run --keep-going --skip-analysis-in-path Pods --compilation-database-escaped compile_commands.json
通过上面两个部分，可能还有有一些其他问题，比如说 clang-11: error: unknown argument: '-index-store-path'，修改Xcode的build setting 的 Enable Index-While-Building Functionality 为 NO 即可。

具体可以参考这个文章来实现：
https://blog.csdn.net/shengpeng3344/article/details/105032969


@lizhaobomb @huajingtong @puyang0521 可以参考下

**Comment by Shawn1yao** [comment]
> 这个错误和你执行的命令有关，请拆分使用这两个命令来info扫描： 1、先编译数据database
> 
> ```
> xcodebuild -workspace pgWebViewModule.xcworkspace -scheme pgWebViewModule_Example -sdk iphoneos14.4 | tee xcodebuild.log | xcpretty -r json-compilation-database -o compile_commands.json
> ```
> 
> 2、再执行infer指令
> 
> ```
> infer run --keep-going --skip-analysis-in-path Pods --compilation-database-escaped compile_commands.json
> ```
> 
> 通过上面两个部分，可能还有有一些其他问题，比如说 `clang-11: error: unknown argument: '-index-store-path'`，修改Xcode的build setting 的 `Enable Index-While-Building Functionality ` 为 NO 即可。
> 
> 具体可以参考这个文章来实现： https://blog.csdn.net/shengpeng3344/article/details/105032969

你好，使用这种指令扫描特别慢，请问下，你是如何优化的？
