### ISSUE TITLE
clang-9: error: unknown argument: '-index-store-path'

### ISSUE THREAD

**Issue by puyang0521** [facebook/infer#1382]
Please make sure your issue is not addressed in the [FAQ](https://fbinfer.com/docs/support#troubleshooting).

Please include the following information:
- [x] The version of infer from `infer --version`.

> Infer version v1.0.0
Copyright 2009 - present Facebook. All Rights Reserved.

- [x] Your operating system and version, for example "Debian 9", "MacOS High Sierra", whether you are using Docker, etc.

> macOS Catalina 10.15.6
> xcode 12.2

- [x] Which command you ran, for example `infer -- make`.

> xcodebuild -workspace xxx.xcworkspace -scheme xxx -sdk iphoneos14.2  | tee xcodebuild.log | xcpretty -r json-compilation-database -o compile_commands.json
infer run --skip-analysis-in-path Pods --no-xcpretty --keep-going --compilation-database-escaped compile_commands.json

- [x] The full output in a paste, for instance a [gist](https://gist.github.com/).
`Error message:
**clang-9: error: unknown argument: '-index-store-path'**

*** Infer needs a working compilation command to run.

Usage Error: Failed to execute compilation command:..............] 75% 5.37s
'/Users/yang.pu/Desktop/ThirdClone/infer-osx-v1.0.0/lib/infer/infer/bin/../../facebook-clang-plugins/clang/install/bin/clang' controller/navigation/PROJECTCommonVi
  @/Users/yang.pu/Desktop/PROJECT/PROJECTClient/infer-out/tmp/cdb_clang_args.tmp.b8ab80.txt
  -fsyntax-only  ++Contents of '/Users/yang.pu/Desktop/PROJECT/PROJECTClient/infer-out/tmp/cdb_clang_args.tmp.b8ab80.txt':
                    -x objective-c -target arm64-apple-ios9.0 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path\=/Users/yang.pu/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/yang.pu/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -fmodule-name\=PROJECTUICommon -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.2.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-semicolon-before-method-body -index-store-path /Users/yang.pu/Library/Developer/Xcode/DerivedData/PROJECTClient-gempmmudvsdfbrayekxbotgqcwds/Index/DataStore -iquote /Users/yang.pu/Library/Developer/Xcode/DerivedData/PROJECTClient-gempmmudvsdfbrayekxbotgqcwds/Build/Intermediates.noindex/PROJECTUICommon.build/Debug-iphoneos/PROJECTUICommon.build/PROJECTUICommon-generated-files.hmap -I/Users/yang.pu/Library/Developer/Xcode/DerivedData/PROJECTClient-gempmmudvsdfbrayekxbotgqcwds/Build/Intermediates.noindex/PROJECTUICommon.build/Debug-iphoneos/PROJECTUICommon.build/PROJECTUICommon-own-target-headers.hmap -I/Users/yang.pu/Library/Developer/Xcode/DerivedData/PROJECTClient-gempmmudvsdfbrayekxbotgqcwds/Build/Intermediates.noindex/PROJECTUICommon.build/Debug-iphoneos/PROJECTUICommon.build/PROJECTUICommon-all-non-framework-target-headers.hmap -ivfsoverlay /Users/yang.pu/Library/Developer/Xcode/DerivedData/PROJECTClient-gempmmudvsdfbrayekxbotgqcwds/Build/Intermediates.noindex/PROJECTUICommon.build/Debug-iphoneos/PROJECTUICommon.build/all-product-headers.yaml -iquote /Users/yang.pu/Library/Developer/Xcode/DerivedData/PROJECTClient-gempmmudvsdfbrayekxbotgqcwds/Build/Intermediates.noindex/PROJECTUICommon.build/Debug-iphoneos/PROJECTUICommon.build/PROJECTUICommon-project-headers.hmap -I/Users/yang.pu/Library/Developer/Xcode/DerivedData/PROJECTClient-gempmmudvsdfbrayekxbotgqcwds/Build/Products/Debug-iphoneos/include -I/Users/yang.pu/Library/Developer/Xcode/DerivedData/PROJECTClient-gempmmudvsdfbrayekxbotgqcwds/Build/Intermediates.noindex/PROJECTUICommon.build/Debug-iphoneos/PROJECTUICommon.build/DerivedSources-normal/arm64 -I/Users/yang.pu/Library/Developer/Xcode/DerivedData/PROJECTClient-gempmmudvsdfbrayekxbotgqcwds/Build/Intermediates.noindex/PROJECTUICommon.build/Debug-iphoneos/PROJECTUICommon.build/DerivedSources/arm64 -I/Users/yang.pu/Library/Developer/Xcode/DerivedData/PROJECTClient-gempmmudvsdfbrayekxbotgqcwds/Build/Intermediates.noindex/PROJECTUICommon.build/Debug-iphoneos/PROJECTUICommon.build/DerivedSources -F/Users/yang.pu/Library/Developer/Xcode/DerivedData/PROJECTClient-gempmmudvsdfbrayekxbotgqcwds/Build/Products/Debug-iphoneos -F/Users/yang.pu/Desktop/PROJECT/PROJECTClient/frameworks/opensource -include /Users/yang.pu/Desktop/PROJECT/PROJECTClient/PROJECTUICommon/PROJECTUICommon/PrefixHeader.pch -MMD -MT dependencies -MF /Users/yang.pu/Library/Developer/Xcode/DerivedData/PROJECTClient-gempmmudvsdfbrayekxbotgqcwds/Build/Intermediates.noindex/PROJECTUICommon.build/Debug-iphoneos/PROJECTUICommon.build/Objects-normal/arm64/PROJECTCommonViewController.d --serialize-diagnostics /Users/yang.pu/Library/Developer/Xcode/DerivedData/PROJECTClient-gempmmudvsdfbrayekxbotgqcwds/Build/Intermediates.noindex/PROJECTUICommon.build/Debug-iphoneos/PROJECTUICommon.build/Objects-normal/arm64/PROJECTCommonViewController.dia -c /Users/yang.pu/Desktop/PROJECT/PROJECTClient/PROJECTUICommon/PROJECTUICommon/com.Project.src/controller/navigation/PROJECTCommonViewController.m -o /Users/yang.pu/Library/Developer/Xcode/DerivedData/PROJECTClient-gempmmudvsdfbrayekxbotgqcwds/Build/Intermediates.noindex/PROJECTUICommon.build/Debug-iphoneos/PROJECTUICommon.build/Objects-normal/arm64/PROJECTCommonViewController.o
                 
Error message:
**clang-9: error: unknown argument: '-index-store-path'**

*** Infer needs a working compilation command to run.

Usage Error: Failed to execute compilation command:
'/Users/yang.pu/Desktop/ThirdClone/infer-osx-v1.0.0/lib/infer/infer/bin/../../facebook-clang-plugins/clang/install/bin/clang' 
  @/Users/yang.pu/Desktop/PROJECT/PROJECTClient/infer-out/tmp/cdb_clang_args.tmp.eb1411.txt
  -fsyntax-only  ++Contents of '/Users/yang.pu/Desktop/PROJECT/PROJECTClient/infer-out/tmp/cdb_clang_args.tmp.eb1411.txt':
                    -x objective-c -target arm64-apple-ios9.0 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path\=/Users/yang.pu/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/yang.pu/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.2.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-semicolon-before-method-body -index-store-path /Users/yang.pu/Library/Developer/Xcode/DerivedData/PROJECTClient-gempmmudvsdfbrayekxbotgqcwds/Index/DataStore -iquote /Users/yang.pu/Library/Developer/Xcode/DerivedData/PROJECTClient-gempmmudvsdfbrayekxbotgqcwds/Build/Intermediates.noindex/PROJECTUICommon.build/Debug-iphoneos/PROJECTUICommon.build/PROJECTUICommon-generated-files.hmap -I/Users/yang.pu/Library/Developer/Xcode/DerivedData/PROJECTClient-gempmmudvsdfbrayekxbotgqcwds/Build/Intermediates.noindex/PROJECTUICommon.build/Debug-iphoneos/PROJECTUICommon.build/PROJECTUICommon-own-target-headers.hmap -I/Users/yang.pu/Library/Developer/Xcode/DerivedData/PROJECTClient-gempmmudvsdfbrayekxbotgqcwds/Build/Intermediates.noindex/PROJECTUICommon.build/Debug-iphoneos/PROJECTUICommon.build/PROJECTUICommon-all-non-framework-target-headers.hmap -ivfsoverlay /Users/yang.pu/Library/Developer/Xcode/DerivedData/PROJECTClient-gempmmudvsdfbrayekxbotgqcwds/Build/Intermediates.noindex/PROJECTUICommon.build/Debug-iphoneos/PROJECTUICommon.build/all-product-headers.yaml -iquote /Users/yang.pu/Library/Developer/Xcode/DerivedData/PROJECTClient-gempmmudvsdfbrayekxbotgqcwds/Build/Intermediates.noindex/PROJECTUICommon.build/Debug-iphoneos/PROJECTUICommon.build/PROJECTUICommon-project-headers.hmap -I/Users/yang.pu/Library/Developer/Xcode/DerivedData/PROJECTClient-gempmmudvsdfbrayekxbotgqcwds/Build/Products/Debug-iphoneos/include -I/Users/yang.pu/Library/Developer/Xcode/DerivedData/PROJECTClient-gempmmudvsdfbrayekxbotgqcwds/Build/Intermediates.noindex/PROJECTUICommon.build/Debug-iphoneos/PROJECTUICommon.build/DerivedSources-normal/arm64 -I/Users/yang.pu/Library/Developer/Xcode/DerivedData/PROJECTClient-gempmmudvsdfbrayekxbotgqcwds/Build/Intermediates.noindex/PROJECTUICommon.build/Debug-iphoneos/PROJECTUICommon.build/DerivedSources/arm64 -I/Users/yang.pu/Library/Developer/Xcode/DerivedData/PROJECTClient-gempmmudvsdfbrayekxbotgqcwds/Build/Intermediates.noindex/PROJECTUICommon.build/Debug-iphoneos/PROJECTUICommon.build/DerivedSources -F/Users/yang.pu/Library/Developer/Xcode/DerivedData/PROJECTClient-gempmmudvsdfbrayekxbotgqcwds/Build/Products/Debug-iphoneos -F/Users/yang.pu/Desktop/PROJECT/PROJECTClient/frameworks/opensource -include /Users/yang.pu/Desktop/PROJECT/PROJECTClient/PROJECTUICommon/PROJECTUICommon/PrefixHeader.pch -MMD -MT dependencies -MF /Users/yang.pu/Library/Developer/Xcode/DerivedData/PROJECTClient-gempmmudvsdfbrayekxbotgqcwds/Build/Intermediates.noindex/PROJECTUICommon.build/Debug-iphoneos/PROJECTUICommon.build/Objects-normal/arm64/PROJECTClientNotificationsName.d --serialize-diagnostics /Users/yang.pu/Library/Developer/Xcode/DerivedData/PROJECTClient-gempmmudvsdfbrayekxbotgqcwds/Build/Intermediates.noindex/PROJECTUICommon.build/Debug-iphoneos/PROJECTUICommon.build/Objects-normal/arm64/PROJECTClientNotificationsName.dia -c /Users/yang.pu/Desktop/PROJECT/PROJECTClient/PROJECTUICommon/PROJECTUICommon/com.Project.src/global/PROJECTClientNotificationsName.m -o /Users/yang.pu/Library/Developer/Xcode/DerivedData/PROJECTClient-gempmmudvsdfbrayekxbotgqcwds/Build/Intermediates.noindex/PROJECTUICommon.build/Debug-iphoneos/PROJECTUICommon.build/Objects-normal/arm64/PROJECTClientNotificationsName.o
                 
Error message:
**clang-9: error: unknown argument: '-index-store-path'**

*** Infer needs a working compilation command to run.

144/144 [########################################################] 100% 7.227s

Nothing to compile. Try cleaning the build first.
There was nothing to analyze.
`

**Comment by puyang0521** [comment]
@jvillard

**Comment by puyang0521** [comment]
@jvillard

**Comment by jvillard** [comment]
Hi @puyang0521, sorry for not getting back to you sooner. This argument is only present in newer versions of clang and the version of infer at the time was using clang 9. The latest version 1.0.0 has clang-10, which I think supports it, and the current master is on clang 11, which definitely supports it.

For reference you can also tell infer to drop this argument in case this comes up again, eg I expect this would have worked:
```
infer --clang-blacklisted-flags-with-arg -index-store-path -- clang -index-store-path . -c foo.c
```
