### ISSUE TITLE
RacerD and Java.io

### ISSUE THREAD

**Issue by andrecostea** [facebook/infer#1383]
Consider a case where RacerD analyses a program where certain reads and stores are performed by `Java.io` methods. 

Infer has a default model for `Java.io` where the read and store operations are ignored.

Is there any way to instruct RacerD to ignore those default models and instead analyse the classes of interest from `Java.io`? Even better, is there a way to model these operations such that RacerD can extract meaningful summaries from these method definitions?

Consider the example below, where we'd expect an Unprotected Write and a Read/Write race, yet RacerD does not detect these bugs. 

```
import java.io.BufferedInputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import com.facebook.infer.annotation.ThreadSafe;

@ThreadSafe
public class ThreadA {

	byte[] messageByte = new byte[100];

	public void foo(boolean read) {
		  ServerSocket server;
		  Socket clientSocket = null;
		  int currentBytesRead;

		  try {
		  server = new ServerSocket(8080);
		  Socket socket = server.accept();

		  DataInputStream in = new DataInputStream(new BufferedInputStream(socket.getInputStream()));
		  DataOutputStream out = new DataOutputStream(clientSocket.getOutputStream());
		  
		  if(read) 
                         // Unprotected Write
			  currentBytesRead = in.read(messageByte);  // read from `in` and write to `messageByte`
		  else
			  out.write(messageByte); //read from `messageByte` and write to `out`
		  } catch (IOException e) {
		  e.printStackTrace(); }
	}
}
```

**Comment by andrecostea** [comment]
Adding some dummy writes and reads in `Java.io.DataInputStream.read` and `Java.io.DataOutputStream.write`, respectively,  seems to have no effect over the analysis performed by RacerD after recompiling Infer:

```
  public int read(byte b[]) throws IOException {
    b[0] = 0; //dummy write
    return InferUndefined.can_throw_ioexception_int();
  }
```

```
  public void write(byte b[]) throws IOException {
    if(b[0]>0) InferBuiltins._exit();
    InferUndefined.can_throw_ioexception_void();
  }
```

I am probably missing some of the basic understanding of the models, but not sure what. Your input would be much appreciated. Thanks!

**Comment by ngorogiannis** [comment]
Hi! Something that probably confuses a lot of people is that the model files in models/ only affect biabduction and no other analyses.

The race here is indeed missed. Analysing the java.io code can maybe be done but is non-trivial. it seems to me the easiest way would be to model these methods inside RacerD (see https://github.com/facebook/infer/blob/faaf0ecf180c3e0357c593a300e5c44e69a67183/infer/src/concurrency/RacerD.ml#L126)

**Comment by andrecostea** [comment]
> Hi! Something that probably confuses a lot of people is that the model files in models/ only affect biabduction and no other analyses.

That explains a lot of teh behaviours. Thanks! 

> The race here is indeed missed. Analysing the java.io code can maybe be done but is non-trivial. it seems to me the easiest way would be to model these methods inside RacerD (see
> 
> https://github.com/facebook/infer/blob/faaf0ecf180c3e0357c593a300e5c44e69a67183/infer/src/concurrency/RacerD.ml#L126
> 
> )

Thanks for the suggestion. 

One last question: if I create a custom IO package, say `custom.jar` which contains custom classes to perform the reading and the writing, and then run Infer with the `--dependecies` flag on and `-cp custom.jar:.` passed to the Java compiler, the race is detected in a version of the earlier example which now uses the custom IO instead of the `Java.io`. So I wonder whether there is a rule of thumb that Infer and ultimately RacerD follow to analyse such dependencies?

**Comment by ngorogiannis** [comment]
The `--dependencies` flag with a custom classpath is effectively another way to introduce models for all analyses, but only for Java.  Thumbs up for discovering that :)

Infer in this case does not know that the methods in `custom.jar` are "models", it's just that the rules for scanning classpaths mean these methods are overriding the standard library ones.

**Comment by andrecostea** [comment]
Thanks a lot for the clarifications. Indeed, `--dependencies` proved to be a useful feature to test out models before actually implementing them. 

Again, thank you! Highly appreciated the prompt replies.
