### ISSUE TITLE
Infer should return exit code != 0 to run on travis-ci

### ISSUE THREAD

**Issue by hckhanh** [facebook/infer#139]
Hi, my name is Khanh
I am using Infer to detect error from android's source code. I really like it when I run on local machine. But when I let Infer run on Travis. It still returns **exit code 0** even I got some errors. I think Infer should return the **error exit code (not zero)** to notify the user about the bug on travis-ci :+1: 

Thanks in advance. :D

**Comment by jeremydubreil** [comment]
@hckhanh: There is a discussion about this in https://github.com/facebook/infer/pull/126

**Comment by jvillard** [comment]
@hckhanh there is now a `--fail-on-bug` flag you can pass to Infer to do what you want.

**Comment by hckhanh** [comment]
Thank you, @jvillard 
Have a nice day :D
