### ISSUE TITLE
Infer and LLVM 11.0.1

### ISSUE THREAD

**Issue by hamzasohail** [facebook/infer#1390]
Infer currently uses LLVM 10.0.1. That's a bit of a bummer for me since I need to analyze Obj-C projects which can only be built with LLVM 11.0.1+ toolchain. I tried to take a stab at this myself by downloading Infer's source; modifying the scripts to download LLVM 11.0.1 (clang, compiler-rt, etc.); fixing compilation errors when building the clang plugin (e.g., StringRef to std::string conversions needing explicit static casting, some enums being renamed, some functions being renamed etc.) etc. My hope was I don't have to regenerate ASTExporter.h; I was hoping I could squeak by without really having to run ASTDumper (which in itself needs to be modified I'm pretty sure). I finally ran into this one at which point I decided to open an issue:

[*ERROR**][25393] ./ASTExporter.h:4042:19: error: indirection requires pointer operand ('clang::ExprWithCleanups::CleanupObject' (aka 'PointerUnion<clang::BlockDecl *, clang::CompoundLiteralExpr *>') invalid)
[*ERROR**][25393]       dumpDeclRef(*Node->getObject(i));

This one made me think may be I really need to regenerate the ASTExporter.h and there aren't any easy shortcuts to this.

So question: When should we expect for Infer to upgrade to using LLVM 11.0.1+ ?

Just in case someone is interested on what monstrosity I've done, here's the file with really one error (the above one) with rest being warnings. I'm sure even if I were to get around the above one, there'd be more. I just don't seem to know whether when such an upgrade happens, does the ASTExporter.h needs to be regenerated from scratch OR can we hack up a working version.

[error.txt](https://github.com/facebook/infer/files/5990598/error.txt)

**Comment by hamzasohail** [comment]
@jvillard Thought you might have some thoughts on this ?

**Comment by jvillard** [comment]
ASTExporter.h is not generated, this is all lovingly hand-crafted code :) Every time the version of LLVM changes there typically needs to be some adjustments to ASTExporter.h and friends. See eg the most recent version bump 9fd1a87cd5f7c4115f142c98ead3a10baa382199

Compilation errors like the ones in your error.txt file usually come from changes in the LLVM API across versions. I'm afraid there's no other way but to address them one by one to make ASTExporter.h compatible with the new API.

**Comment by martintrojer** [comment]
We (Infer team) have now started the work to migrate llvm/clang 11.  I expect this to conclude in a week or two.

**Comment by martintrojer** [comment]
llvm11 landed in 18f28395e860384ab622d05ddf6bba316278079d
