### ISSUE TITLE
--enable-issue-type flag reports more issues than expected

### ISSUE THREAD

**Issue by xi-liu-ds** [facebook/infer#1397]
Hi,

I have a question regarding the `--enable-issue-type` flag that reports on specified issue types. 

For example, if I run `infer --enable-issue-type NULL_DEREFERENCE -- javac examples/java_hello/Pointers.java examples/java_hello/Resources.java examples/java_hello/Hello.java`, I will still get warnings other than null dereferences (i.e., resource leak). Is it expected? If it is, is there a way to enable specifically named issue types *only* with other issues disabled?

Thanks.

**Comment by jvillard** [comment]
This option toggles individual options. At the moment there is no option to disable all issue types or enable all issue types. You can still get what you want programatically by looking at the output of `infer help --list-issue-types`. For instance this disables all issue types then enables only NULL_DEREFERENCE:

```
infer \
  $(infer help --list-issue-types 2> /dev/null | grep ':true:' | cut -d ':' -f 1 | sed -e 's/^/--disable-issue-type /') \
  --enable-issue-type NULL_DEREFERENCE \
  -- \
  javac examples/java_hello/Pointers.java
```

I am not sure why you'd want to do that but an option could be added that does this if it makes sense, eg `--enable-only-issue-type NULL_DEREFERENCE`.

**Comment by xi-liu-ds** [comment]
I think it is good to have an option like `--enable-only-issue-type` flag. But the programmatic solution you provided also works pretty well for us. Thanks so much 👍 .
