### ISSUE TITLE
[Feature Request] Please update homebrew bottle for 1.1.0 

### ISSUE THREAD

**Issue by pumano** [facebook/infer#1399]
Currently available only v0.17.0 via homebrew 

Please add support for 1.0.0

Idea to install tool via tarball from github in 2021 is not suitable.

**Comment by jvillard** [comment]
Please direct your comments here instead: https://github.com/Homebrew/homebrew-core/pull/62862

**Comment by pumano** [comment]
@jvillard it's not possible, because thread is closed due to inactivity. 

You working at Facebook, but can't release this shit as home brew bottle in 2021. Good story for software interviews. Thank you.

**Comment by andrewvaughanj** [comment]
@pumano could you maybe help here? Infer (and Homebrew) are both open source -- if this is important to you, maybe you could "help give back" to Infer?

**Comment by jvillard** [comment]
Re-opening as it turns out we can't discuss on the Homebrew PR anymore, oops.

**Comment by andrewvaughanj** [comment]
I have a Big Sur i7 and a Big Sur M1 that I can "volunteer" for the effort -- do we know "what's wrong" with the Homebrew builds/how to reproduce the problem?

I have no idea how to "contribute" to Homebrew, but I can try taking a look if the reproduction steps are there.

**Comment by pumano** [comment]
I can test using Catalina too

**Comment by andrewvaughanj** [comment]
Sure, but I think what Infer needs now is people to help fix it, not just test the fix ...

**Comment by jvillard** [comment]
Great! And thanks @andrewvaughanj for keeping the discussion constructive.

To repro the issues you can clone the homebrew-core repo and then the PR above, then running `brew install --build-from-source Formula/infer.rb` should try to build and install infer using the new formula.

However, I think by now there could be other issues with the formula as time went by, so I wonder if cutting a new release of infer would help. Who knows, maybe the compilation issues will go away. We just upgraded our internal version of clang to clang 11 so that would be a good enough excuse to do so too.

**Comment by andrewvaughanj** [comment]
>  I wonder if cutting a new release of infer would help

I think that would be good.

Looking at your PR though, we can probably just change the url to use the `https://github.com/{username}/{projectname}/archive/{sha}.zip` syntax to grab `HEAD` (well, the SHA of the current HEAD).

How far off is a new release with clang 11 integrated?

Just to be clear: I am *not* going to try doing this with the old hash -- doesn't seem like a good use of time when we know we have a new release coming.

**Comment by jvillard** [comment]
Yep, trying the formula with HEAD makes a lot of sense! I agree trying to salvage the old release is kind of pointless now. Re: new release: hopefully "very soon" ;)

**Comment by andrewvaughanj** [comment]
Okay; I'll try with HEAD tonight -- I want to setup a Big Sur VM to make sure this is all good (I'm a MacPorts user 🤦)

**Comment by andrewvaughanj** [comment]
Ignore the branch name: https://github.com/Homebrew/homebrew-core/compare/master...andrewvaughanj:infer-1.0.0

🚀

**Comment by andrewvaughanj** [comment]
Two hours later -- built first time 🥳 🥳 🥳 🥳 🥳 🥳 

Build log: [log.txt](https://github.com/facebook/infer/files/6166254/log.txt)

@jvillard do you want me to open-up a Homebrew PR for the current version of `HEAD` (056c8abbff965ed90e19709af6c2f4c22fae5aff) or wait until the new release?

@pumano you're welcome to clone by branch as above and run `brew install --verbose --build-from-source Formula/infer.rb` to check it works for you not on Big Sur.

**Comment by jvillard** [comment]
That's awesome, @andrewvaughanj! I'll likely be able to release 1.1.0 in the coming days. I tagged a draft release and it went smoothly and generated binaries so now it's just a matter of ironing out some last-minute details in master and repeating the process for good.

**Comment by andrewvaughanj** [comment]
Okay, once that's out, one of us can then update that branch to point to 1.1.0 (over the SHA) and then it should be good to go 💪

**Comment by andrewvaughanj** [comment]
I updated my formula to point to 1.1.0 (which is the same SHA as what I already built) and opened-up the Homebrew PR:

- https://github.com/Homebrew/homebrew-core/pull/73440

**Comment by andrewvaughanj** [comment]
@jvillard can you update the title of this issue to be 1.1.0 and not 1.0.0 please?

**Comment by pumano** [comment]
@andrewvaughanj I cloned your repo and build as you wrote, and all is OK for my MacOS Catalina. Build succeed and infer 1.1.0 available.

Sorry guys and especially @jvillard for my yesterday negativity. 

Thank you for bring latest release of infer to homebrew. it's very good for all who use it. 

Hope @andrewvaughanj opened pull request soon :)

**Comment by andrewvaughanj** [comment]
> Hope @andrewvaughanj opened pull request soon :)
>

Already there: https://github.com/Homebrew/homebrew-core/pull/73440 :)

**Comment by andrewvaughanj** [comment]
@pumano 1.1.0 is out and the Homebrew PR is marked to be merged 💪

**Comment by pumano** [comment]
@andrewvaughanj thank you!

**Comment by pumano** [comment]
looks like we can close this issue. Thank you guys.
