### ISSUE TITLE
Missing translation for Cast Kind

### ISSUE THREAD

**Issue by stfairy** [facebook/infer#14]
I encountered many warnings saying "Missing translation for Cast Kind <XXX>" where XXX is one of
- FunctionToPointerDecay
- ArrayToPointerDecay
- BuiltinFnToFnPtr
- IntegralToPointer
- NullToPointer

Are they being analyzed at all?

**Comment by jeremydubreil** [comment]
Thanks for reporting this. Cast operations are not all translated yet. This output corresponds to missing cases in: https://github.com/facebook/infer/blob/master/infer/src/clang/cTrans_utils.ml#L365.

Do you know how we could reproduce these issues ?

**Comment by stfairy** [comment]
I compiled a single C file which is http://git.linuxfoundation.org/?p=llvmlinux/kernel.git;a=blob_plain;f=net/ipv4/tcp_ipv4.c;h=a3f72d7fc06c07c43e1c00b67970eaee074e4593;hb=master

**Comment by stfairy** [comment]
Detail steps:

```
git clone git://git.linuxfoundation.org/llvmlinux/kernel.git llvmlinux
cd llvmlinux/
make defconfig
make prepare

~/infer-linux64-v0.1.0/infer/infer/lib/clang/clang_wrapper -Xclang -load -Xclang ~/infer-linux64-v0.1.0/infer/infer/lib/clang/../../../../facebook-clang-plugin/libtooling/build/FacebookClangPlugin.dylib -Xclang -add-plugin -Xclang YojsonASTExporter -I./arch/x86/include -Iarch/x86/include/generated/uapi -Iarch/x86/include/generated -Iinclude -I./arch/x86/include/uapi -Iarch/x86/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -fno-strict-aliasing -fno-common -std=gnu89 -m64 -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -pipe -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -O2 --param=allow-store-data-races=0 -fno-stack-protector -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-strict-overflow -c -o net/ipv4/tcp_ipv4.o net/ipv4/tcp_ipv4.c >ast.json

InferClang -debug -headers -c net/ipv4/tcp_ipv4.c -results_dir infer-out -project_root . -x c <ast.json
```

**Comment by dulmarod** [comment]
Thanks for reporting this. Yes, the clang frontend is still in development and a few constructs are not translated yet. In general, this doesn't represent a problem to an accurate analysis, because we skip the functions that contain untranslated constructs to avoid inconsistencies in the analysis. 
We will continue working on the frontend and also encourage contributions :)

**Comment by chenyunyou** [comment]
2506571489@qq.com

**Comment by jvillard** [comment]
These messages do not show up anymore except when debugging infer. They are harmless as the translation skips over these constructs which is the right thing to do.
