### ISSUE TITLE
Infer Error while loading shared libraries: libtinfo.so.5: cannot open shared object file

### ISSUE THREAD

**Issue by bios8086** [facebook/infer#1400]
I couldn't find a similar solution though there are a lot of posts with the same name.
I just installed the Facebook Infer. I was trying to run the Hello world C example from the website.
https://fbinfer.com/docs/hello-world

My Infer version: 1.0.0
My OS: Linux Mint 20.1 Ulyssa
The commands I ran: infer run -- gcc -c hello.c

I got the following errors:
External Error: Error executing:   /opt/infer-linux64-v1.0.0/lib/infer/infer/bin/../../facebook-clang-plugins/clang/install/bin/clang
                   -c hello.c
exited with code 127

Error backtrace:
Raised at Stdlib.input_line.scan in file "stdlib.ml", line 449, characters 14-31
Called from Stdio__In_channel.input_line_exn in file "src/in_channel.ml" (inlined), line 68, characters 13-30
Called from IBase__Utils.with_channel_in in file "src/base/Utils.ml", line 252, characters 11-44
Re-raised at IBase__Die.raise_error.do_raise in file "src/base/Die.ml" (inlined), line 26, characters 8-56
Called from IBase__Logging.die.(fun) in file "src/base/Logging.ml", line 347, characters 6-39
Called from Integration__Driver.capture in file "src/integration/Driver.ml", line 148, characters 6-40
Called from IBase__Utils.timeit in file "src/base/Utils.ml", line 421, characters 16-20
Called from IBase__ScubaLogging.execute_with_time_logging in file "src/base/ScubaLogging.ml" (inlined), line 79, characters 29-44
Called from Integration__Driver.capture.(fun) in file "src/integration/Driver.ml", line 180, characters 2-233
Called from Backend__GCStats.log_f in file "src/backend/GCStats.ml" (inlined), line 90, characters 10-14
Called from Integration__Driver.capture in file "src/integration/Driver.ml", line 178, characters 2-288
Called from Dune__exe__Infer.run in file "src/infer.ml" (inlined), line 20, characters 2-36
Called from IBase__Utils.timeit in file "src/base/Utils.ml" (inlined), line 421, characters 16-20
Called from IBase__ScubaLogging.execute_with_time_logging in file "src/base/ScubaLogging.ml" (inlined), line 79, characters 29-44
Called from Dune__exe__Infer.run in file "src/infer.ml", line 25, characters 22-94

![Screenshot from 2021-02-27 16-21-56](https://user-images.githubusercontent.com/7280748/109392045-3e85d180-791a-11eb-8622-07cfa45ded63.png)

**Comment by jvillard** [comment]
This looks like #1168, have you tried installing the libtinfo library on your system? Please re-open if there is still an issue.
