### ISSUE TITLE
Build your own Resource Leak analysis, outdated README 

### ISSUE THREAD

**Issue by You-never-know** [facebook/infer#1401]
Hi, 

I am learning how to make my own checker, I am doing the " Build your own Resource Leak analysis " exercise. And I was reading the README.md, where I was reading the chapter " (1) Warm up: running, testing, and debugging Infer "

Where there is an example on how to use infer for this exercise.
" infer -g --resource-leak-only -- javac Leaks.java "

But the parameter " --resource-leak-only " no longer works.

I found in the --help-full, that there is a parameter " --resource-leak-lab ". I think that this is the new parameter used for this exercise.

So can you please update this README,md ? 
https://github.com/facebook/infer/blob/master/infer/src/labs/README.md

Thank you

**Comment by jiseongg** [comment]
Oh, thanks for opening this issue. I was wondering if I had failed some setup for that excercise

**Comment by You-never-know** [comment]
You are welcome, I was wondering that as well, so I did some digging. I found, that " --resource-leak-lab-only" even uses only the files from this exercise.

So it is even better to see how well your implementation works.

**Comment by jvillard** [comment]
Thanks for the report!
