### ISSUE TITLE
code 65

### ISSUE THREAD

**Issue by Supremefjy** [facebook/infer#1405]
Internal Error:   /usr/local/Cellar/infer/0.17.0/lib/infer/infer/bin/../lib/python/infer.py
  -j 8 --project-root /Users/mac/jenkins/workspace/auto-pull-iOS/RoomBox
  --out /Users/mac/jenkins/workspace/auto-pull-iOS/RoomBox/infer-out --
  xcodebuild -target RoomBox -configuration Debug -sdk iphonesimulator:
  exited with code 65
Error backtrace:
Raised at file "string.ml", line 145, characters 16-31
Called from file "string.ml" (inlined), line 149, characters 17-46
Called from file "src/string.ml", line 407, characters 12-33
Called from file "src/string.ml", line 416, characters 11-33
Re-raised at file "base/Die.ml", line 26, characters 8-56
Called from file "integration/Driver.ml", line 171, characters 2-16
Called from file "integration/Driver.ml", line 272, characters 6-409
Called from file "integration/Driver.ml", line 323, characters 2-29
Called from file "base/Utils.ml", line 398, characters 16-20
Called from file "scuba/ScubaLogging.ml", line 66, characters 29-44
Called from file "infer.ml", line 20, characters 2-36
Called from file "base/Utils.ml", line 398, characters 16-20
Called from file "scuba/ScubaLogging.ml", line 66, characters 29-44
Called from file "infer.ml", line 137, characters 8-54

**Comment by Supremefjy** [comment]
Can infier really run？

**Comment by jvillard** [comment]
Can you please re-open this issue with more information? Please include:
- The version of infer from `infer --version`.
- Your operating system and version, for example "Debian 9", "MacOS High Sierra", whether you are using Docker, etc.
- Which command you ran, for example `infer -- make`.
- The full output in a paste, for instance a [gist](https://gist.github.com/).
- If possible, a minimal example to reproduce your problem

**Comment by Supremefjy** [comment]
infer run --keep-going --  xcodebuild -workspace RoomBox.xcworkspace -scheme RoomBox -configuration Debug -sdk iphonesimulator;

**Comment by Supremefjy** [comment]
✘ mac@bogon  ~  infer --version
Infer version v0.17.0
Copyright 2009 - present Facebook. All Rights Reserved.
