### ISSUE TITLE
Xcode oc

### ISSUE THREAD

**Issue by tangmengze** [facebook/infer#1406]
infer --version:    v0.17.0
operating system and version:   MacOS    11.2.1
command:  infer-master ./build-infer.sh

output
xxxxxx....
Are you sure you want to compile clang? (y/N) y
llvm-10.0.1.src.tar.xz: FAILED
shasum: WARNING: 1 computed checksum did NOT match

**Comment by jvillard** [comment]
There isn't enough information to understand what the issue is exactly but I would suggest deleting facebook-clang-plugins/clang/src/download/* and trying again.
