### ISSUE TITLE
[Java] False positive on Nullable

### ISSUE THREAD

**Issue by denizt** [facebook/infer#141]
Infer doesn't call Android's TextUtils I guess?
```java
	public State(@Nullable String states) {
		if (!TextUtils.isEmpty(states)) {
			mSegments = states.split(";");
			trimSegments();
		} else {
			mSegments = new String[0];
		}
	}
```
Causes NULL_DEREFERENCE

**Comment by jeremydubreil** [comment]
Hi @denizt. Thanks for reporting this. Yes, Infer does not currently analyses the standard libraries. It only analyses what gets compiled and does not know what `TextUtils.isEmpty` does in this case. It especially does not know that `TextUtils.isEmpty(states)` returns `true` when `statues == null`. 

I am keeping this task opened for now as we may start to analyse some part of the standard library in the future, which could fix this false positive.

**Comment by denizt** [comment]
Would something like https://github.com/denizt/infer/commit/108dfb15330c8d56a5581b709f044269dd732dbb be OK to fix the problem?

**Comment by jeremydubreil** [comment]
Yes, thanks for the pull request. This should solve the issues involving `TextUtils.isEmpty()`
