### ISSUE TITLE
Can RacerD support C/C++ programs? Does it need annotations?

### ISSUE THREAD

**Issue by ycaibb** [facebook/infer#1426]
Dear Developers:
       Recently, I am using RacerD to scan C/C++ projects. I found, in some multi-threaded projects, RacerD does not report any race warnings. Does it need any annotations? What are the possible reasons? Thank you for the answer.

**Comment by ngorogiannis** [comment]
RacerD does report on C++/ObjC classes (it analyses but does not report on isolated C functions). Annotations are not used. The contract checked is the following:
If any method of a class uses locking directly (not transitively), then read/write races are reported on that class. 
These data races must be between a write under lock and a read without a lock.

**Comment by ycaibb** [comment]
Thank you for the answer. My understanding is that RacerD does not support a pure C program. Right?

**Comment by ngorogiannis** [comment]
That is correct.  The functions may be analysed but there will be no report, as there is no global inference of what functions may run in parallel.  That's the reason RacerD focusses on classes.

**Comment by ycaibb** [comment]
Thank you indeed!

**Comment by ngorogiannis** [comment]
Closing, feel free to reopen if you have more questions on this.

**Comment by ngorogiannis** [comment]
Infer, in general, has no Scala parsing. That means that no analyser works with Scala at the moment.

**Comment by yokurang** [comment]
Right, I am thinking of converting my Scala files into Bytecode and then decompile it into Java source. That way, I can use RacerD. I am still a student, but I wanted to ask your thoughts on this?
