### ISSUE TITLE
Contributing: Several errors running `make devsetup`

### ISSUE THREAD

**Issue by tony-go** [facebook/infer#1436]
Hi everyone 👋 

I'm trying to run Infer locally but I face several issues. I try to fixed them one by one but it seems endless ahah ^^

I saw in the `Makefile.autoconf` this comment: `# override in your `make` command to make the install relocatable`. Maybe should I change some variables, but I don't really know where I could start.

If probably drop some steps in the documentation. Sorry in advance if it's the case. 🙏 

Errors I faced: 
- Replace `Makefile.autoconfig.in` by `Makefile.autoconfig` 
- Comment the line `@SET_MAKE@` to avoid `Makefile.autoconf:6: *** missing separator.  Stop.`
- Replace  `date` by `/bin/date`

Additional Information:
- The version of infer: 1.1.0
- OS: BigSur 11.2.3
- Command: `$ make devsetup` - `$ make -j`
- Output:
```
[14:27:38][77137] installing ocp-indent merlin utop webbrowser tuareg...
[*ERROR**][77137] *** ERROR 'installing ocp-indent merlin utop webbrowser tuareg'
[*ERROR**][77137] *** command: ' OPAMSWITCH=@OPAMSWITCH@; @OPAM@ install --yes --no-checksum user-setup ocp-indent merlin utop webbrowser tuareg'
[*ERROR**][77137] *** CWD: '/Users/tonygorez/perso/infer'
[*ERROR**][77137] *** stdout:
bash: sed: command not found
make: *** [devsetup] Error 127
```

**Comment by jvillard** [comment]
This file is for ./configure to fill in, it's not meant to be used directly. Have you tried building infer with `./build-infer.sh`? This basically runs `./autogen.sh && ./configure && make`. You seem to be missing the first two steps. See here for more instructions: https://github.com/facebook/infer/blob/master/INSTALL.md#install-infer-from-source

**Comment by tony-go** [comment]
Hi @jvillard 👋 

Thanks a lot for you time ^^ In fact, I'd an issue with brew on my machine. 

I succeed to build from sources, modify the source code, rebuild and see changes happen.

The hacking journey's starting here 💪  I'll reverse eng the code to understand the flow.
