### ISSUE TITLE
CalledprocessError

### ISSUE THREAD

**Issue by zekey2005** [facebook/infer#144]
hi,guys,i have encountered a problem when using infer in my project
Xcode version:6.1.1
python version:2.7.6
infer version:0.2.0
error message:
CompileC build/ttpic.build/Release-iphoneos/ttpic.build/Objects-normal/armv7/RequestF.o ttpic/Source/Modal/Serializable/RequestF.mm normal armv7 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Traceback (most recent call last):
  File "/Users/rico/Downloads/infer-0.2.0/infer/bin/../lib/capture/xcodebuild.py", line 69, in capture
    subprocess.check_call(self.cmd, env=self.get_envvars())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['xcodebuild', '-target', 'ttpic', '-configuration', 'Release', '-sdk', 'iphoneos', 'build', 'CODE_SIGN_IDENTITY=', 'CODE_SIGNING_REQUIRED=NO', 'CC=/Users/rico/Downloads/infer-0.2.0/infer/bin/../lib/capture/clang', 'CPLUSPLUS=/Users/rico/Downloads/infer-0.2.0/infer/bin/../lib/capture/clang++', 'GCC_PRECOMPILE_PREFIX_HEADER=NO']' returned non-zero exit status 65
None

**Comment by martinoluca** [comment]
Hello @zekey2005,
Could you please paste here the error message provided by xcodebuild? Usually it's located above the one you've just pasted.

By just looking at this paste, try also running the infer command with `-sdk iphonesimulator -configuration Debug`.

Thanks

**Comment by zekey2005** [comment]
Hi @martinoluca ,
I have tried many ways to compile ,such as: infer -- xcodebuild -target ttpic -configuration Release -sdk iphoneos  or infer -- xcodebuild -target ttpic -configuration Release -sdk iphonesimulator,both failed.
error message is the same as above

**Comment by zekey2005** [comment]
But if compiled with xcodebuild ,that's ok

**Comment by wielkapala** [comment]
20 lip 2015 08:51, "zekey2005" <notifications@github.com> napisał(a):

**Comment by jvillard** [comment]
please provide more info if this issue is still current
