### ISSUE TITLE
Incremental analysis: more issues detected after adding only a new line to a source file

### ISSUE THREAD

**Issue by zyh1121** [facebook/infer#1442]
Please make sure your issue is not addressed in the [FAQ](https://fbinfer.com/docs/support#troubleshooting).

Please include the following information:
- [x] The version of infer from `infer --version`.
```shell
$ infer --version
Infer version v1.1.0
Copyright 2009 - present Facebook. All Rights Reserved.
```
- [x] Your operating system and version, for example "Debian 9", "MacOS High Sierra", whether you are using Docker, etc.
```shell
Ubuntu 20.04
```
- [x] Which command you ran, for example `infer -- make`.
```shell
infer run --reactive --bufferoverrun --pulse --bo-field-depth-limit 3 \
--no-linters  --no-fragment-retains-view \
--no-inefficient-keyset-iterator --no-self-in-block  --enable-issue-type ARRAY_OUT_OF_BOUNDS_L1  \
--enable-issue-type ARRAY_OUT_OF_BOUNDS_L2  --enable-issue-type ARRAY_OUT_OF_BOUNDS_L3  \
--enable-issue-type BUFFER_OVERRUN_L4  --enable-issue-type BUFFER_OVERRUN_L5  \
--enable-issue-type BUFFER_OVERRUN_U5  --enable-issue-type INTEGER_OVERFLOW_L5  \
--enable-issue-type INTEGER_OVERFLOW_U5 \
-j 1 -- make -j 1
```
- [x] The full output in a paste, for instance a [gist](https://gist.github.com/).
**After adding a new line to a source file, infer found 120 more issues in the incremental build.** Please refer to 
https://gist.github.com/zyh1121/9d5db5b3c556a20ac827f27a260532fa#file-libtiff_incremental-sh-session-L486

- [ ] If possible, a minimal example to reproduce your problem (for instance, some code where
    infer reports incorrectly, together with the way you run infer to reproduce the incorrect
    report).

**Comment by jvillard** [comment]
Infer reports all the issues found in all the functions that were analysed in the run. In your case, changing one line triggered the analysis of all the functions in that file, and of all the functions transitively called by functions in the file. Infer then reported all the issues found during the analysis, in this case 120 of them.

You can tell infer that you are only interested in the new issues by comparing the old report and the new report using `infer reportdiff` as explained on [this page](https://fbinfer.com/docs/steps-for-ci#differential-workflow).

I hope this clears things up. Please re-open if you have more questions about this.

**Comment by SolomonSun2010** [comment]
Infer报告在运行中分析的所有功能中发现的所有问题。在您的例子中，更改一行会触发对该文件中所有函数的分析，以及文件中函数传递调用的所有函数的分析。
