### ISSUE TITLE
Investigating intermediate live variables

### ISSUE THREAD

**Issue by shashank-srikant** [facebook/infer#1459]
I am new to Infer (and partially to OCaml), and have been trying to investigate the set of live variables generated in [`infer/src/liveness.ml, L171`](https://github.com/facebook/infer/blob/master/infer/src/checkers/liveness.ml#L171-L178) for each line of input source code that is parsed.

Specifically, at the end of each call, i'd like to look at what `Domain` stores, and eventually store these intermediate results in the `sqlite` datastore that's set up in the codebase.

1. What's the easiest way for me to print `Domain`'s current set of values to the console at the end of that method? I realize this may be a trivial OCaml thing, to which i'm fairly new to as well. I see most of the abstraction domains have pretty printers defined as well. I'm unsure though how to use it. 
2. How do I use the `F.fprintf ` facility I see used in the code base for printing and logging these kinds of intermediate results?
3. I would like to investigate the set of live variables at each lines of code. Any suggestions on how I can hook into it?
4. How do i store and retrieve such information from the `sqlite` datastore?

Would appreciate it if you could point me to the right resources/example code snippets which achieve something similar, that would be very useful.

Thanks.

**Comment by jvillard** [comment]
Hi @shashank-srikant, let me answer here too for posterity: to get the abstract state at each program point you can browse the html debug output, which you can get with `--debug` or `-g` (there's also an option to get just the html debug without other debug options, see the manuals): `infer -g -- clang -c foo.c` then open the html files infer-out/captured/*.html.

There are a bit more details in the [lab exercise](https://github.com/facebook/infer/blob/master/infer/src/labs/README.md#1-warm-up-running-testing-and-debugging-infer).

**Comment by shashank-srikant** [comment]
Thank you so much @jvillard for your timely offline help.
I'll add more details to the specific questions i had raised, in case others find it useful.

> What's the easiest way for me to print Domain's current set of values to the console at the end of that method? 

Just a simple `print_string(Domain.name)` or any property of `Domain` prints the desired property of `Domain`.

> How do I use the F.fprintf facility I see used in the code base for printing and logging these kinds of intermediate results?

Most data types have a pretty printing method defined, which will help display the string-equivalent of the object.
Simply printing to the console via `print_string(xx)` should suffice.

> I would like to investigate the set of live variables at each lines of code. Any suggestions on how I can hook into it?

The set of live variables can be read off of a call to `extract_pre` or  `extract_post` in https://github.com/facebook/infer/blob/master/infer/src/absint/AbstractInterpreter.ml#L420

> How do i store and retrieve such information from the sqlite datastore?

A method can be defined in the `DBWriter` class. See the usage of `add_source_file` (https://github.com/facebook/infer/blob/master/infer/src/base/DBWriter.ml#L294-L296) as an example.
To retrieve information from this `sqlite` information, you could use a simply Python script and use the `sqlite` package to create a connection to, and read the table into a Pandas dataframe.
