### ISSUE TITLE
A false negative from Infer's official document

### ISSUE THREAD

**Issue by Belle-PL** [facebook/infer#1464]
1. Infer version: v1.1.0

2. OS version: Ubuntu 20.04, No Docker

3. Command: infer run --inefficient-keyset-iterator -- javac target_file.java

4. Full output
```
Capturing in javac mode...
Found 1 source file to analyze in /home/user_name/infer-out
1/1 [################################################################################] 100% 101ms

  No issues found  
```

5. A minimal example to reproduce

```java
void foo(String k, Integer v) {
    System.out.println(k + v);
}
void checkEfficientIterator(HashMap<String, Integer> map) {
    for(String key : map.keySet()) {
        Integer value = map.get(key); // Should report a issue here
        foo(key, value);
    }
}
```
Actually, this case is the same as [official case](https://fbinfer.com/docs/all-issue-types#inefficient_keyset_iterator) here.

**Comment by Belle-PL** [comment]
@jvillard, Hi Dr.Villard, could you please help me check this issue? I think this problem is importatant because it is related to document. Thanks!

**Comment by Belle-PL** [comment]
@rgrig, Hi, Radu, could you please help me check this issue caused by inconsistency between doc and tool?

**Comment by jvillard** [comment]
Hi @Belle-PL, I am unable to reproduce your problem, Infer correctly reports the issue for me. Please re-open if there is still an issue.

PS: The "inefficient keyset iterator" checker is enabled by default, no need to pass the option on the command line.
