### ISSUE TITLE
.cpp compile error

### ISSUE THREAD

**Issue by guafei** [facebook/infer#147]
When I use command "infer -- xcodebuild -workspace xxx.xcworkspace -scheme xxxx", it compiles error that "CompileC /xxx/CADebugMacros.cpp normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler (1 failures)", as we all know, infer does not support c++ analyze, so how can I build success my project with c++ files.
Thanks.

**Comment by martinoluca** [comment]
Hello @guafei,
could you please provide the error reported by xcodebuild?
Usually there's a more detailed error message above the one you've just pasted.

Thanks.

**Comment by guafei** [comment]
Hi @martinoluca,

The error message is 
"The following build commands failed:
	CompileC /Users/guafei/Library/Developer/Xcode/DerivedData/Mogujie4iPhone-fdcbfyexveuuwwfyasfuhajbixfl/Build/Intermediates/Pods.build/Debug-iphoneos/Pods-Mogujie4iPhone-DDIMSDK.build/Objects-normal/armv7/CAStreamBasicDescription.o DDIMSDK/IOSDuoduo/IOSDuoduo/Voice/manager/PublicUtility/CAStreamBasicDescription.cpp normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/guafei/Library/Developer/Xcode/DerivedData/Mogujie4iPhone-fdcbfyexveuuwwfyasfuhajbixfl/Build/Intermediates/Pods.build/Debug-iphoneos/Pods-Mogujie4iPhone-DDIMSDK.build/Objects-normal/armv7/CADebugMacros.o DDIMSDK/IOSDuoduo/IOSDuoduo/Voice/manager/PublicUtility/CADebugMacros.cpp normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)"

Please check, thanks.

**Comment by martinoluca** [comment]
First try running
```
 xcodebuild -workspace xxx.xcworkspace -scheme xxxx clean
```
then run infer again.

Then there must be an error from clang saying what went wrong during the compilation. What you are providing is a summary of the build steps that failed while xcodebuild was running.

Thanks.

**Comment by guafei** [comment]
Hi @martinoluca ,

Sorry for forget provide key message, I have follow you steps, clean the project then build it, but the error message is 
"In file included from /Users/guafei/Desktop/Mogujie/projects/mogujie-iphone/Pods/DDIMSDK/IOSDuoduo/IOSDuoduo/Voice/manager/PublicUtility/CAXException.cpp:47:
In file included from /Users/guafei/Desktop/Mogujie/projects/mogujie-iphone/Pods/DDIMSDK/IOSDuoduo/IOSDuoduo/Voice/manager/PublicUtility/CAXException.h:56:
/Users/guafei/Desktop/Mogujie/projects/mogujie-iphone/Pods/DDIMSDK/IOSDuoduo/IOSDuoduo/Voice/manager/PublicUtility/CADebugMacros.h:101:42: error: invalid suffix on literal; C++11
      requires a space between literal and identifier [-Wreserved-user-defined-literal]
                #define DebugMessage(msg)       DebugStr("\p"msg)
                                                             ^
"

it seems that the C++11 grammar problem ?  Thanks.

**Comment by guafei** [comment]
Hi @martinoluca, @jeremydubreil, @dulmarod

My project has builded and analyzed successful, it is great, keep in touch and have a good weekend.

Regards & Thanks

**Comment by martinoluca** [comment]
Hello @guafei,
Please feel free to share here how you solved the issue, so that other people can do the same in case they encounter a similar problem.

Thanks.
