### ISSUE TITLE
No leak reported, but still have leak

### ISSUE THREAD

**Issue by azevedogustavo** [facebook/infer#1472]
information:
-  version: v1.1.0-2b144509a
- OS: Ubuntu 18.04.5 LTS  on host, kernel 5.4.0-77-generic, g++ 7.5.0
- Comand: infer --keep-going -- g++ -g
- No issues found (but still have leak)

snippet code

```c++
#include <iostream>
using namespace std;

struct noisy
{
    noisy() { cout << "constructing noisy" << endl; }
    ~noisy() { cout << "destroying noisy" << endl; }
};

int main()
{
    noisy* p = new noisy[3];
    delete p;
    return 0;
}
```

**Comment by jvillard** [comment]
Thanks. There is work to be done to detect leaks in C++. Namely here, to detect this one, the Pulse analysis should be improved to understand `new` and `delete` (currently it handles `malloc` and `free`). Writing this here for reference:
- model `new` and `new[]` as allocating one and several cells, respectively (like [`malloc`](https://github.com/facebook/infer/blob/50c3f0ba64236ed61550a731daac4fefde79dea6/infer/src/pulse/PulseModels.ml#L223))
- model `delete` and `delete[]` as deleting one and several cells, respectively (like [`free`](https://github.com/facebook/infer/blob/50c3f0ba64236ed61550a731daac4fefde79dea6/infer/src/pulse/PulseModels.ml#L170))
- After that pulse should be able to report the two cells leaked in this program.
