### ISSUE TITLE
@SuppressLint without android?

### ISSUE THREAD

**Issue by bakkot** [facebook/infer#1475]
The [FAQ](https://fbinfer.com/docs/support/) says that in Java you can suppress warnings with `@SuppressLint("infer")`. That appears to be an android-only thing. Is there a way to suppress spurious warnings for non-android Java projects?

(The specific error is in code similar to

```java
List<T> keys = new ArrayList(map.keys());
// ...
for (T key : key) {
  map.get(key).method();
}
```
which, I understand why it can't do this inference correctly, but I would like to suppress the warning.)

**Comment by ngorogiannis** [comment]
What issue are you seeing exactly?

Annotations are generally matched in Infer by the last component of the qualified path, so essentially the package is ignored. This is so as to allow use cases like yours.  In other words you can define your own `@SuppressLint` annotation and use it to suppress issues, like `@SuppressLint("ISSUE_TYPE")`.

Support may be patchy across analysers though hence my question about issue type, but I'd try that first.

**Comment by bakkot** [comment]
Oh, I didn't realize you could just define your own annotation. I can't seem to get it to work, though.

It's specifically a null dereference warning I'm trying to suppress. Here's a concrete example:

in `src/main/java/example/com/Main.java`:

```java
package main.java.example.com;

import java.util.HashMap;

public class Main {
    @SuppressLint("infer")
    public static void main(String[] args) {
        HashMap<String, String> map = new HashMap<>();

        map.put("foo", "bar");
        map.put("bar", "baz");

        String s = map.get(map.get("foo"));
        System.out.println(s.length());
    }
}
```

in `src/main/java/example/com/SuppressLint.java`:
```java
package main.java.example.com;

public @interface SuppressLint {
    String value();
}
```

(and a generic pom.xml I'll omit)

And then:

```
$ infer --version
Infer version v1.1.0
Copyright 2009 - present Facebook. All Rights Reserved.

$ infer -- mvn compile
[...]
src/main/java/example/com/Main.java:14: error: Null Dereference
  object `s` last assigned on line 13 could be null and is dereferenced at line 14.
  12.
  13.           String s = map.get(map.get("foo"));
  14. >         System.out.println(s.length());
  15.       }
  16.   }


Found 1 issue
          Issue Type(ISSUED_TYPE_ID): #
  Null Dereference(NULL_DEREFERENCE): 1
```

**Comment by ngorogiannis** [comment]
Try `@SuppressLint("NULL_DEREFERENCE")`. I'm not sure whether it'll work as support for this may depend on the analyser.

**Comment by bakkot** [comment]
Yup, that seems to have done it, thanks! Seems like the FAQ should be updated?
