### ISSUE TITLE
Heisenbug when running several instances of infer in parallel

### ISSUE THREAD

**Issue by andrewhabib** [facebook/infer#1476]
- infer version: v1.1.0
- os version: Ubuntu 20.04.2 LTS (through Docker)
- command: infer -- run
- running infer in javac mode

Hi,

This issue is not regarding an incorrect output, but rather a non-deterministic crash heisenbug sort of.
So basically the observed anomalous behavior is that infer crashes where it is not supposed to.

Here is the scenario:

I run several parallel instances of Infer to analyze _different_ projects. 
I instantiate the different infer runs using a python script and the joblib Parallel API together with the subprocess module to invoke several instance of infer at once. 
Every time I run my python script, infer crashes on a small subset of the analyzed projects... and this subset of projects that infer crashes on is not the same... with every run, infer crashes on different subset of the analyzed projects.

I describe them as heisenbugs for two reasons:

1) When I try to investigate a single crash, e.g., by invoking infer myself (not in the parallel script case) using the same exact command, the crash bug never shows and infer analyses the project correctly.

2) The set of projects where infer crashes on, changes with every run of my parallel script. I.e., infer does not crash on the same projects with every run.

Here is an example of a crash trace:

```
Capturing in javac mode...
Uncaught Internal Error: (IO.No_more_input)
Error backtrace:
Raised at IO.input_channel.(fun) in file "IO.ml", line 310, characters 23-42
Called from IO.read_byte in file "IO.ml" (inlined), line 423, characters 30-43
Called from IO.BigEndian.read_real_i32 in file "IO.ml", line 645, characters 43-57
Called from JParse.parse_class_low_level in file "jParse.ml", line 674, characters 14-30
Called from JFile.extract_class_name_from_file in file "jFile.ml", line 175, characters 10-44
Called from JavaFrontend__JClasspath.load_from_verbose_output.loop in file "src/java/jClasspath.ml", line 119, characters 14-55
Called from IBase__Utils.with_file_in.f in file "src/base/Utils.ml" (inlined), line 231, characters 13-17
Called from IBase__Utils.do_finally_swallow_timeout in file "src/base/Utils.ml" (inlined), line 215, characters 8-12
Called from IBase__Utils.try_finally_swallow_timeout in file "src/base/Utils.ml" (inlined), line 225, characters 16-54
Called from IBase__Utils.with_file_in in file "src/base/Utils.ml", line 233, characters 2-41
Re-raised at IStdlib__IExn.reraise_after in file "src/istd/IExn.ml" (inlined), line 13, characters 2-50
Called from IBase__Utils.do_finally_swallow_timeout in file "src/base/Utils.ml" (inlined), line 217, characters 6-141
Called from IBase__Utils.try_finally_swallow_timeout in file "src/base/Utils.ml" (inlined), line 225, characters 16-54
Called from IBase__Utils.with_file_in in file "src/base/Utils.ml", line 233, characters 2-41
Called from JavaFrontend__JClasspath.load_from_verbose_output.(fun) in file "src/java/jClasspath.ml" (inlined), line 140, characters 4-116
Called from JavaFrontend__JClasspath.with_classpath in file "src/java/jClasspath.ml" (inlined), line 204, characters 8-49
Called from JavaFrontend__JMain.main in file "src/java/jMain.ml", line 124, characters 2-171
Called from JavaFrontend__JMain.from_verbose_out in file "src/java/jMain.ml" (inlined), line 131, characters 40-91
Called from Integration__Javac.capture in file "src/integration/Javac.ml", line 127, characters 8-47
Called from Integration__Driver.capture in file "src/integration/Driver.ml", line 136, characters 6-40
Called from IBase__Utils.timeit in file "src/base/Utils.ml", line 429, characters 16-20
Called from IBase__ScubaLogging.execute_with_time_logging in file "src/base/ScubaLogging.ml" (inlined), line 79, characters 29-44
Called from Integration__Driver.capture.(fun) in file "src/integration/Driver.ml", line 159, characters 2-233
Called from Backend__GCStats.log_f in file "src/backend/GCStats.ml" (inlined), line 90, characters 10-14
Called from Integration__Driver.capture in file "src/integration/Driver.ml", line 157, characters 2-288
Called from Dune__exe__Infer.run in file "src/infer.ml" (inlined), line 20, characters 2-36
Called from IBase__Utils.timeit in file "src/base/Utils.ml" (inlined), line 429, characters 16-20
Called from IBase__ScubaLogging.execute_with_time_logging in file "src/base/ScubaLogging.ml" (inlined), line 79, characters 29-44
Called from Dune__exe__Infer.run in file "src/infer.ml", line 25, characters 22-94

Run the command again with `--keep-going` to try and ignore this error.
```

It is to be noted that the crash trace is different from one crash to to another... but all crashes share the same reported root cause:

``Uncaught Internal Error: (IO.No_more_input)``

Any idea why/how this happens and how to solve it?

**Comment by ngorogiannis** [comment]
Some quick questions:

Do you use a unique results directory for each run? (`-o` argument) That could easily cause issues.

Is there any way common dependencies of projects to be compiled by two different runs? In general, the javac integration compiles code into class files and parses those.  Racing on compiling the class files might cause problems.

**Comment by andrewhabib** [comment]
Hi @ngorogiannis ,

Thank you for your response.

I explicitly use `-o` with a unique output directory for each run. So probably it is not this one.

Mmm... Definitely there are common dependencies among the different runs... and I don't do anything specific to prevent repeated compilation of the same classes by the different parallel runs of infer.
_Which directory does infer use for compiling the classes?_ 
If it uses the current working directory (by looking closely at logs and stack traces, it seems to be the case), then probably this is the reason since all my parallel runs inherit the working directory of the parent process. 
Or wait! Since I am running infer in javac mode, it uses the javac output directory, which when not explicitly specified using the `-d` argument, would default to the current working directory.

**Comment by ngorogiannis** [comment]
Infer doesn't override what the build system dictates, generally, so I believe your last guess about `-d` might be correct.

**Comment by andrewhabib** [comment]
I can confirm that using the `-d` argument for javac with a unique output directory for every parallel run eliminates the problem.
Gonna close the issue.

Thank you for your prompt help!
