### ISSUE TITLE
Infer Deadlock Checker

### ISSUE THREAD

**Issue by jenny-cheung** [facebook/infer#1485]
Hi, developers:
          It seems Infer can detect deadlock now, which is wonderful! When would it be open-source?

```
A Compositional Deadlock Detector for Android Java [BibTeX]
James Brotherston, Paul Brunet, Nikos Gorogiannis and Max Kanovich. Revised version coming soon, to appear in Proceedings of ASE-36, 2021.
```
       
Best,

**Comment by andrewvaughanj** [comment]
Why do you think that this is any different that the deadlock detectors that are already included in Infer? I read "Revised version coming soon" to mean the _paper_, not the implementation.

Indeed, to quote the paper:

> Our analyser is built inthe INFER verification framework and has been in industrial deployment for over two years; it has seen over two hundred fixed deadlock reports with a report fix rate of ∼54%.
>

and

> The analyser (named starvation) is open-source code included in INFER, see https://fbinfer.com/
>

and

> Our deadlock analyser has been de-ployed at Facebook as part of the INFER framework for the last two years and has resulted in hundred of potential bugs being flagged, with an actual developer fix rate of over 50%(and we note that this does not imply a false positive rate of nearly 50%). 
>

**Comment by jenny-cheung** [comment]
@andrewvaughanj OK, thank you very much for your answers.

**Comment by jenny-cheung** [comment]
@andrewvaughanj Can infer also detect communication deadlocks?

**Comment by ngorogiannis** [comment]
No, the starvation analysis detects only lock-based deadlocks currently.

**Comment by jenny-cheung** [comment]
Ok, thanks~

**Comment by jenny-cheung** [comment]
@ngorogiannis Could infer's deadlock checker handle C/C++ programs?

**Comment by ngorogiannis** [comment]
Yes, it can handle C/C++ and it also reports self-deadlocks.

**Comment by jenny-cheung** [comment]
@ngorogiannis  Thank you. By the way, could be data race detector also work for the C/C++ program?
