### ISSUE TITLE
Fatal error: exception Assert_failure(clang/cTrans.ml, 1378, 24)

### ISSUE THREAD

**Issue by stfairy** [facebook/infer#15]
It seems that unexpected AST nodes are encountered.  For example:
- OffsetOfExpr
- CompoundLiteralExpr
- ImplicitValueInitExpr
- GCCAsmStmt

Are they going to be supported?

**Comment by dulmarod** [comment]
Hi,
yes, the clang frontend is still in development and a few constructs are not translated yet. We will work on them soon. 
What we do right now is to skip the whole function where an unexpected AST node is encountered to avoid inconsistencies in the analysis. 

We also encourage contributions!

**Comment by jvillard** [comment]
These instructions are handled more gracefully now and no error is shown to the user anymore. If there are specific issues caused by the translation then let's open other issues for them.
