### ISSUE TITLE
Add a way to filter out false positives

### ISSUE THREAD

**Issue by denizt** [facebook/infer#150]
Currently there is no way to filter out false positives. Approaches [FindBugs](http://findbugs.sourceforge.net/manual/filter.html) use are `filter files` and `annotations` --which brings the dependency complexity. In our set up, we use the file approach, which resides in the repository and run by the build servers.

A similar approach would simplify deploying infer.

**Comment by jeremydubreil** [comment]
Yes, you can create a JSON file named `.inferconfig` which should be in the directory where Infer is run. This allow to enable or disable the analysis at the level of files or directory. For example:

```json
{
  "infer_whitelist": [
    "src/",
  ],
  "infer_blacklist": [
    "src/third-party/"
  ],
  "infer_blacklist_files_containing": [
    "@DISABLE_INFER"
  ]
}
```

will have the effect of enabling Infer on all the files in the `src/` sub-directory unless they are under `src/third-party` or they contain the string `@DISABLE_INFER`.

I hope that is what you are talking about. The Sourceforge website is unreachable so I cannot access the FindBugs documentation.

**Comment by denizt** [comment]
I think @sblackshear is working on something similar to FindBugs' SupressWarnings annotation, or maybe I am misreading a9b6f33940554629538cecd1c36ccb291da9ce78? For further reference, please see [the stackoverflow question] (http://stackoverflow.com/questions/1829904/is-there-a-way-to-ignore-a-single-findbugs-warning)

**Comment by sblackshear** [comment]
@denizt Yes, Infer now supports the java.lang `@SuppressWarnings` [annotation](http://docs.oracle.com/javase/7/docs/api/java/lang/SuppressWarnings.html). You can write `@SuppressWarnings("infer")` or `@SuppressWarnings("null")` on a method/class to suppress all warnings on the method/methods belonging to the class.

This does indeed seem to be very similar to the FindBugs feature you mention. Hope this helps you; feel free to close the issue if so or tell us what else would be useful if not!

**Comment by denizt** [comment]
Yes, indeed this was the feature request :) Thanks!

**Comment by sveinungkb** [comment]
Have anyone successfully used the `@SupressWarnings` annotation with Java infer? Tried both 0.5.0 and 0.6.0 and it still gives false positives on closing a `InputStream`.

@sblackshear this is supposed to work, right?
```
    @SuppressWarnings("infer") // tried "" and "infer", same result
    public void set(int index, String value) throws IOException {
        Writer writer = null;
        try {
            writer = new OutputStreamWriter(newOutputStream(index), DiskLruCache.UTF_8);
            writer.write(value);
        } finally {
// Checks if writer is null, then closes capturing any exceptions.
            closeQuietly(writer);
        }
    }
```

**Comment by jeremydubreil** [comment]
Hi @sveinungkb. Which build system are you using ?

**Comment by sveinungkb** [comment]
gradle (Android):

```
Infer version v0.6.0-2479f69
gradle 2.4
compileSdkVersion 22
buildToolsVersion "22.0.1"
```

**Comment by sveinungkb** [comment]
@jeremydubreil sorry for the potential spam, but forgot to mention you so not sure if github sent any response email.

**Comment by sblackshear** [comment]
This is currently broken in Gradle because the annotation processor we use to collect the source-level SuppressWarnings annotations always writes to the same file :/ (potentially clobbering other SuppressWarnings information). We are working on fixing this.

**Comment by sveinungkb** [comment]
Thanks for the update @sblackshear, what are my options for whitelisting a file/class/method today?
Any issue I can follow?

**Comment by sblackshear** [comment]
Sorry for the slow response. As a temporary workaround, you can suppress things at the file level by adding a .inferconfig JSON file to the root directory for your project. If you want to suppress warnings for the entire file `path/from/project/root/to/MyClass.java`, this file would look like:

```
{
  "infer_blacklist": [
    "path/from/project/root/to/MyClass.java"                 
  ]
}
```

I'll post in this issue when we fix the issues with SuppressWarnings in Gradle.

**Comment by jvillard** [comment]
annotations work with gradle since version 0.8.0

**Comment by ozmium** [comment]
The follow things do not work for me to suppress the Infer warnings of `getActivity() = null` or `Nullable`:

```java
@SuppressWarnings({"ConstantConditions", "infer"})
AlertDialog.Builder builder = new AlertDialog.Builder(getActivity(), R.style.AppCompatDialogStyle);

@SuppressWarnings({"ConstantConditions", "null"})
AlertDialog.Builder builder = new AlertDialog.Builder(getActivity(), R.style.AppCompatDialogStyle);

@SuppressWarnings("infer")
AlertDialog.Builder builder = new AlertDialog.Builder(getActivity(), R.style.AppCompatDialogStyle);

@SuppressWarnings("ConstantConditions")
AlertDialog.Builder builder = new AlertDialog.Builder(getActivity(), R.style.AppCompatDialogStyle);
```

The warning is only suppressed in Android Studio, via the `"ConstantConditions"` tag. But infer ignores all these tags. It also doesn't work if the `@SuppressWarnings` is applied to the whole class.

What am I doing wrong?

```
Infer version 0.16.0
Linux
Android Gradle builds
compileSdkVersion 28
targetSdkVersion 28
implementation 'com.android.support:appcompat-v7:28.0.0'
implementation 'com.android.support:design:28.0.0'
```
