### ISSUE TITLE
No docs for Infer-Sharp

### ISSUE THREAD

**Issue by TomMD** [facebook/infer#1522]
I'd love to try infer-sharp now that it is merged but am entirely unclear on how to use the feature.  For example, the infer-sharp microsoft repository has a run-infer-sharp shell script that has many bash-isms and implies it runs over DLLS (https://github.com/microsoft/infersharp/blob/main/run_infersharp.sh).   What is the method now that this code is merged into infer?

**Comment by jvillard** [comment]
Hi @TomMD, Infer# is not completely merged into the infer repo, only the part that can ingest and analyse the results of the Infer# frontend is (the part common between infer and infer#).

**Comment by TomMD** [comment]
Ahh, I had a massive misunderstanding! Thank you.
