### ISSUE TITLE
Integration with Travis CI

### ISSUE THREAD

**Issue by Hesamedin** [facebook/infer#153]
Hi, I want to integrate Infer into Travis but have no idea of the possibility. So is it possible?
If yes, can you provide any tips? Since the fact that download of Infer for every particular PR is horrible I'm thinking there might be a way of caching it somewhere. Am I able to do that too? 

Thanks

**Comment by hckhanh** [comment]
This is my bash file to install infer for Travis CI
```sh
#!/bin/bash

set -ev

# Install Opaml
wget https://github.com/ocaml/opam/releases/download/1.2.2/opam-1.2.2-x86_64-Linux -O opam
chmod ugo+x opam
./opam init --yes --comp=4.01.0 #(then say 'y' to the final question)
eval `./opam config env`
./opam install --yes sawja.1.5 atdgen.1.5.0 javalib.2.3a extlib.1.5.4 #(then say 'y' to the question)

# Install infer (latest version)
git clone https://github.com/facebook/infer.git
cd infer/
make -C infer java
export PATH=`pwd`/infer/bin:$PATH
cd ../

**Comment by Hesamedin** [comment]
You are the man @hckhanh :) Yours works like charm. Thank you.

This is my code which is like yours:
```
#!/bin/bash

set -ev

echo "*** TRY TO INIT INFER ***"



# 1. Install Opaml
echo "> Try to get OPAM package"
wget https://github.com/ocaml/opam/releases/download/1.2.2/opam-1.2.2-x86_64-Linux -O opam
chmod ugo+x opam
./opam init --yes --comp=4.01.0 #(then say 'y' to the final question)
eval `./opam config env`
./opam install --yes sawja.1.5.1 atdgen.1.6.0 javalib.2.3.1 extlib.1.5.4 #(then say 'y' to the question)

# Good reference at http://www.cyberciti.biz/faq/unix-linux-test-existence-of-file-in-bash/
[ -s opam ] && echo "Opam downloaded successfully." || echo "Something went wrong :("



# 2. Install Infer (latest version)
INFER_GIT_PATH="https://github.com/facebook/infer.git"
echo "> Try to Clone Infer from ${INFER_GIT_PATH}"
git clone ${INFER_GIT_PATH}

INFER_PATH="./infer/infer/bin/infer"
if [ -s ${INFER_PATH} ]
then
    echo "Infer downloaded successfully."

    echo "Try to Make Infer."
    cd infer/
    make -C infer java
    export PATH=`pwd`/infer/bin:$PATH
    cd ../

else
    echo "Something went wrong :("
fi



echo "*** INFER INITIALIZATION IS DONE ***"
```

**Comment by Hesamedin** [comment]
@hckhanh Do you have any idea how to cache it on travis in order to prevent installation each time?
i'm not sure it's possible but it's good idea to be able to create Ubuntu custom snapshot based on our needs. Then we always are able to initialize it once and use it when new PR created. Is that possible?

**Comment by hckhanh** [comment]
In Travis, they have an function and it's called **cache**. But I have tried it. It only cache file before the **before_install** is executed.

**Comment by jvillard** [comment]
Hi @Hesamedin, is it ok to close this issue or do you have more questions to be addressed?

**Comment by Hesamedin** [comment]
@jvillard hey dude, yup. go for it!
:+1:
