### ISSUE TITLE
Pulse Java Null Dereference False Positive (logical expressions involving numerical comparison)

### ISSUE THREAD

**Issue by matjin** [facebook/infer#1555]
Looks like pulse has some issues with reasoning about numerical comparison. A couple of false positive examples on an open-source project:

1. 
Seems not to realize that desiredRatePerSec < 0 so the dereference isn't reached.

https://github.com/linkedin/ambry/blob/97b552f4a48cb2d153c41a1c8207520c560383d8/ambry-utils/src/test/java/com.github.ambry.utils/RejectThrottlerTest.java

    "bug_type": "NULLPTR_DEREFERENCE",
    "qualifier": "Pulse found a potential null pointer dereference on line 34 indirectly during the call to `RejectThrottler.shouldThrottle(...)`.",
    "severity": "ERROR",
    "line": 34,
    "column": -1,
    "procedure": "com.github.ambry.utils.RejectThrottlerTest.basicTest():void",
    "procedure_start_line": 31,
    "file": "ambry-utils/src/test/java/com.github.ambry.utils/RejectThrottlerTest.java",
    "bug_trace": [
        {
            "level": 1,
            "filename": "ambry-utils/src/test/java/com.github.ambry.utils/RejectThrottlerTest.java",
            "line_number": 33,
            "column_number": -1,
            "description": "is the null pointer"
        },
        {
            "level": 1,
            "filename": "ambry-utils/src/test/java/com.github.ambry.utils/RejectThrottlerTest.java",
            "line_number": 33,
            "column_number": -1,
            "description": "in call to `RejectThrottler.<init>(long,Meter)`"
        },
        {
            "level": 2,
            "filename": "ambry-utils/src/main/java/com.github.ambry.utils/RejectThrottler.java",
            "line_number": 30,
            "column_number": -1,
            "description": "parameter `meter` of RejectThrottler.<init>(long,Meter)"
        },
        {
            "level": 2,
            "filename": "ambry-utils/src/main/java/com.github.ambry.utils/RejectThrottler.java",
            "line_number": 32,
            "column_number": -1,
            "description": "assigned"
        },
        {
            "level": 1,
            "filename": "ambry-utils/src/test/java/com.github.ambry.utils/RejectThrottlerTest.java",
            "line_number": 33,
            "column_number": -1,
            "description": "return from call to `RejectThrottler.<init>(long,Meter)`"
        },
        {
            "level": 1,
            "filename": "ambry-utils/src/test/java/com.github.ambry.utils/RejectThrottlerTest.java",
            "line_number": 34,
            "column_number": -1,
            "description": "when calling `boolean RejectThrottler.shouldThrottle(long)` here"
        },
        {
            "level": 2,
            "filename": "ambry-utils/src/main/java/com.github.ambry.utils/RejectThrottler.java",
            "line_number": 46,
            "column_number": -1,
            "description": "parameter `this` of boolean RejectThrottler.shouldThrottle(long)"
        },
        {
            "level": 2,
            "filename": "ambry-utils/src/main/java/com.github.ambry.utils/RejectThrottler.java",
            "line_number": 50,
            "column_number": -1,
            "description": "invalid access occurs here"
        }
    ],
    "key": "RejectThrottlerTest.java|basicTest|NULLPTR_DEREFERENCE",
    "hash": "5df112a6514f4cdcaeed3f6ab70edd68",
    "bug_type_hum": "Null Dereference"
}

2. Again seems not to realize that streamSize==0 means that the dereference is not reached.

https://github.com/linkedin/ambry/blob/97b552f4a48cb2d153c41a1c8207520c560383d8/ambry-tools/src/main/java/com.github.ambry/tools/perf/rest/PerfRSC.java

```
{
    "bug_type": "NULLPTR_DEREFERENCE",
    "qualifier": "Pulse found a potential null pointer dereference on line 233 indirectly during the call to `PerfRSC(...)`.",
    "severity": "ERROR",
    "line": 233,
    "column": -1,
    "procedure": "com.github.ambry.tools.perf.rest.PerfNioServer$PerfRestRequest.<init>(com.github.ambry.rest.RestMethod,java.lang.String,byte[],long)",
    "procedure_start_line": 223,
    "file": "ambry-tools/src/main/java/com.github.ambry/tools/perf/rest/PerfNioServer.java",
    "bug_trace": [
        {
            "level": 1,
            "filename": "ambry-tools/src/main/java/com.github.ambry/tools/perf/rest/PerfNioServer.java",
            "line_number": 233,
            "column_number": -1,
            "description": "is the null pointer"
        },
        {
            "level": 1,
            "filename": "ambry-tools/src/main/java/com.github.ambry/tools/perf/rest/PerfNioServer.java",
            "line_number": 233,
            "column_number": -1,
            "description": "when calling `PerfRSC.<init>(byte[],long)` here"
        },
        {
            "level": 2,
            "filename": "ambry-tools/src/main/java/com.github.ambry/tools/perf/rest/PerfRSC.java",
            "line_number": 49,
            "column_number": -1,
            "description": "parameter `bytes` of PerfRSC.<init>(byte[],long)"
        },
        {
            "level": 2,
            "filename": "ambry-tools/src/main/java/com.github.ambry/tools/perf/rest/PerfRSC.java",
            "line_number": 50,
            "column_number": -1,
            "description": "invalid access occurs here"
        }
    ],
    "key": "PerfNioServer.java|<init>|NULLPTR_DEREFERENCE",
    "hash": "5d15db0e964acd88527a271d3b4f151a",
    "bug_type_hum": "Null Dereference"
}
```

**Comment by jvillard** [comment]
Ah, yes, we haven't implement reasoning about floats. Thanks for the report, we'll look into this.
