### ISSUE TITLE
Broken link to PLDI tutorial in documentation

### ISSUE THREAD

**Issue by olegmyrk** [facebook/infer#1566]
The PLDI 2017 tutorial slides link is broken at this page:
https://fbinfer.com/docs/absint-framework/
https://fbinfer.com/downloads/pldi17-infer-ai-tutorial.pdf

**Comment by jvillard** [comment]
Thanks for the report, looks like we lost this at some point. I found it here: https://github.com/facebook/infer/blob/5248925e2c93002e33fb7abdafe416cf4e5f9836/downloads/pldi17-infer-ai-tutorial.pdf

I'll reupload and fix the link. Thanks again!
