### ISSUE TITLE
Disable outputing bug traces in infer bug report

### ISSUE THREAD

**Issue by xi-liu-ds** [facebook/infer#1567]
Hi,

I am wondering is it possible (a command flag or something) to disable outputting bug traces, such as those shown in the screenshot below, in infer bug report?

![image](https://user-images.githubusercontent.com/63893533/145629887-01763149-e2d6-45ea-864e-d86d6717363d.png)

Thanks!

**Comment by jvillard** [comment]
There is no such option at the moment. Can you say more about why you'd want to do this? You can post-process the json to get rid of them (for example using [`jq`](https://stedolan.github.io/jq/)) but these bug traces are generally needed to understand infer reports.

**Comment by xi-liu-ds** [comment]
Currently Sarif Viewer extension has some incompatibility with SARIF files with bug traces. We have to disable it to unblock us from deploying InferSharp on some platforms. I have created [this PR](https://github.com/facebook/infer/pull/1569) to disable outputting bug traces in SARIF files through a `-no-sarif-codeflows` flag.

**Comment by jvillard** [comment]
PR has been closed, issue seems resolved.
