### ISSUE TITLE
FreeBSD Support

### ISSUE THREAD

**Issue by sbennett1990** [facebook/infer#157]
The latest version of FreeBSD supports the latest versions of OCaml, OPAM, and Clang (3.6.2 is in the ports tree) and all the dependencies/libraries in the installation instructions will install successfully (I tried). It seems that it would not be too difficult to include FreeBSD support in the facebook-clang-plugin/clang/setup.sh script.

**Comment by jeremydubreil** [comment]
What do you observe when you run `facebook-clang-plugin/clang/setup.sh` ? Does it fail ?

**Comment by sbennett1990** [comment]
Yes, because currently the script is coded to only run if it detects "Darwin" or "Linux" OS:
```sh
platform=`uname`

if [ $platform == 'Darwin' ]; then
    CONFIGURE_ARGS=(
        --prefix="$CLANG_PREFIX"
        --enable-libcpp
        --enable-cxx11
        --disable-assertions
        --enable-optimized
        --enable-bindings=none
    )
elif [ $platform == 'Linux' ]; then
    CONFIGURE_ARGS=(
        --prefix="$CLANG_PREFIX"
        --enable-cxx11
        --disable-assertions
        --enable-optimized
        --enable-bindings=none
    )
else
    echo "Clang setup: platform $platform is currently not supported by this script"; exit 1
fi
```
It is possible that this conversation belongs in the https://github.com/facebook/facebook-clang-plugins project, but since infer depends on it, I thought I'd start the request here.

**Comment by jeremydubreil** [comment]
Did you try with:

```python
elif [ $platform == 'Linux' ] || [$platform == 'FreeBSD']; then
```
?

The compilation options may be the same on Linux and on FreeBSD. If something like this works, you can try to make a pull request in https://github.com/facebook/facebook-clang-plugins.

**Comment by sbennett1990** [comment]
Ah, yes I did try modifying the script and many of the patches were applied, but the process ultimately ended in failure:
```
Hmm...  The next patch looks like a unified diff to me...
The text leading up to this was:
--------------------------
|Index: utils/TableGen/ClangAttrEmitter.cpp
|===================================================================
|--- utils/TableGen/ClangAttrEmitter.cpp        (revision 231004)
|+++ utils/TableGen/ClangAttrEmitter.cpp        (working copy)
--------------------------
Patching file utils/TableGen/ClangAttrEmitter.cpp using Plan A...
Hunk #1 succeeded at 2674 (offset -5 lines).
done
/tmp/clang-setup.EPqRA5 ~/Dev/infer
../facebook-clang-plugin/clang/setup.sh: llvm/configure: /bin/sh: bad interpreter: Permission denied
```

I ran the script as root, and I tried this first...
```sh
elif [ $platform == 'Linux' ] || [$platform == 'FreeBSD']; then
```
...then I tried 
```sh
elif [ $platform == 'Darwin' ] || [$platform == 'FreeBSD']; then
```
Both attempts failed.

**Comment by jeremydubreil** [comment]
It seems that the failure happens when trying to compile clang itself. Could you try to compile clang directly from the sources in:

https://github.com/facebook/facebook-clang-plugins/blob/ae0700a8f51650118ad832681f23c08491a84d98/clang/src/clang-3.6.1.tar.xz

?

The script llvm/configure may be incompatible with the shell in /bin/sh

**Comment by jvillard** [comment]
@sbennett1990 is your `/tmp` partition mounted with the `noexec` option by any chance?

**Comment by jvillard** [comment]
@sbennett1990 any more blockers related to this issue?

**Comment by jvillard** [comment]
Please re-open this issue if needed.
