### ISSUE TITLE
Can infer analyze the .class files directly without compiling process?

### ISSUE THREAD

**Issue by GOptimistic** [facebook/infer#1573]
Hello,

I have some projects which are difficult to be compiled with ant, maven or gradle tools due to the problems of version, but I have the compiled .class files. I want to know whether the infer can analyze the .class files directly without "infer run -- ant" or other commands?

**Comment by ngorogiannis** [comment]
Yes, with `infer --generated-classes ...` and no build command. You will have to supply the class path manually.

**Comment by SolomonSun2010** [comment]
Good.
