### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by LoganLieou** [facebook/infer#1578]
Hello I just wanted to suggest a minor edit to CONTRIBUTING.md it says "You'll want to install a few more dependencies to comfortably hack on the infer codebase." then gives the command `make devsetup`

`make devsetup` doesn't work by default until `./configure` is ran bc automake.

in order to run `make devsetup` you need to first run a series of commands: `./autogen.sh` which will generate `configure` which can be ran `./configure` so that you can run `make` infer has a lot of dependencies, which can be installed with `opam install . --deps-only` once deps are installed `./configure` can be ran. But contributing only lists `make devsetup` which may be somewhat unclear.

I don't know if this change is necessary or if I'm missing something here.

**Comment by jvillard** [comment]
It should be enough to run `./build-infer.sh` before `make devsetup`. I believe that was the intention here. I agree the current instructions are not enough. I think we can just add "./build-infer.sh" before "make devsetup" in the code block after "Simply run:". What do you think?

**Comment by LoganLieou** [comment]
oh interesting I didn't know about `./build-infer.sh` but yes this would most definitely be helpful as I don't think listing `make devsetup` is enough.

**Comment by jvillard** [comment]
Fixed by #1581
