### ISSUE TITLE
error when  do this command "./opam install sawja.1.5 atdgen.1.5.0 javalib.2.3a extlib.1.5.4"

### ISSUE THREAD

**Issue by chenjinying** [facebook/infer#158]
The following actions will be performed:
  ∗  install ocamlfind   1.5.5                [required by javalib, atdgen, extlib, sawja]
  ∗  install menhir      20140422             [required by atd]
  ∗  install extlib      1.5.4   
  ∗  install easy-format 1.0.2                [required by biniou, atd, yojson]
  ∗  install cppo        1.1.2                [required by yojson]
  ∗  install camlzip     1.05                 [required by javalib]
  ∗  install biniou      1.0.9                [required by atdgen]
  ∗  install atd         1.1.2                [required by atdgen]
  ∗  install javalib     2.3a    
  ∗  install yojson      1.2.1                [required by atdgen]
  ∗  install sawja       1.5     
  ∗  install atdgen      1.5.0   
===== ∗  12 =====
Do you want to continue ? [Y/n] Y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[atd] Archive in cache
[atdgen] Archive in cache
[biniou] Archive in cache
[camlzip] Archive in cache
[cppo] Archive in cache
[easy-format] Archive in cache
[extlib] Archive in cache
[javalib] Archive in cache
[menhir] Archive in cache
[ocamlfind] Archive in cache
[sawja] Archive in cache
[yojson] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of ocamlfind failed at "./configure -bindir /home/cjy/.opam/4.01.0/bin -sitelib /home/cjy/.opam/4.01.0/lib -mandir /home/cjy/.opam/4.01.0/man -config
        /home/cjy/.opam/4.01.0/lib/findlib.conf".
Processing  1/12: [ocamlfind: make uninstall]
#=== ERROR while installing ocamlfind.1.5.5 ===================================#
# opam-version 1.2.2
# os           linux
# command      ./configure -bindir /home/cjy/.opam/4.01.0/bin -sitelib /home/cjy/.opam/4.01.0/lib -mandir /home/cjy/.opam/4.01.0/man -config /home/cjy/.opam/4.01.0/lib/findlib.conf
# path         /home/cjy/.opam/4.01.0/build/ocamlfind.1.5.5
# compiler     4.01.0
# exit-code    1
# env-file     /home/cjy/.opam/4.01.0/build/ocamlfind.1.5.5/ocamlfind-29279-d8a4ae.env
# stdout-file  /home/cjy/.opam/4.01.0/build/ocamlfind.1.5.5/ocamlfind-29279-d8a4ae.out
# stderr-file  /home/cjy/.opam/4.01.0/build/ocamlfind.1.5.5/ocamlfind-29279-d8a4ae.err
### stdout ###
# Welcome to findlib version 1.5.5
# Configuring core...
### stderr ###
# configure: ocaml not in PATH; this is required

=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions were aborted
  ∗  install atd         1.1.2   
  ∗  install atdgen      1.5.0   
  ∗  install biniou      1.0.9   
  ∗  install camlzip     1.05    
  ∗  install cppo        1.1.2   
  ∗  install easy-format 1.0.2   
  ∗  install extlib      1.5.4   
  ∗  install javalib     2.3a    
  ∗  install menhir      20140422
  ∗  install sawja       1.5     
  ∗  install yojson      1.2.1   
The following actions failed
  ∗  install ocamlfind 1.5.5
No changes have been performed

=-=- ocamlfind.1.5.5 troubleshooting =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> Could not build ocamlfind. The most common reason for that is a missing 'm4' system package.

**Comment by martinoluca** [comment]
Hello @chenjinying,
Do you have `m4` installed on your machine? Please run `m4 --version` and check if you get version information about it.

Thanks.

**Comment by jvillard** [comment]
Hi @chenjinying, did @martinoluca's suggestion solve your issue?

**Comment by jvillard** [comment]
Please reopen this issue if needed.
