### ISSUE TITLE
deadlock undetected in C program

### ISSUE THREAD

**Issue by Y-chav** [facebook/infer#1582]
We try starvation deadlock detector on these two C programs.

```
#include <pthread.h>
#include <stdio.h>
#include <unistd.h>

pthread_mutex_t lock1 = PTHREAD_MUTEX_INITIALIZER;
pthread_mutex_t lock2 = PTHREAD_MUTEX_INITIALIZER;


void *thread2(void *v)
{
        pthread_mutex_lock(&lock2);
        pthread_mutex_lock(&lock1);

        return NULL;
}

void *thread1(void *v)
{
        pthread_mutex_lock(&lock1);
        pthread_mutex_lock(&lock2);

        return NULL;
}

int main()
{
        pthread_t t1, t2;

        pthread_create(&t1, NULL, thread1, NULL);
        pthread_create(&t2, NULL, thread2, NULL);

        pthread_join(t1, NULL);
        pthread_join(t2, NULL);
        printf("ok\n");
        return 0;
}
```

```
#include <pthread.h>
#include <stdio.h>
#include <unistd.h>

pthread_mutex_t lock = PTHREAD_MUTEX_INITIALIZER;


void *thread(void *v)
{
        pthread_mutex_lock(&lock);
        pthread_mutex_lock(&lock);

        return NULL;
}

int main()
{
        pthread_t t;

        pthread_create(&t, NULL, thread, NULL);

        pthread_join(t, NULL);
        printf("ok\n");
        return 0;
}
```

The one above contains a cyclic deadlock lock1 -> lock2 & lock2 -> lock1, the one below contains a self-lock lock -> lock. 

However, Infer fails to detect deadlock in these two programs.

<img width="694" alt="image" src="https://user-images.githubusercontent.com/44321769/149301264-ebd9415a-a779-40b1-b3e8-d8baa2d7f891.png">

The Infer version we use is v1.1.0.

<img width="416" alt="image" src="https://user-images.githubusercontent.com/44321769/149301358-cd2dde22-2ce4-47c8-b3ac-3c01484fbcd9.png">

The command line we enter is like this.

<img width="314" alt="image" src="https://user-images.githubusercontent.com/44321769/149301544-e2a27e83-704b-465e-89c5-eaae206a091c.png">

Is it because the way we use Inter is wrong or the version we use does not support deadlock detection?

**Comment by ngorogiannis** [comment]
Hi, the checker does not currently support pthread mutexes.

**Comment by Y-chav** [comment]
Thanks for your reply. So what kind of lock does it support, is it any buggy program example?

**Comment by Y-chav** [comment]
Which mutexes in C programs are supported? Or it cannot handle C programs and only focus on balanced locks in C++ programs?

**Comment by ngorogiannis** [comment]
The tests may be of interest: https://github.com/facebook/infer/tree/main/infer/tests/codetoanalyze/cpp/starvation

C++ mutexes are supported; balance is not required, though it helps with precision.

**Comment by Y-chav** [comment]
Thanks.
