### ISSUE TITLE
Publish packages for infer

### ISSUE THREAD

**Issue by mcandre** [facebook/infer#159]
Please publish packages for infer, to make it easier for newbies to install.

**Comment by sblackshear** [comment]
You can now install Infer with Homebrew: `brew install infer`, or use our [releases](https://github.com/facebook/infer/releases).

**Comment by mcandre** [comment]
Hi,

The Homebrew package for Mac users is fantastic! I see that there are some Docker images as well.

The Docker image method is interesting, because that can sometimes restrict the rest of the developer's Docker environment, in terms of having to extend that base image. It can unnecessarily inhibit Docker builds for complicated projects that uses a lot of different build tools.

Binary releases are helpful. There is the stumbling block of extracting and adding to PATH.

Would like to see more Infer packages for other operating systems. E.g., Debian .DEB packages and RHEL .RPM packages built by fpm. And a .MSI for Windows. A FreeBSD package. Just to lower the barrier to entry even further for newbies.

I don't know if that needs to be a priority for the core infer team, or perhaps a community group of maintainers. But I really want Infer to be as easy to install as other popular linters. The easier it is to install, the more users you will have.
