### ISSUE TITLE
How to get memory consumption

### ISSUE THREAD

**Issue by Y-chav** [facebook/infer#1590]
I want to get the concrete memory consumption and I see some data in **infer-out/log**. But the log is too long, I don't know which one of these records is the information I want. 

<img width="531" alt="image" src="https://user-images.githubusercontent.com/44321769/150397044-e018ff0b-5825-40e4-b5c7-1599628f89bd.png">

**Comment by jvillard** [comment]
Hi @Y-chav, sorry for the delay. What information are you looking for more precisely? The information you screenshotted are stats about the OCaml garbage collector during the analysis phase of infer. For things like resident memory, etc., you should be able to use usual unix tools, eg valgrind. Hope that helps, please re-open with more details if not.
