### ISSUE TITLE
infer run for [iOS program] fail

### ISSUE THREAD

**Issue by zhoujian12** [facebook/infer#1591]
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.#.....................................] 22% 1min5s
Error: the following clang command did not run successfully:
    /usr/local/Cellar/infer/1.1.0_1/lib/infer/facebook-clang-plugins/clang/install/bin/clang-11

**Comment by mistdon** [comment]
How do you solve it?
