### ISSUE TITLE
While installing infer on Ubuntu 20.04

### ISSUE THREAD

**Issue by Vishrutidesai** [facebook/infer#1596]
./autogen.sh 
generating m4/__GENERATED__ac_check_infer_man_last_modified.m4... ./autogen.sh: line 37: m4/__GENERATED__ac_check_infer_man_last_modified.m4: Permission denied

how to solve this error?

**Comment by Vishrutidesai** [comment]
./autogen.sh 
generating m4/__GENERATED__ac_check_infer_man_last_modified.m4... ./autogen.sh: line 37: m4/__GENERATED__ac_check_infer_man_last_modified.m4: Permission denied

how to solve this error?

**Comment by jvillard** [comment]
Hi @Vishrutidesai, sorry for the delay in replying. This looks like a problem specific to your setup where the user with which you are running `./autogen.sh` does not have permission to write inside the infer repo. Did you manage to solve your issue? Optimistically closing this issue.
