### ISSUE TITLE
error in 'make -c infer'?

### ISSUE THREAD

**Issue by b0207191** [facebook/infer#161]
when i make infer, there is an error message,can anyone help me?

infer# make -C infer
make: Entering directory '/home/rgos/infer/infer/infer'
make -C src clang
make[1]: Entering directory '/home/rgos/infer/infer/infer/src'
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
sed -e 's/@MAJOR@/0/g' \
        -e 's/@MINOR@/2/g' \
        -e 's/@PATCH@/0/g' \
        -e 's/@GIT_COMMIT@//g' \
        -e 's/@GIT_BRANCH@//g' \
        -e 's/@GIT_TAG@//g' \
        backend/version.ml.in > backend/version.ml
atdgen -t backend/jsonbug.atd -o backend/jsonbug
atdgen -j backend/jsonbug.atd -o backend/jsonbug
atdgen -t backend/jsonbug.atd -o backend/jsonbug
atdgen -j backend/jsonbug.atd -o backend/jsonbug
/home/rgos/infer/infer/scripts/check_clang_plugin_version.sh /home/rgos/infer/infer/../facebook-clang-plugin
SKIPPING the facebook-clang-plugins version check since
/home/rgos/infer/infer/../facebook-clang-plugin is NOT a Git repository
make[1]: *** No rule to make target '/home/rgos/infer/infer/../facebook-clang-plugin/clang-ocaml/build/clang_ast.atd', needed by 'clang/clang_ast_t.ml'.  Stop.
make[1]: Leaving directory '/home/rgos/infer/infer/infer/src'
Makefile:19: recipe for target 'clang' failed
make: *** [clang] Error 2
make: Leaving directory '/home/rgos/infer/infer/infer'

**Comment by sblackshear** [comment]
Hi b0207191,
  Could you try running `make clean` and then `./update-fcp.sh && ../facebook-clang-plugin/clang/setup.sh && ./compile-fcp.sh`? Sounds like your clang plugin may be out of date.

**Comment by b0207191** [comment]
thanks, 
i retry 'running make clean and then ./update-fcp.sh && ../facebook-clang-plugin/clang/setup.sh && ./compile-fcp.sh'
it still failed on the step'make -c infer' with the following log:

# make -C infer
make: Entering directory '/home/rgos/infer/infer/infer'
make -C src clang
make[1]: Entering directory '/home/rgos/infer/infer/infer/src'
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
sed -e 's/@MAJOR@/0/g' \
        -e 's/@MINOR@/2/g' \
        -e 's/@PATCH@/0/g' \
        -e 's/@GIT_COMMIT@//g' \
        -e 's/@GIT_BRANCH@//g' \
        -e 's/@GIT_TAG@//g' \
        backend/version.ml.in > backend/version.ml
mkdir -p ../_build-infer
atdgen -t backend/jsonbug.atd -o backend/jsonbug
atdgen -j backend/jsonbug.atd -o backend/jsonbug
atdgen -t backend/jsonbug.atd -o backend/jsonbug
atdgen -j backend/jsonbug.atd -o backend/jsonbug
/home/rgos/infer/infer/scripts/check_clang_plugin_version.sh /home/rgos/infer/infer/../facebook-clang-plugin
SKIPPING the facebook-clang-plugins version check since
/home/rgos/infer/infer/../facebook-clang-plugin is NOT a Git repository
atdgen -rec -t /home/rgos/infer/infer/../facebook-clang-plugin/clang-ocaml/build/clang_ast.atd -o clang/clang_ast
atdgen -rec -j /home/rgos/infer/infer/../facebook-clang-plugin/clang-ocaml/build/clang_ast.atd -o clang/clang_ast
atdgen -rec -v /home/rgos/infer/infer/../facebook-clang-plugin/clang-ocaml/build/clang_ast.atd -o clang/clang_ast
cp -f -p /home/rgos/infer/infer/../facebook-clang-plugin/clang-ocaml/build/clang_ast_proj.ml clang
cp -f -p /home/rgos/infer/infer/../facebook-clang-plugin/clang-ocaml/build/clang_ast_proj.mli clang
cp -f -p /home/rgos/infer/infer/../facebook-clang-plugin/clang-ocaml/clang_ast_cache.ml clang
cp -f -p /home/rgos/infer/infer/../facebook-clang-plugin/clang-ocaml/clang_ast_main.ml clang
ocamlbuild -build-dir ../_build-infer -j 0 -I backend -I checkers -I facebook/checkers -I facebook/checkers/graphql -I facebook/scripts -I harness -I opensource -lflags -annot -cflags "-bin-annot -warn-error @5@8@10..12@20@26@39" -lib unix -lib str -cflags -annot -lflags -I,/root/.opam/4.01.0/lib/easy-format,-I,/root/.opam/4.01.0/lib/biniou,-I,/root/.opam/4.01.0/lib/yojson,-I,/root/.opam/4.01.0/lib/atdgen -cflags -I,/root/.opam/4.01.0/lib/easy-format,-I,/root/.opam/4.01.0/lib/biniou,-I,/root/.opam/4.01.0/lib/yojson,-I,/root/.opam/4.01.0/lib/atdgen -lib biniou -lib atdgen -mod easy_format -mod yojson -mod ag_oj_run -mod ag_util  -cflags -annot -lflags -I,/root/.opam/4.01.0/lib/extlib,-I,/root/.opam/4.01.0/lib/camlzip/../zip,-I,/root/.opam/4.01.0/lib/ptrees,-I,/root/.opam/4.01.0/lib/javalib,-I,/root/.opam/4.01.0/lib/sawja -cflags -I,/root/.opam/4.01.0/lib/extlib,-I,/root/.opam/4.01.0/lib/camlzip/../zip,-I,/root/.opam/4.01.0/lib/ptrees,-I,/root/.opam/4.01.0/lib/javalib,-I,/root/.opam/4.01.0/lib/sawja -lib zip -lib extLib -lib ptrees -lib javalib -lib sawja backend/inferanalyze.native backend/inferprint.native clang/cMain.native
+ /root/.opam/4.01.0/bin/ocamlyacc clang/cTypes_parser.mly
22 rules never reduced
51 shift/reduce conflicts, 1 reduce/reduce conflict.
+ /root/.opam/4.01.0/bin/ocamlopt.opt -c -bin-annot -warn-error @5@8@10..12@20@26@39 -annot -I /root/.opam/4.01.0/lib/easy-format -I /root/.opam/4.01.0/lib/biniou -I /root/.opam/4.01.0/lib/yojson -I /root/.opam/4.01.0/lib/atdgen -annot -I /root/.opam/4.01.0/lib/extlib -I /root/.opam/4.01.0/lib/camlzip/../zip -I /root/.opam/4.01.0/lib/ptrees -I /root/.opam/4.01.0/lib/javalib -I /root/.opam/4.01.0/lib/sawja -I clang -I harness -I opensource -I checkers -I backend -o clang/cTypes.cmx clang/cTypes.ml
File "clang/cTypes.ml", line 78, characters 57-74:
Error: This pattern matches values of type 'a * 'b * 'c
       but a pattern was expected which matches values of type
         Clang_ast_t.stmt_info * Clang_ast_t.stmt list *
         Clang_ast_t.expr_info * Clang_ast_t.cxx_delete_expr_info
Command exited with code 2.
Compilation unsuccessful after building 412 targets (0 cached) in 00:00:25.
Makefile:142: recipe for target 'build_clang' failed
make[1]: *** [build_clang] Error 10
make[1]: Leaving directory '/home/rgos/infer/infer/infer/src'
Makefile:19: recipe for target 'clang' failed
make: *** [clang] Error 2
make: Leaving directory '/home/rgos/infer/infer/infer'
root@rgos-All-Series:/home/rgos/infer/infer# 



btw: infer.zip and facebook-clang-plugin.zip  are downloaded today.i think they are update.

**Comment by sblackshear** [comment]
Hmm, the only other oddity I see is that your have stored infer inside a directory called infer (leading to the triple "infer/infer/infer" in your path). Could you try unzipping infer.zip in the top level of your home directory and following the instructions from scratch? It should work regardless of what the top-level path is, but there may be some script that is relying on being in the home directory.

**Comment by b0207191** [comment]
well, i upgrade both the 'infer dir' and 'facebook-clang-plugin dir' to /home directory. 
the result is same, 

root@rgos-All-Series:/home/infer# make -C infer
make: Entering directory '/home/infer/infer'
make -C src clang
make[1]: Entering directory '/home/infer/infer/src'
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
sed -e 's/@MAJOR@/0/g' \
        -e 's/@MINOR@/2/g' \
        -e 's/@PATCH@/0/g' \
        -e 's/@GIT_COMMIT@//g' \
        -e 's/@GIT_BRANCH@//g' \
        -e 's/@GIT_TAG@//g' \
        backend/version.ml.in > backend/version.ml
mkdir -p ../_build-infer
atdgen -t backend/jsonbug.atd -o backend/jsonbug
atdgen -j backend/jsonbug.atd -o backend/jsonbug
atdgen -t backend/jsonbug.atd -o backend/jsonbug
atdgen -j backend/jsonbug.atd -o backend/jsonbug
atdgen -t backend/jsonbug.atd -o backend/jsonbug
atdgen -j backend/jsonbug.atd -o backend/jsonbug
/home/infer/scripts/check_clang_plugin_version.sh /home/infer/../facebook-clang-plugin
SKIPPING the facebook-clang-plugins version check since
/home/infer/../facebook-clang-plugin is NOT a Git repository
atdgen -rec -t /home/infer/../facebook-clang-plugin/clang-ocaml/build/clang_ast.atd -o clang/clang_ast
atdgen -rec -j /home/infer/../facebook-clang-plugin/clang-ocaml/build/clang_ast.atd -o clang/clang_ast
atdgen -rec -v /home/infer/../facebook-clang-plugin/clang-ocaml/build/clang_ast.atd -o clang/clang_ast
cp -f -p /home/infer/../facebook-clang-plugin/clang-ocaml/build/clang_ast_proj.ml clang
cp -f -p /home/infer/../facebook-clang-plugin/clang-ocaml/build/clang_ast_proj.mli clang
cp -f -p /home/infer/../facebook-clang-plugin/clang-ocaml/clang_ast_cache.ml clang
cp -f -p /home/infer/../facebook-clang-plugin/clang-ocaml/clang_ast_main.ml clang
ocamlbuild -build-dir ../_build-infer -j 0 -I backend -I checkers -I facebook/checkers -I facebook/checkers/graphql -I facebook/scripts -I harness -I opensource -lflags -annot -cflags "-bin-annot -warn-error @5@8@10..12@20@26@39" -lib unix -lib str -cflags -annot -lflags -I,/root/.opam/4.01.0/lib/easy-format,-I,/root/.opam/4.01.0/lib/biniou,-I,/root/.opam/4.01.0/lib/yojson,-I,/root/.opam/4.01.0/lib/atdgen -cflags -I,/root/.opam/4.01.0/lib/easy-format,-I,/root/.opam/4.01.0/lib/biniou,-I,/root/.opam/4.01.0/lib/yojson,-I,/root/.opam/4.01.0/lib/atdgen -lib biniou -lib atdgen -mod easy_format -mod yojson -mod ag_oj_run -mod ag_util  -cflags -annot -lflags -I,/root/.opam/4.01.0/lib/extlib,-I,/root/.opam/4.01.0/lib/camlzip/../zip,-I,/root/.opam/4.01.0/lib/ptrees,-I,/root/.opam/4.01.0/lib/javalib,-I,/root/.opam/4.01.0/lib/sawja -cflags -I,/root/.opam/4.01.0/lib/extlib,-I,/root/.opam/4.01.0/lib/camlzip/../zip,-I,/root/.opam/4.01.0/lib/ptrees,-I,/root/.opam/4.01.0/lib/javalib,-I,/root/.opam/4.01.0/lib/sawja -lib zip -lib extLib -lib ptrees -lib javalib -lib sawja backend/inferanalyze.native backend/inferprint.native clang/cMain.native
+ /root/.opam/4.01.0/bin/ocamlyacc clang/cTypes_parser.mly
22 rules never reduced
51 shift/reduce conflicts, 1 reduce/reduce conflict.
+ /root/.opam/4.01.0/bin/ocamlopt.opt -c -bin-annot -warn-error @5@8@10..12@20@26@39 -annot -I /root/.opam/4.01.0/lib/easy-format -I /root/.opam/4.01.0/lib/biniou -I /root/.opam/4.01.0/lib/yojson -I /root/.opam/4.01.0/lib/atdgen -annot -I /root/.opam/4.01.0/lib/extlib -I /root/.opam/4.01.0/lib/camlzip/../zip -I /root/.opam/4.01.0/lib/ptrees -I /root/.opam/4.01.0/lib/javalib -I /root/.opam/4.01.0/lib/sawja -I clang -I harness -I opensource -I checkers -I backend -o clang/cTypes.cmx clang/cTypes.ml
File "clang/cTypes.ml", line 78, characters 57-74:
Error: This pattern matches values of type 'a * 'b * 'c
       but a pattern was expected which matches values of type
         Clang_ast_t.stmt_info * Clang_ast_t.stmt list *
         Clang_ast_t.expr_info * Clang_ast_t.cxx_delete_expr_info
Command exited with code 2.
Compilation unsuccessful after building 412 targets (0 cached) in 00:00:25.
Makefile:142: recipe for target 'build_clang' failed
make[1]: *** [build_clang] Error 10
make[1]: Leaving directory '/home/infer/infer/src'
Makefile:19: recipe for target 'clang' failed
make: *** [clang] Error 2
make: Leaving directory '/home/infer/infer'




---------------------------

i noticed last of compile log is 

"File "clang/cTypes.ml", line 78, characters 57-74:
Error: This pattern matches values of type 'a * 'b * 'c
       but a pattern was expected which matches values of type
         Clang_ast_t.stmt_info * Clang_ast_t.stmt list *
         Clang_ast_t.expr_info * Clang_ast_t.cxx_delete_expr_info
Command exited with code 2."

can the file clang/cTypes.ml be the reason?

**Comment by jvillard** [comment]
Hi @b0207191, which version of infer and the facebook-clang-plugins are you using? Can you try with the latest git master of infer?

**Comment by b0207191** [comment]
hi jvillard,

infer.zip and facebook-clang-plugin.zip are downloaded in 2015-8-7. i think they are new.

**Comment by jvillard** [comment]
Did you get these from GitHub?

You need a specific version of facebook-clang-plugins to compile infer. Usually the latest version of the plugin does not work with infer. You can find which version of the facebook-clang-plugins you need in [dependencies/clang-plugin/clang-plugin-version.config](https://github.com/facebook/infer/blob/master/dependencies/clang-plugin/clang-plugin-version.config).

For instance, to compile the current infer master, you need https://github.com/facebook/facebook-clang-plugins/archive/3a4b470518da7251f2dc296444c4d616fef5dc2c.zip.

The easiest way to get the right version of the plugin is to simply remove your current facebook-clang-plugins/ directory and run `./update-fcp.sh` from inside infer, which will get the right version for you.

**Comment by b0207191** [comment]
hi @jvillard 

thanks for your advice, i replace the facebook.zip with the version you mentinoed, it compiled correctly now!

**Comment by jvillard** [comment]
good to hear!
