### ISSUE TITLE
Run Infer on standalone Jar/War files.

### ISSUE THREAD

**Issue by martinschaef** [facebook/infer#1613]
I want to run Infer in bulk on a few Jar files. Is there a way to run infer capture without the `--sourcepath` option and just tell it to ingest all the class files it sees in the `--generated-classes`?

**Comment by ngorogiannis** [comment]
This isn't currently possible. There is a `--dependencies` that was used for this, but the last time I tried this it failed so probably has bit-rotted.

**Comment by martinschaef** [comment]
Thx. Do you know what the `--sourcepath` is used for? Would it be possible to just `touch` the filenames that it needs, or do I actually have to run it through a decompiler?

**Comment by ngorogiannis** [comment]
`touch` might just work. I believe (look at `jMain:capture_libs`) this is what `--dependencies` used to do on the fly.

**Comment by SolomonSun2010** [comment]
Run Infer on standalone Jar/War or classes files path, we also need it .
