### ISSUE TITLE
about makefile in project?

### ISSUE THREAD

**Issue by b0207191** [facebook/infer#162]
i have a c program project, which compile command is 'make xxx' to call some .mk

now when i run 'infer -- make xxx', it compiled normally to generate the binary. but infer does not work
because i see the last log of compile as following:

....

Starting analysis (Infer version git-)
Analysis done

0 file analyzed

btw:
echo $CC
i486-unknown-linux-gnu-gcc

**Comment by akotulski** [comment]
@b0207191 hi, did you run `make clean` before `infer -- make xxx`?
Infer needs to capture whole compilation process. More information about this (including --incremental flag for incremental builds) here:
http://fbinfer.com/docs/infer-workflow.html

**Comment by b0207191** [comment]
yes, i clean all the binary and .o files before i execute the command 'infer -- make '
it still reports '0 file analyzed'

because my project used cross-compile ,so i wonder if the "clang and the facebook-clang-plugins" work well on such case?

**Comment by martinoluca** [comment]
Hello @b0207191,
Could you please post one of the clang commands that your Makefile executes? This will help us troubleshooting.

Thanks.

**Comment by b0207191** [comment]
the compiler in project is gcc,not clang,

echo $CC
i486-unknown-linux-gnu-gcc

and the key .mk file used in compile i think is following:


CONFIG_SHELL := $(shell if [ -x "$$BASH" ]; then echo $$BASH; \
	  else if [ -x /bin/bash ]; then echo /bin/bash; \
	  else echo sh; fi ; fi)
CENV := $(shell if [ `uname` = "Linux" ]; then echo linux; else echo cygwin; fi)

top_srcdir := $(shell pwd)

all: do-it-all

OUTPUT_DIR := $(top_srcdir)/build

ADD_CFLAGS  =

ifeq ($(CONFIG_GCOV),y)
GCOV_FLAGS := -fprofile-arcs -ftest-coverage
endif

export MAKEFLAGS += $(JOB_SLOTS)
export MAKEFILES += ${KCONFIG}

export CONFIG_SHELL OUTPUT_DIR GCOV_FLAGS ADD_CFLAGS
export top_srcdir  
 
unexport rootdir-y

include $(KCONFIG)

include $(top_srcdir)/Rules.mk

PKG := mng

VERSION := 1.0.0

src_type := svn

rootdir-y := 
rootdir-$(CONFIG_xxx1) += tech_support
rootdir-$(CONFIG_xxx2) += syslog

.PHONY: header
header:
	ln -s -f ${ROOTFS_BUILD}/$(PKG)/cli/common/ ${ROOTFS_BUILD}/$(PKG)/cli/server/common

.PHONY: do-it-all
do-it-all: build 

.PHONY: build
build: $(patsubst %, _dir_%, $(rootdir-y))
$(patsubst %, _dir_%, $(rootdir-y)): 
	$(MAKE) CFLAGS="$(CFLAGS)" -C $(top_srcdir)/$(patsubst _dir_%,%, $@) _PDIR="$(OUTPUT_DIR)/$(patsubst _dir_%,%, $@)"
	@echo "Compiled OK! find output in $(OUTPUT_DIR)/$(patsubst _dir_%,%, $@)"
	@echo

.PHONY: install
install:
	n=`ls $(install_root)/ | wc -l`; \
	if [ $$n -gt 0 ] ; then \
		cp -a -rf $(install_root)/* ${IMAGES}; fi
		
.PHONY: rpmpkg
rpmpkg:
	$(RPMPKG) $(install_rootfs_dir) $(PKG).spec $(src_type)

.PHONY: gcov-docs
gcov-docs:
	@-for dir in $(rootdir-y) ; do \
	lcov -c -b $$dir -d $$dir -o $$dir.info; \
	genhtml -o $(GCOV_DOCS)/$(PKG)-$(VERSION)/$$dir $$dir.info --title $$dir; done

.PHONY: version
version:
	@echo ${VERSION}

.PHONY:gcov-cp-gcda
gcov-cp-gcda:
	@tar zxf gcov_*.tar.gz -C $(PKG)
	
.PHONY: clean
clean:
	@-for dir in $(rootdir-y) ; do \
	$(MAKE) -C $$dir clean ; done
	@rm -rf $(shell find -name "*.gcda" && find -name "*.gcno" && find -name "report" && find -name "*.info" && find -name "*.o")
	@rm -rf $(install_root)
	@rm -rf $(OUTPUT_DIR)

**Comment by martinoluca** [comment]
I suspect what's happening in your case is that the makefiles are running the compiler providing an absolute path rather than a relative one. In this case Infer won't be able to capture the compile commands (because it does it by changing the PATH environment variable, which won't be effective in this case).

Usually you can replace the compilers on Makefiles setting variables like CC and CXX: try setting those to point to your compiler, but without specifying the absolute path. If there's a `configure` step that generates these makefiles, then run it again setting those variables first.

Thanks.

**Comment by b0207191** [comment]
@martinoluca 
thanks for your suggestion, i have still two questions
1. how infer change the PATH environment variable, i echo the $PATH and found it is appended the cross-compile tool directory, is it enough

echo $PATH
/home/infer/infer/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/11xprj/rgosm-build/.toolchain-x86_32/x86_32/bin(<- last segment)

2. there is no 'configure' step in the project, can i know how many environment variables infer need to use, so that i can check if they are useful?

**Comment by b0207191** [comment]
because the project use cross compile,so i wonder if i should set change $CC to the dest-$CC at first.
so i setup the $CC ,then excute '../facebook-clang-plugin/clang/setup.sh'

the compile stop at
configure: error:
The selected GCC C++ compiler is not new enough to build LLVM. Please upgrade
to GCC 4.7. You may pass --disable-compiler-version-checks to configure to

so i added '--disable-compiler-version-checks' to 'setup.sh'
and excute  '../facebook-clang-plugin/clang/setup.sh' again

now the compile stop at 

cc1plus: error: unrecognized command line option "-std=c++11"cc1plus: error: unrecognized command line option "-std=c++11"

cc1plus: error: unrecognized command line option "-std=c++11"cc1plus: error: unrecognized command line option "-std=c++11"

llvm[1]: Compiling Atomic.cpp for Release build
/bin/rm: /bin/rm: cannot remove 鈥?tmp/clang-setup.Jlv7QM/lib/Support/Release/APSInt.d.tmp鈥?bin/rm: : No such file or directorycannot remove 鈥?tmp/clang-setup.Jlv7QM/lib/Support/Release/APInt.d.tmp鈥?
         : No such file or directory
/tmp/clang-setup.Jlv7QM/llvm/Makefile.rules:1514: recipe for target '/tmp/clang-setup.Jlv7QM/lib/Support/Release/APSInt.o' failed
make[1]: *** [/tmp/clang-setup.Jlv7QM/lib/Support/Release/APSInt.o] Error 1
make[1]: *** Waiting for unfinished jobs....
cannot remove 鈥?tmp/clang-setup.Jlv7QM/lib/Support/Release/ARMBuildAttrs.d.tmp鈥?tmp/clang-setup.Jlv7QM/llvm/Makefile.rules:1514: recipe for target '/tmp/clang-setup.Jlv7QM/lib/Support/Release/APInt.o' failed
make[1]: *** [/tmp/clang-setup.Jlv7QM/lib/Support/Release/APInt.o] Error 1
: No such file or directory/bin/rm: cannot remove 鈥?tmp/clang-setup.Jlv7QM/lib/Support/Release/APFloat.d.tmp鈥? No such file or directory

cc1plus: error: unrecognized command line option "-std=c++11"/tmp/clang-setup.Jlv7QM/llvm/Makefile.rules:1514: recipe for target '/tmp/clang-setup.Jlv7QM/lib/Support/Release/APFloat.o' failed
make[1]: *** [/tmp/clang-setup.Jlv7QM/lib/Support/Release/APFloat.o] Error 1

cc1plus: error: unrecognized command line option "-std=c++11"
/tmp/clang-setup.Jlv7QM/llvm/Makefile.rules:1514: recipe for target '/tmp/clang-setup.Jlv7QM/lib/Support/Release/ARMBuildAttrs.o' failed
make[1]: *** [/tmp/clang-setup.Jlv7QM/lib/Support/Release/ARMBuildAttrs.o] Error 1
cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: error: unrecognized command line option "-std=c++11"
/bin/rm: cannot remove 鈥?tmp/clang-setup.Jlv7QM/lib/Support/Release/Allocator.d.tmp鈥? No such file or directory
/bin/rm: cannot remove 鈥?tmp/clang-setup.Jlv7QM/lib/Support/Release/BlockFrequency.d.tmp鈥? No such file or directory
/tmp/clang-setup.Jlv7QM/llvm/Makefile.rules:1514: recipe for target '/tmp/clang-setup.Jlv7QM/lib/Support/Release/Allocator.o' failed
make[1]: *** [/tmp/clang-setup.Jlv7QM/lib/Support/Release/Allocator.o] Error 1
/tmp/clang-setup.Jlv7QM/llvm/Makefile.rules:1514: recipe for target '/tmp/clang-setup.Jlv7QM/lib/Support/Release/BlockFrequency.o' failed
make[1]: *** [/tmp/clang-setup.Jlv7QM/lib/Support/Release/BlockFrequency.o] Error 1
/bin/rm: cannot remove 鈥?tmp/clang-setup.Jlv7QM/lib/Support/Release/ARMWinEH.d.tmp鈥? No such file or directory
/bin/rm: cannot remove 鈥?tmp/clang-setup.Jlv7QM/lib/Support/Release/Atomic.d.tmp鈥?tmp/clang-setup.Jlv7QM/llvm/Makefile.rules:1514: recipe for target '/tmp/clang-setup.Jlv7QM/lib/Support/Release/ARMWinEH.o' failed
make[1]: *** [/tmp/clang-setup.Jlv7QM/lib/Support/Release/ARMWinEH.o] Error 1
: No such file or directory
/tmp/clang-setup.Jlv7QM/llvm/Makefile.rules:1514: recipe for target '/tmp/clang-setup.Jlv7QM/lib/Support/Release/Atomic.o' failed
make[1]: *** [/tmp/clang-setup.Jlv7QM/lib/Support/Release/Atomic.o] Error 1
make[1]: Leaving directory '/tmp/clang-setup.Jlv7QM/lib/Support'
/tmp/clang-setup.Jlv7QM/llvm/Makefile.rules:873: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by jvillard** [comment]
Hi @b0207191,

You probably don't need to use dest-$CC to compile infer and the facebook-clang-plugins. (The error you get is because your dest-$CC is indeed too old)

The Makefile you pasted does not seem to contain any build rules, it just calls other Makefiles. To be able to help, it would be great to see an example invocation of the compiler as called by your Makefiles.

One possibility for your issue is if your Makefile gives several source files to $CC at once. Infer cannot deal with this. For instance, `infer -- gcc -c a.c b.c` does not work. Instead, one should use `infer -- gcc -c a.c && infer -- gcc -c b.c`. I realise now that we seem to have forgotten to document this!

**Comment by b0207191** [comment]
@jvillard 
yes,the project do the compile by call 'makefile' in every directory Recursively 

one 'makefile' look like this:

include $(top_srcdir)/Rules.mk

LIB_CLI_VER := 1.0.0
DLIB_FLAGS = -fPIC -shared -lpthread -lrt
TAG := xxx.so
ELF := $(TAG).$(LIB_CLI_VER)
SRC := $(shell find -name '*.c')
DEPEND = $(shell find -name '*.d')
OBJ = file1.o   file2.o .... filen.o

%.o: %.c
	$(CC) -c -fPIC $(CFLAGS) -Wall $< -o $@

.PHONY: build install clean
all: build install

build: $(TAG)
$(TAG): $(OBJ)
	$(CC) $(CFLAGS) $(DLIB_FLAGS) $^ $(IMAGES)/lib/fsui.a -o $(ELF)

install:
	mkdir -p $(install_sodir)
	cp -p $(ELF) $(install_sodir)
	cd $(install_sodir) && ln -sf $(ELF) $(TAG)

clean:
	rm -rf  $(OBJ) $(ELF) $(DEPEND)

include $(SRC:.c=.d)

%.d: %.c
	set -e; rm -f $@; \
	$(CC) -M -MT $*.o $(CFLAGS) $< > $@.$$$$; \
	sed 's,\($*\)\.o[ :]*,\1.o $@ : ,g' < $@.$$$$ > $@; \
	rm -f $@.$$$$
		
--------------------

i think gcc in the makefile is 'gcc -c file1.c gcc -c file2.c', but not 'gcc -c file1.c file2.c'??

**Comment by jvillard** [comment]
My hunch was wrong, it looks like you are compiling files one by one, which is good.

Looking back at your comments, I see another possibility. You mentioned this:

```shell
echo $CC
i486-unknown-linux-gnu-gcc
```

If `$CC` is set to something other than gcc or clang, Infer will not be able to capture calls to the compiler, because it only looks for calls to gcc and clang, and not eg i486-unknown-linux-gnu-gcc.

Can you try the following? (replacing `xxx` with your usual target)

```shell
make clean
infer -- make CC=clang xxx
```

**Comment by b0207191** [comment]
@jvillard 
well, although i can try 'infer -- make CC=clang xxx', i haven't all the codes in the project, the code of mine need to link other .so(dynamic library) of other components , so the log occur in linking parse:

--------------------
/usr/bin/ld: skipping incompatible build/prj_nic-x86-32/images/rootfs/lib/libxxx.so when searching for -lxxx
------------------

i think if i want to use infer, i should get all the code of project, then use 'infer -- make CC=clang xxx' to make all the code from the head.

**Comment by jvillard** [comment]
Because Infer uses a custom compiler under the hood, it is common for the linking step to fail (see [the FAQ](http://fbinfer.com/support.html#quot-infer-lt-build-command-gt-quot-fails-during-a-linking-step)).

You can try this workaround:

```
LD=/bin/true infer -- make CC=clang xxx
```

**Comment by b0207191** [comment]
@jvillard 
thank you for advise all above. 
i made a try under 32bit-ubuntu enviroment and had successfully to run infer the project inspite there are most false positive in result.

by the way, can infer now only detect null pointer reference and memory(resouce) leak ?
i think since its working manner is similiar to coverity, it should discover many bugs in the future.

**Comment by jvillard** [comment]
We'd love to hear about any false positive you found, to improve Infer! You're very welcome to open issues about them. I'm closing this one as it sounds like your original problem is solved.
