### ISSUE TITLE
error /bin/sh: javac:not found  Infer needs a working compilation command to run

### ISSUE THREAD

**Issue by ppoooo0** [facebook/infer#1620]
Hello,I would like to askfor advice. 
my infer version:v1.1.0 and  use linux-64
when I use "infer --racerd-only -- javac File.java" it ports an error.

_ppo@ppo-virtual-machine:~$ infer --racerd-only -- javac File.java
Capturing in javac mode...
Usage Error: 
*** Failed to execute compilation command: exited with code 127
*** Command: javac '@/home/ppo/infer-out/tmp/javac_args.tmp.685e92'
*** Output:
/bin/sh: 1: javac: not found

*** Infer needs a working compilation command to run._

I would appreciate it if you could reply to me.

**Comment by jvillard** [comment]
> /bin/sh: 1: javac: not found

Have you tried to see if you have javac installed on your system? Please let us know what steps you have tried so far.

**Comment by ppoooo0** [comment]
> > /bin/sh: 1: javac: not found
> 
> Have you tried to see if you have javac installed on your system? Please let us know what steps you have tried so far.

 Thank you for your reply , I have solved this problem through your help, the infer analysis tool is now available.
