### ISSUE TITLE
Fatal error: exception DB.Path_not_prefix_root

### ISSUE THREAD

**Issue by romanoaugusto88** [facebook/infer#163]
I'm trying to infer a large project, and after few seconds the infer crashes abnormally. What this could be?

> $ ./gradlew clean && infer -- ./gradlew build

> Fatal error: exception DB.Path_not_prefix_root
Traceback (most recent call last):
  File "/home/romano/infer-linux64-v0.3.0/infer/bin/infer", line 168, in <module>
    main()
  File "/home/romano/infer-linux64-v0.3.0/infer/bin/infer", line 143, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/home/romano/infer-linux64-v0.3.0/infer/bin/../lib/capture/gradle.py", line 75, in capture
    return util.run_commands(cmds)
  File "/home/romano/infer-linux64-v0.3.0/infer/bin/../lib/capture/util.py", line 40, in run_commands
    if not cmd.start():
  File "/home/romano/infer-linux64-v0.3.0/infer/bin/inferlib.py", line 689, in start
    if self.capture() == os.EX_OK:
  File "/home/romano/infer-linux64-v0.3.0/infer/bin/inferlib.py", line 451, in capture
    return self.run_infer_frontend()
  File "/home/romano/infer-linux64-v0.3.0/infer/bin/inferlib.py", line 442, in run_infer_frontend
    self.args.analyzer
  File "/home/romano/infer-linux64-v0.3.0/infer/bin/inferlib.py", line 358, in run_command
    raise e
subprocess.CalledProcessError: Command '[u'/home/romano/infer-linux64-v0.3.0/infer/bin/InferJava', u'-project_root', '/home/romano/projects/MyApp', u'-results_dir', u'/home/romano/projects/MyApp/infer-out', u'-verbose_out', '/tmp/javac_pVNbVO.out', u'-models', u'/home/romano/infer-linux64-v0.3.0/infer/bin/../lib/java/models.jar', u'-no-static_final']' returned non-zero exit status 2

> $ infer -v
Infer version v0.3.0
Copyright 2009 - present Facebook. All Rights Reserved.

**Comment by jvillard** [comment]
Hi @romanoaugusto88,

This seems like a bug in Infer. Thanks for reporting it!

- Could you please post the contents of infer-out/toplevel.log?
- Can you try running `./gradlew clean && OCAMLRUNPARAM=b infer -- ./gradlew build` and paste the result?

**Comment by romanoaugusto88** [comment]
Hey @jvillard, here is the outputs. Hope it helps:

`infer-out/toplevel.log`:

> [INFO] Running command /home/romano/infer-linux64-v0.3.0/infer/bin/infer -- ./gradlew build
[INFO] Path to infer script /home/romano/infer-linux64-v0.3.0/infer/bin/infer (/home/romano/infer-linux64-v0.3.0/infer/bin/infer)
[INFO] Infer version v0.3.0
Copyright 2009 - present Facebook. All Rights Reserved.


> [INFO] Platform: Linux-3.8.0-44-generic-x86_64-with-elementary_OS-0.2.1-luna
[INFO] PATH=/home/romano/infer-linux64-v0.3.0/infer/bin:/home/romano/.opam/4.01.0/bin:/home/romano/.gvm/pkgsets/letras/global/bin:/home/romano/.gvm/gos/letras/bin:/home/romano/.gvm/pkgsets/letras/global/overlay/bin:/home/romano/.gvm/bin:/home/romano/.gvm/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/opt/node/bin:/usr/local/jdk/bin
[INFO] SHELL=/bin/bash
[INFO] PWD=/home/romano/projects/ss/AndroidMyApp/App/MyApp
[INFO] Running with:

> ------------------------------------------------------------
Gradle 2.2.1
------------------------------------------------------------

> Build time:   2014-11-24 09:45:35 UTC
Build number: none
Revision:     6fcb59c06f43a4e6b1bcb401f7686a8601a1fb4a

> Groovy:       2.3.6
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.7.0_79 (Oracle Corporation 24.79-b02)
OS:           Linux 3.8.0-44-generic amd64


> [ERROR] Failure during frontend, original command was

> [u'inferJ', u'-g', u'-a', 'capture', u'javac', '-source', '1.6', '-target', '1.6', '-d', '/home/romano/projects/ss/AndroidMyApp/Libraries/com_actionbarsherlock/build/intermediates/classes/debug', '-g', '-encoding', 'UTF-8', '-bootclasspath', '/home/romano/Android/Sdk/platforms/android-18/android.jar', '-classpath', '/home/romano/Android/Sdk/extras/android/m2repository/com/android/support/support-v4/13.0.0/support-v4-13.0.0.jar', u'@/home/romano/projects/ss/AndroidMyApp/App/MyApp/infer-out/filelists/gradle_dm4ha8.txt']

`./gradlew clean && OCAMLRUNPARAM=b infer -- ./gradlew build`:

> :ActionBarSherlock:clean
:AmazingListView:clean UP-TO-DATE
:MyApp:clean UP-TO-DATE
:NineOldAndroids:clean UP-TO-DATE
:SlidingTabs:clean UP-TO-DATE
:UtilLibrary:clean UP-TO-DATE
:ViewPageIndicator:clean UP-TO-DATE
:Volley:clean UP-TO-DATE

> BUILD SUCCESSFUL

> Total time: 7.734 secs
16:27:08.982 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:27:08.985 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:27:10.807 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:27:10.807 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:27:16.054 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:27:16.055 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:27:16.055 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
16:27:16.055 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
16:27:17.747 [ERROR] [system.err] Note: /home/romano/projects/ss/AndroidMyApp/Libraries/UtilLibrary/src/com/mycompany/utillibrary/Miscellaneous/Storage.java uses or overrides a deprecated API.
16:27:17.747 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:27:17.747 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
16:27:17.748 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
16:27:19.382 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:27:19.382 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:27:20.461 [ERROR] [org.gradle.api.Task] AAPT err(1422735772) : No Delegate set : lost message:/home/romano/projects/ss/AndroidMyApp/App/MyApp/MyApp/build/intermediates/exploded-aar/MyApp/ActionBarSherlock/unspecified/res/drawable-mdpi-v4/abs__ic_search.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
16:27:20.746 [ERROR] [org.gradle.api.Task] AAPT err(1422735772) : No Delegate set : lost message:/home/romano/projects/ss/AndroidMyApp/App/MyApp/MyApp/build/intermediates/exploded-aar/MyApp/ActionBarSherlock/unspecified/res/drawable-hdpi-v4/abs__ab_share_pack_holo_dark.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
16:27:20.877 [ERROR] [org.gradle.api.Task] AAPT err(360939889) : No Delegate set : lost message:/home/romano/projects/ss/AndroidMyApp/App/MyApp/MyApp/build/intermediates/exploded-aar/MyApp/ActionBarSherlock/unspecified/res/drawable-hdpi-v4/abs__ic_go.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
16:27:23.182 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:27:23.183 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:27:23.183 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
16:27:23.183 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
16:28:28.147 [ERROR] [org.gradle.api.Task] AAPT err(1708424840) : No Delegate set : lost message:/home/romano/projects/ss/AndroidMyApp/App/MyApp/MyApp/build/intermediates/exploded-aar/MyApp/ActionBarSherlock/unspecified/res/drawable-hdpi-v4/abs__ic_clear_disabled.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
16:28:28.289 [ERROR] [org.gradle.api.Task] AAPT err(1364812987) : No Delegate set : lost message:/home/romano/projects/ss/AndroidMyApp/App/MyApp/MyApp/build/intermediates/exploded-aar/MyApp/ActionBarSherlock/unspecified/res/drawable-xhdpi-v4/abs__ic_clear_disabled.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
16:28:28.591 [ERROR] [org.gradle.api.Task] AAPT err(135615744) : No Delegate set : lost message:/home/romano/projects/ss/AndroidMyApp/App/MyApp/MyApp/build/intermediates/exploded-aar/MyApp/ActionBarSherlock/unspecified/res/drawable-hdpi-v4/abs__ab_share_pack_holo_dark.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
16:28:28.599 [ERROR] [org.gradle.api.Task] AAPT err(1423856212) : No Delegate set : lost message:/home/romano/projects/ss/AndroidMyApp/App/MyApp/MyApp/build/intermediates/exploded-aar/MyApp/ActionBarSherlock/unspecified/res/drawable-xhdpi-v4/abs__ab_share_pack_holo_light.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
16:28:28.629 [ERROR] [org.gradle.api.Task] AAPT err(135615744) : No Delegate set : lost message:/home/romano/projects/ss/AndroidMyApp/App/MyApp/MyApp/build/intermediates/exploded-aar/MyApp/ActionBarSherlock/unspecified/res/drawable-hdpi-v4/abs__ic_search.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
16:28:28.734 [ERROR] [org.gradle.api.Task] AAPT err(2143102079) : No Delegate set : lost message:/home/romano/projects/ss/AndroidMyApp/App/MyApp/MyApp/build/intermediates/exploded-aar/MyApp/ActionBarSherlock/unspecified/res/drawable-xhdpi-v4/abs__ic_go.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
16:28:28.821 [ERROR] [org.gradle.api.Task] AAPT err(805909275) : No Delegate set : lost message:/home/romano/projects/ss/AndroidMyApp/App/MyApp/MyApp/build/intermediates/exploded-aar/MyApp/ActionBarSherlock/unspecified/res/drawable-mdpi-v4/abs__ab_share_pack_holo_dark.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
16:28:30.414 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:28:30.414 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:28:30.414 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
16:28:30.415 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
16:28:59.735 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:28:59.735 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:28:59.736 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
16:28:59.736 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
16:29:04.164 [ERROR] [system.err] Note: /home/romano/projects/ss/AndroidMyApp/Libraries/UtilLibrary/src/com/mycompany/utillibrary/Miscellaneous/Storage.java uses or overrides a deprecated API.
16:29:04.165 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:29:04.165 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
16:29:04.165 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
16:29:06.907 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:29:06.907 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
Fatal error: exception DB.Path_not_prefix_root
Called from file "parsing.ml", line 162, characters 4-28
Traceback (most recent call last):
  File "/home/romano/infer-linux64-v0.3.0/infer/bin/infer", line 168, in <module>
    main()
  File "/home/romano/infer-linux64-v0.3.0/infer/bin/infer", line 143, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/home/romano/infer-linux64-v0.3.0/infer/bin/../lib/capture/gradle.py", line 75, in capture
    return util.run_commands(cmds)
  File "/home/romano/infer-linux64-v0.3.0/infer/bin/../lib/capture/util.py", line 40, in run_commands
    if not cmd.start():
  File "/home/romano/infer-linux64-v0.3.0/infer/bin/inferlib.py", line 689, in start
    if self.capture() == os.EX_OK:
  File "/home/romano/infer-linux64-v0.3.0/infer/bin/inferlib.py", line 451, in capture
    return self.run_infer_frontend()
  File "/home/romano/infer-linux64-v0.3.0/infer/bin/inferlib.py", line 442, in run_infer_frontend
    self.args.analyzer
  File "/home/romano/infer-linux64-v0.3.0/infer/bin/inferlib.py", line 358, in run_command
    raise e
subprocess.CalledProcessError: Command '[u'/home/romano/infer-linux64-v0.3.0/infer/bin/InferJava', u'-project_root', '/home/romano/projects/ss/AndroidMyApp/App/MyApp', u'-results_dir', u'/home/romano/projects/ss/AndroidMyApp/App/MyApp/infer-out', u'-verbose_out', '/tmp/javac_akLYkb.out', u'-models', u'/home/romano/infer-linux64-v0.3.0/infer/bin/../lib/java/models.jar', u'-no-static_final']' returned non-zero exit status 2

**Comment by sylvestre** [comment]
Similar issue with a different project / build system:
```
 1:01.37 Fatal error: exception DB.Path_not_prefix_root
 1:01.37 Called from file "parsing.ml", line 162, characters 4-28
 1:01.37 [ERROR] Failure during frontend, original command was
 1:01.37 
 1:01.37 [u'inferJ', u'-g', u'-a', 'capture', u'javac', '-target', '1.7', '-source', '1.7', '-classpath', '/var/lib/jenkins/.mozbuild/android-sdk-linux/platforms/android-21/android.jar:/var/lib/jenkins/.mozbuild/android-sdk-linux/tools/lib/lint.jar:/var/lib/jenkins/.mozbuild/android-sdk-linux/tools/lib/lint-checks.jar', '-bootclasspath', '/var/lib/jenkins/.mozbuild/android-sdk-linux/platforms/android-21/android.jar', '-encoding', 'UTF8', u'-g', '-d', 'annotationProcessors-classes', '/var/lib/jenkins/workspace/fennec-infer/build/annotationProcessors/AnnotationInfo.java', '/var/lib/jenkins/workspace/fennec-infer/build/annotationProcessors/AnnotationProcessor.java', '/var/lib/jenkins/workspace/fennec-infer/build/annotationProcessors/classloader/AnnotatableEntity.java', '/var/lib/jenkins/workspace/fennec-infer/build/annotationProcessors/classloader/ClassWithOptions.java', '/var/lib/jenkins/workspace/fennec-infer/build/annotationProcessors/classloader/IterableJarLoadingURLClassLoader.java', '/var/lib/jenkins/workspace/fennec-infer/build/annotationProcessors/classloader/JarClassIterator.java', '/var/lib/jenkins/workspace/fennec-infer/build/annotationProcessors/CodeGenerator.java', '/var/lib/jenkins/workspace/fennec-infer/build/annotationProcessors/SDKProcessor.java', '/var/lib/jenkins/workspace/fennec-infer/build/annotationProcessors/utils/AlphabeticAnnotatableEntityComparator.java', '/var/lib/jenkins/workspace/fennec-infer/build/annotationProcessors/utils/GeneratableElementIterator.java', '/var/lib/jenkins/workspace/fennec-infer/build/annotationProcessors/utils/Utils.java']
 1:01.37 
 1:01.37 
 1:01.37 Traceback (most recent call last):
 1:01.37   File "/opt/infer/infer/bin/inferJ", line 23, in <module>
 1:01.37     stats = analysis.start()
 1:01.37   File "/var/lib/jenkins/opt/infer-linux64-v0.3.0/infer/bin/inferlib.py", line 689, in start
 1:01.37     if self.capture() == os.EX_OK:
 1:01.37   File "/var/lib/jenkins/opt/infer-linux64-v0.3.0/infer/bin/inferlib.py", line 451, in capture
 1:01.37     return self.run_infer_frontend()
 1:01.37   File "/var/lib/jenkins/opt/infer-linux64-v0.3.0/infer/bin/inferlib.py", line 442, in run_infer_frontend
 1:01.37     self.args.analyzer
 1:01.37   File "/var/lib/jenkins/opt/infer-linux64-v0.3.0/infer/bin/inferlib.py", line 358, in run_command
 1:01.37     raise e
 1:01.37 subprocess.CalledProcessError: Command '[u'/var/lib/jenkins/opt/infer-linux64-v0.3.0/infer/bin/InferJava', u'-project_root', '/var/lib/jenkins/workspace/fennec-infer/obj-arm-linux-androideabi/build/annotationProcessors', u'-results_dir', '/var/lib/jenkins/workspace/fennec-infer/infer', u'-verbose_out', '/tmp/javac_HOiWDZ.out', u'-models', u'/var/lib/jenkins/opt/infer-linux64-v0.3.0/infer/bin/../lib/java/models.jar', u'-no-static_final']' returned non-zero exit status 2
 1:01.38 /var/lib/jenkins/workspace/fennec-infer/config/makefiles/java-build.mk:136: recipe for target 'annotationProcessors.jar' failed
```

**Comment by sblackshear** [comment]
Hi @sylvestre,
  Could you try pulling the latest Infer code, recompiling, running it again, and reporting the result? a62c71290b4f03db93277fe8abc01911631277c0 added a better error message that should help us debug this problem.

**Comment by sylvestre** [comment]
@sblackshear infer built. The error message is indeed much better:  "The project root /var/lib/jenkins/workspace/fennec-infer/obj-arm-linux-androideabi/build/annotationProcessors is not a prefix of /var/lib/jenkins/workspace/fennec-infer/build/annotationProcessors/AnnotationInfo.java" but I am not sure infer is right here (it worked with 0.1.0)

**Comment by sblackshear** [comment]
Try passing `-project_root /var/lib/jenkins/workspace/fennec-infer/build/annotationProcessors/` to your top-level Infer command and see if that fixes the problem. 

Thanks for working with us on this--I think we need to make Infer a bit smarter at detecting the project root for Gradle projects.

**Comment by sylvestre** [comment]
Welcome! FYI, I am not using Gradle but the custom Mozilla build system (building firefox for android here).
Failed the same way: *The project root /var/lib/jenkins/workspace/fennec-infer/obj-arm-linux-androideabi/build/annotationProcessors is not a prefix of /var/lib/jenkins/workspace/fennec-infer/build/annotationProcessors/AnnotationInfo.java* with *--project_root ...*

If you want to see the full log: http://relman-ci.mozilla.org/job/fennec-infer/97/console

**Comment by sblackshear** [comment]
Thanks, the full log/the link to the fennec-infer source inside is very helpful! I think I see the problem (`project_root` flag not being passed down the line properly); I'll see if I can get it to work properly.

**Comment by sblackshear** [comment]
I've just pushed a fix that should stop this exception from occurring. Feel free to close the issue if this fixes it on your end.

**Comment by sylvestre** [comment]
OK. It fixes the bug but the warning is displayed on every call... This is flooding the log:
http://relman-ci.mozilla.org/job/fennec-infer/101/consoleFull
I don't know if it is possible for you but showing it once should be enough.

**Comment by cristianoc** [comment]
Thanks for the report.
Fix in https://github.com/facebook/infer/commit/28f5025862b0b145ee64ce4a4ed44b94eeb071c0.
