### ISSUE TITLE
Null Dereference False Negative

### ISSUE THREAD

**Issue by pattersonz** [facebook/infer#1632]
infer 1.1.0
Ubuntu 18.04.4
infer -- clang 

So, when I execute this:
```
const int a;
const int b;
const int d;
const int e;

void bar() {
  return;
}

int foo(){
  int * x;
  if (a) {
    bar();
  }
  x = malloc(sizeof(*x));
  if (d) {
    bar();
  }
  if (e) {
    bar();
  }

  return *x;
}

int main () {
  return 1;
}
```
I get this:
```
Capturing in make/cc mode...
Found 1 source file to analyze in infer-1.1.0/testing/infer-out
1/1 [################################################################################] 100% 88.777ms

test.c:25: error: Null Dereference
  pointer `x` last assigned on line 17 could be null and is dereferenced at line 25, column 10.
  23.   }
  24.
  25.   return *x;
               ^
  26. }
  27.


Found 1 issue
          Issue Type(ISSUED_TYPE_ID): #
  Null Dereference(NULL_DEREFERENCE): 1
```

However when I add an if statement, I get nothing:
```
const int a;
const int b;
const int d;
const int e;

void bar() {
  return;
}

int foo(){
  int * x;
  if (a) {
    bar();
  }
// ---diff
  if (b) {
    bar();
  }
// ---
  x = malloc(sizeof(*x));
  if (d) {
    bar();
  }
  if (e) {
    bar();
  }

  return *x;
}

int main () {
  return 1;
}
```

```
Capturing in make/cc mode...
Found 1 source file to analyze in infer-1.1.0/testing/infer-out
1/1 [################################################################################] 100% 84.518ms

  No issues found
```

Is there something I can do on my end to fix this?

**Comment by AshUK** [comment]
Just add null check after malloc, remember if malloc cannot allocate the requested amount of memory it will return a null value, this is a possible code path that infer has correctly detected.

```
if(x == NULL) {
 return -1;
}```

**Comment by pattersonz** [comment]
> Just add null check after malloc, remember if malloc cannot allocate the requested amount of memory it will return a null value, this is a possible code path that infer has correctly detected.
> 
> ```
> if(x == NULL) {
>  return -1;
> }
> ```

I think you're misunderstanding the issue here. It correctly identifies it in case 1. In case 2 the only difference is an extra if statement that effectively does nothing between the definition and initialization. In this case, although the exact same error exists, it doesn't find it.

**Comment by jvillard** [comment]
Hi @pattersonz, I can reproduce the issue with the latest version as well. However, the new analysis pulse correctly handles your example:

```
$ infer --pulse-only --enable-issue-type NULLPTR_DEREFERENCE_LATENT -- clang -c issue1632.c     
issue1632.c:28: error: Null Dereference
  `x` could be null (last assigned on line 20) and is dereferenced.
  26.   }
  27. 
  28.   return *x;
               ^
  29. }
  30. 


Found 1 issue
                    Issue Type(ISSUED_TYPE_ID): #
  Null Dereference(NULLPTR_DEREFERENCE_LATENT): 1
```

As you can see I needed to enable the "latent" version of null dereference issue type of pulse. This is because by default pulse will refrain from reporting issues unless it can be sure that there is a calling context that can cause the issue and here the issue depends on the values of the global variables (we may revisit this in the future). Another way to make pulse report in your example is to call `foo()` from main:

```
$ tail -n 4 issue1632.c
int main () {
  foo();
  return 1;
}
$ infer --pulse-only -- clang -c issue1632.c                           
issue1632.c:32: error: Null Dereference
  The call to `foo` may trigger the following issue: `x` could be null (from the call to `foo()` on line 20) and is dereferenced in call to `foo()`.
  30. 
  31. int main () {
  32.   foo();
        ^
  33.   return 1;
  34. }

issue1632.c:32: error: Uninitialized Value
  is read without initialization during the call to `foo()`.
  30. 
  31. int main () {
  32.   foo();
        ^
  33.   return 1;
  34. }


Found 2 issues
                      Issue Type(ISSUED_TYPE_ID): #
  Uninitialized Value(PULSE_UNINITIALIZED_VALUE): 1
           Null Dereference(NULLPTR_DEREFERENCE): 1
```

**Comment by pattersonz** [comment]
```
infer --pulse-only --enable-issue-type NULLPTR_DEREFERENCE_LATENT -- clang -c test.c
```
I don't seem to be able to get this to display any issues, actually on any file. Is there some options I need to run/configure, or an update I need to make for pulse to work?

**Comment by jvillard** [comment]
@pattersonz are you using infer 1.1.0? My tests were with the latest from "main" on GitHub.

**Comment by pattersonz** [comment]
I was using the latest release of infer, but not the latest version on github. After updating, it does work. Thank you!
