### ISSUE TITLE
PulseTaintOperations Causing Analysis Crash

### ISSUE THREAD

**Issue by matjin** [facebook/infer#1633]
Hello -- it seems that modifications made during April 2022 to PulseTaintOperations seem to be causing the analysis to crash in certain scenarios. Below is the stack trace. I did check out commit 2e1119932b895ad126faa4f56799d59cc3b34697 from March 31 and reran my example to validate that the crash does not occur on that version. Would it be possible to add some kind of exception handling to PulseTaintOperations to prevent this issue from resulting in analysis crash?

> Internal Error: ok_exn of something not Ok
> Error backtrace:
> Raised at Stdlib__Map.Make.min_binding in file "map.ml", line 231, characters 17-32
> Called from Absint__Scheduler.ReversePostorder.pop in file "src/absint/Scheduler.ml", line 87, characters 31-55
> Re-raised at IBase__Die.raise_error.do_raise in file "src/base/Die.ml", line 26, characters 8-56
> Called from Pulselib__PulseTaintOperations.taint_initial.(fun) in file "src/pulse/PulseTaintOperations.ml", line 536, characters 10-116
> Called from Base__List.fold_map.(fun) in file "src/list.ml", line 432, characters 23-31
> Called from Base__List.count_map in file "src/list.ml", line 394, characters 13-17
> Called from Base__List.map in file "src/list.ml" (inlined), line 418, characters 15-31
> Called from Base__List.fold_map in file "src/list.ml", line 431, characters 4-88
> Called from Pulselib__PulseTaintOperations.taint_initial in file "src/pulse/PulseTaintOperations.ml", line 533, characters 4-428
> Called from Pulselib__Pulse.initial in file "src/pulse/Pulse.ml", line 796, characters 4-169
> Called from Pulselib__Pulse.analyze in file "src/pulse/Pulse.ml", line 843, characters 6-163
> Called from Backend__CallbackOfChecker.interprocedural_with_field in file "src/backend/CallbackOfChecker.ml", line 55, characters 15-36
> Called from Backend__Callbacks.iterate_procedure_callbacks.(fun) in file "src/backend/callbacks.ml", line 58, characters 22-49
> Called from Stdlib__List.fold_left in file "list.ml", line 121, characters 24-34
> Called from Backend__Ondemand.analyze in file "src/backend/ondemand.ml", line 155, characters 16-76
> Re-raised at IStdlib__IExn.reraise_if in file "src/istd/IExn.ml", line 18, characters 15-63
> Called from Backend__Ondemand.run_proc_analysis in file "src/backend/ondemand.ml", line 225, characters 4-752
> Called from Backend__Ondemand.analyze_proc_name_no_caller in file "src/backend/ondemand.ml" (inlined), line 342, characters 2-58
> Called from Backend__Ondemand.analyze_procedures.analyze_proc_name_call in file "src/backend/ondemand.ml", line 348, characters 12-53
> Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
> Called from Base__List0.iter in file "src/list0.ml" (inlined), line 25, characters 16-35
> Called from Backend__Ondemand.analyze_procedures in file "src/backend/ondemand.ml", line 350, characters 2-54
> Called from Backend__InferAnalyzeJson.analyze_json in file "src/backend/InferAnalyzeJson.ml", line 722, characters 2-43
> Called from Integration__Driver.execute_analyze_json in file "src/integration/Driver.ml", line 200, characters 6-54
> Called from IBase__Utils.timeit in file "src/base/Utils.ml", line 424, characters 16-20
> Called from IBase__ScubaLogging.execute_with_time_logging in file "src/base/ScubaLogging.ml", line 83, characters 29-44
> Called from Dune__exe__Infer.run in file "src/infer.ml", line 21, characters 2-47
> Called from IBase__Utils.timeit in file "src/base/Utils.ml", line 424, characters 16-20
> Called from IBase__ScubaLogging.execute_with_time_logging in file "src/base/ScubaLogging.ml", line 83, characters 29-44
> Called from Dune__exe__Infer.run in file "src/infer.ml", line 25, characters 22-94

**Comment by matjin** [comment]
OK! I will follow up with the debug output :)

**Comment by jvillard** [comment]
Should be fixed by 02a784948f4aa629234362c258bc2bfa01f6f3ad
