### ISSUE TITLE
make -C infer  the step is always wrong 

### ISSUE THREAD

**Issue by owen19891030** [facebook/infer#166]
on my mac, when I run " make -C infer", then make error. such as : atdgen no such file or dircectory;
but I installed all depence library.

**Comment by jvillard** [comment]
you probably need to run `eval $(opam config env)`. According to [INSTALL.md](https://github.com/facebook/infer/blob/master/INSTALL.md):

```sh
opam init -y --comp=4.01.0
eval `opam config env`
opam install -y extlib.1.5.4 atdgen.1.6.0 javalib.2.3.1 sawja.1.5.1
```

If you followed these steps and ran `eval $(opam config env)` in your current shell but still get an error, can you please paste the full error message?

**Comment by owen19891030** [comment]
thanks ,it's ok
