### ISSUE TITLE
Missing infer/bin/InferAnalyze in package Infer version 0.3.0

### ISSUE THREAD

**Issue by lzhenyu0** [facebook/infer#168]

**Comment by akotulski** [comment]
@lzhenyu0 this is intended behavior. We provide releases with prebuilt clang and facebook-clang-plugins, but you need to build the rest from source we provide in the release (it should be fairly quick)

The full installation process is described here: http://fbinfer.com/docs/getting-started.html
Please remember to install all dependencies: https://github.com/facebook/infer/blob/master/INSTALL.md#install-the-dependencies
