### ISSUE TITLE
error in "make -C infer "

### ISSUE THREAD

**Issue by ytrjp** [facebook/infer#169]
jinpengdeMacBook-Pro:infer-osx-v0.3.0 jinpeng$ make -C infer
make -C src clang
sed -e 's/@MAJOR@/0/g' \
		-e 's/@MINOR@/2/g' \
		-e 's/@PATCH@/0/g' \
		-e 's/@GIT_COMMIT@/37a4709a0f2be7b23a29950a2d6345040b67b8eb/g' \
		-e 's/@GIT_BRANCH@/master/g' \
		-e 's/@GIT_TAG@/v0.3.0/g' \
		backend/version.ml.in > backend/version.ml
atdgen -t backend/jsonbug.atd -o backend/jsonbug
make[1]: atdgen: No such file or directory
make[1]: *** [backend/jsonbug_t.ml] Error 1
make: *** [clang] Error 2

**Comment by akotulski** [comment]
You are missing one of the dependencies. Make sure you follow the steps in https://github.com/facebook/infer/blob/master/INSTALL.md#install-the-dependencies

**Comment by balachandarlinks** [comment]
after initialising opam, we should run "opam update" to synchronize the repo. Otherwise it will never find the required packages.

So the instructions should be,

opam init -y --comp=4.01.0
eval `opam config env`
opam update
opam install -y extlib.1.5.4 atdgen.1.6.0 javalib.2.3.1 sawja.1.5.1

**Comment by sacrificar** [comment]
after I do opam update and opam install, I still get the problem. What supose I do?

**Comment by martinoluca** [comment]
Hello @sacrificar,
could you please paste here the output of `opam list`?
Thanks

**Comment by sacrificar** [comment]
# Installed packages for 4.01.0:
atd               1.1.2  Parser for the ATD data format description language
atdgen            1.7.1  Generates efficient JSON serializers, deserializers and
base-bigarray      base  Bigarray library distributed with the OCaml compiler
base-threads       base  Threads library distributed with the OCaml compiler
base-unix          base  Unix library distributed with the OCaml compiler
biniou            1.0.9  Binary data format designed for speed, safety, ease of 
camlp4             4.01  Camlp4 is a system for writing extensible parsers for p
camlzip            1.05  Provides easy access to compressed files in ZIP, GZIP a
cppo              1.3.0  Equivalent of the C preprocessor for OCaml programs
easy-format       1.0.2  High-level and functional interface to the Format modul
extlib            1.5.4  A complete yet small extension for OCaml standard libra
javalib           2.3.1  Javalib is a library written in OCaml which aims at pro
menhir         20140422  LR(1) parser generator
ocamlfind         1.5.5  A library manager for OCaml
sawja             1.5.1  Provide a high level representation of Java bytecode pr
yojson            1.2.3  Yojson is an optimized parsing and printing library for

**Comment by martinoluca** [comment]
the version of atdgen that we require to install from the website is atdgen.1.6.0

**Comment by sacrificar** [comment]
before I update to 1.7.1, I already have atdgen 1.6.0 but that's not working. Then I read this issues and try to opam update then terminal said there's update for atdgen and other 2. Then I do opam upgrade. Then that's still not working too.

**Comment by martinoluca** [comment]
it may be that atdgen is not in your PATH environment, so try running 
```
eval `opam config env`
```
then try again.

**Comment by sacrificar** [comment]
that's work. Thanks.
