### ISSUE TITLE
recognize CFBridgingRelease() when analyzing memory leaks

### ISSUE THREAD

**Issue by voisine** [facebook/infer#17]
The following generates an erroneous memory leak warning:

```NSMutableString *s = CFBridgingRelease(CFStringCreateMutableCopy(NULL, 0, CFSTR("foo")));```

**Comment by dulmarod** [comment]
Hi,
I cannot reproduce your issue. I tried the following little example and I don't get the bug. 
#import <Foundation/Foundation.h>
@interface A : NSObject
@end 
@implementation	A
-(void) test {
  NSMutableString *s = CFBridgingRelease(CFStringCreateMutableCopy(NULL, 0, CFSTR("foo")));
}
@end

Could you give me more context about how you called Infer? 
Thanks,
Dulma

**Comment by dulmarod** [comment]
By checking this, it seems unlikely that that line produces a Memory Leak. We think that it may be an issue with line numbers. Sometimes they are wrong and we are working to fix them.
