### ISSUE TITLE
possibly incorrect handling of loops over iterators

### ISSUE THREAD

**Issue by cr-gh** [facebook/infer#171]
When running infer over the following snippet it reports no issues regarding the possible null dereferencing when calling length(). However when commenting out the while loop it rightfully points out that there might be an issue there.

	static HashMap<String,String> hm = new HashMap<String,String>();
	static HashMap<String, String> hm2 = new HashMap<String,String>();
	static void iterator_test() {
		Iterator<String> it = hm.keySet().iterator();
		while(it.hasNext()) {
			String m = it.next();
		}
		hm2.get("g").length();
	}

**Comment by cristianoc** [comment]
This should be fixed in https://github.com/facebook/infer/commit/1e9ce380567b64b555a8088a046eb29240d5f614
