### ISSUE TITLE
Failed to run InferAnalyze binary, exiting

### ISSUE THREAD

**Issue by zlychelsea** [facebook/infer#172]
Ubuntu 14.04
1. tar xf infer-linux64-v0.3.0.tar.xz
2. echo "export PATH=$PATH:`pwd`/infer-linux64-v0.3.0/infer/bin" \ >> ~/.bashrc && source ~/.bashrc
3. infer -- javac hello.java

Error : Failed to run InferAnalyze binary, exiting

**Comment by martinoluca** [comment]
Hello @zlychelsea,
This issue is the same as the one reported in https://github.com/facebook/infer/issues/170
Please make sure you follow the instructions in http://fbinfer.com/docs/getting-started.html to compile and install infer and its dependencies.

**Comment by jvillard** [comment]
closing as duplicate. please reopen if this is not accurate.

**Comment by IgorGanapolsky** [comment]
I am having the same issue on MacOs El Capitan.  Any solution?
