### ISSUE TITLE
RacerD should understand JCIP annotations like NotThreadSafe

### ISSUE THREAD

**Issue by dsmiley** [facebook/infer#1724]
I am using RacerD indirectly via Sonatype Lift and see THREAD_SAFETY_VIOLATION reported against my project.  I want to add Java annotations to help RacerD help us and to better communicate threading/concurrency expectations to readers of our code.  I see RacerD has its own/special annotations like [ThreadConfined](https://fbinfer.com/docs/1.0.0/checker-racerd/#threadconfined).  I request that RacerD be adapted to recognize [JCIP annotations](https://jcip.net/annotations/doc/index.html) like NotThreadSafe which is equivalent to ThreadConfined.

**Comment by ngorogiannis** [comment]
`NotThreadSafe` is supported: https://fbinfer.com/docs/all-issue-types#thread-safety-conditions-checked-before-reporting

**Comment by dsmiley** [comment]
Great!  This wasn't obvious in the docs!  I think https://fbinfer.com/docs/1.0.0/checker-racerd#annotations-to-help-racerd-understand-your-code (which also shows annotations prominently in the sidebar) should show JCIP annotations.
