### ISSUE TITLE
Missing capture module when running infer

### ISSUE THREAD

**Issue by kingangelTOT** [facebook/infer#173]
+ infer -- gradle build
Traceback (most recent call last):
  File "/usr/bin/infer", line 142, in <module>
    main()
  File "/usr/bin/infer", line 104, in main
    imported_module = load_module(mod_name)
  File "/usr/bin/infer", line 50, in load_module
    pkg_info = imp.find_module(CAPTURE_PACKAGE, [LIB_FOLDER])
ImportError: No module named capture

env: jenkins + mac

**Comment by martinoluca** [comment]
Hello @kingangelTOT,
It looks like a problem of paths.
`infer` searches for the capture package within the lib folder, and that is not found. How did you install infer?

**Comment by jvillard** [comment]
closing for now. feel free to reopen with more info as per @martinoluca's question.
