### ISSUE TITLE
run infer error in mac

### ISSUE THREAD

**Issue by kingangelTOT** [facebook/infer#174]
download infer-osx-v0.3.0.tar.xz 
/Users/kingangeltot/Downloads/infer-osx-v0.3.0/infer/bin/infer

and get Failed to run InferAnalyze binary, exiting

**Comment by JohnWong** [comment]
I got the same error when after I compiled from source. Please check your Xcode version. 
```
XCode <= 6.3, >= 6.1
```

**Comment by martinoluca** [comment]
Hello @kingangelTOT,
Before running `infer` you need to compile it first, please follow the instructions described here http://fbinfer.com/docs/getting-started.html to install the dependencies and compile infer

**Comment by kingangelTOT** [comment]
xcode version is 6.4 

so i can't run？

**Comment by JohnWong** [comment]
@kingangelTOT Finally, I run infer without issue. Do not compile from source. Just use the release as follow to save your time: http://fbinfer.com/docs/getting-started.html

**Comment by jvillard** [comment]
@kingangelTOT Xcode 6.4 should be no problem.

**Comment by jvillard** [comment]
closing for now, please reopen if there's still an issue
