### ISSUE TITLE
--skip-analysis-in-path does not work

### ISSUE THREAD

**Issue by pastel001** [facebook/infer#1754]
Please make sure your issue is not addressed in the [FAQ](https://fbinfer.com/docs/support#troubleshooting).

Please include the following information:
- [ ] The version of infer from `infer --version`. 
Infer version v1.1.0-d7549bc1c0
- [ ] Your operating system and version, for example "Debian 9", "MacOS High Sierra", whether you are using Docker, etc.
MacOS Monterey 12.6.4
- [ ] Which command you ran, for example `infer -- make`.
xcodebuild clean build xxx | tee  xcodebuild.log |  xcpretty -r json-compilation-database -o compile_commands.json
infer run --skip-analysis-in-path Pods --compilation-database compile_commands.json --keep-going
OR
infer capture  --skip-analysis-in-path Pods -- xcodebuild clean build xxx 
infer analysis 
OR
infer run  --skip-analysis-in-path Pods -- xcodebuild clean build xxx 
- [ ] The full output in a paste, for instance a [gist](https://gist.github.com/).
the files in the Pods dir alse been analysis, the files issue also in the infer-out/report.txt

**Comment by elhoangvu** [comment]
Try using the following cmd
```console
infer capture --skip-analysis-in-path ".+/Pods" -- xcodebuild clean build xxx
```
A path is skipped if its prefix matches the given regex

**Comment by coooliang** [comment]
.inferconfig
```
{
  "report-blacklist-path-regex": [
    "Pods"
  ]
}
```

**Comment by SolomonSun2010** [comment]
Good
