### ISSUE TITLE
Not able to compile infer on Linux Ubuntu 14.10

### ISSUE THREAD

**Issue by swatigoel** [facebook/infer#176]
I have followed this link to setup infer on Linux machine (https://github.com/facebook/infer/blob/master/INSTALL.md#install-the-dependencies)

After that I followed steps to checkout infer and clang to compile But I am not able to do so/
# Checkout Infer
git clone https://github.com/facebook/infer.git
cd infer
git submodule update --init --recursive
# Compile clang
facebook-clang-plugins/clang/setup.sh # go have a coffee :)
# Compile the clang plugin
./compile-fcp.sh
# Compile Infer
make -C infer

I have checked out at home directory. After running make -C infer, I am getting following error:

make: Entering directory '/home/user/infer/infer'
make -C src clang
make[1]: Entering directory '/home/user/infer/infer/src'
GIT_COMMIT=$(git rev-parse HEAD 2> /dev/null || printf "unknown commit"); \
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2> /dev/null || printf "unknown branch"); \
UNKNOWN="-unknown"; \
if [ -e "/home/user/infer/.release" ]; then \
  UNKNOWN=""; \
fi; \
GIT_TAG=$(git tag --points-at HEAD 2> /dev/null || printf "v0.3.0$UNKNOWN"); \
sed -e 's/@MAJOR@/0/g' \
	-e 's/@MINOR@/3/g' \
	-e 's/@PATCH@/0/g' \
	-e "s/@GIT_COMMIT@/$GIT_COMMIT/g" \
	-e "s#@GIT_BRANCH@#$GIT_BRANCH#g" \
	-e "s/@GIT_TAG@/$GIT_TAG/g" \
	backend/version.ml.in > backend/version.ml
atdgen -t backend/jsonbug.atd -o backend/jsonbug
make[1]: atdgen: Command not found
Makefile:173: recipe for target 'backend/jsonbug_t.ml' failed
make[1]: *** [backend/jsonbug_t.ml] Error 127
make[1]: Leaving directory '/home/user/infer/infer/src'
Makefile:19: recipe for target 'clang' failed
make: *** [clang] Error 2
make: Leaving directory '/home/user/infer/infer'

Can you please help me to set up infer?

**Comment by martinoluca** [comment]
Hello @swatigoel,
I think that your problem is due to a missing atdgen binary (`make[1]: atdgen: Command not found`).
Make sure all your dependencies have been installed correctly (run `opam list` and check they are all there) or re-install them with the command:
```
./opam install -y extlib.1.5.4 atdgen.1.6.0 javalib.2.3.1 sawja.1.5.1
```

If they are all there and the problem persists, run: 
```
eval `./opam config env`
```
and try again.

**Comment by swatigoel** [comment]
can you please tell me in which directory, I have to run this command
./opam install -y extlib.1.5.4 atdgen.1.6.0 javalib.2.3.1 sawja.1.5.1

**Comment by swatigoel** [comment]
I got it... I am doing opam setup 
Setup Opam
wget https://github.com/ocaml/opam/releases/download/1.2.2/opam-1.2.2-x86_64-Linux -O opam
chmod +x opam
./opam init -y --comp=4.01.0
eval `./opam config env`
./opam install -y extlib.1.5.4 atdgen.1.6.0 javalib.2.3.1 sawja.1.5.1

**Comment by swatigoel** [comment]
Hello @martinoluca ,
I run this command "eval ./opam config env" as per setup steps but I got below error:

The program 'opam' is currently not installed. You can install it by typing:
sudo apt-get install opam

So I did sudo apt-get install opam, it installed opam but after running command "eval ./opam config env" again I got below error:

[ERROR] Your version of OPAM (1.1.1) is not recent enough to read ~/.opam/config. Upgrade OPAM to a more recent version (at least 1.2) to read this file correctly.
'opam config env' failed.
# opam-version    1.1.1
# os              linux
File /home/user/.opam/config: Bad format! opam-version

**Comment by martinoluca** [comment]
Right, seems like you've installed opam from apt-get rather than using the one you downloaded with wget.

You now have to use that one, which means you should suppress the `./` from the command and type instead:
```
eval `opam config env`
```

**Comment by swatigoel** [comment]
thank you for your quick response, I used this comman now eval `./opam config env` and run
make -C infer again. Now it's giving another error

make: Entering directory '/home/user/infer/infer'
make -C src clang
make[1]: Entering directory '/home/user/infer/infer/src'
GIT_COMMIT=$(git rev-parse HEAD 2> /dev/null || printf "unknown commit"); \
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2> /dev/null || printf "unknown branch"); \
UNKNOWN="-unknown"; \
if [ -e "/home/user/infer/.release" ]; then \
  UNKNOWN=""; \
fi; \
GIT_TAG=$(git tag --points-at HEAD 2> /dev/null || printf "v0.3.0$UNKNOWN"); \
sed -e 's/@MAJOR@/0/g' \
	-e 's/@MINOR@/3/g' \
	-e 's/@PATCH@/0/g' \
	-e "s/@GIT_COMMIT@/$GIT_COMMIT/g" \
	-e "s#@GIT_BRANCH@#$GIT_BRANCH#g" \
	-e "s/@GIT_TAG@/$GIT_TAG/g" \
	backend/version.ml.in > backend/version.ml
atdgen -t backend/jsonbug.atd -o backend/jsonbug
atdgen -j backend/jsonbug.atd -o backend/jsonbug
atdgen -t backend/jsonbug.atd -o backend/jsonbug
atdgen -j backend/jsonbug.atd -o backend/jsonbug
make[1]: *** No rule to make target '/home/user/infer/facebook-clang-plugins/clang-ocaml/build/clang_ast_converter', needed by 'clang/clang_ast_t.ml'.  Stop.
make[1]: Leaving directory '/home/user/infer/infer/src'
Makefile:19: recipe for target 'clang' failed
make: *** [clang] Error 2
make: Leaving directory '/home/user/infer/infer'

**Comment by martinoluca** [comment]
try running
```
make -C infer clean && make -C infer
```

**Comment by swatigoel** [comment]
Thanks, It worked. Now I've completed infer setup. I want to know how can I run this for my application.

**Comment by swatigoel** [comment]
one more thing, I want to know. How can I maintain opam and infer setup for subsquent sessions.

**Comment by martinoluca** [comment]
From now on, you'll need to pull the latest changes from the infer repo, then run `make -C infer` to build the new changes.
To run Infer on your codebase, follow the instructions here http://fbinfer.com/docs/analyzing-apps-or-projects.html

**Comment by swatigoel** [comment]
thanks for your help. It really helped me to set up infer.
