### ISSUE TITLE
Not able to analyze my app using infer not even sample app on Linux

### ISSUE THREAD

**Issue by swatigoel** [facebook/infer#177]
I have done infer setup as per documentation and steps told in this thread https://github.com/facebook/infer/issues/176

After that I tried to run infer for sample app android_hello. It worked in sample app. So I thought to run for my application.

My Android application has little complex structure. It uses 2 android library and one java library and it's own code structure.
When I ran "infer -- gradlew build" it started analyzing all the resources first and then code and then it threw error in one library's java file with same problem as I have mentioned below

So I thought to again run infer sample app. This time, it again failed to run infer. Please check below logs:

user@user-Latitude-E6440:~$ cd infer/examples/android_hello/
user@user-Latitude-E6440:~/infer/examples/android_hello$ infer -- gradlew build
Traceback (most recent call last):
  File "/home/user/infer/infer/bin/infer", line 180, in <module>
    main()
  File "/home/user/infer/infer/bin/infer", line 144, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/home/user/infer/infer/bin/../lib/capture/gradle.py", line 82, in capture
    cmds = self.get_inferJ_commands(util.get_build_output(self.build_cmd))
  File "/home/user/infer/infer/bin/../lib/capture/util.py", line 30, in get_build_output
    proc = subprocess.Popen(build_cmd, stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Can you please help me to run infer so that I can figure out issues which can occur at run time.

**Comment by martinoluca** [comment]
Hello @swatigoel,
Could you please run `infer --version` and paste here the output?

**Comment by swatigoel** [comment]
@martinoluca 
This is the output.
Infer version git-401109b4eb9d54ef8831ee953a3436ec3e2bb72e
Copyright 2009 - present Facebook. All Rights Reserved.

**Comment by martinoluca** [comment]
You ran `infer -- gradlew build` and it fails saying `No such file or directory`.
Try running `gradlew build` only.

**Comment by swatigoel** [comment]
I ran ./gradlew build and it said everything is UP-TO-DATE and build is successful including all 3 depenedent library(2 android lib and 1 java lib)

BUILD SUCCESSFUL
Total time: 42.298 secs

**Comment by martinoluca** [comment]
`./gradlew` is not `gradlew`
Please now run `./gradlew clean` then run `infer -- ./gradlew build`

**Comment by swatigoel** [comment]
ok will do, Actually I tried to run "gradlew build" it showed below error
No command 'gradlew' found, did you mean:
 Command 'gradle' from package 'gradle' (universe)
gradlew: command not found

So I ran "./gradlew build" and it successfully built the app.

As you said, I ran "./gradlew clean" and then ran "infer -- ./gradlew build" now it started running infer. Let's see this time it should complete without error.

**Comment by swatigoel** [comment]
It gave below error now

Fatal error: exception Failure("The project root /home/user/app is not a prefix of /home/user/javalib/src/main/java/com/test/MyClass.java")
Traceback (most recent call last):
  File "/home/user/infer/infer/bin/infer", line 180, in <module>
    main()
  File "/home/user/infer/infer/bin/infer", line 144, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/home/user/infer/infer/bin/../lib/capture/gradle.py", line 83, in capture
    return util.run_commands(cmds)
  File "/home/user/infer/infer/bin/../lib/capture/util.py", line 40, in run_commands
    if not cmd.start():
  File "/home/user/infer/infer/bin/inferlib.py", line 691, in start
    if self.capture() == os.EX_OK:
  File "/home/user/infer/infer/bin/inferlib.py", line 477, in capture
    return self.run_infer_frontend()
  File "/home/user/infer/infer/bin/inferlib.py", line 468, in run_infer_frontend
    self.args.analyzer
  File "/home/user/infer/infer/bin/inferlib.py", line 384, in run_command
    raise e
subprocess.CalledProcessError: Command '[u'/home/user/infer/infer/bin/InferJava', u'-project_root', '/home/user/app', u'-results_dir', u'/home/user/app/infer-out', u'-verbose_out', '/tmp/javac_f_Bf7V.out', u'-models', u'/home/user/infer/infer/bin/../lib/java/models.jar', u'-no-static_final']' returned non-zero exit status 2

**Comment by martinoluca** [comment]
Is your library located in `/home/user/javalib`?

**Comment by swatigoel** [comment]
Yes, it's located in javalib folder

**Comment by martinoluca** [comment]
Try passing the `--project_root` argument to infer, run:
```
./gradlew clean && infer --project_root /home/user -- ./gradlew build
```

**Comment by swatigoel** [comment]
@martinoluca 

thanks for your support. But that also didn't work. Actually "infer" doesn't suit to our code structure.
To run infer I have moved all library folders into main app folder and then ran below commands

"./gradlew clean" 
"infer -- ./gradlew build"

Now it started running without giving project root error.

**Comment by swatigoel** [comment]
hello @martinoluca 

After running "infer -- ./gradlew build", it gets stuck after sometimes.
I retried multiple times but always it gets stuck at same location.
Attached is the screen-shot that displays logs after that app gets stuck for infinite time. I have to interrupt it by Ctrl+C
![selection_001](https://cloud.githubusercontent.com/assets/3157058/9873267/397363fa-5bbc-11e5-8ea8-aaa4ecf61bb7.png)

**Comment by martinoluca** [comment]
Hello @swatigoel,
That is the output of the debug info of gradle, and should be normal, the analysis may take some time, depending on the size of your codebase.

**Comment by swatigoel** [comment]
ok sir, I got it. but if it is actually running then it should show debug info with latest time stamp. right?

I waited for more than 2 hours and last debug info on terminal was 2 hours ago.

**Comment by swatigoel** [comment]
I ran infer for small app it gave output in seconds only.
May be I have to wait for longer time to analyze my app.
Thank you anyways. Will ask you again if I get stuck somewhere.

**Comment by martinoluca** [comment]
Good point about the timestamp, the reason why they are shown with a delay is that `infer` processes the debug info in order to run the analysis, then it emits the info as soon as the processing is done.
Wait and see how it goes!

**Comment by swatigoel** [comment]
sure, thank you so much for your support.

**Comment by sblackshear** [comment]
Unless your app is massive or your machine is very slow, two hours seems way too long.

Could you try running `infer --log_to_stderr -- ./gradlew build` and sharing the output?

In addition, if you would be willing to share the source code for your app I would be happy to try running it on my machine to see if I can understand what's going on.

**Comment by swatigoel** [comment]
Hello @sblackshear 
As I already said My main app is using 2 android app as library and 1 java library. All are at different different locations.
So while running "infer -- ./gradlew build" , I was getting error related to project root.
So After code checkout I moved out all library code inside my main app and updated path in settings.gradle
After that I ran "./gradlew clean" command to build the project and then ran infer command.

It took more than 2 hours after that I saw the log "starting analyzing git....." and to analyze full codebase and creating bugs.txt it took around 3:30 hrs to 4 hrs.

I cannot share the source code as it is confidential.

I will try running "infer --log_to_stderr -- ./gradlew build" and will share the output here.

**Comment by dongdaqing** [comment]
@sblackshear I got the same error as belows, and the output here:
dongdaqing->~/Downloads/infer-master/examples/android_hello $infer --log_to_stderr -- ./gradlew build
[INFO] Running command /Users/dongdaqing/AndroidDevEnv/infer-osx-v0.4.0/infer/bin/infer --log_to_stderr -- ./gradlew build
[INFO] Path to infer script /Users/dongdaqing/AndroidDevEnv/infer-osx-v0.4.0/infer/bin/infer (/Users/dongdaqing/AndroidDevEnv/infer-osx-v0.4.0/infer/bin/infer)
[INFO] Infer version v0.4.0
Copyright 2009 - present Facebook. All Rights Reserved.


[INFO] Platform: Darwin-15.0.0-x86_64-i386-64bit
[INFO] PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/dongdaqing/AndroidDevEnv/android-sdk-macosx/platform-tools:/Users/dongdaqing/AndroidDevEnv/android-sdk-macosx/tools:/Users/dongdaqing/AndroidDevEnv/android-sdk-macosx/build-tools/22.0.1:/Users/dongdaqing/AndroidDevEnv/android-sdk-macosx/gradle-2.5/bin:/Users/dongdaqing/iOSDevEnv/checker-276:/usr/local/mysql/bin:/Users/dongdaqing/AndroidDevEnv/infer-osx-v0.4.0/infer/bin
[INFO] SHELL=/bin/bash
[INFO] PWD=/Users/dongdaqing/Downloads/infer-master/examples/android_hello
[INFO] Running with:

------------------------------------------------------------
Gradle 2.2.1
------------------------------------------------------------

Build time:   2014-11-24 09:45:35 UTC
Build number: none
Revision:     6fcb59c06f43a4e6b1bcb401f7686a8601a1fb4a

Groovy:       2.3.6
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.7.0_71 (Oracle Corporation 24.71-b01)
OS:           Mac OS X 10.11.1 x86_64

**Comment by sblackshear** [comment]
Closing as we have made lots of performance improvements in the latest release, feel free to reopen if you are still experiencing problems.
