### ISSUE TITLE
infer compilation error 

### ISSUE THREAD

**Issue by RahulRvR** [facebook/infer#178]
I get the following error 

make -C infer

<pre>
*make -C src clang
GIT_COMMIT=$(git rev-parse HEAD 2> /dev/null || printf "unknown commit"); \
	GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2> /dev/null || printf "unknown branch"); \
	UNKNOWN="-unknown"; \
	if [ -e "/Users/vijayr/Downloads/infer/.release" ]; then \
	  UNKNOWN=""; \
	fi; \
	GIT_TAG=$(git tag --points-at HEAD 2> /dev/null || printf "v0.3.0$UNKNOWN"); \
	sed -e 's/@MAJOR@/0/g' \
		-e 's/@MINOR@/3/g' \
		-e 's/@PATCH@/0/g' \
		-e "s/@GIT_COMMIT@/$GIT_COMMIT/g" \
		-e "s#@GIT_BRANCH@#$GIT_BRANCH#g" \
		-e "s/@GIT_TAG@/$GIT_TAG/g" \
		backend/version.ml.in > backend/version.ml
atdgen -t backend/jsonbug.atd -o backend/jsonbug
atdgen -j backend/jsonbug.atd -o backend/jsonbug
atdgen -t backend/jsonbug.atd -o backend/jsonbug
atdgen -j backend/jsonbug.atd -o backend/jsonbug
make[1]: *** No rule to make target `/Users/vijayr/Downloads/infer/facebook-clang-plugins/clang-ocaml/build/clang_ast.atd', needed by `clang/clang_ast_t.ml'.  Stop.
make: *** [clang] Error 2 *
<pre>

**Comment by jvillard** [comment]
Hi @RahulRvR, thanks for opening a separate issue. I'm pasting what I said on #170 here:

it looks like you're not using the release version of infer, so you need to compile the clang plugin (or `make -C infer java` if you're only interested in Infer for Java). Please follow the [compile instructions](https://github.com/facebook/infer/blob/master/INSTALL.md#compile-clang-and-infer-from-source).

Let me know if this solves your issue.

**Comment by jvillard** [comment]
Closing this issue, assuming it is solved.
