### ISSUE TITLE
Infer should not specify -Werror flag for javac compilation

### ISSUE THREAD

**Issue by anerudhbalaji** [facebook/infer#18]
Currently when 'javac' maven builds with infer generates warnings, it treats them as errors since -Werror flag is specified. This results in false positives being reported. Should this be changed to treat warnings as warnings? 

====== Command used ======
  
infer -- mvn install

====== Sample Logs ======

warning: [path] bad path element "/Users/foobar/.m2/repository/com/googlecode/htmlcompressor/htmlcompressor/1.4/guava-r08.jar": no such file or directory

error: warnings found and -Werror specified

**Comment by irpap** [comment]
Thanks for reporting this, I'll take a look.
