### ISSUE TITLE
facebook-clang-plugins/clang/setup.sh should detect if rebuilding clang is necessary

### ISSUE THREAD

**Issue by sylvestre** [facebook/infer#181]
It would be appreciated if ```facebook-clang-plugins/clang/setup.sh``` could detect if a rebuild of clang is necessary or not.
For now, it is rebuilding the whole software each time it is called.

**Comment by jvillard** [comment]
Hi @sylvestre, thanks for the suggestion. There is a fix in the facebook-clang-plugins repo: https://github.com/facebook/facebook-clang-plugins/commit/2bc8e83d2e84a0c274ad0eaf61645bfc0be1855c

We'll soon include it in infer.
