### ISSUE TITLE
Infer - clang plugin OCaml - Issue

### ISSUE THREAD

**Issue by mantejl** [facebook/infer#1810]
I am trying to build Infer using the documentation given, but I am coming across this issue everytime I try to build. Not sure what the error is, I have tried changing the script and make file. 

Infer version: not yet available, as infer is not building 

OS Version: Ventura 13.0.1

Command: ./build-infer.sh clang

Output: 

initializing opam...
looking if switch 4.14.0+flambda exists in this list:
4.14.0+flambda
verdict: yes

installing infer dependencies; this can take up to 30 minutes...
Nothing to do.
preparing build...
+ ./configure --disable-erlang-analyzers --disable-hack-analyzers --disable-java-analyzers --disable-python-analyzers
checking for .release... no
checking for .facebook... no
checking for build platform... Darwin
checking for Windows build... no
checking for realpath... grealpath
checking whether to use the compilers in /Users/mantej/steel-work/infer/facebook-clang-plugins/clang/install/bin... no
checking for shasum... shasum
checking for cmake... cmake
checking for python3... python3
checking for xcode-select... xcode-select
checking for xcrun... xcrun
checking for clang... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether clang accepts -g... yes
checking for clang option to enable C11 features... none needed
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln -s works... yes
checking whether make sets $(MAKE)... yes
checking for a race-free mkdir -p... mkdir -p
checking how to run the C preprocessor... clang -E
checking for clang++... clang++
checking whether the compiler supports GNU C++... yes
checking whether clang++ accepts -g... yes
checking for clang++ option to enable C++11 features... -std=gnu++11
checking if the C/C++ compiler is recent enough... yes
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for fcntl.h... yes
checking for inttypes.h... (cached) yes
checking for limits.h... yes
checking for locale.h... yes
checking for malloc.h... no
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for sys/mount.h... yes
checking for sys/param.h... yes
checking for sys/socket.h... yes
checking for sys/statfs.h... no
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for wchar.h... yes
checking for wctype.h... yes
checking for ocamlc... /Users/mantej/.opam/4.14.0+flambda/bin/ocamlc
OCaml version is 4.14.0
OCaml library path is /Users/mantej/.opam/4.14.0+flambda/lib/ocaml
checking for ocamlopt... /Users/mantej/.opam/4.14.0+flambda/bin/ocamlopt
checking for ocamlc.opt... /Users/mantej/.opam/4.14.0+flambda/bin/ocamlc.opt
checking for ocamlopt.opt... /Users/mantej/.opam/4.14.0+flambda/bin/ocamlopt.opt
checking for dynlink.cmxa... yes
checking for ocaml... /Users/mantej/.opam/4.14.0+flambda/bin/ocaml
checking for ocamldep... /Users/mantej/.opam/4.14.0+flambda/bin/ocamldep
checking for ocamlmktop... /Users/mantej/.opam/4.14.0+flambda/bin/ocamlmktop
checking for ocamlmklib... /Users/mantej/.opam/4.14.0+flambda/bin/ocamlmklib
checking for ocamldoc... /Users/mantej/.opam/4.14.0+flambda/bin/ocamldoc
checking for ocamlbuild... /Users/mantej/.opam/4.14.0+flambda/bin/ocamlbuild
checking if OCaml version is >= 4.06.1... yes
checking for ocamlbuild... /Users/mantej/.opam/4.14.0+flambda/bin/ocamlbuild
checking for ocamlfind... /Users/mantej/.opam/4.14.0+flambda/bin/ocamlfind
checking for ocamllex... /Users/mantej/.opam/4.14.0+flambda/bin/ocamllex
checking for ocamllex.opt... /Users/mantej/.opam/4.14.0+flambda/bin/ocamllex.opt
checking for menhir... menhir
checking for OCaml findlib package atdgen... /Users/mantej/.opam/4.14.0+flambda/lib/atdgen
checking for OCaml findlib package biniou... /Users/mantej/.opam/4.14.0+flambda/lib/biniou
checking for OCaml findlib package camlzip... /Users/mantej/.opam/4.14.0+flambda/lib/camlzip
checking for OCaml findlib package easy-format... /Users/mantej/.opam/4.14.0+flambda/lib/easy-format
checking for OCaml findlib package oUnit... /Users/mantej/.opam/4.14.0+flambda/lib/oUnit
checking for utop... no
checking for OCaml findlib package yojson... /Users/mantej/.opam/4.14.0+flambda/lib/yojson
checking which ocamlformat to use... ocamlformat
checking for opam... opam
checking opam version... 2.1.5
checking current opam root... [WARNING] var was deprecated in version 2.1 of the opam CLI. Use opam var instead or set OPAMCLI environment variable to 2.0.
/Users/mantej/.opam
checking current opam switch... 4.14.0+flambda
checking for atdgen... atdgen
checking for getconf... getconf
checking the number of cpus the build host has... 8
checking for ant... no
checking for buck1... no
checking for emacs... no
checking for mvn... no
checking for ndk-build... no
checking for ndk-build... no
checking for ninja... no
checking for xcpretty... no
checking for sed... sed
checking if sed is GNU sed... yes
checking if diff supports --LTYPE-line-format=LFMT options... no
checking for brew... brew
checking for install_name_tool... install_name_tool
checking for ldd... no
checking for otool... otool
checking for patchelf... no
configure: creating ./config.status
config.status: creating Makefile.autoconf
configure: enabled language frontends:  clang
configure: disabled language frontends: erlang, hack, java, python
+ set +x
[12:26:04][60505] Building clang plugin...
[      0s][60505] SUCCESS Building clang plugin
[12:26:04][60527] Building clang plugin OCaml interface...
[*ERROR**][60527] *** ERROR 'Building clang plugin OCaml interface'
[*ERROR**][60527] *** command: ' /Library/Developer/CommandLineTools/usr/bin/make INTERACTIVE=1 -C /Users/mantej/steel-work/infer/facebook-clang-plugins/clang-ocaml build/clang_ast_proj.ml build/clang_ast_proj.mli CC=clang CXX=clang++ -std=gnu++11 CFLAGS="-g -O2" CXXFLAGS="-g -O2" CPP="clang -E" LDFLAGS="" LIBS="" LOCAL_CLANG=/Users/mantej/steel-work/infer/facebook-clang-plugins/clang/install/bin/clang CLANG_PREFIX=/Users/mantej/steel-work/infer/facebook-clang-plugins/clang/install CLANG_INCLUDES=/Users/mantej/steel-work/infer/facebook-clang-plugins/clang/install/include SDKPATH=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk '
[*ERROR**][60527] *** CWD: '/Users/mantej/steel-work/infer'
[*ERROR**][60527] *** stdout:
[*ERROR**][60527] *** stderr:
[*ERROR**][60527] /Library/Developer/CommandLineTools/usr/bin/make: invalid option -- =
[*ERROR**][60527] /Library/Developer/CommandLineTools/usr/bin/make: invalid option -- g
[*ERROR**][60527] /Library/Developer/CommandLineTools/usr/bin/make: invalid option -- u
[*ERROR**][60527] /Library/Developer/CommandLineTools/usr/bin/make: invalid option -- +
[*ERROR**][60527] /Library/Developer/CommandLineTools/usr/bin/make: invalid option -- +
[*ERROR**][60527] /Library/Developer/CommandLineTools/usr/bin/make: invalid option -- 1
[*ERROR**][60527] /Library/Developer/CommandLineTools/usr/bin/make: invalid option -- 1
[*ERROR**][60527] Usage: make [options] [target] ...
[*ERROR**][60527] Options:
[*ERROR**][60527]   -b, -m                      Ignored for compatibility.
[*ERROR**][60527]   -B, --always-make           Unconditionally make all targets.
[*ERROR**][60527]   -C DIRECTORY, --directory=DIRECTORY
[*ERROR**][60527]                               Change to DIRECTORY before doing anything.
[*ERROR**][60527]   -d                          Print lots of debugging information.
[*ERROR**][60527]   --debug[=FLAGS]             Print various types of debugging information.
[*ERROR**][60527]   -e, --environment-overrides
[*ERROR**][60527]                               Environment variables override makefiles.
[*ERROR**][60527]   -f FILE, --file=FILE, --makefile=FILE
[*ERROR**][60527]                               Read FILE as a makefile.
[*ERROR**][60527]   -h, --help                  Print this message and exit.
[*ERROR**][60527]   -i, --ignore-errors         Ignore errors from commands.
[*ERROR**][60527]   -I DIRECTORY, --include-dir=DIRECTORY
[*ERROR**][60527]                               Search DIRECTORY for included makefiles.
[*ERROR**][60527]   -j [N], --jobs[=N]          Allow N jobs at once; infinite jobs with no arg.
[*ERROR**][60527]   -k, --keep-going            Keep going when some targets can't be made.
[*ERROR**][60527]   -l [N], --load-average[=N], --max-load[=N]
[*ERROR**][60527]                               Don't start multiple jobs unless load is below N.
[*ERROR**][60527]   -L, --check-symlink-times   Use the latest mtime between symlinks and target.
[*ERROR**][60527]   -n, --just-print, --dry-run, --recon
[*ERROR**][60527]                               Don't actually run any commands; just print them.
[*ERROR**][60527]   -o FILE, --old-file=FILE, --assume-old=FILE
[*ERROR**][60527]                               Consider FILE to be very old and don't remake it.
[*ERROR**][60527]   -p, --print-data-base       Print make's internal database.
[*ERROR**][60527]   -q, --question              Run no commands; exit status says if up to date.
[*ERROR**][60527]   -r, --no-builtin-rules      Disable the built-in implicit rules.
[*ERROR**][60527]   -R, --no-builtin-variables  Disable the built-in variable settings.
[*ERROR**][60527]   -s, --silent, --quiet       Don't echo commands.
[*ERROR**][60527]   -S, --no-keep-going, --stop
[*ERROR**][60527]                               Turns off -k.
[*ERROR**][60527]   -t, --touch                 Touch targets instead of remaking them.
[*ERROR**][60527]   -v, --version               Print the version number of make and exit.
[*ERROR**][60527]   -w, --print-directory       Print the current directory.
[*ERROR**][60527]   --no-print-directory        Turn off -w, even if it was turned on implicitly.
[*ERROR**][60527]   -W FILE, --what-if=FILE, --new-file=FILE, --assume-new=FILE
[*ERROR**][60527]                               Consider FILE to be infinitely new.
[*ERROR**][60527]   --warn-undefined-variables  Warn when an undefined variable is referenced.
[*ERROR**][60527]   -N OPTION, --NeXT-option=OPTION
[*ERROR**][60527]                               Turn on value of NeXT OPTION.
[*ERROR**][60527]
[*ERROR**][60527] This program built for i386-apple-darwin11.3.0
[*ERROR**][60527] Report bugs to <bug-make@gnu.org>
make[1]: *** [clang_plugin] Error 2
make: *** [opt] Error 2

  compilation failure; you can try running

    make clean
    './build-infer.sh' clang

**Comment by skcho** [comment]
Looking at the failed command, `CXX` is suspicious to include some flags. Could you check how it has been set in `config.status`. For example, for me it is like,

```
S["CXXFLAGS"]="-g -O2"
S["CXX"]="clang++"
```

If `CXX` is including `-std=gnu++11`, I think it is better to set under `CXXFLAGS`.

**Comment by mantejl** [comment]
Just checked the config.status file, and this is what showed up for me:

S["CXXFLAGS"]="-g -O2"
S["CXX"]="clang++ -std=gnu++11"

**Comment by samuelchen2015** [comment]
I ran into the same issue? any idea? build with os 13 and xcode14
