### ISSUE TITLE
Termux command request 

### ISSUE THREAD

**Issue by Khany123** [facebook/infer#1812]
https://github.com/termux/termux-api/issues/595

**Comment by Rk5014** [comment]
Withdrawal

**Comment by Pm081220** [comment]
https://www.facebook.com/pedro.zm.10

**Comment by Wwxzc** [comment]
"#DISPLAY=": {
        "Built-inScreen_falseHDR": {
            "Name": "Built-in Screen",
            "State": "ON",
            "ro.sf.lcd_density": "300",
            "RefreshRate": 60.000003814697266,
            "ScreenSpecs": "720 x 1280",
            "ViewingMetrics": "DisplayMetrics{density=1.875, width=720, height=1280, scaledDensity=1.875, xdpi=294.967, ydpi=295.563}",
            "AllMetrics": "720 x 1280, largest app 1280 x 1280, smallest app 720 x 720, appVsyncOff 2000000, presDeadline 11666666, mode 1, defaultMode 1, modes [{id=1, width=720, height=1280, fps=60.000004, alternativeRefreshRates=[]}], hdrCapabilities HdrCapabilities{mSupportedHdrTypes=[], mMaxLuminance=500.0, mMaxAverageLuminance=500.0, mMinLuminance=0.0}, userDisabledHdrTypes [], minimalPostProcessingSupported false, rotation 0, state ON}",
            "SupportedHdrTypes": "",
            "SupportedModes": "{id=1, width=720, height=1280, fps=60.000004, alternativeRefreshRates=[]}",
            "Mode": "{id=1, width=720, height=1280, fps=60.000004, alternativeRefreshRates=[]}",
            "RefreshRates21": "60.000004",
            "Cutout": "null"
        }
    }

**Comment by Wwxzc** [comment]
"#DISPLAY=": {
        "Built-inScreen_falseHDR": {
            "Name": "Built-in Screen",
            "State": "ON",
            "ro.sf.lcd_density": "300",
            "RefreshRate": 60.000003814697266,
            "ScreenSpecs": "720 x 1280",
            "ViewingMetrics": "DisplayMetrics{density=1.875, width=720, height=1280, scaledDensity=1.875, xdpi=294.967, ydpi=295.563}",
            "AllMetrics": "720 x 1280, largest app 1280 x 1280, smallest app 720 x 720, appVsyncOff 2000000, presDeadline 11666666, mode 1, defaultMode 1, modes [{id=1, width=720, height=1280, fps=60.000004, alternativeRefreshRates=[]}], hdrCapabilities HdrCapabilities{mSupportedHdrTypes=[], mMaxLuminance=500.0, mMaxAverageLuminance=500.0, mMinLuminance=0.0}, userDisabledHdrTypes [], minimalPostProcessingSupported false, rotation 0, state ON}",
            "SupportedHdrTypes": "",
            "SupportedModes": "{id=1, width=720, height=1280, fps=60.000004, alternativeRefreshRates=[]}",
            "Mode": "{id=1, width=720, height=1280, fps=60.000004, alternativeRefreshRates=[]}",
            "RefreshRates21": "60.000004",
            "Cutout": "null"
        }
    }
