### ISSUE TITLE
No issues found / Error during capture phase, exiting on "infer -- mvn install"

### ISSUE THREAD

**Issue by giacgbj** [facebook/infer#182]
Environment:
* infer git-a50ecde01cf990555f2d2e9e5da05af87b8965d7
* Java 1.7.0_71
* Maven 3.3.3
* Python 2.7.10

Running the following commands

```
mvn clean
infer -g --log_to_stderr -- mvn install
```

no issues are found on a project which surely has issues and the file "target/infer-out/toplevel.log" contains

```
[INFO] Running command /Applications/infer/bin/infer -i -o [OMISSIS]/target/infer-out -- javac [OMISSIS] -d [OMISSIS]/target/javacOut -classpath [OMISSIS]
[INFO] Path to infer script /Applications/infer/bin/infer (/Applications/infer/bin/infer)
[INFO] Infer version git-a50ecde01cf990555f2d2e9e5da05af87b8965d7
Copyright 2009 - present Facebook. All Rights Reserved.


[INFO] Platform: Darwin-14.5.0-x86_64-i386-64bit
[INFO] PATH=[OMISSIS]
[INFO] SHELL=/bin/bash
[INFO] PWD=[OMISSIS][INFO] Starting analysi[INFO] [INFO] Starting analysis
[INFO] Capture phase was successful
[u'inferJ', u'-g', u'-a', u'infer', u'javac', '[OMISSIS]']


[ERROR] Error during capture phase, exiting
```

I can't find anywhere which error the logs are referring to.

Moreover, the logs seem not properly "flushed" and the rows mix in different ways each time I run that command.

**Comment by jvillard** [comment]
Hi @giacgbj, sorry for the delay. Is there any chance you could share the project you are trying to analyse, or provide a reproducible example?

In "toplevel.log", the line `[u'inferJ', u'-g', u'-a', u'infer', u'javac', '[OMISSIS]']` has java files instead of `'[OMISSIS]`, right? Just checking that infer actually sees *some* files being compiled.

Lastly, you might want to have a look at #38.

**Comment by giacgbj** [comment]
Hi @jvillard, unfortunaly I cannot share the project: I would be probably fired :-)
[OMISSIS] had a lot of file.

I just installed the stable version v0.4.0 and I tried again: from the error I have now I understood that I had to increase the number of open files, as suggested in #22;
However, still no issues are found.

I don't know if it can help you, but *infer-out/log/analyzer_err* contains
```
Found 591 source files in [OMISSIS]/infer-out
[OMISSIS]
Procedures defined in more than one file: 
Found 0 defined procedures in 0 files.
Analyzing 0 files.

Minimal clusters:

Combined clusters with max size 50
```

**Comment by jvillard** [comment]
Hi @giacgbj, does the latest infer work for you? If not please re-open this issue and paste the full output of infer somewhere (such as gist.github.com). Thank you!
