### ISSUE TITLE
Retain Cycle - Possible False Alarm?

### ISSUE THREAD

**Issue by sphan** [facebook/infer#184]
Hi Infer team,

I have recently used Infer to analyse a few opensource iOS projects for a university subject. I came across 3 retain cycles detected by Infer from the same application and file.

These are the 3 bugs reported:
aMenjar-master/aMenjar/AMQRPedidoViewController.m:638: error: RETAIN_CYCLE
  Retain cycle involving the following objects:  (1) an object of class MBProgressHUD  retaining another object via instance variable _delegate,  (2) object self retaining self._HUD,   at line 638, column 5

aMenjar-master/aMenjar/AMQRPedidoViewController.m:765: error: RETAIN_CYCLE
  Retain cycle involving the following objects:  (1) object self retaining self._btnDer,  (2) an object of class UIBarButtonItem  retaining another object via instance variable _target,   at line 765, column 5

aMenjar-master/aMenjar/AMResumenIpadViewController.m:611: error: RETAIN_CYCLE
  Retain cycle involving the following objects:  (1) an object of class MBProgressHUD  retaining another object via instance variable _delegate,  (2) object self retaining self._HUD,   at line 611, column 5

The application is called aMenjar and its Github location can be found at https://github.com/maurovc/aMenjar.

The 1st bug is between the class AMQRPedidoViewController (self) that has a property of type MBProgressHUD (a strong pointer), MBProgressHUD has a property delegate that is set to AMQRPedidoViewController at line 638 stated. The pointer to the delegate is a weak pointer. So according to the documentation, if 2 objects are pointing to each other, and one of them is strong pointer and the other is a weak pointer, then a retain cycle does not exist as eventually, one of the object can be released and thus the other will be released.

The 3rd bug is the same as the 1st bug

The 2nd bug is for the class AMQRPedidoViewController having a property named btnDer of type UIBarButtonItem. This is a weak pointer from the self object to btnDer. In UIBarButtonItem, there is a target property that can be set. In line 744, [self.btnDer setTarget:self]; is called, hence setting AMQRPedidoViewController as the target of btnDer. Though the target property in UIBarButtonItem is a weak pointer. So the retain cycle does not establish between 2 weak pointers as no ownership is present for both objects.

I think that the bugs reported maybe false alarm, but let me know otherwise if I was incorrect.

Many thanks for your help.

**Comment by ddino** [comment]
hi, 
you are right these are false positives. 

Thanks for reporting them. We will work to improve infer reporting on retain cycles.

**Comment by sphan** [comment]
Hi ddino,

just to confirm on the method and to know if my method was correct, how did you verify that they are false positives?

Thanks.
