### ISSUE TITLE
Maven build with java 17 failed

### ISSUE THREAD

**Issue by mstepan** [facebook/infer#1846]
```
infer run  -- mvn clean package
```
Failed b/c java 11 used as a forked version.

Please include the following information:
- [v] Infer version v1.2.0
- [v] Darwin Kernel Version 23.5.0
- [v] `infer run  -- mvn clean package`
- [v] Compilation errors related to java 17 features, such as records
```
error: records are not supported in -source 11
[ERROR]   (use -source 16 or higher to enable records)
```

**Comment by geralt-encore** [comment]
Can you try `infer --java-version 17 run  -- mvn clean package`?

**Comment by mstepan** [comment]
```
infer --java-version 17 run  -- mvn clean package
```
Works as expected. Thanks.

**Comment by mstepan** [comment]
Issue was clarified.

**Comment by Mason-Fan** [comment]
I have several projects with differnet jdk versions to compile.  Sever default jdk is jdk11
java --version
openjdk 11.0.24

 for a project which need jdk 17
1. export JAVA_HOME=jdk17; mvn clean pakcage 
I can compile it successuflly

2. add infer
export JAVA_HOME=jdk17;  infer --java-version 17 run  --mvn clean pakcage 
compilation failed

so how can I set java version dynamically for mvn project ?
