### ISSUE TITLE
Failed to run InferAnalyze binary, exiting

### ISSUE THREAD

**Issue by wangype** [facebook/infer#187]
hi, I download infer-linux64-v0.4.0.tar.gz and run 'tar -xvzf' to the file on linux system,  report "Failed to run InferAnalyze binary, exiting" when i run infer, can you tell me how to run the infer ,thank you very much.

**Comment by jvillard** [comment]
Hi @wangype, you need to compile Infer to use it. The release only contains a pre-compiled clang because that's the most time-consuming step. Please follow the instructions [here](http://fbinfer.com/docs/getting-started.html).

**Comment by wangype** [comment]
thank you very much~
