### ISSUE TITLE
False positive with NSMutableDictionary and CoreFoundation bridging?

### ISSUE THREAD

**Issue by lumaxis** [facebook/infer#189]
We are using SFHFKeychainUtils in our project and analyzing our code with Infer, I get the following error

```
error: MEMORY_LEAK
memory dynamically allocated to searchData by call to alloc() at line 464, column 37 is not reachable after line 468, column 3
```

for these [lines](https://github.com/bitstadium/HockeySDK-iOS/blob/develop/Classes/BITKeychainUtils.m#L291-L295):

``` objectivec
291 NSMutableDictionary *searchData = [NSMutableDictionary new];
292 [searchData setObject:(__bridge id)kSecClassGenericPassword forKey:(__bridge id)kSecClass];
293 [searchData setObject:serviceName forKey:(__bridge id)kSecAttrService];

295 OSStatus status = SecItemDelete((__bridge CFDictionaryRef)searchData);
```

I'm thinking this might be a false positive or am I overlooking something? Thanks in advance for looking into it.

**Comment by jvillard** [comment]
Hi @lumaxis, thanks for your report. From the small snippet it's not immediately obvious what's wrong, we'll look into it.

PS: It seems that the project you linked to is gone [(404 here)](https://github.com/kamiro/SFHFKeychainUtils).

**Comment by lumaxis** [comment]
Hey @jvillard, thanks for looking into this! After being online for 3 years, the project out of all days was removed now ... weird.
I updated the links in my original post to point to the part of our code where we use SFHFKeychainUtils, hope that helps debugging.

**Comment by lumaxis** [comment]
This is almost 5 years old now, probably not relevant anymore 🙂

**Comment by dulmarod** [comment]
@lumaxis as it happens, I'm currently writing a new version of this check with improved bridging. Do you still use Infer for Objective-C at all?

**Comment by lumaxis** [comment]
Hah, amazing timing 🙂
Actually, I've personally moved on from iOS/Objective-C entirely and am not involved in that ecosystem at all anymore.

**Comment by lumaxis** [comment]
Feel free to reopen this though if it's helpful for others!
