### ISSUE TITLE
Unclear on howto use for cross compiler

### ISSUE THREAD

**Issue by stewart-ibm** [facebook/infer#19]
It seems to be rather hard to use with a cross compiler. Rather than gcc, we have, say, powerpc64-linux-gcc being the compiler we use to compile our project. It appears as though if I symlink it to gcc in infer-linux64-v0.1.0/infer/infer/lib/wrappers/ I get further, but I think I then run foul of some compiler options we need.

It appears as though the facebook-clang-plugin is an actual copy of clang and targets x86-64 ? So, I likely need to build infer from source and build with it?

I'm happy to go do that and contribute docs, but was wondering if there's any other possible gotchas that I may be missing.

**Comment by irpap** [comment]
Thanks for your report. What language is the project in? Infer is using clang under the hood, specifically the open source clang that ships with facebook-clang-plugin (even if you pass it --gcc). Would your code compile with clang?

**Comment by stewart-ibm** [comment]
It's the skiboot part of OpenPower firmware (github.com/open-power/skiboot) which is written in C and is buildable by clang on ppc64el (although clang won't build a bootable image).

Sounds like if I build infer on ppc64el it would build a ppc64el clang which should be able to deal with my codebase. I'll give it a go and see.

**Comment by sblackshear** [comment]
Did this end up working for you?

**Comment by jvillard** [comment]
Feel free to re-open if there is an issue in infer preventing you from analasing cross-compiled projects.

**Comment by vChavezB** [comment]
Was there any update on how to make this work?
I am trying to incorporate different static analysis tools and was considering infer. But based on the fact that it uses [clang](https://github.com/facebook/infer/issues/19#issuecomment-112095448) would I be correct to assume that if I am already using Codechecker there wouldnt be a need to use infer right?
