### ISSUE TITLE
Error while doing "make -C infer"

### ISSUE THREAD

**Issue by RameshAran** [facebook/infer#190]
After installing all dependencies while I do "make -C infer", I am getting the following error.

I was following steps from 

https://github.com/facebook/infer/blob/master/INSTALL.md#install-the-dependencies
http://fbinfer.com/docs/getting-started.html

Error from console
=======================================

In file included from wctype.cIn file included from In file included from glib.c:In file included from 14xlib.cwchar.c::infer_builtins.c1310::::
:In file included from 1313 :
math.c13./infer_builtins.h:
::
./infer_builtins.h13::13fatal error./infer_builtins.h:: 13:
:./infer_builtins.h1010:::'wctype.h'  :./infer_builtins.h13::1310fatal error 13:: file10 ::not:  found'stdlib.h'10  :fatal error 
: fatal errorfatal errorfile: fatal error:  'stdlib.h': not'stdlib.h'  file'stdlib.h'  foundfilenot 'stdlib.h'file   found notnot #include <wctype.h>file  
found
notfound          ^
found

#include <stdlib.h>
         ^#include <stdlib.h>
#include <stdlib.h>

         ^#include <stdlib.h>         ^

#include <stdlib.h>

         ^
         ^
In file included from libc_basic.c:29:
./infer_builtins.h:13:10: fatal error: 'stdlib.h' file not found
#include <stdlib.h>
         ^
1 error generated.
1 error generated.
1 error generated.
1 error generated.
1 error generated.
make[3]: *** [glib.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [xlib.o] Error 1
make[3]: *** [infer_builtins.o] Error 1
1 error generated.
make[3]: *** [wctype.o] Error 1
1 error generated.
make[3]: *** [wchar.o] Error 1
make[3]: *** [libc_basic.o] Error 1
make[3]: *** [math.o] Error 1
make[2]: *** [run_infer] Error 2
make[1]: *** [/Users/<user>/Documents/infer-osx-v0.4.0/infer/models/../lib/specs/c_models] Error 2
make: *** [clang] Error 2

Console log ends here
==================================================

Not sure what is happening here. Please help. I am using the following environment.

Mac OSX - 10.10.4 (14E46)
have both Xcode 7 and Xcode 6.4, not sure this will cause something weird. 

I am getting this error in both cases , while using compiled version as well as precompiled version.

**Comment by jvillard** [comment]
@RameshAran have you tried reinstalling the command-line tools?

```sh
xcode-select --install
```

This looks similar to #132.

**Comment by RameshAran** [comment]
@jvillard, Thank you. Yes,  its working now.
