### ISSUE TITLE
Getting error while doing Compile Infer from source with clang enabled steps

### ISSUE THREAD

**Issue by bhargav1** [facebook/infer#193]
for ./compile-fcp.sh getting error
bash: ocamlfind: command not found
make: *** [build/clang_ast_types.cmx] Error 127

for  make -C infer getting 
make -C src clang
GIT_COMMIT=$(git rev-parse HEAD 2> /dev/null || printf "unknown commit"); \
	GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2> /dev/null || printf "unknown branch"); \
	UNKNOWN="-unknown"; \
	if [ -e "/Users/bhargavsuthar/infer/.release" ]; then \
	  UNKNOWN=""; \
	fi; \
	GIT_TAG=$(git tag --points-at HEAD 2> /dev/null || printf "v0.4.0$UNKNOWN"); \
	sed -e 's/@MAJOR@/0/g' \
		-e 's/@MINOR@/4/g' \
		-e 's/@PATCH@/0/g' \
		-e "s/@GIT_COMMIT@/$GIT_COMMIT/g" \
		-e "s#@GIT_BRANCH@#$GIT_BRANCH#g" \
		-e "s/@GIT_TAG@/$GIT_TAG/g" \
		backend/version.ml.in > backend/version.ml
make[1]: *** No rule to make target `/Users/bhargavsuthar/infer/facebook-clang-plugins/clang-ocaml/build/clang_ast_converter', needed by `clang/clang_ast_t.ml'.  Stop.
make: *** [clang] Error 2

**Comment by jvillard** [comment]
Did you install the [dependencies](https://github.com/facebook/infer/blob/master/INSTALL.md#infer-dependencies-for-macosx)? It looks like ocaml is not installed on your system.

**Comment by bhargav1** [comment]
yes i had install already that dependencies

**Comment by jvillard** [comment]
Can you run `which ocamlfind`, then `./compile-fcp.sh`? Maybe you didn't run `eval $(opam config env)` before `./compile-fcp.sh`?

**Comment by bhargav1** [comment]
eval $(opam config env)
work before ./compile-fcp.sh

Thanks
