### ISSUE TITLE
Failed to run InferAnalyze binary, exiting When the infer run

### ISSUE THREAD

**Issue by oatsuper** [facebook/infer#198]
On  unbuntu ,I git clone the source code ,and updated the bashrc for Infer

I met "Failed to run InferAnalyze binary, exiting" and the infer run fail

and How can I do static analysis the android code with android eclipse project 

Thanks~

**Comment by martinoluca** [comment]
Hello @oatsuper,
About the "Failed to run InferAnalyze binary, exiting" error, you have to compile the binaries of Infer first, please follow the instructions [here](http://fbinfer.com/docs/getting-started.html).

About Eclipse, there's no plugin to run Infer from the UI, but you can still run Infer on your source code through the command-line. If your project builds with gradle, and the task to build it is `build`, then you can simply run the following command:
```
infer --incremental -- gradle build
```

Same rule applies to other build systems like buck, maven, ant and make.

Thanks.

**Comment by oatsuper** [comment]
Thanks you very much~

**Comment by martinoluca** [comment]
Feel free to open this issue again if the problem persists.

Thanks!

**Comment by IgorGanapolsky** [comment]
Still getting this same error.

**Comment by jvillard** [comment]
@igorcanadi what steps did you follow to compile infer? Also, there's no need to comment on multiple closed issues.

**Comment by IgorGanapolsky** [comment]
I followed every single step I could find about Infer.  Installed
everything.  And yes, comments need to happen on multiple issues until
problem is resolved.

**Comment by jvillard** [comment]
Can you be more specific about the steps you followed? For instance, did you run `./build-infer.sh` successfully? What version of Infer are you trying to use?

I disagree that comments should be posted on several issues, because one issue should correspond to one problem only. The symptoms may be the same (eg, "it crashes"), but the causes are likely to be different.

**Comment by IgorGanapolsky** [comment]
Multiple issues were found through Google search engine pointing at the
same error.  Yea, I ran the commands you are specifying, trying to use
latest version of Infer last night.
