### ISSUE TITLE
Use Infer in Android Studio project , It appear unrecognized arguments

### ISSUE THREAD

**Issue by ruijun** [facebook/infer#199]
When I use `infer –- ./gradlew build` to android studio project TestInfer

ruijun-MacBookPro:TestInfer ruijun$ infer –- ./gradlew build
usage: infer [-h] [-o <directory>] [-i] [-ic] [-g] [-a ANALYZER] [-nf]
             [—fail-on-bug] [—android-harness] [-l] [—log_to_stderr] [-v]
             [-j n] [-x <projectname>] [-r <githash>] [—buck]
             [—infer_cache <directory>] [-pr PROJECT_ROOT] [—absolute-paths]
             [—ml_buckets ML_BUCKETS] [-nt] [—specs-dir <dir>] [— <cmd>]
infer: error: unrecognized arguments: –- ./gradlew build

How can I solve this ?

**Comment by jvillard** [comment]
You are using `–-` (long-dash dash) instead of `--` (dash dash) in your infer command. Try `infer -- ./gradlew build`.

**Comment by ruijun** [comment]
@jvillard Thank you, it is work for me.
