### ISSUE TITLE
Support @import of modules in Objective-C

### ISSUE THREAD

**Issue by streeter** [facebook/infer#2]
While trying out infer on my project, it fails with the build error:

```
error: use of '@import' when modules are disabled
    @import Foundation;
    ^
1 error generated.
```

I tried passing `CLANG_ENABLE_MODULES=YES` as an environment variable (it is already enabled in my project and `xcodebuild` runs cleanly), but seems to be ignored.

**Comment by triage** [comment]
+1

**Comment by loufranco** [comment]
This seems to be purposely turned off because the open-source clang doesn't support it:

https://github.com/facebook/infer/blob/master/infer/lib/clang/clang_wrapper#L18

**Comment by dostrander** [comment]
+1

**Comment by sk-** [comment]
+1

**Comment by dzlobin** [comment]
+1

**Comment by Nykho** [comment]
+1

**Comment by kerrmarin** [comment]
+1

**Comment by bootstraponline** [comment]
:+1:

**Comment by qmoya** [comment]
+1

**Comment by vitormf** [comment]
+1

**Comment by altyus** [comment]
++

**Comment by matto1990** [comment]
Same issues for me

**Comment by stavash** [comment]
+1

**Comment by micahelcheng** [comment]
+1

**Comment by Mo7amedFouad** [comment]
+1

**Comment by IanKeen** [comment]
+1

**Comment by artoyer** [comment]
error: use of '@import' when modules are disabled
@import Foundation;
^

I'm getting the same error. Any news when it will be fixed?

**Comment by martinoluca** [comment]
This issue has been addressed, please consider using the latest release available in:
https://github.com/facebook/infer/releases/latest

Reopen this task if the problem still persists.

**Comment by muzixiaowu** [comment]
+1

**Comment by zhangying19871987** [comment]
+1
