### ISSUE TITLE
Use system clang on OSX

### ISSUE THREAD

**Issue by yurikoles** [facebook/infer#20]
This can avoid most errors with features which Apple is not pushed to upstream, like nullable

**Comment by martinoluca** [comment]
Hello @yurikoles, thanks for asking this question.
Infer analysis for clang based source-code requires the use of clang plugins, and plugins don't work with Apple's clang.
In the specific, Infer uses the `YojsonASTExporter` plugin provided by https://github.com/facebook/facebook-clang-plugins

We are currently investigating the `nullable` issue, the problem should be fixed soon.
