### ISSUE TITLE
make -C infer  can't find wctype.h or stdlib.h

### ISSUE THREAD

**Issue by andrewbutterfield** [facebook/infer#200]
I tried to install infer, but the build failed with a number of errors - unable to find certain header files:

examples:
wctype.c:14:10: fatal error: 'wctype.h' file not found
#include <wctype.h>
         ^
In file included from math.c:13:
./infer_builtins.h:13:10: fatal error: 'stdlib.h' file not found
#include <stdlib.h>
         ^
In file included from infer_builtins.c:13:

(see attachedfile for full log transcript).

My setup at build time:

OS X 10.10.5
opam 1.2.2
clang-700.1.76
Python 2.7.10
My Xcode is 7.1,  your dependencies suggest  6.1 to 7.0 - is this a problem?
Java 1.7 is not available anymore - I'm not pushed - I don't do Java....

[build-fail-20151111.txt](https://github.com/facebook/infer/files/32074/build-fail-20151111.txt)

**Comment by martinoluca** [comment]
Hello @andrewbutterfield,
Have you installed the xcode command-line tools?
If not, the command to install them is:
```
xcode-select --install
```

**Comment by andrewbutterfield** [comment]
Gah! I thought those were installed! I did as you suggested and all now seems to work (I get warnings about no Java, but that's fine)

PS - will installing JDK 1.8 work with current infer, or does it have to be 1.7?

**Comment by martinoluca** [comment]
Hello @andrewbutterfield,
You can use JDK 1.8 but new Java 8 constructs in source code are not supported.

Feel free to reopen this issue in case the problem still persists.

**Comment by akotulski** [comment]
@andrewbutterfield regarding JDK 1.8, we don't really support it yet and we encourage to use JDK 1.7.
While JDK 1.8 might work for some projects, infer might crash for some projects.

You are also fine with JDK 1.8 as long as you are not analyzing java code.

**Comment by andrewbutterfield** [comment]
That's OK - I'll skip the Java for now. I managed to get it to run on C - and got some Null Dereference errors - so now I am happy! Thanks for your help.
