### ISSUE TITLE
Retain Cycle not work

### ISSUE THREAD

**Issue by keywind** [facebook/infer#201]
I test infer for detecting retain cycle with simple exsample:

In ViewController.m:

    @property (strong, nonatomic) TestView *testView;

    self.testView = [TestView new];
    self.testView.controller = self;

In TestView.m 

    @property (strong, nonatomic) ViewController *controller;

Run infer and give me some other issue but no Retain Cycle warning.

**Comment by dulmarod** [comment]
Hi, could you paste the exact code that you tried to run? Was the code 

self.testView = [TestView new];
self.testView.controller = self;

inside a method?

**Comment by dulmarod** [comment]
Also can you paste the command that you used for analysing those files with Infer?

**Comment by ddino** [comment]
Hi this is an interesting example.
As Dulma suggest can you paste the full example and the command to run infer and we will look into that.

Thanks,
Dino

Sent from my iPhone

On 18 Nov 2015, at 07:09, Dafeng Jin <notifications@github.com<mailto:notifications@github.com>> wrote:


I test infer for detecting retain cycle with simple exsample:

In ViewController.m:

@property (strong, nonatomic) TestView *testView;

self.testView = [TestView new];
self.testView.controller = self;


In TestView.m

@property (strong, nonatomic) ViewController *controller;


Run infer and give me some other issue but no Retain Cycle warning.

**Comment by keywind** [comment]
Sorry for the lack of information.

The example is really simple, I just upload it: https://github.com/keywind/InferSample.

and I run Infer as this: 

<img width="483" alt="2015-11-18 5 44 24" src="https://cloud.githubusercontent.com/assets/782770/11237719/815f23ec-8e1c-11e5-9dad-863b88cd78f7.png">

The PARAMETER_NOT_NULL_CHECKED issue works and the Retain Cycle not.

**Comment by dulmarod** [comment]
If you add this function 

void t() {
    ViewController *controller = [ViewController new];
    [controller viewDidLoad];
}

you will get the cycle. Infer only reports it when the variable involved in the cycle is going out of scope.

**Comment by dulmarod** [comment]
We will look into improving reporting of cycles. Will close this issue for now. Feel free to reopen if you have more questions.

**Comment by tingxuan** [comment]
mark
