### ISSUE TITLE
Unable to build ios app with Apple watch extension : infer

### ISSUE THREAD

**Issue by sulthana** [facebook/infer#203]
I am trying to build and check possible crashes and errors for iOS app with Apple watch extension. The command I am using is like below,
infer -- xcodebuild -target TestApp -configuration Debug -sdk iphonesimulator

This is not getting build with the following error,
Check dependencies
target specifies product type 'com.apple.product-type.watchkit2-extension', but there's no such product type for the 'iphonesimulator' platform

Please help me in resolving this issue.

Thanks in advance!

**Comment by martinoluca** [comment]
Hello @sulthana,
The support for the analysis of the Watch extension is not yet implemented, we are working on it.

Thanks.

**Comment by Leandros** [comment]
Any progress on that?

**Comment by jvillard** [comment]
It seems that the version of clang used in Infer since [0.8.1](https://github.com/facebook/infer/releases/v0.8.1) supports the flags used to compile Watch apps. Please try the latest version of Infer on your project and re-open this issue if it still doesn't work. Thanks!
