### ISSUE TITLE
Pop/WebCore/TransformationMatrix.cpp normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler (1 failure)

### ISSUE THREAD

**Issue by xuejunxd** [facebook/infer#204]
when we use infer to analyze project ,will get error as follow,but the project can be compiled successfully with xcodebuild 。

 In file included from <module-includes>:2:
1610 In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:10:
1611 In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:5:
1612 In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:8:
1613 /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSZone.h:8:1: error: expected unqualified-i
1614 @class NSString;
1615 ^
1616 /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSZone.h:18:64: error: unknown type name 'N
1617 FOUNDATION_EXPORT void NSSetZoneName(NSZone * __nullable zone, NSString *name)NS_SWIFT_UNAVAILABLE("Zone-based memory management is unavailable");
1618                                                                ^
1619 /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSZone.h:19:19: error: unknown type name 'N
1620 FOUNDATION_EXPORT NSString *NSZoneName(NSZone * __nullable zone) NS_SWIFT_UNAVAILABLE("Zone-based memory management is unavailable");
1621                   ^
1622 While building module 'QuartzCore' imported from /Users/djisoftmacpro/.jenkins/jobs/DJI_GO_A3_Static_Analyze/workspace/DJI-ThirdPart/source/Pop/WebCore/TransformationMatrix.h:31:
1623 While building module 'Foundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk/System/Library/Frameworks/QuartzCore.framework/He
1624 In file included from <module-includes>:2:

**Comment by jvillard** [comment]
could you paste a more complete output on https://gist.github.com/? the output is truncated here, eg, line 1613 cuts after "expected unqualified-i".

**Comment by jvillard** [comment]
please re-open this issue if the latest version of Infer doesn't solve your problem.
