### ISSUE TITLE
inferAnalyze stuck at 100% cpu, no io

### ISSUE THREAD

**Issue by Gohan** [facebook/infer#205]
GohanMBP:tribe_proj chaozhong$ infer -- ./gradlew :compileProductDebugSources
Running and capturing gradle compilation...
16:54:50.571 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:54:50.581 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:54:50.582 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
16:54:50.583 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
Starting analysis (Infer version git-867e7804afef05234396aa619a7f5d3707f28cf8)
Computing dependencies... 100%
Analyzing 1489 clusters....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................^[[C.............................................................................................................................................................................

^Cmake: *** Deleting file `cl1361'
Traceback (most recent call last):
  File "/usr/local/share/infer/infer/bin/infer", line 180, in <module>
    main()
  File "/usr/local/share/infer/infer/bin/infer", line 166, in main
    analysis.analyze_and_report()
  File "/usr/local/share/infer/infer/lib/python/inferlib/analyze.py", line 547, in analyze_and_report
    if self.analyze() == os.EX_OK:
  File "/usr/local/share/infer/infer/lib/python/inferlib/analyze.py", line 456, in analyze
    self.args.analyzer
  File "/usr/local/share/infer/infer/lib/python/inferlib/analyze.py", line 231, in run_command
    return subprocess.check_call(cmd)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1384, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
GohanMBP:tribe_proj chaozhong$ make: *** [cl1361] Interrupt: 2

**Comment by jvillard** [comment]
The analysis can take some time, a few minutes to a few hours depending on the size of the app. As long as infer is printing dots it's still running usefully.

**Comment by sblackshear** [comment]
We fixed an infinite loop in the latest release that should hopefully fix the issue. Feel free to re-open if not.
