### ISSUE TITLE
Build failed: clang: error: unknown argument: '-fembed-bitcode-marker'

### ISSUE THREAD

**Issue by TequilarTomsk** [facebook/infer#207]
I try to build xcode project with cocoapods.
After run pod install, I tried to build work space by command:
infer -- xcodebuild -workspace Test.xcworkspace -scheme Test
But it always returns error: clang: error: unknown argument: '-fembed-bitcode-marker'
Please help

**Comment by martinoluca** [comment]
Hello @TequilarTomsk,
We recently updated the version of clang, that supports this flag.
The release is not ready yet, so you need to compile Infer from source following the instructions [here](http://fbinfer.com/docs/getting-started.html) (look at the `Dependencies` section, then follow the `Compile and install Infer`).

Thanks!

**Comment by martinoluca** [comment]
Hello @TequilarTomsk,
I had a better look at that and seems like the version of clang in use doesn't support that flag yet, so please update your release of Infer to a recent one that is skipping that flag and should proceed with the analysis.

Thanks!

**Comment by martinoluca** [comment]
Just to clarify, please visit https://github.com/facebook/infer/releases/tag/v0.4.0/latest and download the latest release; that should fix your problem. 
To install it, please follow the instructions [here](http://fbinfer.com/docs/getting-started.html)

Thanks!

**Comment by TequilarTomsk** [comment]
Thank you so much!!!!!!!!!

**Comment by TequilarTomsk** [comment]
@martinoluca  So sorry.I checked again and I think I installed the latest version v0.4.0 ;(
But it always returns error: clang: error: unknown argument: '-fembed-bitcode-marker'
only in case when I try to build workspace

**Comment by jvillard** [comment]
@TequilarTomsk you can check which version of infer you are using with

  infer --version

Can you post the contents of infer-out/toplevel.log from where you've run infer to help us debug?

**Comment by TequilarTomsk** [comment]
@jvillard Please check some log files.
[toplevel.log.zip](https://github.com/facebook/infer/files/51614/toplevel.log.zip)
[toplevel.log.zip](https://github.com/facebook/infer/files/51615/toplevel.log.zip)

**Comment by TequilarTomsk** [comment]
@jvillard Here are the screen capture when I tried to build
<img width="541" alt="screen shot 2015-12-04 at 10 48 48 am" src="https://cloud.githubusercontent.com/assets/10858548/11581483/140f8088-9a75-11e5-8941-0cf79a9d9dd6.png">
<img width="780" alt="screen shot 2015-12-04 at 10 51 16 am" src="https://cloud.githubusercontent.com/assets/10858548/11581482/140ee9b6-9a75-11e5-9996-fbffca54c6bd.png">

**Comment by njafei** [comment]
open your project 
in Build Setting ，search Enable BitCode ，then set NO
wish can help

**Comment by jvillard** [comment]
@TequilarTomsk sorry, that's an issue with v0.4.0 that has been addressed since (9db0648cb1d9b9512dc5c5b7c5ef68db2f891a29). Please upgrade to latest master or wait until we publish a new release (should be soon!).
