### ISSUE TITLE
can I collect warning infomation by Eradicate?

### ISSUE THREAD

**Issue by njafei** [facebook/infer#210]
I read document ,and find that Eradicate can report warning like null thing, but when I read report.json, I did't find warning infomation,
so here is my question: can collect warnings by Eradicate?
I have tried inferTraceBugs, but  it not work
thanks

**Comment by akotulski** [comment]
@njafei you need to add `-a eradicate` flag to run eradicate analyzer. Eradicate only works for @Nullable annotations in java.

You need to run something like this:
infer -a eradicate -- ...

**Comment by njafei** [comment]
@akotulski  so I can't use it to collect warning in Object-C
in infer's log,I found something like:
/InferTest/DetailViewController.m:34:15: warning: 
      unused variable 'price' [-Wunused-variable]
    NSString *price;
              ^
1 warning generated.

but it did's show in report,can I collect warnings like this?I mean it's loged,so there is a way to collect it?

**Comment by jvillard** [comment]
@njafei there is no equivalent of eradicate for ObjC at the moment. The warning you see is from the compiler (clang), not infer.

**Comment by njafei** [comment]
@jvillard  get it ,thanks
