### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by ruimaranhao** [facebook/infer#212]
Hi, 

I am not able to do ./configure when trying to install. I am following the instructions in INSTALL.md.

 ✘ maranhao@crystal-wlan  ~/PARC/Static/infer   master  ./configure
zsh: no such file or directory: ./configure

Any idea what is going on?

Thanks.

**Comment by sblackshear** [comment]
Are you running `./autogen.sh` beforehand, and does it complete with no errors? Errors during autogen could prevent `configure` from being generated.

**Comment by ruimaranhao** [comment]
Yes, I am.

**Comment by ruimaranhao** [comment]
Oh wait, there is something going on here: 

generating ./configure script..../autogen.sh: line 32: autoreconf: command not found

Ok. Thanks. This was already useful.

**Comment by sblackshear** [comment]
No problem!

Sounds like you may be missing `auoconf` and `automake`; `yum install autoconf automake` (or the equivalent for your package manager) should hopefully do the trick.

**Comment by marukami** [comment]
Thanks @sblackshear 
I had a same issue. Should ```brew install opam``` be updated to  ```brew install opam autoconf automake``` in the https://github.com/facebook/infer/blob/master/INSTALL.md#infer-dependencies-for-macosx

**Comment by jvillard** [comment]
we'll add this to the instructions, thanks!
