### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by veryitman** [facebook/infer#213]
Hi
i run:
make -C infer
and happen error:
make: *** No targets specified and no makefile found.  Stop.

My pc is mac os 10.11.1 and xcode7.

**Comment by veryitman** [comment]
please help me.

**Comment by jvillard** [comment]
The way to build infer has changed; now you need to run

```sh
./autogen.sh
./configure
make
```

**Comment by veryitman** [comment]
@jvillard 
why not update doc?
i download from https://github.com/facebook/infer/releases/tag/v0.4.0, and build successfully!

**Comment by Hellengo** [comment]
hi, 
make -C infer
make: *** No targets specified and no makefile found.  Stop.

then run:

./autogen.sh
git repository detected, updating submodule... done
generating acinclude.m4... done
generating ./configure script..../autogen.sh: line 29: autoreconf: command not found

./configure
zsh: no such file or directory: ./configure


My pc is mac os 10.10.5 and xcode7.2

**Comment by jvillard** [comment]
@Hellengo you can use `brew install infer` to install infer on mac os.

If you want to compile infer yourself, you need to upgrade your version of ocaml. Assuming you use opam:

```sh
opam switch 4.02.3
eval $(opam config env)
opam pin add --yes --no-action infer .
opam install --deps-only infer
./build-infer.sh
```

**Comment by Hellengo** [comment]
@jvillard  thx，use brew install infer solve my problem, cool
