### ISSUE TITLE
Stuck with 100% CPU usage

### ISSUE THREAD

**Issue by vigneshr89** [facebook/infer#214]
I have used infer to analyze my iOS project. Its a big project with lots of dependencies (sub projects). Normally the compilation takes around 5 mins with xctool. But with Infer it is extremely slow (1.30 mins and stuck with 90% CPU usage). The machine I have is really powerful and fast. Sorry, I can't share source code.

**Comment by martinoluca** [comment]
Hello @vigneshr89, could you please provide more information, for example the console output where it gets stuck? It will help understanding more what's happening.

Thanks.

**Comment by jberdine** [comment]
Also, you should expect infer to take much longer than the compiler.  As long as it continues to print dots ('.') on the terminal, progress is being made.

**Comment by vigneshr89** [comment]
@martinoluca there is no specific console output . It was xcodebuild compile command for a .m file and stopped there for around 20 mins. 
@jberdine I understand that it will be slower than the compiler but 90 mins and counting seemed to be way long. Definitely Facebook source code must be much bigger than mine. I am wondering how much it takes for infer to analyze the source code.  

It could be because infer stuck on a infinite loop in code. If thats the case, a guard or time out for a file could help.

**Comment by sblackshear** [comment]
We fixed an infinite loop bug in the latest release (though the loop was in Java analysis code); would you mind giving it another try?

**Comment by vigneshr89** [comment]
Sure. I will try after Tuesday and Post the update

**Comment by vigneshr89** [comment]
The issue is resolved now. The time taken to analyze is reasonable too. Closing the issue. Thanks for fix.

**Comment by sblackshear** [comment]
Awesome, glad to hear it!
