### ISSUE TITLE
error"Failed to run InferAnalyze binary, exiting"

### ISSUE THREAD

**Issue by qiuhm** [facebook/infer#218]
My os is mac os 10.10.5.
I have downloaded the Infer version 0.4.0 and set the environment path.
But when I changed to the dicrctory /Applications/infer-osx-v0.4.0/examples/ios_hello,I execute the command :infer -- xcodebuild -target HelloWorldApp -configuration Debug -sdk iphonesimulator ,it infos me the error:Failed to run InferAnalyze binary, exiting.
Could anybody help me ?

**Comment by jvillard** [comment]
It looks like you did not compile infer. Please follow the instructions here: http://fbinfer.com/docs/getting-started.html

**Comment by tingxuan** [comment]
Now I execute the shell script:/Users/tingxuanqhm/libtool/infer/build-infer.sh
But it infos me the error:
checking if we are in an Infer release build... yes
checking whether to use the compilers in /Users/tingxuanqhm/libtool/infer/facebook-clang-plugins/clang/bin... yes
checking for shasum... shasum
checking for python2.7... python2.7
checking for javac... javac
checking for xcode-select... xcode-select
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/Users/tingxuanqhm/libtool/infer':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

I have tried to find the solution of the problem,But it seems like helpless.
So What can I do now?Thanks very much.

**Comment by martinoluca** [comment]
Hello @tingxuan,
Please check whether you have the command-line tools already installed. If not, please run
```
xcode-select --install
```
to install them. Once you've done it, try running `build-infer.sh` again.

Thanks.
