### ISSUE TITLE
What are the extra features & Support provided by Infer compared to Clang

### ISSUE THREAD

**Issue by sulthana** [facebook/infer#219]
Could you please let me know what are the extra features & support provided by Infer compared to Clang. When I run Analyzer option available in Xcode tool, its listing all the possible leaks. The same output I am getting if I run Infer. Please provide the details on the same.

Thanks in advance!

**Comment by jeremydubreil** [comment]
Hi @sulthana. Do you get the same list of leaks with both tools ?

**Comment by sulthana** [comment]
Hi @jeremydubreil, When I tested I am getting the same list of leaks with both Xcode Analyze option and Infer. This is where I got a doubt that when Apple itself is poviding options in its IDE, Why are we going for Infer? Even in Infer FAQ page, I have seen like "On iOS there is the Clang Static analyzer. Infer does some things different, in particular reasoning that spans across multiple files. But CSA checks for more kinds of issues and is also more mature than Infer when it comes to iOS" Please provide details on the same with the extra fetures that are povided by Infer compared to Clang.

Thanks!

**Comment by jvillard** [comment]
Infer and CSA are two different tools that check for errors in very different ways. It's hard to compare precisely, but you can find more details in the documentation about [Infer error types for C and Objective-C](http://fbinfer.com/docs/infer-bug-types.html).
