### ISSUE TITLE
Segmentation fault to compile wchar.c on Centos7

### ISSUE THREAD

**Issue by gushengyuan** [facebook/infer#220]
[sgu1@localhost src]$ /home/sgu1/Downloads/infer-linux64-v0.5.0/facebook-clang-plugins/clang/bin/clang -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -main-file-name wchar.c -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -target-linker-version 2.22 -dwarf-column-info -coverage-file /home/sgu1/Downloads/infer-linux64-v0.5.0/infer/models/c/src/wchar.o -resource-dir /home/sgu1/Downloads/infer-linux64-v0.5.0/facebook-clang-plugins/clang/bin/../lib/clang/3.8.0 -internal-isystem /usr/local/include -internal-isystem /home/sgu1/Downloads/infer-linux64-v0.5.0/facebook-clang-plugins/clang/bin/../lib/clang/3.8.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -Wno-everything -w -fdebug-compilation-dir /home/sgu1/Downloads/infer-linux64-v0.5.0/infer/models/c/src -ferror-limit 19 -fmessage-length 211 -fobjc-runtime=gcc -fdiagnostics-show-option -load /home/sgu1/Downloads/infer-linux64-v0.5.0/infer/lib/clang_wrappers/../../../facebook-clang-plugins/libtooling/build/FacebookClangPlugin.dylib -add-plugin BiniouASTExporter -plugin-arg-BiniouASTExporter - -plugin-arg-BiniouASTExporter PREPEND_CURRENT_DIR=1 -o wchar.o -x c wchar.c 
0  clang                     0x00000000027e7145 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 37
1  clang                     0x00000000027e57b6 llvm::sys::RunSignalHandlers() + 54
2  clang                     0x00000000027e5995
3  libpthread.so.0           0x00007f02f29b7100
4  libstdc++.so.6            0x00007f02f2352f38 std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) + 24
5  FacebookClangPlugin.dylib 0x00007f02f1767beb ASTPluginLib::PluginASTOptionsBase::makeMap(std::vector<std::string, std::allocator<std::string> > const&) + 347
6  FacebookClangPlugin.dylib 0x00007f02f176b44c
7  clang                     0x00000000007b4a19 clang::FrontendAction::CreateWrappedASTConsumer(clang::CompilerInstance&, llvm::StringRef) + 329
8  clang                     0x00000000007b5ec8 clang::FrontendAction::BeginSourceFile(clang::CompilerInstance&, clang::FrontendInputFile const&) + 4840
9  clang                     0x000000000078dbe5 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 229
10 clang                     0x0000000000771da5 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 1541
11 clang                     0x000000000076a718 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) + 2328
12 clang                     0x000000000074d076 main + 6550
13 libc.so.6                 0x00007f02f19dcb15 __libc_start_main + 245
14 clang                     0x000000000076901d
Stack dump:
0.	Program arguments: /home/sgu1/Downloads/infer-linux64-v0.5.0/facebook-clang-plugins/clang/bin/clang -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -main-file-name wchar.c -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -target-linker-version 2.22 -dwarf-column-info -coverage-file /home/sgu1/Downloads/infer-linux64-v0.5.0/infer/models/c/src/wchar.o -resource-dir /home/sgu1/Downloads/infer-linux64-v0.5.0/facebook-clang-plugins/clang/bin/../lib/clang/3.8.0 -internal-isystem /usr/local/include -internal-isystem /home/sgu1/Downloads/infer-linux64-v0.5.0/facebook-clang-plugins/clang/bin/../lib/clang/3.8.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -Wno-everything -w -fdebug-compilation-dir /home/sgu1/Downloads/infer-linux64-v0.5.0/infer/models/c/src -ferror-limit 19 -fmessage-length 211 -fobjc-runtime=gcc -fdiagnostics-show-option -load /home/sgu1/Downloads/infer-linux64-v0.5.0/infer/lib/clang_wrappers/../../../facebook-clang-plugins/libtooling/build/FacebookClangPlugin.dylib -add-plugin BiniouASTExporter -plugin-arg-BiniouASTExporter - -plugin-arg-BiniouASTExporter PREPEND_CURRENT_DIR=1 -o wchar.o -x c wchar.c 
Segmentation fault (core dumped)

**Comment by jvillard** [comment]
You might have to compile clang from source, see [here](https://github.com/facebook/infer/blob/master/INSTALL.md) for more details. I haven't been able to reproduce the crash on a centos7 locally, but it may be that our binaries are not portable enough for your particular configuration.

I'm curious: what's the result of `ldd /home/sgu1/Downloads/infer-linux64-v0.5.0/facebook-clang-plugins/clang/bin/clang` for you? Does the segfault still happen with the latest release? Feel free to re-open the issue if you have more details.
