### ISSUE TITLE
configure: error: cannot run C compiled programs.

### ISSUE THREAD

**Issue by tingxuan** [facebook/infer#224]
I have installed all the dependencies ，when I executed the "./build-infer.sh"，it infos the error：
checking whether we are cross compiling... configure: error: in `/Users/tingxuanqhm/libtool/infer':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

**Comment by tingxuan** [comment]
I have resolved the problem.Close the issue.

**Comment by itouch2** [comment]
@qiuhm  How to resolve this?

**Comment by itouch2** [comment]
It seemed I missed ```xcode-select --install```
