### ISSUE TITLE
infer command not found

### ISSUE THREAD

**Issue by kushalsethi** [facebook/infer#225]
I have installed all the dependencies required for the fb infer on Ubuntu 14.04 LTS. Also I have cloned the latest infer from Git. After compilation and installation of the infer, I am getting error each time saying infer command not found, whenever I am trying to run infer for infer/examples/android-hello project.

I am running command after moving to infer/examples/android-hello project: 
infer -- ./gradlew build as said in the document of the infer.

And I am getting error saying "infer command not found".

Also when I am trying to get infer version by running "infer --version", still I am getting the same message "infer command not found".

Can someone help me to resolve this?
This image consist of the error message which I am getting when compilation and installation of the infer.

![infer-error](https://cloud.githubusercontent.com/assets/11423727/12014504/f365701c-ad53-11e5-9ed6-81745e73a4d7.png)

**Comment by jeremydubreil** [comment]
Hi @kushalsethi. Did you follow the install instructions in [install-infer-from-source](https://github.com/facebook/infer/blob/master/INSTALL.md#install-infer-from-source) ?

**Comment by kushalsethi** [comment]
Thank you! I followed them and got infer running. :)

Can you please tell me if I have one module dependency for my android project and my project's folder structure looks like- 
main-project/main-app
main-project/module-dependecny

Where should I run infer command? Do I have to run separately for each folder or only main-app will work?

Thank you!

**Comment by martinoluca** [comment]
Hello @kushalsethi,
You should run infer through the build-system used to build your app. The code that will be analyzed will be the one where the build-system invokes the compiler.
If the command to build your app is, for example
```
./gradlew build
```
then the command to run the analysis is
```
infer -- ./gradlew build
```

Thanks.

**Comment by kushalsethi** [comment]
Thank you! It worked.
