### ISSUE TITLE
BAD_POINTER_COMPARISON   Implicitly checking whether NSNumber pointer value is nil at line.

### ISSUE THREAD

**Issue by RameshAran** [facebook/infer#227]
(BOOL)setValue:(NSNumber *)value forUnit:(NSString *)unit
{
    if(value)
    {
          //some code here
    }
}

I am getting the above error in my code. What is the expectation here, Can some one give an example. I am getting lot errors like this. Please suggest.

**Comment by jberdine** [comment]
A common mistake is to write `if(value)` when intending to test whether `value` is a non-zero integer, while the code actually tests whether `value` is `nil`.  If you instead write `if(value != nil)` explicitly, then the warning should not be reported.

**Comment by RameshAran** [comment]
Thank you @jberdine

**Comment by jeremydubreil** [comment]
Some documentation: http://fbinfer.com/docs/infer-bug-types.html#BAD_POINTER_COMPARISON
