### ISSUE TITLE
Error building clang 

### ISSUE THREAD

**Issue by nickbit** [facebook/infer#229]
I get the following error when trying to build infer.
This is also happening after a ```make clean``` call

```
+ /usr/local/bin/ocamlc.opt -c -annot -bin-annot -warn-error @5@8@10..12@20@26@39 -I /Users/nikosbitoulas/.opam/system/lib/easy-format -I /Users/nikosbitoulas/.opam/system/lib/biniou -I /Users/nikosbitoulas/.opam/system/lib/yojson -I /Users/nikosbitoulas/.opam/system/lib/atdgen -I /Users/nikosbitoulas/.opam/system/lib/extlib -I /Users/nikosbitoulas/.opam/system/lib/camlzip/../zip -safe-string -I backend -I opensource -I harness -I checkers -o backend/specs.cmi backend/specs.mli
File "backend/specs.mli", line 124, characters 16-32:
Error: Unbound module TypeState
Command exited with code 2.
make[2]: *** [build_clang] Error 10
make[1]: *** [clang] Error 2
make: *** [clang] Error 2
compilation failure; try running "make clean"
```

**Comment by jberdine** [comment]
Thanks, this should be [fixed](https://github.com/facebook/infer/commit/51f494f542037c34aa04e9b1097eb4ec59e5304f).  You'll need to regenerate the Makefile, which executing `build-infer.sh` should take care of.

**Comment by nickbit** [comment]
This doesn't seem to fix it. Got the same error.
OS X El Capitan  10.11.2

**Comment by jberdine** [comment]
Are you sure that the `Makefile`s have been regenerated since you pulled the latest commit?  The absence of `-I eradicate` in the failing command is what happened on the preceding commit.

**Comment by nickbit** [comment]
I see that the change was done on Jan, 3 while I downloaded the latest one on Jan 2. Will retry with the new repo and report.

**Comment by nickbit** [comment]
It works OK. Please close. Thank you!
