### ISSUE TITLE
v0.5.0 configure: error: cannot run C compiled programs.

### ISSUE THREAD

**Issue by cegonya** [facebook/infer#231]
I am not able to use **/build-infer.sh** because it throws this error:

```
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```
In `config.log` I found this:

```
configure:2750: checking whether the C compiler works
configure:2772: <directory>/infer-osx-v0.5.0/facebook-clang-plugins/clang/bin/clang    conftest.c  >&5
configure:2776: $? = 0
configure:2824: result: yes
configure:2827: checking for C compiler default output file name
configure:2829: result: a.out
configure:2835: checking for suffix of executables
configure:2842: <directory>/infer-osx-v0.5.0/facebook-clang-plugins/clang/bin/clang -o conftest    conftest.c  >&5
configure:2846: $? = 0
configure:2868: result: 
configure:2890: checking whether we are cross compiling
configure:2898: <directory>/infer-osx-v0.5.0/facebook-clang-plugins/clang/bin/clang -o conftest    conftest.c  >&5
conftest.c:9:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.
configure:2902: $? = 1
configure:2909: ./conftest
./configure: line 2911: ./conftest: No such file or directory
configure:2913: $? = 127
configure:2920: error: in `<directory>/infer-osx-v0.5.0':
configure:2922: error: cannot run C compiled programs.
```

Can anyone help me with this issue?

**Comment by jvillard** [comment]
Can you try `xcode-select --install`?

**Comment by cegonya** [comment]
I installed `xcode-select` and now i have this new error:

```
checking for OCaml findlib package atdgen version 1.6.0... not found
configure: error: missing dependency: atdgen.

If you are using opam, please run

  opam update
  opam pin add --yes --no-action .
  opam install --deps-only infer
```

I have **opam 1.2.2** installed

**Comment by cegonya** [comment]
When i try to run
```
opam install --deps-only infer
```
I got this error : `[ERROR] No package named infer found.`

I installed `atdgen`, and now there is another missing dependency: `camlzip`

**Comment by cegonya** [comment]
After installing all these dependencies:
```
sawja
javalib
extlib
camlzip
atdgen
```
Infer works fine.

Now my question is: did I do something wrong in the installing process? because I had to install all of them manually before running **build-infer.sh**

**Comment by jvillard** [comment]
@cegonya thanks for your report. This is indeed the intended workflow: `./build-infer.sh` tells you how to install the opam dependencies. `opam pin add --yes --no-action .` should have created the "infer" package that opam is complaining about in your message about `opam install --deps-only infer`.

See #222 for a discussion about how to improve the docs around this.

**Comment by cegonya** [comment]
@jvillard thank you for this information. Definitely, you need to update that documentation for required Opam modules.

**Comment by i-tanova** [comment]
Hi, I've just changed command to
opam install --deps-only infer-linux-v0

**Comment by jnewc** [comment]
After some guesswork, the following worked for me on OSX:

`opam install --deps-only infer-osx-v0

This installed the following dependencies:

```
  ∗  install ocamlbuild  0       
  ∗  install ocamlfind   1.5.6   
  ∗  install camlp4      4.02+6  
  ∗  install menhir      20151112
  ∗  install easy-format 1.2.0   
  ∗  install cppo        1.3.1   
  ∗  install camlzip     1.05    
  ∗  install extlib      1.5.4   
  ∗  install biniou      1.0.9   
  ∗  install atd         1.1.2   
  ∗  install javalib     2.3.1   
  ∗  install yojson      1.3.0   
  ∗  install sawja       1.5.1   
  ∗  install atdgen      1.7.2   
```

**Comment by sanjayahuja** [comment]
Yes need to install all required dependencies: opam install "depedency name"
