### ISSUE TITLE
unknown type  name error 

### ISSUE THREAD

**Issue by bkangtf** [facebook/infer#235]
Hi ladies and guys,

How are u ??  ^  ^ 

I just post error issue here because it seems like there is no where else to post this issue about. 

I just started to use infer from yesterday, and I made cool environment for launching Infer.

and When I launch infer, too many unknown type  name errors.. like below..

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/usr/include/sys/types.h:95:9: error: unknown type
      name 'u_int64_t'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/usr/include/sys/_types.h:56:9: error: unknown type
      name '__int32_t'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/usr/include/machine/_types.h:34:2: error: 
      architecture not supported

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/usr/include/sys/cdefs.h:707:2: error: Unsupported
      architecture

and so on...
...
..

my app is only run on iPad series , and target SDK is over iOS 6.0. and base sdk is iOS9.

Valid Architectures :  arm7, arm7s, arm64 
Build Active Architectures Only  : NO

I commanded like this : infer -- xcodebuild -target myTarget -configuration Debug -sdk iphonesimulator

.
.
any idea why  those so many errors occur ??

Thanks in advance !

**Comment by jvillard** [comment]
Hi @bkangtf,

Does `xcodebuild -target myTarget -configuration Debug -sdk iphonesimulator` succeed on its own?

Can you paste the contents of `infer-out/toplevel.log`? Please use something like https://gist.github.com/ or pastebin et al. for text pastes as it will preserve formatting.

**Comment by bkangtf** [comment]
HI  jvillard

I post the file using https://gist.github.com/ .. how to share it with other people ??

it is as below .. though..

+[INFO] Running command /usr/local/infer-osx-v0.5.0/infer/bin/infer -- xcodebuild -target TwitNew -scheme TwitNew -configuration DEBUG -sdk iphonesimulator
+[INFO] Path to infer script /usr/local/infer-osx-v0.5.0/infer/bin/infer (/usr/local/infer-osx-v0.5.0/infer/lib/python/infer)
+[INFO] Infer version v0.5.0
+Copyright 2009 - present Facebook. All Rights Reserved.
+
+
+[INFO] Platform: Darwin-15.2.0-x86_64-i386-64bit
+[INFO] PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/infer-osx-v0.5.0/infer/bin
+[INFO] SHELL=/bin/bash
+[INFO] PWD=None
+[INFO] Xcode version:
+Xcode 7.2
+Build version 7C68
+
+[INFO] clang version:
+Apple LLVM version 7.0.2 (clang-700.1.81)
+Target: x86_64-apple-darwin15.2.0
+Thread model: posix
+
+[ERROR] Error during capture phase, exiting

and

 xcodebuild -target myTarget -configuration Debug -sdk iphonesimulator 

results as same...

**Comment by jvillard** [comment]
@bkangtf re: gist.github: just share the url once you've pasted it.

If I understand correctly, you get the same error running `xcodebuild -target myTarget -configuration Debug -sdk iphonesimulator`. This means that this is not the right command to build your project. You first need to figure out how to compile your project from the command line. Then use `infer -- <your command here>` to run infer.

**Comment by martinoluca** [comment]
Hello @bkangtf,
if the original command you provided fails:
```
xcodebuild -target myTarget -configuration Debug -sdk iphonesimulator
```

Then it may be that the `iphonesimulator` SDK doesn't support the required architecture.
Try running
```
xcodebuild -target myTarget -configuration Debug
```
and see if works, then try running infer with it.

Thanks.

**Comment by bkangtf** [comment]
Thank you jvillard & martinoluca , I will try again , Thanks ^ ^

**Comment by Coeur** [comment]
It's an Xcode 7.2 bug: http://www.openradar.me/23857648
Workaround is to "*provide the -destination param to xcodebuild*" (example given in the link above).

**Comment by jvillard** [comment]
Thanks @Coeur.

@bkangtf: let us know if this didn't work for you.
