### ISSUE TITLE
xxxx/Applications/infer-os/facebook-clang-plugins/clang/bin/../include/c++/v1/math.h:309:10: fatal error:

### ISSUE THREAD

**Issue by yschenfz** [facebook/infer#236]
i have met a probrem,could you tell me how to fix it ?

While building module 'Darwin' imported from protoBuff/google/protobuf/stubs/stringprintf.h:43:
In file included from <module-includes>:86:
In file included from /Users/chen-pc/Applications/infer-os/facebook-clang-plugins/clang/bin/../lib/clang/3.8.0/include/tgmath.h:29:
/Users/chen-pc/Applications/infer-os/facebook-clang-plugins/clang/bin/../include/c++/v1/math.h:309:10: fatal error:
      timed out waiting to acquire lock file for module 'std'
#include <type_traits>
         ^

** BUILD FAILED **

The following build commands failed:
	CompileC build/protoBuff.build/Debug-iphoneos/protoBuff.build/Objects-normal/armv7/zero_copy_stream_impl_lite.o protoBuff/google/protobuf/io/zero_copy_stream_impl_lite.cc normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
None

**Comment by yschenfz** [comment]
Add a  look,  i use the command "xcodebuild -target myTarget -configuration Debug -sdk iphoneos9.2" successfully,but use  "infer -- incremental --xcodebuild -target myTarget -configuration Debug -sdk iphoneos9.2".

**Comment by martinoluca** [comment]
Hello @yschenfz can you please try to add
```
CLANG_ENABLE_MODULES=NO
```
to the xcodebuild command, so that you get something like:
```
infer --incremental -- xcodebuild -target myTarget -configuration Debug -sdk iphoneos9.2" CLANG_ENABLE_MODULES=NO
```

Let me know if that helps! Thanks!

**Comment by yschenfz** [comment]
Hello  @martinoluca , success thank you !  Could you tell me why i should add CLANG_ENABLE_MODULES=NO?

**Comment by martinoluca** [comment]
Seems like the issue is a known problem in clang, see https://github.com/facebook/infer/issues/232#issuecomment-169744110 that solves a similar issue.

Thanks!
