### ISSUE TITLE
Analysis CPU is high 90%  four process

### ISSUE THREAD

**Issue by ronniesun** [facebook/infer#237]
android      infer -- gradle assembleRelease
Analysis is used when CPU is high, blocking analysis,
IOS no problem

who can help me? thank you

**Comment by ronniesun** [comment]
infer-0.5.0

**Comment by ronniesun** [comment]
Analyzing 1023 clusters..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................


block block block block block block block block

**Comment by jvillard** [comment]
Infer is indeed CPU-intensive and uses several cores. Does it stop printing dots? It can sometimes be several minutes between each dot.

**Comment by ronniesun** [comment]
stop printing dots

**Comment by ronniesun** [comment]
postscript : Pre-compiled versions for mac

**Comment by sblackshear** [comment]
We recently fixed an infinite loop bug that may be causing your issue (https://github.com/facebook/infer/commit/43ee904a1f1098d0ab3ddbeb8a8e84102d00f1c1). Would you mind compiling the latest Infer code from scratch and re-running to see if you still experience the issue?

**Comment by ronniesun** [comment]
Recently, I try again, look forward to your next Pre-compiled versions for mac。
Thank you very much!!!

**Comment by sblackshear** [comment]
Sorry to be dense--did you still see the issue when you re-ran with the code from master?

**Comment by ronniesun** [comment]
The macbook is not around, give you the answer tomorrow or the day after tomorrow。

**Comment by ronniesun** [comment]
I re-ran with the code from master, android can be passed, no stuck, the problem is fixed. I hope you get better and better. Thank you very much!   @jvillard @sblackshear

**Comment by sblackshear** [comment]
Great! Thank you for reporting back.
