### ISSUE TITLE
DIRECT_ATOMIC_PROPERTY_ACCESS issue

### ISSUE THREAD

**Issue by bkangtf** [facebook/infer#239]
Hi  ^ ^ 

I checked my code with infer, and infer found 264 issues...

and most of them are DIRECT_ATOMIC_PROPERTY_ACCESS ..

my codes do not use ARC (Automatic Reference Counting) because
it is old code... 

for example, the error is as below..

TwitPad/FBNetworkReachability.m:239: warning: DIRECT_ATOMIC_PROPERTY_ACCESS
  Direct access to ivar connectionMode_ of an atomic property at line 239, column 9. Accessing an ivar of an atomic property makes the property nonatomic
  237.   - (FBNetworkReachabilityConnectionMode)connectionMode
  238.   {
  239. >     if (connectionMode_ == FBNetworkReachableUninitialization) {
  240.           [self refresh];
  241.       }

and FBNetworkReachableUninitialization is declared as below.

typedef enum {
	FBNetworkReachableUninitialization = 0,
	FBNetworkReachableNon,
	FBNetworkReachableWiFi,
	FBNetworkReachableWWAN
} FBNetworkReachabilityConnectionMode;

..

What is a reason of DIRECT_ATOMIC_PROPERTY_ACCESS,
and how to fix this more than 200 issues ?

Thx in advance 

ps. if someone also know how to fix issue below, plz tell me ^ ^
This is not 'warning' but 'error', so I want to fix ti ~!

TwitPad/RootViewController.m:656: error: RETAIN_CYCLE
  Retain cycle involving the following objects:  (1) object &cell retaining &cell._statusLabel,   at line 656, column 10
  654.       TimeLineCell *cell = (TimeLineCell *)controller.view;
  655.       [controller release];
  656. >     cell.statusLabel.text = [textArray objectAtIndex:indexPath.row];
  657.       
  658.       [cell.statusLabel sizeToFit];

**Comment by ddino** [comment]
DIRECT_ATOMIC_PROPERTY_ACCESS happens when you are accessing an atomic property directly with an ivar. This makes the atomic property not atomic anymore. So potentially you may get a race condition.

To fix the problem you need to access properties with their getters.

**Comment by bkangtf** [comment]
oh Thanks ddino.. so I have to make a property, and sync ivar with property, and access to the property, (not access directly to ivar) right ?

**Comment by ddino** [comment]
yes, access the property only with the getter.

**Comment by bkangtf** [comment]
I see! Thank you so much.

**Comment by dulmarod** [comment]
I'm closing this issue. About the retain cycle, to help you we need to see more of the code. If you want to give us more info, you could create a new issue for that.

**Comment by bkangtf** [comment]
Oh... thank you dulmarod : )

I kept open this, because other people could check this issue when they have a same issue.

Is there any way to see closed issues again ??

**Comment by dulmarod** [comment]
I've written documentation about this new check in the website, so hopefully that will be useful for people that don't understand what the check does. (http://fbinfer.com/docs/infer-bug-types.html#DIRECT_ATOMIC_PROPERTY_ACCESS)
About seeing closed issues, yes, when you go to the issues page, it takes you to the open issues, and there is a tab closed issues in the top where you can find them.

**Comment by dengwei729** [comment]
@dulmarod can not find DIRECT_ATOMIC_PROPERTY_ACCESS info in the page (http://fbinfer.com/docs/infer-bug-types.html#DIRECT_ATOMIC_PROPERTY_ACCESS)


```
@implementation CCAlertView
@synthesize alert, blocks, dismissAction, keepInMemory;

- (void)alertView: (UIAlertView*) alertView didDismissWithButtonIndex: (NSInteger) buttonIndex
{
    if (!OS_VERSION_8_LATER){
        if (buttonIndex >= 0 && buttonIndex < [blocks count]) {
            dispatch_block_t block = [blocks objectAtIndex:buttonIndex];
            block();
        }
        if (dismissAction != NULL) {
            dismissAction();
        }

        [[NSNotificationCenter defaultCenter] removeObserver:self];
        [self setKeepInMemory:nil];
    }
}
```

I want to know why
