### ISSUE TITLE
C++ support

### ISSUE THREAD

**Issue by KevinArturia** [facebook/infer#24]
Is there any plan to ass C++ support?

Thanks in advance,
Kevin

**Comment by irpap** [comment]
Hi Kevin,
We've already started work on translating C++. There's a lot of work to be done as C++ is big, so it's going to take some time until it yields good results, but it's one of our plans for the future.

**Comment by KevinArturia** [comment]
Good news. I'll follow it and wait for it :)

**Comment by czras** [comment]
Is there any cooperation with the https://github.com/facebook/flint development in this regard?

**Comment by irpap** [comment]
No, they are two separate tools.

**Comment by jvillard** [comment]
Infer has C++ support since 0.10.0.
