### ISSUE TITLE
Where can I find a clear list of dependencies?

### ISSUE THREAD

**Issue by MatthewBennington** [facebook/infer#242]
I'm trying to build Infer from source on RHEL. I find the INSTALL.md unhelpful.

There are three lists of dependencies which might be helpful to me: one labeled "Infer dependencies for Linux", one labeled "Debian 7 and Ubuntu 14.04 LTS", and one labeled "Ubuntu 12.04.4 LTS". Each of these lists contains a different list of packages.

Can anyone give me a exhaustive list of packages I need for Infer to run?

**Comment by jeremydubreil** [comment]
Hi @MatthewBennington. The best way is probably to follow the [list of dependencies for Linux](https://github.com/facebook/infer/blob/master/INSTALL.md#infer-dependencies-for-linux) and to find the corresponding packages in RHEL.

**Comment by jvillard** [comment]
There are generic dependencies listed at the top of the "Infer dependencies for Linux" section: https://github.com/facebook/infer/blob/master/INSTALL.md#infer-dependencies-for-linux

Then `./build-infer.sh` should let you know if you are missing any dependencies. Let me know if that's not the case.
