### ISSUE TITLE
cannot run C compiled programs.

### ISSUE THREAD

**Issue by VVJason** [facebook/infer#244]
when run build-infer.sh , What am I supposed to do

checking if we are in an Infer release build... yes
checking whether to use the compilers in /Users/weibing/Documents/Projects/Work/infer-osx-v0.6.0/facebook-clang-plugins/clang/bin... yes
checking for shasum... shasum
checking for python2.7... python2.7
checking for xcode-select... xcode-select
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/Users/weibing/Documents/Projects/Work/infer-osx-v0.6.0':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

**Comment by jvillard** [comment]
you may want to install the command line tools: `xcode-select install`.

**Comment by VVJason** [comment]
@jvillard  thank you .  but run build-infer.sh ,  
```
initializing opam...
[ERROR] multiple lines for package path
[ERROR]
OPAM has already been initialized.[ERROR] multiple lines for package path
[ERROR]

```

**Comment by VVJason** [comment]
when   run  " infer -- clang -c Hello.m "  
```
Failed to run InferAnalyze binary, exiting
```

**Comment by VVJason** [comment]
thank you
