### ISSUE TITLE
False positive RESOURCE_LEAK for Cursor's put in CursorAdapter's

### ISSUE THREAD

**Issue by markusfisch** [facebook/infer#245]
A Cursor object given to a CursorAdapter cannot be closed immediately because the CursorAdapter will use this Cursor object later on.

The open Cursor can only be closed after the CursorAdapter has created its views.

One way to close the open Cursor is to call [changeCursor(null)](http://developer.android.com/reference/android/widget/CursorAdapter.html#changeCursor(android.database.Cursor)) what will make the adapter close the last Cursor.

For example, the following test case:

```java
public class MainActivity extends Activity {
	protected TestCursorAdapter testCursorAdapter;

	@Override
	protected void onCreate(Bundle state) {
		super.onCreate(state);
		setContentView(R.layout.activity_main);

		testCursorAdapter = new TestCursorAdapter(
			this,
			querySomething());
	}

	@Override
	protected void onDestroy() {
		super.onDestroy();

		// close cursor
		testCursorAdapter.changeCursor(null);
	}

	private Cursor querySomething() {
		return new MockCursor();
	}

	private class TestCursorAdapter extends CursorAdapter {
		public TestCursorAdapter(Context context, Cursor cursor) {
			super(context, cursor);
		}

		@Override
		public void bindView(
			View view,
			Context context,
			Cursor cursor) {
		}

		@Override
		public View newView(
			Context context,
			Cursor cursor,
			ViewGroup parent) {
			return null;
		}
	}
}
```

Results in:

```
Starting analysis (Infer version v0.6.0-ad2a906)
Computing dependencies... 100%
Analyzing 4 clusters....%
Analyzed 37 procedures in 4 files

Found 1 issue
app/src/main/java/de/markusfisch/android/inferprobecursoradapter/activity/MainActivity.java:24: error: RESOURCE_LEAK
   resource of type android.test.mock.MockCursor acquired by call to querySomething() at line 24 is not released after line 24
  22.   		testCursorAdapter = new TestCursorAdapter(
  23.   			this,
  24. > 			querySomething());
  25.   	}
  26.   
```

**Comment by sblackshear** [comment]
The problem here is that Infer doesn't handle the Android lifecycle, so it doesn't know that `onDestroy` will always be called after `onCreate` and close the `Cursor`. 

However, even if it did understand the lifecycle, it would still complain about this example. The reason is that if an uncaught exception is thrown in `super.onDestroy()`, `testCursorAdapter.changeCursor(null)` will never be called and the `Cursor` will remain open.

**Comment by markusfisch** [comment]
Good point! You're right. `testCursorAdapter.changeCursor(null)` should be called before `super.onDestroy()`. Thanks for the note. I'll change this in the original project I took this sample from.

**Comment by jvillard** [comment]
Looks like the report was legit after all. Feel free to open a more general issue about infer not knowing about the android lifecycle.
