### ISSUE TITLE
Add support for disabling certain checks.

### ISSUE THREAD

**Issue by tonycosentini** [facebook/infer#247]
It would be nice to be able to disable certain checks.

For example, we have a lot of `RETURN_VALUE_IGNORED` warnings, but we don't plan on addressing them (is there a reason ignored return values are considered bad?).

Since we block diffs via using Infer's `--fail-on-bug` + checking the return value of the command, it would be nice to be able to disable some checks.

**Comment by tonycosentini** [comment]
I'm going to look into how hard this is to do, but I'm also curious if any Infer maintainers can comment on whether or not it makes sense to add this.

**Comment by jeremydubreil** [comment]
Hi @tonycosentini. There is no easy support for that right now. The filtering is implemented in this file: https://github.com/facebook/infer/blob/master/infer/lib/python/inferlib/issues.py#L259

However, the `RETURN_VALUE_IGNORED` should be displayed by default. I am not sure we actually ever looked at how this check for return values behaves in Java. Are you using Infer with the `--no-filtering` option ?

**Comment by tonycosentini** [comment]
Re getting `RETURN_VALUE_IGNORED`, that was a user error on my part.

Will reopen if I run into this again, sorry for the noise.
