### ISSUE TITLE
Infer thinks Android's implementation of Collections.synchronizedList can cause ERADICATE_FIELD_NOT_INITIALIZED.

### ISSUE THREAD

**Issue by tonycosentini** [facebook/infer#253]
I'm getting ERADICATE_FIELD_NOT_INITIALIZED warnings for this code when in an Android project:

``` java
import java.util.Collections;
import java.util.LinkedList;
import java.util.List;

public class MyClass {

    private final List<String> list;

    public MyClass() {
        list = Collections.synchronizedList(new LinkedList<String>()); 
    }
}
```

However, I don't get this warning for the same exact code in Java projects.

I think it's because Android has a different implication of synchronizedList.

Here's the Android implementation:

``` java
public static <T> List<T> synchronizedList(List<T> list) {
    if (list == null) {
        throw new NullPointerException("list == null");
    }
    if (list instanceof RandomAccess) {
        return new SynchronizedRandomAccessList<T>(list);
    }
    return new SynchronizedList<T>(list);
}
```

and here's an implementation from OpenJDK:

``` java
public static <T> List<T> synchronizedList(List<T> list) {
    return (list instanceof RandomAccess ?
            new SynchronizedRandomAccessList<T>(list) :
            new SynchronizedList<T>(list));
}
```

As far as I can tell, both cannot return null (although the Android one will NPE internally if you pass it null).

Apologies if I'm doing something wrong, let me know if there are more details that would help here.

Thanks!

**Update 2/1/16:** It seems like `Collections.emptyList()` also results in the same error.

**Comment by cristianoc** [comment]
Even doing directly ```list = null;``` would result in a ERADICATE_FIELD_NOT_NULLABLE, but not a ERADICATE_FIELD_NOT_INITIALIZED: it's initialized but with the wrong value.

Which error are you getting?

**Comment by tonycosentini** [comment]
I'm getting `ERADICATE_FIELD_NOT_INITIALIZED`, sorry for the confusion.

**Comment by jvillard** [comment]
I tried to reproduce but eradicate doesn't report anything on the code in the issue. I ran with

```
infer -g --eradicate-only -- javac -cp ~/infer/infer/lib/java/android/android-23.jar issue253.java
```
