### ISSUE TITLE
Is false positive of NULL_DEREFERENCE

### ISSUE THREAD

**Issue by savaskoc** [facebook/infer#254]
Hi,

I have some code wrapped by try-catch block, and infer reports this part as a issue

<img width="883" alt="screen shot 2016-01-29 at 23 12 19" src="https://cloud.githubusercontent.com/assets/3313518/12688270/d0386a10-c6dd-11e5-9ad9-90a9c0657a11.png">

Is that a false positive?

**Comment by sblackshear** [comment]
Infer is correct that flow may be `null` and could be dereferenced. But you are correct that the `NullPointerException` thrown by this dereference will be caught by your catch-all block :). Infer chooses to report NPE's regardless of whether or not they will be caught.
