### ISSUE TITLE
Offer Gradle plugin

### ISSUE THREAD

**Issue by mcandre** [facebook/infer#256]
Please integrate with popular build tools like Gradle, so that infer can be applied to projects with hundreds of interconnected source files, not just HelloWorld's.

**Comment by sblackshear** [comment]
Infer does support Gradle, as well as several other popular build tools (see the [documentation](http://fbinfer.com/docs/analyzing-apps-or-projects.html) for a complete list of supported build tools) .

Please try `infer -- grade build <your_project>` and let us know if you encounter any problems.

**Comment by mcandre** [comment]
That's not quite what I mean. From a CI server's perspective, it would be more convenient to be able to invoke a Gradle command to run Infer, rather than have to explicitly shell out to infer to run Gradle.

**Comment by sblackshear** [comment]
This would indeed be nice to have. We do not currently have this for any build system. 

For now, replacing all gradle commands with `infer -- <gradle command>` should be a usable workaround. But if someone with a good understanding of Gradle created a plugin, that would be great.

**Comment by clonetwin26** [comment]
https://github.com/uber-common/infer-plugin

**Comment by mcandre** [comment]
+100
