### ISSUE TITLE
"0 files" when actually 1+ files

### ISSUE THREAD

**Issue by mcandre** [facebook/infer#259]
When I run `infer -- gradle clean build` against my FizzBuzz project, infer fails to find my Java files.

https://github.com/mcandre/mcandre/tree/master/java/fizzy

**Comment by sblackshear** [comment]
The problem is that this is a Java 8 project. The frontend we use cannot currently parse Java 8, so Infer ignores any files with Java 8 bytecode instructions. We have reported this issue upstream, and are exploring temporary workarounds.

**Comment by jvillard** [comment]
I've opened a separate issue to properly analyse Java 8 in Infer (#314).
