### ISSUE TITLE
"Nothing to compile. Try running `gradle clean` first."

### ISSUE THREAD

**Issue by mcandre** [facebook/infer#260]
When I run `infer -- gradle clean build` against either the bomb-applet or bomb-threads projects in my java forkbombs collection, infer doesn't find any of my Java files.

https://github.com/mcandre/forkbombs/tree/master/java

**Comment by jvillard** [comment]
I've looked at your project and `gradle build` creates an empty jar:

```
$ unzip build/libs/bomb-applet.jar
Archive:  ../build/libs/bomb-applet.jar
   creating: META-INF/
  inflating: META-INF/MANIFEST.MF
```

Looking at the output of `gradle --debug build` confirms that there's nothing to compile when doing `gradle build`. If there is a build target that builds your project you can try that one instead.
