### ISSUE TITLE
Ignore shebang in .java files

### ISSUE THREAD

**Issue by mcandre** [facebook/infer#263]
BeanShell Java source allows shebangs (e.g. `#!/usr/bin/env bsh`) at the beginning of Java source files. Infer currently borks on these.

Could we have Infer automatically strip these out of the beginning of Java files, so that Infer works with BeanShell Java code?

**Comment by sblackshear** [comment]
Whatever build system is compiling these source files must have some way of stripping these out, right (otherwise javac wouldn't work)? Is there some way we can piggyback on this existing mechanism?

**Comment by mcandre** [comment]
Most people don't generate API documentation for command line scripts, such as BeanShell scripts.

I've since dropped support for BeanShell among my own projects, so I'm satisfied to close this for now.
