### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by mcandre** [facebook/infer#265]
Please support Python v3+, so that I can use Infer in projects that require Python 3 and higher.

**Comment by jvillard** [comment]
Hi @mcandre, can you tell us a bit more about what breaks if your project uses Python 3?

**Comment by mcandre** [comment]
My projects often use Python 3, so having the python(2.7) binary in PATH tends to break my projects.

**Comment by jvillard** [comment]
The scripts use `python2.7` [explicitly](https://github.com/facebook/infer/blob/master/infer/lib/python/infer#L1), so you should be able to keep `python` pointing to Python 3 at the same time without conflicts. Is there any issue with that?

**Comment by mcandre** [comment]
I use tools like pyenv to switch Python versions per project, so I don't always have python2.7 on path.

**Comment by jvillard** [comment]
There is no plan to support Python3. Python2.7 is marked as a dependency already so I'm closing this task.

@mcandre you need python2.7 in your `PATH` to run infer.

**Comment by mcandre** [comment]
Python 2 is deprecated. Linuxen are switching to Python 3.

**Comment by jvillard** [comment]
Python2.7 is not deprecated yet, its end of life is [planned for 2020](http://legacy.python.org/dev/peps/pep-0373/). We plan to have moved away from Python2.7 by then :smiley:
