### ISSUE TITLE
build-infer.sh: line 108: set: -g: invalid option

### ISSUE THREAD

**Issue by Skyfold** [facebook/infer#267]
I am installing Infer from source following the install guide for MacOSX.

When I run `./build-infer.sh clang` or `./build-infer.sh java` I get:

```
initializing opam...
./build-infer.sh: line 108: set: -g: invalid option
set: usage: set [--abefhkmnptuvxBCHP] [-o option] [arg ...]
```

However, on line 108 in build-infer.sh you have `eval $(opam config env)`. I ran `eval $(opam config env)` and the command runs without errors.

If I just comment out line 108, `build-infer.sh clang` runs without errors. It just requests you run these commands before it will compile clang.

```
  opam update
  opam pin add --yes --no-action infer .
  opam install --deps-only
```

Does anyone else have this error? Any idea why you would get that error?

Regardless this is not a major issue. Just posting this in case someone else gets the same error.

**Comment by jberdine** [comment]
Thanks for reporting.  Could you post the results of executing `opam --version` and `opam config env`?

**Comment by Skyfold** [comment]
Thanks for looking at this!

`opam --version` is 1.2.2
`opam config env`

```
set -gx CAML_LD_LIBRARY_PATH "/Users/[username]/.opam/system/lib/stublibs:/usr/local/lib/ocaml/stublibs";
set -gx OPAMUTF8MSGS "1";
set -gx MANPATH "/Users/[username]/.opam/system/man" "";
set -gx PERL5LIB "/Users/[username]/.opam/system/lib/perl5";
set -gx OCAML_TOPLEVEL_PATH "/Users/[username]/.opam/system/lib/toplevel";
set -gx PATH "/Users/[username]/.opam/system/bin" [rest of my path]
```

I should have mentioned I am using Fish. However, the problem persisted even after switching to Bash.

My guess is it has something to do with either my system or the build-infer.sh. Opam worked fine when called outside of the script.

**Comment by jberdine** [comment]
Perhaps we need to use `opam config env --shell=bash` instead of `opam config env` in build-infer.sh since it is a bash script.  I'm not sure if opam detects this correctly since you installed it for fish, but then build-infer.sh calls it from bash.  Perhaps you can add that option locally to test if it resolves things in your environment?

Thanks!
