### ISSUE TITLE
can't build infer 

### ISSUE THREAD

**Issue by yishuiliunian** [facebook/infer#268]
cp: /private/tmp/clang-setup.i9guIF/tools/clang/runtime/compiler-rt/clang_darwin/eprintf/libcompiler_rt.a: No such file or directory
make[5]: *** [/private/tmp/clang-setup.i9guIF/Release/lib/clang/3.8.0/lib/darwin/libclang_rt.eprintf.a] Error 1
make[5]: *** Waiting for unfinished jobs....
cp: /private/tmp/clang-setup.i9guIF/tools/clang/runtime/compiler-rt/clang_darwin/cc_kext/libcompiler_rt.a: No such file or directory
make[5]: *** [/private/tmp/clang-setup.i9guIF/Release/lib/clang/3.8.0/lib/darwin/libclang_rt.cc_kext.a] Error 1
cp: /private/tmp/clang-setup.i9guIF/tools/clang/runtime/compiler-rt/clang_darwin/osx/libcompiler_rt.a: No such file or directory
make[5]: *** [/private/tmp/clang-setup.i9guIF/Release/lib/clang/3.8.0/lib/darwin/libclang_rt.osx.a] Error 1
cp: /private/tmp/clang-setup.i9guIF/tools/clang/runtime/compiler-rt/clang_darwin/10.4/libcompiler_rt.a: No such file or directory
make[5]: *** [/private/tmp/clang-setup.i9guIF/Release/lib/clang/3.8.0/lib/darwin/libclang_rt.10.4.a] Error 1
rm /private/tmp/clang-setup.i9guIF/tools/clang/runtime/compiler-rt/clang_darwin/asan_iossim_dynamic/libcompiler_rt.dylib /private/tmp/clang-setup.i9guIF/Release/lib/clang/3.8.0/lib/darwin/.dir /private/tmp/clang-setup.i9guIF/Release/lib/clang/3.8.0/lib/macho_embedded/.dir /private/tmp/clang-setup.i9guIF/tools/clang/runtime/compiler-rt/clang_darwin/ubsan_iossim_dynamic/libcompiler_rt.dylib
make[4]: *** [compiler-rt/.makeall] Error 2
make[3]: *** [all] Error 1
make[2]: *** [clang/.makeall] Error 2
make[1]: *** [all] Error 1
cp: /Users/stonedong/OpenCode/infer/facebook-clang-plugins/clang/bin/clang: No such file or directory
make: *** [clang_setup] Error 1

  compilation failure; you can try running

    make clean
    ./build-infer.sh clang

**Comment by jvillard** [comment]
can you give the command you were trying to run as well as its full output?

**Comment by yishuiliunian** [comment]
i run the commond:
./build-infer.sh clang

**Comment by jvillard** [comment]
This is a problem in the compilation of clang, not of infer. If you can, use a release of `homebrew install infer` instead.

If not, can you share the full output of the compilation, as well as your configuration? (version of macos, architecture, ...)

**Comment by jvillard** [comment]
The way of compiling clang has changed, so hopefully this works now. Please reopen if there is still an issue.
