### ISSUE TITLE
Stuck after analyzing all files

### ISSUE THREAD

**Issue by mshukla19** [facebook/infer#27]
When i run infer with ./gradlew build and debug options , it analyses all my java files and then gets stuck. nothing happens after that. if i manually terminate using ctrl+c , then i see infer out directory is generated and captured folder has all the java files in it, but reports.json is missing.

**Comment by martinoluca** [comment]
Hello @mshukla19, could you please provide more context where possible, e.g. output of Infer, screenshots.
This will give us the possibility to further investigate the root cause of this issue.

Thanks!

**Comment by mshukla19** [comment]
yeah for sure, i am attaching screenshot of the initial command  and the point where terminal gets stuck. I am running this on an android project (built using android studio with lintoptions set to false).
![screen shot 2015-06-12 at 2 34 35 pm](https://cloud.githubusercontent.com/assets/7594206/8127230/c431ddcc-1112-11e5-9a18-ca9d38154b7c.png)
![screen shot 2015-06-12 at 2 47 16 pm](https://cloud.githubusercontent.com/assets/7594206/8127229/c42ea99a-1112-11e5-81b5-4bcbacf9ae8c.png)

i have also tried running infer without incremental option also but still the same result.

**Comment by martinoluca** [comment]
Thanks for posting the screenshots!
I see from your command line that you are running Infer using the `--debug` option.
`--debug` is telling Infer to emit extra internal information during the analysis and this will make it slower than usual.
If you're interested on the internals of Infer and you want to look at the translation information generated during the analysis, then there's nothing wrong with your analysis instance, you should just wait for the analysis to finish (it may take some time, depending on the size of your codebase).

In case you're just interested in what bugs Infer finds on your code, then you should just remove the `--debug` option and let the analysis run.

Make sure you `./gradlew clean` before running it again, to make sure Infer captures all the compilation commands.
