### ISSUE TITLE
Please update Infer release usage instructions

### ISSUE THREAD

**Issue by sitsofe** [facebook/infer#275]
A downloaded infer-linux64-v0.6.0.tar.xz tarball linked from https://github.com/facebook/infer/releases/tag/v0.6.0 passed SHA256 checks but when trying to use
`./build-infer.sh clang`
results in the following message:
```
initializing opam... 
preparing build... 

  Warning: you are not using a release of Infer. The C and
  Objective-C analyses require a custom clang to be compiled
  now. This step takes ~30-60 minutes, possibly more.

  To speed this along, you are encouraged to use a release of
  Infer instead:

  http://fbinfer.com/docs/getting-started.html

  If you are only interested in analyzing Java programs, simply
  run this script with only the "java" argument:

  ./build-infer.sh java

Are you sure you want to compile clang? (y/N) 
```

Poking around the problem was because the `shasum` utility was not present on Fedora 23. Installing `perl-Digest-SHA` solved the problem.

Next up the following message was printed during the build:
```
checking for OCaml findlib package atdgen version 1.6.0... not found
configure: error: missing dependency: ocamlfind.

If you are using opam, please run

  opam update
  opam pin add --yes --no-action .
  opam install --deps-only infer
```

Unfortunately running `opam install --deps-only infer` just resulted in the error message
```
[ERROR] No package named infer found.
```

Running `opam install --deps-only infer-linux64-v0` seemed to work though.

Could the instructions be updated to say there's a perl-Digest-SHA requirement (at least on Linux) and that opam dependencies might need a different name to the one displayed?

**Comment by jvillard** [comment]
Hi @sitsofe, thanks for reporting this.

We'll change the error message when `shasum` is not present, good catch!

The second problem you raise is fixed in master (the script now suggests `opam pin add --yes --no-action infer .`), but isn't included in a release yet.
