### ISSUE TITLE
Integrating infer with jenkins in ubuntu

### ISSUE THREAD

**Issue by kushalsethi** [facebook/infer#277]
Can someone please explain how to configure infer in Jenkins so as to analyze code each time the build generates.
Thank you!

**Comment by jvillard** [comment]
@kushalsethi you can look into [this post](https://medium.com/@Rapchik/static-analysis-build-server-for-android-with-jenkins-using-docker-bda888d4b34e#.257b2muh6) for example.

**Comment by kushalsethi** [comment]
Thanks. I will try this.

**Comment by LeeY0510** [comment]
Hi, @jvillard. You provide the URL(example) can not be opened.

**Comment by jvillard** [comment]
@LeeY0510 it still opens for me
