### ISSUE TITLE
infer fails to build on 10.11 - Cant find the include directory, since it isn't in /usr/include

### ISSUE THREAD

**Issue by Daij-Djan** [facebook/infer#278]
Hi,
infer fails to build on 10.11.

It Cant find the include directory, since it isn't in /usr/include

`cgndpich67723:infer-osx-v0.7.0 dpich$ ./build-infer.sh 
initializing opam... 
preparing build... 
checking if we are in an Infer release build... yes
checking whether to use the compilers in /Users/dpich/Downloads/infer-osx-v0.7.0/facebook-clang-plugins/clang/bin... yes
checking for shasum... shasum
checking for python2.7... python2.7
checking for xcode-select... xcode-select
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in '/Users/dpich/Downloads/infer-osx-v0.7.0':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use '--host'.
See 'config.log' for more details
cgndpich67723:infer-osx-v0.7.0 dpich$ `

**Comment by Daij-Djan** [comment]
xcode-select --install doesn't work for me :)

what works is xcrun to find the include path:
/usr/bin/xcrun --show-sdk-path --sdk macosx
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include

**Comment by jvillard** [comment]
How does it work once you'ver run `/usr/bin/xcrun --show-sdk-path --sdk macosx`? Simply by running `./configure` again?

**Comment by Daij-Djan** [comment]
that gives me the real include path. I don't know how to pass it to configure and to make. I'd somehow have to pass it. I haven't instigated as I can't pass it to buildInfer script already.

**Comment by Daij-Djan** [comment]
to cc id pass it as -I flag if I recall correctly. I did it in the past

**Comment by jvillard** [comment]
hey @Daij-Djan, sorry for the delay. A quick search on the web suggests upgrading XCode to 7.0 or later and running `xcode-select --install` again. Could you try that?

**Comment by Daij-Djan** [comment]
no thats not it and the posts are wrong ;) found that too

**Comment by jvillard** [comment]
can you try `./configure CFLAGS=-I$(/usr/bin/xcrun --show-sdk-path --sdk macosx) && make`?

**Comment by jvillard** [comment]
closing optimistically
