### ISSUE TITLE
i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler

### ISSUE THREAD

**Issue by d6638219** [facebook/infer#282]
I use the following command：

infer --incremental  -- xcodebuild ARCHS="i386 x86_64" ONLY_ACTIVE_ARCH=NO  -target Autohome  -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=9.0,name=iPhone 6' CLANG_ENABLE_MODULES=NO

error:

CompileC build/Autohome.build/Debug-iphonesimulator/Autohome.build/Objects-normal/i386/SBJsonStreamParserAdapter.o ThirdControl/SBJson/SBJsonStreamParserAdapter.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler

My app is arc,SBJsonStreamParserAdapter.m marked  "-fno-objc-arc"

**Comment by jvillard** [comment]
hi @d6638219, You only pasted the line used to compile SBJsonStreamParserAdapter.m; can you please provide the actual error message as well? You can paste the entire output [here](https://gist.github.com/).

**Comment by d6638219** [comment]
@jvillard，

/AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.m:72:2: error: 'array' is unavailable
        array = nil;
        ^
In file included from /AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.m:33:
/AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.h:122:25: note: declaration uses __weak, but ARC is disabled
        __weak NSMutableArray *array;
                               ^
/AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.m:73:2: error: 'dict' is unavailable
        dict = nil;
        ^
In file included from /AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.m:33:
/AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.h:123:30: note: declaration uses __weak, but ARC is disabled
        __weak NSMutableDictionary *dict;
                                    ^
/AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.m:79:3: error: 'array' is unavailable
                array = value;
                ^
In file included from /AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.m:33:
/AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.h:122:25: note: declaration uses __weak, but ARC is disabled
        __weak NSMutableArray *array;
                               ^
/AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.m:82:3: error: 'dict' is unavailable
                dict = value;
                ^
In file included from /AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.m:33:
/AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.h:123:30: note: declaration uses __weak, but ARC is disabled
        __weak NSMutableDictionary *dict;
                                    ^
/AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.m:92:5: error: 'array' is unavailable
                        [array addObject:obj];
                         ^
In file included from /AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.m:33:
/AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.h:122:25: note: declaration uses __weak, but ARC is disabled
        __weak NSMutableArray *array;
                               ^
/AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.m:97:5: error: 'dict' is unavailable
                        [dict setObject:obj forKey:[keyStack lastObject]];
                         ^
In file included from /AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.m:33:
/AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.h:123:30: note: declaration uses __weak, but ARC is disabled
        __weak NSMutableDictionary *dict;
                                    ^
/AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.m:119:3: error: 'dict' is unavailable
                dict = [[NSMutableDictionary new] autorelease];
                ^
In file included from /AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.m:33:
/AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.h:123:30: note: declaration uses __weak, but ARC is disabled
        __weak NSMutableDictionary *dict;
                                    ^
/AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.m:120:20: error: 'dict' is unavailable
                [stack addObject:dict];
                                 ^
In file included from /AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.m:33:
/AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.h:123:30: note: declaration uses __weak, but ARC is disabled
        __weak NSMutableDictionary *dict;
                                    ^
/AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.m:131:15: error: 'dict' is unavailable
                id value = [dict retain];
                            ^
In file included from /AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.m:33:
/AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.h:123:30: note: declaration uses __weak, but ARC is disabled
        __weak NSMutableDictionary *dict;
                                    ^
/AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.m:141:3: error: 'array' is unavailable
                array = [[NSMutableArray alloc] init];
                ^
In file included from /AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.m:33:
/AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.h:122:25: note: declaration uses __weak, but ARC is disabled
        __weak NSMutableArray *array;
                               ^
/AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.m:142:20: error: 'array' is unavailable
                [stack addObject:array];
                                 ^
In file included from /AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.m:33:
/AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.h:122:25: note: declaration uses __weak, but ARC is disabled
        __weak NSMutableArray *array;
                               ^
/AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.m:144:4: error: 'array' is unavailable
                [array release];
                 ^
In file included from /AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.m:33:
/AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.h:122:25: note: declaration uses __weak, but ARC is disabled
        __weak NSMutableArray *array;
                               ^
/AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.m:150:15: error: 'array' is unavailable
                id value = [array retain];
                            ^
In file included from /AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.m:33:
/AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.h:122:25: note: declaration uses __weak, but ARC is disabled
        __weak NSMutableArray *array;
                               ^
/AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.h:122:25: error: cannot create __weak reference in file using
      manual reference counting
        __weak NSMutableArray *array;
                               ^
/AutoHome/Plugin/Autohome_plugin5.3.2/ThirdControl/SBJson/SBJsonStreamParserAdapter.h:123:30: error: cannot create __weak reference in file using
      manual reference counting
        __weak NSMutableDictionary *dict;
                                    ^

**Comment by jvillard** [comment]
thanks, is there anything in the few lines just before what you pasted? It doesn't look like the first error is included in what you pasted.

**Comment by d6638219** [comment]
I do not see other error messages.thanks

**Comment by d6638219** [comment]
Why is there this error , what's the solution .thanks.

**Comment by martinoluca** [comment]
Hello @d6638219,
Have you tried replacing `ARCHS="i386 x86_64"` with `ARCHS="x86_64"` ?

Thanks

**Comment by d6638219** [comment]
@marcelerz  
I have tested, but reported the same mistakes。

**Comment by qiuhm** [comment]
I have met the similar mistake.
When I execute the shell "infer -- xcodebuild -workspace Source/AliCentrumDB.xcworkspace -scheme AliCentrumDB -configuration Debug -destination 'name=iPhone 6' ",it failed.
error is:
The following build commands failed:
	CompileC DerivedData/AliCentrumDB/Build/Intermediates/AliCentrumDB.build/Debug-iphonesimulator/AliCentrumDB.build/Objects-normal/i386/ACDSDBManager.o AliCentrumDB/DbRuntime/ACDSDBManager.mm normal i386 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
None

But When I execute the shell "xcodebuild -workspace Source/AliCentrumDB.xcworkspace -scheme AliCentrumDB -configuration Debug -destination 'name=iPhone 6' ",it suceeded.

It is confusing.How do resolve the problem?

**Comment by jvillard** [comment]
Is there still an issue in the latest version of infer?

**Comment by galaxycoder** [comment]
same question, excute "infer -- xcodebuild -workspace xx.xcworkspace -scheme xx -configuration Debug" failed, however, excute "xcodebuild -workspace xx.xcworkspace -scheme xx -configuration Debug" succeeded

how to resolve it?

**Comment by jvillard** [comment]
@galaxycoder to answer this question we need more information:
- what version of infer are you using?
- what is the full output of the infer command? (use https://gist.github.com/ or similar)

**Comment by galaxycoder** [comment]
@jvillard 

version 0.7, brew installed, then i install it from source, excute succeeded, but another issue occurred - #400

**Comment by jvillard** [comment]
Please reopen if the same issue still exists.
