### ISSUE TITLE
Does not work when /usr/bin/python is python3

### ISSUE THREAD

**Issue by phiresky** [facebook/infer#29]
On Arch Linux I get this error:

```
Traceback (most recent call last):
  File "infer/infer/infer/bin/infer", line 142, in <module>
    main()
  File "infer/infer/infer/bin/infer", line 100, in main
    mod_name = get_module_name(capture_module_name)
  File "infer/infer/infer/bin/infer", line 42, in get_module_name
    for module, commands in MODULE_TO_COMMAND.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

It works fine when I symlink /usr/bin/python to python2.

A solution for linux would be to replace every `#!/usr/bin/env python` line with `#!/usr/bin/env python2`

**Comment by iiSeymour** [comment]
The problem with changing `#!/usr/bin/env python` to `#!/usr/bin/env python2` is OS X doesn't support [PEP-0394](https://www.python.org/dev/peps/pep-0394/) and you'll end up with `python2 not found`.

A better solution would be to support both Python 2.X and Python 3.X. Projects such as [six](https://pythonhosted.org/six/) are design to help with this.

**Comment by reactormonk** [comment]
@iiSeymour and to wait for Apple to fix that will probably take years?

**Comment by akotulski** [comment]
I changed the code so now it explicitly looks for python2.7 (we don't support 2.6 anyway), like so:
#!/usr/bin/env python2.7

It should work on Arch as well, as long as you have python2.7 installed
https://github.com/facebook/infer/commit/f47166eb4450952047ad6bc6ef44a3bf159d3ba0
