### ISSUE TITLE
normal i386 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler

### ISSUE THREAD

**Issue by qiuhm** [facebook/infer#290]
When I execute the shell "infer --debug -- xcodebuild -workspace Source/AliCentrumDB.xcworkspace -scheme AliCentrumDB -configuration Debug -destination 'name=iPhone 6' ",it failed.
error is:
The following build commands failed:
CompileC DerivedData/AliCentrumDB/Build/Intermediates/AliCentrumDB.build/Debug-iphonesimulator/AliCentrumDB.build/Objects-normal/i386/ACDSDBManager.o AliCentrumDB/DbRuntime/ACDSDBManager.mm normal i386 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Traceback (most recent call last):
  File "/Users/tingxuanqhm/libtool/infer/infer/lib/python/inferlib/capture/xcodebuild.py", line 73, in capture
    subprocess.check_call(self.cmd, env=self.get_envvars())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '[u'xcodebuild', u'-workspace', u'Source/AliCentrumDB.xcworkspace', u'-scheme', u'AliCentrumDB', u'-configuration', u'Debug', u'-destination', u'name=iPhone 6', 'CC=/Users/tingxuanqhm/libtool/infer/infer/lib/python/inferlib/../../../lib/xcode_wrappers/clang', 'CPLUSPLUS=/Users/tingxuanqhm/libtool/infer/infer/lib/python/inferlib/../../../lib/xcode_wrappers/clang++', 'GCC_PRECOMPILE_PREFIX_HEADER=NO']' returned non-zero exit status 65
None

But When I execute the shell "xcodebuild -workspace Source/AliCentrumDB.xcworkspace -scheme AliCentrumDB -configuration Debug -destination 'name=iPhone 6' ",it suceeded.

It is confusing.How do resolve the problem?

**Comment by qiuhm** [comment]
My python version is 2.7.10

**Comment by jvillard** [comment]
Can you please give the full output of the run? (please use https://gist.github.com/ or equivalent)

**Comment by jvillard** [comment]
Please re-open if you have more info, in particular the full output of infer.

**Comment by WANGNEWMAN** [comment]
@jvillard  I user common flow,but i get some error.
xcodebuild -workspace RoDress.xcworkspace -scheme RoDress -configuration Debug -sdk iphonesimulator clean
infer -- xcodebuild -target RoDress -configuration Debug -sdk iphonesimulator CLANG_ENABLE_MODULES=NO


** BUILD FAILED **


The following build commands failed:
	CompileC /Users/wangnewman/Documents/Royole/hat_coat/build/RoDress.build/Debug-iphonesimulator/RoDress.build/Objects-normal/i386/RYMoreControlDeviceView.o /Users/wangnewman/Documents/Royole/hat_coat/RoDress/RYMain/Home/OneControllerMore/View/subView/RYMoreControlDeviceView.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/wangnewman/Documents/Royole/hat_coat/build/RoDress.build/Debug-iphonesimulator/RoDress.build/Objects-normal/i386/UIButton+HGTool.o /Users/wangnewman/Documents/Royole/hat_coat/RoDress/Common/Category/UIButton/UIButton+HGTool.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/wangnewman/Documents/Royole/hat_coat/build/RoDress.build/Debug-iphonesimulator/RoDress.build/Objects-normal/i386/RYAboutView.o /Users/wangnewman/Documents/Royole/hat_coat/RoDress/RYMain/Mine/RYAbout/View/RYAboutView.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/wangnewman/Documents/Royole/hat_coat/build/RoDress.build/Debug-iphonesimulator/RoDress.build/Objects-normal/i386/RYBlockHelper.o /Users/wangnewman/Documents/Royole/hat_coat/RoDress/RYNetWooking/Tools/RYBlockHelper.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(4 failures)
Internal Error:   /usr/local/lib/infer/infer/bin/../lib/python/infer.py -j 4 --project-root
  /Users/wangnewman/Documents/Royole/hat_coat --out
  /Users/wangnewman/Documents/Royole/hat_coat/infer-out -- xcodebuild -target
  RoDress -configuration Debug -sdk iphonesimulator
  CLANG_CXX_LIBRARY=libstdc++:
  exited with code 65
Error backtrace:
Raised at file "string.ml", line 142, characters 16-31
Called from file "src/string.ml", line 402, characters 12-33
Called from file "src/string.ml", line 411, characters 11-33
Re-raised at file "base/Die.ml" (inlined), line 26, characters 8-56
Called from file "base/Die.ml", line 32, characters 6-39
Called from file "integration/Driver.ml", line 164, characters 2-16
Called from file "integration/Driver.ml", line 282, characters 6-409
Called from file "integration/Driver.ml" (inlined), line 304, characters 2-29
Called from file "integration/Driver.ml", line 309, characters 67-94
Called from file "scuba/ScubaEventLogging.ml", line 62, characters 16-20
Called from file "infer.ml", line 20, characters 2-36
Called from file "scuba/ScubaEventLogging.ml", line 62, characters 16-20
Called from file "infer.ml" (inlined), line 25, characters 22-99
Called from file "infer.ml", line 133, characters 8-54


tks

**Comment by WANGNEWMAN** [comment]
@jvillard 
logs 
[logs.txt](https://github.com/facebook/infer/files/3240713/logs.txt)
tks

**Comment by jvillard** [comment]
@WANGNEWMAN Thanks for the logs. It's not obvious to me what's wrong, but the recommended way to analyse xcodebuild projects is via a compilation database, see https://fbinfer.com/docs/analyzing-apps-or-projects.html#xcodebuild
