### ISSUE TITLE
Docker build failed

### ISSUE THREAD

**Issue by wisenight** [facebook/infer#291]
Hi, Sir

I use docker to build the infer images.

And it got below error: 

Could you help to check it?

**[ERROR] The compilation of conf-ncurses failed at "pkg-config ncurses".**
```

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[conf-m4: m4] Command started
[conf-ncurses: pkg-config ncurses] Command started
-> installed ocamlbuild.0
[camlp4: ./configure] Command started
-> installed conf-m4.1
[ERROR] The compilation of conf-ncurses failed at "pkg-config ncurses".
[camlp4: make all] Command started
[camlp4: make install] Command started
-> installed camlp4.4.02+7
```

**Comment by kstreee** [comment]
I experienced it too very recently, and I found a solution of it, add `pkg-config` after [this line](https://github.com/facebook/infer/blob/master/docker/Dockerfile#L25).
I don't know what exactly it is, but the command `opam depext conf-pkg-config.1.0` installs it  to resolve installation failure what you reported.

**Comment by wisenight** [comment]
@kstreee thx for your hlep, it works now
