### ISSUE TITLE
Infer does not analyze the whole android project

### ISSUE THREAD

**Issue by nellylam** [facebook/infer#292]
After I ran `infer -- ./gradlew build` it only returned results from external libraries and a couple other modules. I looked in the filelist, and it is missing almost the entire source code of our app. Our source code is not at the root, but in 2 layers deep of subdirectories, but I must run ./gradlew build at the root. The results are pretty useless unless I can analyze the actual app. Any ideas?
Here is my toplevel.log:
```
[INFO] Running command /Users/nelly/Code/infer/infer/bin/infer -- ./gradlew build
[INFO] Path to infer script /Users/nelly/Code/infer/infer/bin/infer (/Users/nelly/Code/infer/infer/lib/python/infer)
[INFO] Infer version v0.7.0
Copyright 2009 - present Facebook. All Rights Reserved.


[INFO] Platform: Darwin-14.5.0-x86_64-i386-64bit
[INFO] PATH=/Users/nelly/Code/infer/infer/bin:/Users/username/android/sdk/platform-tools:/Users/nelly/Code/android-sdk-macosx/tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/nelly/Code/android-sdk-macosx/platform-tools/
[INFO] SHELL=/bin/bash
[INFO] PWD=/Users/nelly/Code/android
[INFO] Running with:

------------------------------------------------------------
Gradle 2.2.1
------------------------------------------------------------

Build time:   2014-11-24 09:45:35 UTC
Build number: none
Revision:     6fcb59c06f43a4e6b1bcb401f7686a8601a1fb4a

Groovy:       2.3.6
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.7.0_80 (Oracle Corporation 24.80-b11)
OS:           Mac OS X 10.10.5 x86_64


[INFO] Capture phase was successful
[INFO] Starting analysis
 ```

**Comment by sblackshear** [comment]
Our Gradle integration is quite primitive (it just looks for calls to `javac` in the verbose output of Gradle), so it can certainly miss things.

Can you share a link to your project (or a tarball)? I can take a look and try to understand why it's missing your source code in this particular case.

**Comment by nellylam** [comment]
@sblackshear Unfortunately, it's a private project, but can maybe you tell me what to look for?

**Comment by nellylam** [comment]
@sblackshear or is there any other information I can provide to help debug this?

**Comment by sblackshear** [comment]
A paste of the output of `./gradlew --debug` would be helpful (I can look at it and see if it's just a problem with our parsing of javac commands from the verbose, or a deeper problem with out approach).

**Comment by nellylam** [comment]
It looks like a lot of these: `Error:
	Attribute permission#${package}.permission.C2D_MESSAGE@name at AndroidManifest.xml:24:9 requires a placeholder substitution but no value for <package> is provided.
`

**Comment by nellylam** [comment]
followed by this ```
13:36:58.480 [ERROR] [org.gradle.api.Project] /Users/nelly/Code/android/App/src/main/AndroidManifest.xml:0:0 Error:
	Validation failed, exiting
13:36:58.497 [ERROR] [org.gradle.BuildExceptionReporter] 
13:36:58.497 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
13:36:58.498 [ERROR] [org.gradle.BuildExceptionReporter] 
13:36:58.498 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
13:36:58.498 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':AppLibrary:processDexOptionsDebugManifest'.
13:36:58.498 [ERROR] [org.gradle.BuildExceptionReporter] > Manifest merger failed with multiple errors, see logs
13:36:58.498 [ERROR] [org.gradle.BuildExceptionReporter] 
13:36:58.498 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
13:36:58.498 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
Starting analysis (Infer version v0.7.0)
```

**Comment by nellylam** [comment]
On second look, running ./gradlew build is now failing w/out Infer.

**Comment by nellylam** [comment]
Ok, I've verified that this is not happening for anyone else but me. 
also seeing these errors `Error:
	Attribute data@scheme at AndroidManifest.xml:522:21 requires a placeholder substitution but no value for <deepLinkScheme> is provided.`
Do you think it could be something I've installed for Infer? Does Infer modify the Manifest file?

**Comment by sblackshear** [comment]
No, Infer does not modify the manifest file. It certainly shouldn't be doing anything that changes the non-Infer build workflow, but let us know if it is!

**Comment by sblackshear** [comment]
Closing this; feel free to reopen if you find that this is an Infer issue rather than a Gradle one.
