### ISSUE TITLE
Typo in opam file.

### ISSUE THREAD

**Issue by kstreee** [facebook/infer#293]
Building latest version of Infer works after replacing `oUnit` to `ounit` in [this line](https://github.com/facebook/infer/blob/master/opam#L23) and running `opam install --deps-only infer` after changing the line.

**Comment by jvillard** [comment]
thanks for the report!

**Comment by jvillard** [comment]
@kstreee what kind of system did you run infer on?

**Comment by kstreee** [comment]
I run Infer on Ubuntu, Mac OS X, Cent OS 6.x. I usually use Ubuntu.

**Comment by sblackshear** [comment]
Fixed by 450b97b9d70cfca578d3f2621e5e7e2eb8cc8403/
