### ISSUE TITLE
I got unknown type name '__uint32_t' typedef __uint32_t  when i run infer on my project 

### ISSUE THREAD

**Issue by shenruisi** [facebook/infer#295]
i use this command line 
infer -- xcodebuild -scheme ht -configuration Debug -sdk iphonesimulator

and run on Xcode 7.2.1 ios9.2, but got follow error.
[temp.zip](https://github.com/facebook/infer/files/163096/temp.zip)

**Comment by jvillard** [comment]
Can you try running `xcode-select --install`?

**Comment by shenruisi** [comment]
I have installed it all ready.发自网易邮箱大师
            在2016年03月08日 20:02，Jules Villard 写道:Can you try running xcode-select --install?

**Comment by shenruisi** [comment]
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

**Comment by jvillard** [comment]
Does `xcodebuild -scheme ht -configuration Debug -sdk iphonesimulator` work on its own, without infer?

**Comment by jvillard** [comment]
please re-open if there is still an issue
