### ISSUE TITLE
Error while trying to run inferTest (eradicate:eradicate dependency)

### ISSUE THREAD

**Issue by luiscruz** [facebook/infer#296]
I'm not able to run tests:

```
$ inferTest java
Not using buckd because watchman isn't installed.
[+] PROCESSING BUCK FILES...0.3s [100%]
BUILD FAILED: Couldn't get dependency '//infer/tests/endtoend/java/eradicate:eradicate' of target '//infer/tests/endtoend:java_endtoend_tests':
Parse error for build file /Users/luiscruz/dev/infer/infer/tests/endtoend/java/eradicate/BUCK: Stream closed
```
I'm running from the ```./infer/bin``` folder.
Am I missing something here?

--Luis

**Comment by jvillard** [comment]
The supported way to run tests is `make test`. `inferTest` doesn't check that things have been built before running, so that may be the issue here.

If that doesn't fix it, can you tell me how you built infer?

**Comment by luiscruz** [comment]
I was following the description in the following link:
http://fbinfer.com/docs/advanced-features.html#run-internal-tests

Thanks @jvillard. I will give it a try.

**Comment by jvillard** [comment]
oops, didn't catch that when we introduced `make test`. I'll update the website, thanks!

**Comment by luiscruz** [comment]
A similar error persists when I run ```make test```:

```
...(Lots of weird stuff)...
# Parallel statistics: { count(total): 9(115), max: 2, min: 2, average(total): 2.000(1.078) }
cp -f -p /Users/luiscruz/dev/infer/infer/_build-infer/unit/unit/inferunit.native 
/Users/luiscruz/dev/infer/infer/bin/InferUnit
..................
Ran: 18 tests in: 0.11 seconds.
OK
NO_BUCKD=1 buck clean
Not using buckd because NO_BUCKD is set.
NO_BUCKD=1 buck test java objc
Not using buckd because NO_BUCKD is set.
[+] PROCESSING BUCK FILES...0.3s [100%]
BUILD FAILED: Couldn't get dependency '//infer/tests/endtoend/java/comparison:comparison' of target '//infer/tests/endtoend:java_endtoend_tests':
Parse error for build file /Users/luiscruz/dev/infer/infer/tests/endtoend/java/comparison/BUCK: Stream closed
make: *** [buck_test] Error 1
```

PS: Is ```inferTest``` still necessary?

**Comment by jvillard** [comment]
How did you build infer? Can you run `make clean` then paste the output of:

  ./configure
  make
  make test

re: PS: `make test` still uses `inferTest` under the hood.

**Comment by luiscruz** [comment]
I just run those instructions but the error persists.
I have installed infer from the pre-compiled version with opam.
I will try to build it from source without opam.

**Comment by luiscruz** [comment]
My laptop is still building which means I wasn't doing it right, previously.
I believe we can close this for now. I'll re-open it if the issue persists, but probably it doesn't.
Thanks for the help @jvillard and sorry for the noob question. :sweat_smile:

**Comment by luiscruz** [comment]
Humm problem persists..

```
$ make test
(...)
# Parallel statistics: { count(total): 9(115), max: 2, min: 2, average(total): 2.000(1.078) }
cp -f -p /Users/cruz/dev/infer/infer/_build-infer/unit/unit/inferunit.native /Users/cruz/dev/infer/infer/bin/InferUnit
/Users/cruz/dev/infer/infer/bin/InferUnit
..................
Ran: 18 tests in: 0.19 seconds.
OK
NO_BUCKD=1 buck clean
Not using buckd because NO_BUCKD is set.
NO_BUCKD=1 buck test c cpp java objc
Not using buckd because NO_BUCKD is set.
[+] PROCESSING BUCK FILES...0.6s [100%]
BUILD FAILED: Couldn't get dependency '//infer/tests/endtoend/java/comparison:comparison' of target '//infer/tests/endtoend:java_endtoend_tests':
Parse error for build file /Users/cruz/dev/infer/infer/tests/endtoend/java/comparison/BUCK: Stream closed
make: *** [buck_test] Error 1```

**Comment by sblackshear** [comment]
I wonder if this could be a buck version problem--would you mind printing the output of `buck --version`?

Thanks for being patient with this--we surprisingly don't seem to have a lot of users trying to run our tests, and we appreciate the feedback!

**Comment by luiscruz** [comment]
@sblackshear:

```
$buck --version
buck version v2016.02.29.01
```

Glad I can help :)

**Comment by jvillard** [comment]
>  I have installed infer from the pre-compiled version with opam.

Can you clarify the steps you used to build infer?

**Comment by luiscruz** [comment]
Last time I've built infer from source:

```
git clone --recursive https://github.com/facebook/infer.git
cd infer
./autogen.sh
./configure
opam update
opam pin add --yes --no-action infer .
opam install --deps-only infer
./configure
make
make test
```

Somewhere in the process I also had to do

```eval $(opam config env)```

But I'm not sure exactly when and if it was necessary for this particular case.

**Comment by luiscruz** [comment]
I've tried again in a different machine and I got the same error.

- MacBook Air (13-inch, Late 2010) running Mac OS X Yosemite 10.10.5
- iMac (27-inch, Mid 2011) running Mac OS X El Capitan Version 10.11.3

**Comment by jvillard** [comment]
> `Parse error for build file /Users/cruz/dev/infer/infer/tests/endtoend/java/comparison/BUCK: Stream closed`

I managed to repro this using the latest buck from github, looking into it now.

**Comment by luiscruz** [comment]
Any update on this?

**Comment by jvillard** [comment]
@luiscruz yes, you can try reverting buck to an older version to make it work. See facebook/buck#697. The first release that removed it was v2015.11.02.01. You can revert to https://github.com/facebook/buck/releases/tag/v2015.10.26.01 to get a working version. I'll add a `.buckconfig` file to infer to prevent this problem, then close the issue.

**Comment by luiscruz** [comment]
Great! Thanks @jvillard!
