### ISSUE TITLE
Docs page Separation logic and bi-abduction

### ISSUE THREAD

**Issue by luiscruz** [facebook/infer#297]
I'm reading the following docs page:
http://fbinfer.com/docs/separation-logic-and-bi-abduction.html

and I believe there are some rendering issues, as you can see in the images.

Picture 1:
![screen shot 2016-03-08 at 23 15 15](https://cloud.githubusercontent.com/assets/1080714/13619949/01d5b784-e584-11e5-95b8-151b972a949c.png)

Picture 2:
![screen shot 2016-03-08 at 23 15 05](https://cloud.githubusercontent.com/assets/1080714/13619950/0209436a-e584-11e5-870e-0a930483ea5b.png)

This happens both on Safari Version 9.0.3 (10601.4.4) and Chrome Canary Version 51.0.2670.0 canary (64-bit).

**Comment by jvillard** [comment]
thanks for the report @luiscruz!

**Comment by luiscruz** [comment]
No problem @jvillard! ;)
