### ISSUE TITLE
How to compare Procname.java_type with Sil.typ

### ISSUE THREAD

**Issue by luiscruz** [facebook/infer#305]
I am trying to build a Checker and I have the following pattern in my ```do_instr```:
```ocaml
 | Sil.Call (_, Sil.Const (Sil.Cfun pn), ((_arg1_exp,arg1_typ)::_ as args), loc, _) -> (*...*)
```

In this particular checker I am only interested in method calls in which the class of the method is the same as the class of the first argument.
The closest I came up with was with the following expression:
```ocaml
((Sil.typ_to_string arg1_typ) = (Procname.java_get_class pn) )
```
This doesn't work. With the class ```Hello``` the expression above is equivalent to this:
```ocaml
"class Hello" = "Hello"
```

I can always remove the "class " prefix but I'm sure there is a better way of doing it...

**Comment by cristianoc** [comment]
In `Patternmatch`:
```ocaml
(** Get the class name of the type *)
val type_get_class_name : Sil.typ -> Mangled.t option
```
Then `Mangled.to_string`

**Comment by luiscruz** [comment]
Ok got it with:

```ocaml
let arg1_class =  match (PatternMatch.type_get_class_name arg1_typ) with
  | Some mangled_class_name -> Mangled.to_string mangled_class_name
  | _ -> "" 
```
