### ISSUE TITLE
PatternMatch.is_getter no longer works with Sil.Cfun

### ISSUE THREAD

**Issue by luiscruz** [facebook/infer#307]
In my ```do_instr``` I am matching the following pattern:
```ocaml
| Sil.Call (_, Sil.Const (Sil.Cfun pn), ((_arg1_exp,arg1_typ)::_ as args), loc, _) -> (*...*)
```

Doing ```PatternMatch.is_getter pn``` after pulling commit 7ffb6357197d88b9caa50b8986902169c80e8e83, but it no longer works with the latest commit (9f7bfea98fabb997bae02df028adcf0735a3a93a).

I'm not sure when this has changed but now I have the following error:
```
Error: This expression has type Procname.t
       but an expression was expected of type Procname.java
```

--Luis

**Comment by cristianoc** [comment]
The API of Procname is undergoing change to make it safer, as it would assert false if e.g. functions for Java procedure names were called with C procedure names.

For example `PatternMatch.is_getter` would work only with Java, so now it takes  type `java` to make sure it's not called from the wrong language.
(things will change some more, but not in complex ways)

**Comment by luiscruz** [comment]
Got it! Thanks @cristianoc
