### ISSUE TITLE
IOError when trying to compile Hello.java

### ISSUE THREAD

**Issue by sorainsm** [facebook/infer#309]
Hi,

I'm trying to run the example file Hello.java using the command "infer  -- javac Hello.java" from inside the examples folder but it keeps terminating with an IOError that there's no infer-out/.start file. I was wondering if anyone knows what's going on with this? I was under the assumption that Infer created it's own results directory, but do I need to make one instead?

Thanks!

**Comment by sorainsm** [comment]
UPDATE: recompiled infer and everything worked fine. Not sure what went wrong the first time then. Any thoughts?

**Comment by jvillard** [comment]
maybe you were mixing two versions of infer together? one that doesn't create a ".start" file and one that expects it's there.
