### ISSUE TITLE
Infer reports errors in wrong location (a CoreFoundation header that is not analysed)

### ISSUE THREAD

**Issue by AravinthChandran** [facebook/infer#31]
/Applications/Xcode 6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFAvailability.h:131: error: MEMORY_LEAK
   memory dynamically allocated to ref by call to SCNetworkReachabilityCreateWithAddress() at line 128, column 36 is not reachable after line 131, column 9

/Applications/Xcode 6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFAvailability.h:258: error: MEMORY_LEAK
   memory dynamically allocated to policies by call to array at line 251, column 32 is not reachable after line 258, column 5

/Applications/Xcode 6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFAvailability.h:273: error: MEMORY_LEAK
   memory dynamically allocated to pinnedCertificates by call to array at line 269, column 50 is not reachable after line 273, column 13

**Comment by jvillard** [comment]
Hi,

What command did you use to run Infer? It looks like you passed `--headers` to the `infer` command, which makes Infer analyse headers, hence why it would report on these `.h` files.

**Comment by AravinthChandran** [comment]
Hey jvillard,
this is what i've used,
infer -- xcodebuild -target <target name> -configuration Release clean build -sdk iphonesimulator

**Comment by jvillard** [comment]
It looks like Infer is wrongly reporting the locations of these errors. There is no `SCNetworkReachabilityCreateWithAddress()`, `policies` or `pinnedCertificates` in `/Applications/Xcode 6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFAvailability.h`!

So these reports are actually for somewhere else in the code, not in this header.

This is a known issue in our clang frontend that sometimes line numbers/files are off. We are actively working on fixing this. Leaving this open until we do.

**Comment by chenyunyou** [comment]
13765303472

**Comment by chenyunyou** [comment]
0412+.liliral

**Comment by chenyunyou** [comment]
553848408@qq.com

**Comment by cakey** [comment]
Getting a similar issue.

**Comment by AravinthChandran** [comment]
@cakey  Do you use AFNetworking in your project, i did a project wide search on 
SCNetworkReachabilityCreateWithAddress(), policies, pinnedCertificates all are inside AFNetworking .

**Comment by cakey** [comment]
No - just plain c.

**Comment by dulmarod** [comment]
This issue has been addressed, please consider using the latest release available in:
https://github.com/facebook/infer/releases/latest.
