### ISSUE TITLE
Infer is not finding frameworks 

### ISSUE THREAD

**Issue by royanghami** [facebook/infer#310]
infer -- clang -c ViewController.m
ViewController.m:8:9: fatal error: 'UIKit/UIKit.h' file not found
#import <UIKit/UIKit.h>
        ^
1 error generated.

**Comment by jvillard** [comment]
The error you get is from clang, not Infer, as you can test by trying `clang -c ViewController.m` on its own. You need to use a compilation command that works for your project. See http://fbinfer.com/docs/analyzing-apps-or-projects.html for examples.
