### ISSUE TITLE
failed to compile xcode project

### ISSUE THREAD

**Issue by royanghami** [facebook/infer#311]
The following build commands failed:
CompileC /Users/admin/Desktop/App/iOS/build/Pods.build/Debug-iphonesimulator/pop.build/Objects-normal/i386/POPAnimatableProperty.o pop/pop/POPAnimatableProperty.mm normal i386 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler

**Comment by jvillard** [comment]
Can you paste the command you are running as well as its full output? Use https://gist.github.com/ or similar for large pastes. Also, the contents of "infer-out/toplevel.log" could be useful, please paste them as well. Thanks!

**Comment by royanghami** [comment]
command + output: https://gist.github.com/royanghami/76ce2973a34b6b449183
toplevel.log: https://gist.github.com/royanghami/c246ff5286695e1f61d4

**Comment by jvillard** [comment]
Thanks! The error is actually "fatal error: cyclic dependency in module 'Darwin': Darwin -> std -> Darwin". It's a [know problem in clang](https://github.com/facebook/infer/issues/232#issuecomment-169744110), see the solutions suggested in #232 to solve your problem.

**Comment by royanghami** [comment]
i try the solutions in #232, but nothing works

**Comment by jvillard** [comment]
do you get the same output when you run `infer -- xcodebuild -workspace Anghami.xcworkspace -scheme Anghami" "Release -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=9.1,name=iPhone 6' CLANG_ENABLE_MODULES=NO`?

**Comment by royanghami** [comment]
I got another error

**Comment by jvillard** [comment]
can you please paste the full output of that one?

**Comment by royanghami** [comment]
output : https://gist.github.com/royanghami/51e5f83acfff4fe1e0a7

**Comment by jvillard** [comment]
There are two errors:

1. The linking step is failing. You can set `LD` to `/bin/true` to circumvent the issue. See the [FAQ](http://fbinfer.com/support.html#infer----build-command-fails-during-a-linking-step). Let me know if linking still fails.

2. You need to disable modules only selectively because you use `@import` in your project. Does [this solution](https://github.com/facebook/infer/issues/232#issuecomment-173378896) work for you?

**Comment by jvillard** [comment]
closing optimistically. We're tracking the module issue in #335
