### ISSUE TITLE
How does one white-list or black-list directories for Infer to analyze?

### ISSUE THREAD

**Issue by MatejBalantic** [facebook/infer#312]
Hey,

first of all big shout out to Facebook for this cool project and the fact that it was open sourced. 

Is there any way to exclude or white-list paths that we want Infer to analyze? We have bunch of 3rd party dependencies that we don't (always) want to analyze and we would love to exclude them from the checks?

Thanks

**Comment by cristianoc** [comment]
Here's an example `.inferconfig` file.
It should go into the current directory where the `infer -- build_command` is issued.
If no whitelist is given, then everything is in. If some whitelist is given, then only what's specified in the whitelist is in.
In any case, what is specified in the blacklist is out.

```
{
  "infer_whitelist": [
    "java/"
    "libraries/"
  ],
  "infer_blacklist": [
    "dont/analyze/badfile.java",
    "this/dir/should/be/ignored/"
  ]
  "eradicate_whitelist": [
    "apps/someapp",
    "this/directory/should/be/analyzed"
  ],
  "eradicate_blacklist": [
    "mytests/"
  ],
  "checkers_whitelist": [
    "java/"
  ],
}
```

**Comment by MatejBalantic** [comment]
@cristianoc Thank you very much for this, I must have missed the documentation on this! Very useful!

**Comment by qmkCamel** [comment]
Now it should replace " infer_whitelist " to " infer-whitelist-path-regex ".
But I don`t find any thing about the white-list or black-list in the website .
Is there anything need to explain how to use it in the website , or just give a example in the website.
Thanks !

**Comment by jvillard** [comment]
@qmkCamel they work the same as before, only the names changed. The example above is still valid.

If you specify a whitelist, only the files whose path matches the whitelist regexp will be analysed. The path is relative to the project root (see help for `--project-root`).

**Comment by qmkCamel** [comment]
@jvillard Thanks ! I got it .
