### ISSUE TITLE
Detecting internal accessor methods

### ISSUE THREAD

**Issue by luiscruz** [facebook/infer#313]
I am trying to create a detector for the use of internal accessor methods.
I have created a Checker for that --> https://github.com/luiscruz/infer/blob/b6474d04eaee790c1632e86297de10282d9d5a07/infer/src/checkers/androidEnergyCheckers.ml

However, my Checker is detecting whether a method is a getter or setter by parsing the method name. I.e., methods starting with ```get``` or ```set``` and with 0 or 1 parameters, respectively, are accessors.

The problem with this approach is that there are many false positives. Some methods which name starts with ```get``` or ```set```, do not strictly get or set one object's field.

I'm thinking that maybe add another restriction that considers the LOC of the method would fix the problem.

Is this possible with Infer Checkers? Is there a better framework for this problem? What do you think?

**Comment by cristianoc** [comment]
How do you plan to use the location information?
(Btw the location information can be accessed using `AttributesTable.load_attributes proc_name`, then look at field `ProcAttributes.loc`. Note though: the front-end start from bytecodes so the location information is not always 100% accurate).

I don't know of an accurate heuristic to detect getters and setters, but you can try and see if the one you have can be refined to the point of being useful.
Another possible observation, getters/setters tend to be very simple functions, so one could in principle look at the instructions in their implementation, and see if there are very few instructions, for some notion of `very few`. Look at the control-flow graph of the code you have, and see if code simplicity could be positively correlated.

Perhaps by LOC you mean simplicity.

**Comment by cristianoc** [comment]
If you need to look at the implementation of the callee, every callback has a field called `get_proc_desc`, which can be used to obtain the procedure description of the callee. With it, you can look at nodes and instructions.

**Comment by luiscruz** [comment]
@cristianoc by LOC I was trying to mean lines of code/simplicity. 
An accessor should have only one instruction.
```get_proc_desc ``` will probably get the job done.
Thanks!

**Comment by luiscruz** [comment]
I'm finding this ```get_proc_desc``` hard to understand.
@cristianoc could you give me some examples?

**Comment by cristianoc** [comment]
```
let my_callback { Callbacks.proc_desc; proc_name; get_proc_desc } =
...
match get_proc_desc callee_proc_name with
| Some callee_proc_desc -> ...iterate over nodes and instructions...
```
So for each callee it's as if you were writing a new checker: start again from the procedure description.

When the callee is a simple getter, I would expect a start node, an exit node, and a node in the middle, with only a few instructions. (Plus an exceptions sink node. for collecting exceptions, I guess).

Given this source
```
  String getF() {
    return f;
  }
```
here's the central node, between the start and the exit node:
```
16: method_body
n$0=*&this:class C * [line 5]
n$1=*n$0.C.f:class C [line 5]
*&return:class java.lang.String *=n$1 [line 5]
REMOVE_TEMPS(n$0,n$1); [line 5]
NULLIFY(&this,false); [line 5]
APPLY_ABSTRACTION; [line 5]
```

Not as beautiful as the source, but that's what you get after translation to a lower level IR.

**Comment by luiscruz** [comment]
So basically I have created the following function, that gives the number of nodes:

```ocaml
let proc_get_number_of_nodes = function
  | Some callee_proc_desc -> (IList.length (Cfg.Procdesc.get_nodes callee_proc_desc))
  | _ -> 0
```

Testing it with the java methods ```getFoo()``` and ```setFoo()``` implemented in the following class Hello:
```java
class Hello {
	public int foo;
	public int getFoo(){
		return foo;
	}
	public void setFoo(int val){
		foo=val;
	}
}
```

... my function ```proc_get_number_of_nodes``` returns 4 for ```getFoo``` and 5 for ```setFoo```. So basically I am filtering getters and setters with these values. This gets the job done for now. However, this is just an empirical restriction, I am not really sure about the structure of these nodes. 
Can you give me some hints on this?

**Comment by cristianoc** [comment]
Another simple observation: if you count only nodes with "real" instructions, there's only one node each, for the two cases above.
Instructions that are not "real" include `DECLARE_LOCALS, REMOVE_TEMPS, NULLIFY, APPLY_ABSTRACTION`.
Furthermore, you can narrow it down some more by looking at the instructions in that node, if useful.

**Comment by luiscruz** [comment]
> Furthermore, you can narrow it down some more by looking at the instructions in that node, if useful

Looking at the instructions will be useful, but I am doing baby steps because I still need to get familiar with all of this.

**Comment by luiscruz** [comment]
Is there a way of printing the SIL representation of the CFG?
I know an instruction can be Letderef, Set, Prune, Call, Nullify, Abstract, Remove_temps, Stackop, Declare_locals or Goto_node. But in some cases is hard to guess how a given node in the cfg will using SIL.

**Comment by luiscruz** [comment]
For instance, consider the following Java code:
```java
public int getFoo(){
	return foo;
}
```

The number of nodes of this proc_desc is 4 which is in accordance with the CFG. But when I iterate using ```Cfg.Procdesc.fold_instrs```, the number of instructions is 8 but I'm not quite sure how they look like.
In this case I know that there is an instruction that matches with Sil.Set(_,_,_,_). But where is the assignment in this code?

It's hard for me to create patterns to match instructions because I am trying to guess them.. A print method or other debug tool might help here..

**Comment by sblackshear** [comment]
A nice way to see what the CFG looks like is to run:

`infer -g -- javac MyFile.java`
`open infer-out/captured/MyFile.<hash>.html`

The HTML file will show each line of source code next to its SIL representation. It's quite handy!

Note: HTML output won't be produced if you run with `-a checkers`. I usually run once in regular mode to generate the debug output, then switch over to running in checkers mode to debug my checker.

**Comment by luiscruz** [comment]
Thanks @sblackshear. This is really cool.

For the method above, ```getFoo()``` I have the following representation
```
19		public int getFoo(){ S_4 int Hello.getFoo(): 1 specs
20			return foo; E_5 I_6 I_22
21		}
```
I can see that ```S_*``` probably means a start node, ```E_*``` an exit node and ```I_*``` an instruction node. This is pretty similar to what I can get from the dot CFG when I run with checkers enabled:
```
infer -g -a checkers -- javac Hello.java
dot -Tpdf infer-out/captured/Hello.java*/icfg.dot -o icfg.pdf
open icfg.pdf
```

![screen shot 2016-03-23 at 16 59 04](https://cloud.githubusercontent.com/assets/1080714/13993534/ac738e06-f118-11e5-810a-0bd8cf3fa7de.png)

Both outputs are really cool and really useful.
However, it is still hard for me to create patterns that match SIL based on this.

Example:
The following pattern matches with of the instructions of node of the Procdesc ```int Hello.getFoo()```

```ocaml
Sil.Set(_,_,_,loc)
```

However, every time I want to create a new pattern I am blindly trying to guess these things.
Is there any shortcut fort this?

**Comment by luiscruz** [comment]
Any thoughts about this?
It would be enough if there were methods to print types expr and instr.
Maybe there is already some method for this. If not, do you have any suggestion of how to do it?

Thanks!

**Comment by sblackshear** [comment]
To print instructions and expressions, you can use `Sil.d_exp` and `Sil.d_instr`. What these do is print to the debug buffer associated with each node in the HTML debug output. You can print strings to this same buffer using `Logging.d_strln`.

**Comment by sblackshear** [comment]
You can also use `Logging.stdout`/`Logging.stderr` with the pretty-printers for expressions and instrs `Sil.pp_exp`, `Sil.pp_instr`.

These pretty-printers require a `printenv`, and the one you want is almost always `pe_text`. So, an example might look like:

`Logging.stderr "This expression is %a@." (Sil.pp_exp pe_text) exp`.

**Comment by sblackshear** [comment]
Closing this, feel free to file issues if you run into other problems!
