### ISSUE TITLE
support Java 8

### ISSUE THREAD

**Issue by jvillard** [facebook/infer#314]
Right now Infer skips files that use Java 8 constructs (eg, lambdas). Infer should understand Java 8 and analyse these files instead.

Note: this requires Java 8 support from [Javalib & Sawja](http://sawja.inria.fr/).

**Comment by csierra** [comment]
does anybody know if somebody has any idea when java 8 support is going to be added? are we talking about months or years?

**Comment by sblackshear** [comment]
The goal is to support Java 8 before the end of the year.

**Comment by pumano** [comment]
Currently latest Android API 24.0.1 require Java 8 for compile. I can't use infer in our project due to this limitation.

If I use Java 8, Infer crashing (but I'm not sure, we can have cyrillic letters in project, and maybe python unicode decoding problems contains):
```

Traceback (most recent call last):
  File "/usr/local/bin/infer", line 183, in <module>
    main()
  File "/usr/local/bin/infer", line 147, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/usr/local/Cellar/infer/0.8.1/libexec/infer/lib/python/inferlib/capture/gradle.py", line 87, in capture
    cmds = self.get_infer_commands(util.get_build_output(self.build_cmd))
  File "/usr/local/Cellar/infer/0.8.1/libexec/infer/lib/python/inferlib/capture/util.py", line 27, in get_build_output
    return verbose_out_chars.split('\n')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 19159249: ordinal not in range(128)


```

I will wait for your update. If you have any more detailed ETA than "end of year", write here please.

**Comment by sblackshear** [comment]
The latest release https://github.com/facebook/infer/commit/a2f9ce3f23da3c8ddd8c11d0e84852d7d009711e has preliminary Java 8 support, and the changes will be in homebrew once https://github.com/Homebrew/homebrew-core/pull/7057 is accepted. 

We should no longer crash on Java 8 code, but we may miss some bugs in code that uses `invokedynamic`. 

Closing this issue for now, feel free to open new ones with specific examples of `invokedynamic`-related bugs that you'd like Infer to catch.
