### ISSUE TITLE
waf build system mostly working

### ISSUE THREAD

**Issue by hmijail** [facebook/infer#316]
I am trying to use infer with the waf build system, and it mostly works by using it like this (on OS X 10.11.3, waf 1.8, infer 0.8)

export CC="/usr/local/bin/infer --reactive -- clang" # for better traceability, --debug --frontend-debug
rm -r infer-out ; ./waf clean
./waf configure 
./waf build -v -j 1

I say "mostly" because the build log is peppered with infer lines saying "Analyzing 2 files", "3 files", "2 files", etc. Looks like infer is (spuriously?) detecting modifications in the last couple of compiled files each time it runs.

Is that normal? 
And, does it matter? Meaning, would the analysis be better if infer got to analyze all the files at once?

I have tried using --continue, but it's not working; see #315

**Comment by hmijail** [comment]
For completeness: I have tried using CC="infer --incremental -- clang" (though the help says it's deprecated in 0.8) and the effect is the same.

I have also tried CC="infer -a capture -- clang", and during the whole build infer reports to be capturing. But at the end, infer -- analyze says "Analyzed 0 files", which doesn't sound right.

**Comment by hmijail** [comment]
New data: an infer-out directory was being created in the root directory of the project, and that directory ended up containing no captures. But in the <root>/build directory another infer-out directory appeared, and that one contained all the captures.

The sanest-looking way I have found then to run infer with waf is this:
export CC="/usr/local/bin/infer -a capture --reactive -- clang" 
# the -a capture stops infer from analyzing, and the --reactive makes infer accumulate captures; 
# no --continue needed
rm -r infer-out ; rm -r build/infer-out
./waf clean 
./waf configure
./waf build -v -j 1
cd build
infer -- analyze

**Comment by jvillard** [comment]
Thanks for this info! What you're doing manually is very similar to the way Infer integrates with `make`. I wonder if simply adding `waf` to the list of "things that behave like make" would just work.

Can you try applying [this patch](https://gist.github.com/jvillard/853d6ef595b6997c0fdb) on top of your infer version?

```sh
wget https://gist.githubusercontent.com/jvillard/853d6ef595b6997c0fdb/raw/26c137840e0edf3c149145b862b4e3c58cef9a90/waf-support.patch
cd infer-osx-v0.8.0/
patch -p1 < ../waf-support.patch
```

Then you should be able to analyse your waf project like so (don't set your `CC` variable):

```sh
./waf clean 
./waf configure
infer -- ./waf build -v -j 1
```

Let me know the result.

**Comment by hmijail** [comment]
Thank you, but the patch didn't work. ./build/infer-out now doesn't get created, ./infer-out does but the capture directory seemingly stays empty. Infer ends up with "Analyzed 0 files".

Anyway, the basic question is: does infer work better if it gets to see all the files at once?

**Comment by jvillard** [comment]
yes the captured compilation needs to be gathered all in one place for the analysis to work. Infer doesn't go and look into other sub-directories.

The way you use seems to work because all the files end up in build/. Does infer report a sensible number of files analysed? I'll try to find a waf project to play with to understand what's needed to make the integration a bit easier.

**Comment by jvillard** [comment]
Ok, so waf hardcodes the full path to the compilers it finds during `./waf configure`, so infer needs to substitute its own compilers during that phase too.

Can you try again with my patch:

```sh
./waf clean
infer -- ./waf configure
infer -- ./waf build -v -j 1
```

I've successfully analysed samba with that flow (well, had to change one more thing because the wrap `waf` inside `./configure`, but your project shouldn't have that problem).

Many thanks!

**Comment by hmijail** [comment]
Sure, but... which patch should I test?

**Comment by jvillard** [comment]
I meant the one you already tried: https://gist.github.com/jvillard/853d6ef595b6997c0fdb

**Comment by hmijail** [comment]
Ah, sorry, I didn't realize that you had added the call to infer to waf configure. I'll try.

**Comment by hmijail** [comment]
Worked :). Thanks!

Following on the question of seeing all files at once: I have a static library project which uses waf, and a runnable project which uses make and depends on the library. The waf part is now solved, and make is supported, but... how to mix them?
(I guess I should ask this somewhere else: the IRC channel? Anyway please consider this a bug against documentation :) )

**Comment by jvillard** [comment]
awesome, I'll push this to master soon.

For your question, you could try to capture both compilations into the same directory and then analyse both at once:
```sh
infer -o /some/where/infer-out -a capture -- ./waf build
# go to the other part of your project
infer -o /some/where/infer-out --reactive --continue -a capture -- make
# analyze both
infer -o /some/where/infer-out -- analyze
```

**Comment by hmijail** [comment]
Great. Thank you!
