### ISSUE TITLE
Every time I installed infer, restart the computer must be re-installed once, how I need to do?

### ISSUE THREAD

**Issue by ZiYouDeLaoGe** [facebook/infer#318]
Every time I installed infer, restart the computer must be re-installed once, how I need to do?

**Comment by jvillard** [comment]
you can set up your PATH permanently in your .bash_profile (for example on mac) or equivalent. Something like this:

```sh
export PATH="/Users/.../infer-osx-v0.8.0/infer/bin:$PATH"
echo export PATH=$PATH >> ~/.bash_profile
```

**Comment by ZiYouDeLaoGe** [comment]
谢谢了，这个问题已经解决非常感谢啊！

**Comment by jvillard** [comment]
you're welcome :)

**Comment by ZiYouDeLaoGe** [comment]
I use the source code installed, how can I do it? Thanks!
