### ISSUE TITLE
Build Failed with ReactJS.framework

### ISSUE THREAD

**Issue by verystrongjoe** [facebook/infer#319]
If I put the library ReactJS.framework to the embedded Binary, I can't build properly. Whenever it builds, it  can't proceed. Instead, It seemed to hang for 2 minutes displaying "Running 2 of 2 two custom shell scripts" on the top of xcode. And it gave final message, "build failed" without error message.  So If I get rid of it in the embedded Binary, it works.

**Comment by jvillard** [comment]
Can you please provide more information? Please include:
- the command you used to run infer
- the full output (please use https://gist.github.com/ or equivalent)
- the contents of toplevel.log (also on https://gist.github.com/)

**Comment by jvillard** [comment]
please re-open with more details
