### ISSUE TITLE
infer -- gradle aR UnicodeDecodeError

### ISSUE THREAD

**Issue by hannahqing** [facebook/infer#320]
raceback (most recent call last):
  File "/usr/local/bin/infer", line 178, in <module>
    main()
  File "/usr/local/bin/infer", line 142, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/inferlib/capture/gradle.py", line 87, in capture
    cmds = self.get_infer_commands(util.get_build_output(self.build_cmd))
  File "/usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/inferlib/capture/util.py", line 27, in get_build_output
    return verbose_out_chars.split('\n')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 75698648: ordinal not in range(128)

**Comment by jvillard** [comment]
Are there non-ascii characters in the `pwd`?

If not, can you try the latest master?

If that doesn't work, please give the output of `locale`, and the contents of infer-out/toplevel.log.

**Comment by smb510** [comment]
I've got the same issue, and I don't have non-ascii characters in my `pwd`.

Here's the output of my `locale`: 
```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

and here's topLevel.log: https://gist.github.com/smb510/a21805256e39d09bc2fe

I'll try with latest master and report back.

**Comment by smb510** [comment]
Yep- exact same thing happens with latest master :grimacing:

**Comment by jvillard** [comment]
Thanks! While waiting for a fix, you can run `LC_ALL="en_US.UTF-8" infer - ...`. Let me know if this works.

(python doesn't like it when your locale and the encoding of strings you are manipulating don't match)

**Comment by hqzhon** [comment]
### I've got the same issue, and I don't have non-ascii characters in my pwd.

### Here's the output of my locale:
``` 
LANG=en_US
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
``` 

### and here's topLevel.log:
``` 
[INFO] Running command /home/zhonghq/development/infer-0.8.0/infer/bin/infer -- ./gradlew build
[INFO] Path to infer script /home/zhonghq/development/infer-0.8.0/infer/bin/infer (/home/zhonghq/development/infer-0.8.0/infer/lib/python/infer)
[INFO] Infer version v0.8.0-unknown
Copyright 2009 - present Facebook. All Rights Reserved.


[INFO] Platform: Linux-3.13.0-71-generic-x86_64-with-Ubuntu-14.04-trusty
[INFO] PATH=/home/zhonghq/.opam/4.02.3/bin:/home/zhonghq/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:~/bin:/home/zhonghq/development/android-sdk-linux/platform-tools:/home/zhonghq/development/android-sdk-linux/tools:/home/zhonghq/development/android-sdk-linux/platform-tools:/home/zhonghq/.npm-packages/bin:/usr/lib/jvm/java-7-oracle/bin:/home/zhonghq/development/infer-0.6.0/infer/bin:/usr/local/go/bin:/home/zhonghq/development/android-sdk-linux/build-tools/23.0.1
[INFO] SHELL=/bin/bash
[INFO] PWD=/home/zhonghq/kingsoft/CleanMaster
[INFO] Running with:

------------------------------------------------------------
Gradle 2.4
------------------------------------------------------------

Build time:   2015-05-05 08:09:24 UTC
Build number: none
Revision:     5c9c3bc20ca1c281ac7972643f1e2d190f2c943c

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.4 compiled on April 29 2014
JVM:          1.7.0_80 (Oracle Corporation 24.80-b11)
OS:           Linux 3.13.0-71-generic amd64
``` 

I'll try with latest master and report back.

**Comment by hqzhon** [comment]
sorry,i have try with latest master and same thing happens with latest master

**Comment by hqzhon** [comment]
fix it by adding the following code to the File "/usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/inferlib/capture/gradle.py"
``` 
import sys
``` 
and add the code to the \_\_init\_\_ function 
``` 
reload(sys)
sys.setdefaultencoding('utf-8') 
```

**Comment by smb510** [comment]
@hqzhon that works! Thanks for the help :-D

**Comment by jvillard** [comment]
Since [0.8.1](https://github.com/facebook/infer/releases/v0.8.1), which includes b9c9f208926a687208a909196a86893940a4272b, it should possible to force the encoding used in infer without having to modify the python scripts by hand. In particular, this should fix the issue:

```sh
LC_ALL="en_US.UTF-8" infer ...
```
