### ISSUE TITLE
Detect instance fields

### ISSUE THREAD

**Issue by luiscruz** [facebook/infer#326]
Hi again,

In the checker I am trying to create, I need to know whether a fieldname is an instance field or not.
Example:

```java
class Hello{
  int foo= 0;

  public void test(){
    int i = 0;
    i=3+foo; // foo is a an instance field
    System.out.println("ok");
  }
}
```

I took a look at the ```Ident.java_fieldname_is_outer_instance``` to give me an idea method but I'm not quite sure when appears the string ".this$".

Do you have any suggestion?

**Comment by cristianoc** [comment]
Look for the sample checker `callback_check_field_access`, it does exactly what you need, to detect field accesses buried into arbitrarily complicated expressions.
That checker can be turned into an utility function/visitor.

**Comment by luiscruz** [comment]
I had looked at this method but it didn't get me the restuls I was expecting.

For instance, it is detecting this:
```
Hello.java:29: error: CHECKERS_ANDROID_2
  field java.lang.System.out reading@.
  27.   	}
  28.
  29. > 	public int nonStaticFunction(){
  30.   		System.out.println("calling method of other class"+foo);
  31.   		return 0;
  32.
```

There are 2 things I don't need here:

- static fields
- fields of other classes/objects.

--
Side question: Functions calls are always instructions. They will never appear as an expression. Is this correct?

**Comment by cristianoc** [comment]
@luiscruz are sure you're getting static fields? Static fields are represented as global variables internally, not as field accesses.

If you want to restrict to the current class:
```ml
  (** A field offset, the type is the surrounding struct type *)
  | Lfield of exp * Ident.fieldname * typ

```
The surrounding type gives you a handle to restrict the attention to specific types.

**Comment by luiscruz** [comment]
> are sure you're getting static fields?
It was my impression since it detected System.out. But I'll double check it.

> The surrounding type gives you a handle to restrict the attention to specific classes.
This will get the job done. Thanks!

**Comment by luiscruz** [comment]
It's done. Thanks @cristianoc.
I've adapted the ```callback_check_field_access``` checker.
Regarding the static field accesses I had to check the outer struct ```static_fields```.
Otherwise it would detect them.

**Comment by cristianoc** [comment]
Thanks @luiscruz. At some point, when you get some results, let us know how you're using your checker.

**Comment by luiscruz** [comment]
Will do :+1:

**Comment by luiscruz** [comment]
Hi again,

In this checker I am getting two kids of false positives:

- **Methods that are annotated with @override** -- although I am checking whether a given method is overriding any method in one of its superclasses, this is not enough.
- **Methods that are being overridden by one their subclasses** -- these methods cannot be converted to static.

For the first false positive I think I am getting close but if you could give me some hints it would be really helpful.

For the second, I have no clue... :worried:

**Comment by cristianoc** [comment]
@luiscruz can you paste small examples to illustrate what you would like to get?

**Comment by luiscruz** [comment]
Sure @cristianoc:

> Methods that are annotated with @override

```java
class Hello extends SomeSuperClass implements SomeInterface {
  @override
  public void shouldNotBeStatic{
    // this method does not access any instance property
    // but is tagged with @override
     return;
  }
}
```

> Methods that are being overridden by one of their subclasses

```java
class HelloSuper: HelloSub{
  public void shouldNotBeStatic{
    // this method does not access any instance property
    // but it should not be static in order to be overridden 
     return;
  }
}

class HelloSub{
  private int staticProperty = 0;
  public void shouldNotBeStatic{
    property = 0
    return;
  }
}
```

So, in this last case I don't want to flag ```HelloSuper.shouldNotBeStatic``` as a potential static method since it is not static so that it can be overridden by a subclass.

**Comment by luiscruz** [comment]
Regarding the @ override I thought about this because although I am checking whether the given method belongs to a superclass, I am still having false positives with methods that are overriding other methods.
Probably this happens in methods that implement interfaces. I have to double check this.

**Comment by sblackshear** [comment]
`Prover.get_overrides_of` and `AndroidFramework.get_all_supertypes` could both be suitable for this, depending on exactly what you want to do.

**Comment by luiscruz** [comment]
Thanks @sblackshear.

I think ```Prover.get_overrides_of``` will get the job done for my second problem -- Methods that are being overridden by one of their subclasses.

Regarding my first problem -- Methods that are annotated with @ override -- I need to do this because I am having the following false positive. I.e., I am identifying that this method should be static:

```java
import android.widget.BaseAdapter;

public class FileAdapter extends BaseAdapter {
    @Override
    public long getItemId(int i) {
        return i;
    }
}
```

I believe that since ```android.widget.BaseAdapter``` is not in the source code Infer is not able to retrieve it. Would ```AndroidFramework.get_all_supertypes``` fix this @sblackshear?

I tried it with no luck, but maybe I am doing something wrong. Just wanted to double check this with you.

**Comment by sblackshear** [comment]
I am a little bit confused by what you are trying to do. A static method cannot override an instance method. So although `getItemId` could be static, you can't both make it static and override the method of the superclass. Doing so will give you a compiler error, at least for Java <= 7. I'm not sure about Java 8, though.

**Comment by sblackshear** [comment]
Ah, I understand. You are trying to avoid warning on this method for exactly this reason :).

**Comment by sblackshear** [comment]
I would expect `Prover.get_overrides_of FileAdapter.getItemId <> []` to work for what you want. Let me know if this is not the case and I will take a look.

**Comment by luiscruz** [comment]
From what I understood, ```Prover.get_overrides_of``` will be helpful to get all the overwriting methods of subclasses. I.e., I will retrieve ```getItemId()```methods from subclasses of ```FileAdapter```.

In this problem I need methods from superclasses. I have used ```PatternMatch.proc_iter_overridden_methods``` but it doesn't work for this particular case.

**Comment by luiscruz** [comment]
I've successfully used ```Prover.get_overrides_of``` to skip methods that are being override in subclasses. Thanks @sblackshear!

I still need to check whether a method is overriding a superclass method. I.e., I don't want to identify the method ```getItemId()``` in https://github.com/facebook/infer/issues/326#issuecomment-209526683 as a static candidate.

**Comment by sblackshear** [comment]
I think that you will probably need to write custom logic for this (but please do send a pull request, as this logic could be useful elsewhere!). 

Given a method `m`, I would look up its struct type `T` using `Tenv.proc_extract_declaring_class_typ`. Each `struct_typ` knows what its immediate superclasses and declared methods are. I would iterate through the declared methods of each supertype of `T` looking for methods `m_super` whose name is the same as `m` (for full precision, you'll have to check the the correct subtyping relationship holds on the parameters of `m` and `m_super` as well). This should be done recursively for all superclasses of `T` until you find a match. The code from `AndroidFramework.get_all_supertypes` might be useful to reuse/adapt for this.

**Comment by luiscruz** [comment]
Sure! I'll give it a try :+1:

**Comment by luiscruz** [comment]
I think I've made it.

```ocaml
let struct_typ_is_super_method_of_pname struct_typ java_pname=
	(*comparison between pnames must ignore class name *)
	IList.fold_left (fun acc e -> acc || ((Procname.java_get_method java_pname) = (Procname.get_method e))) false struct_typ.Sil.def_methods
	
let struct_typ_get_def_method_by_name struct_typ method_name = 
	IList.find (fun def_method -> (method_name = (Procname.get_method def_method))) struct_typ.Sil.def_methods
	
let get_struct_typ_of_typename tenv typename=
	Tenv.lookup tenv typename

let get_overriden_method tenv java_pname=
	let rec get_overriden_method_in_superclasses java_pname superclasses=
		match superclasses with
		| superclass::superclasses_tail -> (
			match get_struct_typ_of_typename tenv superclass with
			| Some struct_typ -> 
				if struct_typ_is_super_method_of_pname struct_typ java_pname then
					Some (struct_typ_get_def_method_by_name struct_typ (Procname.java_get_method java_pname))
				else
					(get_overriden_method_in_superclasses java_pname (superclasses_tail@struct_typ.superclasses))
			| None -> get_overriden_method_in_superclasses java_pname superclasses_tail
		)
		| [] -> None
	in
	match (Tenv.proc_extract_declaring_class_typ tenv java_pname) with
	| Some proc_struct_typ ->
		(get_overriden_method_in_superclasses java_pname proc_struct_typ.superclasses)
	| _ -> None
```

I'm not making a pull request yet because I still need to clean aux methods, make some tests, By the way, I still need to figure out how to unit test this.
Also, where do you want this method to be available?
I would suggest module ```Procname```, but I'm not sure.

**Comment by luiscruz** [comment]
I think ```struct_typ_is_super_method_of_pname``` is not really necessary. I will remove it afterwords.

**Comment by sblackshear** [comment]
I think you will run into circular dependencies if you put it in `procname.ml`; `tenv.ml` is probably the best choice if so.  

For unit tests, I would add `tenvTests.ml` under `src/unit` and add your tests there (`procCfgTests` or `schedulerTests` are good examples to follow). We don't have a lot of unit tests so far, but are trying to add more as we write new code. You can run build unit tests using `make unit` and run them using `InferUnit`.

Thanks, this will be a nice function to have!

**Comment by sblackshear** [comment]
Thanks for your contributions! Feel free to open another issue if you need more help with the checkers framework.
