### ISSUE TITLE
BAD_POINTER_COMPARISON: shall we fix it?

### ISSUE THREAD

**Issue by forrest1g** [facebook/infer#329]
Hello folks, I managed to generate report for my iOS project, and there is BAD_POINTER_COMPARISON error. I want the code author to fix it, but he doesn't want to do so. Here's why: this style of coding has been there for ages, and it generates no issue, so won't fix it. 
Code like:
if(some_pointer){//some code here}
I understand infer suggest:
if(some_pointer != nil){//some code here}
so pointer is boxed object and if statement expression expects unboxed value right? This is performance issue I think. Is there other solid reason?

Thanks in advance,
forrest

**Comment by sblackshear** [comment]
Hi Forrest,
  Our motivation for this check is to avoid confusion between a `nil` pointer and a pointer to the numerical value value zero. In our experience, the type coercions in Objective-C make it easy to accidentally write `if (some_pointer)` when you actually meant `if ([some_pointer intValue])`.

**Comment by forrest1g** [comment]
Understood, thank you.
