### ISSUE TITLE
'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by mbrubin56** [facebook/infer#330]
Hi, there.
I ran infer with the command
```infer --  xcodebuild -workspace <my product>.xcworkspace -scheme <my scheme> -sdk iphonesimulator -configuration Debug build```

and received this error
```
The following build commands failed:
	CompileC /Users/mrubin/Library/Developer/Xcode/DerivedData/<my product>-bgiahkwtwuuwnqatrhfacebgivun/Build/Intermediates/Pods.build/Debug-iphonesimulator/Snappy.build/Objects-normal/i386/snappy-sinksource.o Snappy/snappy-sinksource.cc normal i386 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Traceback (most recent call last):
  File "/usr/local/bin/infer", line 178, in <module>
    main()
  File "/usr/local/bin/infer", line 142, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/inferlib/capture/xcodebuild.py", line 78, in capture
    utils.stdout(exc.output)
  File "/usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/inferlib/utils.py", line 298, in stdout
    print(encode(s, errors=errors))
  File "/usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/inferlib/utils.py", line 294, in encode
    return u.encode(encoding=config.LOCALE, errors=errors)
AttributeError: 'NoneType' object has no attribute 'encode'
```
My toplevel.log is
```
[INFO] Running command /usr/local/bin/infer --reactive -- xcodebuild -workspace <product name>.xcworkspace -scheme <my scheme> -sdk iphonesimulator -configuration Debug build
[INFO] Path to infer script /usr/local/bin/infer (/usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/infer)
[INFO] Infer version v0.8.0
Copyright 2009 - present Facebook. All Rights Reserved.


[INFO] Platform: Darwin-15.4.0-x86_64-i386-64bit
[INFO] PATH=/usr/local/bin/git:/Users/mark/bin:/usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin/mongodb/mongodb-osx-x86_64-2.0.6/bin:/Applications/apache-ant-1.9.4/bin:/Users/mrubin/Development/Android/sdk/tools:/Users/mrubin/Development/Android/sdk/platform-tools:/Users/mrubin/Development/Android/android-ndk-r10e:/Users/mrubin/.nvm/v0.10.21/bin:/usr/local/bin/git:/Users/mark/bin:/usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin/mongodb/mongodb-osx-x86_64-2.0.6/bin:/Applications/apache-ant-1.9.4/bin:/Users/mrubin/Development/Android/sdk/tools:/Users/mrubin/Development/Android/sdk/platform-tools:/Users/mrubin/Development/Android/android-ndk-r10e:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/mrubin/Development/apache-maven-3.2.3/bin:/Users/mrubin/Development/infer-osx-v0.2.0/infer/infer/bin:/Users/mrubin/Development/apache-maven-3.2.3/bin:/Users/mrubin/Development/infer-osx-v0.2.0/infer/infer/bin
[INFO] SHELL=/bin/sh
[INFO] PWD=/Users/mrubin/source/beamit-ios/app
[INFO] Xcode version:
Xcode 7.3
Build version 7D175

[INFO] clang version:
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Thanks for any help!

**Comment by jvillard** [comment]
hi @mbrubin56, the python error is bad, thanks for reporting. It's hiding the real issue, which in your case is that building failed.

Does the command `xcodebuild -workspace <my product>.xcworkspace -scheme <my scheme> -sdk iphonesimulator -configuration Debug build` succeed?

**Comment by dleyanlin** [comment]
same issues when and infer command in build command,if no add infer command build is succss.

thanks

**Comment by jvillard** [comment]
@dleyanlin, @mbrubin56, to debug further, I need the full output of the infer run. Can you paste it, eg to gist.github.com?

**Comment by foobra** [comment]
we have this problem too, we have chinese characters in the path and filename, will it break python script?

**Comment by jvillard** [comment]
@foobra can you paste the full output and infer-out/toplevel.log to gist.github.com or similar please?

**Comment by rocketnik** [comment]
I also ran into this issue with version 0.8.0 of infer. As another hint:
Try make your build work without infer on the command line first. for our project, the commands were:
xcodebuild  build  -workspace SomeProject.xcworkspace -scheme SomeProject-QA-Staging -configuration Release
infer -- xcodebuild  build  -workspace SomeProject.xcworkspace -scheme SomeProject-QA-Staging -configuration Release

**Comment by hujiachun** [comment]
@jvillard
infer-out/toplevel.log
  
 [INFO] Running command /usr/local/bin/infer -- xcodebuild -workspace /Users/hujiachun684/Downloads/PALifeApp-master/PALifeApp.xcworkspace -scheme PALifeApp -configuration Debug -sdk iphonesimulator
[INFO] Path to infer script /usr/local/bin/infer (/usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/infer)
[INFO] Infer version v0.8.0
Copyright 2009 - present Facebook. All Rights Reserved.


[INFO] Platform: Darwin-15.4.0-x86_64-i386-64bit
[INFO] PATH=/Users/hujiachun684/Downloads/oclint-0.10.2//bin:/Users/hujiachun684/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/hujiachun684/Library/Android/sdk/platform-tools:/Users/hujiachun684/Library/Android/sdk/tools:/Users/hujiachun684/.rvm/bin:/tools:/platform-tools:/bin:/Users/hujiachun684/appium:/usr/local/Cellar/maven/3.3.9/libexec/bin:/Users/hujiachun684/infer/infer/bin:/users/hujiachun684/downloads/infer-osx-v0.8.1/infer/bin
[INFO] SHELL=/bin/bash
[INFO] PWD=/Users/hujiachun684/Downloads/PALifeApp-master
[INFO] Xcode version:
Xcode 7.3
Build version 7D175

[INFO] clang version:
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
