### ISSUE TITLE
"RETAIN CYCLE" bug detection problem

### ISSUE THREAD

**Issue by ZiYouDeLaoGe** [facebook/infer#331]
Hello
"Infer" detected a bug - RETAIN CYCLE, I interrupted point "delloc" at the method, this method is to be performed, the memory can be released, but reported a bug - RETAIN CYCLE, my code is as follows :

`@interface NetworkRequestModel()`
`@property (nonatomic,weak) id child;`

`@implementation NetworkRequestModel`
`- (instancetype)init`
`{`
`    if (self = [super init]) {`
`      if ([self conformsToProtocol:@protocol(RequestModelProtocol)]) {`
`         self.child = self;`
`      }else{`
`         NSAssert(NO, @"Subclass must implement RequestModelProtocol");`
`      }`
`   }`
`   return self;`
`}`

Test results point to "self.child = self".
I modified child with weak property.
This is my problem? If this is how to solve, if not want to optimize "infer". Thank you.

**Comment by jvillard** [comment]
does infer still complain after you add `weak` to `child`?

**Comment by ZiYouDeLaoGe** [comment]
I modified with weak but infer give me feedback---"RETAIN CYCLE".

**Comment by ZiYouDeLaoGe** [comment]
你好，可以帮忙看看吗？

**Comment by dulmarod** [comment]
Can you give me more details about the class NetworkRequestModel and the protocol RequestModelProtocol? When I replaced them by empty class and protocol, I don't get the error, so I can't reproduce the bug.

**Comment by ZiYouDeLaoGe** [comment]
OK, you need a subclass inherits NetworkRequest Model, then the subclass must implement RequestModelProtocol, RequestModelProtocol can define any methods. Thanks!

**Comment by dulmarod** [comment]
Is NetworkRequestModel a standard library class? Where is it defined?

**Comment by ZiYouDeLaoGe** [comment]
It does not belong to the system library, you will be able to build a class!

**Comment by dulmarod** [comment]
I tried this code:

@interface NetworkRequestModel : NSObject
@end

@protocol P <NSObject>
@end

@interface NetworkRequestModel()<P>
@property (nonatomic,weak) id child;
@end

@implementation NetworkRequestModel
- (instancetype)init
{
    if (self = [super init]) {
        if ([self conformsToProtocol:@protocol(P)]) {
            self.child = self;
        }
    }
    return self;
}
@end

and I don't get the error. If you are able to send me a version of your code that compiles where the error happens, I will be able to reproduce it.
