### ISSUE TITLE
[system.err] fail to Infer scan on my private Android project

### ISSUE THREAD

**Issue by yitelu** [facebook/infer#332]
Hi FB infer team,
How are you doing? And thanks for such wonderful tool.

Wondering if you could help to take a look at what happened when i tried to infer scan my Android project?

I've installed the infer v0.8.0 on my local Ubuntu, and i've setup my environment properly by execute the infer scan on the examples folder's android_hello project, which shows the expected results of detected 3 errors.

But when i've infer scan my Android project that it would show lots [system.err] and did not generate inferTraceBugs report.

my steps: (Alone doing the clean then build could build correct without problem)
1. ./gradlew clean
2. infer -- ./gradlew build

please help to check the infer output log files and please let me know if there's any missing step.
Thanks so much :+1:

logs:
`ichardlu@richardlu-VirtualBox:~/.jenkins/jobs/PG2GIT$ ~/Downloads/infer-linux64-v0.8.0/infer/bin/infer -- ./gradlew build >> PG2-infer-result-0407.txt
15:10:22.221 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
15:10:22.234 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
15:10:22.235 [ERROR] [system.err] Note: /home/richardlu/.jenkins/jobs/PG2GIT/CMNowWeatherPanelSDK/src/main/java/com/cmnow/weather/utils/DimenUtils.java uses unchecked or unsafe operations.
15:10:22.241 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
15:10:49.202 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
15:10:49.203 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
15:10:49.203 [ERROR] [system.err] Note: /home/richardlu/.jenkins/jobs/PG2GIT/CMNowWeatherPanelSDK/src/main/java/com/cmnow/weather/utils/DimenUtils.java uses unchecked or unsafe operations.
15:10:49.204 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
15:12:01.284 [ERROR] [system.err] /home/richardlu/.jenkins/jobs/PG2GIT/app/src/main/java/com/cmcm/cmx/pagetwo/PDataController.java:196: warning: non-varargs call of varargs method with inexact argument type for last parameter;
15:12:01.291 [ERROR] [system.err]                                     PResult.RESULT_TIME_OUT, behavior, null));
15:12:01.298 [ERROR] [system.err]                                                                        ^
15:12:01.298 [ERROR] [system.err]   cast to Object for a varargs call
15:12:01.298 [ERROR] [system.err]   cast to Object[] for a non-varargs call and to suppress this warning
15:12:01.874 [ERROR] [system.err] /home/richardlu/.jenkins/jobs/PG2GIT/app/src/main/java/com/cmcm/cmx/pagetwo/news/NewsDataController.java:55: warning: non-varargs call of varargs method with inexact argument type for last parameter;
15:12:01.875 [ERROR] [system.err]             onRefreshComplete(new PResult(PResult.RESULT_NOT_SUPPORT, behavior, null));
15:12:01.876 [ERROR] [system.err]                                                                                 ^
15:12:01.877 [ERROR] [system.err]   cast to Object for a varargs call
15:12:01.878 [ERROR] [system.err]   cast to Object[] for a non-varargs call and to suppress this warning
15:12:01.909 [ERROR] [system.err] /home/richardlu/.jenkins/jobs/PG2GIT/app/src/main/java/com/cmcm/cmx/pagetwo/news/NewsDataController.java:213: warning: non-varargs call of varargs method with inexact argument type for last parameter;
15:12:01.912 [ERROR] [system.err]                             mBehavior, news));
15:12:01.912 [ERROR] [system.err]                                        ^
15:12:01.912 [ERROR] [system.err]   cast to Object for a varargs call
15:12:01.912 [ERROR] [system.err]   cast to Object[] for a non-varargs call and to suppress this warning
15:12:04.959 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
15:12:04.960 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
15:12:04.960 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
15:12:04.960 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
15:12:04.961 [ERROR] [system.err] 3 warnings
15:15:33.568 [ERROR] [system.err] /home/richardlu/.jenkins/jobs/PG2GIT/app/src/main/java/com/cmcm/cmx/pagetwo/PDataController.java:196: warning: non-varargs call of varargs method with inexact argument type for last parameter;
15:15:33.569 [ERROR] [system.err]                                     PResult.RESULT_TIME_OUT, behavior, null));
15:15:33.570 [ERROR] [system.err]                                                                        ^
15:15:33.570 [ERROR] [system.err]   cast to Object for a varargs call
15:15:33.571 [ERROR] [system.err]   cast to Object[] for a non-varargs call and to suppress this warning
15:15:33.885 [ERROR] [system.err] /home/richardlu/.jenkins/jobs/PG2GIT/app/src/main/java/com/cmcm/cmx/pagetwo/news/NewsDataController.java:55: warning: non-varargs call of varargs method with inexact argument type for last parameter;
15:15:33.888 [ERROR] [system.err]             onRefreshComplete(new PResult(PResult.RESULT_NOT_SUPPORT, behavior, null));
15:15:33.888 [ERROR] [system.err]                                                                                 ^
15:15:33.889 [ERROR] [system.err]   cast to Object for a varargs call
15:15:33.889 [ERROR] [system.err]   cast to Object[] for a non-varargs call and to suppress this warning
15:15:33.893 [ERROR] [system.err] /home/richardlu/.jenkins/jobs/PG2GIT/app/src/main/java/com/cmcm/cmx/pagetwo/news/NewsDataController.java:213: warning: non-varargs call of varargs method with inexact argument type for last parameter;
15:15:33.899 [ERROR] [system.err]                             mBehavior, news));
15:15:33.899 [ERROR] [system.err]                                        ^
15:15:33.899 [ERROR] [system.err]   cast to Object for a varargs call
15:15:33.899 [ERROR] [system.err]   cast to Object[] for a non-varargs call and to suppress this warning
15:15:36.500 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
15:15:36.511 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
15:15:36.511 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
15:15:36.512 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
15:15:36.512 [ERROR] [system.err] 3 warnings
`

**Comment by cctanfujun** [comment]
I use the infer for my android project i got this log.

```java

16:45:13.848 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:45:13.849 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:45:13.850 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
16:45:13.850 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
16:45:14.698 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:45:14.698 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:45:15.010 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
16:45:15.010 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
16:45:27.339 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:45:27.339 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:45:27.339 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
16:45:27.339 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
16:45:38.007 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:45:38.007 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:45:38.007 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
16:45:38.008 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
16:45:55.170 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:45:55.171 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:45:55.171 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
16:45:55.172 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
16:46:06.097 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:46:06.097 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:46:06.097 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
16:46:06.098 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
16:47:23.116 [ERROR] [com.android.build.gradle.internal.ApplicationTaskManager] warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.tencent.mm.sdk.openapi.WXApiImplV10$ActivityLifecycleCb$1) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.tencent.mm.sdk.openapi.WXApiImplV10$ActivityLifecycleCb$2) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.tencent.mm.sdk.b.b) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.

16:47:34.834 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:47:34.835 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:47:34.835 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
16:47:34.835 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
16:47:50.321 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:47:50.322 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:47:50.338 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
16:47:50.339 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
16:48:04.795 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:48:04.795 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:48:04.795 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
16:48:04.795 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
16:48:18.787 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:48:18.788 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:48:18.788 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
16:48:18.788 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
16:48:33.932 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:48:33.933 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:48:33.933 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
16:48:33.933 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
16:48:47.410 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:48:47.410 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:48:47.410 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
16:48:47.411 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
16:49:00.682 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:49:00.682 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:49:00.682 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
16:49:00.683 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
16:49:09.840 [ERROR] [org.gradle.api.Task] AAPT err(Facade for 1901593724) : No Delegate set : lost message:/Users/tanfujun/MEIZUCode/flyme5_dev/meizu/Cloud/Center/AppCenter/app/src/main/res/drawable-xxxhdpi/plugin_appdefault_ic_flyme.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
16:49:13.642 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:49:13.642 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:49:13.642 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
16:49:13.642 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
16:49:26.582 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:49:26.582 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:49:26.582 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
16:49:26.582 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
16:49:41.326 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:49:41.326 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:49:41.327 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
16:49:41.327 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.

```

Hope your help!

**Comment by cctanfujun** [comment]
i use  `infer -- ./gradlew compileDebugSources`  the infer worked. But I don't konw it is the same with `infer -- ./gradlew build`

**Comment by jvillard** [comment]
@cctanfujun you should use whatever command works to compile your project. `infer -- ./gradlew compileDebugSources` sounds like the right command for you.

@yitelu does `./gradlew build` work for you?

**Comment by yitelu** [comment]
@jvillard `./gradlew build` works on my project that i could build the apk without problem, but i don't know  why it can't generate the infer report....i've tried `./gradlew assembleDebug`, which responsed the same infer system err message

**Comment by yitelu** [comment]
@cctanfujun After some search, that I believes there's some limitation with FB infer, which not all of the gradle build variant could work, some build variant won't work with FB infer, so in your and my cases that we saw the system err....the best way is to try to find out which gradle build variant would work, you could type `gradlew task` which would list the build variant and hope there's one combination that would work XDD...close thread for now, thanks
