### ISSUE TITLE
Using infer for embedded software

### ISSUE THREAD

**Issue by DPastl** [facebook/infer#333]
Hello,

I'm attempting to use Infer to test an embedded project.  I know there are a number of null reference errors in the code, among other issues, but infer is not picking them up.  Since a large part of the code being run occurs only if an interrupt is generated, will this affect the ability of infer to test it correctly?  It's possible that the compiler is optimizing out large parts of the code simply because it appears unreachable in some way.

If I point infer at a single source file, other than the main.c file, will it analyse it correctly even if there is no main function?

Cheers,

David

**Comment by DPastl** [comment]
I suppose I should add that this is also an API that I'm trying to test: i.e. it does not attempt to exercise the entire code base as that is for the customer to use.

**Comment by sblackshear** [comment]
Hi David,
  Infer should analyze every file that is compiled regardless of whether functions in that file are called from elsewhere. How are you building the project?

**Comment by DPastl** [comment]
I'm currently just building if from the top level file, main.c, using clang:
infer -- clang -c main.c -I api -I app_sim -I app

**Comment by jberdine** [comment]
Infer will only analyze source files passed to clang during the process of executing the build command.  So for:

> infer -- clang -c main.c -I api -I app_sim -I app

only the functions defined in main.c will be analyzed.  Are the null dereference errors you mentioned in main.c, or elsewhere?

**Comment by DPastl** [comment]
They are in one of the sub files, tried running infer by pointing it to the subfile, but I didn't get my expected error (to be fair, almost no other tool shows the error).

**Comment by jberdine** [comment]
You can test that the function is being analyzed by inserting a bug infer should report, such as `int* p = NULL; *p = 42;`, and checking that this is indeed reported.

If that works, but the real issue isn't, is it possible to sanitize the code into something that can be shared with us?

**Comment by cristianoc** [comment]
@DPastl from this discussion I'm wondering whether you're calling Infer one file at a time. That won't find issues that involve calling from one file to another one. To get the latter functionality, you'll need to either use a Makefile, and a single invocation of e.g. `infer -- make`, or use a slightly different workflow:
```
infer -a capture -- clang -c file1.c
infer -a capture -- clang -c file2.c
infer -- analyze
```

**Comment by DPastl** [comment]
I was calling infer with one file at a time.  I tried the way you suggested @cristianoc but I'm still not seeing any errors.  I'm thinking that perhaps the issue is a little too difficult to find, it was originally pointed out to me by someone running klocwork.  It looks like great tool, it just might not be what we need.

**Comment by cristianoc** [comment]
Sorry for giving the wrong command line, I've edited it above. It was missing ```--reactive --continue```.
It might not make a difference, but that's the correct command line.
