### ISSUE TITLE
Issues reported in debug html file but not in console and report files

### ISSUE THREAD

**Issue by wouter89** [facebook/infer#340]
Command used:
``` infer --debug -- make ```

Output in console:
```
Analyzed 465 files

No issues found
```

But when looking at the debug information (.html file) for 1 of the files that was analyzed by Infer in  ```infer-out/captured/``` the following report was generated:

```
File <filename>.c
-------------------------------------------------------------------------------------------------
ERRORS DURING FOOTPRINT 
NULL_DEREFERENCE [B1] pointer twoIntsStructPointer last assigned on line 23 
could be null and is dereferenced at line 26, column 47 node4#session3( 26)
-------------------------------------------------------------------------------------------------
ERRORS DURING RE-EXECUTION
-------------------------------------------------------------------------------------------------
WARNINGS DURING FOOTPRINT 
ANALYSIS_STOPS exception: NULL_DEREFERENCE node4#session3( 26)
-------------------------------------------------------------------------------------------------
WARNINGS DURING RE-EXECUTION
-------------------------------------------------------------------------------------------------
INFOS DURING FOOTPRINT
-------------------------------------------------------------------------------------------------
INFOS DURING RE-EXECUTION
```

I confirmed there is a null dereference in this file, and before my upgrade to infer version v0.8.0, Infer reported this in the console and the debug html file. But, the debug html file also contained code. 

The code for the above report is:

```C
#include "std_testcase.h"

void nullPointerDerefBinaryIf()
{
    {
        twoIntsStruct *twoIntsStructPointer = NULL;
        /* FLAW: Using a single & in the if statement will cause both sides 
        of the expression to be evaluated thus causing a NPD */
        if ((twoIntsStructPointer != NULL) & (twoIntsStructPointer->intOne == 5))
        {
            printLine("intOne == 5");
        }
    }
}
```

When I look at the above report Infer does report a ''NULL_DEREFERENCE'', and at the right location. This should also be reported in the console I suspect? (The report.json and report.csv files are also empty, corresponding with the console output)

Infer version: v0.8.0
Operating System: OS X 10.11.4
Analyzed files: c and c++

**Comment by jvillard** [comment]
Thanks for the report! This looks like it could be a duplicate from #336 . You can verify this by trying the latest master, or inserting an instruction after the `if`.

**Comment by wouter89** [comment]
I tried adding a return statement (at multiple places) after the if statement but this doesn't solve the issue.

**Comment by wouter89** [comment]
I found the problem. It is related to an earlier issue #99.

A higher level folder that contained my source code contained a whitespace. After removing all the whitespaces from the folder inside and in the path of the project Infer analyzed the files correctly.

**Comment by jvillard** [comment]
Thanks @wouter89, I'm closing the issue as we're already tracking the whitespace issue in #99.
