### ISSUE TITLE
How to run  InferAnalyze binary correctly?

### ISSUE THREAD

**Issue by AliceTENGZI** [facebook/infer#342]
I dowmload Infer version 0.8.0 in https://github.com/facebook/infer/releases.
Then I run "tar xf infer-linux64-v0.8.0.tar.xz" in Linux.
(The version of Python is 2.7 )
I modify the PATH as follows:
cd infer-*v0\.\1\.0 &&
echo "export PATH=\"\$PATH:`pwd`/infer/infer/bin\"" \ >> ~/.bash_profile &&
source ~/.bash_profile

But I cannot run InferAnalyze binary.
What should I do if I want to use infer check my code.

**Comment by jvillard** [comment]
Hi @AliceTENGZI, these instructions are out of date, please follow this instead: http://fbinfer.com/docs/getting-started.html

On Linux you can use either Docker or build infer from source.

**Comment by AliceTENGZI** [comment]
I saw some dependences as follows:
Infer dependencies for Linux

Here are the prerequisites to be able to compile Infer on Linux. This is required to be able to use the release (faster), or to compile everything from source (see the end of this document).

opam >= 1.2.0
Python 2.7
Java (only needed for the Java analysis)
gcc >= 4.7.2 or clang >= 3.1 (only needed for the C/Objective-C analysis)
autoconf >= 2.63 and automake >= 1.11.1 (if building from git)。。。。

Are the all dependences required if I just want to analysing java code???

**Comment by jvillard** [comment]
Some of these dependencies are not needed for the java analysis: those marked "only needed for the C/Objective-C analysis". So what you need to build from a [release](https://github.com/facebook/infer/releases/) is:

- opam >= 1.2.0
- Python 2.7
- Java

**Comment by AliceTENGZI** [comment]
[@sjs_14_125 bianyuteng]# opam --version
1.2.2
[@sjs_14_125 bianyuteng]# python -V
Python 2.7.5
[@sjs_14_125 bianyuteng]# java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
[@sjs_14_125 infer-linux64-v0.8.0]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.2 (Santiago)

Above is my install enviroment.

But when I run "./build-infer.sh"
As follows the err information:

[@sjs_14_125 infer-linux64-v0.8.0]# ./build-infer.sh 
initializing opam... 
[WARNING] Running as root is not recommended
[ERROR] Initialisation failed
Fatal error:
Sys_error("No space left on device")
[WARNING] Running as root is not recommended
Checking for available remotes: [ERROR] Initialisation failed
Sys_error("No space left on device")
Fatal error:
Sys_error("No space left on device")

**Comment by jvillard** [comment]
> ` Sys_error("No space left on device") `

Your disk ran out of space.

**Comment by AliceTENGZI** [comment]
When I clean my disk for enough space.
and run "./build-infer.sh "..Error still exists as follows.

[@sjs_14_125 infer-0.8.0]# ./build-infer.sh 
initializing opam... 
[WARNING] Running as root is not recommended
[WARNING] Running as root is not recommended
preparing build... 
checking if we are in an Infer release build... no
checking whether to use the compilers in /search/bianyuteng/infer-0.8.0/facebook-clang-plugins/clang/bin... no
checking for shasum... shasum
checking for python2.7... python2.7
checking for xcode-select... no
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking for gawk... gawk
checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln -s works... yes
checking whether make sets $(MAKE)... yes
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -std=gnu++0x accepts -g... yes
checking if the C/C++ compiler is recent enough... no
configure: error:
Your C/C++ compiler seems to be too old to build clang, which is
required by the facebook-clang-plugins. Please install either
gcc version >= 4.7.2 or clang version >= 3.1.

See the output of `./configure --help` to force the use of a different
C compiler.

Alternatively, you can checkout a release of infer with clang
pre-compiled here:

  https://github.com/facebook/infer/releases/
