### ISSUE TITLE
fatal error: 'UIKit/UIKit.h' file not found

### ISSUE THREAD

**Issue by FridayAndHoliday** [facebook/infer#343]
I have the latest version of infer (0.8.0), but still occurred the  issue:
`elenadeMacBook-Pro:InferTest baidu$ infer -- clang -c ViewController.m
In file included from ViewController.m:9:
./ViewController.h:9:9: fatal error: 'UIKit/UIKit.h' file not found
#import <UIKit/UIKit.h>
        ^
1 error generated.`

how to fix it?

**Comment by jvillard** [comment]
You have to replace `clang -c ViewController.m` by a command that compiles `ViewController.m`. If this is an xcode project you should find the `xcodebuild` command that builds the whole project and run `infer -- <command>`. See [here](http://fbinfer.com/docs/analyzing-apps-or-projects.html) for more examples.
