### ISSUE TITLE
infer: command not found

### ISSUE THREAD

**Issue by Rexota** [facebook/infer#345]
When I try to run infer from any terminal or from android studio's terminal, I'm getting this error:

    infer: command not found

How can I solve this? I installed it with docker. Thanks.

**Comment by jvillard** [comment]
Hi @Rexota, the instructions for docker create an isolated container with infer in it, but it doesn't modify your local environment. When installing infer via docker, you need to perform your analysis from within the docker container. For example, here's how to run a Gradle-based project that builds with `./gradlew build`:

```sh
docker build -t infer .
docker run -v /path/to/gradle/project:/opt/project -it infer /bin/bash -c 'cd /opt/project/ && infer -- ./gradlew clean build'
```

You can edit that last command to adapt to your needs (eg to run `inferTraceBugs` after the analysis: `docker run -v /path/to/gradle/project:/opt/project -it infer /bin/bash -c 'cd /opt/project/ && infer -- ./gradlew clean build && inferTraceBugs'`).

If you need to install more dependencies into the docker image, you can either edit `Dockerfile` or jump inside the image, install whatever you need, then save it again:

```sh
$ docker run -it infer /bin/bash
root@<container id>:/workspace# apt-get install some-dependency
...
root@<container id>:/workspace# exit
$ docker commit <container id> infer
$ # now the image "infer" has some-dependency installed
$ docker run -v /path/to/gradle/project:/opt/project -it infer /bin/bash -c 'cd /opt/project/ && infer -- ./gradlew clean build'
```

Alternatively, you can make infer available in your system (not within docker) by [installing infer from source](http://fbinfer.com/docs/getting-started.html#install-from-source).

**Comment by Rexota** [comment]
Hey @jvillard, I'm new to docker thing and didn't know that. 

Thanks for your detailed response. Have a good day.

**Comment by Rexota** [comment]
Hey @jvillard , as you said it's an isolated container. So how can I access my project files from docker?

Because when I run this cmd from my project folder :
`sudo docker run infer /bin/bash -c 'infer -- ./gradlew build'`

It says :

```
Running and capturing gradle compilation...
Traceback (most recent call last):
  File "/infer/infer/bin/infer", line 178, in <module>
    main()
  File "/infer/infer/bin/infer", line 142, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/opt/infer-linux64-v0.8.0/infer/lib/python/inferlib/capture/gradle.py", line 87, in capture
    cmds = self.get_infer_commands(util.get_build_output(self.build_cmd))
  File "/opt/infer-linux64-v0.8.0/infer/lib/python/inferlib/capture/util.py", line 25, in get_build_output
    proc = subprocess.Popen(build_cmd, stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```

**Comment by tabishjaved03** [comment]
hey @Rexota ,

Any progress? i am getting the same error.

**Comment by Rexota** [comment]
As @jvillard said I tried to build infer from source.
http://fbinfer.com/docs/getting-started.html#install-from-source

I'll make it available for all system and "infer" command will be accessible from everywhere.

**Comment by jvillard** [comment]
The way to access your project from within the docker container is described in my previous comment: https://github.com/facebook/infer/issues/345#issuecomment-212886795

See also [the docker documentation about data volumes](https://docs.docker.com/engine/userguide/containers/dockervolumes/#mount-a-host-directory-as-a-data-volume).
