### ISSUE TITLE
v0.8.0 fails to compile on linux

### ISSUE THREAD

**Issue by rdtennent** [facebook/infer#346]
./build-infer.sh clang leads to

...
mkdir -p /home/rdt/src/infer-linux64-v0.8.0/infer/_build-infer
make[2]: *** No rule to make target `/home/rdt/src/infer-linux64-v0.8.0/facebook-clang-plugins/clang-ocaml/build/clang_ast.atd', needed by `clang/clang_ast_t.ml'.  Stop.

**Comment by jvillard** [comment]
can you paste the full output of `./build-infer.sh clang` please? use gist.github.com or similar

**Comment by rdtennent** [comment]
[build.txt](https://github.com/facebook/infer/files/229953/build.txt)

**Comment by jvillard** [comment]
Did you run `make clean` by any chance? That would mess up the release, unfortunately. You'll need to download the release tarball again if that's the case.

**Comment by rdtennent** [comment]
The output said:
compilation failure; you can try running

    make clean
    ./build-infer.sh clang
I presume I can re-use the tarball without re-downloading.

**Comment by jvillard** [comment]
Yes, I'll change `make clean` to not clean inside `facebook-clang-plugins/` if we're inside a release, thanks for the report!

**Comment by rdtennent** [comment]
After re-untaring the tarball, the compilation works. Thanks.  Please fix the compilation failure outpuit (or fix make clean!).

**Comment by AliceTENGZI** [comment]
How do you install opam(>=1.20) for linux ?

**Comment by jvillard** [comment]
@AliceTENGZI please post this in #342 instead. See [this section of the docs](https://github.com/facebook/infer/blob/master/INSTALL.md#setting-up-opam).
