### ISSUE TITLE
false positives because aborting function not recognized

### ISSUE THREAD

**Issue by rdtennent** [facebook/infer#347]
The following produces a false positive NULL_DEREFERENCE message because infer doesn't recognize that error(  ) aborts execution:

    t = strpbrk (s, "{}");
    if (t == NULL) error ("Expected '}'");
    if (*t == '{') ...

**Comment by jvillard** [comment]
Thanks for the report @rdtennent. Can you share the code of `error()`?

**Comment by rdtennent** [comment]
void
error (const char msg[])      /* abort with stderr message msg                        */
{
  if (lineno > 0)
    fprintf (stderr, "Error on line %d: %s\n", lineno, msg);
  else
    fprintf (stderr, "Error: %s\n", msg);
  exit (EXIT_FAILURE);
}

**Comment by jvillard** [comment]
I cannot reproduce the issue. Infer correctly realises that `error()` never returns and doesn't report on the following code:

```c
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

static int lineno;

void
error (const char msg[])      /* abort with stderr message msg                        */
{
  if (lineno > 0)
    fprintf (stderr, "Error on line %d: %s\n", lineno, msg);
  else
    fprintf (stderr, "Error: %s\n", msg);
  exit (1);
}

void foo(const char s[]) {
  char *t = strpbrk (s, "{}");
  if (t == NULL) error ("Expected '}'");
  if (*t == '{') { return; }
}
```

How are you calling infer? Are the files where infer reports and the file that defines `error()` compiled in the same command?

**Comment by rdtennent** [comment]
The file that defines error() is in another file previously analyzed by infer.  How do I call infer with multiple file arguments?

**Comment by rdtennent** [comment]
OK.  infer -- gcc -c  files works.  Thanks.

**Comment by jvillard** [comment]
Yes, if you have a command that compiles your whole project at once, you can just use `infer -- <command>`.

Otherwise, you can also do something like this:

```shell
infer -a capture --reactive -- clang -c file_1.c
infer -a capture --reactive -- clang -c file_2.c
....
infer -a capture --reactive -- clang -c file_n.c
infer -- analyze
```

Each `infer -a capture --reactive -- clang -c file_i.c` will translate `file_i.c` into infer's internal language. Then `infer -- analyze` will analyze all the procedures captured so far at once.

**Comment by rdtennent** [comment]
When I do  
infer -- gcc -c files
I get the message "Analyzed 0 files" followed by "No issues found", even if I add an issue that _should _be found.  Yet gcc -c files works. Doesn't seem right.

**Comment by jvillard** [comment]
`infer -- gcc -c <files>` isn't supported, unfortunately. For now you have to either write a short Makefile or other for your project, or use the method outlined above to do individual capture of each C file.

**Comment by jvillard** [comment]
Just FYI Infer now supports gcc/clang commands that involve multiple source files: 596823bd32cc8e21bb9fde8de9a88260b4dca7e1.
