### ISSUE TITLE
Is Infer support for java 1.8? 

### ISSUE THREAD

**Issue by AliceTENGZI** [facebook/infer#348]
[@sjs_14_125 bianyuteng]# java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
[@sjs_14_125 infer-linux64-v0.8.0]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.2 (Santiago)

Can infer analyze java code on environment above?

**Comment by jvillard** [comment]
yes, that shouldn't be an issue.

**Comment by jvillard** [comment]
Please reopen if you have a concrete problem with this configuration that we can look at.

**Comment by AliceTENGZI** [comment]
OK  I will  Thanks.~
