### ISSUE TITLE
Infer unable to find project root in docker container

### ISSUE THREAD

**Issue by tabishjaved03** [facebook/infer#349]
I am using infer on Ubuntu 14.04(TLS) via docker. I execute the provided run.sh and  docker container opens up. 
I am able to run  java and android_hello example. But when i provide my project root, it does not find any class to compile. Could you please answer my below query:

1) How to access external files from inside the docker container?
2) Is it possible to install infer via linuxbrew?

 I am new to docker, any help is appreciated.

**Comment by jvillard** [comment]
1. see https://github.com/facebook/infer/issues/345#issuecomment-212886795
2. there is no linuxbrew recipe for infer as of yet. You can always [build infer from source](http://fbinfer.com/docs/getting-started.html#install-from-source)

**Comment by tabishjaved03** [comment]
Thanks for your help @jvillard . Closing the issue, I ran infer from source.
