### ISSUE TITLE
get opam failed(can I skip curl if I download it by myself)

### ISSUE THREAD

**Issue by chen881129** [facebook/infer#351]
Step 5 failed:
The command '/bin/sh -c VERSION=1.2.2;     curl -sL       https://github.com/ocaml/opam/releases/download/$VERSION/opam-$VERSION-x86_64-Linux       -o /usr/local/bin/opam &&     chmod 755 /usr/local/bin/opam &&     ((/usr/local/bin/opam --version | grep -q $VERSION) ||      (echo "failed to download opam from GitHub."; exit 1))' returned a non-zero code: 35

Then I get "https://github.com/ocaml/opam/releases/download/1.2.2/opam-1.2.2-x86_64-Linux" manuallly(include rename && chmod 755):
/usr/local/bin/opam --version
1.2.2

Can I skip the curl step?

**Comment by chen881129** [comment]
I find the Dockerfile and alter it, I'm doing the next command(also get an error with the run.sh....do it manuallly), good luck to me

**Comment by jvillard** [comment]
Hi @chen881129, did you solve your problem? Is there an issue with the Dockerfile?

**Comment by chen881129** [comment]
Thanks a lot, it's solved :)
