### ISSUE TITLE
Can infer analyze java project?

### ISSUE THREAD

**Issue by AliceTENGZI** [facebook/infer#352]
http://ios.jobbole.com/84371/
Some code errors occur  when I use Infer analyze java project from article above.
Is resolved this issue that infer cannot analyze java project?

**Comment by jvillard** [comment]
Hi @AliceTENGZI, Infer works with Java projects too.

What's the Java project you have issues with? What error do you get?

**Comment by jvillard** [comment]
please re-open with more information
