### ISSUE TITLE
infer doesn't report potential NPE on a field initialised via an XML file

### ISSUE THREAD

**Issue by chen881129** [facebook/infer#353]
package src;
import src.*;
public class Test{
    public static void main(String[] args){
            A a = new A();
            String s = a.id;
            s.length();
    }   
}

Here s maybe a nullpointer.
But infer said "No issues found"

**Comment by jvillard** [comment]
- What is the code of class `A`?
- What command did you use to run infer?
- What version of infer are you using?
- Can you paste the full output?

Thanks!

**Comment by chen881129** [comment]
Sorry for my mistake. I got the result because I didn't clean my .class files.

But it really dosn't work when I check my java project,  the code is like this:

String docvrid = doc.getClassid();
if (! docvrid.equals("10000103")) {
 ...
}

doc.classid is a private member and initialized from a xml in the constructed function, but [classid] in the xml maybe null. So, the code 'docvrid.equals("10000103")' maybe call a NullPointerException.

The version of infer I'm using is 0.8.0.
The command I ran infer is `infer -- ant`.

**Comment by jeremydubreil** [comment]
Hi @chen881129. Infer does not parse the xml files, so the information whether `doc.getClassid()` may  return `null` is not known. In this case, Infer will make optimistic assumptions about the code. Here, `docvrid` being dereferenced in `docvrid.equals(...)`, Infer will assumes that `docvrid != null`. If you know that `docvrid` can be null, you can annotate the code accordingly:
```java
@Nullable String docvrid = doc.getClassid();
```
And Infer will then make the opposite assumption: `docvrid` will be considered as potentially `null` unless there is enough information to state otherwise. For instance:
```java
  if (docvrid != null && !docvrid.equals("10000103")) {
   ...
  }
```

**Comment by chen881129** [comment]
Hello @jeremydubreil, very nice to receive your message.
You are right that Infer dose not know `docvrid` is null. Actually `docvrid` is not always null, it's potentially null. So, `docvrid != null && !docvrid.equals("10000103")` will be safe and `docvrid.equals("10000103")` without `docvrid != null` is dangerous.

In my opinion the dangerous code should be print. Can Infer print the potentially NullPointerException?

**Comment by jeremydubreil** [comment]
In theory, Infer could report every time there is not enough information to prove that a variable being dereference is not null. But in practice, this will generate way too many reports and make the tool unusable.

**Comment by sblackshear** [comment]
If you want more demonic behavior w.r.t nullability, you might want to give eradicate a try (`infer -a eradicate -- <your_compile_command>`). Eradicate requires more annotations than Infer, but is also more exhaustive in reporting NPE warnings.

**Comment by sblackshear** [comment]
Check out my answer to https://github.com/facebook/infer/issues/383 to see another way to make Infer's NPE reporting more aggressive.
