### ISSUE TITLE
RESOURCE_LEAK rule

### ISSUE THREAD

**Issue by wisenight** [facebook/infer#356]
Dear sir

We write a tool class to close Closable item, like below

public class CloseUtils {
    public static close(Closable closable) {
        try {
            if (closable != null) {
                closable.close();
            }
        } catch (Exception e) {
        }
    }
}

But Infer still tell us we have res leak when we use this class to close item. Is there any way to change the rule? If we use this tool class to close item, Infer won't display this issue.

**Comment by jeremydubreil** [comment]
Hi @wisenight. Thanks for reporting this. We are currently working on solving this case, which is more tricky than it looks because of dynamic dispatch. 

Keeping the issue open for now and will update it when this case is fully supported.

**Comment by jeremydubreil** [comment]
@wisenight : Infer should now support this case involving resolution of dynamic dispatch. Is the issue still there?

**Comment by jeremydubreil** [comment]
This should normally be solved, closing the task. @wisenight, feel free to re-open if you still observe the same issue.
