### ISSUE TITLE
infer can't  Ignore third party library scanning

### ISSUE THREAD

**Issue by Hellengo** [facebook/infer#357]
if run：
infer --pmd-xml -- xcodebuild -workspace Vodka.xcworkspace -scheme Vodka 

will analysis all files including Pods , but  i want to analysis my project files ,can i add some parameter  to  Ignore third party library?

**Comment by jvillard** [comment]
Thanks for your question, there is a hole in our documentation currently. This has been answered on #364, please report there if that doesn't work for you.
