### ISSUE TITLE
Using Infer for Technical-Debt calculation?

### ISSUE THREAD

**Issue by waqas716** [facebook/infer#359]
Infer is really great tool, I tried it for Android projects and was impressed by its detection of Context leaks, although it was a false positive [will upload the scenario with example] but was helpful to see that wrong parameter can cause problems.

I am doing master thesis at RWTH university Aachen, I need to develop a tool which will detect code smells / bad code design to determine and quantify Technical Debt. After initial research about existing platforms and tools I shortlisted two to compare and select one as a base. One is of course Infer and other is MOOSE [http://moosetechnology.org]

I wanted to know what do you think about me extending Infer platform by using existing infer AST and CHECKERS etc to crawl code repositories to determine Design flaws instead of bugs. And adding functionality or additional Checkers per say which can determine Technical Debt. Does current Infer stack give enough information about the code structure to determine different design flaws like, Deep Inheritance hierarchies , Feature Envy, Brain Method, Brain Class, Significant duplication etc.

I know I won’t get APIs or method calls which will just return me required information( that will be my job to develop these though) but just wanted to know before going deep into it, if it sounds like a good idea to someone who knows all in/outs of Infer already. Your feedback will be much appreciated.

**Comment by sblackshear** [comment]
Infer would likely be suitable for this. I don't know enough about the code smells you mention to know which ones will be easy vs hard, but if all you need is to look at the CFG/class hierarchy then Infer is good for that (and will work with multiple languages!).

You'd probably want to implement your each code smell analyses as a separate checker. Simple ones can just iterate over the CFG, and fancier ones that need dataflow information/interprocedural analysis can use the checkers abstract interpretation framework,

Let me know if you have any more questions or need some more specific pointers!

**Comment by sblackshear** [comment]
Closing for now, feel free to reopen or file a new issue if you have another question.
