### ISSUE TITLE
Failed to load any Java source code during parallelized build.

### ISSUE THREAD

**Issue by clonetwin26** [facebook/infer#360]
I think the the infer runs aren't thread safe. When I run to runs on the same project concurrently, one of the jobs fails to load source.

**Comment by jeremydubreil** [comment]
I am trying to understand the problem you are facing. Is the issue that you are running:

  in shell1 my/project/sources > infer -o out1 -- <build command>

and

  in shell2 my/project/sources > infer -o out2 -- <build command>

and then the second command does not load any source files ?

**Comment by clonetwin26** [comment]
Yeah. Thats it.

**Comment by jeremydubreil** [comment]
Assuming that the build command can run concurrently on the same project ? For instance:

in shell1:
   `my/project/sources > gradle build`

and in shell2:
   `my/project/sources > gradle build`

Then the files that are compiled in one of the shell will not be recompiled in the other shell. And Infer will only analyze the files that are compiled during the build.

What is the objective of running Infer concurrently on the same project ?

**Comment by sblackshear** [comment]
I could see why you would want to run Infer concurrently on the same project. For example, you might want to get results from both Infer and Eradicate. 

I don't think we have a good story for how to do this right now, though. Would be nice to have.

**Comment by clonetwin26** [comment]
Ill keep trying to get it right on my end. The big interest here is to run it as part of a big parallelized build system. Where one box could be running against two diffs off the same project at the same time.

**Comment by jeremydubreil** [comment]
This is a very interesting use case. Does it also fail if you specify two different output directories ? For instance:

`shell 1 > infer --out out1 ...`
and:
`shell 2 > infer --out out2 ...`

However, I am not sure I understand the situation very well. How can the "normal" build run two different builds on two different commits in the same directory ? If in two different directories, there should be no conflict normally.

Also, just to double check, the `Failed to load any Java source code` issue could actually come from something else. Which version of javac are you using ?

**Comment by jvillard** [comment]
There are ways to support this use-case currently but it's hard to help without knowing more about the build system. One way is to use something like this:

```sh
infer run --force-integration make -- <your build system command>
```

Please re-open if there are further issues with this approach.
