### ISSUE TITLE
Unable to run self implemented checker

### ISSUE THREAD

**Issue by jmtiong** [facebook/infer#362]
Greetings, I am sorry as I do not know where to post this, however, after I followed the instructions on fbinfer (Adding checkers), it did not run/detect at all? Am I doing something wrong? And I could not find any registerCheckers.mli anywhere hence I place the code for registerCheckers.mli into registerChecker.ml

**Comment by jmtiong** [comment]
UPDATE: If I explicitly run `infer -a checkers -- javac Hello.java`, the implemented my_simple_checker will run. If the command `infer -- javac Hello.java` is ran, it seems that the checkers module did not run. Any idea or more details of how infer works?

**Comment by jvillard** [comment]
This is the intended way to run checkers. If you don't specify a value for the `-a` option then by default it selects `-a infer`.

**Comment by jvillard** [comment]
Closing for now, let me now if you have any more questions about implementing your checker!

**Comment by jmtiong** [comment]
Understood, thank you for your help!
