### ISSUE TITLE
Does infer detect an array out of bounds error?

### ISSUE THREAD

**Issue by Mahmohsen** [facebook/infer#363]
For example, would infer raise any errors with the following code:

int max(int *arr, int n)
{
    int i = 0; 
    int Result = arr[i];
    while (n > i)
    {    	
  	i = i + 1;
        if (Result <= arr[i])
            Result = arr[i];
    }
    return Result;
}

**Comment by jvillard** [comment]
Infer doesn't report any array bounds error as of yet, but that's something we are looking to improve.

For reference, you can look at the [list of bug types Infer currently reports](http://fbinfer.com/docs/infer-bug-types.html), and array bounds errors are in the [list of bug types Infer currently doesn't report](http://fbinfer.com/docs/limitations.html#bugtypes).
