### ISSUE TITLE
How to include project folders or exclude dependency folders during analysis of iOS project?

### ISSUE THREAD

**Issue by tvsathish** [facebook/infer#364]
How to include project folders or exclude dependency folders during analysis of iOS project? I have a big project in which there are lots of dependencies. I do not need to analyze them as it is out of scope and adds to the time infer takes to analyze the project. Is there a way to specify only project-specific folders or exclude unwanted folders during analysis? 

Also how to speed up the analysis phase?

**Comment by akotulski** [comment]
> How to include project folders or exclude dependency folders during analysis of iOS project? I

Yes, there is a way to exclude certain directories. I'll illustrate it by example let me know if it works for you.
If your use case is different/more complex let me know as well.

Let's say I have a project with following directory structure.
```
<ROOT>
  - <Lib> // libraries that your project depends on.
    - <ExternalDeps> // you want to skip analyzing those
    - <InternalLibs> // you want to analyze those
  - <Src> // implementation of your project 
  - <Headers> // headers of your project
  - <Docs> // irrelevant
```

We have a way of providing extra information to guide the analyzer by .inferconfig file (it's in json format)

Step 1:
Create .inferconfig file (name is important) in <ROOT> directory

Step 2:
Add entry for `skip-clang-analysis-in-path` with list of all paths relative to <ROOT>.
.inferconfig file should look like this:
```
{
    "skip-clang-analysis-in-path": [
        "Lib/ExternalDeps"
    ]
}
```

Step 3:
Run infer from <ROOT> directory (it's important for infer to find .inferconfig file there). If you have to run infer from different directory, you have pass `--project-root` flag to your infer invocation. And that's all.


> Also how to speed up the analysis phase?

By excluding certain directories, we skip analyzing them at all which should speed up the whole analysis process. 
If you want to see reports in the code that you just changed, you can follow differential workflow described [here](http://fbinfer.com/docs/infer-workflow.html). It's much faster, but won't report problems in whole codebase.

**Comment by akotulski** [comment]
Unfortunately, this feature is fairly new (implemented last week in https://github.com/facebook/infer/commit/83e6ab1a20e0ece09bf1c965513d5ebf0026905f) so you'll have to use infer from master. Last release of infer `0.8.1` doesn't have it.

**Comment by alexmx** [comment]
It would be great to have the possibility to exclude some directories by passing some args (e.g. `-e and --exclude`) to command line like `infer -e 'Pods' -e 'Libs' -- xcodebuild ...` without creating an .inferconfig file.

**Comment by jvillard** [comment]
This is in-progress but definitely planned. It works even now if you pass arguments via the `INFER_ARGS` environment variable (options are separated using `^`). The `--skip-clang-analysis-in-path` option expects a json array as argument, so you would write for instance:

```
INFER_ARGS="--skip-clang-analysis-in-path^[\"Pods\",\"Libs\"]" infer -- xcodebuild ...
```

**Comment by jvillard** [comment]
(you have to use infer from master, it's not in 0.8.1)

**Comment by jvillard** [comment]
Hopefully this is enough information to achieve what you wanted, please re-open if there is an issue.
