### ISSUE TITLE
Infer on IOS Application

### ISSUE THREAD

**Issue by meghanapatlolla** [facebook/infer#366]
hi there,

i am facing issues integrating Infer with IOS applications , it always complains about missing the header files like "ICAnalyticsController.h" 

Logs with error:
**ApplicationName-Prefix.pch:15:9: fatal error: 
      'ICAnalyticsController.h' file not found
#import "ICAnalyticsController.h"**

Things observed on Xcode:

1. when i go to ApplicationName-Prefix.pch file 
No error observed, already imported"ICAnalyticsController.h header 
2. Xcode also builds the app with no issues

Is that infer depends on this file??? if so what to do ???

**Comment by meghanapatlolla** [comment]
Above is solved and now i see ICAdjustSDKTrackingController.h is not found. Can anyone please me  help with all the dependent libraries for Infer to run on IOS

**Comment by akotulski** [comment]
Could you provide command that you used?
Does the build command by itself succeed?

**Comment by meghanapatlolla** [comment]
command used : infer -- xcodebuild -target ApplicationName -configuration Debug -sdk iphonesimulator

**Comment by meghanapatlolla** [comment]
Build fails with exception , saying some header files are missing . So it would be helpful if you could help me with , header files that infer is dependent on

like
ICLog.h
IC+NSString.h......

**Comment by jvillard** [comment]
Infer shouldn't depend on any more files than your project. Does `xcodebuild -target ApplicationName -configuration Debug -sdk iphonesimulator` succeed on its own, without `infer -- `?

**Comment by meghanapatlolla** [comment]
Build fails with "xcodebuild -target ApplicationName -configuration Debug -sdk iphonesimulator" too

**Comment by jvillard** [comment]
Infer needs a working compilation command. You should find the right way to compile your project from the command line, then run `infer -- <that command>`. Let me know if you have more issues with this, closing for now.
