### ISSUE TITLE
Analyzing tainted variables

### ISSUE THREAD

**Issue by jmtiong** [facebook/infer#367]
Hi everyone! Are there any guides or documentations that I can read on how FBinfer performs checks on tainted variables that I can learn from and hopefully contribute back to the site. 

Thank you very much!

**Comment by tabishjaved03** [comment]
+1

I would love to know more too. It shows that some db variables are reaching sensitive functions. But which db variables are flagged and which are not isn't clear. A little more information can help me getting these issues fixed by developers. Clearly, this category is very important from security context. A little help from the community in understanding these issues, would go a long way.

Thanks everyone!

**Comment by sblackshear** [comment]
The taint analysis is an experimental feature that's still under development, but I can share a few details on what it can do now.

- The taint checks Infer does fall into two categories: security and privacy. Security checks ensure that user-controlled input does not flow to sensitive functions, and privacy checks ensure that sensitive user data does not escape to the outside.

- There are a few built in taint checks in the open-source version of Infer (most notably, the SSL hostname verification check), but you can also specify your own sources and sinks using the [`PrivacySource`](https://github.com/facebook/infer/blob/master/infer/annotations/com/facebook/infer/annotation/PrivacySource.java), `PrivacySink`, `IntegritySource`, and `IntegritySink` annotations. Once you add these annotations, Infer will report source-sink flows between the annotations.

- At the theoretical level, the taint analysis works using the same bi-abduction technique that Infer uses to compute function pre and postconditions. When the analysis encounters a taint sink, it generates a proof obligation that flows into that sink are untainted, and it propagates that proof obligation into the precondition. When applying that precondition at a call site where the precondition cannot be met, Infer will report a warning.

**Comment by jmtiong** [comment]
@sblackshear Thank you very much for your reply! Just one clarification for 

> Once you add these annotations, Infer will report source-sink flows between the annotations.

Does it mean I do not need to change anything on the OCaml code? Or in the OCaml code I have to do some changes as well?

Right now I am trying to implement a checker that will detect the tainted variables that was brought over from one function to another function.

**Comment by jmtiong** [comment]
![Image of checker]
(http://i.imgur.com/Dpq07Nv.png)
Like from the above image, inside one of my function it will call AsyncTask.get() which will return an object, 
and the checker's code to identify the AsyncTask.get is

    let do_instr node = function
        | Sil.Call (_, Sil.Const (Sil.Cfun pn), _, loc, _) when 
              Procname.java_async_method pn ->
            (* How may I continue from here to get the returned variable 
             from async which is a File Object and access it at the box in green*)
        | _ -> () in
    Cfg.Procdesc.iter_instrs do_instr proc_desc

**Comment by sblackshear** [comment]
The functionality for propagating tainted sources to tainted sinks lives in the main bi-abduction analysis, so you won't be able to leverage it from a custom checker.

I don't fully understand what you are trying to do with your checker, but if you explain a bit more I can try to help.

**Comment by jmtiong** [comment]
I would like to implement a checker such that it is able to detect programs that attempt to download files over the internet and perform operations (e.g. unzipping or executing) with the files that have been downloaded. 

Hence the thoughts of utilizing and tracking tainted variables would be very useful to detect such patterns.

**Comment by sblackshear** [comment]
If you want to implement such a checker from scratch, Infer's abstract interpretation framework for checkers would be quite suitable for this. See `liveness.ml` for an example of a simple AbsInt checker and `annotationReachability.ml` for an example of a more advanced one.

However, if you want to take advantage of Infer's builtin capabilities for propagating taint, you'll have to build your checker on top of the core bi-abduction algorithm. This would probably be simpler; you should just need to add the methods you care about as sources and sinks. See `inferTaint.ml` for examples of how to to this.

**Comment by jmtiong** [comment]
Thank you very much, I will go take a closer look at these files, by the way, has `inferTaint.ml` been renamed? I could not find it in the current sources.

**Comment by sblackshear** [comment]
Sorry, I meant `taint.ml`.

You need to include the android JAR and Infer annotations JAR to compile this file. You can take a look at the BUCK file that runs the test to see the compilation command that is used.

**Comment by sblackshear** [comment]
Closing for now; please feel free to open a new issue if you have additional questions.

**Comment by computereasy** [comment]
Hello! Just a quick question, is it feasible to use `taint analysis` engine of Infer at this point?
