### ISSUE TITLE
False positive on telescoping constructors

### ISSUE THREAD

**Issue by clonetwin26** [facebook/infer#368]
When running infer I get the following error when trying to telescope my constructors.

src/main/java/Controller.java:60: error: NULL_DEREFERENCE
  object null could be null and is dereferenced by call to Controller(...) at line 60
1.               @NonNull Source source,
2.               @NonNull Type type) {
3. >         this(activity, config, listener, summary, source, type, null);
4.       }
5.   
6.   

The null here is passed into a @Nullable parameter in another constructor. Here null isn't actually dereferenced.

**Comment by jeremydubreil** [comment]
Unfortunately, it is hard to tell what is happening without more context about the definition of `Controler`. If I understood correctly, the constructor is of the form: 

  `Controller(..., @Nullable Object obj) { ...}`

where `obj` is not being dereference without a check for `null` inside the body of `Controler`. If that was the case, then the NPE would be reported in the body of `Controler`, not when calling the constructor with `null` somewhere else.

Would you be able to reproduce the issue on a small toy example ?

**Comment by jvillard** [comment]
Please reopen with more details if you can.
