### ISSUE TITLE
Decrease the infer-build time: how can i do?

### ISSUE THREAD

**Issue by GeekMin** [facebook/infer#369]
hey,
   Infer now using infer-capture-build: 
1. ant -v
2. match "javac“
3. etc.
  so, the whole infer-build time is： original ant build time + infer-build time...
Here, If I want to get the ant building command, but not running the really building, i.e dry-run mode 
How can I do? If infer do not built-in supported, How can i do?

**Comment by sblackshear** [comment]
The only way to make it faster would be writing an ant plugin for Infer like the Gradle [plugin](https://github.com/uber-common/infer-plugin) Uber recently contributed. This would be a very welcome contribution if you are up to it!
