### ISSUE TITLE
Variables for fast enumerations in Objective-C are marked as UNINITIALIZED_VALUE

### ISSUE THREAD

**Issue by alexmx** [facebook/infer#370]
When using a fast enumeration in Objective-C, variables are marked as UNINITIALIZED_VALUE warnings.

For instance for current piece of code:
```objective-c
for (UILabel *label in someLabels) {
    label.text = @"some text";
}
```

we get the warning:
`UNINITIALIZED_VALUE
  value label was not initialized after declaration and is used at line xx, column xx`

Kind regards,
Alex.

**Comment by jvillard** [comment]
Thanks for the report @alexmx! I cannot reproduce this issue locally. Can you give me a full example? Also, which version of Infer are you using?

**Comment by alexmx** [comment]
Thanks @jvillard for taking a look at this.
I'm using Infer version v0.8.1

I was able to reproduce it for attached project example.
[InferBugExample.zip](https://github.com/facebook/infer/files/284377/InferBugExample.zip)

I'm running the following command:
`infer -a checkers -a capture -a compile -a infer -a tracing -- xcodebuild -scheme InferBugExample -configuration Debug -sdk iphonesimulator`

By the way, is there an option to run infer with all analyzers without listing them separately?

**Comment by jvillard** [comment]
Specifying multiple analyzers on the command line simply selects the last one, so your command only runs the experimental "tracing mode" analyzer (which is not meant to be run by users). There is no direct way to run all available analyzers right now. One simple way is to do the following:

```sh
infer -a capture -- xcodebuild ...
infer -a infer -- analyze
infer -a checkers -- analyze
```

(From your example command-line, I'm assuming you want to run "infer" and "checkers", but not "eradicate". "compile" only runs the compilation command, and "capture" [translates your source files into Infer's intermediate representation](http://fbinfer.com/docs/infer-workflow.html).)

**Comment by alexmx** [comment]
Ok, got it. Thanks @jvillard.

I was confused by the output of help command `infer -h:`
`-a ANALYZER, --analyzer ANALYZER
                        Select the analyzer within: capture, checkers,
                        compile, eradicate, infer, tracing`

So I listed all of them, except eradicate which is for Android projects.

I assume that this issue can be closed as I'm not getting this issue after running:
```
infer -a capture -- xcodebuild ...
infer -a infer -- analyze
infer -a checkers -- analyze
```

P.S. I would be cool to be able to merge the results of the analyzers in one final report.

**Comment by jvillard** [comment]
Yes the help on that option is not very... helpful. I'll see if I can come up with a better message.

re: merging: I think eventually we'd like to be able to run several analyzers at the same time, in the way you assumed was working already (eg `infer -a checkers -a infer -- analyze`).
