### ISSUE TITLE
How to extend it to Javascript

### ISSUE THREAD

**Issue by bitliner** [facebook/infer#372]
I hope this is the right place to ask such question.

I was wondering:
- is there any documentation that explains how to extend Infer to other programming languages or to add rules to "infer more"?
- is Flow the Infer implementation for Javascript ?

**Comment by jeremydubreil** [comment]
Flow and Infer are two unrelated projects. 

There is no generic documentation describing precisely how to extend Infer to a new languages. Basically, what needs to be done is to trans-compile the input source code into the Infer intermediate representation. The [Infer IR](https://github.com/facebook/infer/tree/master/infer/src/IR) is a low level description of types, expressions, instructions and control flow. The code of the intermediate representation is written in [Reason](https://facebook.github.io/reason/) which has a syntax close to Javascript. Reading the documentations of the `.rei` files, example: [Sil.rei](https://github.com/facebook/infer/blob/master/infer/src/IR/Sil.rei) is a good way to understand how to write a new frontend.

There is currently one frontend for [Java](https://github.com/facebook/infer/tree/master/infer/src/java) and one for [Clang](https://github.com/facebook/infer/tree/master/infer/src/clang). They can be used ass input examples.

Just for curiosity, what kind of issues are you interested to detect with Infer in Javascript code ?

**Comment by bitliner** [comment]
@jeremydubreil thanks for your answer.

I am interested in detecting common issues that usual common static analyzers (e.g. jshint) do not detect, like undefined methods.

I was curious to understand more how Infer works. Because usually I have had problem using Flow (not so easy to get started with it the way I would like to), and I am still trying to set up Reason (that would be my favorite choice I think).

**Comment by jvillard** [comment]
The questions in the issue have been resolved, closing.
