### ISSUE TITLE
False positive CHECKERS_DEAD_CODE in places where NSStringFromClass foundation function is used

### ISSUE THREAD

**Issue by alexmx** [facebook/infer#373]
Infer version v0.8.1

Run command: `infer -a checkers -- xcodebuild -scheme InferBugExample -configuration Debug -sdk iphonesimulator`

Sample project:
[InferBugExample.zip](https://github.com/facebook/infer/files/286561/InferBugExample.zip)

The following code examples are marked as CHECKERS_DEAD_CODE warnings even though they are valid pieces of code:
```objective-c
    for (int i = 0; i < 2; i++) {
        Class viewClass = (i) ? [UITableViewCell class] : [UIView class];
        NSLog(@"Class name: %@", NSStringFromClass(viewClass));
    }
```

Infer output: 
```objective-c
InferBugExample/ViewController.m:19: error: CHECKERS_DEAD_CODE
  Node not visited: 11
  17.       for (int i = 0; i < 3; i++) {
  18.
  19. >         Class viewClass = (i) ? [UITableViewCell class] : [UIView class];
  20.           NSLog(@"Class name: %@", NSStringFromClass(viewClass));
  21.       }
  22.
```

Another example:
```objective-c
InferBugExample/main.m:13: error: CHECKERS_DEAD_CODE
  Node not visited: 3
  11.
  12.   int main(int argc, char * argv[]) {
  13. >     @autoreleasepool {
  14.           return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class]));
  15.       }
```

It seems that Infer marks all the code snippets where NSStringFromClass foundation function is used as CHECKERS_DEAD_CODE.

Kind regards,
Alex.

**Comment by alexmx** [comment]
Has anyone seen this ticket? 😄 
I would appreciate any feedback on it.
Thank you.

**Comment by jvillard** [comment]
Thanks for the report @alexmx. That's definitely an issue with the dead code checker. To be honest I think we'd be better off just not running that checker by default since no-one actively maintains it anymore.

**Comment by alexmx** [comment]
Thanks @jvillard.

How can I exclude this particular dead code checker when running `infer -a checkers ...` command?
Or you meant that I should avoid using `checkers` analyzer?

Cheers.

**Comment by jvillard** [comment]
The clang checkers should all be disabled by default, we'll fix that. There are some other checkers available by default for Java that are more useful.
