### ISSUE TITLE
Format/grammar of the Intermediate Representation

### ISSUE THREAD

**Issue by Tony-Mao** [facebook/infer#375]
The IR files are stuffed through serialization and the content in captured/ is not human-readable. Is there a manual about the format and grammar of the IR files. In particular, if I want to just look into the IR, all I can seem to do is to somewhat 'print' the 'cluster' information before places like `analyze_cluster (nr - 1)  cluster` in `inferanalyze.ml`. 

To be more concrete, I just want to convert the `.cfg`, `.cg` and `.tenv` files into human readable format. Right now they are OCaml serialized data structures.  

The debug mode with the graphical representation is really nice. But I was wondering if generating these visualization is accessible somewhere.

Thanks a lot!

**Comment by jvillard** [comment]
There are two things you can look at:
- The IR consists of [control flow graphs](https://github.com/facebook/infer/blob/3a2a6c7c448f89fb294e6613b84b0ed72379c816/infer/src/IR/Cfg.re#L68-L75) (one for each source file) of [nodes](https://github.com/facebook/infer/blob/3a2a6c7c448f89fb294e6613b84b0ed72379c816/infer/src/IR/Cfg.re#L31-L55), described in the [Cfg file](https://github.com/facebook/infer/blob/3a2a6c7c448f89fb294e6613b84b0ed72379c816/infer/src/IR/Cfg.re). Each node contains instructions, as described in the [Sil.re file](https://github.com/facebook/infer/blob/3a2a6c7c448f89fb294e6613b84b0ed72379c816/infer/src/IR/Sil.re#L794-L811).
- You can generate .dot files representing the control flow graph of a source file (which will contain all procedures defined in that file) by running infer with the `--debug` option for Java, or the `--frontend-debug` option for the clang frontend (see `infer --help`). This creates one `infer-out/captured/<source file name>.<hash>/icfg.dot` file per source file, containing the cfg of that file. This file is in the [DOT](https://en.wikipedia.org/wiki/DOT_%28graph_description_language%29) format. You can also run with `--debug` for either Java or clang and look at the generated html file in `infer-out/caputer/<source file name>.<hash>.html` and if you hover over `I` nodes (or click on them) you'll see the IR instructions executed at that program point.

**Comment by GeekMin** [comment]
@hongzimao 
Here, If i want to get human readable format, have you found any solutions..~?
(like xml format.. or others that is easier to format.. to assist something, like do regression test..
hmmm, you see, if i get the xml-like format, I think i really get the raw data..)

**Comment by sblackshear** [comment]
Have you taken a look at the debug [HTML](http://fbinfer.com/docs/advanced-features.html) that is produced when running using the `--debug` option? This gives a very readable representation of the IR, especially because you see the IR next to the source code that produced it.
