### ISSUE TITLE
Turning on looping related analysis

### ISSUE THREAD

**Issue by Tony-Mao** [facebook/infer#376]
In `infer/infer/tests/codetoanalyze/java/infer/ArrayOutOfBounds.java` it says

`// tests below this line are turned off until array functionality improves`

These are loop related analysis. I was wondering if this feature can be turned on somewhere? If not, are the developers anticipating to see the improvement of this functionality? 

Thanks!

**Comment by jvillard** [comment]
Hi @Tony-Mao, there is a rudimentary array bounds analysis in Infer, but the reports are filtered out by default as this feature is not supported at the moment and performs quite poorly. You can remove error filtering by running with the `--no-filtering` option (see `infer --help`).

We're working on improving the array bounds analysis.
