### ISSUE TITLE
what does facebook-clang-plugins project for ?

### ISSUE THREAD

**Issue by oatsuper** [facebook/infer#377]
My clang version :
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

i wanna know the plugin project must to be "make all",and how to use it ?

**Comment by jvillard** [comment]
What are you trying to do? If you want to install infer, please follow [the docs](http://fbinfer.com/docs/getting-started.html) or just run `brew install infer`.

**Comment by oatsuper** [comment]
you are nice for reply soon~
if I was just to use Infer for IOS project, and brew install infer successful
so, I can ignore the plugin project , it's right?

**Comment by jvillard** [comment]
`brew install infer` already installs everything, including the plugin. You don't have to compile it yourself.

**Comment by oatsuper** [comment]
Another question for help,
Yesterday, I got the completed Infer report and almost 160 errors. After the report review ,Our developers think that testing in a large number of false positives in the report。
I  really really wanna prove Infer is powerful, but i am poor with Object-c

**Comment by ddino** [comment]
Which kind of bug types were considered false positive?

**Comment by akotulski** [comment]
Closing this issue. Feel free to create another issue with concrete false positive examples you have.
