### ISSUE TITLE
mac ,The following build commands failed:

### ISSUE THREAD

**Issue by hujiachun** [facebook/infer#378]
hujiachun:PALifeApp hujiachun684$ infer -- xcodebuild -target PALifeApp -configuration Debug -sdk iphonesimulator
Build settings from command line:
    CC = /usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/inferlib/../../../lib/xcode_wrappers/clang
    CPLUSPLUS = /usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/inferlib/../../../lib/xcode_wrappers/clang++
    GCC_PRECOMPILE_PREFIX_HEADER = NO
    SDKROOT = iphonesimulator9.3

=== BUILD TARGET PALifeApp OF PROJECT PALifeApp WITH CONFIGURATION Debug ===

Check dependencies
No architectures to compile for (ONLY_ACTIVE_ARCH=YES, active arch=i386, VALID_ARCHS=armv7 armv7s arm64).
Warning: Multiple build commands for output file /Users/hujiachun684/Downloads/infer-osx-v0.8.1/examples/PALifeAppIos/PALifeApp/build/Debug-iphonesimulator/PALifeApp.app/201保单列表_03 22@2x.png

** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
Traceback (most recent call last):
  File "/usr/local/bin/infer", line 178, in <module>
    main()
  File "/usr/local/bin/infer", line 142, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/inferlib/capture/xcodebuild.py", line 78, in capture
    utils.stdout(exc.output)
  File "/usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/inferlib/utils.py", line 298, in stdout
    print(encode(s, errors=errors))
  File "/usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/inferlib/utils.py", line 294, in encode
    return u.encode(encoding=config.LOCALE, errors=errors)
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by jvillard** [comment]
Hi @hujiachun, sorry for the delay in replying. This should be fixed in the latest version, can you please give it a try? Please re-open if there is still an issue.
