### ISSUE TITLE
infer install error on mac os

### ISSUE THREAD

**Issue by gql19890103** [facebook/infer#380]
./build-infer.sh clang
initializing opam... 
preparing build... 
checking for .release... no
checking for .facebook... no
checking whether to use the compilers in /Users/guanqinglong/infer/facebook-clang-plugins/clang/bin... no
checking for shasum... shasum
checking for cmake... no
configure: error: cmake not found.

**Comment by akotulski** [comment]
As the message tells you, you don't have cmake installed. It is new dependency needed when we compile clang from source.
If you are using homebrew, you can install it by running `brew install cmake`

**Comment by gql19890103** [comment]
thanks

**Comment by gql19890103** [comment]
thanks,it's work now.
