### ISSUE TITLE
what is "rebuild"

### ISSUE THREAD

**Issue by chen881129** [facebook/infer#381]
I'm installing infer with `./build-infer.sh java`, and I get an error:`configure: error: rebuild not found.`

initializing opam... 
[WARNING] Running as root is not recommended
[WARNING] Running as root is not recommended
preparing build... 
checking for .release... no
checking for .facebook... no
checking for python2.7... python2.7
checking for xcode-select... no
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking for gawk... gawk
checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln -s works... yes
checking whether make sets $(MAKE)... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for ocamlc... ocamlc
OCaml version is 4.02.3
OCaml library path is /usr/local/lib/ocaml
checking for ocamlopt... ocamlopt
checking for ocamlc.opt... ocamlc.opt
checking for ocamlopt.opt... ocamlopt.opt
checking for dynlink.cmxa... yes
checking for ocaml... ocaml
checking for ocamldep... ocamldep
checking for ocamlmktop... ocamlmktop
checking for ocamlmklib... ocamlmklib
checking for ocamldoc... ocamldoc
checking for ocamlbuild... ocamlbuild
checking if OCaml version is >= 4.02.3... yes
checking for ocamlfind... ocamlfind
checking for ocamllex... ocamllex
checking for ocamllex.opt... ocamllex.opt
checking for ocamlyacc... ocamlyacc
checking for rebuild... no
configure: error: rebuild not found.

**Comment by jvillard** [comment]
`rebuild` is installed as part of [Reason](https://github.com/facebook/reason), follow the instructions on GitHub to install Reason. The error message should be better though, thanks for the report.

**Comment by chen881129** [comment]
Thank you for your solution~
But I get another error when I installing Reason

merlin is now git-pinned to https://github.com/the-lambda-church/merlin.git#reason-0.0.1

[ERROR] Command "git fetch -q origin +reason-0.0.1:refs/remotes/opam-ref" failed:
# opam-version 1.2.2
# os           linux
# command      git fetch -q origin +reason-0.0.1:refs/remotes/opam-ref
# path         /root/.opam/4.02.3/packages.dev/merlin
# exit-code    128
# env-file     /root/.opam/log/log-6774-58c514.env
# stdout-file  /root/.opam/log/log-6774-58c514.out
# stderr-file  /root/.opam/log/log-6774-58c514.err
### stderr ###
# fatal: Couldn't find remote ref reason-0.0.1

**Comment by cristianoc** [comment]
@chen881129 can you do  `opam update` and try again the step
```opam pin add -y merlin 'https://github.com/the-lambda-church/merlin.git#reason-0.0.1```.

**Comment by chen881129** [comment]
@cristianoc 
"opam update" before the step and the result is the same.
```
opam update
[WARNING] Running as root is not recommended

=-=- Updating package repositories =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default] synchronized from https://opam.ocaml.org
```

```
opam pin add -y merlin 'https://github.com/the-lambda-church/merlin.git#reason-0.0.1'
[WARNING] Running as root is not recommended
[NOTE] Package merlin is already git-pinned to https://github.com/the-lambda-church/merlin.git#reason-0.0.1.
       This will erase any previous custom definition.
Proceed ? [Y/n] y

[ERROR] Command "git fetch -q origin +reason-0.0.1:refs/remotes/opam-ref" failed:
# opam-version 1.2.2
# os           linux
# command      git fetch -q origin +reason-0.0.1:refs/remotes/opam-ref
# path         /root/.opam/4.02.3/packages.dev/merlin
# exit-code    128
# env-file     /root/.opam/log/log-16912-58c514.env
# stdout-file  /root/.opam/log/log-16912-58c514.out
# stderr-file  /root/.opam/log/log-16912-58c514.err
### stderr ###
# fatal: Couldn't find remote ref reason-0.0.1
```

**Comment by cristianoc** [comment]
@chen881129 looks like the tag `reason-0.0.1` is not found.
But it's there: https://github.com/the-lambda-church/merlin/commits/reason-0.0.1
The last commit there is 87ea0e7998c04f16e4821676c27f19d3879dc2d1.
So you could instead try the more direct
```
opam pin add -y merlin https://github.com/the-lambda-church/merlin.git#87ea0e7998c04f16e4821676c27f19d3879dc2d1
```

**Comment by chen881129** [comment]
Hello, @cristianoc , sorry to leave so long time.
I tried this command last friday, it also didn't work.

```
opam pin add -y merlin https://github.com/the-lambda-church/merlin.git#87ea0e7998c04f16e4821676c27f19d3879dc2d1
[WARNING] Running as root is not recommended
[NOTE] merlin is currently git-pinned to https://github.com/the-lambda-church/merlin.git.
Proceed ? [Y/n] y
merlin is now git-pinned to https://github.com/the-lambda-church/merlin.git#87ea0e7998c04f16e4821676c27f19d3879dc2d1

[ERROR] Command "git fetch -q origin +87ea0e7998c04f16e4821676c27f19d3879dc2d1:refs/remotes/opam-ref" failed:
# opam-version 1.2.2
# os           linux
# command      git fetch -q origin +87ea0e7998c04f16e4821676c27f19d3879dc2d1:refs/remotes/opam-ref
# path         /root/.opam/4.02.3/packages.dev/merlin
# exit-code    128
# env-file     /root/.opam/log/log-24521-58c514.env
# stdout-file  /root/.opam/log/log-24521-58c514.out
# stderr-file  /root/.opam/log/log-24521-58c514.err
### stderr ###
# fatal: Couldn't find remote ref 87ea0e7998c04f16e4821676c27f19d3879dc2d1
```

**Comment by akotulski** [comment]
The problem shouldn't happen anymore - we install reason as part of ./build-infer script now
https://github.com/facebook/infer/commit/1420cabac5cdb1a7cb1d0999f48f1a7a6af80457

**Comment by mishudark** [comment]
I have the same problem on Centos 6

**Comment by jvillard** [comment]
@mishudark Can you please provide more information? Please include:
- the version of Infer
- the command you ran
- the full output (please use https://gist.github.com/ or equivalent)

**Comment by mishudark** [comment]
@jvanzyl sure
**os**: `CentOS release 6.8 (Final)`
**infer version**: `infer-linux64-v0.9.2$`
**command**: `sh build-infer.sh`
**output**: 
````
[ERROR] Command "git fetch -q origin +reason-0.0.1:refs/remotes/opam-ref" failed:
# opam-version 1.2.2
# os           linux
# command      git fetch -q origin +reason-0.0.1:refs/remotes/opam-ref
# path         /home/mishu/.opam/4.02.3/packages.dev/merlin
# exit-code    128
# env-file     /home/mishu/.opam/log/log-16626-58c514.env
# stdout-file  /home/mishu/.opam/log/log-16626-58c514.out
# stderr-file  /home/mishu/.opam/log/log-16626-58c514.err
### stderr ###
# fatal: Couldn't find remote ref reason-0.0.1
```

**Comment by jvillard** [comment]
@mishudark The version of `git` might be too old on your system. You'll need to install Reason manually for now I'm afraid. Something like this may work:
1. select the infer-4.02.3 opam switch: `opam switch infer-4.02.3 && eval $(opam config env)`
2. clone the Reason repo locally, checkout its 0.0.1 release, then `opam pin add -k git reason .` inside the repo should install reason from there
3. run `./build-infer.sh` from the infer repo again

Hope this helps!
