### ISSUE TITLE
can it  analysis application back end?

### ISSUE THREAD

**Issue by calistochen** [facebook/infer#382]
can it  analysis application back end?

**Comment by jmtiong** [comment]
What do you mean by analyzing application back end? Such as, running Infer in the background while the application is running? To my knowledge, Infer is a static analyzer so which means that it cannot analyze programs dynamically.

**Comment by calistochen** [comment]
i means analyze the server side, not just client.

**Comment by calistochen** [comment]
@jmtiong I means analyze the server side, not just client.

**Comment by calistochen** [comment]
Example :facebook not only use it to analyze Instagram , but  also to analyze Instagram's server side?

**Comment by calistochen** [comment]
@jmtiong facebook not only use it to analyze Instagram , but also to analyze Instagram's server side?

**Comment by cristianoc** [comment]
There are no special restrictions, as long as the language and build system are supported by Infer.
An example of non-client code is buck: https://github.com/facebook/buck which Infer also analyzes.

**Comment by cristianoc** [comment]
Feel free to re-open if you run into specific issues.
