### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 

### ISSUE THREAD

**Issue by LichFaker** [facebook/infer#387]
Hi, I type this into my terminal:
`infer -- gradle clean build`

However,  I got an error:
![image](https://cloud.githubusercontent.com/assets/5850082/16217793/5f879038-37a9-11e6-9293-ed88cf84b8e3.png)

I want to know why and how to solve it ?

**Comment by chen881129** [comment]
infer-0.8.1/infer/lib/python/inferlib/capture/util.py: 27

`return verbose_out_chars.decode('gbk').split('\n')`
改成这样试试

**Comment by jvillard** [comment]
This should be fixed in latest master from GitHub. We should make a release but in the meantime you can compile Infer from source.

**Comment by LichFaker** [comment]
@jvillard Okay, thank u very much

**Comment by loveai88** [comment]
I run in OSX ,and change it to verbose_out_chars.decode('UTF-8').split('\n').It is ok

**Comment by LichFaker** [comment]
@loveai88  thanks
