### ISSUE TITLE
Analyse one single file in a large project

### ISSUE THREAD

**Issue by kumarbanty** [facebook/infer#388]
I have an android app which contains more than 500 java classes and every time I run infer, it checks through the entire project, which takes a lot of time.Is it possible to run the tests in one single class only?

**Comment by cristianoc** [comment]
@kumarbanty have you seen the Differential Workflow in http://fbinfer.com/docs/infer-workflow.html?
Alternatively, if your use case is different than a loop, change code + analyze, there are some experimental options to specify a list of files to be analyzed.

**Comment by kumarbanty** [comment]
Thank you so much for your reply
