### ISSUE TITLE
User-defined model for malloc

### ISSUE THREAD

**Issue by Guoanshisb** [facebook/infer#389]
Hi infer developers,

I was wondering if it is impossible to change the builtin model of `malloc` such that it always returns a non-null pointer.

Thanks,
Shaobo

**Comment by ddino** [comment]
malloc can return null. So it would be an incorrect model of the semantics of malloc. 
There are other functions that do not return null for example xmalloc.

**Comment by Guoanshisb** [comment]
@ddino what if user defined a `malloc` function, will Infer always use its built-in model?

**Comment by sblackshear** [comment]
Unfortunately, the model for `malloc` is currently baked into the backend, so the only way to change Infer's handling of `malloc` is to change the backend itself. If you change `execute_alloc Sil.Mmalloc true` to `execute_alloc Sil.Mmalloc false` [here](https://github.com/facebook/infer/blob/master/infer/src/backend/modelBuiltins.ml#L1117), Infer will treat `malloc` as if it never returns null.

**Comment by akotulski** [comment]
There is configuration option being added that will allow to change behavior of malloc (specifically whether it can return null). Stay tuned

**Comment by jvillard** [comment]
I'm adding an option to choose a different behaviour for `malloc`, stay tuned.
