### ISSUE TITLE
false positive on short-circuit evaluation

### ISSUE THREAD

**Issue by Guoanshisb** [facebook/infer#392]
Hi guys,

Infer seems to give a false positive in terms of null pointer deference on the following example,

```C
#include <stdlib.h>

int main()
{
  int* x = (int*)malloc(sizeof(int));
  int ret = x && *x;
  if (x)
    free(x);
  return ret;
}
```

The output of Infer is `pointer x last assigned on line 5 could be null and is dereferenced at line 6, column 18`

Please let me know if some undefined behavior shows up. The command line I used is `infer -- clang -c <filename> ` and Infer version is `v0.8.1`.

Thanks,
Shaobo

**Comment by sblackshear** [comment]
It looks like this issue has been fixed since the 0.8.1 release. With I run with Infer built from c23dc81cfdad2d12d38ad3e7fab02d5a983edb74, I get no errors when running `infer -- clang -c <filename>` and get 

```
sample.c:6: warning: UNINITIALIZED_VALUE (backend/symExec.ml:115:65-72:)
  value *x was not initialized after declaration and is used at line 6, column 18
  4.   {
  5.     int* x = (int*)malloc(sizeof(int));
  6. >   int ret = x && *x;
  7.     if (x)
  8.       free(x);
  9.   
```
when running with `infer -nf -- clang -c <filename>` (which seems as expected to me).

**Comment by Guoanshisb** [comment]
@sblackshear Thanks for your reply. I tried to find the commit you mentioned by doing `git show c23dc81cfdad2d12d38ad3e7fab02d5a983edb74` and it seems that there is no such commit.

**Comment by sblackshear** [comment]
Apologies; I meant d1fa1e130dd154c5642174180851f8730c792aaa.

**Comment by Guoanshisb** [comment]
@sblackshear It's fine. I built Infer release using this link (https://github.com/facebook/infer/releases/tag/v0.8.1). It seems that the commit you sent me is quite new and thus does not show up in the official release. So I was wondering if I should checkout the latest commit of master branch and rebuild it.

**Comment by sblackshear** [comment]
Yes, that's what I would do. I'm not sure when the issue you bring up was introduced, but it seems to be fixed in master.

**Comment by akotulski** [comment]
it was fixed in https://github.com/facebook/infer/commit/daf043bff1c3cc35ab055c3ee5c752ef930965c1
