### ISSUE TITLE
Failed to run InferAnalyze binary, exiting on MacOS

### ISSUE THREAD

**Issue by YechengZhou** [facebook/infer#393]
Down load infer-osx-v0.8.0.tar.xz, follow the steps in https://github.com/facebook/infer/blob/master/INSTALL.md#install-the-dependencies

but get the error message "Failed to run InferAnalyze binary, exiting " when analyzing IOS project

**Comment by jvillard** [comment]
you need to compile infer or install it from homebrew. See [this page](http://fbinfer.com/docs/getting-started.html) for more instructions.
