### ISSUE TITLE
brew for version v0.9.0

### ISSUE THREAD

**Issue by eikebartels** [facebook/infer#394]
There is no installer for version v0.9.0

**Comment by jvillard** [comment]
There is no 0.9.0 release yet, it's in preparation.

**Comment by eikebartels** [comment]
I see! Any eta when 0.9.0 will be released?

**Comment by jvillard** [comment]
probably next week!

**Comment by eikebartels** [comment]
latest release https://github.com/facebook/infer/releases/tag/v0.9.0 not available via homebrew

**Comment by jvillard** [comment]
Turns out this issue is hard to release via homebrew due to the way it links binaries. We've fixed this issue in infer and are hoping for a 0.9.1 release to put on homebrew in the coming days. Sorry for the wait.

**Comment by pumano** [comment]
How to get infer 0.9.1 via homebrew? or it not available? I have only 0.8.1 available via homebrew.

**Comment by jvillard** [comment]
You can follow along this PR on homebrew for infer 0.9.2: https://github.com/Homebrew/homebrew-core/pull/4007

**Comment by jvillard** [comment]
0.9.2 has hit Homebrew.
