### ISSUE TITLE
Is there any documentation for running infer through Docker

### ISSUE THREAD

**Issue by MatthewBennington** [facebook/infer#395]
The ["Getting started with Infer"](http://fbinfer.com/docs/getting-started.html) lists Docker as the recommended way of installing Infer on Linux.

I had trouble installing infer from source in the past, so I wanted to jump at the opportunity to try it again.

But I'm not clear on how to actually run the program. You can of course run it in the Docker instance, but I can't access my project from in there.

**Comment by jvillard** [comment]
You can mount a volume pointing to your project inside the Docker instance. See for instance #345, or the Docker documentation.
