### ISSUE TITLE
Infer - Jenkins Integration

### ISSUE THREAD

**Issue by RaghAkella** [facebook/infer#396]
Hi,

Using PMD plugin in jenkins we can analyse the results generated by ****oclint**.** 
is infer giving support for any such features?

Any documentation for jenkins integration

**Comment by jvillard** [comment]
There's a `--pmd` switch, see `infer --help`. Does that help?

**Comment by uhafner** [comment]
@chenlujjj Please file a bug report in my [warnings-plugin](https://github.com/jenkinsci/warnings-plugin) if the file cannot be read within Jenkins.
