### ISSUE TITLE
why infer told me configure error shasum not found?

### ISSUE THREAD

**Issue by luoshangyu** [facebook/infer#398]
Hi experts,

I'm sorry for the bother.

I was building the infer but finally got below issue.
And nothing in the ../infer/bin except inferTest.

Anyone can help on this? Thanks a lot.

![image](https://cloud.githubusercontent.com/assets/7412385/16973268/fa49c696-4e64-11e6-81e2-f9c9f79cbb09.png)

I was building infer on CentOS 7.

Best Regards,
Lucas Luo

**Comment by sblackshear** [comment]
Hi Lucas, looks like your distribution of CentOS is missing the shasum package. Try `yum install shasum` (or however you install packages on your system) and give the Infer build script another shot.

**Comment by luoshangyu** [comment]
Thanks  sblackshear.
but after the build (./build-infer.sh), why nothing in ../infer/bin? still the `inferTest`?

**Comment by luoshangyu** [comment]
finally resolved everything, thanks `sblackshear`.

**Comment by wubo0067** [comment]
No package shasum available

**Comment by jvillard** [comment]
@wubo0067 what system are you using?

**Comment by jvillard** [comment]
@itkovian does `yum install shasum` solve your problem?

**Comment by itkovian** [comment]
Ah, it's in `perl-Digest-SHA`. Thanks for the swift response!
