### ISSUE TITLE
Analyzed 0 files

### ISSUE THREAD

**Issue by galaxycoder** [facebook/infer#400]
version v0.9.0
install from source

excute "infer -- xcodebuild -workspace xxx.xcworkspace -scheme xxx -configuration Debug -sdk iphonesimulator", no warning or error, excute succeeded, but output "Analyzed 0 files", then i excute with example code in [infer Hello world](http://fbinfer.com/docs/hello-world.html), still got output "Analyzed 0 files"

**Comment by jvillard** [comment]
Can you please paste the full output of the hello world example you tried with `infer -g`? E.g. `infer -g -- clang -c hello.c`. Please also paste the contents of toplevel.log. You can use https://gist.github.com/ or similar. Thanks!

**Comment by jvillard** [comment]
please reopen if this is still relevant
