### ISSUE TITLE
Any example on finding security (data flow) bug?

### ISSUE THREAD

**Issue by liweijian** [facebook/infer#405]
I just watch the talk of Infer on Mobile@Scale, and as it mentioned

![secanalysis](https://cloud.githubusercontent.com/assets/19320783/17174472/58e1b130-5434-11e6-836c-ba051b5cdb04.jpeg)

> Security (data flow) analysis

Wow~ It's so great!

I was wondering if there's any example on that kind of bug which Infer could hunt?

**Comment by sblackshear** [comment]
Thanks for your kind words!

Here's an [example](https://gerrit-review.googlesource.com/#/c/75724/) of a security issue found by Infer: SSL hostname verification bug in Gerrit.
