### ISSUE TITLE
Running infer on Eclipse Jetty on MAC OS X raises an exception in analyze.py

### ISSUE THREAD

**Issue by xennygrimmato** [facebook/infer#408]
Trace: [Github Gist](https://gist.github.com/xennygrimmato/4c7ac1627368a54fcdb7ba15d373693b)

Command: `infer -- mvn package`

I ran this after cloning eclipse jetty.

**Comment by sblackshear** [comment]
This happens when running on Java 8 code. Infer does not yet support Java 8, but we plan to soon (#314).
