### ISSUE TITLE
Missing capture module when running infer -- <cmd>

### ISSUE THREAD

**Issue by leoherbie** [facebook/infer#41]
Attempting to execute any command through infer like:
```Traviss-MBP:kc Travis$ infer -- mvn install```

Results in:
```
Traceback (most recent call last):
  File "/usr/local/bin/infer", line 142, in <module>
    main()
  File "/usr/local/bin/infer", line 104, in main
    imported_module = load_module(mod_name)
  File "/usr/local/bin/infer", line 50, in load_module
    pkg_info = imp.find_module(CAPTURE_PACKAGE, [LIB_FOLDER])
ImportError: No module named capture
```

Note: that I have python 2.7 installed via homebrew

**Comment by martinoluca** [comment]
Hi @leoherbie,
I see from your error message you've installed Infer on `/usr/local/bin/infer`, this means that you should also have installed the `lib/` folder of Infer in `/usr/local/lib/`, since the `infer` command expects a `capture/` folder in `lib/`.

**Comment by akotulski** [comment]
@leoherbie 
If your /usr/local/bin/infer is a symbolic link, there was minor issue that we missed in initial release in regards to handing this:
https://github.com/facebook/infer/pull/13

If you apply following code change, it should work:
https://github.com/dambrisco/infer/commit/b2b2fe4436d43cc16405c792396d175ce4572cc6

**Comment by leoherbie** [comment]
@akotulski That is exactly the issue.  I had created symlinks.  Thank you.

**Comment by kingangelTOT** [comment]
Traceback (most recent call last):
  File "/usr/bin/infer", line 142, in <module>
    main()
  File "/usr/bin/infer", line 104, in main
    imported_module = load_module(mod_name)
  File "/usr/bin/infer", line 50, in load_module
    pkg_info = imp.find_module(CAPTURE_PACKAGE, [LIB_FOLDER])
ImportError: No module named capture 

this issue is still exist?
