### ISSUE TITLE
Infer should support Contract annotations in Java

### ISSUE THREAD

**Issue by ZacSweers** [facebook/infer#410]
https://www.jetbrains.com/help/idea/2016.2/contract-annotations.html

**Comment by cristianoc** [comment]
@hzsweers great suggestion.
What specific use cases do you have in mind?
For example, some time ago we added `@TrueOnNull` https://github.com/facebook/infer/blob/97bc95e8c920196d91a9d48cb4ac93f6c43b8187/infer/tests/codetoanalyze/java/eradicate/NullMethodCall.java#L248 to support boolean functions on objects that return `true` when the object is `null`. They can then be used as in https://github.com/facebook/infer/blob/97bc95e8c920196d91a9d48cb4ac93f6c43b8187/infer/tests/codetoanalyze/java/eradicate/NullMethodCall.java#L261.

**Comment by hzsweers** [comment]
It would be great to support them in general as they give a lot of contextual information about how a method handles inputs. The example in there about a method that only returns `null` if the input parameter is `null` is a great example. Being able to express other conditions in that format would be great too. Being able to mark methods as throwing on certain conditions would be immense as well.

Looking at the page again, I think it would be great to support `@ParametersAreNonnullByDefault` annotation as well, as it also looks pretty useful.
