### ISSUE TITLE
Some latex components on the website are not rendered

### ISSUE THREAD

**Issue by xennygrimmato** [facebook/infer#413]
Under bi-abduction heading in the docs, a Latex component was not rendered, in the paragraph that starts with "In order to be able to decompose a global analysis":

`<script type="math/tex; mode=display">CallingState \vdash pre\_f  \;\;\;\;\;\;\;\;\;\;\;\; (Function Call)</script>`

**Comment by jvillard** [comment]
Thanks for your report, it looks like markup of the form `$$ formula $$` is not rendered (anymore?). Let me take a look.
