### ISSUE TITLE
Question: Quantitative Comparison with Findbugs Rules

### ISSUE THREAD

**Issue by xennygrimmato** [facebook/infer#415]
Findbugs, being pretty old, has a long set of rules implemented. Where does Infer stand in comparison to the set of rules implemented? I would like to contribute if possible to adding new rules to Infer.

**Comment by jvillard** [comment]
The kinds of bugs found by the analyzers in Infer are listed here:
- http://fbinfer.com/docs/infer-bug-types.html
- http://fbinfer.com/docs/checkers-bug-types.html
- http://fbinfer.com/docs/eradicate-warnings.html

Contributions are very welcome! You can start here for directions on how to add new checks: http://fbinfer.com/docs/infer-bug-types.html

Feel free to open new issues or PRs to get help on specific checks.

**Comment by xennygrimmato** [comment]
Thanks for the info! I've written a custom checker, modifying the existing example. Should I create a PR and continue the conversation there?

**Comment by jvillard** [comment]
Please create a PR.
