### ISSUE TITLE
Adding Checkers doc is outdated

### ISSUE THREAD

**Issue by xennygrimmato** [facebook/infer#416]
-  [/docs/adding-checkers](http://fbinfer.com/docs/adding-checkers.html) still shows the `.mli` files instead of `.rei`. Maybe the example can be updated with Reason syntax as it conforms to the current master I suppose.

- If a function has been implemented for comparing (class_name, method_name), maybe it can be added to the doc. 

- Does `java_proc_name_with_class_method` in `patternMatch.ml` do what is implemented in the example?

**Comment by jvillard** [comment]
I think your PR addressed all of these.
