### ISSUE TITLE
infer -- mvn package does not seem to start analysis for a long time

### ISSUE THREAD

**Issue by xennygrimmato** [facebook/infer#417]
I am running infer on [Guava](https://github.com/google/guava) on an Ubuntu 14.04 Docker image, running on a MAC host.

Running `infer -- mvn package` after `mvn clean` printed:

```
Infer version v0.9.0-85add04
Copyright 2009 - present Facebook. All Rights Reserved.
``` 

and I waited for a long time, expecting to see some log regarding the analysis. I finally stopped the process as no log was printed on stdout.

**Comment by sblackshear** [comment]
It looks like `mvn package` takes a long time even without Infer since it's running tests. Have you tried `mvn compile`?

**Comment by xennygrimmato** [comment]
Build failed, saying it couldn't resolve a dependency - `com.google.guava:guava-gwt:jar:20.0-SNAPSHOT`

**Comment by sblackshear** [comment]
That sounds independent of Infer. Have you tried running plain `mvn compile` without Infer? I always run the vanilla build to make sure it works before I try running Infer.

**Comment by xennygrimmato** [comment]
Yes, I ran `mvn compile` without infer.

**Comment by sblackshear** [comment]
Does the failure to resolve a dependency happen with `mvn compile` as well, or only under `infer -- mvn compile`?

**Comment by xennygrimmato** [comment]
`mvn compile` seems to be working fine now actually. I am trying to run `infer -- mvn compile`, but I guess it will take some time. Meanwhile, I wanted to know if we can show `mvn`'s logs while running `infer -- mvn compile`? I think, what I'm perceiving to be "time-consuming", is the build process itself, but `infer` doesn't seem to log that.

**Comment by xennygrimmato** [comment]
The failure to resolve a dependency happens with `mvn compile`.
With `infer -- mvn compile`, the program exists with exit status 1.

**Comment by sblackshear** [comment]
> The failure to resolve a dependency happens with mvn compile.

Sounds like `mvn compile` fails without Infer. Infer only works when the underlying compilation command works.
