### ISSUE TITLE
infer -- mvn package tries running javac on .properties and .MF files

### ISSUE THREAD

**Issue by xennygrimmato** [facebook/infer#418]
infer exits as it tries to run Manifest files with javac, while building using mvn.

**Comment by sblackshear** [comment]
Thanks for the report. This should be a pretty easy fix, but do you have an example Maven project where I can reproduce the issue? I haven't actually encountered this problem before.

**Comment by xennygrimmato** [comment]
Example Maven Project 1: [Jackson](https://github.com/FasterXML/jackson-core)
I ran the following on bash:
1. `mvn clean`
2. `infer -- mvn package`

Example Maven Project 2: [Error Prone](https://github.com/google/error-prone)
I ran the following on bash:
1. `mvn clean`
2. `infer -a eradicate -- mvn package`
