### ISSUE TITLE
I don't wanna library soure code in Pods folder when my IOS project under infer running , can i ? 

### ISSUE THREAD

**Issue by oatsuper** [facebook/infer#419]
I don't wanna library soure code in Pods folder were checked when my IOS project under infer running , can i ?

**Comment by oatsuper** [comment]
any update？

**Comment by akotulski** [comment]
Sorry for late reply. There is a flag (`--skip-clang-analysis-in-path`) to exclude directories from being taken into account when running infer. For you it should look something like  `infer --skip-clang-analysis-in-path Pods ...`.
You still might see some issues coming from c++ headers in `Pods` if you are running in `--cxx` mode. If that's the case, you can try adding `--skip-translation-headers Pods` to infer command.

Closing the issue, but don't hesitate to reopen if it doesn't work for you.

**Comment by oatsuper** [comment]
usage: infer [-h] [-o <directory>] [-i] [-ic] [-r] [-m] [-c]
             [--debug-exceptions] [-g] [-a ANALYZER] [-nf] [--fail-on-bug]
             [--android-harness] [-l] [-v] [--pmd-xml] [-j n]
             [-x <projectname>] [--revision <githash>] [--buck]
             [--infer_cache <directory>] [-pr PROJECT_ROOT] [--absolute-paths]
             [--ml_buckets ML_BUCKETS] [-npb] [--specs-dir <dir>]
             [--specs-dir-list-file <file>] [-hd] [--models_mode]
             [--no_failures_allowed] [-tm] [--cxx] [-fs] [-fd] [-- <cmd>]
infer: error: unrecognized arguments: --skip-clang-analysis-in-path Pods

Why ??

**Comment by akotulski** [comment]
Which version of infer are you using (run `infer --version`)? 
I think latest homebrew release doesn't have the parameter yet. You can try infer [0.9.0](https://github.com/facebook/infer/releases/tag/v0.9.0) from our github releases page.
We are planning to release 0.9.1 with the fix allowing us to publish new infer via homebrew, but it's not there yet

**Comment by oatsuper** [comment]
OK， my infer version is 0.8.1 , So  I try the newer infer by github download ~
 you are so nice ~~

**Comment by thyrlian** [comment]
'`--skip-clang-analysis-in-path`' is deprecated. Use '`--skip-analysis-in-path`' instead.
