### ISSUE TITLE
False positive with pointer returned through struct value (speex)

### ISSUE THREAD

**Issue by rillian** [facebook/infer#42]
Thanks for the tool release! It's great to see new code in the static analysis space.

I found a false positive with the speex library. It sees a leak when a pointer is allocated and then returned as a member in a struct value. It may be more complicated than that, since I wasn't able to reproduce with a simpler test case.
```
src/skeleton.c:138: error: MEMORY_LEAK
   memory dynamically allocated to fp.message_header_fields by call to calloc() at line 135, column 82 is not reachable after line 138, column 5
```
https://github.com/xiph/speex/blob/master/src/skeleton.c#L138

**Comment by jvillard** [comment]
this bug is not found anymore with the latest versions of infer and speex
