### ISSUE TITLE
NULL_DEREFERENCE around `try ... catch`

### ISSUE THREAD

**Issue by liweijian** [facebook/infer#422]
My code:
```java
public class Dertry {
    public int test(String[] params) {
        String bundle = null;
        if (params != null && params.length >= 1) {
            bundle = "hello world";
        }

        try {
            int idx = bundle.indexOf('o');
            return idx;
        } catch (Exception e) {}
        return 0;
    }

    public static void main(String[] args) {
        Dertry dertry = new Dertry();
        dertry.test(null);
    }
}
```

Infer result:
```bash
Dertry.java:12: error: NULL_DEREFERENCE
  object bundle last assigned on line 6 could be null and is dereferenced at line 12
  10.
  11.           try {
  12. >             int idx = bundle.indexOf('o');
  13.               return idx;
  14.           } catch (Exception e) {}
```

Since the null value dereferenced is wrapped by a `try ... catch`, I think may Infer should ignore it?

**Comment by martinoluca** [comment]
Hello @liweijian,
What you are discussing here is still a null dereference in practice, despite it being handled by the `catch` block.
In general, the presence of a potential null dereference in your code means that there's something wrong with the implementation itself, and you should avoid this situation by handling it correctly.
Do you have a specific use case in mind such that this kind of pattern is strictly necessary?

Thanks
