### ISSUE TITLE
NULL_DEREFERENCE around try...catch

### ISSUE THREAD

**Issue by xennygrimmato** [facebook/infer#423]
This is in reference to #422 . 

Consider that an object of type `T` is null and is being dereferenced, within a `try...catch` that handles `NullPointerException`. Shouldn't this be treated differently from a case in which the `try...catch` doesn't handle the null dereference at all?

From how I see this, probably we can show a warning to the user, saying, `"Maybe you should handle this derefence properly, although the try...catch seems to be handling this."`

**Comment by jvillard** [comment]
Strictly speaking, it's true that the code will not generate an NPE. That said, the choice Infer makes is to report anyway. If a project deliberately catches `NullPointerException`, Infer will produce a lot of unintended reports. For such projects (if they exist), a different message would help.

I suspect that it would be hard to implement that behaviour in infer: if `foo()` dereferences null, then infer will want to report on `foo()`. But maybe `foo()` is only called from inside `bar()`, which catches `Exception` or `NullPointerException`. Currently, infer has no way to know every context in which `foo()` is called prior to analysing `foo()`, so it would be hard to avoid reporting on `foo()`.

That said, as @martinoluca was saying in #422, such code patterns are dubious at best anyway.

**Comment by xennygrimmato** [comment]
Just curious to know:

- Which source files contain the logic for maintaining context and for composition?

**Comment by xennygrimmato** [comment]
It seems that the `type t` represents the Graph, `Procname.t` represents each node in the Graph and `Cfg.re` has functions to modify the graph. Is my understanding correct?

**Comment by jvillard** [comment]
Which `type t` are you talking about? `git grep 'type t\b' infer/src/` returns 223 results ;)

`Procname` is a module for procedure names. A `Cfg` object contains the control-flow graph of all the functions defined in a given file, but by no means of all the procedures in a program. Those are stored on disk in infer-out/captured/.

The logic to analyse functions and in which order lives in ondemand.ml and interproc.ml. Roughly, Infer analyses each function independently. If a function `f()` calls another function `g()`, infer will go and analyse `g()` first (to get its pre- and post-conditions, called "specs", and store them on disk in infer-out/specs/), then go back to analysing `f()`. The only information that is kept around from one function to the other is its set of specs.

**Comment by jvillard** [comment]
Seems like we can close this, please re-open if not.
