### ISSUE TITLE
A custom checker for Java to check that no catch( ) block is blank

### ISSUE THREAD

**Issue by xennygrimmato** [facebook/infer#425]
I want to write a custom checker for Java programs to process the contents of a `try...catch` block, specifically to perform some processing on the contents of the `catch` block.
From whatever code I read, I could figure out the following:
- `Cfg.Procdesc.iter_instrs do_instr proc_desc` iterates over the instructions of a procedure node in the CFG and executes `do_instr` on each instruction.
- `ProcAttributes.re` gives the name and type of variables captured in a procedure, as well as the Exceptions thrown by the procedure.
- `cg.re` contains functions regarding the parents and children of a node in the Call Graph.

What I want to know:
- How do I find out whether a certain line is enclosed within a `try` block, or is followed by a `catch` block?
- How do I find the `type` of the Exception being caught by the `catch`?
- How do I find whether a certain instruction is part of a `catch` block, or how do I find what instructions are present in a certain `catch` block?

Please correct me if I went wrong in understanding something. Answers to the above would be valuable for me to understand the flow of what is happening internally.

**Comment by xennygrimmato** [comment]
For understsanding the CFG created when a `try...catch` is present, I used the following piece of code:

```java
import java.io.*;
class Hello2 {
    int test() {
      try {
        String s = "Hello World";
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        File f = new File("a.txt");
        System.out.println(s);
        s = null;
        int x = s.length();
        return x;
      } catch(NullPointerException e) {

      } catch(Exception e2) {

      }
      return 0;
    }
}
```
CFG created:
[trycatch.pdf](https://github.com/facebook/infer/files/403420/trycatch.pdf)

In `18: method_body`, a line that I think would be particularly useful for me is:
```
n$13=*&CatchVar53:class java.lang.Object * [line 14]
```
I am guessing that a method_body node with the `CatchVar` property would be the start of the method body within a `catch`, and the Exception caught would be its parent in the CFG.

Is this the right approach to get started with this?

**Comment by xennygrimmato** [comment]
`>> A problem that I would face further with this, would probably be that I won't know where the method body ends.`
I guess [these lines](https://github.com/facebook/infer/blob/master/infer/src/IR/Cfg.re#L61-#L62) in `Cfg.re` give me the list of nodes in the procedure, so it won't be a problem.

**Comment by sblackshear** [comment]
>How do I find out whether a certain line is enclosed within a try block, or is followed by a catch block?

This is going to be a bit cumbersome with our current checkers setup, but it can be done in a hacky way. Let me explain how to do this by modifying the `exec_instr` function in the checker [here](https://github.com/facebook/infer/blob/master/infer/src/checkers/liveness.ml).

```
let exec_instr : astate proc_data node instr =
    let is_catch_pvar _pvar = failwith "implement me" in
    let is_start_of_catch = function
      | Sil.Set (Exp.Lvar lhs_pvar, _, _, _) -> is_catch_pvar lhs_pvar
      | _ -> false in
    let is_maybe_end_of_catch = function
      | Sil.Abstract _ -> true
      | _ -> false in
```
I say `maybe` in the second function because it will also report the end of a catch block early if the catch block contains a loop. But for your use-case of detecting empty catches, this should work just fine.

>How do I find the type of the Exception being caught by the catch?

For each exception type `e` caught by the catch block, there will be an instruction performing an `instanceof` check on `e` to decide whether to enter the catch block or not.

>How do I find whether a certain instruction is part of a catch block, or how do I find what instructions are present in a certain catch block?

I would use the utility functions above to know when you are in a catch block, then create a mapping from catch blocks to the instructions they contain.

**Comment by xennygrimmato** [comment]
Thanks for the reply, @sblackshear !
To check if `_pvar` in `let is_catch_pvar _pvar = failwith "implement me" in` is a `catch`, do I need to compare it with the `handler.JBir.e_catch_var` type? I am unable to traverse to that variable in Atom - it seems to be in Sawja Javalib.

**Comment by sblackshear** [comment]
Yes, you won't be able to do it using the Sawja type. I believe you'll need to do it in a slightly hacky way: a string comparison on the name of the `pvar`.

**Comment by xennygrimmato** [comment]
@sblackshear : For String comparison, I'm using `Pvar.to_string _pvar = "CatchVar"`, since the icfg.dot file seemed to have a node containing `n$13=*&CatchVar53:class java.lang.Object *`. However, I couldn't find a concrete name for a "catch" program variable, as other parts of the code seem to be using `JBir.e_catch_var` instead of String comparison. I tried string comparison of pvar with "catch", "Catch", "CatchVar", but none of them matched. I wanted to try comparison with Sawja's `JBir.e_catch_type` but I get `Unbound value JBir.e_catch_type`.

**Comment by jvillard** [comment]
I think what you want here is to compare just the prefix of the variable name since the variable seems to be named `CatchVar53`, so something like this:

**Comment by jvillard** [comment]
Please do re-open if you would like more information.
