### ISSUE TITLE
Debugging and logging in infer

### ISSUE THREAD

**Issue by xennygrimmato** [facebook/infer#428]
I am writing a checker and I want to print some logs in order to see what's happening under the hood, in order to debug the checker.
I am trying to use `L.err "Sample Log Message %a@." Procname.pp proc_name;`, but it doesn't print anything on STDOUT, and the `infer-out/log/analyzer_err` and `infer-out/log/analyzer_out` files are empty.
What is the best way to perform logging and debugging while writing a checker?

**Comment by martinoluca** [comment]
Hello @xennygrimmato,
To use `L.err`/`L.out` you have to be in developer mode, which means you need to invoke infer with the `--developer-mode` argument (as you can see [here](https://github.com/facebook/infer/blob/fe780cb6ffd236cf618c2f9b63b03ddd2de18764/infer/src/backend/logging.ml#L142-L148))

But even if you use that, there may be many different processes running one after the other during the analysis thus overwriting the content of the `analyzer_err` and `analyzer_out` log files, and this should explain why they look empty at the end.

For now, try using `L.stdout`/`L.stderr` to get your output in the console, and you don't need to run in developer mode to use it.

Thanks

**Comment by xennygrimmato** [comment]
Thanks @martinoluca , using `L.stderr` worked for me, but `L.stdout` didn't.

**Comment by jberdine** [comment]
The situation should be a bit better since [f30b6e3](https://github.com/facebook/infer/commit/f30b6e39db55b9c1ba6c02e5544abd2b36e598a2).  In particular, `L.err` and `L.out` should reliable produce output in log files under the results directory when run in `--stats` or `--debug` modes.  Please reopen if this issue persists.
