### ISSUE TITLE
A possible false positive for Null Dereference

### ISSUE THREAD

**Issue by xennygrimmato** [facebook/infer#430]
I ran `infer -- gradle build`on [Mozilla Rhino](https://github.com/mozilla/rhino).

``` java
src/org/mozilla/javascript/NativeCallSite.java:132: error: NULL_DEREFERENCE
  object cs last assigned on line 130 could be null and is dereferenced at line 132
  130.           NativeCallSite cs = (NativeCallSite)obj;
  131.           StringBuilder sb = new StringBuilder();
  132. >         cs.element.renderJavaStyle(sb);
  133.           return sb.toString();
  134.       }
  135.
```

Lines `127-129` in [`NativeCallSite.java`](https://github.com/mozilla/rhino/blob/master/src/org/mozilla/javascript/NativeCallSite.java#L127-L132):

``` java
if (obj == null) {
    return NOT_FOUND;
}
```

It seems that the object `cs` won't be `null` on [Line 132](https://github.com/mozilla/rhino/blob/master/src/org/mozilla/javascript/NativeCallSite.java#L132).
Seems like a false positive to me.

**Comment by jvillard** [comment]
Thanks for the report. Could you please run `inferTraceBugs` and dump the trace corresponding to that NULL_DEREFERENCE report? That would help us see why Infer thinks `obj` can be null here. Thank you!

**Comment by xennygrimmato** [comment]
[Here's the trace](https://gist.github.com/xennygrimmato/3980d96224bbf6e9d2eee55879417ec4).

**Comment by jvillard** [comment]
I was not able to build rhino to confirm, but it seems that this issue is gone as infer doesn't report anything on the following example:

```Java
class Bar {
  void bar() {}
}

class Foo {
  void foo(Object o) {
    if (o == null) {
      return;
    }
    Bar bar = (Bar)o;
    bar.bar();
  }
}
```
