### ISSUE TITLE
Using --reactive with infer after the first time shows that no issues were found

### ISSUE THREAD

**Issue by xennygrimmato** [facebook/infer#431]
- I ran infer for the first time using `infer -- mvn package`

I got a report consisting of some bug descriptions.

- Made some changes in my source code to fix some of the bugs.
- Ran `mvn clean`
- Ran `infer --reactive -- mvn package`

I got a new report, saying no issues were found.

I was expecting infer to show the previous report minus the bugs that I fixed, but instead it showed that there were no bugs at all.

**Comment by jvillard** [comment]
This is the expected behaviour. `--reactive` will only show newly introduced bugs as it will only analyze changed files. See also http://fbinfer.com/docs/infer-workflow.html#differential-workflow
