### ISSUE TITLE
Accessing modulo operator in Java source code

### ISSUE THREAD

**Issue by xennygrimmato** [facebook/infer#432]
In a checker, I want to find statements in a Java source code in which modulo 1 operations are being performed.
For example:

``` java
public class Mod {
    public int modulo_one(int x) {
        int rem = x % 1; // <<
        return rem;
    }
}
```

In order to do this, I am trying to use some thing similar to: [this line in checkers.ml](https://github.com/facebook/infer/blob/master/infer/src/checkers/checkers.ml#L186).
- How do I check if a certain line contains an expression with a `Binop.Mod` operator?
  In order to access the expressions on the left and right hand side of the operator, I am guessing I could use some thing similar to [this line in prop.ml](https://github.com/facebook/infer/blob/master/infer/src/backend/prop.ml#L2001)

``` ocaml
| Exp.BinOp (op, e1, e2) ->
      let e1' = exp_captured_ren ren e1 in
      let e2' = exp_captured_ren ren e2 in
      Exp.BinOp (op, e1', e2')
```

For starting off, I want to check if a node matches a `x % y` expression.

**Comment by sblackshear** [comment]
Hi @xennygrimmato,

[Here](https://github.com/facebook/infer/blob/master/infer/src/checkers/liveness.ml) is a simple checker that you can imitate to get started. This checker computes the set of live variables at each program points, which requires traversing each instruction and expression type in SIL.

Once you've created  a checker that looks like this, you can add it to the checkers to be run in registerCheckers.ml, then run the checkers on code with `infer -a checkers -- <build_cmd>`

For detecting `x % y`, I would do something like this: 

```
let rec contains_mod_exp = function
  | Exp.Binop (Binop.Mod, _, _) -> true
  | Exp.Binop (_, e1, e2) | Lindex (e1, e2) -> contains_mod_exp e1 || contains_mod_exp e2
  | Unop e | Lfield (e, _, _) -> contains_mod_exp e
  | _ -> false
```

To get started, I would replace calls to `exp_get_live` in the checker above with calls to this function.

**Comment by jvillard** [comment]
Please re-open if you have more questions about this.
