### ISSUE TITLE
Getting all defined methods of a Java class

### ISSUE THREAD

**Issue by xennygrimmato** [facebook/infer#434]
Does infer provide a function to get the list of all methods defined within a Java class?
Specifically, I want to check whether a certain class has both - `equals( )` as well as `hashCode( )` methods defined, identical to [this](https://github.com/SonarQubeCommunity/sonar-findbugs/blob/master/src/main/resources/org/sonar/l10n/findbugs/rules/findbugs/HE_USE_OF_UNHASHABLE_CLASS.html) rule in FindBugs.

**Comment by sblackshear** [comment]
You can implement a cluster checker like [this](https://github.com/facebook/infer/blob/master/infer/src/checkers/checkers.ml#L189) one that will be passed all of the procedures declared in a file (check the `all_procs` field). This isn't quite right for inner classes, but will catch most cases (I can explain the workarounds required for the inner class case if you are interested).
