### ISSUE TITLE
Proposal to create API documentation for infer

### ISSUE THREAD

**Issue by xennygrimmato** [facebook/infer#435]
Documenting functionality of various files in the infer source code might be beneficial to contributors now and in the future. Since there is no comprehensive documentation regarding the contents of the infer source code and their functionality, I would like to start writing documentation for the project. However, I am still new to the codebase and not strongly aware of all components of infer.
I would want to know what the maintainers think about this, and if it can be taken forward.

**Comment by jvillard** [comment]
More documentation is always good. If you submit a PR we'll definitely look at it.

**Comment by xennygrimmato** [comment]
Ok, I'll create a PR to start off. Thanks!

**Comment by cristianoc** [comment]
This is the starting point:
```
./infer/src/backend/README.md
./infer/src/checkers/README.md
./infer/src/clang/README.md
./infer/src/eradicate/README.md
./infer/src/IR/README.md
./infer/src/java/README.md
```

**Comment by jvillard** [comment]
The API documentation is now available online here: http://fbinfer.com/docs/internal-API.html
