### ISSUE TITLE
Help with understanding do_analysis in Interproc.ml

### ISSUE THREAD

**Issue by xennygrimmato** [facebook/infer#436]
I am trying to understand the `do_analysis` function/expression present in `Interproc.ml`:

``` ocaml
(** Perform the analysis of an exe_env *)
let do_analysis exe_env =
  let cg = Exe_env.get_cg exe_env in
  let procs_and_defined_children = get_procs_and_defined_children cg in
  let get_calls caller_pdesc =
    let calls = ref [] in
    let f (callee_pname, loc) = calls := (callee_pname, loc) :: !calls in
    Cfg.Procdesc.iter_calls f caller_pdesc;
    IList.rev !calls in
  let init_proc (pname, dep) =
    let pdesc = match Exe_env.get_proc_desc exe_env pname with
      | Some pdesc ->
          pdesc
      | None ->
          assert false in
```

From what I understand, all the defined Nodes in the CG are extracted, after which CFG for each call is created. I am guessing each procedure in the CG is traversed, and after creation of the CFG, it's analysis is stored on disk. I don't understand what exactly is happening in this function though Can someone briefly describe its functionality?
https://github.com/facebook/infer/blob/master/infer/src/backend/interproc.ml#L1435-L1449

**Comment by jvillard** [comment]
I'm afraid we were so slow to respond that this function doesn't exist anymore, sorry... It looks like this was based on the call-graph approach of scheduling the analysis: the analysis would proceed bottom-up starting from the leaves of the global call graph. This is not the case anymore as the analysis can proceed anywhere. An `exe_env` starts from the analysis of a single file and we simple schedule the analysis on each of the procedures defined in that source file: https://github.com/facebook/infer/blob/7f9ff54638b70c7715aefdbf4146ce1d6e807009/infer/src/backend/callbacks.ml#L129

Please re-open if you have more questions about this.
