### ISSUE TITLE
error with lib/xcode_wrappers/clang++, how to skip this file during infer

### ISSUE THREAD

**Issue by stellaloveK** [facebook/infer#439]
In file included from /Users/……/PRTimeFormatter/nspr/prtime.cp:78:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:19:
In file included from /Users/……/infer/facebook-clang-plugins/clang/install/bin/../include/c++/v1/math.h:309:
In file included from /Users/……/infer/facebook-clang-plugins/clang/install/bin/../include/c++/v1/type_traits:363:
/Users/……/infer/facebook-clang-plugins/clang/install/bin/../include/c++/v1/cstddef:53:7: error: 
      no member named 'max_align_t' in the global namespace; did you mean '::UCPRTime::max_align_t'?
using ::max_align_t;
      ^~
In file included from /Users/……/PRTimeFormatter/nspr/prtime.cp:78:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:19:
In file included from /Users/……/infer/facebook-clang-plugins/clang/install/bin/../include/c++/v1/math.h:309:
In file included from /Users/……/infer/facebook-clang-plugins/clang/install/bin/../include/c++/v1/type_traits:363:
In file included from /Users/……/infer/facebook-clang-plugins/clang/install/bin/../include/c++/v1/cstddef:43:
In file included from /Users/……/infer/facebook-clang-plugins/clang/install/bin/../lib/clang/3.8.0/include/stddef.h:118:
/Users/……/infer/facebook-clang-plugins/clang/install/bin/../lib/clang/3.8.0/include/__stddef_max_align_t.h:32:21: note: 
      '::UCPRTime::max_align_t' declared here
typedef long double max_align_t;
                    ^
3 errors generated.

**Comment by jvillard** [comment]
Thanks for your bug report. It looks like something went bad in replacing your compiler with Infer's own version of clang.

Can you please provide more information? Please include:
- the command you used to run infer
- the full output (please use https://gist.github.com/ or equivalent)
- the contents of toplevel.log (also on https://gist.github.com/)

There's no way to skip the compilation of some files using the xcodebuild integration for now.

**Comment by stellaloveK** [comment]
- command:
 infer -- xcodebuild -project testInfer.xcodeproj -target testInfer -configuration Debug -sdk iphonesimulator9.3 -hideShellScriptEnvironment -arch i386

- full  output:
[https://gist.github.com/stellaloveK/8a728d2e4774c78ecf35d1b933b84ddf](url)

- what is toplevel.log??

In my project, there are many subprojects, can skip a subproject?
Originally I thought parameters(--skip-clang-analysis-in-path or --infer-blacklist-path-regex or --infer-whitelist-path-regex) can skip some files, but they do not work.

**Comment by mikechengwei** [comment]
i aslo want to skip some files,for example Pods. how to to it?

**Comment by jberdine** [comment]
This issue may be resolved by using the xcpretty integration for xcodebuild in the current 0.9.4 release.  Optimistically closing, but please reopen if the problem remains.
