### ISSUE TITLE
build fail with ios app

### ISSUE THREAD

**Issue by zhangying19871987** [facebook/infer#446]
The infer version I used is V0.9.2.
when I execute
infer -- xcodebuild -workspace QQNews.xcworkspace -scheme QQNews -configuration Debug -sdk iphoneos
I met the error
clang -cc1as: error: error reading '/var/folders/yt/mcn2wbd112g1pyjcn84h4c3h0000gn/T/darwin64_x86_64-c68750.s'

**Comment by jvillard** [comment]
Thanks for the report @zhangying19871987 

Could you edit [this line](https://github.com/facebook/infer/blob/a31a735e355aeb0cb28377c7b25583c4bd374e2e/infer/lib/clang_wrappers/hijack_and_normalize_clang_command.sh#L30) to change

```sh
if [ "$1" = "-cc1" ]; then
```

to

```sh
if [ "$1" = "-cc1" ] || [ "$1" = "-cc1as" ]; then
```

and report back?

**Comment by zhangying19871987** [comment]
I have change if [ "$1" = "-cc1" ]; then to if [ "$1" = "-cc1" ] || [ "$1" = "-cc1as" ]; then
I got the error as follows：
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/usr/include/module.m
odulemap:53:11: error: header 'float.h' not found
                        header "float.h" // note: supplied by compiler
                               ^
While building module 'Foundation' imported from /Users/selmazhang/workspace/news_ios_codeCheck/QNCore/QNCore/QNCrashGuard
/QNCrashGuard.h:9:
While building module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platfor
m/Developer/SDKs/iPhoneOS9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In file included from <module-includes>:1:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/System/Library/Frame
works/CoreFoundation.framework/Headers/CoreFoundation.h:11:10: note: submodule of top-level module 'Darwin' implicitly imp
orted here
#include <sys/types.h>
         ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/System/Library/Frame
works/CoreFoundation.framework/Headers/CoreFoundation.h:12:10: fatal error: 'stdarg.h' file not found
#include <stdarg.h>
         ^
2 errors generated.
While building module 'Foundation' imported from /Users/selmazhang/workspace/news_ios_codeCheck/QNCore/QNCore/QNCrashGuard
/QNCrashGuard.h:9:
In file included from <module-includes>:1:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/System/Library/Frame
works/Foundation.framework/Headers/Foundation.h:6:10: fatal error: could not build module 'CoreFoundation'
#include <CoreFoundation/CoreFoundation.h>
 ~~~~~~~~^
While building module 'Foundation' imported from /Users/selmazhang/workspace/news_ios_codeCheck/QNCore/QNCore/QNCrashGuard
/QNCrashGuard.h:9:
While building module 'ObjectiveC' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/De
veloper/SDKs/iPhoneOS9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:6:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/usr/include/module.m
odulemap:53:11: error: header 'float.h' not found
                        header "float.h" // note: supplied by compiler
                               ^
While building module 'Foundation' imported from /Users/selmazhang/workspace/news_ios_codeCheck/QNCore/QNCore/QNCrashGuard
/QNCrashGuard.h:9:
While building module 'ObjectiveC' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/De
veloper/SDKs/iPhoneOS9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:6:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sd
k/usr/include/objc/./message.h:29:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/usr/include/objc/obj
c.h:31:10: note: submodule of top-level module 'Darwin' implicitly imported here
#include <sys/types.h>      // for __DARWIN_NULL
         ^
While building module 'Foundation' imported from /Users/selmazhang/workspace/news_ios_codeCheck/QNCore/QNCore/QNCrashGuard
/QNCrashGuard.h:9:
While building module 'ObjectiveC' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/De
veloper/SDKs/iPhoneOS9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:6:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/usr/include/module.m
odulemap:53:11: error: header 'float.h' not found
                        header "float.h" // note: supplied by compiler
                               ^
While building module 'Foundation' imported from /Users/selmazhang/workspace/news_ios_codeCheck/QNCore/QNCore/QNCrashGuard
/QNCrashGuard.h:9:
While building module 'ObjectiveC' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/De
veloper/SDKs/iPhoneOS9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:6:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sd
k/usr/include/objc/./message.h:29:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/usr/include/objc/obj
c.h:32:10: note: submodule of top-level module 'Darwin' implicitly imported here
#include <Availability.h>
         ^
While building module 'Foundation' imported from /Users/selmazhang/workspace/news_ios_codeCheck/QNCore/QNCore/QNCrashGuard
/QNCrashGuard.h:9:
While building module 'ObjectiveC' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/De
veloper/SDKs/iPhoneOS9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:6:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/usr/include/module.m
odulemap:53:11: error: header 'float.h' not found
                        header "float.h" // note: supplied by compiler
                               ^
While building module 'Foundation' imported from /Users/selmazhang/workspace/news_ios_codeCheck/QNCore/QNCore/QNCrashGuard
/QNCrashGuard.h:9:
While building module 'ObjectiveC' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/De
veloper/SDKs/iPhoneOS9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:6:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sd
k/usr/include/objc/./message.h:29:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sd
k/usr/include/objc/objc.h:33:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/usr/include/objc/obj
c-api.h:28:10: note: submodule of top-level module 'Darwin' implicitly imported here
#include <Availability.h>
         ^
While building module 'Foundation' imported from /Users/selmazhang/workspace/news_ios_codeCheck/QNCore/QNCore/QNCrashGuard
/QNCrashGuard.h:9:
While building module 'ObjectiveC' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/De
veloper/SDKs/iPhoneOS9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:6:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/usr/include/module.m
odulemap:53:11: error: header 'float.h' not found
header "float.h" // note: supplied by compiler
                               ^
While building module 'Foundation' imported from /Users/selmazhang/workspace/news_ios_codeCheck/QNCore/QNCore/QNCrashGuard
/QNCrashGuard.h:9:
While building module 'ObjectiveC' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/De
veloper/SDKs/iPhoneOS9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:6:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sd
k/usr/include/objc/./message.h:29:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sd
k/usr/include/objc/objc.h:33:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/usr/include/objc/obj
c-api.h:29:10: note: submodule of top-level module 'Darwin' implicitly imported here
#include <AvailabilityMacros.h>
         ^
While building module 'Foundation' imported from /Users/selmazhang/workspace/news_ios_codeCheck/QNCore/QNCore/QNCrashGuard
/QNCrashGuard.h:9:
While building module 'ObjectiveC' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/De
veloper/SDKs/iPhoneOS9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:6:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/usr/include/module.m
odulemap:53:11: error: header 'float.h' not found
                        header "float.h" // note: supplied by compiler
                               ^
While building module 'Foundation' imported from /Users/selmazhang/workspace/news_ios_codeCheck/QNCore/QNCore/QNCrashGuard
/QNCrashGuard.h:9:
While building module 'ObjectiveC' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/De
veloper/SDKs/iPhoneOS9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:6:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sd
k/usr/include/objc/./message.h:29:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sd
k/usr/include/objc/objc.h:33:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/usr/include/objc/obj
c-api.h:30:10: note: submodule of top-level module 'Darwin' implicitly imported here
#include <TargetConditionals.h>
         ^
While building module 'Foundation' imported from /Users/selmazhang/workspace/news_ios_codeCheck/QNCore/QNCore/QNCrashGuard
/QNCrashGuard.h:9:
While building module 'ObjectiveC' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/De
veloper/SDKs/iPhoneOS9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:6:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sd
k/usr/include/objc/./message.h:29:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/usr/include/objc/obj
c.h:34:10: fatal error: 'stdbool.h' file not found
#include <stdbool.h>
         ^
6 errors generated.
While building module 'Foundation' imported from /Users/selmazhang/workspace/news_ios_codeCheck/QNCore/QNCore/QNCrashGuard
/QNCrashGuard.h:9:
While building module 'Dispatch' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Deve
loper/SDKs/iPhoneOS9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSDateIntervalFormatter.h:6:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/usr/include/module.m
odulemap:53:11: error: header 'float.h' not found
                        header "float.h" // note: supplied by compiler
                               ^
While building module 'Foundation' imported from /Users/selmazhang/workspace/news_ios_codeCheck/QNCore/QNCore/QNCrashGuard
/QNCrashGuard.h:9:

**Comment by zhangying19871987** [comment]
After I edit the line, I got another error as follows:
** BUILD FAILED **


The following build commands failed:
        CompileC /Users/selmazhang/Library/Developer/Xcode/DerivedData/QQNews-dzxfdpizqronydacwqerxzqgevkb/Build/Intermediates/QNCore.build/Debug-iphoneos/QNCore.build/Objects-normal/armv7/darwin64_x86_64.o QNCore/QNCrashGuard/3rd/JSPatch/Extensions/JPCFunction/libffi/src/x86/darwin64_x86_64.S normal armv7 assembler-with-cpp com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by akotulski** [comment]
which version of xcode are you using (you can run `xcodebuild -version` to find out)?

**Comment by zhangying19871987** [comment]
Xcode 7.3
Build version 7D175

**Comment by zhangying19871987** [comment]
I comment the line in infer/lib/clang_wrappers/hijack_and_normalize_clang_command.sh
I change the line 

sed -e "s#^[[:space:]]\"\([^\"]*\)\" \"-cc1\" \(.*\)\$# \"$CLANG_CC1_CAPTURE\" \"-cc1\" \2#g" | \

to

#sed -e "s#^[[:space:]]\"\([^\"]*\)\" \"-cc1\" \(.*\)\$# \"$CLANG_CC1_CAPTURE\" \"-cc1\" \2#g" | \

And now my ios app build success, Can I do like this?

**Comment by jvillard** [comment]
Could you paste the full output of infer prior to the changes please? Please use a paste site such as https://gist.github.com/.

**Comment by jvillard** [comment]
You could also try not executing -cc1as commands by inserting this line right after the `sed` line that you commented out (but uncomment the `sed` line as well):

```
        grep -v "\"-cc1as\"" | \
```

**Comment by jvillard** [comment]
More precisely, could try to apply this diff? Thanks!

https://gist.github.com/jvillard/5fd9b9dc32a402aa5347edc5d327f45b

**Comment by zhangying19871987** [comment]
The problem is I got the error when I compile my ios project

clang -cc1as: error: error reading '/var/folders/yt/mcn2wbd112g1pyjcn84h4c3h0000gn/T/darwin64_x86_64-08684d.s'
Command /Users/selmazhang/workspace/infer-osx-v0.9.2/infer/lib/python/inferlib/../../../lib/xcode_wrappers/clang failed wi
th exit code 1 
** BUILD FAILED **

The following build commands failed:
CompileC /Users/selmazhang/Library/Developer/Xcode/DerivedData/QQNews-dzxfdpizqronydacwqerxzqgevkb/Build/Intermediates/QNCore.build/Debug-iphoneos/QNCore.build/Objects-normal/armv7/darwin64_x86_64.o QNCore/QNCrashGuard/3rd/JSPatch/Extensions/JPCFunction/libffi/src/x86/darwin64_x86_64.S normal armv7 assembler-with-cpp com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)


I do not change anything about infer except that change

if [ "$1" = "-cc1" ]; then
to

if [ "$1" = "-cc1" ] || [ "$1" = "-cc1as" ]; then


Please tell me  what shall I do ?

**Comment by zhangying19871987** [comment]
I try not executing -cc1as commands by inserting this line right after the sed line

        grep -v "\"-cc1as\"" | \


and I got error as well:

/Users/selmazhang/workspace/news_ios_codeCheck/QNCore/QNCore/QNCrashGuard/3rd/JSPatch/Extensions/JPCFunction/libffi/src/ar
m/trampoline_armv7.S:3:1: error: expected identifier or '('
# GENERATED CODE - DO NOT EDIT
^
/Users/selmazhang/workspace/news_ios_codeCheck/QNCore/QNCore/QNCrashGuard/3rd/JSPatch/Extensions/JPCFunction/libffi/src/ar
m/trampoline_armv7.S:41:5: error: unknown type name 'ldr'
    ldr r0, [pc, #-4092]
    ^
/Users/selmazhang/workspace/news_ios_codeCheck/QNCore/QNCore/QNCrashGuard/3rd/JSPatch/Extensions/JPCFunction/libffi/src/ar
m/trampoline_armv7.S:41:14: error: use of undeclared identifier 'pc'
    ldr r0, [pc, #-4092]
             ^
/Users/selmazhang/workspace/news_ios_codeCheck/QNCore/QNCore/QNCrashGuard/3rd/JSPatch/Extensions/JPCFunction/libffi/src/ar
m/trampoline_armv7.S:44:8: error: expected ';' after top level declarator
    ldr pc, [pc, #-4092]
       ^
       ;
4 errors generated.
Command /Users/selmazhang/workspace/infer-osx-v0.9.2/infer/lib/python/inferlib/../../../lib/xcode_wrappers/clang failed wi
th exit code 1

** BUILD FAILED **


The following build commands failed:
        CompileC /Users/selmazhang/Library/Developer/Xcode/DerivedData/QQNews-dzxfdpizqronydacwqerxzqgevkb/Build/Intermediates/QNCore.build/Debug-iphoneos/QNCore.build/Objects-normal/armv7/trampoline_armv7.o QNCore/QNCrashGuard/3rd/JSPatch/Extensions/JPCFunction/libffi/src/arm/trampoline_armv7.S normal armv7 assembler-with-cpp com.apple.compilers.llvm.clang.1_0.compiler

**Comment by zhangying19871987** [comment]
It was fixed this issue. Thanks a lot.

**Comment by jberdine** [comment]
Infer 0.9.3 has been released, please try and reopen this issue if the problem remains.
