### ISSUE TITLE
v0.9.2 uses too much cpus

### ISSUE THREAD

**Issue by chen881129** [facebook/infer#448]
Too much processes:
```
ps -ef | grep InferAnalyze -c
41
```

High load:
`load average: 19.18, 7.57, 4.23`

My OS is centos7, release: 7.2.1511.

**Comment by akotulski** [comment]
I think by default infer uses as many processes as there are cores on the machine (specifically, the result of `getconf _NPROCESSORS_ONLN 2>/dev/null`). How many cores your machine has?
 
If you are using `infer -- make ...` or `infer -- buck build ...`, you can use `-l` option limit load average. You can also decrease number of parallel jobs, by passing `-j` flag.

**Comment by akotulski** [comment]
Closing issue for now, feel free to reopen if you need further assistance
