### ISSUE TITLE
command not found: inferTraceBugs

### ISSUE THREAD

**Issue by yishuiliunian** [facebook/infer#449]
i install infer from brew ,but the  inferTraceBugs not found 
<img width="569" alt="677feb40-b19f-43f5-a6ee-56f16ed7346d" src="https://cloud.githubusercontent.com/assets/846525/18075292/0a392b12-6ea6-11e6-9763-130653740105.png">

**Comment by jvillard** [comment]
Is this infer 0.9.2?

**Comment by yishuiliunian** [comment]
Infer version v0.8.1

**Comment by jvillard** [comment]
Upgrading to 0.9.2 with brew should fix this. Please reopen if it doesn't.

**Comment by crespoxiao** [comment]
Infer version v0.13.1 also has this problem

**Comment by jvillard** [comment]
@crespoxiao it has been replaced by `infer explore`. See #881.

**Comment by crespoxiao** [comment]
thank you. " infer explore --html"  works     @jvillard
