### ISSUE TITLE
Infer looks for hardcoded command names when run on shell

### ISSUE THREAD

**Issue by kageiit** [facebook/infer#453]
In https://github.com/facebook/infer/blob/e1f19192c07caf2fa0a2ea4fd6692e3de9cddbcd/infer/lib/python/infer.py#L34

the commands to look for are hardcoded to invoke the correct modules. This prevents users the flexibility to wrap such commands in their own.

For example, we wrap all buck invocations in a `buckw` script to perform some steps before the actual buck run and invoke it like `./buckw build target`, very similar to `./gradlew task`

Can there be a configuration option in inferconfig that can specify aliases to different commands?

**Comment by akotulski** [comment]
Right now there is no such option - you may try adding `buckw` to the list in line you provided, but it's not guaranteed to out of the box for `buck` (we may have hardcoded `buck` in our buck integration).

Another short term solution is to make `which buck` point to your script, but I can imagine it may not be an option for you.

As for adding an option, we could add it in following form (modulo naming):
```
  infer --run-capture-module buck -- my_great_custom_script build <buck_target>
```
Allowing such option may lead to maintenance problems - we are assuming a lot under the hood which means that `my_great_custom_script` needs to work exactly as `buck`. In case of `buckw` this should be true. In case of some random script/binary it will lead to a lot of pain when upgrading infer (to whoever uses this option)
@jvillard @jberdine - do you have any objections/alternatives in regards to adding `--run-capture-module` option to infer?

**Comment by kageiit** [comment]
We circumvented this by writing an `inferw` wrapper that sets up the path correctly and replaces `buckw` with `buck` internally and invokes the right command

**Comment by akotulski** [comment]
Yes, that works as well. Thanks for letting us know about this use case.
