### ISSUE TITLE
Support skip translation using path filters

### ISSUE THREAD

**Issue by kageiit** [facebook/infer#454]
Seems like the skip translation matchers only match with source file contents or method names

https://github.com/facebook/infer/blob/7e59032a427769e8003d8bf3c34d207b81f47d3d/infer/src/backend/inferconfig.ml#L196

This makes it very hard to exclude auto generated source files from codegen for skipping translation in Infer.

Seems like the a new `FilePatternMatcher` can be supported for this.

Once that is available, it would be nice to auto exclude generated source folders in build systems like buck automatically

**Comment by jeremydubreil** [comment]
What kind of information could be used to distinguish those generated files ?

**Comment by kageiit** [comment]
The best information to distinguish these files is the directory where they come from. All generated sources typically have an ancestor dir that contains them.

Looking at the generated source itself is not reliable because all annotation processors/gradle plugins etc do not produce similar generated code or annotate them the same way

**Comment by jvillard** [comment]
Looks like this was fixed, there is now the `--skip-analysis-in-path` option.
