### ISSUE TITLE
iOS App: Build Failed

### ISSUE THREAD

**Issue by LeeY0510** [facebook/infer#455]
/<Document_ROOT>/<Project_Name>/Vendors/ReactNative/React/Core/React/Profiler/RCTProfileTrampoline-arm.S:15:3: error: 
      expected identifier or '('
  .thumb
  ^
/<Document_ROOT>/<Project_Name>/Vendors/ReactNative/React/Core/React/Profiler/RCTProfileTrampoline-arm.S:37:3: error: 
      unknown type name 'mov'
  mov r0, #0xc
  ^
/<Document_ROOT>/<Project_Name>/Vendors/ReactNative/React/Core/React/Profiler/RCTProfileTrampoline-arm.S:37:11: error: 
      expected identifier or '('
  mov r0, #0xc
          ^
/<Document_ROOT>/<Project_Name>/Vendors/ReactNative/React/Core/React/Profiler/RCTProfileTrampoline-arm.S:37:10: error: 
      expected ';' after top level declarator
  mov r0, #0xc
         ^
         ;
4 errors generated.
clang -cc1as: error: error reading '/var/folders/50/m9jqld1s6c7dx9vp8cv3wf8c0000gn/T/RCTProfileTrampoline-arm-134fcd.s'
Command /Users/Lee/Documents/RRX/git/infer-osx-v0.9.2/infer/lib/python/inferlib/../../../lib/xcode_wrappers/clang failed with exit code 1

------------------- toplevel.log ----------------------
[INFO] output of locale.getdefaultlocale(): ('en_US', 'UTF-8')
[INFO] encoding we chose in the end: UTF-8
[INFO] Running command /<Document_Root>/infer-osx-v0.9.2/infer/bin/../lib/python/infer.py --multicore 8 --out /<Document_Root>/JDBApp/JDBApp/infer-out --project_root /<Document_Root>/JDBApp/JDBApp -- xcodebuild -scheme <Project_Name> -workspace <Project_Name>.xcworkspace -configuration Debug
[INFO] Path to infer script /<Document_Root>/infer-osx-v0.9.2/infer/bin/../lib/python/infer.py (/<Document_Root>/infer-osx-v0.9.2/infer/lib/python/infer.py)
[INFO] 
[INFO] Platform: Darwin-15.5.0-x86_64-i386-64bit
[INFO] PATH=/<Document_Root>/infer-osx-v0.9.2/infer/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Users/Lee/.opam/infer-4.02.3/bin:/usr/local/mysql/bin:/<Document_Root>/infer-osx-v0.9.2/infer/bin:/Users/Lee/.rvm/gems/ruby-2.0.0-p643/bin:/Users/Lee/.rvm/gems/ruby-2.0.0-p643@global/bin:/Users/Lee/.rvm/rubies/ruby-2.0.0-p643/bin:/Users/Lee/.opam/system/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/Users/Lee/.rvm/bin:/Users/Lee/.rvm/bin:/bin:/<Document_Root>/infer/infer/lib/python
[INFO] SHELL=/bin/zsh
[INFO] PWD=/<Document_Root>/JDBApp/JDBApp
[INFO] Xcode version:
Xcode 7.3.1
Build version 7D1014

[INFO] clang version:
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

[ERROR] Error during capture phase, exiting
 
I need your kind help. I will provide all helpful information to solve the issue.

**Comment by akotulski** [comment]
We encountered other similar reports recently:
https://github.com/facebook/infer/issues/450
https://github.com/facebook/infer/issues/446

It has to do with compiling assembly code (somehow infer doesn't run the right thing). The problem with solving those issue is that it's hard for us to reproduce.

Would it be possible for you to share complete example that doesn't work for you?
I suspect it might be enough to put `ReactNative` library in ///Vendors and compile it same way you are compiling in your app.

**Comment by akotulski** [comment]
I think I managed to reproduce and fix the issue with https://github.com/facebook/infer/commit/0817ab0ec221d97c6685e0f22f88c967b2b471df. You can follow instructions from https://github.com/facebook/infer/issues/450#issuecomment-245879215 to quickly try the fix without having to recompile infer

**Comment by LeeY0510** [comment]
Thx for ur kind reply. It was fixed this issue. Thanks a lot.
