### ISSUE TITLE
infer build error under xcode 8 -sdk iphonesimulator10.0

### ISSUE THREAD

**Issue by frankyliu** [facebook/infer#464]
We used the infer 0.8.1 and  upgraded xcode version to xcode8 and encounter error as below:

build command:
infer -- xcodebuild -scheme xxxx -configuration Release -sdk iphonesimulator10.0

error message:

While building module 'MessageUI' imported from /Users/xxxx/IOS_INFER/source/xxxx/xxx/xxx.m:12:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk/System/Library/Frameworks/MessageUI.framework/Headers/MessageUI.h:10:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk/System/Library/Frameworks/MessageUI.framework/Headers/MFMailComposeViewController.h:8:9: fatal error: could not build module 'UIKit'
#import <UIKit/UIKit.h>
#import <UIKit/UIKit.h>
 ~~~~~~~^
1 error generated.

**Comment by jvillard** [comment]
Hi @frankyliu,

- Does `xcodebuild -scheme xxxx -configuration Release -sdk iphonesimulator10.0` succeed on its own?
- Do you still get an error with infer 0.9.2?
- If so, do you still get an error with the latest master from github? We recently upgraded the version of clang used by infer to deal with the latest xcode release.

**Comment by frankyliu** [comment]
thanks jvillard quickly response.
1. we have tried xcodebuild for the project, it was compiled green.
2. also we tried the infer 0.9.2, the same issue there.
3. ok, we will try it today. 

By the way,  when the latest version will be released?

**Comment by jvillard** [comment]
We are working on publishing a new release with the newer clang.

**Comment by jberdine** [comment]
Infer 0.9.3 has been released, please try and reopen this issue if the problem remains.
