### ISSUE TITLE
attempting to build only the clang analyzers with `./build-infer.sh clang` fails

### ISSUE THREAD

**Issue by hapton** [facebook/infer#466]
```
nfer-deps-6F1M
preparing build... 
checking for .release... no
checking for .facebook... no
checking whether to use the compilers in /Users/gaosong/Downloads/infer-0.9.3/facebook-clang-plugins/clang/install/bin... no
checking for shasum... shasum
checking for cmake... cmake
checking for python2.7... python2.7
checking for xcode-select... xcode-select
checking for clang... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln -s works... yes
checking whether make sets $(MAKE)... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking how to run the C preprocessor... clang -E
checking for clang++... clang++
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ accepts -g... yes
checking if the C/C++ compiler is recent enough... yes
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for inttypes.h... (cached) yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking malloc.h usability... no
checking malloc.h presence... no
checking for malloc.h... no
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/mount.h usability... yes
checking sys/mount.h presence... yes
checking for sys/mount.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/statfs.h usability... no
checking sys/statfs.h presence... no
checking for sys/statfs.h... no
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking wchar.h usability... yes
checking wchar.h presence... yes
checking for wchar.h... yes
checking wctype.h usability... yes
checking wctype.h presence... yes
checking for wctype.h... yes
checking for ocamlc... ocamlc
OCaml version is 4.02.3
OCaml library path is /Users/gaosong/.opam/infer-4.02.3/lib/ocaml
checking for ocamlopt... ocamlopt
checking for ocamlc.opt... ocamlc.opt
checking for ocamlopt.opt... ocamlopt.opt
checking for dynlink.cmxa... yes
checking for ocaml... ocaml
checking for ocamldep... ocamldep
checking for ocamlmktop... ocamlmktop
checking for ocamlmklib... ocamlmklib
checking for ocamldoc... ocamldoc
checking for ocamlbuild... ocamlbuild
checking if OCaml version is >= 4.02.3... yes
checking for ocamlfind... ocamlfind
checking for ocamllex... ocamllex
checking for ocamllex.opt... ocamllex.opt
checking for ocamlyacc... ocamlyacc
checking for OCaml findlib package atdgen version 1.6.0... /Users/gaosong/.opam/infer-4.02.3/lib/atdgen
checking for OCaml findlib package biniou... /Users/gaosong/.opam/infer-4.02.3/lib/biniou
checking for OCaml findlib package camlzip... /Users/gaosong/.opam/infer-4.02.3/lib/camlzip/../zip
checking for OCaml findlib package easy-format... /Users/gaosong/.opam/infer-4.02.3/lib/easy-format
checking for OCaml findlib package extlib version 1.5.4... /Users/gaosong/.opam/infer-4.02.3/lib/extlib
checking for OCaml findlib package oUnit version 2.0.0... /Users/gaosong/.opam/infer-4.02.3/lib/oUnit
checking for OCaml findlib package reason... /Users/gaosong/.opam/infer-4.02.3/lib/reason
checking for OCaml findlib package yojson... /Users/gaosong/.opam/infer-4.02.3/lib/yojson
checking for rebuild... rebuild
checking for atdgen... atdgen
checking which version of Buck to use... a965937ccdadf8119a98ab766c3feb0708dc424e
checking for getconf... getconf
checking the number of cpus the build host has... 4
configure: saving configure flags to ./config.flags
configure: creating ./config.status
config.status: creating Makefile.config
export CC="clang" CFLAGS="-g -O2"; \
    export CXX="clang++" CXXFLAGS="-g -O2"; \
    export CPP="clang -E" LDFLAGS="" LIBS=""; \
    /Users/gaosong/Downloads/infer-0.9.3/facebook-clang-plugins/clang/setup.sh 
Clang is already installed according to /Users/gaosong/Downloads/infer-0.9.3/facebook-clang-plugins/clang/installed.version
Nothing to do, exiting.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C /Users/gaosong/Downloads/infer-0.9.3/facebook-clang-plugins/libtooling all \
      CC=clang CXX=clang++ \
      CFLAGS="-g -O2" CXXFLAGS="-g -O2" \
      CPP="clang -E" LDFLAGS="" LIBS="" \
      LOCAL_CLANG=/Users/gaosong/Downloads/infer-0.9.3/facebook-clang-plugins/clang/install/bin/clang \
      CLANG_PREFIX=/Users/gaosong/Downloads/infer-0.9.3/facebook-clang-plugins/clang/install \
      CLANG_INCLUDES=/Users/gaosong/Downloads/infer-0.9.3/facebook-clang-plugins/clang/install/include
make[1]: Nothing to be done for `all'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C /Users/gaosong/Downloads/infer-0.9.3/facebook-clang-plugins/clang-ocaml all \
          build/clang_ast_proj.ml build/clang_ast_proj.mli \
      CC=clang CXX=clang++ \
      CFLAGS="-g -O2" CXXFLAGS="-g -O2" \
      CPP="clang -E" LDFLAGS="" LIBS="" \
      LOCAL_CLANG=/Users/gaosong/Downloads/infer-0.9.3/facebook-clang-plugins/clang/install/bin/clang \
      CLANG_PREFIX=/Users/gaosong/Downloads/infer-0.9.3/facebook-clang-plugins/clang/install \
      CLANG_INCLUDES=/Users/gaosong/Downloads/infer-0.9.3/facebook-clang-plugins/clang/install/include
make[1]: Nothing to be done for `all'.
make[1]: `build/clang_ast_proj.ml' is up to date.
make[1]: `build/clang_ast_proj.mli' is up to date.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C /Users/gaosong/Downloads/infer-0.9.3/infer/src infer
TMPFILE=$(mktemp backend/version.ml.tmp.XXXX); \
    INFER_GIT_COMMIT=$(git --work-tree=../.. --git-dir=../../.git rev-parse --short HEAD || printf "unknown"); \
    INFER_GIT_BRANCH=$(git --work-tree=../.. --git-dir=../../.git rev-parse --abbrev-ref HEAD || printf "unknown"); \
    sed \
      -e 's|@INFER_MAJOR[@]|0|g' \
      -e 's|@INFER_MINOR[@]|9|g' \
      -e 's|@INFER_PATCH[@]|3|g' \
      -e 's|@IS_RELEASE_TREE[@]|no|g' \
      -e "s|@INFER_GIT_COMMIT[@]|$INFER_GIT_COMMIT|g" \
      -e "s|@INFER_GIT_BRANCH[@]|$INFER_GIT_BRANCH|g" \
      backend/version.ml.in > "$TMPFILE"; \
    /usr/bin/install -c -m 644 -C "$TMPFILE" backend/version.ml; \
    rm -f "$TMPFILE"
fatal: Not a git repository: '../../.git'
fatal: Not a git repository: '../../.git'
rebuild -r -cflags -g -lflags -g -cflags -short-paths -cflags -safe-string -cflags -principal -cflags -strict-formats -cflags -strict-sequence -cflags -w,+5+6+8+10+11+12+18+19+20+23+26+29+27+32+33+34+35+37+38+39+50-4-9-40-41-42-45-48 -tag-line "<*{clang/clang_ast_*,backend/jsonbug_*,checkers/stacktree_*}>: warn(-27-32-35-39)" -pkgs atdgen,extlib,oUnit,str,unix,yojson,zip -cflags -annot -cflags -bin-annot -j 4 -I IR -I backend -I checkers -I eradicate -I harness -I quandary -I opensource -I clang -build-dir /Users/gaosong/Downloads/infer-0.9.3/infer/_build/infer backend/infer.native backend/InferAnalyze.native backend/InferPrint.native unit/inferunit.native scripts/checkCopyright.native scripts/StatsAggregator.native unit/inferunit.native clang/cMain.native integration/BuckCompilationDatabase.native
+ env OCAMLOPT="ocamlopt.opt" /Users/gaosong/.opam/infer-4.02.3/bin/reopt -c -g -short-paths -safe-string -principal -strict-formats -strict-sequence -w +5+6+8+10+11+12+18+19+20+23+26+29+27+32+33+34+35+37+38+39+50-4-9-40-41-42-45-48 -annot -bin-annot -I /Users/gaosong/.opam/infer-4.02.3/lib/atd -I /Users/gaosong/.opam/infer-4.02.3/lib/atdgen -I /Users/gaosong/.opam/infer-4.02.3/lib/biniou -I /Users/gaosong/.opam/infer-4.02.3/lib/easy-format -I /Users/gaosong/.opam/infer-4.02.3/lib/extlib -I /Users/gaosong/.opam/infer-4.02.3/lib/oUnit -I /Users/gaosong/.opam/infer-4.02.3/lib/ocaml -I /Users/gaosong/.opam/infer-4.02.3/lib/yojson -I /Users/gaosong/.opam/infer-4.02.3/lib/zip -I checkers -I quandary -I opensource -I IR -I harness -I eradicate -I clang -I backend -o checkers/patternMatch.cmx checkers/patternMatch.ml
File "checkers/patternMatch.ml", line 29, characters 68-85:
Error: Unbound module JConfig
Hint: Did you mean Config?
Command exited with code 2.
Compilation unsuccessful after building 305 targets (304 cached) in 00:00:01.
make[1]: *** [infer] Error 10
make: *** [src_build] Error 2

  compilation failure; you can try running

    make clean
    ./build-infer.sh clang
```

I fail to install infer 0.9.3 release (./build-infer.sh clang),please give me some advice.Thanks.

**Comment by jberdine** [comment]
Can you tell us explicitly how you got the source code (e.g. git clone or release tarball, etc.) and what commands you executed leading to this failure?

**Comment by hapton** [comment]
I download the release package and unzip it.And brew install dependency, then i /build-infer.sh clang.
<img width="960" alt="2016_9_25_ 11_00" src="https://cloud.githubusercontent.com/assets/1235170/18812718/3df54f8a-830f-11e6-9809-a0a20c0364b0.png">

**Comment by hapton** [comment]
opam list
# Installed packages for infer-4.02.3:
ANSITerminal              0.7  Basic control of ANSI compliant terminals and the
atd                     1.2.0  Parser for the ATD data format description langua
atdgen                 1.10.0  Generates efficient JSON serializers, deserialize
base-bigarray            base  Bigarray library distributed with the OCaml compi
base-bytes               base  Bytes library distributed with the OCaml compiler
base-ocamlbuild          base  OCamlbuild binary and libraries distributed with 
base-threads             base  Threads library distributed with the OCaml compil
base-unix                base  Unix library distributed with the OCaml compiler
BetterErrors            0.0.1  Better compiler error output.
bin_prot            113.33.03  A binary protocol generator
biniou                 1.0.12  Binary data format designed for speed, safety, ea
camlp4                 4.02+7  Camlp4 is a system for writing extensible parsers
camlzip                  1.05  Provides easy access to compressed files in ZIP, 
camomile                0.8.5  A comprehensive Unicode library
conf-autoconf             0.1  Virtual package relying on autoconf installation.
conf-m4                     1  Virtual package relying on m4
conf-ncurses         1+system  Virtual package relying on ncurses
conf-which                  1  Virtual package relying on which
core                113.33.03  Industrial strength alternative to OCaml's standa
core_kernel         113.33.03  Industrial strength alternative to OCaml's standa
cppo                    1.4.0  Equivalent of the C preprocessor for OCaml progra
easy-format             1.2.0  High-level and functional interface to the Format
extlib                  1.5.4  A complete yet small extension for OCaml standard
fieldslib           113.33.03  Syntax extension to define first class values rep
javalib                 2.3.1  Javalib is a library written in OCaml which aims 
js-build-tools      113.33.04  Collection of tools to help building Jane Street 
lambda-term            1.10.1  Terminal manipulation library for OCaml
lwt                     2.5.2  A cooperative threads library for OCaml
menhir               20160825  LR(1) parser generator
merlin                  2.3.1 (pinned)  Editor helper, provides completion, typing and so
merlin_extend             0.2 (pinned)  
ocamlbuild                  0  Build system distributed with the OCaml compiler 
ocamlfind               1.6.2  A library manager for OCaml
ounit                   2.0.0  Unit testing framework loosely based on HUnit. It
ppx_assert          113.33.03  Assert-like extension nodes that raise useful err
ppx_bench           113.33.03  Syntax extension for writing in-line benchmarks i
ppx_bin_prot        113.33.03  Generation of bin_prot readers and writers from t
ppx_compare         113.33.03  Generation of comparison functions from types
ppx_core            113.33.03  Standard library for ppx rewriters
ppx_custom_printf   113.33.03  Printf-style format-strings for user-defined stri
ppx_deriving              4.0  Type-driven code generation for OCaml >=4.02
ppx_driver          113.33.03  Feature-full driver for OCaml AST transformers
ppx_enumerate       113.33.03  Generate a list containing all values of a finite
ppx_expect          113.33.03  Cram like framework for OCaml
ppx_fail            113.33.03  Add location to calls to failwiths
ppx_fields_conv     113.33.03  Generation of accessor and iteration functions fo
ppx_here            113.33.03  Expands [%here] into its location
ppx_inline_test     113.33.03  Syntax extension for writing in-line tests in oca
ppx_jane            113.33.03  Standard Jane Street ppx rewriters
ppx_let             113.33.03  Monadic let-bindings
ppx_optcomp         113.33.03  Optional compilation for OCaml
ppx_pipebang        113.33.03  A ppx rewriter that inlines reverse application o
ppx_sexp_conv       113.33.03  Generation of S-expression conversion functions f
ppx_sexp_message    113.33.03  A ppx rewriter for easy construction of s-express
ppx_sexp_value      113.33.03  A ppx rewriter that simplifies building s-express
ppx_tools          5.0+4.02.0  Tools for authors of ppx rewriters and other synt
ppx_type_conv       113.33.03  Support Library for type-driven code generators
ppx_typerep_conv    113.33.03  Generation of runtime types from type declaration
ppx_variants_conv   113.33.03  Generation of accessor and iteration functions fo
re                      1.7.0  RE is a regular expression library for OCaml
react                   1.2.0  Declarative events and signals for OCaml
reason                  0.0.5 (pinned)  
result                    1.2  Compatibility Result module
sawja                   1.5.1  Provide a high level representation of Java bytec
sexplib             113.33.03  Library for serializing OCaml values to and from 
typerep             113.33.03  typerep is a library for runtime types.
utop                   1.19.3  Universal toplevel for OCaml
variantslib         113.33.03  Part of Jane Street's Core library
yojson                  1.3.2  Yojson is an optimized parsing and printing libra
zed                       1.4  Abstract engine for text edition in OCaml

**Comment by jvillard** [comment]
Does `./build-infer.sh` work for you? It looks like the clang build now depends on the Java build so you get an error trying to compile just clang.

**Comment by jberdine** [comment]
Just to update: there is a change now in master that should fix this and will be included in the next release.

**Comment by jvillard** [comment]
This is fixed in master, closing.
