### ISSUE TITLE
Can't update infer

### ISSUE THREAD

**Issue by mmellau** [facebook/infer#468]
I'm trying to update Infer to 0.9.3 by executing `brew upgrade infer`, but unfortunately the output is `Error: infer 0.9.2 already installed`. Should I install the new version by downloading the release package and run build-infer.sh?

**Comment by jberdine** [comment]
We are working on updating brew.  The brew formula no longer works and another release of infer is needed to patch the build script.

**Comment by frankyliu** [comment]
when will this be ready? My project is looking forward to it

**Comment by cendywang** [comment]
We have the same problem regarding to this. When could we got 0.9.3 at homebrew?

**Comment by kanersan** [comment]
I had the same issue also, I had to manually install 0.9.3 which wasn't as easy as using homebrew. Though after upgrading to 0.9.3 Xcode8.0 storyboards still don't compile. Burn!

**Comment by bsameh** [comment]
Any updates on this? There doesn't seem to be a due date for 0.9.4, which is supposed to include a fix for the issue with the Homebrew formula.

**Comment by jvillard** [comment]
The new release is published, and there's a PR for the Homebrew formula https://github.com/Homebrew/homebrew-core/pull/7057

**Comment by bsameh** [comment]
Great news! 👍

**Comment by kanersan** [comment]
Nice. I fixed my issue actually. After installing Xcode 8.0 next to 7.0, my terminal still thought 7.0 was default for running Xcode commands which also happen while running infer. So that's why the storyboards were not compiling. As soon as I made Xcode 8.0 the system default, everything worked fine with Infer 0.9.3.

**Comment by jberdine** [comment]
Optimistically closing this, please reopen if the issue remains.

**Comment by devKrishnan** [comment]
I fixed this issue by updating my brew to the latest version
