### ISSUE TITLE
infer binary

### ISSUE THREAD

**Issue by rocketnik** [facebook/infer#470]
Hello infer dev-team,

compiling/installing infer seems to be a common problem.

Personal experience (on Mac):
I have had trouble installing infer 0.8.1 in the beginning and managed to get it compiled/installed after half a day.
I had problems installing infer 0.9.1? and gave up.
I could install 0.9.2 without problems via brew on one machine. Later when installing on a 2nd machine, I could not get it install via brew. I copied over the binary from machine 1, then it worked.
Just now I failed on my try to install 0.9.3.

There are also some issues here on github regarding installation.

Since tools/Xcode/command line utilities/libraries/OS and so on constantly change, it is a lot of effort to maintain a working installation script.

Wouldn't it make the lives of ordinary developers like me easier, if there was a binary distribution of infer? Wouldn't it be hard enough for all the great developers, who work on infer, to figure out the right set of libraries/compilers/environemnt? Couldn't their achievements of getting infer compiled on their machines be harnessed and transferred in binary self-contained form to other developers?

I am not such a good developer to be aware of all the consequences and the pros of source distribution (except for allowing further development) over binary distribution. I might be overlooking something. But I wonder, why "normal" consumer facing applications like the ones on the App Stores are distributed in binary form and usually survive many more OS updates and library changes on the system (due to static linking?), yet source distribution is so popular.

Thank you for writing this great tool and making it available publicly!
Kind regards
Nikolas

**Comment by jberdine** [comment]
We are aware of the pains of building from source, but there are some issues with binary distribution.  We aren't there yet, and it will take some time.

In the meantime, is the installation process using homebrew also painful in your experience?

**Comment by rocketnik** [comment]
using brew in general is rather convenient and not painful, except that most of the time, running "brew install" did not result in a working installation of the infer app on my machine (in some cases it did).

**Comment by rocketnik** [comment]
installing infer 0.9.4.1 did work.

**Comment by jberdine** [comment]
Thanks for the info.  Yes, we have had some bum brew releases.  The infer release process and the brew one conflict a bit, and we need to make a github release before we can fully test the brew one, so if there are issues that can't be handled in the brew formula alone, we get a broken release.  Changing the processes takes time...

**Comment by bootstraponline** [comment]
For binary linux releases, this appears to work fine:

- `tar czvf infer-v0.9.4.1-linux.tar.gz /infer/infer/bin /infer/infer/lib`

what exactly are the issues?

**Comment by jvillard** [comment]
@bootstraponline our releases do not include the infer binaries, in particular infer/infer/bin is empty.

**Comment by bootstraponline** [comment]
I understand that but using [these commands](https://github.com/bootstraponline/meta/wiki/Infer) it's easy for someone to generate a binary release on their own.

**Comment by jvillard** [comment]
@bootstraponline The issue is in distributing these binaries, which is tricky due to the licenses of some of infer's dependencies. We are working to resolve the issue but this will likely take some more time.

**Comment by jvillard** [comment]
Infer [v0.15.0](https://github.com/facebook/infer/releases/tag/v0.15.0) comes with binaries :confetti_ball:

We expect our releases to come with binaries for the foreseeable future.
