### ISSUE TITLE
build failed with my ios app

### ISSUE THREAD

**Issue by zhangying19871987** [facebook/infer#477]
I met an error when I build my ios app with infer. The error in the 1.txt. If I build my ios app without infer, I can build successful.

[1.txt](https://github.com/facebook/infer/files/518933/1.txt)

**Comment by dulmarod** [comment]
Hi, we have a new release now, 0.9.4, that provides better integration with xcodebuild, using xcpretty. Check it out, it may solve your problem.

**Comment by jberdine** [comment]
Optimistically closing, please reopen if this problem remains with 0.9.4 and the xcpretty integration.
