### ISSUE TITLE
False Positive Detected by Infer

### ISSUE THREAD

**Issue by cryptogrammer** [facebook/infer#479]
For code of the form 
`if (x != null) {
    doSomethingWithX();
} else {
    doSomethingElse();
}`

infer works just fine. However, for code of the form 

`final boolean y = x != null;
if (y) {
    doSomethingWithX();
} else {
    doSomethingElse();
}`

infer gives an error in doSomethingWithX, saying x could be null.

**Comment by clonetwin26** [comment]
This is probably the most frequent false positive we see with the tool.

**Comment by jeremydubreil** [comment]
Hi @cryptogrammer. Would you be able to reproduce it on a small example ?

**Comment by sblackshear** [comment]
Have tried to repro with the example below, but I don't see any warnings. Is there a similar example where we'll see the FP?

```
 public void test(Object x) {
    final boolean b = x != null;
    if (b) {
      doSomethingWithX(x);
    } else {
    }
  }

  void doSomethingWithX(Object x) {
    x.toString();
  }
```

**Comment by jvillard** [comment]
Closing for lack of repro. Please provide a concrete example to help us fix this issue.
