### ISSUE TITLE
memory is not enough when infer analyze a IOS project

### ISSUE THREAD

**Issue by iceheart82** [facebook/infer#481]
when i use infer to check a ios project which size is 178MB , infer analyse the problem takes 30Gb memory  ,so it is interrupted  with exit code (  macbook pro with 8G rom ),is there anybody who can tell me how to analyse such big project?

**Comment by jberdine** [comment]
We are currently working to reduce memory consumption.  Currently there is not much in the way of configuration options to reduce memory consumption.  One possible option is to set `skip-clang-analysis-in-path` in .inferconfig or on the command line to avoid analyzing particularly problematic code.  Identifying this code is somewhat roundabout, as you need to, while infer is running, observe which InferAnalyze process(es) consume the most memory, look at the command line to see which 'cluster' it is analyzing (clNNN for some number NNN), and then find that cluster in the generated Makefile (infer-out/multicore/Makefile), and look at the comment in that Makefile that indicates which source file(s) the cluster corresponds to.

**Comment by ccl0326** [comment]
we also have this problem.

**Comment by jvillard** [comment]
Can you share the command you use to run infer? Some of them are not meant to be passed on large projects, eg `--debug`.

**Comment by iceheart82** [comment]
infer -- xcodebuild -project xx.xcodeproj -scheme xx -configuration Debug -sdk iphonesimulator -arch "i386" ONLY_ACTIVE_ARCH=NO VALID_ARCHS="i386 x86_64" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO >> result1012.txt

**Comment by iceheart82** [comment]
at last , i delete the file in the directory of '/spec' ,then run infer again to get the final result. 3Q @ jberdine

**Comment by jberdine** [comment]
The 0.9.4 release include significant memory consumption improvements, please try that and reopen if this issue remains.
