### ISSUE TITLE
Java Resource_leak issue

### ISSUE THREAD

**Issue by boyue** [facebook/infer#482]
@Override
    protected IMByteSendStream encodeChildHeader() throws IOException {

```
    IMByteSendStream sendStream = new IMByteSendStream(new ByteArrayOutputStream());

    // 进行写流
    sendStream.writeByte(flag);
    sendStream.writeShort(version);
    sendStream.writeShort(pduType);

    if(isRequestId()) {
        sendStream.writeLong(requestId);
    }
    if(isReserved()) {
        sendStream.writeLong(reserved);
    }

    return sendStream;
}
```

infer  say this have Reaource_leak ，but I dnot know how to fix,anybody can help me ?

**Comment by xennygrimmato** [comment]
Hey @boyue !
In this line:
`IMByteSendStream sendStream = new IMByteSendStream(new ByteArrayOutputStream());`
the `ByteArrayOutputStream()` resource has been passed to `IMByteSendStream` and has not been closed. I think that is the reason for the leak.

**Comment by boyue** [comment]
protected IMByteSendStream encodeChildHeader()  {

        IMByteSendStream sendStream = null;
        ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
        try {
            sendStream = new IMByteSendStream(byteArrayOutputStream);
            // 进行写流
            sendStream.writeByte(flag);
            sendStream.writeShort(version);
            sendStream.writeShort(pduType);

            if (isRequestId()) {
                sendStream.writeLong(requestId);
            }
            if (isReserved()) {
                sendStream.writeLong(reserved);
            }
            return sendStream;
        } catch (Exception e) {
            if(byteArrayOutputStream!=null){
                try {
                    byteArrayOutputStream.close();
                } catch (IOException ee) {
                    e.printStackTrace();
                }
            }
            if(sendStream!=null){
                try {
                    sendStream.close();
                } catch (IOException ee) {
                    e.printStackTrace();
                }
            }

        } finally {

        }
        return null;

    }

@xennygrimmato seems dont work .buddy,T-T

**Comment by xennygrimmato** [comment]
Can you try closing both resources in the `finally` block?

**Comment by peterogithub** [comment]
Can you tell us what the error message was? Could it be that there was a potential exception in the code? Resource leaks sometimes happen when close() is not done on an exception path.

**Comment by peterogithub** [comment]
Also, this link explains some common issues and how to resolve them.
   http://fbinfer.com/docs/infer-bug-types.html#RESOURCE_LEAK

**Comment by sblackshear** [comment]
Closing for now, feel free to re-open if there is an update.
