### ISSUE TITLE
Build failed-0.9.3-clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by adolf2v** [facebook/infer#484]
ld: warning: directory not found for option '-L/Users/xiaoqiang/english/EnglishReading/Tools/Agora/Crasheye'
ld: warning: directory not found for option '-F/Users/xiaoqiang/english/EnglishReading/ThirdLib'
ld: library not found for -lAFNetworking
ld: warning: directory not found for option '-L/Users/xiaoqiang/english/EnglishReading/Tools/Agora/Crasheye'
ld: warning: directory not found for option '-F/Users/xiaoqiang/english/EnglishReading/ThirdLib'
ld: library not found for -lAFNetworking
clang: error: linker command failed with exit code 1 (use -v to see invocation)

*\* BUILD FAILED **

The following build commands failed:
    Ld build/Debug-iphonesimulator/EnglishReadingHD.app/EnglishReadingHD normal i386
(1 failure)
Failed to execute: /Users/xiaoqiang/Downloads/infer-osx-v0.9.3/infer/bin/../lib/python/infer.py -j 4 --out /Users/xiaoqiang/english/infer-out --project_root /Users/xiaoqiang/english -- xcodebuild -arch i386 -target EnglishReadingHD -configuration Debug -sdk iphonesimulator

**Comment by jvillard** [comment]
Because infer inserts itself instead of the compiler, sometimes you need to disable linking for the build system to be happy: `LD=/bin/true infer ...`. Let me know if this helps.

**Comment by adolf2v** [comment]
Im OSX, use /usr/bin/ture instead of /bin/true,It's very very useful, thanks a lot .

**Comment by adolf2v** [comment]
now,run LD=/usr/bin/true infer ..... 
the error :Ld build/Debug-iphonesimulator/EnglishReading.app/EnglishReading normal i386 was found again。

**Comment by adolf2v** [comment]
the complete command is :LD=/usr/bin/true infer -- xcodebuild -target EnglishReading -configuration Debug -sdk iphonesimulator

**Comment by adolf2v** [comment]
I have update Build Active Architecture Only from yes to no, and add i386 in the valid Architectures,but it doesn't work.

**Comment by jvillard** [comment]
What version of infer are you using? 0.9.4.1 has a new xcodebuild integration based on xcpretty that should avoid this issue.

**Comment by adolf2v** [comment]
my version is 0.9.3,when i upgrade 0.9.4.1.the following error was found:
[infer-deps-d7B3] /Users/xiaoqiang/Downloads/infer-0.9.4.1/infer-deps-d7B3/ already up-to-date
The following dependencies couldn't be met:
  - infer-deps-d7B3 -> reason >= 1.4.0
Your request can't be satisfied:
  - reason>=1.4.0 is not available because the package is pinned to https://github.com/facebook/reason.git#0.0.6, version 0.0.5.

No solution found, exiting

**Comment by jvillard** [comment]
Try `OPAMSWITCH=infer-4.02.3 opam unpin reason merlin merlin_extend; opam update`.

**Comment by adolf2v** [comment]
yes ,I ran the command :sudo opam pin add -y reason 'https://github.com/facebook/reason.git#0.0.6' to update reason,the result is that version 0.0.5 was installed 

[reason] https://github.com/facebook/reason.git#0.0.6 updated
[reason] Installing new package description from https://github.com/facebook/reason.git#0.0.6

reason needs to be reinstalled.
The following actions will be performed:
  ↻  recompile reason 0.0.5*

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[reason] https://github.com/facebook/reason.git#0.0.6 already up-to-date

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
⊘  removed   reason.0.0.5
∗  installed reason.0.0.5
Done.

**Comment by jvillard** [comment]
You don't need to pin reason anymore as it's been pushed to the main opam repository. 0.0.6 is too old for infer 0.9.4.1, which requires reason >= 1.4.0. The commands I gave should remove the pin on reason, allowing `./build-infer.sh` to find the more recent reason currently in opam.

**Comment by adolf2v** [comment]
0.9.4.1 has the same problem :

> ld: warning: directory not found for option '-L/Users/xiaoqiang/Downloads/english/build/Debug-iphonesimulator/Masonry'
ld: warning: directory not found for option '-L/Users/xiaoqiang/Downloads/english/build/Debug-iphonesimulator/SDWebImage'
ld: warning: directory not found for option '-L/Users/xiaoqiang/Downloads/english/build/Debug-iphonesimulator/SVProgressHUD'
ld: warning: directory not found for option '-L/Users/xiaoqiang/Downloads/english/build/Debug-iphonesimulator/SocketRocket'
ld: warning: directory not found for option '-L/Users/xiaoqiang/Downloads/english/build/Debug-iphonesimulator/TPiOSFramework'
ld: library not found for -lAFNetworking
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld build/Debug-iphonesimulator/EnglishReading.app/EnglishReading normal i386
(1 failure)

that's my command: 
LD=/usr/bin/true infer --no-xcpretty -- xcodebuild -target EnglishReading -configuration Debug -sdk iphonesimulator

**Comment by adolf2v** [comment]
I had alias Ld="/usr/bin/true",and add it to my /etc/profile,but it doesn't work also

**Comment by jvillard** [comment]
Have you tried the version that uses `xcpretty`? It would likely solve your issue as it doesn't require infer to interfere with the `xcodebuild` compilation process.

Otherwise there should be a way to tell `xcodebuild` to call `/usr/bin/true` instead of the normal `ld` but if exporting `LD` doesn't work I don't know what would. Is there a way you could share your app?

Just to check: the command `xcodebuild -target EnglishReading -configuration Debug -sdk iphonesimulator` succeeds without infer, right?

**Comment by adolf2v** [comment]
AFNetWorking can't support simulator,is there a way that can I  use infer on real phone?

**Comment by adolf2v** [comment]
That‘s the problem of my source code, it can't complie successfully with "xcodebuild -target EnglishReading -configuration Debug -sdk iphonesimulator ". I will close this issue,and try to find the problem with developers.
Thanks a lot.
