### ISSUE TITLE
Analysis ios app failed

### ISSUE THREAD

**Issue by zhangying19871987** [facebook/infer#485]
the errors as follows:

F.................................F..F............F......................................................F............F..............................F..............................................................................F..........................................................................................................................F...............................................................F..............F.......F...........F.........F.......F......F...........................F.F...........F...............................................................F...............F..F.F............................................F........F...F.........F.....................F...F................F....F...........................................F.............F.........F..................F....................................................F.................F.......F......FF......F............................................F.......F..F........F...........F.F..................F....F.F.............F.............FF.......................F....F.........F.F.........F....F.....F.............................F................F....F...........................F..................................................F.........................FF........................F...........F..................F......F.........................F.............................F...........F....F...................F...F....................F.F......F......F...F.................FF...F...F....FF.......F.FFF...F...F........................................................F......F..F......F....F..............FF...........F...........F.......F................................F.F.................F.F......F......F...............................F...........................F.......................F.....F.F.................F.......................F.......................F...........................F..........................................F.......F..............F.............F..........F....F....F..F....FF.....F......F................F...FF.....................F..FFFF.F........................................F......................................F...F...................F.............F......F.F.........................................................F..................F.....F......F........FFF....FF.....F..F..........F.......F..F...F..F.F...F.F..FF...................F....F....F........F...FF.FF.....F..F...F..FF..FF..F.....F.F.....F.....F....F.....F........F..F......F...F...................F..........F....F..............................................................................................................................................................................................................make: Target `default' not remade because of errors.
Traceback (most recent call last):
  File "/Users/daryadan/Documents/infer-osx-v0.9.3/infer/bin/../lib/python/infer.py", line 230, in <module>
    main()
  File "/Users/daryadan/Documents/infer-osx-v0.9.3/infer/bin/../lib/python/infer.py", line 214, in main
    analysis.analyze_and_report()
  File "/Users/daryadan/Documents/infer-osx-v0.9.3/infer/lib/python/inferlib/analyze.py", line 537, in analyze_and_report
    elif self.analyze() == os.EX_OK:
  File "/Users/daryadan/Documents/infer-osx-v0.9.3/infer/lib/python/inferlib/analyze.py", line 428, in analyze
    self.args.analyzer
  File "/Users/daryadan/Documents/infer-osx-v0.9.3/infer/lib/python/inferlib/analyze.py", line 240, in run_command
    raise e
subprocess.CalledProcessError: Command '[u'make', u'-k', u'-j', '8', u'-s']' returned non-zero exit status 2
Failed to execute: /Users/daryadan/Documents/infer-osx-v0.9.3/infer/bin/../lib/python/infer.py -j 8 --out /Users/daryadan/QQStock_iPhone_5.2.0/infer-out --project_root /Users/daryadan/QQStock_iPhone_5.2.0 -- xcodebuild clean build CODE_SIGN_IDENTITY=iPhone Developer: yuan Cui (CW7J8L2GSF) -target QQStock -configuration Debug -sdk iphoneos10.0

**Comment by martinoluca** [comment]
Hello @zhangying19871987,
could you please provide instructions on how to reproduce this issue?

Thanks!

**Comment by dulmarod** [comment]
Hi, we have a new release now, 0.9.4, that provides better integration with xcodebuild, using xcpretty. Check it out, it may solve your problem.

**Comment by jberdine** [comment]
Optimistically closing this, please reopen if the problem remains with the new release.
