### ISSUE TITLE
infer now only scanning one file in Xcode project, was working fine yesterday

### ISSUE THREAD

**Issue by ferasOS** [facebook/infer#489]
HI,

Basically I ran infer to analyse my Xcode project yesterday and it came up with over 100 issues. I have dealt with some of the issues and to check I ran a xcodecuild clean and then tried running infer in a similar way. However now it analysis 1 file and says no issues. I am confused on why this has happened?

Thanks in advance,

Feras A.

**Comment by dulmarod** [comment]
Could you provide more details? 
1. Is the version of Infer the same on both days?
2. Command you ran on both occasions

Doing xcodebuild clean should cause infer to analyze everything again, so this is not expected.

**Comment by ferasOS** [comment]
the versions are the same and the command is:
infer -- xcodebuild -workspace OneScream.xcworkspace -scheme OneScream

**Comment by dulmarod** [comment]
Can you check how many files are getting compiled with 
 xcodebuild -workspace OneScream.xcworkspace -scheme OneScream

I think xcpretty can help with a nicer log.

**Comment by ferasOS** [comment]
Ferass-MacBook-Pro:onescream-ios-app_sourcetree feras$ xcodebuild -workspace OneScream.xcworkspace -scheme OneScream | xcpretty

2016-10-27 17:19:52.063 xcodebuild[6777:780301] [MT] PluginLoading: Required plug-in compatibility UUID 8A66E736-A720-4B3C-92F1-33D9962C69DF for plug-in at path 

'~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XInfer.xcplugin' not present in DVTPlugInCompatibilityUUIDs

▸ Building Pods/AFNetworking [Debug]
▸ Check Dependencies
▸ Building Pods/FBAllocationTracker [Debug]
▸ Check Dependencies
▸ Building Pods/FBRetainCycleDetector [Debug]
▸ Check Dependencies
▸ Building Pods/FFGlobalAlertController-FFGlobalAlertController [Debug]
▸ Check Dependencies
▸ Building Pods/FFGlobalAlertController [Debug]
▸ Check Dependencies
▸ Building Pods/FMDB [Debug]
▸ Check Dependencies
▸ Building Pods/GoSquared [Debug]
▸ Check Dependencies
▸ Building Pods/Toast [Debug]
▸ Check Dependencies
▸ Building Pods/FBMemoryProfiler [Debug]
▸ Check Dependencies
▸ Building Pods/Pods-OneScream [Debug]
▸ Check Dependencies
▸ Building OneScream/OneScream [Debug]
▸ Check Dependencies
▸ Running script '[CP] Check Pods Manifest.lock'
▸ Running script '[CP] Embed Pods Frameworks'
▸ Running script '[CP] Copy Pods Resources'
▸ Running script 'Run Script'

    DEBUG_INFORMATION_FORMAT should be set to dwarf-with-dsym for all configurations. This could also be a timing issue, make sure the Fabric run script build phase is the last build phase and no other scripts have moved the dSYM from the location Xcode generated it. Unable to process OneScream.app.dSYM at path /Users/feras/.../OneScream.app.dSYM

▸ Build Succeeded

**Comment by dulmarod** [comment]
Hi, we have a new release now, 0.9.4, that provides better integration with xcodebuild, using xcpretty. Check it out, it may solve your problem.

**Comment by jberdine** [comment]
Optimistically closing this, please reopen if the issue remains with 0.9.4 and the new xcpretty integration.
