### ISSUE TITLE
"not found" error when executing `infer -- gradle build` in Jenkins with infer built from source

### ISSUE THREAD

**Issue by truebit** [facebook/infer#491]
On a Debian Wheezy, I built infer-0.9.3 as per the guide [Install from source](fbinfer.com/docs/getting-started.html). and I also put gradle 2.14.1 in `$PATH`.

Now I could run `infer -- gradle build` in bash shell. But when I put this command in Jenkins shell, it would throw error `infer -- gradle: not found`.

I also tried put `eval `opam config env`` before infer, but with no luck. log as below:

> - opam config env
>   [WARNING] Running as root is not recommended
> - eval CAML_LD_LIBRARY_PATH="/root/.opam/infer-4.02.3/lib/stublibs"; export CAML_LD_LIBRARY_PATH; MANPATH="/root/.opam/infer-4.02.3/man:"; export MANPATH; PERL5LIB="/root/.opam/infer-4.02.3/lib/perl5"; export PERL5LIB; OCAML_TOPLEVEL_PATH="/root/.opam/infer-4.02.3/lib/toplevel"; export OCAML_TOPLEVEL_PATH; PATH="/root/.opam/infer-4.02.3/bin:/opt/gradle-2.14.1/bin:/opt/infer-0.9.3/bin:/opt/infer-0.9.3/bin:/opt/gradle-2.14.1/bin:/opt/infer-0.9.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/android-sdk-linux/tools:/root/android-sdk-linux/platform-tools:/root/android-sdk-linux/build-tools/24.0.0"; export PATH;
> - CAML_LD_LIBRARY_PATH=/root/.opam/infer-4.02.3/lib/stublibs
> - export CAML_LD_LIBRARY_PATH
> - MANPATH=/root/.opam/infer-4.02.3/man:
> - export MANPATH
> - PERL5LIB=/root/.opam/infer-4.02.3/lib/perl5
> - export PERL5LIB
> - OCAML_TOPLEVEL_PATH=/root/.opam/infer-4.02.3/lib/toplevel
> - export OCAML_TOPLEVEL_PATH
> - PATH=/root/.opam/infer-4.02.3/bin:/opt/gradle-2.14.1/bin:/opt/infer-0.9.3/bin:/opt/infer-0.9.3/bin:/opt/gradle-2.14.1/bin:/opt/infer-0.9.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/android-sdk-linux/tools:/root/android-sdk-linux/platform-tools:/root/android-sdk-linux/build-tools/24.0.0
> - export PATH
> - infer -- gradle build
>   /tmp/hudson2278493570880190800.sh: 4: /tmp/hudson2278493570880190800.sh: infer -- gradle: not found
> 
> Build step 'Execute shell' marked build as failure

**Comment by sblackshear** [comment]
Can't tell for sure from the paste, but it looks like you may be running `infer--gradle` rather than `infer -- gradle` (note the spaces around the `--`).

If that is not the issue, could you please paste the output of `infer -v` and `gradle -v`?

**Comment by truebit** [comment]
there was spaces around `--`. added `-v`, but the message is the same:

> + infer -v --  gradle -v build
> /tmp/hudson7809466999302022077.sh: 5: /tmp/hudson7809466999302022077.sh: infer  -v: not found
> Build step 'Execute shell' marked build as failure
> Finished: FAILURE

**Comment by sblackshear** [comment]
It looks like the Infer executable may not be installed -- can you paste the output of just `infer -v` (no gradle command)?

**Comment by jvillard** [comment]
> infer  -v: not found

This looks suspiciously as if you'd typed an unbreakable space instead of a regular space between `infer` and `-v`. Then the shell would look for a command called "infer -v".

**Comment by truebit** [comment]
Today I removed the command and enter again. It works now
