### ISSUE TITLE
error statement

### ISSUE THREAD

**Issue by rgrig** [facebook/infer#492]
**Question:** I'd like to be able to insert `assert false` in the code, and have Infer tell me if it thinks that that statement is reachable. _Is this possible?_

**Some extra info:**

Unless I'm crazy, which is not unlikely, I recall that using `while(true){}` worked (in the sense that there was a warning when such a piece of code was reachable). But now (08d4465e1dbde345fd96a2df13640388ff20b85f), I don't get any warning on file `A.java` with content

```
class B { static void f() { assert false; } }
class C { static void f() { while (true); } }
public class A { public static void main() { B.f(); C.f(); } }
```

when I use the command `infer -- javac A.java`.

Is there something that can be used as an **error** statement (in Java)? Do I need to give it some command line options? If it's not possible now, are there any plans to introduce one? As you know, other tools do support such a statement; most notably, it's used in the SV-COMP benchmarks.

**Comment by sblackshear** [comment]
This is possible, but only in a somewhat hacky way at the moment. You can use `Object o = null; o.toString()` as an alias for `assert false`, and Infer will report a null dereference on `o` only if it thinks that the dereference is reachable.

**Comment by rgrig** [comment]
If I say

```
class B { static void f() { assert false; } }
class C { static void f() { while (true); } }
class D { static void f(boolean a) { if (a) {Object o = null; o.toString();} } }
public class A { public static void main() { B.f(); C.f(); D.f(false); } }

```

I get a warning no matter what argument I actually send D.f. I'd like to get a warning only if I call with the argument being `true`. The `null` trick you suggest is actually what I was trying before @ddino showed me that `while(true){}` does what I want. But it stopped working in the meantime ...

**Comment by sblackshear** [comment]
Ah, good point. My original suggestion will not work so well for what you want. But what about `f(Object o) { o.toString(); }` with `f(null)` as an alias for `assert false`?

**Comment by rgrig** [comment]
Hmm, it still doesn't seem to be compositional. Here's a function: `void f(Object x, Object y) { /* ??? */ }`. What do I put in there to force infer to find a (single) triple with the precondition x!=y and complain later only if `f` is used in a way for which that triple is not enough? This worked: `void f(Object x, Object y) {while(x==y);}`.

Here's how I tried to use your second proposal (so you can check if I did something wrong):

```
public class T2 {
  void assertF(String o) { o.toString(); }

  void f(Object x, Object y) {
    if (x != y) assertF(null);
  } // gives warning even if g is commented out
  /*
  void g() {
    f(1, 2); // ok
    f(null, null); // nok
  }
  */
}
```

**Comment by sblackshear** [comment]
Thanks, that does indeed clear things up!

I think that the triple you want is what can/will inferred for the on-paper version of the bi-abduction algorithm, but the Infer implementation chooses to report a warning in this case for pragmatic reasons (assuming that all branches are reachable in some context lets us report more bugs without causing too many false positives). 

If I'm right about this, I'm not immediately sure how to talk Infer into doing what you want. Let me think about it a bit more.

(Copying @cristianoc and @ddino since they have better knowledge about how the theory and practice diverge here.)

**Comment by cristianoc** [comment]
Notice that Infer works bottom-up, so if `f` calls `g` then Infer's decision on whether reporting on `g` will not be affected by how `f` calls it.
For example, If `f` contains ```if (a) {Object o = null; o.toString();}``` then the error is reported in `f` no matter how it's called.
If `f` contains instead ```if (a) {o.toString();}``` then nothing is reported in `f` but will be reported in `g` if it calls `f` the wrong way (with `a=true` and `o=null`).
Being bottom-up, it might be difficult to model the typical top-down reachability question, as if the error is reported half way through the chain of calls, it won't be reported in calls higher up the call stack.
One attempt could be to put a dereference in the code that you wish to know if reachable, as in ```foo(Object r,...) { ...r.toString;...}```
Then pass r through each call, untouched, and only call it with `null` from `main`, or from the roots of the program where one would like to know if it's reachable.
Another proviso is that the analysis might fail for a number of reasons (errors found, limits to the number of operations, etc), so it might not explore all the paths, and fail to report reachability.

**Comment by rgrig** [comment]
Bottom up "reachability" is what I want. I want to cook up a procedure with a given pre (say, `x!=y`) and then have infer say when that procedure is called in a situation where the pre doesn't hold. The issue is convincing Infer to use the precondition I want. The precondition I want will always be a (Java, boolean) expression over the arguments.

**Comment by rgrig** [comment]
> as if the error is reported half way through the chain of calls, it won't be reported in calls higher up the call stack.

So, that's OK in principle. But, why is there an error reported in `f` in the `T2` example? Clearly it can continue propagating up the pre.

**Comment by rgrig** [comment]
I dug a bit to make sure I'm not crazy. This is the file I was actually looking at some time ago (with @ddino):

```
import java.util.Random;

class G { // global
  static private Object tracked = null;
  static private int state = 0;
  static void get_ret(Object x) {
    if (maybe()) tracked = x;
  }
  static void go_ret(Object x) {
  }
  static void go_call(Object x) {
    if (x == tracked) {
      if (state == 0) state = 1;
      else if (state == 1) {while (true);}
    }
  }
  static boolean maybe() {
    return random.nextBoolean();
  }
  static private Random random = new Random();
}

class O {
  private O() {}
  public static O get() {
    return new O();
  }
  public void go() { }
}

public class T3 {
  public static void main(String[] args) {
    O x = O.get();
    G.get_ret(x);
    O y = O.get();
    G.get_ret(y);
    G.go_call(y);
    y.go();
    G.go_call(x);
    x.go();
    G.go_call(x); // HERE
    x.go();
  }
}

```

This used to give a warning on line marked with HERE. It stopped giving a warning at commit 3fb8801b6c8672ad0b7819aeda74d1feb4325be7 (by @cristianoc).

In any case, even if the parent commit gives a warning on T3@HERE (which I want!), it does not give a warning on the following:

```
public class T2 {
  void assertF(String o) { o.toString(); }

  void f(Object x, Object y) {
    //if (x == y) assertF(null);
    while (true);
  }
  void g() {
    f(1, 2); // ok
    f(null, null); // nok
  }
  public static void main(String[] args) {
    while (true);
  }
}
```

I don't understand why. I'm rather confused at this point.

**Comment by rgrig** [comment]
Oh, maybe it's because `G.go_call` has some specs, while `T2.f` doesn't.

**Comment by rgrig** [comment]
Last time I forgot to say that one needs `-nf` to see the warning with older versions. Also, I misidentified the culprit, probably by messing up some `git bisect` command. The issue appeared in a9f1d21dd210f41c5632cff23ddce06361bd6d8c. I'll put a comment on the commit to ask if the change was intended. (I hope not.)

Here's a small change that brings back the missing warnings:
[m.zip](https://github.com/facebook/infer/files/587647/m.zip)

**Comment by rgrig** [comment]
One can get back the warnings with `--debug-exceptions`. I'm closing.
