### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by ktsaou** [facebook/infer#495]
Hi,

I tried to analyze https://github.com/firehol/netdata with infer.

I get 2 false positives:

```
src/url.c:50: error: MEMORY_LEAK
   memory dynamically allocated to buf by call to mallocz() at line 49, column 17 is not reachable after line 50, column 5
  48.
  49.       char *buf = mallocz(size);
  50. >     return url_decode_r(buf, str, size);
  51.   }
  52.
  53.

src/web_client.c:1920: error: NULL_DEREFERENCE
  pointer 0 could be null and is dereferenced by call to gettimeofday() at line 1920, column 5
  1918.
  1919.       // start timing us
  1920. >     gettimeofday(&w->tv_in, NULL);
  1921.
  1922.       if(unlikely(!hash_api)) {
  1923.

Summary of the reports

       MEMORY_LEAK: 1
  NULL_DEREFERENCE: 1
```

The first is false positive, since `url_decode_r()` returns the supplied `buf`: https://github.com/firehol/netdata/blob/2fffb74cab6bfe7d6b8e212afcfaf8f74113a07f/src/url.c#L76

The second is false positive, since `tv_in` is a static member of `w`: https://github.com/firehol/netdata/blob/2fffb74cab6bfe7d6b8e212afcfaf8f74113a07f/src/web_client.h#L72 and `w` is passed properly to this function.

**Comment by jvillard** [comment]
Both of these warnings have disappeared with infer 0.15.0 and netdata version 2fffb74cab6bfe7d6b8e212afcfaf8f74113a07f.
