### ISSUE TITLE
 False positive on Infer and small struct.

### ISSUE THREAD

**Issue by master-q** [facebook/infer#496]
I have following code:

https://gist.github.com/master-q/8d24f66a3a3be66440fc2713982af6fb#file-check_foo_eats_null-txt-L1

that occurs error on Infer, but it doesn't really have any problems.
And also I changed the code as following:

https://gist.github.com/master-q/8d24f66a3a3be66440fc2713982af6fb#file-check_foo_eats_nonnull-txt-L1

that have problem at `__infer_assert` line. 

I found difference between these cases with `-g` option output:

https://gist.github.com/master-q/8d24f66a3a3be66440fc2713982af6fb#file-check_foo_eats_null-txt-L56
https://gist.github.com/master-q/8d24f66a3a3be66440fc2713982af6fb#file-check_foo_eats_nonnull-txt-L56

On latter case, Infer found the `PRECONDITION_NOT_MET` error, but doesn't report it.

I think Infer should not report such `NULL_DEREFERENCE` error, and should report such `PRECONDITION_NOT_MET` in my small example.

I'm using Infer version `v0.9.4-e757d92`.

**Comment by master-q** [comment]
Thanks for your advice. I should try to capture invariant in BSD's tree.h using INFER_EXCLUDE_CONDITION.

**Comment by jvillard** [comment]
I'm not sure what the overall goal is here. Is it to detect arbitrary assertion violations? This is not well supported by infer. Did you manage to achieve what you wanted? Closing optimistically, let us know if we can help more.
