### ISSUE TITLE
No Files Analyzed when using "infer -- make" on cmake generated Makefiles

### ISSUE THREAD

**Issue by doggkruse** [facebook/infer#50]
Encountered this on multiple cmake based projects:
cmake ./
infer -- make
[ 50%] Building C object CMakeFiles/testCmakeProj.dir/testCmakeProjStandalone.c.o
[100%] Building C object CMakeFiles/testCmakeProj.dir/testCmakeProjParse.c.o
Linking C executable testCmakeProj
[100%] Built target testCmakeProj
Starting analysis (Infer version v0.1.0)
Analysis done

0 file analyzed

No issues found

**Comment by jvillard** [comment]
Hi @doggkruse,

cmake generated Makefiles are not directly compatible with Infer.

Please see #25 for a workaround.
