### ISSUE TITLE
Updates to .inferconfig do not invalidate cached infer results when running with buck

### ISSUE THREAD

**Issue by kageiit** [facebook/infer#503]
Changes to `.inferconfig` do not invalidate the buck cache if no other changes to source are made.

infer should be able to add `.inferconfig` as a src to every rule to make sure the invalidation happens automatically. I believe it already adds the generated python script as a source to ensure such invalidation

**Comment by jeremydubreil** [comment]
This is indeed a problem. Buck has support for decorating the Java and Android targets and make them depends on a target like:
```
  export_file(
    name = 'inferconfig',
    src = '.inferconfig',
  )
```

**Comment by kageiit** [comment]
can the infer.py script not wrap the existing rules dynamically?

**Comment by jeremydubreil** [comment]
I don't know. Is there a buck command that can do this ?

**Comment by kageiit** [comment]
I dont think there is a buck command. But basically the infer python wrapper creates rules on the fly so it could also add `.inferconfig` as a source so it can invalidate the cache

**Comment by jvillard** [comment]
The contents of .inferconfig are now hashed and this gets [added to the key](https://github.com/facebook/infer/blob/7f9ff54638b70c7715aefdbf4146ce1d6e807009/infer/src/base/Config.ml#L2258-L2261) automatically.
