### ISSUE TITLE
Infer does not respect `javac_jar` in .buckconfig

### ISSUE THREAD

**Issue by kageiit** [facebook/infer#504]
Rules that set `javac_jar` or if it is configured in `.buckconfig`, do not invalidate the buck cache for infer as it always uses a javac from path. This leads to different build behavior in buck and infer and creates cache key duplication for the network cache. Can we support running on top of a `javac_jar` that buck supplies in it's config?

**Comment by jeremydubreil** [comment]
I am not sure I understand. Using Infer will create infer specific cache entires anyway that should be separated from the cache entries of the normal build. 

Infer can use the `javac_jar` to compile the code by adding the option:

  "java-jar-compiler":
    "path/to/javac.jar"

in the `.inferconfig` file.

**Comment by kageiit** [comment]
Was not aware of that option. Because there are two configuration options one in `.buckconfig` and one in `.inferconfig

**Comment by jeremydubreil** [comment]
Closing the issue. @kageiit: please re-open it is there is more to be done.
