### ISSUE TITLE
Fatal error: exception Out of memory

### ISSUE THREAD

**Issue by boyue** [facebook/infer#506]
I have a problem when i used 0.9.3 to analyze thouands of java files ,as below .
but it's ok when i used 0.8.1 to do the same thing before.

.................................F....F..................................................................F.......................................F.........................................F...............................................................................................................................................................................................................................F...............................................................................................................................................F.........................F....F.....................F........F.......F..................................F..........................F....................F..F...F......F....F......................................................................................F..F.......F..........................................F..............................................................................................................................................................................................................................................................................................................................................................................Fatal error: exception Out of memory
make: *** [cl6727] Error 2
make: Target `default' not remade because of errors.
Running and capturing gradle compilation...
Traceback (most recent call last):
  File "/home/jenkins/infer-linux64-v0.9.3/infer/lib/python/infer.py", line 230, in <module>
    main()
  File "/home/jenkins/infer-linux64-v0.9.3/infer/lib/python/infer.py", line 214, in main
    analysis.analyze_and_report()
  File "/home/jenkins/infer-linux64-v0.9.3/infer/lib/python/inferlib/analyze.py", line 537, in analyze_and_report
    elif self.analyze() == os.EX_OK:
  File "/home/jenkins/infer-linux64-v0.9.3/infer/lib/python/inferlib/analyze.py", line 428, in analyze
    self.args.analyzer
  File "/home/jenkins/infer-linux64-v0.9.3/infer/lib/python/inferlib/analyze.py", line 240, in run_command
    raise e
subprocess.CalledProcessError: Command '[u'make', u'-k', u'-j', '4', u'-s']' returned non-zero exit status 2
Failed to execute: /home/jenkins/infer-linux64-v0.9.3/infer/lib/python/infer.py -j 4 --out /home/jenkins/Home/workspace/AndroidInferAllCodeAnalyzer/testDebug/infer-out --project_root /home/jenkins/Home/workspace/AndroidInferAllCodeAnalyzer/testDebug -- ./gradlew assembleDebug
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by jvillard** [comment]
Hi, can you please paste the full command you are using to run infer? How much RAM do you have?

We've made improvements in that area since 0.9.3, would you mind trying out the latest master and see if memory consumption is still an issue?

**Comment by jberdine** [comment]
The 0.9.4 release includes significant memory consumption improvements, please try and reopen if this is still an issue.
