### ISSUE TITLE
InferClang++ missing in 0.9.4 Homebrew release

### ISSUE THREAD

**Issue by zhuowei** [facebook/infer#508]
After upgrading Infer to version 0.9.4 through Homebrew on macOS Sierra 10.12.1, I'm getting this message when running Infer:

`
/usr/local/Cellar/infer/0.9.4/lib/infer/infer/lib/python/inferlib/../../../lib/xcode_wrappers/clang++: line 8: /usr/local/Cellar/infer/0.9.4/lib/infer/infer/lib/xcode_wrappers/../../bin/InferClang++: No such file or directory`

`Command /usr/local/Cellar/infer/0.9.4/lib/infer/infer/lib/python/inferlib/../../../lib/xcode_wrappers/clang++ failed with exit code 127
`

I manually downloaded the 0.9.4 bottle from https://bintray.com/homebrew/bottles/infer#files, and can confirm that there's no InferClang++ file:

```
$ tar tf infer-0.9.4.sierra.bottle.tar.gz |grep InferClang
infer/0.9.4/lib/infer/infer/bin/InferClang
```

**Comment by dulmarod** [comment]
Thanks for reporting, we'll look into that. Could you tell us more about what kind of project you were trying to analyze, and the command you used if possible?

**Comment by akotulski** [comment]
`InferClang` should be created during build process of infer, so it's ok if it's not in the archive. Could you try removing and installing infer? Maybe there is something wrong with the upgrade process.
`brew reinstall infer`

**Comment by jberdine** [comment]
As a temporary workaround, you can create a symbolic link named InferClang++ in the same directory as InferClang that points to InferClang.

**Comment by akotulski** [comment]
@zhuowei I reproduced issue on my computer and I'm looking into the fix.
For now you can follow @jberdine suggestion

**Comment by akotulski** [comment]
I pushed the fix in https://github.com/facebook/infer/commit/f0bb23bc35bb69ba045052cbc7a24cd38e563c09 I'll keep the issue open until we have fixed release

**Comment by akotulski** [comment]
Fixed version has been pushed to homebrew and this problem shouldn't happen anymore
