### ISSUE TITLE
getting crash after signing android app

### ISSUE THREAD

**Issue by theshuklz** [facebook/infer#515]
I am getting below crash after signing the app. Do I need to add this class to proguard file?

`Verifier rejected class com.android.volley.toolbox.z: com.android.volley.s com.android.volley.toolbox.z.a(android.content.Context, com.android.volley.toolbox.k) failed to verify: com.android.volley.s com.android.volley.toolbox.z.a(android.content.Context, com.android.volley.toolbox.k): [0x59] register v0 has type Precise Reference: android.net.http.AndroidHttpClient but expected Reference: org.apache.http.impl.client.AbstractHttpClient`

**Comment by jvillard** [comment]
Can you please provide more information? Please include:
- the version of infer
- the command you used to run infer
- the full output (please use https://gist.github.com/ or equivalent)
