### ISSUE TITLE
Problem in parallel analysis

### ISSUE THREAD

**Issue by KihongHeo** [facebook/infer#518]
Hi Infer Team,

As @jberdine said in https://github.com/facebook/infer/issues/514,  
> If procedures are recursive, they may be analyzed a few times.  Each procedure should have only a single spec written to disk, however.
Also, multiple parallel processes may analyze the same procedure multiple times and race to write the spec to disk.
> 

- Can multiple parallel processes analyze the same procedure even though it is not recursive?
- Is there any mechanism to protect the race condition?

Also, when I use ```-j 1```, it seems that Infer-0.9.4 does not work well. 
The following is the result from 0.9.4 with ```-j 2``` and ```-j 1```.
```
../infer-linux64-v0.9.4/infer/bin/infer -j 2 -- gcc -c test.c
Capturing in make/cc mode...
Starting analysis...

legend:
  "F" analyzing a file
  "." analyzing a procedure

Found 1 source files in /home/khheo/project/InferExperiment/infer-out
F.

Found 2 issues

test.c:4: error: MEMORY_LEAK
   memory dynamically allocated to p by call to malloc() at line 2, column 13 is not reachable after line 4, column 3
  2.     char* p = malloc(10);
  3.
  4. >   *p = 1;
  5.     return 0;
  6.

test.c:4: error: NULL_DEREFERENCE
  pointer p last assigned on line 2 could be null and is dereferenced at line 4, column 3
  2.     char* p = malloc(10);
  3.
  4. >   *p = 1;
  5.     return 0;
  6.

Summary of the reports

       MEMORY_LEAK: 1
  NULL_DEREFERENCE: 1
```
```
$ ../infer-linux64-v0.9.4/infer/bin/infer -j 1 -- gcc -c test.c
Capturing in make/cc mode...
Found 1 source files in /home/khheo/project/InferExperiment/infer-out
F.
ONDEMAND EXCEPTION main (Failure "Builtins were not initialized")

CALL STACK
Raised by primitive operation at file "backend/ondemand.ml", line 180, characters 40-69
Called from file "list.ml", line 73, characters 12-15
Called from file "backend/interproc.ml", line 1504, characters 2-35
Called from file "backend/InferAnalyze.re", line 29, characters 4-33
Called from file "list.ml", line 77, characters 12-17
Called from file "list.ml", line 79, characters 16-27
Called from file "backend/infer.ml", line 285, characters 11-29
Called from file "backend/infer.ml", line 315, characters 2-20

BACK TRACE
Raised at file "IR/Exceptions.ml", line 307, characters 14-15
Called from file "IR/Exceptions.ml", line 358, characters 37-60
Called from file "backend/interproc.ml", line 594, characters 15-46
Called from file "backend/interproc.ml", line 608, characters 4-40
Called from file "backend/timeout.ml", line 118, characters 4-7
Re-raised at file "backend/timeout.ml", line 129, characters 12-15
Called from file "backend/interproc.ml", line 1321, characters 12-37
Called from file "base/Config.ml", line 1630, characters 14-17
Re-raised at file "base/Config.ml", line 1636, characters 12-15
Called from file "base/Config.ml", line 1648, characters 2-52
Called from file "backend/ondemand.ml", line 173, characters 4-36

Uncaught exception:

  (Failure "Builtins were not initialized")

Raised at file "IR/Exceptions.ml", line 307, characters 14-15
Called from file "backend/reporting.ml", line 41, characters 45-79
Called from file "list.ml", line 73, characters 12-15
Called from file "backend/interproc.ml", line 1504, characters 2-35
Called from file "backend/InferAnalyze.re", line 29, characters 4-33
Called from file "list.ml", line 77, characters 12-17
Called from file "list.ml", line 79, characters 16-27
Called from file "backend/infer.ml", line 285, characters 11-29
Called from file "backend/infer.ml", line 315, characters 2-20
```

When I use ```-a checkers```,  ```-j 2``` works well.
But with ```-j 1```, I think it does not start checkers.

```
Capturing in make/cc mode...
Found 1 source files in /home/khheo/project/InferExperiment/infer-out
F
Analysis finished in 0.283844s

  No issues found
```

The test file is 
```
int main(){
  char* p = malloc(10);

  *p = 1;
  return 0;
}
```

Thanks,
Kihong

**Comment by jberdine** [comment]
> - Can multiple parallel processes analyze the same procedure even though it is not recursive?
> - Is there any mechanism to protect the race condition?

I should have also mentioned this before, but yes, parallel processes can analyze the same procedure simultaneously.  There are mechanisms to protect against reading partially written files, for when one process reads the specs of a procedure while another is writing them, etc.  But there is intentionally nothing blocking multiple parallel processes from analyzing any individual procedure simultaneously.  The intended usage is to write an analysis which produces a spec for each procedure such that if multiple processes analyze the procedure in parallel, they will obtain the same spec, so it does not matter which process wins the race to write the spec.  It is important and can be nontrivial to design the analysis so that the computed specs are always the same.  Any use of global or file system state must be done with care, and other sources of non-determinism need to be minimized or eliminated.


> Also, when I use ```-j 1```, it seems that Infer-0.9.4 does not work well. 
> The following is the result from 0.9.4 with ```-j 2``` and ```-j 1```.

Thanks for the report!  I have just submitted a fix for this to code review, it should be in master in not too long.

**Comment by KihongHeo** [comment]
Thanks. I got your fix and it correctly works with ```-j 1``` without the checkers. 
But I think it still does not invoke the checkers with ```-j 1```. 
The output messages are a little bit different. 
```
$ ../infer/infer/bin/infer -a checkers -j 1 -- gcc -c test.c
Capturing in make/cc mode...
Found 1 source files in /home/khheo/project/InferExperiment/infer-out
F
Analysis finished in 0.245720s

  No issues found
```
```
$ ../infer/infer/bin/infer -a checkers -j 2 -- gcc -c test.c
Capturing in make/cc mode...
Starting analysis...

legend:
  "F" analyzing a file
  "." analyzing a procedure

Found 1 source files in /home/khheo/project/InferExperiment/infer-out
F

  No issues found
```

**Comment by jvillard** [comment]
Hi @KihongHeo, It's expected that the output is a little bit different with `-j 1` than with other modes, so I don't think your last example shows a difference in behaviour between the two. Could you please clarify?

**Comment by KihongHeo** [comment]
Hi @jvillard, 
```-j 1 -a checkers``` does not invoke the checkers (i.e., ```exec_instr``` is not executed).

**Comment by jvillard** [comment]
@KihongHeo I'm looking into this.

**Comment by jvillard** [comment]
Thanks for the report @KihongHeo, this should be fixed now!
