### ISSUE TITLE
[iOS] Incorrect Memory Leak Detection

### ISSUE THREAD

**Issue by FredericJacobs** [facebook/infer#52]
The following Objective-C code incorrectly results in a `error: MEMORY_LEAK
   memory dynamically allocated to buffer by call to malloc() at line X, column X is not reachable after line X, column X`.

```ObjC
void* buffer = malloc(bufferSize);
return [NSData dataWithBytesNoCopy:buffer length:bytesDecrypted freeWhenDone:YES];
```

The buffer is passed to the returned NSData object and will be deallocated when the NSData instance will be.

**Comment by dulmarod** [comment]
Hi, 
That is a real leak. The documentation of Apple also says that if the NSData object doesn't get created then the method will return nil. In that case the buffer will be leaked.

**Comment by FredericJacobs** [comment]
Oh right, thanks.
Got an assertion for that but good point.

**Comment by dflems** [comment]
@dulmarod: I still see this as a `MEMORY_LEAK` after doing a nil-check. Is there a way to silence this?

```objc
uint8_t *buffer = malloc(length);
...
NSData *data = [NSData dataWithBytesNoCopy:buffer length:length freeWhenDone:YES];
if (!data) {
    free(buffer);
}
return data;
```

**Comment by dulmarod** [comment]
There isn't a way to silence individual bugs at the moment.
