### ISSUE TITLE
v0.9.4 only print 10 bugs in the running log,"...too many issues to display (limit=10 exceeded)" but inferTraceBugs only print brief log. Can infer didn't limit the bug number, we want all detail running logs as before

### ISSUE THREAD

**Issue by carozuoP** [facebook/infer#520]

**Comment by carozuoP** [comment]
present, log "
 1. app/mall/SplashFragment.java:315: error: NULL_DEREFERENCE
      object bitmap last assigned on line 299 could be null and is dereferenced at line 315

 2. app/mall/SplashFragment.java:246: error: NULL_DEREFERENCE
      object bitmap last assigned on line 240 could be null and is dereferenced at line 246"

**Comment by akotulski** [comment]
Full report with same output as before should be in `infer-out/bugs.txt` - if you are using it on CI, then you can `cat` it after running infer and see same results on stdout. Would that work for you?

**Comment by jvillard** [comment]
Is the issue that there is no longer a full text output available that includes the source excerpts around each error?

We introduced the limit because we found it was often too spammy to list all the errors on the terminal. Maybe bugs.txt should include the source excerpts as well to make it more like the terminal output.

**Comment by carozuoP** [comment]
To akotulski, infer-out/bugs.txt didn't have source excerpts around each error, it is very simple.  To jvillard, can you add it back to infer-out/bugs.txt if you guys think it is too often spammy. I use it in CI and all my developers like detail codes around the error, they said it is more useful to judge if the report issue needs to fixed at the first glance.

**Comment by jvillard** [comment]
@carozuoP ok, I'll work on adding this feature to bugs.txt. Thanks for the feedback!

PS: If you haven't already, can you please consider adding your company to our [list of users](https://github.com/facebook/infer/edit/gh-pages/_data/powered_by.yml)? This helps us prioritise open-source users.

**Comment by carozuoP** [comment]
thank jvillard so much， my company name is JD(beijing jingdong century trade .ltd), which can be found in NASDAQ

**Comment by jvillard** [comment]
@carozuoP Thanks! Would it be ok to add the logo of your company to our [list of users](http://fbinfer.com/index.html#who-uses-infer)?
