### ISSUE TITLE
Casting operation

### ISSUE THREAD

**Issue by KihongHeo** [facebook/infer#521]
Hi,

It seems that the front-end skips casting operations.
For example,
```c
int* p = (int*) malloc (sizeof(int) * 10);
```
to
```
n$4=_fun_malloc((sizeof(int) * 10):int) [line 3]
*&p:int*=n$4 [line 3]
```

and 
```c
int y;
long z = (long) y;
```
to
```
n$0=*&y:int [line 8]
*&z:long=n$0 [line 8]
```

As @jvillard said in https://github.com/facebook/infer/issues/516,
it seems to be an intended result.
But my checker is sensitive to type casing.
Is it possible to capture type castings?

**Comment by akotulski** [comment]
Yes, right now we don't translate cast operations to SIL. This is ok for us, because we didn't care about them.
Could you explain in a little bit more detail what you would like to catch with your checker (give an example)?

**Comment by KihongHeo** [comment]
Thanks for the answer. 

I want to keep tracking array sizes and their strides by looking the casing operations following mallocs.

**Comment by akotulski** [comment]
I see. Changing frontend shouldn't be very hard, but there are questions I don't know answers to:
1. there may be some implications to our backend that I'm not aware of (this adds another indirection for backend to understand)
2. there is a question how to represent such cast in SIL.
Maybe @ddino or @cristianoc will know?

**Comment by jvillard** [comment]
Infer now records array strides, which I think answers the fundamental original issue. Feel free to re-open if I misunderstood.
