### ISSUE TITLE
Frontend issue on conditional operator in C

### ISSUE THREAD

**Issue by skcho** [facebook/infer#522]
```C
int foo ()
{
  int x = ({1 ? 1 : 1;});
  return 0;
}
```
Current front-end parses the above example into an incorrect control flow graph, where return node is unreachable from the entry node. This issue was initially observed when compiling `strspn()` with `gcc -O2` and `clang -O2` as follows.

```C
#include <string.h>

int foo (char *s)
{
  size_t n_slash = strspn (s, "/");
  return 0;
}
```

**Comment by akotulski** [comment]
Thanks for reporting - we did take some shortcuts translating statement expressions and if you pair it with conditional operators it may end up here.

On the other hand, how did you make source of `strspn`available for infer? Usually we use models for C library

**Comment by skcho** [comment]
Thank you for the reply. We just downloaded gnu gzip 1.8 and run
```bash
./configure
infer -a checkers -- make
```
The default setting of the `Makefile` uses the `-O2` option, and then `strspn` is inlined.

**Comment by akotulski** [comment]
I looked more into the issue and found the problem: clang AST is looking differently when compiled with `-O2` and we don't want that. Infer has a [model](https://github.com/facebook/infer/blob/master/infer/models/c/src/libc_basic.c#L278) for `strspn` which we should use.
I'm going to fix issue with `-O2` and I'll leave "conditional inside statement expression" problem

**Comment by skcho** [comment]
Thanks. It works now in our case.

**Comment by akotulski** [comment]
I just tested the repro case and it works now, probably because of https://github.com/facebook/infer/commit/e366b0d9b57fdb9ca33b92731643bb9776541156
