### ISSUE TITLE
How can I change the rules or add new rules?

### ISSUE THREAD

**Issue by tonyying** [facebook/infer#526]
Hi,
Is there any way to change the rules or add new rules?
eg: change the bug level from error to warning , or ignore specific type bug
thanks for any help :)

**Comment by jvillard** [comment]
Let me answer your questions in reverse order:
- To ignore a specific bug type there is a `--disable-checks` option. Use it on the command line: `infer --disable-checks MEMORY_LEAK --disable-checks RESOURCE_LEAK` or inside .inferconfig:

```
{
    "disable-checks": [
      "MEMORY_LEAK",
      "RESOURCE_LEAK"
    ]
}
```

- Bug levels are hardcoded for each bug type and cannot be changed.
- What rules would you like to change/add?

**Comment by tonyying** [comment]
Thanks for the answer.
It's helpful for me.
