### ISSUE TITLE
C++ class support

### ISSUE THREAD

**Issue by skcho** [facebook/infer#528]
Hi, I'm curious about Infer's support for C++ class.

What happens when a method of a class is invoked? Does Infer start to analyze the callee for calculating its summary?

When given some method calls, it does not look like working as I expected. For example,
```C++
#include <stdlib.h>
#include <unistd.h>
class Foo
{
public:
  void myshell()
  {
    execl(getenv("foo"), getenv("foo"));
  }

};
int main(int argc, char* argv[])
{
  Foo* f = new Foo();
  f->myshell();
  execl(getenv("foo"), getenv("foo"));
} 
```
in this code, there are two sink points inside the `main` function and `myshell` function. However, the analysis result is only about the main function, not the method call. The command I used is `infer -a quandary -- g++ -c a.cpp`.

**Comment by jvillard** [comment]
C++ support is still experimental and you need to pass `--cxx` to infer to capture c++ code:

```
infer --cxx -a quandary -- g++ -c a.cpp
```

**Comment by skcho** [comment]
Oh, I see. Thank you.
