### ISSUE TITLE
Can I suppress infer warning on a block of code rather than putting on a function?

### ISSUE THREAD

**Issue by harshikesh** [facebook/infer#530]
Can I suppress infer warning on a block of code rather than putting on a function?
Registering a listener from onStart() of an Activity to another class is giving a ContextLeak issue. but I am unregistering it in onStop() from same activity. This is false Positive.

**Comment by jvillard** [comment]
Infer doesn't support suppressing warnings on a block of code but you could always put the offending code in a separate method and add `@SuppressWarnings("infer")` on that method.

**Comment by harshikesh** [comment]
Thanks 👍
