### ISSUE TITLE
A method annotated @SuppressParameterNotNullable is considered @Nullable.

### ISSUE THREAD

**Issue by clonetwin26** [facebook/infer#533]
This annotation makes infer think a method is @Nullable even when its not. I think it sees @ and Nullable and causes this bug.

**Comment by sblackshear** [comment]
Good catch. We check if the suffix of the annotation is `Nullable` so we don't need to add separate cases for `javax.lang.Nullable`, `my.custom.Nullable` etc, but it looks like that's the wrong thing to do here :). We should probably check if the unqualified classname is exactly `Nullable` instead.
