### ISSUE TITLE
How to debug Infer's backend

### ISSUE THREAD

**Issue by leo-yinle** [facebook/infer#536]
Hi,

I have had experience of developing compilers' backend. Generally the backend is started in debug, e.g. gdb, and stops at some breakpoints. The backend can be executed step by step and function calls can be followed by stepping into. The IR of the analyzed program can be printed to stdout/stderr or dumped into files. 

However, as a newcomer of OCaml, I cannot find the counterpart things in debugging Infer's backend, which is implemented in OCaml and compiled to native code. Ocamldebug can only work on bytecode. For natvie code, gdb can break at modules' functions, but I found it is extremely hard to print variables' value in OCaml programs. That means examining IR and analysis results in Infer's backend is not easy.

I have read the book, real-world-ocaml and seen Mark Shinwell's video 'https://www.youtube.com/watch?v=NF2WpWnB-nk'. Both them does not give much instructions on printing variables in gdb. 

How do you infer developers debug hundreds of thousands of lines of OCaml code?  Could someone give some advice?

Thanks a lot in advance.

**Comment by dulmarod** [comment]
Hi, 
Most of us don't use a debugger to debug Infer. We just print elements, most of the IR elements have print functions, so we use those. To debug the symbolic execution in particular, we use html files that have printed most of the execution. You get those files with the option --debug, there is an html file for each source file in the folder infer-out/captured. Also, when you print things, if you use Logging.out, the output is only available in debug mode, and in infer-out/log/.... 

I hope this helps, let us know if you have more questions.

**Comment by leo-yinle** [comment]
Hi @dulmarod 

Thank you for your replay.  My question was answered.
