### ISSUE TITLE
Implementation/interface file pairs sometimes clash in filename initial letter case

### ISSUE THREAD

**Issue by ngorogiannis** [facebook/infer#539]
Hello! There are some pairs of .ml/.mli files that differ in casing, e.g.:

checkers/AbstractInterpreter.mli ; checkers/abstractInterpreter.ml

If I rename "abstractInterpreter.ml" to match the case of the .mli file, the build fails. 

There are other instances of this, but not as problematic (eg, checkers/abstractDomain.ml and checkers/AbstractDomain.mli, but building doesn't fail when casing is fixed).

**Comment by jvillard** [comment]
Good catch! Did you remove the build directory before running `make` again? (in infer/_build) In any case I'll send a diff (unless you send one first).

**Comment by ngorogiannis** [comment]
I did `make clean ; make`. 

The reason I didn't include a patch is that it's not that simple :) It seems that `abstractInterpreter.ml` and `AbstractInterpreter.mli` have diverged (eg the `S` signature is different), and it's not obvious to the uninitiated how to reconcile them.

**Comment by sblackshear** [comment]
Wow, that is an unfortunate problem! Nice one. I will fix this.

**Comment by sblackshear** [comment]
Thanks for the report, this should be fixed by 084fd9301be42b5a24980b8b6abc2bb46c399fe1.
