### ISSUE TITLE
FTBFS

### ISSUE THREAD

**Issue by ngorogiannis** [facebook/infer#540]
Hi, infer fails to build from source for me in a freshly cloned folder. 

```
File "checkers/ThreadSafety.ml", line 162, characters 30-62:
Error: Unbound value FbThreadSafety.is_logging_method
```

Command is `build-infer.sh java`.

**Comment by sblackshear** [comment]
Thanks, should be fixed by e817d5390d8087061e74c052d28560c9d37d90ea. Sorry for the breakage.
