### ISSUE TITLE
xcodebuild succeeds but infer fails after finding issues with Apple's framework

### ISSUE THREAD

**Issue by devKrishnan** [facebook/infer#544]
I used the below command to Build a dummy project. The build succeeded without any problems

> xcodebuild -project InferTesting.xcodeproj -scheme InferTesting -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' clean build

Then I used same command with infer prefix to run the infer on my project.

> infer --  xcodebuild -project InferTesting.xcodeproj -scheme InferTesting -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' clean build

**Output** 

http://pastebin.com/M11ZMbRt

**Comment by jvillard** [comment]
Does the issue persist with a more up-to-date infer? You should be able to upgrade with `brew update && brew upgrade infer`.
