### ISSUE TITLE
Publish infer annotations on Central

### ISSUE THREAD

**Issue by davido** [facebook/infer#546]
For easy integration with java projects that not use Monorepo approach (and not check in all dependencies into their repositories), it would be great if `infer` annotations could be published on Central, so that I could just say in `BUCK`:

```python
  remote_file(
    name = 'infer-annotations',
    sha1 = '0b5e946b76cdb1f00b18f2981e7d997141a66c9f',
    url = 'mvn:com.facebook.infer:annotations:jar:1.5',
    out = 'infer-annotations.jar',
  )
```

**Comment by sblackshear** [comment]
This sounds like a great idea! We will look into doing this when we create the next release of Infer.

**Comment by sblackshear** [comment]
We have the annotations published now; see https://github.com/facebook/fresco/commit/b33eefb87639a1cf22e0f6d5068305afe1bbf497 for an example usage.

**Comment by davido** [comment]
Thanks.
