### ISSUE TITLE
how to let infer work in python3.5

### ISSUE THREAD

**Issue by vincentyao** [facebook/infer#551]
Dears:
   i have finished download and install infer0.9.4 on my computer. But my python's version is Python 3.5.2 (default, Nov 10 2016, 12:31:28) .

  when i do execution, infer have a exception occur. i have to edit the infer.py file #!/usr/bin/env python3.5

but the infer still can not execution.

please help,if i want to infer can work in python3.5. how to do it?

thanks

**Comment by jvillard** [comment]
Infer needs Python 2.7 to work. You should be able to install Python 2.7 alongside Python 3.5.2 to use infer. `infer` calls `python27` explicitly so in particular the `python` executable can point to Python 3.5.2 so as not to affect your Python environment.

**Comment by vincentyao** [comment]
@jvillard
Thanks!~
As your message, infer can not support with python3.5? we just let infer  execute in python 2.7 version?

**Comment by jvillard** [comment]
@vincentyao yes

**Comment by kstreee** [comment]
@vincentyao FYI, I strongly recommend the [pyenv](https://github.com/yyuu/pyenv) to handle Python version and dependencies.

**Comment by vincentyao** [comment]
@kstreee 
thanks for your help. i use it in python2.7 now ~~~
