### ISSUE TITLE
Eradicate not reading annotations from class file

### ISSUE THREAD

**Issue by msridhar** [facebook/infer#559]
Not sure if this is a bug or a missing feature (or neither).  I have two source files as input.  

T1.java:
```java
import android.support.annotation.*;
public class T1 {
    public static void checkStr(@NonNull String s) {
    }
}
```
T2.java:
```java
public class T2 {
    public static void main(String[] args) {
        T1.checkStr(null);
    }
}
```
I have infer installed from Homebrew, version 0.9.4.  If I run javac on T2.java with Eradicate, I get the expected result:
```
$ infer -a eradicate -- javac T2.java
Capturing in javac mode...
Translating 2 source files (2 classes)
[...]
Found 2 source files in /Users/msridhar/eradicate_test/infer-out
FF.
Analyzed 2 files

Found 1 issue

T2.java:4: error: ERADICATE_PARAMETER_NOT_NULLABLE
  `checkStr(...)` needs a non-null value in parameter 1 but argument `null` can be null. (Origin: null constant at line 4)
  2.   
  3.       public static void main(String[] args) {
  4. >         T1.checkStr(null);
  5.       }
  6.   
```
However, if I first compile T1.java with javac **without** running Eradicate, and then run javac on T2.java with Eradicate, I get no error:
```
$ javac T1.java
$ infer -a eradicate -- javac T2.java
Capturing in javac mode...
Translating 1 source files (1 classes)
[...]
Found 1 source files in /Users/msridhar/eradicate_test/infer-out
F
Analyzed 1 file

  No issues found  

```
Hence it seems that Eradicate is not reading the `@NonNull` annotation from the T1.class file.  If this is in fact a missing feature and not a bug, I think it'd be a very useful addition for Eradicate to be able to leverage annotations in extant class files.

Thanks for the great tool!

**Comment by akotulski** [comment]
I'm not familiar with eradicate so it may be a little off, but in general if you want to analyze certain file, you need to compile it with `infer --` command. Otherwise we are blind about contents of those files (`T1.java` in your example). That being said `eradicate` is a little bit different/simpler and there may be solution to you problem.

> I think it'd be a very useful addition for Eradicate to be able to leverage annotations in extant class files.

Could you write some concrete example you had in mind?

**Comment by msridhar** [comment]
Thanks for the response!  The main motivating example is with 3rd-party libraries.  If the library is unannotated, there are [tools](https://types.cs.washington.edu/annotation-file-utilities/) that let you inject separately-written annotations into the class files.  (Why not add annotations to the source and contribute back?  Some libraries, like [RxJava](https://github.com/ReactiveX/RxJava/wiki), don't want to introduce any third-party dependencies, e.g., on annotation classes.  Also, it's possible you don't have the source.)  So it'd be cool if Eradicate could leverage these class-file annotations to do better checking.  

Additionally, it may be that you don't care about errors within the 3rd-party library, in which case you'll get some build-time win by not running Infer on the library source code.

**Comment by jeremydubreil** [comment]
Hi @msridhar.

It is theoretically possible to follow the annotations from the 3rd party libraries. One thing that is not so clear is that different libraries do not necessarily follow the same convention when it comes to `@Nullable`. For example, for analyzed source code, 
```
void checkStr(@NonNull String s) {
   ...
}
```
is equivalent to:
```
void checkStr(String s) {
   ...
}
```
for Eradicate, meaning that parameter are consider non-nullable by default except when analyzed with `@Nullable` explicitly.

However, your example suggests that we would want to do the opposite assumption for 3rd party libraries when unannotated variables should be considered as `@Nullable` by default except when annotated with `@NonNull`. But this approach would not work for Guava for instance, which uses `@Nullable` more or less as Eradicate expects it. So there should be a way to tell Eradicate, or to detect automatically, which convention is used for each library. 

Or we may want to follow a 3-value logic for libraries and consider no annotation as `unknown` together with `@NonNull` and `@Nullable`

**Comment by msridhar** [comment]
Hi @jeremydubreil yes that's a good point.  My example was contrived; I wanted to keep things simple to make sure I was running the tool correctly.  Probably the right thing to do is to assume usage similar to Guava when annotations from class files are being parsed.  If it's clearly documented, I think that would work well for most cases.  Also, maybe the default should be to behave just as Infer does now (ignoring annotations in class files) to avoid surprises and/or a ton of unwanted false positives.

**Comment by sblackshear** [comment]
One additional issue that I just became aware of: annotations on method parameters/return values actually live in the constant pool, not in the method signature. For already-compiled classes (and anything else in the classpath), we parse the method signature and add it to the type environment, but we don't look at the implementation of the method or its constant pool. This is why you're seeing the weird behavior on your example.

We might be able to parse only the constant pool in such cases so we can at least have the annotations for pre-compiled code. Will look into it.

**Comment by jeremydubreil** [comment]
@sblackshear, it would actually be easy to load the annotations from the 3rd party library. There is already some support for analyzing the dependencies. For example (changing the example a bit to avoid the issue with `@NonNull` mentioned earlier):

```
public class Lib {

    @Nullable static Object foo() {
        return null;
    }

}
```
and
```
public class Test {

    void bar() {
	Lib.foo().toString();
    }

}
```
We can actually have Eradicate report the issue using the undocumented `--dependencies` options:
```
  $ javac Lib.java
  $ infer --dependencies -a eradicate -- javac Test.java
```
The reason why we don't use `--dependencies` by default is to avoid duplication of work when using Buck as the same class. e.g. `java.lang.String` could otherwise be analyzed on many different Buck targets.

The new genrule based approach to integrate Infer with Buck could actually allow use to analyze the third party libraries only once (decorating `prebuilt_jar`) and cache the analysis artifacts, which would contain the annotations as well. cc @kageiit

**Comment by kageiit** [comment]
@jeremydubreil That sounds like a great idea. As long as infer knows how to extract the analysis artifacts from the `prebuilt_jar` or `prebuilt_android_aar` decorated infer/eradicate genrules, the performance impact will be minimal and the quality of analysis will be a lot greater. Seems like that is the best approach forward.

**Comment by jeremydubreil** [comment]
By the way, this has been solved now. Eradicate can now be run entirely on compiled bytecode and using Buck genrules, which is almost one order of magnitude faster than the other Buck integration using the external compiler option. Example: https://github.com/facebook/infer/blob/master/DEFS

It will by default report inconsistencies about all the code in the classpath. To avoid reporting non-actionable warnings on third party code, we can pass the prefixes of the packages we want to filter out using the `--external-java-packages` option. Example: https://github.com/facebook/infer/blob/master/infer/tests/codetoanalyze/java/checkers/.inferconfig#L21
