### ISSUE TITLE
Running Infer Problem : xcode-select: error: tool 'xcodebuild' requires Xcode

### ISSUE THREAD

**Issue by adityakasturi** [facebook/infer#56]
I am trying to do this in the terminal But I got the following error 

xcodebuild -workspace mcollect.xcworkspace -scheme mcollect -configuration Debug -sdk iphonesimulator
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Am I missing some dependency in here, inorder to run the Xcode Project perfectly what all do I need to install. 

Thanks

**Comment by martinoluca** [comment]
Hello @adityakasturi,
I think you should install Xcode again on your Mac, then try the running the infer command again.
