### ISSUE TITLE
Adding models doc doesn't highlight source  code

### ISSUE THREAD

**Issue by xennygrimmato** [facebook/infer#560]
This is just a minor documentation bug I guess; the `Adding models` page [here](http://fbinfer.com/docs/adding-models.html) doesn't highlight syntax. The markdown text seems to be correct, but the UI doesn't render the highlighted syntax.

**Comment by jvillard** [comment]
Thanks for the report! Apparently GitHub stopped supporting `C` and `Java` as languages and wants `c` and `java` instead. Looks ok now as far as I can tell.
