### ISSUE TITLE
Uncaught exception: ( Sys_error “ //android.content.e967034d408e8fa099bccaf2a80273ba.attr6bb662.tmp.tmp” :file name too long ) 

### ISSUE THREAD

**Issue by 2290120311** [facebook/infer#561]
I'm trying to install infer(https://github.com/facebook/infer/blob/master/INSTALL.md#pre-compiled-versions) on my Ubuntu 14.04 system, But now I'm facing a problem,one tmp file name too long that abort the make progress.see blew

![error](https://cloud.githubusercontent.com/assets/25050663/21839035/8dd353e8-d810-11e6-9069-7da37d983168.PNG)
Is any one can give me some advice on it. Waiting for your reply.

Here is my system information:
![sysinfor](https://cloud.githubusercontent.com/assets/25050663/21839122/13d67d30-d811-11e6-9236-3ab59358c4ec.PNG)

**Comment by jvillard** [comment]
Could you paste the full output together of the build command as text? It's hard to count the number of characters on an image ;)

What's weird to me is that this path doesn't seem too long: no path element seems to be over 255 characters (but I haven't counted precisely). What filesystem is this, can you give the output of `mount`?

**Comment by jberdine** [comment]
It may also be that realpath of a seemingly short path turns out to be very long.

**Comment by mwotton** [comment]
I'm getting this while analysing Tor:

```

**Comment by jvillard** [comment]
Closing due to lack of response. Please reopen if there's still an issue.
