### ISSUE TITLE
false-positive (?) on null deferencing 

### ISSUE THREAD

**Issue by cxzhang2** [facebook/infer#562]
error message:
![image](https://cloud.githubusercontent.com/assets/2879713/21866075/ab49660a-d816-11e6-93a4-c4dd679ee259.png)

code that it's referencing:

```
    public float foo() {
        float key = 1f;

        if (map.get(key) != null) {
            return map.get(key);
        } else {
            //...
        }
    }
```

changing the key to a `Float` "fixes" the bug.

strangely, hardcoding the key also doesn't generate a bug report, e.g.:

```
if(map.get(1f) != null){
  return map.get(1f);
}
```

is fine according to Infer.

**Comment by jeremydubreil** [comment]
Hi @cxzhang2. Is `1f` a global constant in your example ?

**Comment by cxzhang2** [comment]
It is local

**Comment by jeremydubreil** [comment]
Do you still get the NPE reported if you use:
```
  if (map.containsKey(key) != null) {
    return map.get(key);
  } ...
```
?

**Comment by cxzhang2** [comment]
yes

**Comment by jeremydubreil** [comment]
Yes, sorry.

Thanks for checking. So Infer does not understand that `map.get(key)` called twice in a row will return the same value. So Infer assume that `map.get(key)` can return null in `return map.get(key);` does dereference the returned value to unbox the float value. This is indeed a false positive, thanks for reporting it. I will check how we can make Infer not reporting anything here. 

However, I would suggest to rewrite the code as:
```
  Float value = map.get(key);
  if (value != null) {
    return value;
  } else {
     ...
  }
```
which avoids an unnecessary lookup from the map.

**Comment by cxzhang2** [comment]
Hey @jeremydubreil thanks for the suggestion I'll do that for now.  My intuition is that Infer does a `==`check on the keys.  This would explain why `float` generated the bug report but `Float` and the hardcoded `1f` doesn't.   i.e. looking just at the keys of the two map.get() calls, these are the three scenarios:

```
float key = 1f;
Float.valueOf(key) == Float.valueOf(key)  //false, null check is ignored, report bug
```

```
Float key = 1f;
key == key //true, null check is honored
```

`1f == 1f //true, null check is honored`

**Comment by jvillard** [comment]
I think infer's heuristic has changed regarding this type of bugs: now it assumes that two calls to the same function will return the same result. Infer version 0.15.0 does not report anymore on this example:

```Java
import java.util.HashMap;

class Foo {

  public static Float foo(HashMap<Float,Float> map) {
    float key = 1f;

    if (map.get(key) != null) {
      return map.get(key);
    }
    return key;
  }

  public static void goo(HashMap<Float,Float> map) {
    Float f = foo(map);
    if (f.equals(1f)) { }
  }

}
```
