### ISSUE TITLE
when I run infer, my computer crash

### ISSUE THREAD

**Issue by zhangying19871987** [facebook/infer#563]
I use infer 0.9.3 to analyse my ios app, but sometimes my computer crash like this:
<img width="1325" alt="c4f71023-b3ad-4bf8-86f0-3376f6967ca4" src="https://cloud.githubusercontent.com/assets/18108287/21922507/e87b7bfa-d9a9-11e6-9320-492a706058ae.png">

**Comment by zhangying19871987** [comment]
when this happen, I can do nothing without kill the infer process

**Comment by akotulski** [comment]
Please upgrade to infer-0.9.4.1 and try again:
  brew update && brew upgrade infer

**Comment by jvillard** [comment]
Please re-open if the issue is still there with the latest infer version.

**Comment by tate666** [comment]
There is the same issue I'm facing and I'm using Infer-version v0.15.0.  I used infer to do the workspace project for 4~5 times. but each time infer processed to a same profile my mac mini became dead-slow and I can do nothing then unless turn-off the power of the mac. I wonder is there something wrong with the hardware of the mac or are there some issues with the profile I mentioned...Don't know what to do now, can anyone help me to solve this???

**Comment by ngorogiannis** [comment]
Sounds like infer consumes most of the RAM on your mac mini.  Can you post what language is the project in, what build system it's using and whether this happens during capture or analysis?  Also, how much RAM you have.

Unfortunately, mac minis are often too under-powered for analysis -- have you tried running infer on a higher spec machine?

**Comment by tate666** [comment]
> Sounds like infer consumes most of the RAM on your mac mini. Can you post what language is the project in, what build system it's using and whether this happens during capture or analysis? Also, how much RAM you have.
> 
> Unfortunately, mac minis are often too under-powered for analysis -- have you tried running infer on a higher spec machine?

Mac mini (Late 2014) has 8 GB 1600 MHz DDR3 RAM,2.6 GHz Intel Core i5 CPU.  I'm not sure this specification could run infer smoothly. Yesterday, infer run my iOS-app workspace project in capture phase for a while, the RAM detector showed the process consumed over 90% RAM. After that the pc could not work any more. I'll try it on a MacBook pro today, thanks anyway.
