### ISSUE TITLE
Problem in blacklisting the file in eradicate

### ISSUE THREAD

**Issue by mohammedsafiq** [facebook/infer#566]
Hi, 

I have to ignore some files in my project for eradicate analyzer. 

So, in .inferconfig, I have wrote,

"eradicate_blacklist":[
"filename1",
"filename2"]

But eradicate is still running the analyzer for the above mentioned files even though it is blacklisted. 

Here is the command which i use to run eradicate.

infer -a eradicate -- ./gradlew --offline assLollipopDeb

I have also tried eradicate-path-regex and eradicate-files-containing. None of this helps. 

Any help is valued at most.!

**Comment by sblackshear** [comment]
Are `filename1` and `filename2` relative paths to the files from the project root? If you are running Eradicate from `myproject/` and `filename1` is at `myproject/src/com/my/project/filename1`, .inferconfig would expect `src/com/my/project/filename` in `eradicate_blacklist`.

In addition, note that the blacklist does not actually stop Eradicate from running on those files altogether; it just stops Eradicate from reporting any errors on those files. If there are other files that call `@Nullable` methods from `filename1` (directly, or transitively), those errors will still be reported.

**Comment by jvillard** [comment]
Please re-open if you have more questions about this.
