### ISSUE TITLE
Eradicate and conditional field initialization

### ISSUE THREAD

**Issue by msridhar** [facebook/infer#567]
Test case:
```java
import android.support.annotation.*;
public class CondFieldInit {
    Object o1;
    @Nullable Object o2 = null;    
    public CondFieldInit() {
        if (o2 != null) {
            o1 = new Object();
        }
    }
    public static void main(String[] args) {
        CondFieldInit x = new CondFieldInit();
        x.o1.toString();
    }
}
```
Eradicate finds no issues for the above code, but running the code fails with an NPE.  I'm not sure if this is a bug or whether my expectations are off, in terms of what kind of guarantees Eradicate is intended to provide around field initialization.

**Comment by msridhar** [comment]
Here's another similar test:
```java
import android.support.annotation.*;
public class CondFieldInit2 {
    @Nullable Object f1;
    static Object condInit(boolean b) {
        CondFieldInit2 x = new CondFieldInit2();
        if (b) {
            x.f1 = new Object();
        }
        return x.f1;
    }
    public static void main(String[] args) {
        Object y = condInit(false);
        y.toString();
    }
}    
```
Not sure if this is the same problem or not.  If it's different, let me know and I can open a separate issue.

**Comment by cristianoc** [comment]
Thanks for the reports.
In both cases, referencing the object before the conditional triggers the expected report (`Object tmp = o1;` and `Object tmp = x.f1;`), so perhaps the same mechanism can address both.
I'll do some experiments and see how that affects the rest of the system.

**Comment by msridhar** [comment]
Ok, great, thanks for looking into it!

**Comment by satabafome** [comment]
DEUS LUZ FORÇA AXE

**Comment by cristianoc** [comment]
Hi @msridhar, there is a new treatment of conditionals in https://github.com/facebook/infer/commit/319e3ed271e81618bdd809823c2dbb9e065e2794.
This affects the treatment of conditionals in general, when a value is accessed for the first time in one branch of the conditional, and is not accessed in the other branch. The tests we have run look positive so far.

**Comment by msridhar** [comment]
That sounds great!  Did you leave this issue open deliberately?  If the tests above are behaving as expected now, I'm fine with closing.  It may take a bit time before we are able to run this new version across our code base.

**Comment by cristianoc** [comment]
Great, let us know if you notice anything. Closing for now.
