### ISSUE TITLE
Syntax highlighting has arrived for Reason on Github

### ISSUE THREAD

**Issue by chenglou** [facebook/infer#568]
@jberdine I recall you wanted to remove those comment headers for Reason files?

**Comment by cristianoc** [comment]
@chenglou what's the expected classification in the bar that shows the distribution of files per language?
With the comment headers, .re files are classified as Rust files.
Without comment headers, e.g. `InferPrintExe.re` seems not to be classified as any language: https://github.com/facebook/infer/search?utf8=%E2%9C%93&q=InferPrint&type=Code
Though there is syntax highlighting.

**Comment by chenglou** [comment]
https://github.com/github/linguist/pull/3336 seems to have categorized it as plain ocaml. Will have to verify with @freebroccolo

**Comment by freebroccolo** [comment]
Originally they were going to be classified as Reason files but one of the linguist maintainers requested that I change it to OCaml.
