### ISSUE TITLE
Don't escape from the build dir

### ISSUE THREAD

**Issue by reactormonk** [facebook/infer#57]
The installer creates `facebook-clang-plugin` in the parent dir of the repo. That is unexpected behavior, I'd prefer any github repo not to modify any parent dirs.

**Comment by irpap** [comment]
Hi @reactormonk , thanks for reporting this. We are aware of this issue and will work on fixing it.

**Comment by jvillard** [comment]
Fixed by 9ebb365bef293914cc42e8b0a36c4ff767ff8469
