### ISSUE TITLE
Conflicting if condition value in an error trace

### ISSUE THREAD

**Issue by Guoanshisb** [facebook/infer#572]
Hi there,

I am using Infer (version v0.9.4) to analyze sqlite and got a weird error trace that contains contradictory values of a certain if condition.

```
sqlite3.c:70443: Condition is true
  70441.   */
  70442.   SQLITE_PRIVATE const void *sqlite3ValueText(sqlite3_value* pVal, u8 enc){
  70443. >   if( !pVal ) return 0;
  70444.     assert( pVal->db==0 || sqlite3_mutex_held(pVal->db->mutex) );
  70445.

sqlite3.c:70443: Condition is false
  70441.   */
  70442.   SQLITE_PRIVATE const void *sqlite3ValueText(sqlite3_value* pVal, u8 enc){
  70443. >   if( !pVal ) return 0;
  70444.     assert( pVal->db==0 || sqlite3_mutex_held(pVal->db->mutex) );
  70445.
```

Shaobo

**Comment by jvillard** [comment]
Infer includes the evaluation of sub-expressions in the trace, so the way to read this is:
1. `pVal` is true
2. `!pVal` is false

I agree that this can be confusing when negations are involved, especially when the subexpression is trivial. This could be made clearer by adding column number information to the traces to clarify which sub-expression is being evaluated. This is quite hard as, eg, the Java frontend does not provide column number information as of yet. Or, infer could have a special case for trivial sub-expressions of negations, but maybe that's too ad-hoc.

Maybe the easiest way to solve this would be to print the sub-expression in the trace message:
```
sqlite3.c:70443: Condition `pVal` is true
sqlite3.c:70443: Condition `!pVal` is false
```

**Comment by Guoanshisb** [comment]
@jvillard Thanks for your reply. It make sense now. May I ask another question about error trace? I noticed that some functions are not stepped into in the error trace even I set the max level to "max". I was wondering if the analysis is broken somewhere in these functions.

**Comment by jvillard** [comment]
@Guoanshisb this can happen when infer failed to analyse a function for some reason. Possible reasons include infer getting confused when trying to understand the code, or the function taking too long to analyse.

It could be useful to include that kind of info in the trace too in the future.

**Comment by Guoanshisb** [comment]
Thanks, @jvillard. It's so nice of you to answer my questions. Just want to confirm this issue:

```
sqlite3.c:142394: Condition is true
142392.     sqlite3ValueSetStr(pVal, -1, zFilename, SQLITE_UTF16NATIVE, SQLITE_STATIC);
142393.     zFilename8 = sqlite3ValueText(pVal, SQLITE_UTF8);
142394. >   if( zFilename8 ){
142395.       rc = openDatabase(zFilename8, ppDb,
142396.

sqlite3.c:142395:
142393.     zFilename8 = sqlite3ValueText(pVal, SQLITE_UTF8);
142394.     if( zFilename8 ){
142395. >     rc = openDatabase(zFilename8, ppDb,
142396.                         SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE, 0);
142397.

sqlite3.c:142398: Condition is true
142396.                         SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE, 0);
142397.       assert( *ppDb || rc==SQLITE_NOMEM );
142398. >     if( rc==SQLITE_OK && !DbHasProperty(*ppDb, 0, DB_SchemaLoaded) ){
142399.         SCHEMA_ENC(*ppDb) = ENC(*ppDb) = SQLITE_UTF16NATIVE;
142400.
```

This is the last part of an error trace I got from executing the command, `inferTraceBugs --select 11 --max-level max`. `*ppDb` is initialized to 0 at the beginning and got deferenced at line 142399 (`#define ENC(db)        ((db)->enc)`). However, `openDatabase` can have side effects of updating `*ppDb` to a non-null pointer and it is not stepped into in this error trace. For this case, I was wondering what happened. Is a summary computed for `openDatabase`?

**Comment by jvillard** [comment]
@Guoanshisb you can look at the specs in infer-out/specs/ and see if you see one for `openDatabase()`. It should look like `openDatabase.<some hash>.specs`. `InferPrint` knows how to read .specs files if you pass them on the command line (depending on how you installed infer, you may not have it in your `PATH` though, but it's always at `$(dirname $(realpath $(which infer)))/InferPrint`).

**Comment by Guoanshisb** [comment]
@jvillard There are some specs for this function,

```
Procedure: openDatabase
int openDatabase(char* zFilename, struct sqlite3** ppDb, unsigned int flags, char* zVfs)
Timestamp: 3
Status: INACTIVE
Phase: RE_EXECUTION
Dependency_map: 
ERRORS: 
WARNINGS: 
TIME:0.000000 s FAILURE:SYMOPS TIMEOUT (334) SYMOPS:334 CALLS:0,0
```
Does it mean the analysis times out on this function?

**Comment by jvillard** [comment]
`FAILURE:SYMOPS TIMEOUT (334)` yup, that's a timeout (too many symbolic execution steps).

We are increasing the default timeout in the next release (it's already in master), but in the meantime you can increase the timeout using the options `--iterations` and `--symops-per-iteration`. See `infer --help-full` for usage.

**Comment by jvillard** [comment]
I filed #574 and #575 to address the points about making traces more informative, I think this one can be closed now. Let me know if you have other issues!
