### ISSUE TITLE
Eradicate is not understanding the flow in the code.

### ISSUE THREAD

**Issue by mohammedsafiq** [facebook/infer#573]
Hi, 

Please look in the following example.

@Nullable
public String name;

public static boolean notEmpty(@Nullable String string) {
    return !isEmpty(string);
}

public static boolean isEmpty(@Nullable CharSequence str) {
        if (str == null || str.length() == 0)
            return true;
        else
            return false;
}

**My piece of code is**,

public void checkString()
{
   if (notEmpty(name) && name.equals("SomeConstants")) 
   {
   //do something
   }
}

**Now the problem.!!**

Eradicate throws a issue that, in checkString() method, name could be null and NPE will happen in .equals("SomeConstants"). But if you look at notEmpty(name) is already having null check. 

So, why eradicate is not understanding the flow of code and what will be the best solution for this??

Any help is appreciated.

**Comment by cristianoc** [comment]
Hi @mohammedsafiq, Eradicate works pretty much like a type checker, where a value annotated @Nullable is considered as always being potentially null, so local checks for null are required.
In particular, Eradicate does not try to understand the flow of values in a method call, such as `notEmpty(name)`. Another way to look at this: it only considers information at method boundaries, so it will give the same result for any implementation of `isEmpty`, including the one which always returns `true`.

**Comment by cristianoc** [comment]
Closing for now. Feel free to reopen if there are further questions.
