### ISSUE TITLE
Print the expression being evaluated in infer traces

### ISSUE THREAD

**Issue by jvillard** [facebook/infer#574]
This will help understand for instance which condition is being evaluated when infer prints `Condition is true/false`. An example from #572:

```C
sqlite3.c:70443: Condition is true
  70441.   */
  70442.   SQLITE_PRIVATE const void *sqlite3ValueText(sqlite3_value* pVal, u8 enc){
  70443. >   if( !pVal ) return 0;
  70444.     assert( pVal->db==0 || sqlite3_mutex_held(pVal->db->mutex) );
  70445.

sqlite3.c:70443: Condition is false
  70441.   */
  70442.   SQLITE_PRIVATE const void *sqlite3ValueText(sqlite3_value* pVal, u8 enc){
  70443. >   if( !pVal ) return 0;
  70444.     assert( pVal->db==0 || sqlite3_mutex_held(pVal->db->mutex) );
  70445.
```

The goal would be for infer to include a different message in the trace, so that `inferTraceBugs` would print this instead:

```C
sqlite3.c:70443: Condition `pVal` is true
  70441.   */
  70442.   SQLITE_PRIVATE const void *sqlite3ValueText(sqlite3_value* pVal, u8 enc){
  70443. >   if( !pVal ) return 0;
  70444.     assert( pVal->db==0 || sqlite3_mutex_held(pVal->db->mutex) );
  70445.

sqlite3.c:70443: Condition `!pVal` is false
  70441.   */
  70442.   SQLITE_PRIVATE const void *sqlite3ValueText(sqlite3_value* pVal, u8 enc){
  70443. >   if( !pVal ) return 0;
  70444.     assert( pVal->db==0 || sqlite3_mutex_held(pVal->db->mutex) );
  70445.
```

The code printing this message is [here](https://github.com/facebook/infer/blob/fb14d31bb71c480e548cfa2bb22a3c2117e698b4/infer/src/backend/paths.ml#L455-L456).

See #572 for more details.

**Comment by xennygrimmato** [comment]
Can this issue be extended to also cover an entire `if` condition. To be specific, we currently output `Taking true branch` or `Taking false branch`, but we should ideally print the expression as well.
Referring to [this part of code](https://github.com/facebook/infer/blob/fb14d31bb71c480e548cfa2bb22a3c2117e698b4/infer/src/backend/paths.ml#L447-L448).

**Comment by jvillard** [comment]
@xennygrimmato yes, that makes sense.
