### ISSUE TITLE
False Positive Detected by Infer in JAVA

### ISSUE THREAD

**Issue by Vissonabe** [facebook/infer#576]
False positive for Null reference exception.

I have a static method
```Java
public static boolean notEmpty(@Nullable String string) {
    return !TextUtils.isEmpty(string);
 }
```

when i call this in class like this

```Java
String temp;
if(notEmpty(temp)) {
 int i = temp.length;
}
```

it still throws `temp` could be null.

Can you please tell what is the solution for this.

**Comment by jvillard** [comment]
Sorry it took so long to reply. I'm assuming you are talking about the Eradicate analysis? You can annotate `notEmpty` to let it know that it returns true if `string` is not null:

```Java
import com.facebook.infer.annotation.FalseOnNull;

@FalseOnNull
public static boolean notEmpty(@Nullable String string) { ... }
```
