### ISSUE TITLE
can't install infer from source via ./build-infer.sh java

### ISSUE THREAD

**Issue by carozuoP** [facebook/infer#578]
when I run ./build-infer.sh java, it popped
=-=- Synchronising pinned packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[infer-deps-iGyw] /Users/zuoqiong/Documents/infer/infer/infer-deps-iGyw/ already up-to-date
The following dependencies couldn't be met:
  - infer-deps-iGyw -> reason >= 1.4.0
Your request can't be satisfied:
  - reason>=1.4.0 is not available because the package is pinned to https://github.com/jberdine/reason.git#infer, version 0.0.5.

what steps do I need to do ?
my environment is : 
zuoqiongs-MacBook-Pro:~ zuoqiong$ opam install utop
[NOTE] Package utop is already installed (current version is 1.19.3).
zuoqiongs-MacBook-Pro:~ zuoqiong$ python --version
Python 2.7.12
zuoqiongs-MacBook-Pro:~ zuoqiong$ opam --version
1.2.2
zuoqiongs-MacBook-Pro:~ zuoqiong$ pkg-config --version
0.29.1
zuoqiongs-MacBook-Pro:~ zuoqiong$ java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
zuoqiongs-MacBook-Pro:~ zuoqiong$ brew install libffi --force
Updating Homebrew...
Warning: libffi-3.0.13 already installed, it's just not linked
zuoqiongs-MacBook-Pro:~ zuoqiong$ brew link --force libffi
Linking /usr/local/Cellar/libffi/3.0.13... 10 symlinks created
I only need to it works on android project, not for object c project.

**Comment by jvillard** [comment]
Your version of reason was pinned at a specific version that is outdated, probably by a previous version of the `build-infer.sh` script. You need to unpin it:

```sh
OPAMSWITCH=infer-4.02.3 opam pin remove reason merlin merlin_extend
```

Let me know if this works for you.

**Comment by carozuoP** [comment]
it worked, but it still pop error. I installed successfully finnaly by opam update, opam upgrade, it fixed all my dependencies. thanks jvillard
