### ISSUE TITLE
Build failed -  libraries:facebook:lint

### ISSUE THREAD

**Issue by icaspi** [facebook/infer#58]
I'm trying to execute "infer -- gradle build" on an Android project, at first it complained about LeakCanary (https://github.com/square/leakcanary) I suspect its something with its lint release configuration, after removing LeakCanary it complains about this -

22:41:36.360 [ERROR] [org.gradle.BuildExceptionReporter] 
22:41:36.360 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
22:41:36.361 [ERROR] [org.gradle.BuildExceptionReporter] 
22:41:36.361 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
22:41:36.361 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':libraries:facebook:lint'.
22:41:36.361 [ERROR] [org.gradle.BuildExceptionReporter] > Lint found errors in the project; aborting build.
22:41:36.361 [ERROR] [org.gradle.BuildExceptionReporter]

22:41:36.361 [ERROR] [org.gradle.BuildExceptionReporter] Fix the issues identified by lint, or add the following to your build script to proceed with errors:
22:41:36.362 [ERROR] [org.gradle.BuildExceptionReporter] ...
22:41:36.362 [ERROR] [org.gradle.BuildExceptionReporter] android {
22:41:36.362 [ERROR] [org.gradle.BuildExceptionReporter] lintOptions {
22:41:36.362 [ERROR] [org.gradle.BuildExceptionReporter] abortOnError false
22:41:36.362 [ERROR] [org.gradle.BuildExceptionReporter] }
22:41:36.362 [ERROR] [org.gradle.BuildExceptionReporter] }
22:41:36.362 [ERROR] [org.gradle.BuildExceptionReporter] ...
22:41:36.362 [ERROR] [org.gradle.BuildExceptionReporter] 
22:41:36.363 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
22:41:36.363 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.

My release config (gradle clean assembleGoogleRelease) is building fine...

Any ideas?

**Comment by akotulski** [comment]
@icaspi could you run to tell us which version of javac you have?
javac -version

If you could tell us how we could repro this it would help us a lot in troubleshooting.

**Comment by irpap** [comment]
Thanks @icaspi for reporting this. It seems related to this https://github.com/facebook/infer/issues/18. I'll take a look.

**Comment by icaspi** [comment]
@akotulski - javac 1.7.0_79
@irpap - thank you very much let me know if I can help

**Comment by irpap** [comment]
A temporary workaround would be to run " gradle build -x lint" instead to bypass the lint, but we're working on a proper fix.

**Comment by vinod12452** [comment]
hello

**Comment by icaspi** [comment]
That sorted out the issue, thanks!

**Comment by jvillard** [comment]
`gradle build -x lint` sounds like a proper fix to me.
