### ISSUE TITLE
build-infer.sh fails with opam 1.2.0

### ISSUE THREAD

**Issue by 3flex** [facebook/infer#588]
Related to #554 (specifically this https://github.com/facebook/infer/pull/554#issuecomment-271283944)

Confirm that build-infer.sh fails on opam 1.2.0 due to the changed name of the flag as of https://github.com/ocaml/opam/commit/9ccabc03f75b1908ce5fda4c676ddd16d9d0c7ce#diff-906c973c07f8c64e8dd7866de2b40e35. Error is:
```
initializing opam... 
opam: unknown option `--compiler'
```

Would either need to support both `--comp` and `--compiler` flags in build-infer.sh so Debian stable continues to work, or increase minimum opam version to 1.2.1 in [INSTALL.md](https://github.com/facebook/infer/blob/master/INSTALL.md)

**Comment by jvillard** [comment]
Thanks @3flex. As I said in the comment you link to, I'd rather bump the minimum version of opam we support that periodically fix the build for ancient opam versions. Would that make sense for your use-case too?

**Comment by 3flex** [comment]
Yes, I was only playing around with the Docker build, so bumping the minimum version would have no effect on me.
