### ISSUE TITLE
Cannot find Command InferPrint

### ISSUE THREAD

**Issue by sagpatil** [facebook/infer#594]
Hi,

I am getting started with Infer and I can see it analyzed the project and created the output json and csv files, however I cannot use InferPrint to see the report.

I am on Infer version v0.10.0.

I get a -bash: InferPrint: command not found

**Comment by jvillard** [comment]
Hi @sagpatil, we do not put `InferPrint` in the PATH because it's internal to `infer`, but it's still available. You should be able to find it with `$(dirname $(realpath $(which infer)))/InferPrint`, or directly with `/usr/local/Cellar/infer/0.10.0/lib/infer/infer/bin/InferPrint`.

**Comment by sagpatil** [comment]
Thanks @jvillard
