### ISSUE TITLE
Confuse how to integrate Infer into our Gitlab CI 

### ISSUE THREAD

**Issue by sencho** [facebook/infer#596]
I am confused how to integrate Infer into our Gitlab CI pipeline at static analysis stage:

* To slow
I use this command follow the wiki,but still scan whole project 1700+ files when CI Runner checkout the branch every time。
```
infer --reactive --continue -- xcodebuild -workspace xxx.xcworkspace -scheme xxx -sdk iphonesimulator10.2 -configuration Debug build
```

* Can seperate two phases?
 I just want to analyze  the commit files ,but Infer must compile first,and use command `infer -- <command>`
Suppose our CI pipeline include build,test,pre-production,production 4 phase.
Assuming there are two jobs in the build phase, the first job is build, the second is static analysis, , and `infer - <command>` combine  two jobs, and make the build phase become slow.

* Can not set the threshold, analyze the results and throw error  so that the pipeline to stop

Please give me a suggestion  how to integrate  infer into our CI process correctly，thanks!

**Comment by cristianoc** [comment]
@sencho is your build incremental, or does CI compile everything every time it runs?

**Comment by sencho** [comment]
Incremental, we have Android/iOS/Java/HTML5 project

**Comment by sencho** [comment]
compile everything every time it runs

**Comment by sencho** [comment]
@cristianoc ,I have another problem if the two builds are in different CI Runner, how can i ensure that two of the infer-out file contents are synchronized? Should i put the infer-out folder content up or ignore it?

**Comment by cristianoc** [comment]
OK then the best that can be done is to split the work into two parts:
1) together with the build, run the Infer capture phase only
```  infer -a capture -- ...build command...  ```
2) separately, find out what files you want to run the analysis on, and only analyze those files:
``` infer -reactive --changed-files-index index.txt -- analyze```
where `index.txt` contains a list of files to analyze, with relative path from the root of the project.
So if your project looks like this
```
 src/foo.c
 src/bar.c
```
then an example `index.txt` can be
```
src/foo.c
```

Typically, you will want `index.txt` to contain the set of files modified in the current commit.

**Comment by cristianoc** [comment]
@sencho since CI builds all the files every time, each CI Runner should have its own `infer-out`, so no synchronization. Unless I am missing some specific use you have in mind.

**Comment by sencho** [comment]
@cristianoc Can I use a regular expression to match the file name what i want to analyze?

Well, before that, I have to complete a complete analysis, right? Check if the  `infer-out` directory exists .if it exists, then run  incremental analysis, if not exist run full analysis.

**Comment by cristianoc** [comment]
@sencho `index.txt` must be an explicit list of files. You can use a regular expression in a script that generates `index.txt`.

With the process I've described above in points `1.` and `2.` there's no need to run a previous analysis: each analysis will be completely separate.

But, notice that step `1.`, the capture, must run on all the files, every time.

**Comment by sencho** [comment]
@cristianoc ,The third question is that Facebook is using Phabricator to do Code Review, but we are using Gitlab Code Review. When Infer completes the analysis, does the result insert the code into the code's comment to block CI progress?

**Comment by cristianoc** [comment]
Yes the analysis at FB inserts comments into the code review tool, but it does not block progress.
It appears together with the other comments, written by programmers, as part of code review.

**Comment by sencho** [comment]
![image](https://cloud.githubusercontent.com/assets/863912/23603825/9bfe6bd2-0291-11e7-9460-0895e3b87e11.png)

I see a presentation on the Infer team online, which has a slideshow introducing the process. When Infer analyzes the problematic code, it is commented on the code through the review tool's API. The code reviewer will ask for the development Repair again after submission, and then run an Infer analysis, until these is no problematic code then you can merge the code, right?

**Comment by cristianoc** [comment]
The reviewers decide when to accept the code. The static analysis is one of the inputs they use to decide. For example, the issue reported by Infer could be relevant and addressed immediately, or might not be relevant, or might be better addressed in a separate commit.

**Comment by cristianoc** [comment]
This is one way of deploying in CI. Feel free to use whatever works best for you, and let us know what's your experience.

**Comment by sencho** [comment]
@cristianoc Can you talk about the time and analysis strategy used by Facebook iOS App to give us a reference, when to use incremental analysis, when to use the full analysis in a CI process.I think I will share my practice here for everyone, if I succeed.

**Comment by cristianoc** [comment]
@sencho CI on iOS uses always incremental analysis, by giving the list of files that are in the current commit (step 2).

**Comment by sencho** [comment]
@cristianoc Thanks a lot for your help!

**Comment by cristianoc** [comment]
@sencho looking forward to hear about your experience. If all works well, a great outcome would be a short guide to help others with CI integration.

**Comment by sencho** [comment]
@cristianoc ,only infer capture phase spend 28 minutes for 1800+ files(iOS project) ,it is really unacceptable.If the speed is faster, I can implement in every push, instead of  merge request.How can i save time?

**Comment by cristianoc** [comment]
@sencho if you run the same build command, but without Infer, how long does it take?

**Comment by sencho** [comment]
@cristianoc it takes in 3 minutes without infer

**Comment by sencho** [comment]
Whether the performance of the machine will affect the speed?my mac's cup 2.7 GHz Intel Core i5,8G RAM,SSD

**Comment by sencho** [comment]
@cristianoc ,I follow your suggestion,run step2.
```
infer --reactive --changed-files-index ./index.txt
```
 just one .m file  inside index.txt file what I want to analyze, why infer print out all file's analysis result?
```
Summary of the reports

          DIRECT_ATOMIC_PROPERTY_ACCESS: 94
                 ASSIGN_POINTER_WARNING: 17
                 BAD_POINTER_COMPARISON: 10
                            MEMORY_LEAK: 3
  REGISTERED_OBSERVER_BEING_DEALLOCATED: 2
                STRONG_DELEGATE_WARNING: 1
```

**Comment by cristianoc** [comment]
@sencho that's an unusual slowdown -- something in the range of 2X is to be expected, but not from 3 to 28 minutes. You're referring to step 1, i.e. the capture command only, correct?

For your question on step 2, Infer analyzes all the functions called from the .m file you are providing. My guess is that's what you're observing. As a simple check: if `index.txt` is empty, then nothing will be analyzed.

**Comment by akotulski** [comment]
Can you provide full list of commands you run (step 1 and step 2)? I suspect you are running to much in step 1

**Comment by sencho** [comment]
@akotulski 
step1.
```
infer -a capture -- xcodebuild -workspace demo.xcworkspace -scheme demo-Debug -sdk iphonesimulator10.2 -configuration Debug build
```

step2.
```
infer --reactive --changed-files-index ./index.txt -- analyze
```
index.txt file just one .m file path 

```
cat ./infer-out/proc_stats.json |jq
```
```
{
  "files": 1,
  "procedures": 0,
  "lines": 0
}
```
as above proc_stats.json ,it analyze one file only.

**Comment by mohammedsafiq** [comment]
@cristianoc ,

Can i follow the same approach for android too?

1. Where should the index.txt file should reside? 

I followed two steps:

infer -a capture -- ./gradlew --offline assLollipopDeb
infer --reactive --changed-files-index ./index.txt -- analyze

I know there are two issues in the file which i given in index.txt. But its not working. I tried giving both relative path and absolute path of the file in index.txt. I placed index.txt inside infer-out.  

Still the proc_stats_json contains:

{ "files": 0, "procedures": 0, "lines": 0 }

Can you please elaborate if any different steps are available for Android?

**Comment by jvillard** [comment]
There is a now guide to help with setting up infer for CI jobs [in our docs](http://fbinfer.com/docs/steps-for-ci.html). Please open a new issue if you still notice slowdowns with recent infer (latest release is 0.15.0).
