### ISSUE TITLE
Problem with Gradle and AspectJ

### ISSUE THREAD

**Issue by martinschaef** [facebook/infer#6]
I tried infer on my project:
https://github.com/martinschaef/bixie/tree/master/tool
calling gradle clean and then 
infer -- gradle build
and it replies with

Starting analysis (Infer version v0.1.0)
Analysis done
3 files analyzed
No issues found

However, there are significantly more java files in this project. What am I doing wrong?

**Comment by sblackshear** [comment]
Hi Martin,
  You are not doing anything wrong--looks like there's an issue with Infer's Gradle support. The Gradle wrapper is quite primitive and just looks for calls to `javac` in the verbose output for Gradle. For some reason, these calls do not appear for your `compileJava` rule (I suspect it has something to do with the `ant options?).

I was able to get a little further by bypassing Gradle with `find src/main/ -name *.java | xargs infer -- javac -cp .:lib/*` from `bixie/tool/`, but then I ran into #3. We're working on fixing both that and the Gradle problem; thanks for the report!

**Comment by martinschaef** [comment]
Hi Sam ... small world! Are you with Facebook now? I'll follow the other issue as well then. Are you going to release a new version or should I build from source?

**Comment by sblackshear** [comment]
Hi Martin,
  Yes, I work at FB part-time now and am joining full-time in the fall! I am not sure what our policy on releasing new binaries is going to be--my guess is that we'll push bugfixes to source ASAP but that we will only release binaries for new major versions. So it might be worthwhile to try building from source.

**Comment by martinschaef** [comment]
Ok. The gradle problem is that I do some aspect weaving stuff which overrides the compileJava task. Once my I remove line 43 and 44-65 in build.gradle it finds everything but runs into the exception which you mentioned in the other issue. Thanks.

**Comment by jvillard** [comment]
Hi @martinschaef , #3 has been closed by the latest Infer release and it looks like this would solve your issue too. Feel free to reopen if v0.1.1 doesn't fix it for you.
