### ISSUE TITLE
Reactive mode is not working

### ISSUE THREAD

**Issue by RomanWuattier** [facebook/infer#600]
Hi!
I use infer to find every NPE in my Android application. Gradle is an incremental build system so I would analyse only the current changes.
Here is how I use reactive mode with infer v0.10.0:
```$ ./gradlew clean```
```$ infer -a capture -- gradle build```
```$ infer --reactive --continue -- gradle build```

Infer find some issues among 2000 files.

The execution time is very slow and infer analyse every files instead of the latests change.
Looks like the reactive mode is not working.

Thanks

**Comment by cristianoc** [comment]
Fixed in 1a3fcd44a1a8321c722182d3bde65bbc210b7028.
