### ISSUE TITLE
How to set the –iphoneos-target-sdk-version

### ISSUE THREAD

**Issue by qmkCamel** [facebook/infer#602]
infer  -- clang –iphoneos-target-sdk-version 8.0 
Is it like this ? 
But I got the following issue 
clang: error: no such file or directory: '–iphoneos-target-sdk-version'

thanks

**Comment by jvillard** [comment]
You want `--` (two dashes) not `–` (one long dash).

**Comment by dulmarod** [comment]
In general, you can check these things with infer --help.
