### ISSUE TITLE
Function specs missing

### ISSUE THREAD

**Issue by shaobo-he** [facebook/infer#604]
Hi,

In the spec folder, there are no specs for some functions in the source file. Is it possible to troubleshoot why it happens?

Thanks,
Shaobo

**Comment by jvillard** [comment]
What's the command you are using to run infer? If there are no specs for a function, it's most likely because the corresponding source file has not been captured.

**Comment by Guoanshisb** [comment]
I am using `infer -- make`. It appears to me the source is captured since other functions of the same file are analyzed and have corresponding specs.

**Comment by jvillard** [comment]
Would it be possible to give a source file reproducing the issue? #700 (which has a repro source file) doesn't seem related after all.

**Comment by legus78** [comment]
What is this in reference to..??

S. Michael Legus
1-385-495-7552

**Comment by jvillard** [comment]
Please reopen with more details.
