### ISSUE TITLE
Start analysis from certain function

### ISSUE THREAD

**Issue by Guoanshisb** [facebook/infer#605]
Hi,

May I ask if it is possible for Infer to start analysis from certain function? It would be useful if a bug is fixed on one function or the user would like to increase the time spent on some critical function of which the analysis times out.

Thanks,
Shaobo

**Comment by jvillard** [comment]
You can start from a specific **file**, but not from a specific procedure. See the `--changed-files-index` option.

**Comment by jvillard** [comment]
Let me know if you have more questions, feel free to reopen.
