### ISSUE TITLE
Incremental build is not work at iOS project

### ISSUE THREAD

**Issue by sencho** [facebook/infer#607]
Step1: edit one .m file

Step2: run below command 
```
 infer --reactive --continue -- xcodebuild -workspace demo.xcworkspace -scheme demo-Debug -sdk iphonesimulator10.2 -configuration Debug build
```
Infer is still scan all files,why?

**Comment by cristianoc** [comment]
Thanks, also reported in https://github.com/facebook/infer/issues/600.
A fix is available, we just need to push it.

**Comment by cristianoc** [comment]
Closing as duplicate. Please follow on https://github.com/facebook/infer/issues/600.

**Comment by sencho** [comment]
I had a issue #596  before ,but  no one can help me.
