### ISSUE TITLE
infer fails running clang command

### ISSUE THREAD

**Issue by sofiareis** [facebook/infer#609]
Hi, I'm trying to run infer on an objective-c file (infer -- clang -c AFNetworkReachabilityManager.m) but it gives me an error: 

 Capturing in make/cc mode...
AFNetworkReachabilityManager.m:195:5: error: cannot create __weak reference in file using manual reference counting
    __weak __typeof(self)weakSelf = self;
    ^
1 error generated.
Error: the following clang command did not run successfully:
  '/usr/local/Cellar/infer/0.10.0/lib/infer/facebook-clang-plugins/clang/install/bin/clang' "@/Users/fifaz/Documents/thesis/secbench/db/AFNetworking_AFNetworking/ml/vuln1/Vvul/AFNetworking/infer-out/clang/clang_command_5d6859.txt"
Uncaught exception:
  
  (Unix.Exit_or_signal (Exit_non_zero 1))

Raised at file "src/error.ml", line 7, characters 20-30
Called from file "backend/infer.ml", line 455, characters 2-21

If I run only clang (clang -c AFNetworkReachabilityManager.m) it gives me the report:

AFNetworkReachabilityManager.m:170:1: warning: method possibly missing a
      [super dealloc] call [-Wobjc-missing-super-calls]
}
^
AFNetworkReachabilityManager.m:195:5: error: cannot create __weak reference in file
      using manual reference counting
    __weak __typeof(self)weakSelf = self;
    ^
1 warning and 1 error generated.

**Comment by jvillard** [comment]
You have to give infer a working compilation command. You get a similar clang error in both cases (with and without infer). You may need to pass more flags to clang to compile your ObjC file.

**Comment by dulmarod** [comment]
That particular error may be because you need to add the flag -fobjc-arc. But yes, check that the clang command compiles first, then try it with Infer.

**Comment by sofiareis** [comment]
Yes, you're right. Thank you! :) Yesterday, I dove through the flags (clang --help | grep -i objc) for a while and solved the issue.
