### ISSUE TITLE
Issue Building clang

### ISSUE THREAD

**Issue by shreyasmrs** [facebook/infer#610]
I tried building clang after java and got stuck in the process.

details:

checking for ant... no
checking for buck... no
checking for mvn... no
checking for ndk-build... no
checking for ndk-build... no
checking for Python module lxml... ok
checking for xcpretty... no
configure: saving configure flags to ./config.flags
configure: creating ./config.status
config.status: creating Makefile.autoconf

  Warning: you are not using a release of Infer. The C and
  Objective-C analyses require a custom clang to be compiled
  now. This step takes ~30-60 minutes, possibly more.

  To speed this along, you are encouraged to use a release of
  Infer instead:

  http://fbinfer.com/docs/getting-started.html

  If you are only interested in analyzing Java programs, simply
  run this script with only the "java" argument:

  ./build-infer.sh java

Are you sure you want to compile clang? (y/N) y
CMake Warning at cmake/modules/HandleLLVMOptions.cmake:143 (message):
  -fPIC is not supported.
Call Stack (most recent call first):
  cmake/modules/HandleLLVMOptions.cmake:161 (add_flag_or_print_warning)
  CMakeLists.txt:497 (include)

CMake Warning (dev) at projects/libcxx/CMakeLists.txt:15 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'
clang: warning: argument unused during compilation: '-s'

This warning is keeping coming and clang is not built

Thanks
Shreyas

**Comment by jvillard** [comment]
Hi @shreyasmrs, these warnings are harmless. Clang takes a while to build (30 minutes to an hour).

**Comment by shreyasmrs** [comment]
/usr/bin/ld: ../../lib/libLLVMSupport.a(Error.cpp.o): relocation R_X86_64_32 against symbol `_ZN4llvm9ErrorList2IDE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../lib/libLLVMSupport.a(GraphWriter.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../lib/libLLVMSupport.a(IntEqClasses.cpp.o): relocation R_X86_64_32 against symbol `__gxx_personality_v0@@CXXABI_1.3' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../lib/libLLVMSupport.a(ScaledNumber.cpp.o): relocation R_X86_64_32 against symbol `_ZN4llvm7APFloat17x87DoubleExtendedE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../lib/libLLVMSupport.a(ScopedPrinter.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../lib/libLLVMSupport.a(YAMLParser.cpp.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../lib/libLLVMSupport.a(YAMLTraits.cpp.o): relocation R_X86_64_32S against symbol `_ZTVN4llvm4yaml2IOE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [lib/libLTO.so] Error 1
make[2]: *** [tools/lto/CMakeFiles/LTO.dir/all] Error 2
make[1]: *** [all] Error 2
Makefile:117: recipe for target 'clang_setup' failed
make: *** [clang_setup] Error 2

  compilation failure; you can try running

    make clean
    ./build-infer.sh clang

This was the error which i got from ./build-infer.sh clang (Many lines of error were there I reduced it)
I tried "make clean" and ./build-infer.sh clang 
Still i got the same errors

**Comment by jvillard** [comment]
Thanks for the report. To help us debug, could you checkout the latest master and paste the full output of `./build-infer.sh` into a gist? Eg `git checkout master && git pull && ./build-infer.sh 2>&1 > logs.txt`, then upload logs.txt to https://gist.github.com/.

Also, is this a linux machine or osx? Which version?
Thanks!

**Comment by shreyasmrs** [comment]
I'm running infer on kali linux 2.0 sana. The above command you mentioned has taken more than 3 hours. Should I stop it or let it run

**Comment by akotulski** [comment]
Full output of the compilation failure would helps us to determine what's the problem (but https://gist.github.com/ to paste the output).

Which version c++ compiler your system have?
`gcc --version`

**Comment by shreyasmrs** [comment]
gcc (Debian 4.9.2-10) 4.9.2

**Comment by akotulski** [comment]
Ok, that version should be new enough to build llvm.

If I understood correctly, `git checkout master && git pull && ./build-infer.sh 2>&1 > logs.txt` has been running for 3 hours?

Have you typed `y` to make clang compilation move forward? (you don't see prompt because it's redirected to logs.txt)

**Comment by jvillard** [comment]
Oops, yes, running `git checkout master && git pull && ./build-infer.sh --yes 2>&1 > logs.txt` will skip the prompts... You can check what's being done by running `tail -f logs.txt` in another terminal.

**Comment by shreyasmrs** [comment]
please look at the log file [<script src="https://gist.github.com/shreyasmrs/96b5a189d026113400112b103306d179.js"></script>](url) logs.txt

**Comment by akotulski** [comment]
Did you pipe stderr to logs.txt as well? I don't see those errors you mentioned before:
```
/usr/bin/ld: ../../lib/libLLVMSupport.a(Error.cpp.o): relocation R_X86_64_32 against symbol _ZN4llvm9ErrorList2IDE' can not be used when making a shared object; recompile with -fPIC /usr/bin/ld: ../../lib/libLLVMSupport.a(GraphWriter.cpp.o): relocation R_X86_64_32 against.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../lib/libLLVMSupport.a(IntEqClasses.cpp.o): relocation R_X86_64_32 against symbol __gxx_personality_v0@@CXXABI_1.3' can not be used when making a shared object; recompile with -fPIC /usr/bin/ld: ../../lib/libLLVMSupport.a(ScaledNumber.cpp.o): relocation R_X86_64_32 against symbol_ZN4llvm7APFloat17x87DoubleExtendedE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../lib/libLLVMSupport.a(ScopedPrinter.cpp.o): relocation R_X86_64_32 against .rodata.str1.1' can not be used when making a shared object; recompile with -fPIC /usr/bin/ld: ../../lib/libLLVMSupport.a(YAMLParser.cpp.o): relocation R_X86_64_32S against.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../lib/libLLVMSupport.a(YAMLTraits.cpp.o): relocation R_X86_64_32S against symbol `_ZTVN4llvm4yaml2IOE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by shreyasmrs** [comment]
I wrote the following command and got the logs file : git checkout master && git pull && ./build-infer.sh --yes 2>&1 > logs.txt

**Comment by jvillard** [comment]
Unfortunately I gave the wrong command and so we don't get stderr in the logs (need to redirect stderr to stdout *after* redirecting stdout to the log file)...

@shreyasmrs if you still have the energy, could you try this instead?
```
git checkout master && git pull && ./build-infer.sh --yes > logs.txt 2>&1
```

Thanks!

**Comment by shreyasmrs** [comment]
logs file for the above command <script src="https://gist.github.com/shreyasmrs/df21aa807ca0b4e674d1c30d62be4033.js"></script>

**Comment by jvillard** [comment]
@shreyasmrs looks like there's a problem with your paste; could you send again?

**Comment by jvillard** [comment]
@shreyasmrs ah, if I remove .js at the end of the URL it works correctly: https://gist.github.com/shreyasmrs/df21aa807ca0b4e674d1c30d62be4033

**Comment by shreyasmrs** [comment]
Do you got to know the error or issue which I'm facing in clang building

**Comment by jvillard** [comment]
The error is that [the linker fails](https://gist.github.com/shreyasmrs/df21aa807ca0b4e674d1c30d62be4033#file-lo-L9680):
```
[ 71%] Linking CXX shared library ../../lib/libLTO.so
/usr/bin/ld: ../../lib/libLLVMAArch64CodeGen.a(AArch64AsmPrinter.cpp.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
```

It says to use "-fPIC". However, the configure phase says that ["-fPIC" is not supported by the compiler](https://gist.github.com/shreyasmrs/df21aa807ca0b4e674d1c30d62be4033#file-lo-L414-L415):
```
-- Performing Test C_SUPPORTS_FPIC
-- Performing Test C_SUPPORTS_FPIC - Failed
-- Performing Test CXX_SUPPORTS_FPIC
-- Performing Test CXX_SUPPORTS_FPIC - Failed
CMake Warning at cmake/modules/HandleLLVMOptions.cmake:143 (message):
  -fPIC is not supported.
Call Stack (most recent call first):
  cmake/modules/HandleLLVMOptions.cmake:161 (add_flag_or_print_warning)
  CMakeLists.txt:497 (include)
```

These are only observations. I don't understand why it fails that way yet.

**Comment by shreyasmrs** [comment]
Is there any solution you know for this?

**Comment by jvillard** [comment]
We're looking into it.

**Comment by jvillard** [comment]
I managed to reproduce the issue, working to fix it.

**Comment by jvillard** [comment]
Thanks for your patient reporting @shreyasmrs! Please re-open this issue if the current master still doesn't build clang for you.

**Comment by shreyasmrs** [comment]
Thanks for the update. Just to be sure. I have infer in my downloads folder, so the command for PATH is export PATH=/root/Downloads/infer/bin:$PATH/ I need to put this is /etc/profile file and source /etc/profile  right??

**Comment by shreyasmrs** [comment]
Thanks for the commit on github. however I'm unable to clone the facebook-clang-plugins using ./autogen.sh I not sure why this is not working.

**Comment by jvillard** [comment]
@shreyasmrs yes that's one way. You can also run `make install` to install infer in /usr/local/bin, or use `./configure --prefix=/usr` to install in /usr/bin (more installation options are available, see `./configure --help`).

**Comment by shreyasmrs** [comment]
Hi, @jvillard I tried with the new commit as well. I'm still facing the same issue for building the clang. Any suggestions on this please

**Comment by jvillard** [comment]
Hi @shreyasmrs, could you paste again the result of this command? Thanks!
```
git checkout master && git pull && ./build-infer.sh --yes > logs.txt 2>&1
```
