### ISSUE TITLE
Problem with @SuppressWarnings("infer")

### ISSUE THREAD

**Issue by mohammedsafiq** [facebook/infer#612]
Hi, 

I read the documentation that @SuppressWarnings will have no support from v0.10.0. 

Now i have installed v0.10.0 and in my project i have used @SuppressWarnings("infer") in 24 places. I thought after installing v0.10.0 it it will throw 24 errors to replace @SuppressWarnings with @SuppressLint. 

But it is not throwing. So does it mean like @SuppressWarnings will work in v0.10.0??

Any help is appreciated.!!

**Comment by jvillard** [comment]
Hi @mohammedsafiq,

Other tools use `@SuppressWarnings` annotations, so they won't make infer crash but infer will ignore them. In particular, infer may report on methods annotated with `@SuppressWarnings("infer")`.

**Comment by mohammedsafiq** [comment]
No. Its not reporting the methods annotated with @SuppressWarnings("infer")

**Comment by mohammedsafiq** [comment]
And it is throwing few new NULL_DEREFERENCE issues which is not thrown in previous versions.

**Comment by jvillard** [comment]
If you introduce an obvious bug in one of the methods annotated with `@SuppressWarnings`, does infer report it? Maybe it simply doesn't find any issues anymore on these methods as they are.

**Comment by mohammedsafiq** [comment]
Yes I have introduced obvious bug with @SuppressWarnings just to test. Its not reporting. Have you given any backward compatibility?

**Comment by jvillard** [comment]
Can you paste the command you are using and the result of `infer --version`? Thanks!

**Comment by mohammedsafiq** [comment]
Infer version v0.10.0

**Comment by vavrusa** [comment]
Is it possible to annotate C files? Or add models without rebuilding infer?

**Comment by jvillard** [comment]
Closing since I cannot reproduce locally. Please reopen if you are able to reproduce this issue on a self-contained example that you can share with us.
