### ISSUE TITLE
build failed  : fatal error: 'cstddef' file not found

### ISSUE THREAD

**Issue by xiaoNizi90** [facebook/infer#62]
What I use:
Step 1：
	xcodebuild -target MyProject -configuration Debug -sdk iphoneos8.3 clean
Step 2:
	infer -- xcodebuild -target MyProject -configuration Debug -sdk iphoneos8.3

What I got:

dwarf_stack.hpp:30:10: fatal error: 
      'cstddef' file not found
#include <cstddef>
         ^
1 error generated.

** BUILD FAILED **

The following build commands failed:
	CompileC build/CrashReporter.build/Debug-iphoneos/CrashReporter-iOS-Device.build/Objects-normal/arm64/dwarf_stack.o Source/dwarf_stack.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
None

**Comment by martinoluca** [comment]
Hello @xiaoNizi90, maybe this helps:
http://stackoverflow.com/questions/18358350/include-cstddef-file-not-found-in-xcode

**Comment by xiaoNizi90** [comment]
I had tried this before,not useful for me. 
http://stackoverflow.com/questions/18358350/include-cstddef-file-not-found-in-xcode

**Comment by martinoluca** [comment]
@xiaoNizi90 This issue has been addressed, please consider using the latest release available in:
https://github.com/facebook/infer/releases/latest

Reopen this task if the problem still persists.
