### ISSUE TITLE
Issue in capture and analyse - Infer

### ISSUE THREAD

**Issue by mohammedsafiq** [facebook/infer#620]
@cristianoc

I have read the article to make the infer to analyze only the modified files. 
https://github.com/facebook/infer/issues/596

Can i follow the same approach for android too?

Where should the index.txt file should reside?
I followed two steps:

`infer -a capture -- ./gradlew --offline assLollipopDeb`
`infer --reactive --changed-files-index ./index.txt -- analyze`

I know there are two issues in the file which i given in index.txt. But its not working. I tried giving both relative path and absolute path of the file in index.txt. I placed index.txt inside infer-out.

Still the proc_stats_json contains:

{ "files": 0, "procedures": 0, "lines": 0 }

Can you please elaborate if any different steps are available for Android?

**Comment by cristianoc** [comment]
Can you try this on the example given in the Infer distribution.
These are the same commands you're mentioning, and they work for me.

```
cd infer/examples/android_hello
./gradlew clean
infer -a capture -- ./gradlew build

cat ./index.txt
app/src/main/java/infer/inferandroidexample/MainActivity.java

infer --reactive --changed-files-index ./index.txt -- analyze

```

**Comment by mohammedsafiq** [comment]
After excuting the following command, still the index.txt file is empty. 

`cat ./index.txt
app/src/main/java/infer/inferandroidexample/MainActivity.java`

But index.txt should include the file path right?

**Comment by cristianoc** [comment]
Sorry for the confusion: you should edit `index.txt` so that it contains one line:
```
app/src/main/java/infer/inferandroidexample/MainActivity.java
```
Then give the command
```
infer --reactive --changed-files-index ./index.txt -- analyze
```

**Comment by mohammedsafiq** [comment]
Should the file reside inside the infer-out or outside?

**Comment by jvillard** [comment]
Outside. "infer-out" may get wiped out by infer if you run infer without `--reactive`.

**Comment by mohammedsafiq** [comment]
Still not working. Still saying No Issues found. 

I tried 

`./gradlew clean`
`infer -a capture -- ./gradlew build --offline assLollipopDeb`
`cat ./index.txt app/src/main/java/com/olacabs/customer/ui/GreenCategoryHelper.java`
`infer --reactive --changed-files-index ./index.txt -- analyze`

Inside index.txt file, i tried both of the below path:

/Users/mohammedsafiq.sa/Documents/Projects/android/app/src/main/java/com/olacabs/customer/ui/GreenCategoryHelper.java

app/src/main/java/com/olacabs/customer/ui/GreenCategoryHelper.java

Nothing worked.

**Comment by jvillard** [comment]
I don't think your `cat` command does anything. Try:
```
./gradlew clean
infer -a capture -- ./gradlew build --offline assLollipopDeb
echo app/src/main/java/com/olacabs/customer/ui/GreenCategoryHelper.java > index.txt
infer --reactive --changed-files-index ./index.txt -- analyze
```

**Comment by mohammedsafiq** [comment]
Dint work. I am just following your command. Still not sure why it is not throwing.

**Comment by mohammedsafiq** [comment]
Ok now its analysing. Actually its /index.txt and not ./index.txt. 

It said 7 source files found and analysed. How come 7 files when i hardcoded one file path in index.txt?

**Comment by jvillard** [comment]
@mohammedsafiq In order to analyze a file, infer has to analyze all the procedures called from that file. So if some of these procedures live in different files then they are also analyzed. That doesn't mean that all the procedures in these files were analyzed, only the ones called (transitively!) from the original file.

**Comment by jvillard** [comment]
Looks like this is resolved, please reopen if I'm mistaken.
