### ISSUE TITLE
Infer report Null-Rereference wrongly

### ISSUE THREAD

**Issue by carozuoP** [facebook/infer#621]
I use Infer scanning our Android project. Everything goes fine, however it report some null-dereference which should be handled well. Two samples below may make sense: 

## Sample 1:
Infer reports 
> object jsonArray last assigned on line 169 which could be null and is dereferenced by call to getAlphabetList(...) at line 170
```  
168. String key = iterator.next();
169. JSONArrayPoxy jsonArray = alphabetJson.getJSONArrayOrNull(key);
170. ArrayList<BrandValueModel> alphabetValueList = getAlphabetList(jsonArray);
```
But method getAlphabetList defined as below: 
```
private ArrayList<BrandValueModel> getAlphabetList(JSONArrayPoxy jsonArray) {
	ArrayList<BrandValueModel> list = new ArrayList<BrandValueModel>(); 
	if (jsonArray != null && jsonArray.length() > 0) { 		
             for (int i = 0, len = jsonArray.length(); i < len; i++) { 			
                 try {
```
Since it appears already handles the null-pointer, I don't think Infer need report such error.

## Sample 2 
```
Class A {
    Util utils=new Util();
    utils.createAccount(null); 
}
```
Null could be directly passed to method createAccount(),  but it has already check just as sample 1 above. So can infer do something like depth first search?

**Comment by jvillard** [comment]
Can you give a complete trace of the error using `inferTraceBugs`? Infer should not report if `null` is handled correctly by the method.

**Comment by carozuoP** [comment]
You mean you want the whole log by using infer --trace-error gradle assembleDebug?

**Comment by carozuoP** [comment]
> AndroidJD-Lib/src/com/jingdong/common/entity/FilterBrand.java:170: error: NULL_DEREFERENCE
  object jsonArray last assigned on line 169 could be null and is dereferenced by call to getAlphabetList(...) at line 170
```
  168.   				String key = iterator.next();
  169.   				JSONArrayPoxy jsonArray = alphabetJson.getJSONArrayOrNull(key);
  170. > 				ArrayList<BrandValueModel> alphabetValueList = getAlphabetList(jsonArray);
  171.   				if (alphabetValueList != null && alphabetValueList.size() > 0) {
  172.   					alphabetKeys.add(key);
```

And getAlphabetList is defined as below
```
private ArrayList<BrandValueModel> getAlphabetList(JSONArrayPoxy jsonArray) {
    ArrayList<BrandValueModel> list = new ArrayList<BrandValueModel>();
	if (jsonArray != null && jsonArray.length() > 0) {
		for (int i = 0, len = jsonArray.length(); i < len; i++) {
                    ...
                }
         } // end of if
         return list
} // end of func define
```

**Comment by jvillard** [comment]
@carozuoP I mean the output of `inferTraceBugs --max-level max` when you select the bug where infer seems to be wrong. `inferTraceBugs` is an executable that ships with infer.
