### ISSUE TITLE
Steps to speedup the build if infer & eradicate analysis is required

### ISSUE THREAD

**Issue by riyaz** [facebook/infer#623]
Below steps helped us improve the CI builds by 4 times, its good to include these in getting started section under CI section.

I can send PR if anyone can point right section or even if its required, anyways this issue will be help as reference if in case this does not make it to getting started.

We use both infer and eradicate steps in gitlab ci.

```

git diff --name-only origin/$CI_BUILD_REF_NAME..origin/develop > index.txt

infer -a capture -- ./gradlew --offline assemblLollipopDebug

infer --fail-on-issue -a infer --changed-files-index ./index.txt -- analyze --issues-txt issues.txt -- ./gradlew --offline -PdisableCrashlytics assemblLollipopDebug

infer --fail-on-issue -a eradicate --changed-files-index ./index.txt -- analyze --issues-txt issues.txt -- ./gradlew --offline -PdisableCrashlytics assemblLollipopDebug

```

**Comment by riyaz** [comment]
@cristianoc Done, sent PR

**Comment by peterogithub** [comment]
@riyaz, are you using, or have you considered, some of the functionality available under "infer -a checkers"?

In particular, there is a new check for classes labelled @ThreadSafe, which looks for concurrency issues. (Not so well documented yet, but it is there.)

Just though I'd ask!

**Comment by riyaz** [comment]
@peterogithub Not yet, now that we have faster build will include more analyzers, thanks for your inputs.

**Comment by jvillard** [comment]
Thanks for contributing this guide @riyaz, looks like the issue can be closed now that it's part of the website's documentation.
