### ISSUE TITLE
Not work in -sdk iphoneos

### ISSUE THREAD

**Issue by ludaye123** [facebook/infer#625]
hello, I hava a trouble  in this case, what should i do? 

infer  -- xcodebuild -workspace xxx.xcworkspace -scheme xxx  -configuration Debug -sdk iphoneos

Capturing using xcpretty...
Starting translating 0 files
.
Starting analysis...

legend:
  "F" analyzing a file
  "." analyzing a procedure

Found 0 source files in /Users/sangfor/Documents/xxx/infer-out

  No issues found

**Comment by dulmarod** [comment]
Maybe you need to clean the build first? If there is nothing to compile, Infer won't analyse anything.

**Comment by ludaye123** [comment]
yeah, I forget it , thanks
