### ISSUE TITLE
Static Memory Leak Detection

### ISSUE THREAD

**Issue by jsachs** [facebook/infer#629]
I'm currently enrolled in a course on software reliability, and I'm interested in using Infer to explore [static memory leaks in Android apps](http://blog.nimbledroid.com/2016/09/06/stop-memory-leaks.html). I've been digging through the repository and reading the docs to try to understand how to best build new checking capabilities. Are there any particularly good commits or PRs that demonstrate how to properly add a new feature to Infer?

Thanks,
Jacob

**Comment by sblackshear** [comment]
Hi Jacob,
  Infer already supports detecting some of these bug types (e.g., [`Context`](http://fbinfer.com/docs/infer-bug-types.html#CONTEXT_LEAK) leaks). Extending the detection to handle other cases like `View` leaks or leaks via `SensorManager` would should be pretty straightforward.

The code for reporting `Context` leaks lives [here](https://github.com/facebook/infer/blob/master/infer/src/backend/interproc.ml#L652), and the tests are [here](https://github.com/facebook/infer/blob/master/infer/tests/codetoanalyze/java/infer/ContextLeaks.java) (runnable with `make test`). I would probably start off by adding the examples from the blog post to see how many of them Infer can already find, and then refine the checker from there.

If you'd rather start from scratch, here's some [docs](http://fbinfer.com/docs/absint-framework.html) on building brand-new checkers on top of the Infer infrastructure.

Hope this helps and let me know if you have any questions!

**Comment by jsachs** [comment]
This is great, thanks @sblackshear!

**Comment by jsachs** [comment]
I've attempted to modify the context checker to look for any `View` that is assigned to a static variable, as follows (mostly based around changing `is_context` to `is_view`:

```ocaml
(** report an error if any View is assigned to a static field *)
let report_view_leaks pname sigma tenv =
  (* report an error if an expression in [view_exps] is reachable from [field_strexp] *)
  let check_reachable_view_from_fld (fld_name, fld_strexp) view_exps =
    let fld_exps = Prop.strexp_get_exps fld_strexp in
    let reachable_hpreds, reachable_exps =
      Prop.compute_reachable_hpreds sigma fld_exps in
    (* raise an error if any View expression is in [reachable_exps] *)
    List.iter
      ~f:(fun (view_exp, name) ->
          if Exp.Set.mem view_exp reachable_exps then
            let leak_path =
              match get_fld_typ_path_opt fld_exps view_exp reachable_hpreds with
              | Some path -> path
              | None -> assert false (* a path must exist in order for a leak to be reported *) in
            let err_desc =
              Errdesc.explain_view_leak pname (Typ.Tstruct name) fld_name leak_path in
            let exn = Exceptions.View_leak (err_desc, __POS__) in
            Reporting.log_error pname exn)
      view_exps in
  (* get the set of pointed-to expressions of type T <: View *)
  let view_exps =
    List.fold
      ~f:(fun exps hpred -> match hpred with
          | Sil.Hpointsto (_, Eexp (exp, _), Sizeof (Tptr (Tstruct name, _), _, _))
            when not (Exp.is_null_literal exp)
              && AndroidFramework.is_view tenv name
              && not (AndroidFramework.is_application tenv name) ->
              (exp, name) :: exps
          | _ -> exps)
      ~init:[]
      sigma in
  List.iter
    ~f:(function
        | Sil.Hpointsto (Exp.Lvar pv, Sil.Estruct (static_flds, _), _)
          when Pvar.is_global pv ->
            List.iter
              ~f:(fun (f_name, f_strexp) ->
                  check_reachable_view_from_fld (f_name, f_strexp) view_exps)
              static_flds
        | _ -> ())
    sigma
```

However, if fails to find the following memory leak. This is essentially the same form as a `Context` leak, and Infer was able to identify this example as an error when an `Activity` was used instead of a `View`.

```java
public class Option2Activity extends Activity {

    // Static View Variable
    static View view;

    @Override
    public void onCreate(Bundle icicle) {
        super.onCreate(icicle);

        // Remove title bar
        //this.requestWindowFeature(getWindow().FEATURE_NO_TITLE);
        // Remove notification bar
        //this.getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);

        setContentView(R.layout.activity_option);

        // Set title image
        ImageView imageView = (ImageView) this.findViewById(R.id.running_title);
        imageView.setImageResource(R.drawable.running_title_2);

        // Set back button action
        this.findViewById(R.id.backOption1Button).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Option2Activity.this.finish();
            }
        });

        // Leak memory
        leakMemory();
    }

    private void leakMemory(){
        view = this.findViewById(R.id.backOption1Button);
    }
}
```

**Comment by sblackshear** [comment]
Infer doesn't analyze the source code of the Android framework, so it only understands the behavior of functions like `findViewById` if we add an explicit model for the functions.

I would try replacing the call to `findViewById` with a dummy function like `getMyView() { return new ImageView(); }`. If this allows Infer to find the bug, then you can make this work for all calls to `findViewById` by [adding](http://fbinfer.com/docs/adding-models.html) a model of `findViewById` that returns an instance of a `View`.

**Comment by jsachs** [comment]
Hey @sblackshear,

Two things that we tried so far. Adding the explicit function for a `View` still returns nothing, whether running `infer -- gradle build` or `infer -a checkers -- gradle build` (just to see if the View fragment checker might grab it).

We also noticed that we will get slightly different results depending on the order of the checkers. For example,
```ocaml
if Config.curr_language_is Config.Java &&
    Procdesc.get_access pdesc <> PredSymb.Private then
    report_context_leaks pname post.Prop.sigma tenv;
    report_view_leaks pname post.Prop.sigma tenv;
```
produces two leaks, but
```ocaml
if Config.curr_language_is Config.Java &&
    Procdesc.get_access pdesc <> PredSymb.Private then
    report_view_leaks pname post.Prop.sigma tenv;   
    report_context_leaks pname post.Prop.sigma tenv;
```
produces duplicate leaks. It definitely indicates a bug in our code somewhere, but is there some reason that OCaml cares about order that I'm not comprehending? Thanks!

**Comment by sblackshear** [comment]
Ah, this looks like an OCaml gotcha. You probably want:

```
if Config.curr_language_is Config.Java &&
    Procdesc.get_access pdesc <> PredSymb.Private then
    begin
      report_context_leaks pname post.Prop.sigma tenv;
      report_view_leaks pname post.Prop.sigma tenv
  end;
```
In the code snippets you give, the first report instruction will run conditionally, but the second will always run. Think of `begin/end` as `{ }` for a language like C/Java; they create a block.

**Comment by jsachs** [comment]
Got it, thanks! Infer builds and runs correctly. We're still not finding the View leak, but the double counting is gone.

**Comment by sblackshear** [comment]
Hmm, so a simple example like`sView = new MyView()` still isn't detected? I'm not sure what could be going wrong there. What does the code for `report_view_leaks` look like?

**Comment by jsachs** [comment]
@sblackshear it's a few comments above, and still pretty much the same. All we really did was change `AndroidFramework.is_context` to `AndroidFramework.is_view`. My co-developer and I were curious if somehow the View isn't making it into `reachable_exps`.

**Comment by sblackshear** [comment]
One way to check on that is to run Infer on your example with the `--debug` [flag](http://fbinfer.com/docs/advanced-features.html) and check the debug HTML to see if the `View` is in the abstract state. I'm perplexed, though; it seems like your code should work.

**Comment by jsachs** [comment]
With lots of debugging information omitted, this is what I am seeing:
```java
private void leakMemory(){
    view = new ImageView(this); I_4 I_5
    SKIP_FUNCTION ImageView.(Context)
}
```

So does this mean that Infer is still not respecting the constructor as establishing a `View` rval, and we'll just have to implement the model?

**Comment by jvillard** [comment]
@jsachs did you manage to make it work in the end? `SKIP_FUNCTION` comes from the biabduction analysis, so it's unrelated to the context leak checker.

Unfortunately we have removed the context leak checker from infer as it had too many false positives, so I'm closing this issue. Feel free to reopen if you have more questions or want to work further on your checker for assigning Views to static variables!
