### ISSUE TITLE
Fail analyzing ios (Failure    "ERROR: Path is relative, when absolute path was expected .\n")

### ISSUE THREAD

**Issue by smarkovik** [facebook/infer#631]
Hey there, 
I am getting a weird fbinfer error, when analyzing an ios project. 
It all works fine on one machine but on our build server (jenkins) I get this error. 

The error shows up both in a jenkins look but also in a normal terminal.

the build works perfectly fine if I don't add `infer --` in front.

my analysis command is : 
`infer -- xcodebuild -project Project/Project.xcodeproj -target ProjectName -configuration Debug         -sdk iphonesimulator`

Stacktrace follows...

`Capturing using xcpretty...`
`Uncaught exception:`

`(Failure "ERROR: Path sources/Recognizer.m is relative, when absolute path was expected .\n")`
`Raised at file "pervasives.ml", line 30, characters 22-33`
`Called from file "base/SourceFile.ml", line 38, characters 4-101`
`Called from file "integration/CompilationDatabase.ml", line 80, characters 26-59`
`Called from file "list.ml", line 73, characters 12-15`
`Called from file "list.ml", line 73, characters 12-15`
`Called from file "integration/CompilationDatabase.ml", line 87, characters 2-48`
`Called from file "backend/infer.ml", line 195, characters 29-73`
`Called from file "backend/infer.ml", line 455, characters 2-21`

**Comment by akotulski** [comment]
I'm not sure you understand, are you saying you can run `infer -- <build_cmd>` on your laptop, but `infer -- <build_cmd>` fails on jenkins machine (both from jenkins and terminal on jenkins machine)

That's definitely not expected. Could you run following commands on your jenkins terminal?
```
echo $PWD
ls -id $(echo $PWD)
ls -id .
```

**Comment by smarkovik** [comment]
Exactly, 
on my laptop infer works like a charm, but on my CI (both through a jenkins shell script and in a normal terminal) I get the same error (described above).


`echo $PWD - root of repo : /Users/tancho/repos/project`
`ls -id $(echo $PWD) : 828343 /Users/tancho/repos/project`
`ls -id .  : 828343 .`

I am working on a mac (both ci and workstation)
no funky business with symlinks 
just a clean clone from github and running the infer analysis. 
again, a build works fine.

**Comment by akotulski** [comment]
> `echo $PWD - root of repo : /Users/tancho/repos/project`

That was ran on jenkins machine?

**Comment by smarkovik** [comment]
yes, from the normal terminal, not the build loop.
i imagine jenkins's shell environment will show other problems, so for the
time being I wanna make it work as If I use it as a work station
(the jenkins machine is a mac mini which I can access through screen
sharing, and open a normal terminal with a proper bash environment, this
output is from a normal terminal)



<http://www.contentsquare.com/>

Stanojko Tancho Markovikj
<https://data.sigilium.com/signatures/rcevuJOOuCK6-0hyNCIuGCIISRCzQrc/link?element=name>

Mobile Engineering Manager
<https://data.sigilium.com/signatures/rcevuJOOuCK6-0hyNCIuGCIISRCzQrc/link?element=job>

+33 6 51 17 53 54
<https://data.sigilium.com/signatures/rcevuJOOuCK6-0hyNCIuGCIISRCzQrc/link?element=mobile>
stanojko.markovik@contentsquare.com
50 avenue Montaigne - 75008 Paris
<https://data.sigilium.com/signatures/rcevuJOOuCK6-0hyNCIuGCIISRCzQrc/link?element=map_marker>
<https://www.facebook.com/ContentSquareGlobal>
<https://twitter.com/ContentSquare>
<https://www.youtube.com/user/Weballwin1>
<https://www.linkedin.com/company/contentsquare>

<https://data.sigilium.com/signatures/rcevuJOOuCK6-0hyNCIuGCIISRCzQrc/redirect_link>

On Wed, Mar 29, 2017 at 12:48 AM, Andrzej Kotulski <notifications@github.com

**Comment by jvillard** [comment]
This is the code that runs according to the backtrace:

[CompilationDatabase.ml](https://github.com/facebook/infer/blob/41c5be9bad47ff77b51c927363b5ef5a014b2c4d/infer/src/integration/CompilationDatabase.ml#L79-L80)
```OCaml
        let abs_file = if Filename.is_relative file then dir ^/ file else file in
        let source_file = SourceFile.from_abs_path abs_file in
```

[SourceFile.ml](https://github.com/facebook/infer/blob/ec6a3cf6bb36616c8c4cc4e619861a8e345d3e43/infer/src/base/SourceFile.ml#L36-L40):
```OCaml
let from_abs_path fname =
  if Filename.is_relative fname then
    (failwithf
       "ERROR: Path %s is relative, when absolute path was expected .@."
       fname);
```

So it seems that the directory `dir` we get from the compilation database is itself relative. If there's a way to look at the compilation database generated by xcpretty inside the failing jenkins job then we could confirm. In any case, it seems that the code in CompilationDatabase.ml should be hardened to handle that case.

**Comment by smarkovik** [comment]
Have in mind that this works on one machine and not another. 
even if I do a clean clone within a folder anywhere on this machine, it still won't work. 
Is it possible that infer is failing because of xcpretty? 
how about any dependency library which is the wrong version?
It's quite symptomatic that I can not make it work on a machine where it's broken, and I can't break it where it works fine... 

what do you guys think?

**Comment by jvillard** [comment]
@smarkovik hard to tell without seeing some logs on the failing Jenkins job. Can you get your job to run the commands that @akotulski mentioned? I'm also looking for a command you can run to dump the compilation database used by infer, so if you want you can wait until we have that too and run both in the same job to save yourself some time.

**Comment by jvillard** [comment]
Got it (thanks @dulmarod). @smarkovik can you please run these commands as part as your Jenkins job? (the same where infer is failing)

```sh
for path in $PWD sources sources/Recognizer.m; do
  echo $path;
  ls -id "$path";
done
ls -id .
xcodebuild -project Project/Project.xcodeproj -target ProjectName -configuration Debug -sdk iphonesimulator | xcpretty -report json-compilation-database  --output compile_commands.json
cat compile_commands.json
```

Or just check what the entry for "sources/Recognizer.m" is and whether it has a relative or absolute directory. You can also run these commands on your laptop to see if there's a significant difference.

**Comment by smarkovik** [comment]
When I try to run 
```xcodebuild -project Project/Project.xcodeproj -target ProjectName -configuration Debug -sdk iphonesimulator | xcpretty -report json-compilation-database  --output compile_commands.json
cat compile_commands.json```

I get an error, and the output files are not even created... 
I am starting to think `xcpretty` is the issue
```
xcodebuild  -project Project/Project.xcodeproj  -target Project  -configuration Debug -sdk iphonesimulator | xcpretty -report json-compilation-database  --output compile_commands.json
/Users/tancho/.rvm/gems/ruby-2.4.0/gems/xcpretty-0.1.5/bin/xcpretty:73:in `each_line': No such file or directory @ rb_sysopen - json-compilation-database (Errno::ENOENT)
	from /Users/tancho/.rvm/gems/ruby-2.4.0/gems/xcpretty-0.1.5/bin/xcpretty:73:in `<top (required)>'
	from /Users/tancho/.rvm/gems/ruby-2.4.0/bin/xcpretty:22:in `load'
	from /Users/tancho/.rvm/gems/ruby-2.4.0/bin/xcpretty:22:in `<main>'
	from /Users/tancho/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/tancho/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by dulmarod** [comment]
The argument to xcpretty is -r or --report, you were using -report, maybe that's the problem.

**Comment by jvillard** [comment]
Sorry, wrong command, I've edited my post.

**Comment by smarkovik** [comment]
You're absolutely right, the argument was to blame. 
here is the output from my actual project. 

/Users/tancho/Development/repos/cs-ios/attanni
6325429 /Users/tancho/Development/repos/cs-ios/attanni
ContentSquare/sources
6325659 ContentSquare/sources
ContentSquare/sources/CSPinchGestureRecognizer.m
6325698 ContentSquare/sources/CSPinchGestureRecognizer.m

compile commands attached
[compile_commands.txt](https://github.com/facebook/infer/files/879617/compile_commands.txt)

**Comment by jvillard** [comment]
Thanks! So indeed the compilation database gives us no absolute paths to work with...

Last (heh, maybe) question: did you run xcodebuild from /Users/tancho/Development/repos/cs-ios/attanni or /Users/tancho/Development/repos/cs-ios/attanni/ContentSquare?

I'm asking because the compilation database is of the form `{"directory": "sources", "file" : "CSPinchGestureRecognizer.m", "command": "<big command>"}` and doesn't mention having to look into "ContentSquare" so I hope it was where you ran the command from otherwise I don't see how infer could guess it...

**Comment by smarkovik** [comment]
Thanks for the quick reply
I ran it from `/Users/tancho/Development/repos/cs-ios/attanni ` which is the root of my project.

**Comment by jvillard** [comment]
Ok well that's bad news because I don't see how infer can find, eg, `/Users/tancho/Development/repos/cs-ios/attanni/ContentSquare/sources/CSPinchGestureRecognizer.m` given the information that the current dir is `/Users/tancho/Development/repos/cs-ios/attanni` and the compilation database says the file is in `sources/CSPinchGestureRecognizer.m`. At this point we have to resort to parsing the contents of `"command"` in the compilation database...

In the meantime, you can try using the alternative xcodebuild integration that doesn't rely on xcpretty: `infer --no-xcpretty -- xcodebuild ...`.

**Comment by smarkovik** [comment]
That actually solves my problems.... 
I can live without the xcpretty output, but I want to get the analysis...
thanks guys!
