### ISSUE TITLE
[ObjC] Skip analysis on file or part of File

### ISSUE THREAD

**Issue by smarkovik** [facebook/infer#633]
Hey guys, 
is there a way to skip a complete but single file or a part of a file, similarly to what you can do for Java with [@SuppressWarning("infer") ](https://github.com/facebook/infer/issues/206)

Anything similar for xcodebuild analysis?

**Comment by dulmarod** [comment]
Yes, you can skip a whole source file with the option --skip-analysis-in-path <path>. It also accepts regex.

 If you want to skip a header file, that is imported in some source file, you can use --skip-translation-headers <path to header>.

Skipping a part of the file is not supported for the ObjC analysis at the moment.

**Comment by smarkovik** [comment]
That would make for a nice feature... 

Thanks!
