### ISSUE TITLE
ERROR: "etree" Python package not found.

### ISSUE THREAD

**Issue by unkosun** [facebook/infer#635]
use `--pmd-xml` report an error

Summary of the reports

                    NULL_DEREFERENCE: 4
       DIRECT_ATOMIC_PROPERTY_ACCESS: 4
          PARAMETER_NOT_NULL_CHECKED: 2
                         MEMORY_LEAK: 1
                       RESOURCE_LEAK: 1
  PREMATURE_NIL_TERMINATION_ARGUMENT: 1

ERROR: "etree" Python package not found.
ERROR: You need to install it to use Infer with --pmd-xml
** Error running the reporting script:
**   /usr/local/Cellar/infer/0.10.0/lib/infer/infer/bin/../lib/python/report.py --issues-csv /Users/unkosun/Desktop/infer-master/examples/ios_hello/infer-out/report.csv --issues-json /Users/unkosun/Desktop/infer-master/examples/ios_hello/infer-out/report.json --pmd-xml --project-root /Users/unkosun/Desktop/infer-master/examples/ios_hello --results-dir /Users/unkosun/Desktop/infer-master/examples/ios_hello/infer-out

How to solve this problem

**Comment by jvillard** [comment]
You need to install the lxml package, which provides etree. See http://lxml.de/installation.html for instructions.
