### ISSUE TITLE
infer: command not found | Solution in #345 is also not working, throwing same 'command not found'

### ISSUE THREAD

**Issue by DhirajAggarwal** [facebook/infer#637]

**Comment by jvillard** [comment]
Hi @DhirajAggarwal, could you please include more information? Please follow [these guidelines](https://github.com/facebook/infer/blob/master/CONTRIBUTING.md#reporting-issues).

**Comment by DhirajAggarwal** [comment]
Hi @jvillard, I removed my old setup. And did a fresh start. I am getting the same error. I am surely missing some tiny thing. Below is the details of all commands and logs. Please have a look.

> brew install wget

> wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin

Here I got an error: **OPAM has already been initialized.[ERROR] /Users/dhiraj.aggarwal/.opam reports a newer OPAM version, aborting.** 
So I removed the **.opam** file and run the above command again. It worked smoothly. Opam gets installed.

> eval `opam config env`

In **.bash_profile**, I added this: **"test -r /Users/dhiraj.aggarwal/.opam/opam-init/init.sh && . /Users/dhiraj.aggarwal/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true"**

After that, I switched to infer directory

> cd ~/Documents/infer-osx-v0.10.0

> ./build-infer.sh java

Few errors were in the logs. I checked if infer has built through "**infer --version**" and I got the same "command not found". Check the build logs in attached file.[build-infer.sh_java.txt](https://github.com/facebook/infer/files/919510/build-infer.sh_java.txt)

**Comment by jvillard** [comment]
Thanks for the details. The log stops after opam succeeds and I see no errors there. Does the error come after that?

**Comment by DhirajAggarwal** [comment]
Hi @jvillard, errors are only in the attached file. No other error. infer gives no response to me yet.

**Comment by DhirajAggarwal** [comment]
Hey @jvillard, any help here will be appreciated. Just want to, how do I build a Java file now?

**Comment by jeremydubreil** [comment]
@DhirajAggarwal: if the java file compiles with:
```
> javac Test.java
```
then, you can run Infer with:
```
> infer -- javac Test.java
```
http://fbinfer.com/docs/infer-workflow.html

**Comment by jvillard** [comment]
@DhirajAggarwal After the build, infer is left in infer/bin, so you have to run `~/Documents/infer-osx-v0.10.0/infer/bin/infer`, not just `infer`.

You can run `make install` to install infer on your system (defaults to /usr/local/bin, see `./configure --help` for more options), then you can simply type `infer ...`.

**Comment by DhirajAggarwal** [comment]
@jvillard, Thanks a lot!! finally it worked. There were few dependencies were also there that I needed to install.

I built my android app and found multiple Null points. Need to check if they can be really Null. Again a big thanks to you and the community building this!!

**Comment by jvillard** [comment]
Glad to hear it, thanks for the feedback!
