### ISSUE TITLE
How to configure .inferconfig file

### ISSUE THREAD

**Issue by unkosun** [facebook/infer#638]
`.inferconfig `
```
{
  "infer-blacklist-path-regex":[
    "Pods/(?!ddyc)[\\S|\\s]*/?$"
    ]
}
```
I want filter out  directories which  not use `ddyc` for prefix，but it do not work. 
Has same example ?

**Comment by jvillard** [comment]
The regexp is interpreted as an [OCaml regexp](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Str.html).

How about this one?
```JSON
{
  "infer-blacklist-path-regex":[
    "Pods/ddyc.*/"
  ]
}
```

**Comment by unkosun** [comment]
@jvillard  sorry, I wrote wrong， I want filter which not （use 'ddyc' for prefix or use 'component' for suffix）。
