### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by MrThiago** [facebook/infer#64]
Hello I am trying to run infer and getting this error 

infer -- ./gradlew build
Traceback (most recent call last):
  File "/Users/user/1-Programming/4-Infer/infer-osx-v0.1.0/infer/infer/bin/infer", line 142, in <module>
    main()
  File "/Users/user/1-Programming/4-Infer/infer-osx-v0.1.0/infer/infer/bin/infer", line 119, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/Users/user/1-Programming/4-Infer/infer-osx-v0.1.0/infer/infer/bin/../lib/capture/gradle.py", line 41, in capture
    cmds = self.get_inferJ_commands(util.get_build_output(self.build_cmd))
  File "/Users/user/1-Programming/4-Infer/infer-osx-v0.1.0/infer/infer/bin/../lib/capture/util.py", line 24, in get_build_output
    proc = subprocess.Popen(build_cmd, stdout=subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

I have installed 
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
javac 1.8.0_31

python --version
Python 2.7.6

P.S. I am able to run Infer infer -- ./gradlew build in ther sample directory which comes with it.

**Comment by akotulski** [comment]
chmod a+x gradlew should do it.
https://github.com/facebook/infer/issues/61

**Comment by MrThiago** [comment]
Ok, I done that. Now i get this:

env: bash\r: No such file or directory

**Comment by MrThiago** [comment]
thanks for your reply akotulski 

I try it, now i get this:

env: bash\r: No such file or directory

**Comment by martinoluca** [comment]
Hello @MrThiago,
Could you please try running `./gradlew` only?

**Comment by MrThiago** [comment]
same thing.

./gradlew build
env: bash\r: No such file or directory

I will try to restore my project...

**Comment by MrThiago** [comment]
ok, I just restored my project - now i get = gradlew: Permission denied



./gradlew build
-bash: ./gradlew: Permission denied

**Comment by martinoluca** [comment]
The problem is related with permission on your gradlew script.
Have you tried giving it permission like @akotulski suggested?

**Comment by MrThiago** [comment]
yes, 

chmod +x gradlew
./gradlew build
env: bash\r: No such file or directory


and 
chmod a+x gradlew
env: bash\r: No such file or directory

**Comment by irpap** [comment]
Is this the gradle example from the infer release, or a different project? First try to see if you can build it with "./gradlew build". If it doesn't build infer won't be able to analyze it.

**Comment by MrThiago** [comment]
does this looks right ?


ls -l
total 96
-rw-r--r--@ 1 thiago  staff    929 Jun 15 14:44 Rokki.iml
drwx------  9 thiago  staff    306 Jun 15 14:44 app
-rw-r--r--@ 1 thiago  staff    627 Jun 15 14:44 build.gradle
drwx------  3 thiago  staff    102 Jun 15 14:44 gradle
-rw-r--r--@ 1 thiago  staff    872 Jun 15 14:44 gradle.properties
-rwxr-xr-x@ 1 thiago  staff   5244 Jun 15 14:44 gradlew
-rw-r--r--@ 1 thiago  staff   2404 Jun 15 14:44 gradlew.bat
-rw-r--r--@ 1 thiago  staff  14430 Jun 15 14:44 import-summary.txt
drwx------  5 thiago  staff    170 Jun 15 14:44 library
drwx------  7 thiago  staff    238 Jun 15 14:44 library_AndroidAsync
-rw-r--r--@ 1 thiago  staff    492 Jun 15 14:44 local.properties
-rw-r--r--@ 1 thiago  staff     63 Jun 15 14:44 settings.gradle

**Comment by MrThiago** [comment]
@irpap hi. 

If I run Infer on the example project that came with infer release it works fine.

Now I am trying to run on my own project.

**Comment by akotulski** [comment]
@MrThiago these failures have nothing to do with infer - they are related to gradle since it works on our example.
Quick googling gave me this, maybe it applies to you as well:
http://stackoverflow.com/questions/22301956/error-with-gradlew-usr-bin-env-bash-no-such-file-or-directory

**Comment by irpap** [comment]
@MrThiago how do you normally build your project?

**Comment by MrThiago** [comment]
@irpap  using Android Studio 

@akotulski Thank you for your info. I try it. also no hope. I will google more for help on my MAC.

**Comment by MrThiago** [comment]
@akotulski @irpap @martinoluca Thank you very much for all your help...
Apologies to discover the problem was with my gradlew and not Infer.
Thanks agian.

P.S, I fixed gradle, had to install in on my mac. My project was built on a Windows. I guess that was the problem. I can now run INFER ;-))

**Comment by jvillard** [comment]
Thanks for the update @MrThiago!
