### ISSUE TITLE
c++ emory leak false positive

### ISSUE THREAD

**Issue by trofi** [facebook/infer#641]
Found a false positie in `re2c codebase. Iccue looks similar to C bug in https://github.com/facebook/infer/issues/120 but given C++ is involved here I've decided to file a bug anyways.

Example source:

```c++
#include <algorithm>
#include <vector>

#include <stdlib.h> // malloc, free
#include <stddef.h> // size_t
#include <string.h> // memcpy

class Bag {
    std::vector<char*> ptrs_;
  public:
    Bag() : ptrs_ () {}
    // in reality add() is supposed to be a deduplicating
    // function that returns only unique data
    void * add (const char * real_payload, size_t n) {
        char * p = (char*)malloc (n);
        if (! p)
            exit (1);
        memcpy (p, real_payload, n);
        ptrs_.push_back (p);
        // in reality the code here is slightly smarter
        return ptrs_[0];
    }
    ~Bag() {
        for_each (ptrs_.begin(), ptrs_.end(), free);
    }
};

int main() {
    Bag b;
    b.add ("foo", 3);
    b.add ("bar", 3);
    return 0;
}
```

False positive output:

```
$ infer --  g++ a.cc -o a -Wall -Wextra -Weffc++ -O2 && valgrind ./a 
Capturing in make/cc mode...
Starting analysis...

legend:
  "F" analyzing a file
  "." analyzing a procedure

Found 1 (out of 1) source files to be analyzed in /tmp/z/infer-out
per-procedure parallelism jobs:8
F....

Found 1 issue

a.cc:22: error: MEMORY_LEAK
   memory dynamically allocated to `p` by call to `malloc()` at line 15, column 27 is not reachable after line 22, column 5
  20.           // in reality the code here is slightly smarter
  21.           return ptrs_[0];
  22. >     }
  23.       ~Bag() {
  24.           for_each (ptrs_.begin(), ptrs_.end(), free);

Summary of the reports

  MEMORY_LEAK: 1
==8944== Memcheck, a memory error detector
==8944== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==8944== Using Valgrind-3.12.0 and LibVEX; rerun with -h for copyright info
==8944== Command: ./a
==8944== 
==8944== 
==8944== HEAP SUMMARY:
==8944==     in use at exit: 0 bytes in 0 blocks
==8944==   total heap usage: 5 allocs, 5 frees, 72,734 bytes allocated
==8944== 
==8944== All heap blocks were freed -- no leaks are possible
==8944== 
==8944== For counts of detected and suppressed errors, rerun with: -v
==8944== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

Today's git version:
```
$ infer --version
Infer version v0.11.0-11967289
Copyright 2009 - present Facebook. All Rights Reserved.
```

**Comment by akotulski** [comment]
There are bunch of reasons why infer reports this:
1. it doesn't understand `std::for_each` and function pointers
2. deallocation happens in destructor and right now infer doesn't understand those semantics (instead it skips all resource leaks it finds in constructors)

Overall resource resource leaks detection in C++ is not great. With modern C++ it's not an issue that often because RAII prevents most of those leaks

**Comment by halfhiddencode** [comment]
you means it is for memory leak

**Comment by halfhiddencode** [comment]
> Found a false positie in `re2c codebase. Iccue looks similar to C bug in #120 but given C++ is involved here I've decided to file a bug anyways.
> 
> Example source:
> 
> ```c++
> #include <algorithm>
> #include <vector>
> 
> #include <stdlib.h> // malloc, free
> #include <stddef.h> // size_t
> #include <string.h> // memcpy
> 
> class Bag {
>     std::vector<char*> ptrs_;
>   public:
>     Bag() : ptrs_ () {}
>     // in reality add() is supposed to be a deduplicating
>     // function that returns only unique data
>     void * add (const char * real_payload, size_t n) {
>         char * p = (char*)malloc (n);
>         if (! p)
>             exit (1);
>         memcpy (p, real_payload, n);
>         ptrs_.push_back (p);
>         // in reality the code here is slightly smarter
>         return ptrs_[0];
>     }
>     ~Bag() {
>         for_each (ptrs_.begin(), ptrs_.end(), free);
>     }
> };
> 
> int main() {
>     Bag b;
>     b.add ("foo", 3);
>     b.add ("bar", 3);
>     return 0;
> }
> ```
> 
> False positive output:
> 
> ```
> $ infer --  g++ a.cc -o a -Wall -Wextra -Weffc++ -O2 && valgrind ./a 
> Capturing in make/cc mode...
> Starting analysis...
> 
> legend:
>   "F" analyzing a file
>   "." analyzing a procedure
> 
> Found 1 (out of 1) source files to be analyzed in /tmp/z/infer-out
> per-procedure parallelism jobs:8
> F....
> 
> Found 1 issue
> 
> a.cc:22: error: MEMORY_LEAK
>    memory dynamically allocated to `p` by call to `malloc()` at line 15, column 27 is not reachable after line 22, column 5
>   20.           // in reality the code here is slightly smarter
>   21.           return ptrs_[0];
>   22. >     }
>   23.       ~Bag() {
>   24.           for_each (ptrs_.begin(), ptrs_.end(), free);
> 
> Summary of the reports
> 
>   MEMORY_LEAK: 1
> ==8944== Memcheck, a memory error detector
> ==8944== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
> ==8944== Using Valgrind-3.12.0 and LibVEX; rerun with -h for copyright info
> ==8944== Command: ./a
> ==8944== 
> ==8944== 
> ==8944== HEAP SUMMARY:
> ==8944==     in use at exit: 0 bytes in 0 blocks
> ==8944==   total heap usage: 5 allocs, 5 frees, 72,734 bytes allocated
> ==8944== 
> ==8944== All heap blocks were freed -- no leaks are possible
> ==8944== 
> ==8944== For counts of detected and suppressed errors, rerun with: -v
> ==8944== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
> ```
> 
> Today's git version:
> 
> ```
> $ infer --version
> Infer version v0.11.0-11967289
> Copyright 2009 - present Facebook. All Rights Reserved.
> ```
you means it is for memory leak
