### ISSUE TITLE
Can't find list of lints on the fb infer website

### ISSUE THREAD

**Issue by michaeleiselsc** [facebook/infer#651]
Hi, I remember a while back I looked at the fb infer website and it was easy to see a list of lints for each platform. Now, I can't find a link. Can anyone help me out with this? Thanks.

**Comment by jeremydubreil** [comment]
@michaeleiselsc, do you mean this page: http://fbinfer.com/docs/infer-bug-types.html ?

**Comment by michaeleiselsc** [comment]
@jeremydubreil yes, thanks! is there some easy way to get to this page from the home page that i'm missing?

**Comment by dulmarod** [comment]
Normally there is a navigation bar, but seems broken at the moment. I'm sure it will be fixed soon.

**Comment by mbouaziz** [comment]
I just tried and the navigation bar is back.
@michaeleiselsc please reopen the issue if it's not working in your browser

**Comment by michaeleiselsc** [comment]
i see it now, thanks!
