### ISSUE TITLE
Questions about Infer performance

### ISSUE THREAD

**Issue by shaobo-he** [facebook/infer#655]
Hi Infer developers,

Sorry for bothering you again. I am trying to apply Infer to openssh with different configurations. My observation is that the number of procedures with failure (TIMEOUT, SYMOPTIMEOUT, suggested by information dumped by InferPrint) does not decrease significantly (sometimes even increases) if I increase the number of iterations or symops/time per iteration. I was wondering if it is expected. I would like to have some suggestions from you that minimize the number of procedures timed out. It would also be great if you could share some information on what symop means.

Thanks for your time. And I am looking forward to your reply.

Best,
Shaobo

**Comment by jberdine** [comment]
A symop is a coarse-grained measure of a "symbolic operation" which is basically any of the significant manipulations of the symbolic state that infer maintains.  There are only a handful of hits for `grep -R SymOp.pay`.

The number of timeouts can increase as the timeout is increased as code coverage can also increase, and so more procedures have the opportunity to time out.  That said, there are some exponential algorithms in infer, and some possibilities for genuine non-termination.  So it is very hard to predict what the result of increasing the timeout will/should be.

**Comment by Guoanshisb** [comment]
Thanks a lot for your reply. I also noticed that the number of bugs reported can decrease as the timeout increases. May I assume that the reduced number of bugs are false positives?

**Comment by jberdine** [comment]
That is plausible, but I would hesitate to make a strong assumption.  Since the time-outs are at the granularity of individual procedures, the code coverage can change in complicated ways with differing time out values.  In particular, a timeout in a procedure does not necessarily prevent exploration of code following the call, but does keep procedures called by the timed out procedure from being explored.

**Comment by jvillard** [comment]
Feel free to reopen with more questions!
