### ISSUE TITLE
--skip-analysis-in-path is not work

### ISSUE THREAD

**Issue by sencho** [facebook/infer#660]
my command line
```
infer --fail-on-issue -a infer --changed-files-index ./index.txt  --skip-analysis-in-path ./Pods -- analyze
```
The Pods file still exists after the analysis，Pods is a dictionary.

**Comment by sencho** [comment]
it worked ,please close the issue.
```
--skip-analysis-in-path "Pods/."
```

**Comment by coooliang** [comment]
> I have the some issue, use --skip-analysis-in-path "Pods/." don't skip analysis the Pods path

.inferconfig
```
{
  "report-blacklist-path-regex": [
    "Pods"
  ]
}
```
