### ISSUE TITLE
how to use --<analyzer>-blacklist-files-containing ignore files

### ISSUE THREAD

**Issue by xxhank** [facebook/infer#662]
I use blow command to skip files in Pods, but it doesn't work. 
infer run --infer-blacklist-files-containing "Pods/" -- xcodebuild -workspace Demo.xcworkspace -scheme Demo -configuration Debug

**Comment by cristianoc** [comment]
That option searches for a string inside files. Did you mean to blacklist the path of files?
You might want to use --blacklist-path-regex

**Comment by xxhank** [comment]
It worked. 3x
infer run --reactive \
 --infer-blacklist-path-regex "Pods/.*"\
 --infer-blacklist-path-regex "lib/.*"\
 --infer-blacklist-path-regex "Tests/.*"\
 --infer-blacklist-path-regex ".*\.framework/.*"\
 -- $XCODEBUILD build

**Comment by cristianoc** [comment]
Great!
