### ISSUE TITLE
Infer scan android project failed: Target `default' not remade because of errors

### ISSUE THREAD

**Issue by FujiyaFish** [facebook/infer#665]
I can build my android project with command `./gradlew assembleDevelop` successfully, but when I run command `infer -- ./gradlew assembleDevelop` to scan the project, I got errors as below：

my infer version: v0.9.3
system: CentOS release 6.3 (Final)
CPU: Intel Xeon E312xx (Sandy Bridge) 8 cores

make64: Target `default' not remade because of errors.
Traceback (most recent call last):
  File "/usr/local/lib/python/infer.py", line 230, in <module>
    main()
  File "/usr/local/lib/python/infer.py", line 214, in main
    analysis.analyze_and_report()
  File "/usr/local/lib/python/inferlib/analyze.py", line 537, in analyze_and_report
    elif self.analyze() == os.EX_OK:
  File "/usr/local/lib/python/inferlib/analyze.py", line 428, in analyze
    self.args.analyzer
  File "/usr/local/lib/python/inferlib/analyze.py", line 240, in run_command
    raise e
subprocess.CalledProcessError: Command '[u'make', u'-k', u'-j', '8', u'-s']' returned non-zero exit status 2
Failed to execute: /usr/local/lib/python/infer.py -j 8 --out /home/searchbox/jenkins/CI/workspace/searchbox_android_infer/infer-out --project_root /home/searchbox/jenkins/CI/workspace/searchbox_android_infer -- ./gradlew assembleDevelop

can anyone help me？

**Comment by jvillard** [comment]
Does this still happen with the latest version of infer?

**Comment by jvillard** [comment]
Closing optimistically since there have been improvements to the gradle integration since this issue was created. Please reopen if this still happens with the current infer version (0.15.0).
