### ISSUE TITLE
Explicit commands do not work for Gradle projects

### ISSUE THREAD

**Issue by nuald** [facebook/infer#668]
**Scope**: the current development version.
```
> infer --version
Infer version v0.12.0-572a383f
```
**STR:**
```
> cd examples/android_hello
> ./gradlew clean
> ../../infer/bin/infer run -- ./gradlew build
...
.../bin/infer: More than one subcommand specified: 'run', 'capture'.
...
ERROR: (Unix.Exit_or_signal (Exit_non_zero 1))
```
Please note that running `infer` without explicit command (either run or capture) works fine:
```
> ./gradlew clean
> ../../infer/bin/infer -- ./gradlew build
...
  NULL_DEREFERENCE: 2
     RESOURCE_LEAK: 1

```
**Technical Notes**

One command is always declared in `infer/lib/python/inferlib/jwlib.py` (`capture` argument for the `subprocess.check_call`), another command is in `INFER_ARGS` environment variable (looks like it's copied from the command line arguments).

**Comment by AnyMarvel** [comment]
the last version is also could not support gradle. 
Infer version v0.12.0-89ef935
i had try     infer -- gradle build
the same result for me.

**Comment by jvillard** [comment]
Thanks for the reports, I'm looking into it.
