### ISSUE TITLE
No progress is possible

### ISSUE THREAD

**Issue by fulingfan** [facebook/infer#67]
fulingfan@fulingfandeMacBook-Pro Documents$ tar xf infer-osx-v0.1.0.tar.xz 
infer-osx-v0.1.0/facebook-clang-plugin/clang/lib/ocaml/libLLVMX86Desc.a: Lzma library error:  No progress is possible
tar: Error exit delayed from previous errors.
fulingfan@fulingfandeMacBook-Pro Documents$

**Comment by jvillard** [comment]
Looks like the archive you downloaded is corrupted. Please try and download Infer again.

I've added the md5 sums of each archive to the [release page](https://github.com/facebook/infer/releases/latest/). You can test that they match on macos by checking that you get the following output with `md5`:

```shell
$ md5 infer-osx-v0.1.0.tar.xz
MD5 (infer-osx-v0.1.0.tar.xz) = f662de992a423de6c794e035784f33b3
```

**Comment by fulingfan** [comment]
yes, think you

**Comment by jeremydubreil** [comment]
@jvillard, should we add the checksum info here as well: http://fbinfer.com/docs/getting-started.html ?
