### ISSUE TITLE
Support a common report format like Checkstyle or Lint

### ISSUE THREAD

**Issue by tomasbjerre** [facebook/infer#674]
Would be nice if the report can be generated in a common format like [Checkstyle](https://github.com/tomasbjerre/violations-lib/tree/master/src/test/resources/checkstyle) or [Lint](https://github.com/tomasbjerre/violations-lib/tree/master/src/test/resources/lint). So that this tool can be used with other existing tools.

This would resolve https://github.com/tomasbjerre/violations-lib/issues/20 .

**Comment by jvillard** [comment]
Infer supports emitting reports in PMD's xml format, using the `--pmd-xml` option. Is that supported by your tool?

**Comment by tomasbjerre** [comment]
Ok great! Yes PMD is supported.
