### ISSUE TITLE
Bugs in multiple files

### ISSUE THREAD

**Issue by sofiareis** [facebook/infer#675]
Hi,

this is not an issue. I'm trying to understand how the interprocedural part works... When infer analyzes a file, it tries to analyze all the methods, even the ones in other files that are called in the file under analyzation? So, if inside of a function a method from another file is called, the tool checks the function from the 2nd file? Now, imagine that the function from the 2nd file is a method that allocates memory with malloc and returns the created pointer... If this pointer is not freed on the first file, infer will detect a memory leak? I added an example...
- file1.c
```
int method1() {
  int *ptr = method2();
  /* do stuff */
  /* If I don't free(ptr), infer gets a Memory Leak?*/
  return 1;
}
```
- file2.c
```
int *method2() {
  int *ptr = (int*) malloc(100 * sizeof(int));
  return ptr;
}

```

I also would like to know if infer only checks memory leaks for malloc or if also does it to calloc. Thank you! :-)

**Comment by jeremydubreil** [comment]
Yes, Infer should report the memory leak in your example. Does it work if you try on a small example?

Infer will also treat calloc and malloc in the same way: https://github.com/facebook/infer/blob/master/infer/models/c/src/libc_basic.c#L812

**Comment by sofiareis** [comment]
Hi,

I haven't tried with a small example. But I'm running a few samples of memory and resource leaks collected from several github repositories. And one of them is this one, 
```
         playlist = playlist_init(lpl_path, 99999);
         {
            for (j = 0; j < playlist->size; j++)
            {
               if (string_is_equal(playlist->entries[j].crc32, state->crc))
               {
                  printf("CRC Match %s\n", state->crc);
                  strlcpy(state->path, playlist->entries[j].path, sizeof(state->path));
                  state->found = true;
                  task_set_data(task, state);
                  task_set_progress(task, 100);
                  task_set_title(task, strdup("Compatible content found"));
                  task_set_finished(task, true);
                  string_list_free(state->lpl_list);
                  return;
               }
               task_set_progress(task, (int)(j/playlist->size*100.0));
            }
          }
```
where playlist_init is the initialization of the playlist with calloc in other file:

```
playlist_t *playlist_init(const char *path, size_t size)
{
   struct playlist_entry *entries = NULL;
   playlist_t           *playlist = (playlist_t*)calloc(1, sizeof(*playlist));
   if (!playlist)
      return NULL;

   entries = (struct playlist_entry*)calloc(size, sizeof(*entries));
   if (!entries)
   {
      free(playlist);
      return NULL;
   }

   playlist->entries   = entries;
   playlist->cap       = size;

   playlist_read_file(playlist, path);

   playlist->conf_path = strdup(path);
   return playlist;
}
```
There's a memory leak if you return in the first piece of code without freeing playlist, but infer doesn't detect it. It's a false negative right? I also think this is a messed up example and that infer could struggle in many ways... Thank you for helping! :)
