### ISSUE TITLE
Calling NOP function hides some warnings.

### ISSUE THREAD

**Issue by rgrig** [facebook/infer#678]
Here is an example (for https://github.com/facebook/infer/commit/987347ceca51a707054bc4ece38d312df856434a):

[Update 29jun: simpler code]

```java
// Command: infer -g -- javac Test.java
public class T {
  static int q;
  static void f() {
    if (q == 0) { q = 1; }
    else if (q == 1) { while (true); }
  }
  static void h() {
    // Important to have 2 branches, and one of them is (q==1).
    if (q == 1) {} else if (q == 2) {}
  }
  static void go() {
    q = 0;
    f();
    //h();  // warning disappears if this line is uncommented
    f();
  }
}
```

Note the -g flag.

Is this likely to be caused by a heuristic in `symExec.ml`, or is the issue probably coming from somewhere else?

**Comment by rgrig** [comment]
The issue is that the specs of `h()` are bad, which in turn is caused by the joining of postconditions.

Infer first joins preconditions to get something like `{ x |-q-> _x }` where `_x` is a logical variable. Two of the corresponding postconditions are `{ x |-q-> _x and _x=1 }` and `{ x |-q-> _x and _x=2 }`. Then it tries to join these (in `Dom.pathset_collapse` which in turn calls `Dom.eprop_partial_join`). First it joins the spatial parts, obtaining `{ x |-q-> _t and (_t=1 or _t=2) }` where `_t` is a fresh logical variable; then it joins the pure parts, obtaining `true`. So, the result is the triple `{ x |-q-> _x } ... {x |-q-> _t and (_t=1 or _t=2)}` with no connection between `_x` and `_t`.

A fix in this case might be to replace constants (`1` and `2`) by the logical variable they equal (`_x`) before doing the join. But, it's unclear what this will do in general.

For my use case, I'll try to just turn off joining, and see what happens.

**Comment by rgrig** [comment]
FWIW, this is the workaround I use: https://github.com/rgrig/infer/commit/fb20c02a611c139cd8738a678e1c058e73d1f4f8

It fixes this issue, and I didn't notice any significant performance degradation. I only tried on the source code of Tomcat 7. Before: 22m27s, NULL_DEREF 193, LEAK 75. After: 21m17s, NULL_DEREF 193, LEAK 69. (I didn't look at the 6 disappearing leaks.)

**Comment by jvillard** [comment]
Thanks for the detailed investigation @rgrig! I'll look into whether disabling the join for post-conditions works on more codebases. If it does then I'll ask you to make a PR with your change if that's ok.

**Comment by rgrig** [comment]
Sure. If slowdowns do occur, HY suggested that a simple fix might be to apply join every now-and-then.

**Comment by jeremydubreil** [comment]
@rgrig, is there something else to be done with this issue?

**Comment by rgrig** [comment]
it's up to you to decide if you want to issue a pull request request (@jvillard ?)
anyway is fine with me
