### ISSUE TITLE
Help viewing pre/postconditions per instruction

### ISSUE THREAD

**Issue by blzq** [facebook/infer#681]
Hi!

I'm trying to find a way to view the pre and postconditions per line of code in a program, instead of per function via `infer report`.

So far, this is my (possibly bogus) attempt at making a checker to do so:

```
open! IStd

module F = Format
module L = Logging

module Domain = AbstractDomain.FiniteSet(Var.Set)

module TransferFunctions (CFG : ProcCfg.S) = struct
  module CFG = CFG
  module Domain = Domain
  type extras = ProcData.no_extras

  let exec_instr astate proc_data node instr = 
  match astate with
  | _ -> astate
end

module Analyzer =
  AbstractInterpreter.Make (ProcCfg.OneInstrPerNode(ProcCfg.Normal)) (TransferFunctions)

let checker { Callbacks.get_proc_desc; get_procs_in_file; 
  idenv; tenv; summary; proc_desc; } = 
  let summ = Interproc.analyze_procedure { get_proc_desc; get_procs_in_file; 
  idenv; tenv; summary; proc_desc; } in 

  let proc_name = Procdesc.get_proc_name proc_desc in  
  print_string ("\nStart_proc: " ^ Typ.Procname.to_string(proc_name) ^ "\n");
  let print_instrs n = 
    print_string "Node "; 
    (Procdesc.Node.pp_id F.std_formatter (Procdesc.Node.get_id n));
    print_string "\n";
    Procdesc.Node.pp_instrs Pp.text None ~sub_instrs:true F.std_formatter n;
    print_string "\n"
  in
  Procdesc.iter_nodes_rev print_instrs proc_desc;

  let invmap = 
    Analyzer.exec_pdesc (ProcData.make_default proc_desc tenv) ~initial:Domain.empty
  in 
  let print_states n =
    let key = Procdesc.Node.get_id n in
    let state = Analyzer.extract_state (key, ProcCfg.Node_index) invmap in
    match state with 
    | Some s -> Domain.pp F.std_formatter s.pre; 
                Domain.pp F.std_formatter s.post; 
                print_string "\n";
    | None -> print_string "None"
  in
  Procdesc.iter_nodes_rev print_states proc_desc;

  print_string "\nEnd proc\n";
  summ
```
So far I'm able to see instructions being printed when using `infer run -a checkers` on a sample program, but what I thought would be pre and postconditions is printing as `{  }` (using `infer report` reports the function pre/posts correctly). Is it because the normal Infer analysis isn't being used when checkers are run? Is it possible to access the step-by-step analysis?

**Comment by jvillard** [comment]
Hi @blzq, you can view more information about pre/post at each program point in the html debug produced by infer, which works for the biabduction analysis (`-a infer`) as well as for the other checkers. You can generate it with `infer -g ...` (warning: do not use `-g` on large projects as it will generate tons of data and generally be quite slow) and looking at the infer-out/captured/*.html files. If you want to see the steps of the biabduction analyser (`-a infer`), they will be there too. Does that answer your question?

**Comment by blzq** [comment]
Yes it does, thanks very much!
I'm also trying to make use of how propositions are internally represented, but for now accessing propositions through the summaries may be sufficient.
