### ISSUE TITLE
Option for showing what is and isn't activated for that linting run

### ISSUE THREAD

**Issue by michaeleisel** [facebook/infer#685]
It seems like the only way to comprehensively go through all of the lints is to carefully look through `infer --help` and turn everything on. This approach is time consuming and easy to mess up, failing to turn on lints. Two ways that this can be dealt with:
- Make the docs comprehensive, e.g., by including --dump-duplicate-symbols
- Show, when running infer, which options are and aren't active

**Comment by dulmarod** [comment]
Which language are you using? For Objective-C everything available is turned on by default.

**Comment by jvillard** [comment]
`--print-active-checkers` will show you which checkers are active (e.g. "buffer overrun"), but not which linters (from AL) are active. We could make AL print a list of active checkers too.

> Make the docs comprehensive, e.g., by including --dump-duplicate-symbols

This option is mentioned in `infer --help` already. Were you expecting something else?

**Comment by michaeleisel** [comment]
No, that makes sense :)

**Comment by jvillard** [comment]
Fixed by 8e078c33d771385be5b8287aa2d289d29590aca1. Thanks again for the idea!
