### ISSUE TITLE
Warn user before deleting everything in --results-dir

### ISSUE THREAD

**Issue by michaeleisel** [facebook/infer#686]
I misread the docs for --results-dir, believing it to specify a parent that infer-out would be in, and was dismayed to find that all of my work in that directory had been deleted. It would be great if infer would either not delete anything it didn't have to or exit early if it found any files in the directory that it wasn't expecting.

**Comment by jvillard** [comment]
Thanks for flagging this. I think it should be easy to have infer check that a few things that are expected to always exist in infer-out are indeed there before nuking it, for instance [these three directories](https://github.com/facebook/infer/blob/e5556949d3149f19980a41b3d42146b462d3cf76/infer/src/backend/infer.ml#L44-L46).
