### ISSUE TITLE
I want to make some simple rules

### ISSUE THREAD

**Issue by AnyMarvel** [facebook/infer#689]
I want to make some simple rules. Such as not using a class. Can you tell me how to modify the source code? Or what help is the documentation?

**Comment by dulmarod** [comment]
Hi, which language are you interested in? For C, C++ and Objective-C we provide a simple language to write simple rules like what you are trying to do. Check out the documentation here: http://fbinfer.com/docs/linters.html.

**Comment by AnyMarvel** [comment]
I want to interested  in the language is java，Is there a document in this area?

**Comment by sblackshear** [comment]
For simple lint rules like not using a specific Java class, Infer is probably overkill. You might want to check out [error-prone](https://github.com/google/error-prone), which has lots of useful built-in rules.

**Comment by AnyMarvel** [comment]
Because of the particularity of the project. I would like to add rules in Infer to generate a bug.txt, rather than another use of tools. Java rules can be modified?

**Comment by sblackshear** [comment]
Sure, you can still write simple checkers with Infer. Take a look at [these](https://github.com/facebook/infer/blob/master/infer/src/checkers/NullabilitySuggest.ml) [two](https://github.com/facebook/infer/blob/master/infer/src/labs/ResourceLeaks.ml) checkers. The first one suggests that you add a `@Nullable` annotation to an expression that's compared/assigned to `null`, and the second one is a simple resource leak analysis. It should be easy to modify these checkers to do something even simpler. You also might want to take a look at the docs [here](http://fbinfer.com/docs/adding-checkers.html).

**Comment by AnyMarvel** [comment]
thank you. I'll study

**Comment by mbouaziz** [comment]
Let us know if you managed to create the analysis you wanted, thanks!
