### ISSUE TITLE
Quandary not reporting src-sink paths

### ISSUE THREAD

**Issue by yiji21** [facebook/infer#692]
Hi all,

I was trying to use Quandary to detect src-sink paths in my toy Android app (source code: [LeakyApp.zip](https://github.com/facebook/infer/files/1149512/LeakyApp.zip), including infer-out folder). The app only contains 1 activity, the MainActivity, and only has a few lines in OnCreate() to retrieve and log the device ID, as follows.

        final TelephonyManager tm = (TelephonyManager) getBaseContext().getSystemService(Context.TELEPHONY_SERVICE);
        String android_id = tm.getDeviceId();
        Log.wtf("Taint sink", android_id);

Then I run the following commands in the app folder.

**> ./gradlew assembleDebug**
```
Starting a Gradle Daemon (subsequent builds will be faster)
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to <...skipped...>/Library/Android/sdk/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAnimatedVectorDrawable2510Library
:app:prepareComAndroidSupportAppcompatV72510Library
:app:prepareComAndroidSupportConstraintConstraintLayout102Library
:app:prepareComAndroidSupportSupportCompat2510Library
:app:prepareComAndroidSupportSupportCoreUi2510Library
:app:prepareComAndroidSupportSupportCoreUtils2510Library
:app:prepareComAndroidSupportSupportFragment2510Library
:app:prepareComAndroidSupportSupportMediaCompat2510Library
:app:prepareComAndroidSupportSupportV42510Library
:app:prepareComAndroidSupportSupportVectorDrawable2510Library
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:app:javaPreCompileDebug
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:transformClassesWithDexForDebug UP-TO-DATE
:app:mergeDebugJniLibFolders UP-TO-DATE
:app:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:app:validateSigningDebug
:app:packageDebug UP-TO-DATE
:app:assembleDebug UP-TO-DATE

BUILD SUCCESSFUL

Total time: 10.518 secs
```

**> infer --quandary**
```
Found 13 source files to analyze in <...skipped...>/LeakyApp/infer-out
Starting analysis...

legend:
  "F" analyzing a file
  "." analyzing a procedure

FFFF......FFFF.....................FF..F.F......F..........

```
My environment is as follows.

**> gradle --version**
```
Gradle 3.5

Build time:   2017-04-10 13:37:25 UTC
Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_121 (Oracle Corporation 25.121-b13)
OS:           Mac OS X 10.12.3 x86_64
```

**> infer --version**
```
Infer version v0.12.0-f5d3870
Copyright 2009 - present Facebook. All Rights Reserved.
```

Would someone please tell me whether I am running it correctly? If yes, why the source-sink path is not detected?

Thanks,
Yiji

**Comment by sblackshear** [comment]
I checked and this is an issue with our Gradle integration. Our mechanism for filtering out bugs based on the path to their source file has a default value of "allow no paths", which seems wrong. I'm working on a fix, but you can do `./gradlew assembleDebug; infer --no-filter-paths -a checkers --quandary` as a workaround in the meantime.  

Note the `-a checkers` part, which is important. `infer` with no `-a` is an alias for `-a biabduction`, so `infer --quandary` confusingly does nothing. We should probably crash in this case.

**Comment by sblackshear** [comment]
Actually, the path filtering is working just fine (I accidentally had an old `.inferconfig` file in my testing directory). I think the reason it wasn't reporting for you was just the missing `-a`; `./gradlew assembleDebug; infer -a checkers --quandary` now shows

```
Found 1 issue

app/src/main/java/com/example/jordan/leakyapp/MainActivity.java:47: error: QUANDARY_TAINT_ERROR
  PrivateData(String TelephonyManager.getDeviceId() at [line 46]) -> Logging(int Log.wtf(String,String) at [line 47]).
  45.           final TelephonyManager tm = (TelephonyManager) getBaseContext().getSystemService(Context.TELEPHONY_SERVICE);
  46.           String android_id = tm.getDeviceId();
  47. >         Log.wtf("Taint sink", android_id);
  48.           /// Yiji's chunk ends
  49.   
```

for me.

**Comment by yiji21** [comment]
Sam,

Thank you so much for your prompt reply! Yes, I was suspecting that it was most likely the case that I wasn't running it correctly.

I will try Quandary on more apps now.

Thank you again for your help!

**Comment by sblackshear** [comment]
Great! I'll close this issue then; feel free to file new ones if you run into other problems.
