### ISSUE TITLE
Infer blocks clang's stdout

### ISSUE THREAD

**Issue by hmijail** [facebook/infer#696]
Infer v0.12.0. 

Some build systems (like Eclipse CDT's indexer or Waf) do something like `clang -dM -E -` to get a list of the compiler's implicit #defines.  The output goes to stdout.

But if one tries to do that with `infer capture -- clang -dM -E -`, the only output is 
```
Capturing in make/cc mode...
```

A maybe interesting detail is that around v0.8 infer did print clang's stdout when given that command line, AFAIR. In fact, I used that way of working to use infer with my build system (waf), as seen in #316 .

So, is this a regression? Is there any way to get clang's stdout?

(The reason I'm going back to using the CC environment variable is because my build system now hides waf under a layer of scripting, so using `infer run -- buildscript` only gets me a `ERROR: (Invalid_argument "Unsupported build command buildscript")`. So I don't know whether the waf support that got introduced in #316 is still working. I suspect not, given that waf inspects the compiler's output to the mentioned command line)

**Comment by jvillard** [comment]
For me `clang -dM -E -` on its own also blocks (waiting for stdin?). Is that the exact command you are using? Which version of clang is it? I tried with 3.8.1 and 4.0.0.

**Comment by hmijail** [comment]
Sorry, I should have specified that you have to close stdin (with ^D) for clang to continue. 

Clang on its own prints to stdout, but infer only prints its line.
