### ISSUE TITLE
No rule to make target 'include_header/header.o', needed by 'compile'.  Stop

### ISSUE THREAD

**Issue by YYYGH** [facebook/infer#701]
Capturing in make/cc mode...
make: *** No rule to make target 'include_header/header.o', needed by 'compile'.  Stop.
*** ERROR: capture command failed:
*** make
*** exited with code 2
when i carried out "infer run -- make" in /infer/infer/tests/codetoanalyze/cpp/errors directory ,i get this error

**Comment by jberdine** [comment]
It's not clear to me why `infer run -- make` is expected to work. This directory is part of the infer test suite and not intended to be build in other contexts. In particular, the command executed by `make test` is quite different from `infer run -- make`.
