### ISSUE TITLE
Crashlytics: dSYM Error

### ISSUE THREAD

**Issue by evgeniyd** [facebook/infer#73]
* a project uses [Crashlytics](https://www.crashlytics.com/)

* `xcodebuild ` runs OK with the following configuration:
`xcodebuild -workspace <workspace_name>.xcworkspace -scheme <scheme_name> -configuration Debug -arch i386 -sdk iphonesimulator `

* command `infer -- xcodebuild -workspace <workspace_name>.xcworkspace -scheme <scheme_name> -configuration Debug -arch i386 -sdk iphonesimulator` results in an error:
```
...

Crashlytics: dSYM Error

Unable to process <app_name>.app.dSYM at path <path_to_build>/<app_name>.app.dSYM
Make sure your project build settings are generating a dSYM file. DEBUG_INFORMATION_FORMAT should be set to dwarf-with-dsym for all configurations. This could also be a timing issue, make sure the Crashlytics run script build phase is the last build phase and no other scripts have moved the dSYM from the location Xcode generated it.

Command /bin/sh failed with exit code 1

....

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Run\ Script  <path_to_build>/<app_name>.build/Debug-iphonesimulator/<app_name>.build/Script-46B4741615E41D0E00F9C887.sh
(1 failure)
None

```

**WORKAROUND**
I come up with a workaround to [not to run Crashlytics for "Debug" configuration](http://support.crashlytics.com/knowledgebase/articles/118559-can-i-make-the-dsym-uploading-only-on-release-buil)

Note: Standard suggestions, like _turn on symbolication_, _use dsym and dwarf_ and _put Crashlytics script to be last build phase_ don't work.

**Comment by martinoluca** [comment]
Hello @evgeniyd,
Thanks for reporting the issue.
We've just made a new release of Infer, and it is available at https://github.com/facebook/infer/releases/latest

Let us know if the problem still persists, or close the issue if it is solved.

**Comment by evgeniyd** [comment]
I can confirm that with v0.1.1 it is resolved.
