### ISSUE TITLE
`Empty vector access` in c++ doesn't work

### ISSUE THREAD

**Issue by DDMing** [facebook/infer#748]
In [docs](http://fbinfer.com/docs/infer-bug-types.html#EMPTY_VECTOR_ACCESS), `infer` can detect `Empty vector access` for c++.

So I write a simple c++ program in `a.cpp` as below.

```c++
#include <vector>

int foo(){
  const std::vector<int> vec;
  return vec[0];
}

int main(){
  foo();
  return 0;
}
```
But when I run `infer -- g++ -o a a.cpp`. Output is **`No issues found`**.

I also tried other commands, 

 > infer --debug -- clang++ -o a a.cpp
    infer --debug -- clang++ -c a.cpp
    infer -- g++ -c a.cpp

but all get the same results.  **`No issues found`**

So, Is there any missing option for `infer`? or, any problems in compile commands? or, some linking problems in c++?

If necessary, developing env shows as below.
  > Infer version v0.12.1
     g++ 4.2.1
     Apple LLVM version 8.1.0 (clang-802.0.42)
     macOS Sierra version 10.12.6

**Comment by sblackshear** [comment]
Can you try `infer -- clang -x c++ -std=c++1y -c a.cpp`? That shows the bug for me.

I'm surprised Infer doesn't show compilation failures on the other commands; I couldn't get any of them to work locally.

**Comment by DDMing** [comment]
@sblackshear Thanks~

`infer -- clang -x c++ -std=c++1y -c a.cpp`  works fine. I find out that key point is the option `-std=c++1y`.

Without option `-std=c++1y`, the result is **`No issues found`**.  but there is no compilation failures for this command. 

Also, I tried other `-std` options. Only `-std=c++11` or `-std=c++1y` works.

I guess some bug types should use newer language standard.

**Comment by jvillard** [comment]
I've added a note in the documentation that this is only for C++11 and above: http://fbinfer.com/docs/infer-bug-types.html#EMPTY_VECTOR_ACCESS
