### ISSUE TITLE
Cannot install Infer in a Redhat-based machine: fail at step updating OCaml

### ISSUE THREAD

**Issue by tddsg** [facebook/infer#749]
Hi,

I was trying to install Infer using the script `build-infer.sh` but it failed at the first steps when updating OCaml. Below is the error message which is thrown during the installation. 

Could you advise me what happens and how to fix it? I ran the command `build-infer.sh` under a Linux environment (Redhat-based)

Thank you!

```
=-=- Updating package repositories =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default] synchronized from https://opam.ocaml.org

=-=- Synchronizing development packages -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[lock] https://github.com/rgrinberg/opam-lock already up-to-date
Exception:
Reqs_error
 (Process_error
   ("opam install -y ANSITerminal.0.7 atd.1.2.0 atdgen.1.10.0 bin_prot.113.33.00+4.03 biniou.1.0.12 camlp4.4.04+1 camlzip.1.07 camomile.0.8.5 conf-autoconf.0.1 conf-m4.1 conf-pkg-config.1.0 conf-which.1 core.113.33.02+4.03 core_kernel.113.33.02+4.03 cppo.1.4.1 ctypes.0.11.3 easy-format.1.2.0 extlib-compat.1.7.0 fieldslib.113.24.00 javalib.2.3.3 jbuilder.1.0+beta6 lambda-term.1.10.1 lwt.2.7.1 menhir.20170101 merlin-extend.0.3 ocaml-migrate-parsetree.0.7 ocamlbuild.0.11.0 ocamlfind.1.7.1 ounit.2.0.0 ppx_assert.113.33.00 ppx_bench.113.33.00+4.03 ppx_bin_prot.113.33.00+4.03 ppx_compare.113.33.00+4.03 ppx_core.113.33.01+4.03 ppx_custom_printf.113.33.00+4.03 ppx_deriving.4.1 ppx_driver.113.33.02+4.03 ppx_enumerate.113.33.00+4.03 ppx_expect.113.33.01+4.03 ppx_fail.113.33.00+4.03 ppx_fields_conv.113.33.00+4.03 ppx_here.113.33.00 ppx_inline_test.113.33.00+4.03 ppx_jane.113.33.00 ppx_let.113.33.00+4.03 ppx_optcomp.113.33.01+4.03 ppx_pipebang.113.33.00+4.03 ppx_sexp_conv.113.33.01+4.03 ppx_sexp_message.113.33.00+4.03 ppx_sexp_value.113.33.00+4.03 ppx_tools.5.0 ppx_tools_versioned.5.0alpha ppx_type_conv.113.33.02+4.03 ppx_typerep_conv.113.33.00+4.03 ppx_variants_conv.113.33.00+4.03 re.1.7.1 react.1.2.0 reason.1.13.4 reason-parser.1.13.4 result.1.2 sawja.1.5.2 sexplib.113.33.00+4.03 topkg.0.8.1 typerep.113.24.00 utop.1.19.3 variantslib.113.24.00 xmlm.1.2.0 yojson.1.3.3 zed.1.4 --color=never",
   Unix.WEXITED 3)).

```

**Comment by jvillard** [comment]
Which version of infer are you trying to build?

**Comment by tddsg** [comment]
I am using a modified version of Infer, which is forked from revision `eb477b771ed095b21e889be306269b73d4d29900` of the original Infer, back in April 27, 2017.

I just try the newest Infer and this issue doesn't occur.
But before, I also didn't any issue with my modified version of Infer from the revision `eb477b771ed095b21e889be306269b73d4d29900`

**Comment by jvillard** [comment]
@tddsg This might be due to a change in opam, which can sometime break external projects, as discussed eg on this PR: https://github.com/ocaml/opam-repository/pull/10047

Sometimes it can be worked around by using `./build-infer.sh --no-opam-lock` (or record the changes with `make opam.lock`, then `./build-infer.sh`) but sometimes that's not enough either and it's necessary to adjust the dependencies in the opam file manually and run `make opam.lock`.
