### ISSUE TITLE
JSON output, for automatical parsing

### ISSUE THREAD

**Issue by XVilka** [facebook/infer#75]
Or any other similar format, to be able automatically parse the output.

**Comment by dulmarod** [comment]
Hi,
we already offer json and csv format in the output folder. When you run the analysis, a folder called infer-out will be created. Inside you can find the files report.json and report.csv with the bugs.

**Comment by XVilka** [comment]
@dulmarod sorry, didn't noticed them at first place. Closing this bug then. Thank you for a good work!
