### ISSUE TITLE
Assertion failure in no-angelic mode

### ISSUE THREAD

**Issue by rgrig** [facebook/infer#754]
Since a03f765d8f11341c0f3e0e52c3308e22f52c6ad1, the command `infer --no-angelic-execution -g -- javac Repro.java` fails on the following file:

```
import java.util.Random;
class Repro {
  static Random random = new Random();
  static boolean maybe() { return random.nextBoolean(); }
  void bad() {
    if (maybe()) {}
  }
}
```

The error message is

> Assert_failure (/home/rg/research/code/infer/infer/src/backend/prop.ml:1594:6-6:): 1

I would guess a fix would be to revert this commit.

**Comment by jvillard** [comment]
I'm afraid infer no longer supports the "non-angelic" mode: 7b8c46a04e2f8b3223de36d126304370c589a7e2

What was your reason for using it?

**Comment by rgrig** [comment]
I want to see warnings when `f()` is called, but no there is no suitable spec. This includes the case with no spec. But, IIRC, the angelic mode handled no-spec as a special case, and ate PRECONDITION_NOT_MET.

It might be possible to re-organize stuff and not rely on PRECONDITION_NOT_MET at all, in which case the angelic mode should be sufficient.

**Comment by jvillard** [comment]
If you're tinkering with infer's source code it should be possible to play with symExec.ml to get the desired result, eg starting here: https://github.com/facebook/infer/blob/cb8e75be859af0d16a80b2adfe1f0d429c93d903/infer/src/backend/symExec.ml#L405-L406
