### ISSUE TITLE
infer xcode build output error - *** Infer needs a working compilation command to run

### ISSUE THREAD

**Issue by ferasOS** [facebook/infer#755]
I am running infer on an Xcode workspace with the following command using infer version v0.12.1 =

`infer run --reactive -- xcodebuild -workspace WORKSPACE_NAME.xcworkspace -scheme SCEMENAME`

the code builds successfully. but afterwards I get:

 ```
  Build Succeeded
   Starting translating 56 files 

*** ERROR: Failed to execute compilation command. Output:
clang: error: cannot specify -o when generating multiple output files
*** Infer needs a working compilation command to run.
```

...MANY OF THESE...then...

```

...
*** ERROR: Failed to execute compilation command. Output:
clang: error: cannot specify -o when generating multiple output files
*** Infer needs a working compilation command to run.
..

Nothing to compile. Try running `xcodebuild -workspace OneScream.xcworkspace -scheme OneScream clean` first.

There was nothing to analyze.
```

**Comment by tianshunjian** [comment]
I am running infer v0.12.1 on Xcode 9 with iOS 11 using the following command:
"infer -- xcodebuild -workspace myProject.xcworkspace -scheme myProject-Video -configuration Debug -sdk iphonesimulator",
and got the same results. Can anyone know how to deal with it?

**Comment by ferasOS** [comment]
Infer doesn't work with swift atm unfortunately.

**Comment by tianshunjian** [comment]
@ferasOS 
But my project is created by Objective-C

**Comment by StefanoBiasu** [comment]
Same log appeared to me, with iOS 10.2, xcode 9, workspace with Objective-C code. Many of those:

```
...
*** ERROR: Failed to execute compilation command. Output:
clang: error: cannot specify -o when generating multiple output files
*** Infer needs a working compilation command to run.
..
```

then 

```
Nothing to compile. Try running `xcodebuild -workspace <workspace> -scheme <scheme> -destination platform=iOS Simulator,name=iPad Air clean` first.
There was nothing to analyze.
```

**Comment by StefanoBiasu** [comment]
same as [Issue 759](https://github.com/facebook/infer/issues/759)
