### ISSUE TITLE
Failed to load any Java source code

### ISSUE THREAD

**Issue by nidalmer** [facebook/infer#757]
I'm new to Infer and I was to run it on the Hello.java file from the examples but for some reason I keep getting

> Failed to load any Java source code

I have:

- Infer v0.12.1

- Java 9

-  Installed using `brew install infer`

-  Using the command `infer run -- javac Hello.java`

**Comment by jvillard** [comment]
Java9 support is added by 185e7f713111f370c2b1b8a71b2236e1a3b89e21 currently only available from master. Let me know if this still doesn't work for you using infer's master or switching to Java8.
