### ISSUE TITLE
General Questions about Infer and the builtin Infer functions.

### ISSUE THREAD

**Issue by Breee** [facebook/infer#763]
Greetings, 
I found the following file:

https://github.com/facebook/infer/blob/fe21442d478dfcd07d9b6d5b67c1061899151225/infer/models/c/src/infer_builtins.c

**Questions:** 

- How are these functions used correctly if I want to run Infer?

- How does one use Infer, to analyze a .c file without building a binary?

- Does Infer also provide a builtin function which enables reachability analysis of certain points in the program? (Similar to something like  __VERIFIER_error(), which can be used in various SVcomp tools like e.g Ultimate, CBMC..)
i.e. something like  __infer_IsReachable(), which gives me a result similar to:
Program point  X is reachable / not reachable. 

Example: 

```C
int main(){
  float x = 1.0f;
  if (x == 1.0f){
    some_error();
  }
}
```
Can Infer tell me that some_error() is reachable?

- What kind of analysis is Infer using, are there issues with floats/doubles?
e.g. Trace Abstraction, Abstract interpretation, ...

- Are NAN, INFINITY included in __infer_nondet_float() / __infer_nondet_double() ?

Im on Ubuntu 16.04.03  64 bit.

Thanks in advance  and kind regards,
Bree

**Comment by sblackshear** [comment]
> How are these functions used correctly if I want to run Infer?

These functions are included as part of the models, you shouldn't need to do anything with them if you are just running Infer.

> How does one use Infer, to analyze a .c file without building a binary?

Take a look at [these](http://fbinfer.com/docs/analyzing-apps-or-projects.html) [two](https://github.com/facebook/infer/blob/master/examples/README.md) guides.

> Does Infer also provide a builtin function which enables reachability analysis of certain points in the program? (Similar to something like __VERIFIER_error(), which can be used in various SVcomp tools like e.g Ultimate, CBMC..)
i.e. something like __infer_IsReachable(), which gives me a result similar to:
Program point X is reachable / not reachable.

We don't have this. The best way to approximate this is in the way that you describe: put a definite error inside of a branch (e.g., `x = nullptr; y = *x`) and see if it gets reported.

> What kind of analysis is Infer using, are there issues with floats/doubles?
e.g. Trace Abstraction, Abstract interpretation, ...

Infer does not use very sophisticated numerical domains; it has a fairly simple [solver](https://github.com/facebook/infer/blob/master/infer/src/backend/prover.ml) that can symbolically evaluate some kinds of expressions. The focus is on the heap and on integer/boolean expressions; I don't think it can do anything with float/double constants. In general, I think Infer is not a good fit for doing sophisticated reasoning about floats/doubles (as least as things are today). But we would be very happy for someone to put some work into this.

The buffer overrun analysis probably has the fanciest numerical domains of all the analyzers: symbolic intervals with some extensions. @mbouaziz can say more about this.

> Are NAN, INFINITY included in __infer_nondet_float() / __infer_nondet_double() ?

Conceptually yes, but I don't think there's any special logic inside the backend for dealing with these values.

**Comment by Breee** [comment]
Alright, thanks alot for the information.

So I can conclude that infer is not capable (at least yet) to handle floats/doubles?
 
Would you suggest running infer on c files which only use float/double, or is it pointless to do so?

**Comment by mbouaziz** [comment]
Sorry for the late reply :(

> So I can conclude that infer is not capable (at least yet) to handle floats/doubles?

You're right. Infer won't tell anything about the floats in your programs.

> Would you suggest running infer on c files which only use float/double, or is it pointless to do so?

Yes, you can still find other kinds of bugs!
