### ISSUE TITLE
what are files infer-orig with infer run -- mvn compile

### ISSUE THREAD

**Issue by danimelo59** [facebook/infer#764]
Hello,

I've installer infer in a docker. I launch the docker in bash :
I dont' understand the following error : 
root@beee8d333e04:/data# infer run -- mvn compile -DskipTests 
Capturing in maven mode...
Error while running epilogue restoring Maven's pom.xml to its original state:
(Unix.Unix_error "No such file or directory" rename
 "((src /data/videoRecorder/videoRecorder-rpm/pom.xml.infer-orig) (dst /data/videoRecorder/videoRecorder-rpm/pom.xml))").
Powering through...
Error while running epilogue restoring Maven's pom.xml to its original state:
(Unix.Unix_error "No such file or directory" rename
 "((src /data/recordScheduler/recordScheduler-rpm/pom.xml.infer-orig) (dst /data/recordScheduler/recordScheduler-rpm/pom.xml))").
Powering through...
Error while running epilogue restoring Maven's pom.xml to its original state:
(Unix.Unix_error "No such file or directory" rename
 "((src /data/haloEnabler/haloEnabler-rpm/pom.xml.infer-orig) (dst /data/haloEnabler/haloEnabler-rpm/pom.xml))").
Powering through...
ERROR: (Sys_error "/data/ofms-core/pom.xml: No such file or directory")

If I try to execute the same command in subfolders of my project, the command is sometimes OK

Thanks

**Comment by jvillard** [comment]
I think this should have been solved by 817f83972cacba03bd9613979fd55154a6b95e20, but the Dockerfile doesn't contain the fix since it's based on 0.15.0. There's a more up-to-date [Dockerfile](https://github.com/facebook/infer/tree/master/docker/master-java) for tracking master that you can try.

**Comment by linux1304** [comment]
Hi @jvillard ,
I think I got same errors, but I don't run it in Docker. It's okay when I compile without Infer tool.

Usage Error: *** Maven command failed:
*** mvn -X clean package -P infer-capture
*** exited with code 1


Error while running epilogue "restoring Maven's pom.xml to its original state":
(Unix.Unix_error "No such file or directory" rename
 "((src /home/ubuntu/abcxyz/pom.xml.infer-orig) (dst /home/ubuntu/abcxyz/pom.xml))").
Powering through...

**Comment by jvillard** [comment]
@linux1304 can you paste the command you used to run infer, the version of infer, and the full output of maven? I'm wondering if there's another error somewhere; the epilogue error may be a red herring.

**Comment by linux1304** [comment]
@jvillard I am using Infer version v0.15.0. I paste the command and full output of maven in this link: https://pastebin.com/ijD1cMpZ

**Comment by jvillard** [comment]
@linux1304 Thanks for the paste. The "Error while running epilogue ..." message is not the issue there. (Also it is fixed in the current master)

There are a number of java compilation errors in the maven output, which I think are what makes the infer command fail. For example:

```
[ERROR] /home/ubuntu/test/src/main/java/com/knorex/web/security/jwt/JWTFilter.java:[25,7] error: cannot access Filter
```

and

```
[ERROR] /home/ubuntu/test/src/main/java/com/knorex/web/web/rest/errors/ExceptionTranslator.java:[69,60] error: incompatible types: Class<HttpRequestMethodNotSupportedException> cannot be converted to Class<? extends Throwable>
```

Not sure why there are errors with infer but not without though. There may be more information about the exact `javac` command that fails in infer-out/logs, maybe that will help debug. Or, could you give a newer version of infer a try?

**Comment by linux1304** [comment]
@jvillard Thanks you for your reply. This is infer-out/logs content: https://gist.github.com/linux1304/3a86bb9690fd8026043b8cce08801022

**Comment by linux1304** [comment]
@jvillard. I updated miss dependencies and it's working now. Thanks you so much for your support.
