### ISSUE TITLE
infer 0.12.1 fails to build on Debian 9

### ISSUE THREAD

**Issue by abpostelnicu** [facebook/infer#765]
Hello,

I'm encountering an issue when building infer on debian 9.
Steps to reproduce are:
 ./build-infer.sh 
initializing opam... 
OPAM has already been initialized.
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

1. To configure OPAM in the current shell session, you need to run:

      eval `opam config env`

2. To correctly configure OPAM for subsequent use, add the following
   line to your profile file (for instance ~/.profile):

      . /var/lib/jenkins/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

3. To avoid issues related to non-system installations of `ocamlfind`
   add the following lines to ~/.ocamlinit (create it if necessary):

      let () =
        try Topdirs.dir_directory (Sys.getenv "OCAML_TOPLEVEL_PATH")
        with Not_found -> ()
      ;;

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

 To setup the new switch in the current shell, you need to run:
eval `opam config env`

installing infer dependencies; this can take up to 30 minutes... 
[NOTE] Package ANSITerminal is already installed (current version is 0.7).
[NOTE] Package atd is already installed (current version is 1.2.0).
[NOTE] Package atdgen is already installed (current version is 1.10.0).
[NOTE] Package bin_prot is already installed (current version is
       113.33.00+4.03).
[NOTE] Package biniou is already installed (current version is 1.0.12).
[NOTE] Package camlp4 is already installed (current version is 4.04+1).
[NOTE] Package camlzip is already installed (current version is 1.07).
[NOTE] Package camomile is already installed (current version is 0.8.5).
[NOTE] Package cmdliner is already installed (current version is 1.0.0).
[NOTE] Package conf-autoconf is already installed (current version is 0.1).
[NOTE] Package conf-m4 is already installed (current version is 1).
[NOTE] Package conf-pkg-config is already installed (current version is 1.0).
[NOTE] Package conf-which is already installed (current version is 1).
[NOTE] Package core is already installed (current version is 113.33.02+4.03).
[NOTE] Package core_kernel is already installed (current version is
       113.33.02+4.03).
[NOTE] Package cppo is already installed (current version is 1.6.0).
[NOTE] Package cppo_ocamlbuild is already installed (current version is 1.6.0).
[NOTE] Package ctypes is already installed (current version is 0.11.3).
[NOTE] Package easy-format is already installed (current version is 1.2.0).
[NOTE] Package extlib-compat is already installed (current version is 1.7.0).
[NOTE] Package fieldslib is already installed (current version is 113.24.00).
[NOTE] Package jbuilder is already installed (current version is 1.0+beta10).
[NOTE] Package lambda-term is already installed (current version is 1.10.1).
[NOTE] Package lwt is already installed (current version is 2.7.1).
[NOTE] Package menhir is already installed (current version is 20170101).
[NOTE] Package merlin-extend is already installed (current version is 0.3).
[NOTE] Package ocaml-migrate-parsetree is already installed (current version is
       0.7).
[NOTE] Package ocamlbuild is already installed (current version is 0.11.0).
[NOTE] Package ocamlfind is already installed (current version is 1.7.1).
[NOTE] Package ounit is already installed (current version is 2.0.0).
[NOTE] Package ppx_assert is already installed (current version is 113.33.00).
[NOTE] Package ppx_bench is already installed (current version is
       113.33.00+4.03).
[NOTE] Package ppx_bin_prot is already installed (current version is
       113.33.00+4.03).
[NOTE] Package ppx_compare is already installed (current version is
       113.33.00+4.03).
[NOTE] Package ppx_core is already installed (current version is
       113.33.01+4.03).
[NOTE] Package ppx_custom_printf is already installed (current version is
       113.33.00+4.03).
[NOTE] Package ppx_deriving is already installed (current version is 4.1).
[NOTE] Package ppx_driver is already installed (current version is
       113.33.02+4.03).
[NOTE] Package ppx_enumerate is already installed (current version is
       113.33.00+4.03).
[NOTE] Package ppx_expect is already installed (current version is
       113.33.01+4.03).
[NOTE] Package ppx_fail is already installed (current version is
       113.33.00+4.03).
[NOTE] Package ppx_fields_conv is already installed (current version is
       113.33.00+4.03).
[NOTE] Package ppx_here is already installed (current version is 113.33.00).
[NOTE] Package ppx_inline_test is already installed (current version is
       113.33.00+4.03).
[NOTE] Package ppx_jane is already installed (current version is 113.33.00).
[NOTE] Package ppx_let is already installed (current version is
       113.33.00+4.03).
[NOTE] Package ppx_optcomp is already installed (current version is
       113.33.01+4.03).
[NOTE] Package ppx_pipebang is already installed (current version is
       113.33.00+4.03).
[NOTE] Package ppx_sexp_conv is already installed (current version is
       113.33.01+4.03).
[NOTE] Package ppx_sexp_message is already installed (current version is
       113.33.00+4.03).
[NOTE] Package ppx_sexp_value is already installed (current version is
       113.33.00+4.03).
[NOTE] Package ppx_tools is already installed (current version is 5.0).
[NOTE] Package ppx_tools_versioned is already installed (current version is
       5.0alpha).
[NOTE] Package ppx_type_conv is already installed (current version is
       113.33.02+4.03).
[NOTE] Package ppx_typerep_conv is already installed (current version is
       113.33.00+4.03).
[NOTE] Package ppx_variants_conv is already installed (current version is
       113.33.00+4.03).
[NOTE] Package re is already installed (current version is 1.7.1).
[NOTE] Package react is already installed (current version is 1.2.0).
[NOTE] Package reason is already installed (current version is 1.13.4).
[NOTE] Package reason-parser is already installed (current version is 1.13.4).
[NOTE] Package result is already installed (current version is 1.2).
[NOTE] Package sexplib is already installed (current version is
       113.33.00+4.03).
[NOTE] Package topkg is already installed (current version is 0.8.1).
[NOTE] Package typerep is already installed (current version is 113.24.00).
[NOTE] Package utop is already installed (current version is 1.19.3).
[NOTE] Package variantslib is already installed (current version is 113.24.00).
[NOTE] Package xmlm is already installed (current version is 1.2.0).
[NOTE] Package yojson is already installed (current version is 1.3.3).
[NOTE] Package zed is already installed (current version is 1.4).
[ERROR] The compilation of javalib failed at "./configure.sh".

=== ERROR while installing javalib.2.3.3 =====================================
 opam-version         1.2.2
 os                   linux
 command              ./configure.sh
 path                 /var/lib/jenkins/.opam/infer-4.04.0/build/javalib.2.3.3
 compiler             4.04.0
 exit-code            1
 env-file             /var/lib/jenkins/.opam/infer-4.04.0/build/javalib.2.3.3/javalib-8464-d2c37b.env
 stdout-file          /var/lib/jenkins/.opam/infer-4.04.0/build/javalib.2.3.3/javalib-8464-d2c37b.out
 stderr-file          /var/lib/jenkins/.opam/infer-4.04.0/build/javalib.2.3.3/javalib-8464-d2c37b.err
 stdout 
 * Debug flag set to yes.
 * Ocamlfind found at /var/lib/jenkins/.opam/infer-4.04.0/bin/ocamlfind.
 * System-wide installation, in /var/lib/jenkins/.opam/infer-4.04.0/lib.
 
 ! Package extlib old version found
 (/var/lib/jenkins/.opam/infer-4.04.0/lib/extlib) in version cf64877
 (< 1.5.1 needed), please install a more recent version and then re-run
 configure.sh ..
 
  stderr
 ./configure.sh: line 133: [: cf64877: integer expression expected
 ./configure.sh: line 134: [: cf64877: integer expression expected

Exception:
Reqs_error
 (Process_error
   ("opam install -y ANSITerminal.0.7 atd.1.2.0 atdgen.1.10.0 bin_prot.113.33.00+4.03 biniou.1.0.12 camlp4.4.04+1 camlzip.1.07 camomile.0.8.5 cmdliner.1.0.0 conf-autoconf.0.1 conf-m4.1 conf-pkg-config.1.0 conf-which.1 core.113.33.02+4.03 core_kernel.113.33.02+4.03 cppo.1.6.0 cppo_ocamlbuild.1.6.0 ctypes.0.11.3 easy-format.1.2.0 extlib-compat.1.7.0 fieldslib.113.24.00 javalib.2.3.3 jbuilder.1.0+beta10 lambda-term.1.10.1 lwt.2.7.1 menhir.20170101 merlin-extend.0.3 ocaml-migrate-parsetree.0.7 ocamlbuild.0.11.0 ocamlfind.1.7.1 ounit.2.0.0 ppx_assert.113.33.00 ppx_bench.113.33.00+4.03 ppx_bin_prot.113.33.00+4.03 ppx_compare.113.33.00+4.03 ppx_core.113.33.01+4.03 ppx_custom_printf.113.33.00+4.03 ppx_deriving.4.1 ppx_driver.113.33.02+4.03 ppx_enumerate.113.33.00+4.03 ppx_expect.113.33.01+4.03 ppx_fail.113.33.00+4.03 ppx_fields_conv.113.33.00+4.03 ppx_here.113.33.00 ppx_inline_test.113.33.00+4.03 ppx_jane.113.33.00 ppx_let.113.33.00+4.03 ppx_optcomp.113.33.01+4.03 ppx_pipebang.113.33.00+4.03 ppx_sexp_conv.113.33.01+4.03 ppx_sexp_message.113.33.00+4.03 ppx_sexp_value.113.33.00+4.03 ppx_tools.5.0 ppx_tools_versioned.5.0alpha ppx_type_conv.113.33.02+4.03 ppx_typerep_conv.113.33.00+4.03 ppx_variants_conv.113.33.00+4.03 re.1.7.1 react.1.2.0 reason.1.13.4 reason-parser.1.13.4 result.1.2 sawja.1.5.2 sexplib.113.33.00+4.03 topkg.0.8.1 typerep.113.24.00 utop.1.19.3 variantslib.113.24.00 xmlm.1.2.0 yojson.1.3.3 zed.1.4 --color=never",
   Unix.WEXITED 4)).

*** Failed to install opam dependencies
*** Updating opam then retrying

=-=- Updating package repositories =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default] synchronized from https://opam.ocaml.org

=-=- Synchronizing development packages -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[lock] https://github.com/rgrinberg/opam-lock already up-to-date

Updates available for infer-4.04.0, apply them with 'opam upgrade':
===== 20 to install | 9 to recompile | 51 to upgrade =====
[NOTE] Package ANSITerminal is already installed (current version is 0.7).
[NOTE] Package atd is already installed (current version is 1.2.0).
[NOTE] Package atdgen is already installed (current version is 1.10.0).
[NOTE] Package bin_prot is already installed (current version is
       113.33.00+4.03).
[NOTE] Package biniou is already installed (current version is 1.0.12).
[NOTE] Package camlp4 is already installed (current version is 4.04+1).
[NOTE] Package camlzip is already installed (current version is 1.07).
[NOTE] Package camomile is already installed (current version is 0.8.5).
[NOTE] Package cmdliner is already installed (current version is 1.0.0).
[NOTE] Package conf-autoconf is already installed (current version is 0.1).
[NOTE] Package conf-m4 is already installed (current version is 1).
[NOTE] Package conf-pkg-config is already installed (current version is 1.0).
[NOTE] Package conf-which is already installed (current version is 1).
[NOTE] Package core is already installed (current version is 113.33.02+4.03).
[NOTE] Package core_kernel is already installed (current version is
       113.33.02+4.03).
[NOTE] Package cppo is already installed (current version is 1.6.0).
[NOTE] Package cppo_ocamlbuild is already installed (current version is 1.6.0).
[NOTE] Package ctypes is already installed (current version is 0.11.3).
[NOTE] Package easy-format is already installed (current version is 1.2.0).
[NOTE] Package extlib-compat is already installed (current version is 1.7.0).
[NOTE] Package fieldslib is already installed (current version is 113.24.00).
[NOTE] Package jbuilder is already installed (current version is 1.0+beta10).
[NOTE] Package lambda-term is already installed (current version is 1.10.1).
[NOTE] Package lwt is already installed (current version is 2.7.1).
[NOTE] Package menhir is already installed (current version is 20170101).
[NOTE] Package merlin-extend is already installed (current version is 0.3).
[NOTE] Package ocaml-migrate-parsetree is already installed (current version is
       0.7).
[NOTE] Package ocamlbuild is already installed (current version is 0.11.0).
[NOTE] Package ocamlfind is already installed (current version is 1.7.1).
[NOTE] Package ounit is already installed (current version is 2.0.0).
[NOTE] Package ppx_assert is already installed (current version is 113.33.00).
[NOTE] Package ppx_bench is already installed (current version is
       113.33.00+4.03).
[NOTE] Package ppx_bin_prot is already installed (current version is
       113.33.00+4.03).
[NOTE] Package ppx_compare is already installed (current version is
       113.33.00+4.03).
[NOTE] Package ppx_core is already installed (current version is
       113.33.01+4.03).
[NOTE] Package ppx_custom_printf is already installed (current version is
       113.33.00+4.03).
[NOTE] Package ppx_deriving is already installed (current version is 4.1).
[NOTE] Package ppx_driver is already installed (current version is
       113.33.02+4.03).
[NOTE] Package ppx_enumerate is already installed (current version is
       113.33.00+4.03).
[NOTE] Package ppx_expect is already installed (current version is
       113.33.01+4.03).
[NOTE] Package ppx_fail is already installed (current version is
       113.33.00+4.03).
[NOTE] Package ppx_fields_conv is already installed (current version is
       113.33.00+4.03).
[NOTE] Package ppx_here is already installed (current version is 113.33.00).
[NOTE] Package ppx_inline_test is already installed (current version is
       113.33.00+4.03).
[NOTE] Package ppx_jane is already installed (current version is 113.33.00).
[NOTE] Package ppx_let is already installed (current version is
       113.33.00+4.03).
[NOTE] Package ppx_optcomp is already installed (current version is
       113.33.01+4.03).
[NOTE] Package ppx_pipebang is already installed (current version is
       113.33.00+4.03).
[NOTE] Package ppx_sexp_conv is already installed (current version is
       113.33.01+4.03).
[NOTE] Package ppx_sexp_message is already installed (current version is
       113.33.00+4.03).
[NOTE] Package ppx_sexp_value is already installed (current version is
       113.33.00+4.03).
[NOTE] Package ppx_tools is already installed (current version is 5.0).
[NOTE] Package ppx_tools_versioned is already installed (current version is
       5.0alpha).
[NOTE] Package ppx_type_conv is already installed (current version is
       113.33.02+4.03).
[NOTE] Package ppx_typerep_conv is already installed (current version is
       113.33.00+4.03).
[NOTE] Package ppx_variants_conv is already installed (current version is
       113.33.00+4.03).
[NOTE] Package re is already installed (current version is 1.7.1).
[NOTE] Package react is already installed (current version is 1.2.0).
[NOTE] Package reason is already installed (current version is 1.13.4).
[NOTE] Package reason-parser is already installed (current version is 1.13.4).
[NOTE] Package result is already installed (current version is 1.2).
[NOTE] Package sexplib is already installed (current version is
       113.33.00+4.03).
[NOTE] Package topkg is already installed (current version is 0.8.1).
[NOTE] Package typerep is already installed (current version is 113.24.00).
[NOTE] Package utop is already installed (current version is 1.19.3).
[NOTE] Package variantslib is already installed (current version is 113.24.00).
[NOTE] Package xmlm is already installed (current version is 1.2.0).
[NOTE] Package yojson is already installed (current version is 1.3.3).
[NOTE] Package zed is already installed (current version is 1.4).
[ERROR] The compilation of javalib failed at "./configure.sh".

=== ERROR while installing javalib.2.3.3 =====================================
 opam-version         1.2.2
 os                   linux
 command              ./configure.sh
 path                 /var/lib/jenkins/.opam/infer-4.04.0/build/javalib.2.3.3
 compiler             4.04.0
 exit-code            1
 env-file             /var/lib/jenkins/.opam/infer-4.04.0/build/javalib.2.3.3/javalib-8688-d2c37b.env
 stdout-file          /var/lib/jenkins/.opam/infer-4.04.0/build/javalib.2.3.3/javalib-8688-d2c37b.out
 stderr-file          /var/lib/jenkins/.opam/infer-4.04.0/build/javalib.2.3.3/javalib-8688-d2c37b.err
 stdout 
 * Debug flag set to yes.
 * Ocamlfind found at /var/lib/jenkins/.opam/infer-4.04.0/bin/ocamlfind.
 * System-wide installation, in /var/lib/jenkins/.opam/infer-4.04.0/lib.
 
 ! Package extlib old version found
 (/var/lib/jenkins/.opam/infer-4.04.0/lib/extlib) in version cf64877
 (< 1.5.1 needed), please install a more recent version and then re-run
 configure.sh ..
 
 stderr 
 ./configure.sh: line 133: [: cf64877: integer expression expected
 ./configure.sh: line 134: [: cf64877: integer expression expected

Exception:
Reqs_error
 (Process_error
   ("opam install -y ANSITerminal.0.7 atd.1.2.0 atdgen.1.10.0 bin_prot.113.33.00+4.03 biniou.1.0.12 camlp4.4.04+1 camlzip.1.07 camomile.0.8.5 cmdliner.1.0.0 conf-autoconf.0.1 conf-m4.1 conf-pkg-config.1.0 conf-which.1 core.113.33.02+4.03 core_kernel.113.33.02+4.03 cppo.1.6.0 cppo_ocamlbuild.1.6.0 ctypes.0.11.3 easy-format.1.2.0 extlib-compat.1.7.0 fieldslib.113.24.00 javalib.2.3.3 jbuilder.1.0+beta10 lambda-term.1.10.1 lwt.2.7.1 menhir.20170101 merlin-extend.0.3 ocaml-migrate-parsetree.0.7 ocamlbuild.0.11.0 ocamlfind.1.7.1 ounit.2.0.0 ppx_assert.113.33.00 ppx_bench.113.33.00+4.03 ppx_bin_prot.113.33.00+4.03 ppx_compare.113.33.00+4.03 ppx_core.113.33.01+4.03 ppx_custom_printf.113.33.00+4.03 ppx_deriving.4.1 ppx_driver.113.33.02+4.03 ppx_enumerate.113.33.00+4.03 ppx_expect.113.33.01+4.03 ppx_fail.113.33.00+4.03 ppx_fields_conv.113.33.00+4.03 ppx_here.113.33.00 ppx_inline_test.113.33.00+4.03 ppx_jane.113.33.00 ppx_let.113.33.00+4.03 ppx_optcomp.113.33.01+4.03 ppx_pipebang.113.33.00+4.03 ppx_sexp_conv.113.33.01+4.03 ppx_sexp_message.113.33.00+4.03 ppx_sexp_value.113.33.00+4.03 ppx_tools.5.0 ppx_tools_versioned.5.0alpha ppx_type_conv.113.33.02+4.03 ppx_typerep_conv.113.33.00+4.03 ppx_variants_conv.113.33.00+4.03 re.1.7.1 react.1.2.0 reason.1.13.4 reason-parser.1.13.4 result.1.2 sawja.1.5.2 sexplib.113.33.00+4.03 topkg.0.8.1 typerep.113.24.00 utop.1.19.3 variantslib.113.24.00 xmlm.1.2.0 yojson.1.3.3 zed.1.4 --color=never",
   Unix.WEXITED 4)).

Looking other the error message It seems that javalib.2.3.3 doesn't get installed and the problem seems to be that it doesn't like the version:
`   if [ "$ver1front" != "$1" ] || [ "$ver2front" != "$2" ]; then
       [ "$ver1front" -gt "$ver2front" ] && return 11
       [ "$ver1front" -lt "$ver2front" ] && return 9`

I've tried to update extlib and install a newer version but with no luck.

**Comment by jvillard** [comment]
You may be missing some dependencies; does [this sequence of commands](https://github.com/facebook/infer/issues/715#issuecomment-341712882) (probably to be adapted to Debian 9 package names) work for you?

**Comment by abpostelnicu** [comment]
thanks for the reply but unfortunately the problem still persist, is very any debug method to post here mode output?

**Comment by jvillard** [comment]
Our newest [Dockerfile](https://github.com/facebook/infer/blob/f1e01bdfc7c854cda9a92f6534a5ae35f5b7bc57/docker/Dockerfile) uses Debian 9 and infer 0.13.1 successfully. Can you please try again with the [newest version of infer](https://github.com/facebook/infer/releases/tag/v0.13.1)?

**Comment by sylvestre** [comment]
Yeah, I don't experience this issue anymore with 0.13.1
