### ISSUE TITLE
infer my ios workspace run "infer -- xcodebuild ..." error,but run "xcodebuild" build success

### ISSUE THREAD

**Issue by jimmyleaf** [facebook/infer#77]
error message:
infer   -- xcodebuild clean build -workspace xxx.workspace -scheme xxx -configuration Debug -sdk iphoneos  

xxx.cpp fatal error: 'iostream' file not found
#include <iostream>

Is infer ios will igonre .cpp .cc .mm file?

**Comment by martinoluca** [comment]
This issue has already been reported in https://github.com/facebook/infer/issues/69
Thanks for notifying it!

**Comment by martinoluca** [comment]
This issue has been addressed, please consider using the latest release available in:
https://github.com/facebook/infer/releases/latest
