### ISSUE TITLE
how about "TODO: print error message"? 

### ISSUE THREAD

**Issue by gangji001** [facebook/infer#78]
Hi,
run infer in android project (gradle or ant) get the following message.

jigangdeiMac:adblockui jigang$ infer -- ant debug
TODO: print error message
TODO: print error message
TODO: print error message
TODO: print error message
TODO: print error message
TODO: print error message
There was nothing to analyze, exiting

Can you tell me the cause of this result?

**Comment by sblackshear** [comment]
This has been fixed in the 0.1.1 release of Infer as well as in the source code. Please re-open the issue if you see this in the new release.
