### ISSUE TITLE
Reachability of program locations - Is this behaviour intended?

### ISSUE THREAD

**Issue by Breee** [facebook/infer#782]
Given the follwing c program:

```c
void __VERIFIER_error() {
  // malloc for 10 ints
  int *a = malloc(sizeof(int) * 10); //memory never freed.
 }

int main(){
    float x = 1.0f;
    float y = 0.0f;
    if(x < y){
        __VERIFIER_error();
    }
    return 0;
}
```
Infer will report that there is an error, however the error should not be reachable.
How do I enable, that infer only reports errors which are actually reachable?

I execute infer as follows:
infer --compute-analytics --bufferoverrun --biabduction -- gcc -O0 -g -Wall -c filename.c

**Comment by sblackshear** [comment]
Infer has a solver that can symbolically evaluate some kinds of expressions, but I don't think it tries to reason about floats at all. Floating point semantics are tricky. I'm guessing the memory leak report in your example will disappear if you make `x` and `y` `int`'s instead of floats.

**Comment by Breee** [comment]
I see, so what does infer assume/do in the case of floats or doubles?
Does it just assume that `x,y` are ANY value?

**Comment by sblackshear** [comment]
Effectively yes, but I would characterize it as: "it assumes the expression `x < y` can evaluate to either `true` or `false` when its solver can't statically determine what the outcome will be".

**Comment by peterogithub** [comment]
Breee, static analysis of floats is a "known hard problem". And it is even more difficult when you need to deal with large programs (as Infer does), and we choose to concentrate on other (hard!) problems. It would be great, though, if an open source analyzer gave accurate results on floats for real-world code.

If you are interested in this topic, 
   http://www.lix.polytechnique.fr/~putot/Publications/vmcai11.pdf
is  a good place to get started.

**Comment by jvillard** [comment]
Funnily enough infer is not at all confused by the floats here. The issue is that infer analyses each procedure independently. If it finds an issue in a procedure, it reports it there.

In particular, Infer does not attempt to first find out if the procedure can be called from `main()` or other entry points.

For instance, this version of the program where the issue is in the dead branch of `main()` makes infer happy, since it detects that the branch in `main()` is dead code:

```C
int * __VERIFIER_error() {
  // malloc for 10 ints
  int *a = malloc(sizeof(int) * 10); //memory never freed.
  return a;
}

int main(){
    float x = 1.0f;
    float y = 0.0f;
    if(x < y){
        __VERIFIER_error();
    }
    return 0;
}
```

**Comment by Breee** [comment]
Alright, your example works correctly for me too

Well, then I got more complicated code for you (I can also just attach it if it is too much).
Yet again we test if the function __VERIFIER_error() is reachable.
Now I tested your suggestion, and infer finds two MEMORY LEAK errors, but should just find one: 
The call was `infer -- gcc -c test.c`

```c
#include <stdlib.h>

/*
* defined in newlib/libm/common/fdlibm.h
* A union which permits us to convert between a double and two 32 bit ints.
*/
typedef union {
  double value;
  struct {
    __uint32_t lsw;
    __uint32_t msw;
  } parts;
} ieee_double_shape_type;

/*
* Preprocessed version of __fpclassifyd.
* file where the function is implemented: newlib/libm/common/s_fpclassify.c
*/
int __fpclassify_double(double x) {
  __uint32_t msw, lsw;
  do {
    ieee_double_shape_type ew_u;
    ew_u.value = (x);
    (msw) = ew_u.parts.msw;
    (lsw) = ew_u.parts.lsw;
  } while (0);

  if ((msw == 0x00000000 && lsw == 0x00000000) ||
      (msw == 0x80000000 && lsw == 0x00000000))
    return 2;
  else if ((msw >= 0x00100000 && msw <= 0x7fefffff) ||
           (msw >= 0x80100000 && msw <= 0xffefffff))
    return 4;
  else if ((msw >= 0x00000000 && msw <= 0x000fffff) ||
           (msw >= 0x80000000 && msw <= 0x800fffff))

    return 3;
  else if ((msw == 0x7ff00000 && lsw == 0x00000000) ||
           (msw == 0xfff00000 && lsw == 0x00000000))
    return 1;
  else
    return 0;
}

/*
* Preprocessed version of signbit.
* file where the function is implemented: newlib/libm/common/s_signbit.c
*/
int __signbit_double(double x) {
  __uint32_t msw;

  do {
    ieee_double_shape_type gh_u;
    gh_u.value = (x);
    (msw) = gh_u.parts.msw;
  } while (0);

  return (msw & 0x80000000) != 0;
}

/*
* Preprocessed function of fmax.
* file where the function is implemented: newlib/libm/common/s_fmax.c
*/
double fmax_double(double x, double y) {

  if (__fpclassify_double(x) == 0)
    return y;
  if (__fpclassify_double(y) == 0)
    return x;

  return x > y ? x : y;
}

int * __VERIFIER_error() {
  // malloc for 10 ints
  int *a = malloc(sizeof(int) * 10); //memory never freed.
  return a;
}

int main() {

  /*
   * REQ-BL-1252:
   * The fmax and fmaxf procedures shall return +0 if one argument is -0
   * and the other +0.
   *
   * BUG: The function fmax will return the wrong result if:
   * x = 0.0 and y = -0.0
   * CBMC, Ultimate Automizer and Frama-c come to the same conclusion.
   * It follows that REQ-BL-1252 is not satisfied.
   */

  // CASE 1: x = -0.0, y = 0.0;

  double x1 = -0.0;
  double y1 = 0.0;
  double res1 = fmax_double(x1, y1);

  // is res1 == 0.0?
  if (!(res1 == 0.0 && __signbit_double(res1) == 0)) {
    __VERIFIER_error(); // Error is not reachable.
  }

  // CASE 2: x = 0.0, y = -0.0;
  double x2 = 0.0;
  double y2 = -0.0;
  double res2 = fmax_double(x2, y2);

  // is res2 == 0.0?
  if (!(res2 == 0.0 && __signbit_double(res2) == 0)) {
    __VERIFIER_error();  // Error is reachable
  }

  return 0;
}
```

**Comment by jvillard** [comment]
In answer to your question:

> How do I enable, that infer only reports errors which are actually reachable?

This is not something infer can do easily at the moment, as infer reports on a per-procedure basis. The idea is that, if a function has a problem in itself, then it's an issue.

If the goal is to flag program points in other functions, maybe a macro would work? This way the code to report on will always be right where you want it to be and infer will report at the right place:

```C
#define __VERIFIER_ERROR() do {\
    int *error = 0; *error = 0;\
} while (0);

int main(){
    float x = 1.0f;
    float y = 0.0f;
    if(x > y){
        __VERIFIER_ERROR();
    }
    return 0;
}
```

This yields:
```
$ infer -- clang -c issue782.c
...
Found 1 issue

issue782.c:9: error: NULL_DEREFERENCE
  pointer `error` last assigned on line 9 could be null and is dereferenced at line 9, column 9.
  7.       float y = 0.0f;
  8.       if(x > y){
  9. >         __VERIFIER_ERROR();
  10.       }
  11.       return 0;
```

**Comment by jberdine** [comment]
In addition to @jvillard's reply, one thing to keep in mind is that infer is *not* attempting to determine which code is reachable and under what conditions. It does some amount of this as a by-product of analyzing individual procedures, considering their callees, but reachability analysis in the style of classic model checkers is not a goal.

**Comment by jvillard** [comment]
In your second example, infer abstracts too much of the numerical information to realise that `!(res1 == 0.0 && __signbit_double(res1) == 0)` cannot be true, so we're back to the point @sblackshear and @peterogithub were making about infer lacking in precision for the analysis of floating point arithmetic.

**Comment by Breee** [comment]
Alright guys, 
I thank you for the explanations, this is exactly what I tried to find out :) 
Because we wondered if infer can be used for requirement analyzes as an additional tool to CBMC, Ultimate, Frama-c.

Do you have any plans to implement a reachability analysis, or is that nothing you aim for?
Or if I may ask, what are your aims for further versions of infer?

**Comment by jvillard** [comment]
I think that the closest thing we are actively working on at the moment is [inferbo](https://research.fb.com/inferbo-infer-based-buffer-overrun-analyzer/). There have also been some experiments to leverage inferbo to do dead code detection. Inferbo currently targets integers though, and there is no current effort to make it (or other analyses) understand floating-point arithmetic.

Let me know if you have any more concrete questions, or if we can close this issue.

**Comment by Breee** [comment]
No we can close the issue, thanks alot!
