### ISSUE TITLE
Running from Source Error

### ISSUE THREAD

**Issue by AlyaElGamal** [facebook/infer#786]
I am trying to run Facebook Infer from source on a Linux system and I keep getting an error that looks like the following:

*Makefile.config:17: Makefile.autoconf: No such file or directory
make: *** No rule to make target 'Makefile.autoconf' . Stop.*

It seems like there is a missing piece of the makefile

**Comment by jvillard** [comment]
I think you want to follow [these instructions](https://github.com/facebook/infer/blob/master/INSTALL.md#install-infer-from-source): either run `./build-infer.sh`, or manually: `./autogen.sh && ./configure && make`.

Makefile.autoconf is generated by `./configure` from [Makefile.autoconf.in](https://github.com/facebook/infer/blob/149deb97ed5f518796f216fe46e49cb196ac56b0/Makefile.autoconf.in), and `./configure` is generated by [`./autogen.sh`](https://github.com/facebook/infer/blob/149deb97ed5f518796f216fe46e49cb196ac56b0/autogen.sh) from [configure.ac](https://github.com/facebook/infer/blob/149deb97ed5f518796f216fe46e49cb196ac56b0/configure.ac).

**Comment by qzlh521** [comment]
me too

terminal show:
...
preparing build... 
checking for .release... yes
checking for .facebook... no
checking whether to use the compilers in /Users/**/Desktop/infer-osx-v0.13.0/facebook-clang-plugins/clang/install/bin... yes
checking for shasum... shasum
checking for cmake... cmake
checking for python2.7... python2.7
checking for xcode-select... xcode-select
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/Users/**/Desktop/infer-osx-v0.13.0':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

**Comment by KCKH** [comment]
how to solve this? i got the same error too?

**Comment by jvillard** [comment]
Sounds like #1026. A solution was posted there: https://github.com/facebook/infer/issues/1026#issuecomment-460299520

```
xcode-select --install
# check that /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk exists
ls /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
export SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
```

I'm closing this issue which was about a missing `./autogen.sh` step. Please open a new issue if the comments on #1026 don't solve your problem.
