### ISSUE TITLE
C Compiler cannot create executables - Docker installation issue

### ISSUE THREAD

**Issue by TaylorBruening** [facebook/infer#790]
**The following is the output from the terminal before it fails:**
-> installed lock.1.2
Done.
[WARNING] Running as root is not recommended
preparing build... 
checking for .release... yes
checking for .facebook... no
checking whether to use the compilers in /infer/facebook-clang-plugins/clang/install/bin... yes
checking for shasum... shasum
checking for cmake... yes
checking for python2.7... python2.7
checking for xcode-select... no
checking whether the C compiler works... no
configure: error: in `/infer':
configure: error: C compiler cannot create executables
See `config.log' for more details
The command '/bin/sh -c OCAML_VERSION=4.04.2;     opam init --compiler=$OCAML_VERSION -j $(getconf _NPROCESSORS_ONLN || echo 1) --yes &&     cd /infer &&     ./build-infer.sh --opam-switch $OCAML_VERSION &&     rm -rf /root/.opam' returned a non-zero code: 77

This is using docker, on a 32-bit linux os, the installation is started using the command: sudo sh run.sh
 I have installed opam and cmake using sudo apt-get install.

**Comment by jvillard** [comment]
The release is for 64 bit systems only. To use infer on 32 bit systems you will need to [compile from source](https://github.com/facebook/infer/blob/master/INSTALL.md#install-infer-from-source).

**Comment by jvillard** [comment]
Feel free to re-open if you have any more questions.
