### ISSUE TITLE
Crash on Gradle projects that have nothing to build

### ISSUE THREAD

**Issue by aaronjwood** [facebook/infer#793]
If I've recently built my Android project and go to run `infer run -- ./gradlew build` it'll fail with:
```
...
Nothing to compile. Try running `./gradlew clean` first.

Error backtrace:
Raised at file "integration/Driver.ml", line 297, characters 16-78
Called from file "integration/Driver.ml", line 176, characters 2-16
Called from file "backend/infer.ml", line 23, characters 2-36
Called from file "backend/infer.ml", line 106, characters 6-52
Uncaught error: ("InferModules__Driver.Infer_error(\"exited with code 66\")")

Run the command again with `--keep-going` to try and ignore this error.
```

Doing a `./gradlew clean` and running the same command fixes the issue. It seems like Infer is always assuming that it can capture build output...?

**Comment by jvillard** [comment]
This should be categorised as a user error but it looks like an infer error.

> It seems like Infer is always assuming that it can capture build output...?

This is intended behaviour: if there is nothing to capture then nothing will be analysed, so infer crashes as this is unlikely to be the expected outcome.

**Comment by aaronjwood** [comment]
I see. If the intended behavior is for it to crash then I guess you can close this issue out.
