### ISSUE TITLE
inferconfig set relative or absolute path not work

### ISSUE THREAD

**Issue by f40507777** [facebook/infer#803]
Hi all:

My `InferTest.xcworkspace` include two project, `InferTest.xcodeproj` and `PatchProject.xcodeproj`.

I try to skip analysis `PatchProject` in different folder, the folder hierarchy like this:

```
other
├── InferTest
│   ├── InferTest
│   ├── InferTest.xcodeproj
│   ├── InferTest.xcworkspace
│   ├── Podfile
│   ├── Podfile.lock
│   ├── Pods
│   ├── build
│   ├── index.txt
│   ├── infer-out
│   └── .inferconfig
└── PatchProject
    ├── PatchProject
    └── tttt

```
And my `.inferconfig` like this (both used relation path and absolute path not working): 

```
{
    "skip-analysis-in-path": [
         "Pods",
         "../PatchProject",
         "/User/xxxxx/other/PatchProject"
    ]
}
```

And run `infer` command in path `other/InferTest` with args:

```
infer —keep-going --no-xcpretty -- xcodebuild -workspace InferTest.xcworkspace -scheme InferTest -configuration Debug -sdk iphonesimulator
```

Only Pods folder be skipped.
How can I fixed it?

**Comment by jeremydubreil** [comment]
The option `skip-analysis-in-path` is used to specify a list of regular expressions to match files but it is not a list of filesystem path. Therefore, `/User/xxxxx/other/PatchProject` will only match paths of the for `<project root>/User/xxxxx/other/PatchProject*`.

I agree that the name of the option is confusing. At the same time, the name of the option should made consistent with the whitelist, blacklist regexp filtering which currently only cover the path filtering for reporting purposes only.

**Comment by f40507777** [comment]
@jeremydubreil Thank you very much for this, Very useful!

**Comment by coooliang** [comment]
> 
What do I do if I want to ignore everything in the pods folder？
like this ? `"Pods/*"`
