### ISSUE TITLE
Include facebook-clang-plugins version with releases

### ISSUE THREAD

**Issue by japendergrass** [facebook/infer#809]
It would be very helpful if the release notes for each version could specify the commit hash of `facebook-clang-plugins` repository the release is expected to build against.

It is difficult to build infer from source because it is unclear exactly what version of the `facebook-clang-plugins` repo was used in the release tarballs, and the api seems to change with some frequency.

My current solution is "the HEAD facebook-clang-plugins on the date the release was posted" but this could easily be wrong (e.g., if the clang plugins posted a breaking change shortly after infer release).

**Comment by jvillard** [comment]
You can find this from GitHub by going to the version corresponding to the release (clicking on the hash in the column on the left-hand side to the name of the release). This brings you to the latest commit of the release, eg https://github.com/facebook/infer/commit/ddda04c92b03dc86a0c32feaf8544f23874de4b3

From there, there's a button "Browse files" you can click, bringing you to https://github.com/facebook/infer/tree/ddda04c92b03dc86a0c32feaf8544f23874de4b3

There you can see the version of the plugin:
[facebook-clang-plugins @ 6fe0516](https://github.com/facebook/facebook-clang-plugins/tree/6fe0516240c68e8a8aa123996ba54c6f9247f64a)

You can also clone the repo, checkout the release tag (`git checkout v0.13.0`) and run `./build-infer.sh`.

**Comment by japendergrass** [comment]
Thanks, I did eventually figure out how to get the info by cloning the repo.

It would still be convenient to include that information in the Release notes.

**Comment by jvillard** [comment]
The facebook-clang-plugins commit hash is now mentioned directly in the release notes: https://github.com/facebook/infer/releases/tag/v0.15.0
