### ISSUE TITLE
Uncaught error: ("InferModules__Driver.Infer_error(\"exited with code 65\")")

### ISSUE THREAD

**Issue by danyating** [facebook/infer#810]
when I try `infer -- xcodebuild clean build -scheme appName -workspace appName.xcworkspace -configuration Debug -sdk iphoneos`, I get error like "Nothing to compile. Try running xcodebuild clean build scheme appName -workspace appName.xcworkspace -configuration Debug -sdk iphoneos clean first."

Then I try `infer --keep-going --no-xcpretty -- xcodebuild clean build -scheme appName -workspace appName.xcworkspace -configuration Debug -sdk iphoneos`,The error above is gone, but I get a new error 

> like 
**BUILD FAILED**
Error backtrace:
Raised at file "integration/Driver.ml", line 297, characters 16-78
Called from file "integration/Driver.ml", line 176, characters 2-16
Called from file "backend/infer.ml", line 23, characters 2-36
Called from file "backend/infer.ml", line 106, characters 6-52
Uncaught error: ("InferModules__Driver.Infer_error(\"exited with code 65\")")

However, the build command ` xcodebuild clean build -scheme appName -workspace appName.xcworkspace -configuration Debug -sdk iphoneos` can run sucessfully.

Is there something I can do to solve this problem?

**Comment by dulmarod** [comment]
Try running  xcodebuild clean -scheme appName -workspace appName.xcworkspace -configuration Debug -sdk iphoneos first, 

then 

infer --keep-going --no-xcpretty -- xcodebuild build -scheme appName -workspace appName.xcworkspace -configuration Debug -sdk iphoneos

**Comment by runningcode** [comment]
I'm getting a very similar error when running `infer run -- ./gradlew assembleDebug`

```
Error backtrace:
Raised at file "integration/Driver.ml", line 297, characters 16-78
Called from file "integration/Driver.ml", line 176, characters 2-16
Called from file "backend/infer.ml", line 23, characters 2-36
Called from file "backend/infer.ml", line 106, characters 6-52
Uncaught error: ("InferModules__Driver.Infer_error(\"exited with code 1\")")
```

**Comment by WishQi** [comment]
I got the same problem, and the @dulmarod methods did not work for me.
First run:
`xcodebuild clean -workspace Aweme.xcworkspace -configuration AwemeInhouseDebug -scheme Aweme`
Then:
`infer --keep-going --no-xcpretty -- xcodebuild -workspace Name.xcworkspace -configuration Debug -scheme Name`
And I got the following errors:

> `** BUILD FAILED **
> The following build commands failed:
> 	Ld /Users/limaoqi/Library/Developer/Xcode/DerivedData/Aweme-bkezrnqnlfrskocmuntegwvejtzf/Build/Intermediates.noindex/Aweme.build/AwemeInhouseDebug-iphoneos/AwemeVideoNotification.build/Objects-normal/arm64/AwemeVideoNotification normal arm64
> (1 failure)
> 
> Error backtrace:
> Raised at file "integration/Driver.ml", line 297, characters 16-78
> Called from file "integration/Driver.ml", line 176, characters 2-16
> Called from file "backend/infer.ml", line 23, characters 2-36
> Called from file "backend/infer.ml", line 106, characters 6-52
> Uncaught error: ("InferModules__Driver.Infer_error(\"exited with code 65\")")`

How can I solve this problem?

**Comment by dulmarod** [comment]
With that information is difficult for me to figure out the problem. Could you send me the content of infer-out/logs? Also, you could try using the latest version of Infer, the problem may be fixed there, and if not, I will be able to understand the trace better (seems that the code has changed since the version you are using, so I cannot follow the trace).

**Comment by WishQi** [comment]
@dulmarod My logs is:
[logs.txt](https://github.com/facebook/infer/files/1478396/logs.txt)

**Comment by dulmarod** [comment]
@WishQi in your case, Infer is failing  when trying to process a linker command. A solution to this is to pass

 LD=/bin/true infer [options] -- <build command> -- 

See more info in http://fbinfer.com/support.html.

**Comment by WishQi** [comment]
@dulmarod The method did not work for me. And it seems to be more wrong
 And I got these:

> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 	Ld /Users/limaoqi/Library/Developer/Xcode/DerivedData/Aweme-bkezrnqnlfrskocmuntegwvejtzf/Build/Intermediates.noindex/Aweme.build/AwemeDebug-iphoneos/AwemeNotificationService.build/Objects-normal/arm64/AwemeNotificationService normal arm64
> 	Ld /Users/limaoqi/Library/Developer/Xcode/DerivedData/Aweme-bkezrnqnlfrskocmuntegwvejtzf/Build/Intermediates.noindex/Aweme.build/AwemeDebug-iphoneos/AwemeNotificationService.build/Objects-normal/armv7/AwemeNotificationService normal armv7
> (2 failures)
> 
> Error backtrace:
> Raised at file "integration/Driver.ml", line 297, characters 16-78
> Called from file "integration/Driver.ml", line 176, characters 2-16
> Called from file "backend/infer.ml", line 23, characters 2-36
> Called from file "backend/infer.ml", line 106, characters 6-52
> Uncaught error: ("InferModules__Driver.Infer_error(\"exited with code 65\")")
And the logs is:
[logs.txt](https://github.com/facebook/infer/files/1480916/logs.txt)

**Comment by dulmarod** [comment]
Maybe pass also CreateUniversalBinary =/usr/bin/true?

**Comment by danyating** [comment]
First I set this,
`export LD=/bin/true infer`
`export CreateUniversalBinary=/usr/bin/true`
Then
`xcodebuild clean  -scheme appName -workspace appName.xcworkspace -configuration Debug -sdk iphonesimulator`
Then 
`infer capture --keep-going --no-xcpretty -- xcodebuild build  -scheme appName -workspace appName.xcworkspace -configuration Debug -sdk iphonesimulator`
It run succeed!

> ** BUILD SUCCEEDED **
However, I have another problem that it did not generate bug.txt like version before 0.13.0. The result directory shows

- captured
- lint_issues
- logs
- results.db
-lint_issues

So how should I see the bug lists?

**Comment by WishQi** [comment]
@danyating For infer, there are two phases in the whole process. The first is capture, and the second is the analyze. You have only run the first phase capture, so you should run `infer analyze` after `infer capture`

**Comment by WishQi** [comment]
@dulmarod I have another question: Can Infer ignore the pod specs in the capture phase?

**Comment by danyating** [comment]
@WishQi thanks! After I run infer analyze, I get bug.txt file. So it finally woks out!
 And thanks @dulmarod  so much!

**Comment by dulmarod** [comment]
@danyating, @WishQi you don't need to run the capture separately, normally running `infer capture --keep-going --no-xcpretty -- xcodebuild build -scheme appName -workspace appName.xcworkspace -configuration Debug -sdk iphonesimulator` should do everything you need.

**Comment by veryitman** [comment]
@dulmarod 

It happends error:

```
Error backtrace:
Raised at file "integration/Driver.ml", line 297, characters 16-78
Called from file "integration/Driver.ml", line 176, characters 2-16
Called from file "backend/infer.ml", line 23, characters 2-36
Called from file "backend/infer.ml", line 106, characters 6-52
Uncaught error: ("InferModules__Driver.Infer_error(\"exited with code 65\")")
```

**Comment by dulmarod** [comment]
@veryitman I think that error just means the compilation failed, which can be many different things, so maybe it isn't the best to keep it all together in the the same issue. Could you please start a new issue and give more information about what you ran, the whole output, and ideally also the infer-out/logs file?

**Comment by veryitman** [comment]
Thanks @dulmarod .

**Comment by tomcati** [comment]
#855 
[log.txt](https://github.com/facebook/infer/files/1672982/log.txt)
So is mine
