### ISSUE TITLE
[help wanted] how to convert report.json to more readable format

### ISSUE THREAD

**Issue by AwayQuEM** [facebook/infer#811]
I use infer report diff  compare two branch analyze result. How can I convert report.json to more readable format. Like **bugs.txt**.

**Comment by dulmarod** [comment]
We don't have any support for that at the moment, but it shouldn't be hard to write a small program that processes the json and outputs a text format.

**Comment by sblackshear** [comment]
`infer report --from-json-report report.json --bugs-txt mybugs.txt`should work for this. You can also use `infer explore` to see the full trace for a specific bug.

**Comment by AwayQuEM** [comment]
@sblackshear using the cmd I got the human-readable  report, but not has `error code snippet`

use `infer_path/infer/lib/python/report.py --project-root ./ --result-dir ./infer-out --issues-json report.json --issues-txt mybugs.txt` I got what I want.

**Comment by tianshunjian** [comment]
FireFox can make the json file readable with a json add-on, eg Json Lite.

**Comment by sblackshear** [comment]
@AwayQuEM Nice sleuthing, we should perhaps make an easier-to-discover alias for that command! Closing this for now.
