### ISSUE TITLE
Objective-C: infer complains about dispatch_async

### ISSUE THREAD

**Issue by JackRobinson** [facebook/infer#819]
Hi, 

I've tried to find any similar questions, but failed:

infer issues the following warning on encountering dispatch_async in Objective-C code:

The value written to &__objc_anonymous_block_CLASS-NAME_METHOD-NAME______6 is never used.
```
    dispatch_async(dispatch_get_main_queue(), ^{
        NSLog(@"Hello World!");
    });
```
There is no warning if I use NSOperationQueue:
```
    [[NSOperationQueue mainQueue] addOperationWithBlock:^{
        NSLog(@"Hello World!");
    }];
```

Any ideas? Sorry if it's a silly question, I'm newbie in terms of how infer works.

infer:  0.13.0
Xcode: 9.1

**Comment by dulmarod** [comment]
Hi, I've already fixed this issue, you can get the newest version of Infer if you get the current master and compile the source. Otherwise you can pass --no-liveness to Infer to get rid of those warnings.

**Comment by JackRobinson** [comment]
Cool, thanks. Both the options do the trick.

**Comment by revolter** [comment]
Using version `v0.13.1` still complains about this case.

**Comment by jvillard** [comment]
@revolter a new release is in the works. 0.13.1 is from before the fix.

**Comment by revolter** [comment]
@jvillard Thank you for letting me know!
