### ISSUE TITLE
Testing Web application is possible?

### ISSUE THREAD

**Issue by RAMDdFLEET** [facebook/infer#82]
Testing hybrid mobile apps written in JavaScript framework for iOS and Android is possible with Facebook infer??

**Comment by dulmarod** [comment]
Hi,
Infer doesn't support Javascript at the moment. We may work on it in the future.

**Comment by jvillard** [comment]
Note that it should be possible to analyse the Java and Objective-C parts of your project using Infer. Follow the instructions [here](http://fbinfer.com/docs/analyzing-apps-or-projects.html) depending on what you use to build your project.
