### ISSUE TITLE
Is  there  possible  analyze  IOS project with  linux  System

### ISSUE THREAD

**Issue by tiandiyixian** [facebook/infer#820]
hi ，
     I  analyze  different  code  projects，such  as   java、c 、c++ and  oc，is there  one way that we can  analyze   oc   with  ubuntu   or  centos  directly，thanks .

**Comment by dulmarod** [comment]
Hi, in general to compile Objective-C projects one needs MacOS, but if your system builds in Linux, Infer may work too. You can try it.

**Comment by tiandiyixian** [comment]
thanks!
