### ISSUE TITLE
Problem with INFERBO with Java code

### ISSUE THREAD

**Issue by paso101** [facebook/infer#825]
Good evening.
I have a question about the Inferbo checker for bufferoverrun in Java code.
I tried Inferbo on the following two examples of Java code:

**EXAMPLE 1:** 

```
public class BufferOverrun {

	public static void main(String[] args) {
		int arrayDimension = 5;
		int [] myArray = new int[arrayDimension];

		for(int pos = 0; pos < arrayDimension; pos++)
			myArray[pos] = pos * (2 + pos);	
	}
}

```
and output is: 

```
Found 1 issue

BufferOverrun.java:9: error: BUFFER_OVERRUN_L2
  Offset: [0, 4] Size: [1, 1].
  7.   		int [] myArray = new int[arrayDimension];
  8.   		for(int pos = 0; pos < arrayDimension; pos++)
  9. > 			myArray[pos] = pos * (2 + pos);	
  10.   
  11.   	}

Summary of the reports

  BUFFER_OVERRUN_L2: 1
```

But I did not expect errors.

**EXAMPLE 2:** 

```
public class BufferOverrun {

	public static void main(String[] args) {
		int arrayDimension = 5;
		int [] myArray = new int[arrayDimension];
		for(int pos = 0; pos < arrayDimension; pos++) 
			myArray[pos + 1] = pos * (2 + pos);	
	}
}
```

and output is: 

```
Found 1 issue

BufferOverrun.java:9: error: BUFFER_OVERRUN_L1
  Offset: [1, 5] Size: [1, 1].
  7.   		int [] myArray = new int[arrayDimension];
  8.   		for(int pos = 0; pos < arrayDimension; pos++) 
  9. > 			myArray[pos + 1] = pos * (2 + pos);	
  10.   	}
  11.   }


Summary of the reports

  BUFFER_OVERRUN_L1: 1
```

But I expected Size[5, 5]. I don't understand why "myArray" has Size [1, 1] and 
hasn't Size[5, 5]. 

Could you tell me if the two outputs are correct or incorrect?
Thank you so much.

**Comment by mbouaziz** [comment]
Hi @paso101,
Thanks for your interest in Inferbo!
Inferbo is still a work in progress targeting C/C++ for now.
You actually tested it on Java before we even tried!

I am closing the task as we have no plan on supporting Java in the near future but feel free to contact me/send pull requests if you want to contribute and add Java support.
