### ISSUE TITLE
infer build fails with jdk 9

### ISSUE THREAD

**Issue by briannacd** [facebook/infer#826]
Using Ubuntu 16.4 LTS. built with openjdk 8. build completes with no errors. purge openjdk 8, make clean, and install openjdk 9. build again. receive [*ERROR**][567] *** ERROR Building Infer models
[*ERROR**][567] Usage Error: 
[*ERROR**][567] *** Failed to execute compilation command: exited with code 2
[*ERROR**][567] *** Command: 'javac' '@/tmp/args_70e9c9'
[*ERROR**][567] *** Output:
[*ERROR**][567] javac: option -bootclasspath not allowed with target 1.9
[*ERROR**][567] Usage: javac <options> <source files>
[*ERROR**][567] use -help for a list of possible options

**Comment by jvillard** [comment]
Which version of infer is that?

This should be fixed in master, since 185e7f713111f370c2b1b8a71b2236e1a3b89e21.
