### ISSUE TITLE
How does infer works?

### ISSUE THREAD

**Issue by WishQi** [facebook/infer#828]
I am an iOS developer, and I am trying to use infer in our project.
But I really want to know how the infer works and "static analysis principle" infer uses.
I have read the documents in http://fbinfer.com/. But it is not detailed enough.
Can you give me some wikis or webs to learn about that?

**Comment by sblackshear** [comment]
This [paper](http://www.cs.ox.ac.uk/people/hongseok.yang/paper/jacm11-biabduction-webversion.pdf) on Infer's bi-abduction analysis is a good resource. The bi-abduction is only one of many Infer analyses, but it is the basis for many of the checks.

**Comment by jvillard** [comment]
More information can be found in the ["Foundations"](http://fbinfer.com/docs/about-Infer.html) section of the online documentation. Some more papers are listed [here](http://fbinfer.com/docs/separation-logic-and-bi-abduction.html#technical-papers). Hope you can find the answers you're looking for there.
