### ISSUE TITLE
Infer-annotations jar is hard to find

### ISSUE THREAD

**Issue by Cliabhach** [facebook/infer#829]
This issue concerns the document at https://github.com/facebook/infer/blob/gh-pages/_docs/01-racerd.md and on the public website at http://fbinfer.com/docs/racerd.html .

In that document, there is a reference to the package `com.facebook.infer.annotation` under the 'unprotected-write' heading, and further details under 'annotations-to-help-racerd-understand-your-code'. I propose adding a section to the Getting Started document with a link to this part of the RacerD docs and maybe a mention of compatible versions of the infer runner.

Possibly related: [the page on maven-repository.com](https://maven-repository.com/artifact/com.facebook.infer.annotation/infer-annotation/0.10.0.2) that the RacerD docs link to seems to be outdated. Would it make sense to change that link to the repository page at https://maven-repository.com/artifact/com.facebook.infer.annotation/infer-annotation instead?

**Comment by sblackshear** [comment]
Good points, especially regarding the Maven link. I changed the RacerD docs to link to the page you suggest, and I added a link to the Maven page at the point `com.facebook.infer.annotation` is first mentioned to improve discoverability.

Feel free to send a pull request for the change to the "Getting Started" part--I didn't have quite as good of a sense for what you had in mind there.

**Comment by Cliabhach** [comment]
Sure, will do.
