### ISSUE TITLE
Unix.Unix_error "Illegal seek" sysconf ""

### ISSUE THREAD

**Issue by AnyMarvel** [facebook/infer#832]
While running ./build-infer.sh on Ubuntu 17.10 there is a compilation failure claiming an uncaught exception. 
Uncaught exception:
  
  (Unix.Unix_error "Illegal seek" sysconf "")

Raised by primitive operation at file "src/core_unix.ml", line 348, characters 14-29
Makefile:200: recipe for target '/home/admin/infer/infer/man/man1/infer-analyze.1' failed
make: *** [/home/admin/infer/infer/man/man1/infer-analyze.1] Error 2
make: *** 正在等待未完成的任务....
Uncaught exception:
  
  (Unix.Unix_error "Illegal seek" sysconf "")

I hope to solve Bug, thank you.

**Comment by remy-luisant** [comment]
Dupe of #776, it seems.

**Comment by mbouaziz** [comment]
Duplicate indeed, please follow up on #776. Unfortunately still waiting on core fix
