### ISSUE TITLE
Current relase (0.13.0) fails when building on Ubuntu 16.04 LTS.

### ISSUE THREAD

**Issue by andrewhabib** [facebook/infer#834]
Hi, 
I am trying to build Infer on my Ubuntu 16.04 LTS machine.
After fixing several Opam issues, I get the following error related to string/buffers in OCaml:

[18:21:22][12165] Generating source dependencies...
[      0s][12165] SUCCESS Generating source dependencies
[18:21:22][12285] Building native(opt) Infer...
[*ERROR**][12285] *** ERROR Building native(opt) Infer
.
.
.
[*ERROR**][12285] File "eradicate/models.ml", line 53, characters 4-44:
[*ERROR**][12285] Warning 3: deprecated: InferStdlib.IStd.String.set
[*ERROR**][12285] [since 2017-10] Use [Bytes.set] instead
[*ERROR**][12285] File "eradicate/models.ml", line 53, characters 4-5:
[*ERROR**][12285] Error: This expression has type string but an expression was expected of type
[*ERROR**][12285]          bytes
[*ERROR**][12285] make[1]: *** [_build/opt/infer.exe] Error 1
Makefile:161: recipe for target 'src_build' failed
make: *** [src_build] Error 1

I tried to manual change the use of string to bytes at the specified line, but this results in other related errors when this expression is used. Any idea?

**Comment by jberdine** [comment]
This seems to be due to base v0.10.0. An undate to infer that is compatible with base v0.10.0 is upcoming. In the meantime, you should be able to first install base v0.9.4 and then install infer.

**Comment by andrewhabib** [comment]
Thank you! This solved the problem. 
I had to do a lot of manual Opam package installations to avoid the automatic upgrade to base v0.10.0.

**Comment by shiyy123** [comment]
Sorry, I do not understand the base v0.10.0. Is it the Infer version 0.10.0?
