### ISSUE TITLE
View inferred Hoare triples

### ISSUE THREAD

**Issue by jkoppel** [facebook/infer#835]
Hello, 

Is there any way to view the specs inferred by the Infer bi-abductive inference checker, or any of its other intermediate analysis results? I just read through several of the papers on Infer and bi-abductive inference, and am trying to get a better sense of strengths of weaknesses of the technique (especially its points of imprecision).

**Comment by jkoppel** [comment]
NVM; I found the "infer report" command.

**Comment by nuaaysh** [comment]
> NVM; I found the "infer report" command.

Hello, I also use the infer report to compile the `.specs` files to a `result.db` file, but I can not find any hoare tripes from the result.db?

![image](https://user-images.githubusercontent.com/30371276/101704248-45413d00-3abf-11eb-9645-f61643e0f387.png)
![image](https://user-images.githubusercontent.com/30371276/101704296-5ee28480-3abf-11eb-988a-8d690d5fc679.png)


Could you please give me some suggestions?

**Comment by jvillard** [comment]
@nuaaysh You can see the specs using `infer debug`, for example `infer debug --procedures --procedures-summary`. See `infer debug --help` for more information.

**Comment by nuaaysh** [comment]
> @nuaaysh You can see the specs using `infer debug`, for example `infer debug --procedures --procedures-summary`. See `infer debug --help` for more information.

@jvillard  Thanks a lot! I try to analyze the (fletecher32.c file)[https://github.com/RIOT-OS/RIOT/blob/master/sys/checksum/fletcher32.c]:

1. `infer capture -- gcc -c fletcher32.c` ==> generating the .db file
2. `infer-analyze`  ==> no issues found 
3. `infer debug --procedures --procedures-summary` ==> 

```
Selected proc name: fletcher32
unsigned int fletcher32(unsigned short const * data, unsigned long words)
Analyzed
ERRORS: 
WARNINGS: 
FAILURE:SYMOPS TIMEOUT (1101) SYMOPS:1101
Biabduction: phase= RE_EXECUTION

RacerD: 
Threads: NoThread, Locks: 0 
Accesses { } 
Ownership: Unowned 
Return Attribute: Nothing 
Attributes: { } 

Siof: (⊥,
{ })
Starvation: {thread= UnknownThread; return_attributes= Nothing;
             critical_pairs={ };
             scheduled_work= { };
             attributes= { }}
Uninitialised: 
 Pre: { } 
Post: { } 

Waiting for Sqlite write daemon to start (0.200000 seconds)
Waiting for Sqlite write daemon to start (0.400000 seconds)
Waiting for Sqlite write daemon to start (0.800000 seconds)
```
I check the .db file, find two records:
![image](https://user-images.githubusercontent.com/30371276/101764376-f88b4f80-3b1a-11eb-9da8-f858d3cb7231.png) and the 
![image](https://user-images.githubusercontent.com/30371276/101764466-0f31a680-3b1b-11eb-8a53-4f5c29759bdf.png)

So do all pre-post conditions are store in the records?  (as a SQL newbie, I am trying to convert them into the text form, I am trying to execute the SQL `SELECT CONVERT(column USING utf8) FROM specs`, but failed).

Could you please give me some suggestions?

**Comment by jvillard** [comment]
The specs in term form are what gets printed by `infer debug`. They are stored as binary blobs in the sqlite db and there's no way to view them as text there as these actually encode OCaml objects. This is why we provide the `infer debug` command, which loads the sqlite data into OCaml and then prints them.

**Comment by nuaaysh** [comment]
Thanks a lot! 

My Mac installs the 0.17.0 version of fbinfer (my Ubuntu has another version, I will check it tonight). I use the `infer --debug --procedures --procedures-attributes` to generate some html files:
![image](https://user-images.githubusercontent.com/30371276/101778900-ccf56e80-3af4-11eb-911b-110b2ae2a982.png)
And I also find some information like the precondition (about liveness?)
![image](https://user-images.githubusercontent.com/30371276/101779255-5311b500-3af5-11eb-82f0-8cb97e3655b1.png)
Could you please give me some suggestions about how to get the hoare triples form `{pre} c {post}`? or some documents to explain the html form as in the figure?

**Comment by nuaaysh** [comment]
Hi,
@jvillard for instance, I use fbinfer to analyze the [fletcher32.c](https://github.com/RIOT-OS/RIOT/blob/master/sys/checksum/fletcher32.c), but I get the  empty pre-post conditions

```
@ unsigned int fletcher32(unsigned short const * data, unsigned long words) Analyzed
FAILURE:SYMOPS TIMEOUT (1101) SYMOPS:1101
...
Biabduction: phase= RE_EXECUTION

RacerD: 
Threads: NoThread, Locks: { } 
Accesses { } 
Ownership: Unowned 
Return Attributes: { Functional } 

Siof: (⊥,
{ })
Starvation: {events= { }; guard_map= { }; lock_state= { };  order= { }; ui= ⊥}
Uninitialised: 
 Pre: { } 
Post: { } 
```
I find the #963  and #1110, they talked about the `FAILURE:SYMOPS TIMEOUT (1101)`, so it means *fbinfer* can not generate the pre-post conditions because of the timeout?

**Comment by jvillard** [comment]
@nuaaysh The timeout is only for the "Biabduction" analysis (the memory analysis, one of the main analyses in infer). If it hadn't timed out you would have seen pre/post specs there. The other analyses ran fine but didn't record anything interesting in their specs either for some reason: RacerD, SIOF, Starvation, and Uninitialized.

Note that hashing functions have little chance of being given meaningful specifications by static analyses that try to understand relationships between values, such as Biabduction, as hash functions are generally meant to be hard to invert or express in terms of pre/post.

**Comment by nuaaysh** [comment]
Many Thanks!

**Comment by nuaaysh** [comment]
@jvillard  Hello Jules,
![image](https://user-images.githubusercontent.com/30371276/101790437-b9e99b00-3b02-11eb-97d9-493dfdfeee56.png)
Where could I find the explanatory document to help me understand the html file?
such as:
* the FAILURE (I check the [online document](https://fbinfer.com/docs/0.17.0/checkers-bug-types), but no such error)
* there are two places about pre/post conditions, which one is the hoare triples?
* there are some symbols like `val$1formal:` and `val$2update:61:unsigned int`, how to understand this kind of form 

Best,
Shenghao
