### ISSUE TITLE
Compile failed in iOS

### ISSUE THREAD

**Issue by Debhora** [facebook/infer#84]
![screen shot 2015-06-19 at 3 39 57 pm](https://cloud.githubusercontent.com/assets/11853648/8251375/b053ccb6-1699-11e5-8c01-44e83d704cc4.png)

I have followed the instructions in the docs for infer, and installed infer. In oder to analyse the app i have used the following command:

infer --incremental -- xcodebuild -target xyz -configuration Debug -sdk iphonesimulator 

Initially i was getting the @import error in #2 , but now the error is different as described in the screenshot attached. Bt when the app is built in Xcode, the app works fine on simulator and device.

I have the xcworkspace of "xyz" app as pods also is added to the project. Please let me know if there is any other command that can be used to analyse xcworkspace.

**Comment by martinoluca** [comment]
Hello @Debhora,
are you using the latest release of Infer available in https://github.com/facebook/infer/releases/latest
Can you please send me the output of `infer --version`

Thanks!

**Comment by Debhora** [comment]
Hello @martinoluca,

I am using the latest version 1.1. Please find the screensho
![screen shot 2015-06-22 at 4 20 14 pm](https://cloud.githubusercontent.com/assets/11853648/8280420/bbed04da-18fa-11e5-9e3d-8a41020d927c.png)
t in the attchement

**Comment by martinoluca** [comment]
Hi @Debhora,
>I have followed the instructions in the docs for infer, and installed infer. In oder to analyse the app i have used the following command:
infer --incremental -- xcodebuild -target xyz -configuration Debug -sdk iphonesimulator

I suspect the problem is related with the fact that in the presence of CocoaPods, you should use the xcworkspace and not the xcodeproj; please try running a command like this (customize according to your project):
```
xcodebuild -workspace HelloWorld.xcworkspace -scheme HelloWorld
```

As usual, please make sure the command itself works as expected, then run it with `infer --`

Let me know if this helps!

**Comment by matto1990** [comment]
@martinoluca I ran into this issue and it was that I needed to use the workspace rather than the project file implicitly

**Comment by martinoluca** [comment]
Thank you @matto1990!

**Comment by Debhora** [comment]
Hi @martinoluca,

Yes the above command works. Thank you.

**Comment by fer662** [comment]
Sadly i'm running into this issue with 0.1.1. xcodebuild works alone, but infer doesn't, and it complains about being unable to compile some pods.

My command is (censoring for NDA reasons)
infer -- xcodebuild -workspace XXXX.xcworkspace -scheme XXXX-Staging-Debug -sdk iphonesimulator

xcode 6.3
cocoapods 0.37.1
infer v0.1.1
What info would be useful to you?

**Comment by Ricardo1980** [comment]
Nowadays very often iOS developers use cocoapods (or similar).
I suggest writing this info in the docs section, because I spent a while searching what I was doing wrong.

**Comment by revolter** [comment]
I agree with @Ricardo1980. Cocoapods is so used that this should be in the "Hello World" example.

**Comment by jvillard** [comment]
Are you talking about adding this information here: http://fbinfer.com/docs/hello-world.html? It would be easy to add a note in the "Hello world iOS" section.

By the way, there's an entry in the FAQ, but maybe it should be given more visibility: http://fbinfer.com/support.html#infer-cannot-analyze-my-cocoapods-project

**Comment by revolter** [comment]
Yes, in the _Hello world Objective-C_ section, there could be a warning like:

> Warning: If you're using Cocoapods, make sure you read the [FAQ](http://fbinfer.com/support.html#infer-cannot-analyze-my-cocoapods-project).
