### ISSUE TITLE
Need infer materials

### ISSUE THREAD

**Issue by cyw3** [facebook/infer#840]
I can not open the web site http://fbinfer.com/.
And I find that infer-v0.13.0 is different with infer-v0.1.0.
SO, 
1. Can you give me some material on infer?
2. Now, How can i set infer to Incremental analyze?

**Comment by jvillard** [comment]
If you cannot access the website but can access GitHub, you should be able to clone the website locally and run it:

```
sudo gem install bundler
sudo gem install github-pages
git clone https://github.com/facebook/infer.git
cd infer
git checkout gh-pages
jekyll serve -w --config _config.yml,_config_local_dev.yml
```

Then visit http://localhost:4000/, for instance http://localhost:4000/docs/steps-for-ci.html to see the docs about the differential workflow.

**Comment by yalechen-cyw3** [comment]
Thank you!

**Comment by cyw3** [comment]
Thank you!

**Comment by cyw3** [comment]
@jvillard Can you give some material  on all rules of infer?
And there have rule's msg, severity, and language pointed to.

**Comment by jvillard** [comment]
Closing as the initial issue is resolved. Follow-up issue in #844
