### ISSUE TITLE
Error when user infer with clang

### ISSUE THREAD

**Issue by cyw3** [facebook/infer#842]
![image](https://user-images.githubusercontent.com/11549103/35034110-036bd812-fba8-11e7-81a5-14bb3a608e04.png)

We can see:
1. cmd: clang -c main.m
clang works.

2. cmd: infer run -- clang -c main.m 
it occur a error.

main.m code:

```
#import <Foundation/Foundation.h>

int main(int argc, const char * argv[]) {
    @autoreleasepool {
        // insert code here...
        NSLog(@"Hello, World!");
    }
    return 0;
}
```

infer v0.13.0
Mac 10.13.2 (17C88)

clang -v
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by cyw3** [comment]
@facebook-github-bot

**Comment by cyw3** [comment]
Which version of mac os infer support?

**Comment by cyw3** [comment]
@dulmarod 

I think that maybe infer-v0.13.0/lib/infer/facebook-clang-plugins/clang  cant not find the "Fundation.h" which is in the Xcode.

any idea?

**Comment by cyw3** [comment]
I find that on x86_64-apple-darwin16.8.0, infer-clang-v5.0.0 will find the "Fundation.h"  at "/System/Library/Frameworks/Foundation.framework/Versions/C/Headers", but on x86_64-apple-darwin17.3.0, there is not "/System/Library/Frameworks/Foundation.framework/Versions/C/Headers", only have "/System/Library/Frameworks/Foundation.framework/Versions/C/Resources" and something else.

so, i want to know Which version of mac os infer support?

**Comment by jvillard** [comment]
Not sure if that's the issue, but you can try installing the command line tools: `xcode-select --install`.
