### ISSUE TITLE
the list of infer rules

### ISSUE THREAD

**Issue by cyw3** [facebook/infer#844]
Can you give me the list of infer rules and the detail msg of the rules? 
for example, The rules below:
![image](https://user-images.githubusercontent.com/11549103/35141600-65857672-fd36-11e7-94ca-23af5ed7bc71.png)

**Comment by cyw3** [comment]
What is the meaning of "Abduction_case_not_implemented "?

**Comment by jvillard** [comment]
Most of these are filtered by default, and for good reasons: they are internal exceptions, not meant for users. In you screenshot, only `NULL_DEREFERENCE`, `RESOURCE_LEAK`, and `UNINITIALIZED_VALUE` are meaningful reports. These bug types are described in [this page](http://fbinfer.com/docs/infer-bug-types.html).

**Comment by cyw3** [comment]
@jvillard So, the  meaningful rules are all below ???
![image](https://user-images.githubusercontent.com/11549103/35218321-2938a5c0-ffa9-11e7-8356-7e752a2e1361.png)
