### ISSUE TITLE
what does it mean that the bug type of DEAD_STORE, with infer 0.13.0

### ISSUE THREAD

**Issue by NeowuqiLee** [facebook/infer#847]
The bug type DEAD_STORE did not introduced in
http://fbinfer.com/docs/infer-bug-types.html
![image](https://user-images.githubusercontent.com/12151989/35312306-c4c843fe-00f5-11e8-94f7-6f8bd3f1b8e5.png)
Actually, these above values  are used

**Comment by sblackshear** [comment]
Can you share a minimal repro snippet for one of these and instructions for building the snippet?

**Comment by NeowuqiLee** [comment]
the infer cmd ：
![image](https://user-images.githubusercontent.com/12151989/35315785-4080fb7c-0109-11e8-8355-90a5b34348c8.png)
DEAD_STORE  description：
PROVER | ERROR | DEAD_STORE | The value written to &labelText is never used | HIGH | 27 | NewMyLotyMainView_refreshMyInfo | refreshMyInfo#NewMyLotyMainView#instance.fb3a6b865b48fc13447d1a57ca90dcc7 | GuessKit/GuessKit/MyLotyMain/Views/NewMyLotyMainView.m | {"trace":[{"level":0,"filename":"GuessKit/GuessKit/MyLotyMain/Views/NewMyLotyMainView.m","line_number":27,"column_number":9,"description":"Write of unused value","node_tags":[]}]} | 173877444 | <qualifier_tags></qualifier_tags> | 25231827 | 15 | false
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by crespoxiao** [comment]
how to filter the type DEAD_STORE ? I don't want it because so many this kind bug type make the report.html not easy to read.

**Comment by jvillard** [comment]
@crespoxiao passing `--no-liveness` to infer will disable the dead store checker.

**Comment by crespoxiao** [comment]
@jvillard thank you.

**Comment by jvillard** [comment]
Dead store is documented (briefly) [here](http://fbinfer.com/docs/checkers-bug-types.html#dead-store).
