### ISSUE TITLE
Error in inferTraceBugs

### ISSUE THREAD

**Issue by PriyankaJais** [facebook/infer#85]
Hi 

I am trying to run fbInfer for an XCode project. The analysis ran successfully. Got this message at the end: 
** BUILD SUCCEEDED **

There was nothing to analyze, exiting

After this I tried running inferTraceBugs. I am getting the following error: 

Traceback (most recent call last):
  File "/Users/Priyanka/Documents/XXXX /Tools/infer-osx-v0.1.1/infer/infer/bin/inferTraceBugs", line 270, in <module>
    main()
  File "/Users/Priyanka/Documents/XXXX /Tools/infer-osx-v0.1.1/infer/infer/bin/inferTraceBugs", line 248, in main
    with open(os.path.join(args.infer_out, JSON_REPORT)) as report_file:
IOError: [Errno 2] No such file or directory: u'/Users/Priyanka/Documents/XXXX/Local/XXXX/trunk/infer-out/report.json'

Why am I getting this error? Any help appreciated. Thanks!

**Comment by jvillard** [comment]
Hi @PriyankaJais,

> There was nothing to analyze, exiting

This means that Infer didn't find any file to analyse in your project. You should run Infer on a cleaned version of your project. Try running something like this before running Infer:

```shell
xcodebuild -target <your target> -configuration Debug -sdk iphonesimulator clean
```

(adapt this command to your own project)

> IOError: [Errno 2] No such file or directory: u'/Users/Priyanka/Documents/XXXX/Local/XXXX/trunk/infer-out/report.json'
> 
> Why am I getting this error? Any help appreciated. Thanks!

You are getting this error because the Infer result directory (`infer-out`) doesn't exist, because Infer didn't find anything to analyse.

**Comment by PriyankaJais** [comment]
Thanks!

I am sorry if this is a silly question but my xcodeproj is in a trunk folder and the source files are in a folder inside the trunk folder like, 

ls -lrt trunk
rwxr-xr-x@  6 Priyanka  staff     204 May 11 12:31 Project.xcodeproj
drwxr-xr-x@  7 Priyanka  staff     238 Jun 19 17:24 Project

Now, when im trying to run fbInfer from the trunk directory, I get the error: 
There was nothing to analyze, Exiting. 

When i tried running from the Project directory, Im getting the following error:
xcodebuild: error: The directory /Users/Priyanka/Documents/XXXX/Local/Project/trunk/Project does not contain an Xcode project.

**Comment by martinoluca** [comment]
Hello @PriyankaJais,
I'd suggest to have a look at this guide by Apple to find the right command to build your project through `xcodebuild` https://developer.apple.com/library/ios/technotes/tn2339/_index.html#//apple_ref/doc/uid/DTS40014588-CH1-HOW_DO_I_BUILD_MY_PROJECTS_FROM_THE_COMMAND_LINE_

Follow the guide and try running `xcodebuild` with the correct set of arguments first, then as soon as you find the right configuration, try using `infer -- ` with it.

If you still have problems, please paste here, if you can, the `xcodebuild` command you are using and information that can help troubleshooting, like the output of the command.

Thanks!

**Comment by PriyankaJais** [comment]
I am trying to build through a script. Using the following commands:

xcodebuild -project Project.xcodeproj -scheme Project clean
infer -- xcodebuild -target Project

Before using infer, i was using :

xcodebuild -project Project.xcodeproj -scheme Project clean build > xcodebuild.log 

I was able to build successfully without Infer

**Comment by PriyankaJais** [comment]
I tried to use infer with the example HelloWorldApp also in ios_hello directory

Following is the output:
Priyankas-MacBook-Pro:HelloWorldApp Priyanka$ infer -- clang -c Hello.m
Starting analysis (Infer version v0.1.1)
Analysis done

0 file analyzed


No issues found

**Comment by jvillard** [comment]
@PriyankaJais: you may have some luck with re-installing the command line tools, as pointed out in [another issue](https://github.com/facebook/Infer/issues/12#issuecomment-113900524).

**Comment by Mayur5130** [comment]
Hello,
I am checking with example for iOS app and using below command for testing bugs in app but i didnt get any single issue. Can you please help me on that. 

"infer -- xcodebuild -target HelloWorldApp -configuration Debug -sdk iphonesimulator"

Its show only one warning. And in line "There was nothing to analyze, exiting". 

How to check all error and leaks ?

Thanks & Regards,
Mayur Bhansali

**Comment by dulmarod** [comment]
Hi,
Maybe you need to clean your project first by running 
xcodebuild -target HelloWorldApp -configuration Debug -sdk iphonesimulator clean and then try to run infer.

**Comment by jvillard** [comment]
This has been inactive for a while. Feel free to re-open if you have more questions.
