### ISSUE TITLE
List of parsable rule names

### ISSUE THREAD

**Issue by LArmb** [facebook/infer#853]
Hey,
I like the work you are doing, and I would like to integrate the results from Infer with those from other static analysers. In order to do so, I plan to parse your XML report. 
Do you have a list of all the rule names used in your reports (e.g. DEAD_STORE)? In other issues, such as #844, you refer to [http://fbinfer.com/docs/infer-bug-types.html](http://fbinfer.com/docs/infer-bug-types.html). But there, only a description is given, not the actual name used in the report. 
Any additional information on the rules would be highly appreciated as well (e.g. default severity, which of the command line options such as `--bufferoverrun` enables that rule, etc). But a list of names would already be a good start.
Thanks!!
Lukas

**Comment by dulmarod** [comment]
Hi, here is a list with most names: https://github.com/facebook/infer/blob/master/infer/src/base/IssueType.ml

For the linters for iOS, the names are in https://github.com/facebook/infer/blob/master/infer/lib/linter_rules/linters.al, there you can also see the severity in the rule.

**Comment by LArmb** [comment]
Hey,
thanks for the quick reply! I actually did find the IssueType.ml. But in #844, @jvillard wrote about a set of rules mentioned in the question:
> Most of these are filtered by default, and for good reasons: they are internal exceptions, not meant for users.

So I was not sure whether all these `IssueType`s can actually occur in e.g. the XML report. Thanks for the confirmation that they do.

**Comment by dulmarod** [comment]
@jvillard is correct, many of those are filtered out. For the ones that are not filtered out, the website is the best source, you can then cross-reference it with IssueType to get the actual name.

**Comment by LArmb** [comment]
Hey,
okay, I'll do that. Thanks for the support :)
