### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by cyw3** [facebook/infer#856]
![image](https://user-images.githubusercontent.com/11549103/35546748-86e945aa-05b0-11e8-8a81-2c8adb0d5a4e.png)

When i use "infer run --reactive --continue --debug --keep-going --jobs 8 -- ant" to scan a big Android project, I got the error.

infer-v0.13.0

**Comment by cyw3** [comment]
I found that after i use the cmd to scan the project, infer will use javac to build a huge amount of java files and will reach the limit of mac terminate command length.

"Failed to execute: /usr/local/Cellar/infer/0.13.0/lib/infer/infer/lib/python/inferlib/../../../bin/infer capture --continue -- javac -J-Xmx2048m -nowarn -d [lots of java files ]"

**Comment by cyw3** [comment]
I fixed it locally.

**Comment by mbouaziz** [comment]
Hi @cyw3, I'm glad you managed to fix the issue.
Could you share your fix here to help other users facing the same issue?
Many thanks!

**Comment by TomMD** [comment]
I've hit the same issue and learned infer does not all file arguments. That is to say, `javac` allows arguments to be placed in a file and then called as `javac @/the/file` at which point the arguments will be read out. As of writing, it seems infer does not handle `@/some/file` correctly.  Solution unknown.

**Comment by jvillard** [comment]
@TomMD could you provide a repro or elaborate? Running `infer -- javac @/some/file` works for me and there's a word missing in your comment: "infer does not all file arguments".

Or is the issue that there are `javac` commands that are near the OS limit and passing them to infer pushes them over the limit where infer could instead put the arguments into a temporary file?
