### ISSUE TITLE
Error when install infer-Dockerfile.

### ISSUE THREAD

**Issue by cyw3** [facebook/infer#857]
![image](https://user-images.githubusercontent.com/11549103/35553440-dd168da8-05d2-11e8-932b-29aa5e1b555e.png)

How to handle with it?

**Comment by bulwahn** [comment]
This is an issue with the Docker version you are using; recent Docker versions do not support the MAINTAINER identifier in docker files anymore. You will find more information on this elsewhere on the web. This is not related to infer, though. For more information on the infer docker build, there is already an open issue #830 that discusses how to get the docker image to build.

**Comment by cyw3** [comment]
So What is the correct docker version?
@bulwahn

**Comment by jvillard** [comment]
This should be fixed now, thanks for the report.
