### ISSUE TITLE
False alarm: static initialisation order fiasco

### ISSUE THREAD

**Issue by Jaxan** [facebook/infer#866]
The error `STATIC_INITIALIZATION_ORDER_FIASCO` fires even when only an address is taken from a global variable. As far as I know, that is totally defined. It only triggers when using a non-trivial type like `std::string`. (That is to say: I cannot reproduce it with `int`s.)

You can reproduce this false alarm with these files:

```c++
// h.hpp
#pragma once
#include <string>

extern const std::string bla;
extern const std::string * bla_ptr;
```

```c++
// x.cpp
#include "h.hpp"

const std::string bla = { "hoi" };
```

```c++
// y.cpp
#include "h.hpp"

// Note that we are not depending on bla being initialised or not!
const std::string * bla_ptr = { &bla };
```

Gives the following error (false alarm):
```
y.cpp:3: error: STATIC_INITIALIZATION_ORDER_FIASCO
  Initializer of bla_ptr accesses global variable from a different translation unit: bla|EXTERN.
  1.   #include "h.hpp"
  2.   
  3. > const std::string * bla_ptr = { &bla };
```

Thanks for the great tool, by the way :-)!
Infer version v0.13.0

**Comment by Jaxan** [comment]
I just realised that this is a bit more subtle since `operator&` can be overloaded, sadly... So infer is right to say that this may be a fiasco. However, in the case of `std::string`, this operator is not overloaded.

**Comment by jvillard** [comment]
Thanks for the detailed report. This reproes in the latest master, I'll take a look. Infer should (usually) be aware of which `operator&` is being used so overloading should not be too much of any issue.
