### ISSUE TITLE
Some files saying "All Rights Reserved"?

### ISSUE THREAD

**Issue by hartwork** [facebook/infer#87]
Hi!

I stumbled over a file that says "All Rights Reserved" in the header:
https://github.com/facebook/infer/blob/master/infer/src/Makefile
If the license is BSD for everything, please put that in the header of all files in the repository.
That makes infer safe to use and is in line with good practice. Many thanks in advance!

Best, Sebastian

**Comment by cristianoc** [comment]
https://github.com/facebook/infer/commit/3e199467f4c7e901b9c8b470231961f241be6d57

**Comment by wielkapala** [comment]
20 lip 2015 09:37, "cristianoc" <notifications@github.com> napisał(a):

**Comment by hartwork** [comment]
Thank you!
