### ISSUE TITLE
install infer with "docker pull"

### ISSUE THREAD

**Issue by cyw3** [facebook/infer#870]
Can I use "docker pull", not "docker build", to install infer docker image?

**Comment by cyw3** [comment]
@jabley

**Comment by toli** [comment]
the https://hub.docker.com/r/infer/infer/ Docker Hub repo is empty.. noone has pushed an image there yet

would you guys be able to create/push an image there?
we can then use it as a base image 

Until then, feel free to use https://hub.docker.com/r/toli/infer/

**Comment by cyw3** [comment]
Thank you!
