### ISSUE TITLE
build-infer.sh does not work with opam 2

### ISSUE THREAD

**Issue by farao** [facebook/infer#871]
In Fedora, the current opam version is 2.0.0~beta6 and if I execute ./build-infer.sh I get the following error:

=-=- Updating package repositories =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default] no changes from https://opam.ocaml.org/2.0
Now run 'opam upgrade' to apply any package updates.
opam: unknown option `--alias-of'.
Usage: opam switch [OPTION]... [COMMAND] [ARG]...
Try `opam switch --help' or `opam --help' for more information.

*** ERROR: `opam switch set -j 4 infer-4.05.0+flambda --alias-of 4.05.0+flambda` failed

**Comment by mbouaziz** [comment]
Hi @farao, sorry for the delay.
We don't support opam2 for the time being as it is still a beta version, sorry for that.
Feel free to send a PR and we will gladly review it.

**Comment by ZiFy** [comment]
@mbouaziz When will infer support opam2.0？

**Comment by fxcoudert** [comment]
Opam 2 was released

**Comment by jackwzx** [comment]
when could I use infer in mac mojave

**Comment by kfiresmith** [comment]
Whew, glad this was already posted.  I don't know what I'm doing with ocaml or opam (I'm just a hapless sysadmin trying to build infer for a developer) - When I read the deps for Linux, some things had specific versions and some had this-version-or-newer, I suppose I should have realized that opam-1.2.2 *really* means just that version and not opam2.  Potential area of improvement on the docs might be to make the version requirements more explicit and idiot proof.

**Comment by jvillard** [comment]
It ended up taking a while but this is fixed by c00b076a05cc8f4f80f9241f86a247fd43c36fe6.

**Comment by fxcoudert** [comment]
Could a new release be cut with this support?

**Comment by jvillard** [comment]
@fxcoudert that's the plan, but currently building infer on opam2 requires you to disable sandboxing to build javalib (https://github.com/ocaml/opam-repository/issues/13040). I'm waiting for this to be resolved first but if it takes too long I might make a release anyway (since we ship binaries users typically don't need to rely on opam anyway).

In the meantime you can always build master, it's supposed to be stable.
