### ISSUE TITLE
False positives for __block variables

### ISSUE THREAD

**Issue by revolter** [facebook/infer#873]
Having:

```objective-c
__block BOOL hasRecordPermission = NO;

AVAudioSession *audioSession = [AVAudioSession sharedInstance];

dispatch_semaphore_t semamphore = dispatch_semaphore_create(0);

[audioSession requestRecordPermission:^(BOOL granted) {
	hasRecordPermission = granted;

	dispatch_semaphore_signal(semamphore);
}];

dispatch_semaphore_wait(semamphore, DISPATCH_TIME_FOREVER);

return hasRecordPermission;
```

Infer generates the error:

> The value written to &hasRecordPermission is never used

at the line `hasRecordPermission = granted;`.

**Comment by dulmarod** [comment]
Could you add which version of Infer you are using?

**Comment by revolter** [comment]
Sorry, forgot about it.

> Infer version v0.13.1

**Comment by dulmarod** [comment]
I think this is already fixed in current master. You could try installing Infer's master version from source. There are instructions in https://github.com/facebook/infer/blob/master/INSTALL.md.

**Comment by revolter** [comment]
Any idea when the new version will be live on `brew`?

**Comment by dulmarod** [comment]
Don't know, that might take a while.
________________________________

**Comment by dulmarod** [comment]
|Another option is to turn off that checker with the option --no-liveness.

**Comment by jvillard** [comment]
I'll try to make a release soonish. In the meantime, since the issue discussed originally has been fixed in master, let's close it.
