### ISSUE TITLE
ERROR on installing infer 0.13.1

### ISSUE THREAD

**Issue by pnt4kor** [facebook/infer#874]
Hi,

I am facing an issue in installing **infer_v0.13.1** on UBUNTU 16.04. 
After executing **./build-infer.sh** Installation stops at 26%. I have noticed that complete **/tmp** directory space gets 100% occupied by infer installtion.  We have 1.8GB space on /tmp directory. Since we are installing infer on the VM we cannot increase the disk space on /tmp directory. 
Is there any argument that can be passed for infer to change the /tmp directory(**./build-infer.sh**)? or Is there any workaround to fix this issue..

Note : I followed [this ](https://github.com/facebook/infer/blob/8ce15caffb3c48787e3851b888264eee17bef47e/INSTALL.md#install-infer-from-source)page for infer installation.

I also tried installing **infer v0.13.0** on ubuntu 16.04
But i'm facing the following error
```
[ERROR] ppx_driver.v0.9.1 is not available because your system doesn't comply
        with **ocaml-version >= "4.03.0" & ocaml-version < "4.05.0"**.
Exception:
Reqs_error
 (Process_error
   ("opam install -y ANSITerminal.0.7 atd.1.12.0 atdgen.1.12.0 base.v0.9.3 bin_prot.v0.9.1 biniou.1.2.0 camlp4.4.05+1 camlzip.1.07 cmdliner.1.0.2 conf-aclocal.1.0.0 conf-autoconf.0.1 conf-m4.1 conf-pkg-config.1.0 conf-which.1 configurator.v0.9.1 core.v0.9.1 core_kernel.v0.9.0 cppo.1.6.0 cppo_ocamlbuild.1.6.0 ctypes.0.13.0 easy-format.1.3.0 extlib-compat.1.7.2 fieldslib.v0.9.0 integers.0.2.2 jane-street-headers.v0.9.0 javalib.2.3.4 jbuilder.1.0+beta14 menhir.20170712 mtime.1.1.0 num.0 ocaml-compiler-libs.v0.9.0 ocaml-migrate-parsetree.1.0.6 ocamlbuild.0.11.0 ocamlfind.1.7.3 octavius.1.1.0 ounit.2.0.5 parmap.1.0-rc8 ppx_assert.v0.9.0 ppx_ast.v0.9.1 ppx_base.v0.9.0 ppx_bench.v0.9.1 ppx_bin_prot.v0.9.0 ppx_compare.v0.9.0 ppx_core.v0.9.0 ppx_custom_printf.v0.9.0 ppx_derivers.1.0 ppx_deriving.4.2 ppx_driver.v0.9.1 ppx_enumerate.v0.9.0 ppx_expect.v0.9.0 ppx_fail.v0.9.0 ppx_fields_conv.v0.9.0 ppx_hash.v0.9.0 ppx_here.v0.9.1 ppx_inline_test.v0.9.2 ppx_jane.v0.9.0 ppx_js_style.v0.9.0 ppx_let.v0.9.0 ppx_metaquot.v0.9.0 ppx_optcomp.v0.9.0 ppx_optional.v0.9.0 ppx_pipebang.v0.9.0 ppx_sexp_conv.v0.9.0 ppx_sexp_message.v0.9.0 ppx_sexp_value.v0.9.0 ppx_tools.5.0+4.05.0 ppx_traverse.v0.9.0 ppx_traverse_builtins.v0.9.0 ppx_type_conv.v0.9.0 ppx_typerep_conv.v0.9.0 ppx_variants_conv.v0.9.0 re.1.7.1 result.1.2 sawja.1.5.2 sexplib.v0.9.2 spawn.v0.9.0 sqlite3.4.2.0 stdio.v0.9.0 topkg.0.9.0 typerep.v0.9.0 variantslib.v0.9.0 xmlm.1.3.0 yojson.1.4.0 --color=never",
   Unix.WEXITED 66)).

*** `install_opam_deps` failed
```
Has there been any changes in the latest infer version which explains why more /tmp directory space is used compared to previous version?

Thanks and Regards,
Prashanth

**Comment by jberdine** [comment]
13.1 should be trying to use  v0.10 of core and its deps, so I don't understand why v0.9.1 is involved. Is  opam up to date on your machine?

**Comment by pnt4kor** [comment]
yes opam is already updated! **1.2.2**
v13.0 is trying to use v0.9.1. But, I'm not facing this issue with **v0.13.1** instead I'm getting complete **/tmp** directory space gets 100% occupied by infer installation. We have 1.8GB space on /tmp directory. Since we are installing infer on the VM we cannot increase the disk space on /tmp directory.

Any suggestions for this issue?

**Comment by jvillard** [comment]
1.8GB seems insufficient space to install the opam dependencies. On my machine, the infer dependencies take up about 4GB (wow!).

Is the issue about /tmp specifically, i.e., is there some other directory you could use that has more space? If so, setting `TMPDIR` may help.

**Comment by TomMD** [comment]
I believe you can solve this problem by setting `CLANG_TMP_DIR` which is used by the clang setup script:

```
CLANG_TMP_DIR=/mnt/bigvolume/tmp ./build-infer.sh
```

If the opam library is the issue then you could also softlink that elsewhere.  Assuming you do not have an opam library or have moved it:

```
mkdir -p /mnt/bigvolume/.opam
ln -s /mnt/bigvolume/.opam $HOME/.opam
```

When I do these two things the disk space needed on my home and tmp volumes is negligible.

**Comment by jvillard** [comment]
Hopefully the suggestions here helped. Otherwise we now [publish binaries](https://github.com/facebook/infer/releases/latest) too, which have a smaller footprint. Feel free to reopen if infer takes up all your disk again.
