### ISSUE TITLE
Failed to connect to ocaml-extlib.googlecode.com port 443: Operation timed out

### ISSUE THREAD

**Issue by shenxianshu** [facebook/infer#875]
brew install infer  error.....

curl: (7) Failed to connect to ocaml-extlib.googlecode.com port 443: Operation timed out
Error: Failed to download resource "opam--extlib"
Download failed: https://ocaml-extlib.googlecode.com/files/extlib-1.5.3.tar.gz

how to solve this problem?

**Comment by jberdine** [comment]
I'm not sure why you're trying to get 1.5.3, but apparently the url is now http://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/ocaml-extlib/extlib-1.5.3.tar.gz. Looks like an update to the extlib package is needed.
