### ISSUE TITLE
Kotlin Gradle Build integration

### ISSUE THREAD

**Issue by sadhasivam** [facebook/infer#876]
Considering the popularity of Kotlin would be good to integrate `infer` with kotlin project gradle builds.

> Capturing in gradle mode...
Running and capturing gradle compilation...
Nothing to compile. Try running `gradle clean` first.

> Error backtrace:
Raised at file "integration/Driver.ml", line 310, characters 16-78
Called from file "integration/Driver.ml", line 184, characters 2-16
Called from file "backend/infer.ml", line 23, characters 2-36
Called from file "backend/infer.ml", line 112, characters 6-52
Uncaught error: ("InferModules__Driver.Infer_error(\"exited with code 66\")")

Run the command again with `--keep-going` to try and ignore this error.

**Comment by dulmarod** [comment]
Infer doesn't support Kotlin at the moment, only Java, C, C++ and Objective-C.
