### ISSUE TITLE
The Objective-C example(Hello.m) run with command ``infer run -- clang -c Hello.m`` failed

### ISSUE THREAD

**Issue by shiyy123** [facebook/infer#877]
I use the <infer-linux64-v0.13.1 release> version. 
And run ``./build-infer.sh`` and ``sudo make install`` in the Ubuntu 16.04.
The java, C, Android example run normally. However, when I run the Objective-C example I fails.
The error is shown as below.

ca@ca:/home/ca/Project/infer-linux64-v0.13.1/examples$ infer run -- clang -c Hello.m
Capturing in make/cc mode...
Hello.m:10:9: fatal error: 'Foundation/Foundation.h' file not found
#import <Foundation/Foundation.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Error: the following clang command did not run successfully:
  '/usr/local/lib/infer/facebook-clang-plugins/clang/install/bin/clang' "@/tmp/clang_command_.tmp.23464c.txt"

**Comment by dulmarod** [comment]
For Objective-C analysis to run you need to have Xcode installed, it also only works in MacOS. You can try running `clang -c Hello.m` and checking that it succeeds first.

**Comment by cyw3** [comment]
@dulmarod 
first, i use` clang -c Hello.m` and it succeeds.
but, when i use ` infer run -- clang -c Hello.m`, I occured the same error.

**Comment by cyw3** [comment]
And Which version of mac os infer support?

**Comment by dulmarod** [comment]
You said earlier you are using the <infer-linux64-v0.13.1 release> version. That may be the problem, iOS analysis is only supported in MacOS. We support XCode 9.2 version.

**Comment by cyw3** [comment]
My mac :
infer v0.13.0
Mac 10.13.2 (17C88)
XCode 9.2 

I think that maybe infer-v0.13.0/lib/infer/facebook-clang-plugins/clang cant not find the "Fundation.h" which is in the Xcode.

**Comment by jvillard** [comment]
@cyw3 can you open a separate issue for your problem? Thanks.

**Comment by jvillard** [comment]
Oh, I see there's already #842, nevermind.
