### ISSUE TITLE
error: DEAD_STORE ? what's this ?

### ISSUE THREAD

**Issue by shenxianshu** [facebook/infer#880]
```
  The value written to &__objc_anonymous_block_GifImageView_setImageData:______1 is never used.

  32.           float fDuration = [_arrayDurations[_indexGIF] floatValue];
  33.           __weak typeof(self) weakSelf = self;
  34. >         dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(fDuration * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
  35.               [weakSelf updateImageView];
  36.           });
```

**Comment by dulmarod** [comment]
This issue has already been fixed in current master. You can try to get the latest version and compile it from source.

**Comment by dflems** [comment]
Any chance a new release could be cut from the current master? It's quite cumbersome to build infer locally.

**Comment by dulmarod** [comment]
I'm not sure when a new release will be made, it may be a while.

**Comment by shenxianshu** [comment]
infer's version which i used now  is 0.13.1 .Which version has no problem now？i want to downgrade......

**Comment by dulmarod** [comment]
Older versions will have other false positives as we are always improving the tool. What you can do is turn off that checker by passing the option --no-liveness to Infer.
________________________________

**Comment by jvillard** [comment]
I'll try to make a release soonish. In the meantime, since the issue discussed originally has been fixed in master, let's close it.

@shenxianshu please consider using `--no-liveness` as suggested by @dulmarod in the meantime.
