### ISSUE TITLE
inferTraceBugs: command not found

### ISSUE THREAD

**Issue by crikapa7** [facebook/infer#881]
infer version 0.13.1
installed with brew on Mac

how can I solve this problem?

Thank you!

**Comment by jvillard** [comment]
`inferTraceBugs` is now built into infer as `infer explore ...`.

**Comment by crikapa7** [comment]
Thanks jvillard, but I would like to print the time of the inference. Neither with infer explore, nor with infer report I managed to do this. Do you know why?

**Comment by jvillard** [comment]
What do you mean by "time of the inference"?

**Comment by crikapa7** [comment]
I launched the command "infer run..", now i would like to print the time that infer use for analyze the file in input.

**Comment by jvillard** [comment]
Is `time infer run ...` what you're after? If you want to separate the capture and analysis time, you can use `time infer capture ...` then `time infer analyze`.

**Comment by crikapa7** [comment]
Amazing! Finally it worked. Thanks jvillard, sorry for the silly question, but neither on the man nor in the user guide on fbinfer website there was this kind of command. Thank you again.
