### ISSUE TITLE
how to filter bug type: DEAD_STORE 

### ISSUE THREAD

**Issue by crespoxiao** [facebook/infer#882]
I run the command to get the analysis result:

`
LD=/usr/bin/true infer run --keep-going --no-xcpretty -- xcodebuild -workspace RetailHD.xcworkspace -scheme RetailHD -configuration Debug -sdk iphonesimulator
`

then generate html file by command:
`
infer explore --html
`

but the problem is there are so many DEAD_STORE.

eg: /job/normandy-ios/RetailModules/RetailCommon/RetailCommon/Utils/Category/PHImageManager+DownloadImage.m:16: error: DEAD_STORE The value written to &__assert_file__ is never used. (trace)

so my question is how to filter this kind of bug when analysis ?

**Comment by mbouaziz** [comment]
In your `.inferconfig` file, you can have a list of issues you want to hide
```
{
  "disable-issue-type": [
    "DEAD_STORE"
  ]
}
```
In this particular case, you can also completely disable the analyzer that reports this issue (because it reports only this issue):
```
{
  "liveness": false
}
```
Give it a try and let me know how it went. Reopen the issue if needed.

**Comment by crespoxiao** [comment]
@mbouaziz   thank you. it works !
