### ISSUE TITLE
inferconfig blacklist doesn't work with symlinks

### ISSUE THREAD

**Issue by crespoxiao** [facebook/infer#883]
![snap](https://user-images.githubusercontent.com/1168793/37811437-39be959c-2e95-11e8-8718-c283b922478b.png)

The Pods in my project folder is a virtual link. when I run the following command the html file contains many bug in Pods.

`
LD=/usr/bin/true infer run --keep-going --no-xcpretty -- xcodebuild -workspace RetailHD.xcworkspace -scheme RetailHD -configuration Debug -sdk iphonesimulator
&& infer explore --html
`

inside html: 
......
/job/normandy-ios/RetailModules/RetailCommon/Pods/AvengersPatcher/AvengersPatcher/ZanPatch/Extensions/ZanPatchNumber.m:79: error: DEAD_STORE The value written to &__objc_anonymous_block_ZanPatchNumber_main:______1 is never used. (trace)
/job/normandy-ios/RetailModules/RetailCommon/Pods/AvengersPatcher/AvengersPatcher/ZanPatch/Extensions/ZanPatchNumber.m:69: error: DEAD_STORE The value written to &__objc_anonymous_block_ZanPatchNumber_main:______2 is never used. (trace)
......

how to fix it ? any solution ? thank you.

**Comment by mbouaziz** [comment]
Thanks for reporting!
We'll investigate how to deal with symbolic links.

**Comment by jvillard** [comment]
I'm not sure the problem is with symlinks here, as the .inferconfig contains both the symlink and its target. It could be that the filtering tries to match `../RetailModules` and fails to realise that it's the same as `/job/normandy-os/RetailModules`.

@crespoxiao what about the following .inferconfig?

```
{
  "skip-analysis-in-path": [
    ".*/RetailModules/RetailCommon/Pods/"
  ]
}
```

Also, I'm not even sure why infer reports in the first place since these files live outside the project root...

**Comment by crespoxiao** [comment]
@jvillard 

well, thanks to the lib [nokogiri ](https://github.com/sparklemotion/nokogiri ).


here is the code.
`
#! /usr/bin/env ruby

require 'nokogiri'
require 'open-uri'

# Fetch and parse HTML document
doc = Nokogiri::HTML(open('index.html'))

# Filter Pods
puts "### Search for nodes by xpath"
$bugs = Array.new
doc.xpath('//li').each do |link|
    con = link.content
    if !(con.include? "Pods") then $bugs.push(link) end
end

$bugCount = $bugs.size

# Concat usefull bugs
$links = ""
$bugs.each { |item|
$links.concat(item.to_s)
}


# Save the HTML File
newhtml = "<html>\
<head>\
<title>Infer found #$bugCount bugs</title>\
</head>\
<body>\
<h2>List of bugs found</h2>\
<ol>\
#$links \
</ol>\
</body>\
</html>"

if File.exist?('index.html') then File.delete("index.html") end

aFile = File.new("index.html", "w")
if aFile
    aFile.syswrite(newhtml)
else
    puts "Unable to open file!"
end
`
