### ISSUE TITLE
ERROR: `install_opam_deps` failed

### ISSUE THREAD

**Issue by caolongSY** [facebook/infer#884]
install on MacOSX,run ./build-infer.sh. 
<img width="874" alt="default" src="https://user-images.githubusercontent.com/7218624/37895140-0590c59e-3113-11e8-8361-87d38f133dc3.png">

Where are the problems? thanks...

**Comment by Anurag--Singh** [comment]
I am facing exactly the same issue.

**Comment by jvillard** [comment]
Sorry for the late reply, the issue hee seems to be that `aclocal` is not installed. You need to make sure to install the dependencies listed in [`INSTALL.md`](https://github.com/facebook/infer/blob/master/INSTALL.md). In this case `autoconf` is missing: `brew install autoconf` should fix it. Feel free to reopen if there is still an issue.
