### ISSUE TITLE
Starting translating and failed in iOS

### ISSUE THREAD

**Issue by yalechen-cyw3** [facebook/infer#886]
![image](https://user-images.githubusercontent.com/34886223/37943739-63d90b96-31ab-11e8-993c-d27865248f05.png)

* What is this problem's reason???
* How to fix it?
* What is the theory of infer-Xcodebuild-capture?

I have seen the issue #824 , but I still have the problem:

I use infer-v0.13.0

1. if "xcodebuild -scheme appName -configuration Debug -sdk iphonesimulator", it build success.

2. when "infer run --keep-going  -- xcodebuild -scheme appName -configuration Debug -sdk iphonesimulator",  it occured:
error: error reading '/Users//Library/Developer/Xcode/DerivedData/*****/Index/DataStore'
1 error generated.
1 error generated.
1 error generated.
1 error generated.
ERROR RUNNING CAPTURE: Bi_inbuf.End_of_input
Raised at file "src/bi_inbuf.ml", line 49, characters 6-24
Called from file "src/bi_io.ml" (inlined), line 508, characters 12-35
Called from file "atd/clang_ast_b.ml", line 27505, characters 7-24
Called from file "clang/Capture.ml", line 48, characters 8-39
Called from file "clang/Capture.ml" (inlined), line 93, characters 6-35
Called from file "clang/Capture.ml", line 157, characters 26-73

![image](https://user-images.githubusercontent.com/34886223/37943739-63d90b96-31ab-11e8-993c-d27865248f05.png)

3. When "infer run --keep-going --no-xcpretty -- xcodebuild -scheme appName -configuration Debug -sdk iphonesimulator":
![image](https://user-images.githubusercontent.com/34886223/37970627-864b41ac-3206-11e8-82ca-b9c350a671c2.png)

The following build commands failed:
  CompileC /Users/xxx/Library/Developer/Xcode/DerivedData/xxxx-cmuboqhfjnurcceqlcbulpmrnvip/Build/Intermediates.noindex/protobuff.build/Debug-iphonesimulator/protobuf-lite.build/Objects-normal/i386/extension_set.o src/google/protobuf/extension_set.cc normal i386 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Error backtrace:
Raised at file "integration/Driver.ml", line 297, characters 16-78
Called from file "integration/Driver.ml", line 176, characters 2-16
Called from file "backend/infer.ml", line 23, characters 2-36
Called from file "backend/infer.ml", line 106, characters 6-52
Uncaught error: ("InferModules__Driver.Infer_error(\"exited with code 65\")")

4. when "LD=/usr/bin/true infer run --keep-going --no-xcpretty -- xcodebuild -scheme appName -configuration Debug -sdk iphonesimulator" after clean,

![image](https://user-images.githubusercontent.com/34886223/37944027-a80f05da-31ac-11e8-8854-9a10a6af608c.png)

and the content of the sh file is:
![image](https://user-images.githubusercontent.com/34886223/37944038-b1ee5362-31ac-11e8-99d9-c4202d7d19bb.png)

**Comment by cyw3** [comment]
@jvillard @dulmarod

**Comment by dleyanlin** [comment]
same issue

**Comment by cyw3** [comment]
@jvillard Now, it is ok.

**Comment by jvillard** [comment]
From the errors you pasted it looks like the version of clang that infer was using was too old. Infer now ships with a recent version of clang-7. Sorry it took so long to reply. Thanks for trying again and reporting back!
