### ISSUE TITLE
Is it possible to analyze a single java class from android studio project using infer run -- javac Hello.java?

### ISSUE THREAD

**Issue by hallz11** [facebook/infer#889]
Hi, I want to test only single class from my android studio project. Can I do that using infer command?
I got an error when I tried this command infer run -- javac app/.../Hello.java
This is the error message: 
Usage Error: 
*** Failed to execute compilation command: exited with code 1
*** Command: 'javac' '@/var/folders/m4/4ff_4bsn0vl849rgtwmdty7c0000gn/T/args_.tmp.a75c24'
*** Output:
[parsing started RegularFileObject[TestInfer.java]]
[parsing completed 15ms]
[search path for source files: .]
........
*** Infer needs a working compilation command to run.

Is it possible? Thank you.

**Comment by jvillard** [comment]
You need to find a command that works for compiling that single file. In your case I suspect `javac app/../Hello.java` fails.

**Comment by jvillard** [comment]
Hope that answers your question, closing.
