### ISSUE TITLE
Infer analysis is broken (misses bugs) or behavior has changed

### ISSUE THREAD

**Issue by TomMD** [facebook/infer#891]
N.B. using a recent build (7c7b239248f16ed7d16a2431a2f61d877b87cb8e) on Ubuntu.

Following the instructions for CI workflow (http://fbinfer.com/docs/steps-for-ci.html):

Get the code.

```
git clone https://github.com/TomMD/SoundRecorder.git
cd SoundRecorder
```

Get the changed files

```
git diff --name-only b5769eb..dfe1e1c > index.txt
```

Run infer on the feature branch

```
git checkout b5769eb
infer capture --reactive -- ./gradlew build
infer analyze --reactive --changed-files-index index.txt
cp infer-out/report.json ./feature-report.json
```

Run infer on the master branch

```
git checkout dfe1e1c
infer capture --reactive -- ./gradlew build
infer analyze --reactive --changed-files-index index.txt
```

And the files are identical (different run here so there are different file names in copy/paste):

```
$ md5sum src.json infer-out/report.json
ed70cdc5b286b721e33cc00d30eca027  src.json
ed70cdc5b286b721e33cc00d30eca027  infer-out/report.json
```

If we clean things, `rm -rf infer-out ; ./gradlew clean` then re-run things improve:

```
rm -rf infer-out
./gradlew clean
infer capture --reactive -- ./gradlew build
infer analyze --reactive --changed-files-index index.txt
infer reportdiff --report-current src.json --report-previous infer-out/report.json
wc -l infer-out/differential/fixed.json
~~> 28409 infer-out/differential/fixed.json
```

It does not appear that doing only one of the two (either removing infer-out or `./gradlew clean`) suffices, both are necessary.

**Comment by sblackshear** [comment]
(sorry for taking so long to get to this)

I believe this behavior is as expected. If `infer-out` exists, Infer will use it as a local cache (and re-analysis won't happen). If `gradle clean` isn't run, Gradle may not rebuild enough code to force Infer to re-analyze in a way that changes the results.

I'm not if the use of `--reactive` is supposed to change this behavior, though. @jvillard might know?

**Comment by TomMD** [comment]
Should I close this then, @sblackshear  @jvillard ?  It strikes me as an odd desired behavior - infer willing to use specs generated from old code - but one I can certainly handle.

**Comment by jvillard** [comment]
Yes this is intended behaviour. To get correct results across arbitrary code changes the only way is to run two full analyses since infer relies only on what is captured by the build system. In particular it won't noticed files that get deleted.
