### ISSUE TITLE
How to activate bufferoverrun checker (inferbo) 

### ISSUE THREAD

**Issue by gunjanaggarwal** [facebook/infer#893]
Hello,

I just read the blog on [inferbo](https://research.fb.com/inferbo-infer-based-buffer-overrun-analyzer/) and tried executing infer on the examples mentioned in the blog. But, Infer doesn't report any buffer overrun error. 
Following are the details:

I installed infer using docker. 
```
root@3ffffbcd94b9:/examples# infer --version
Infer version v0.13.1
Copyright 2009 - present Facebook. All Rights Reserved.
```

Created following C program:
```
root@3ffffbcd94b9:/examples# cat fb_buffer_overrun2.c 
#include <stdlib.h>

void set_i(int *arr, int index) {
    arr[index] = 0;
}

char * malloc_wrapper(int n) {
 return malloc(n);
}

void interprocedural() {
 int *arr = malloc_wrapper(9*sizeof(int)); 
 if (arr != NULL){
   int i;
   for (i = 0; i < 9; i+=1) {
     set_i(arr, i); // safe
     set_i(arr, i + 1); // alarm
   }
  }
}

int main( int argc, const char* argv[] )
{
  interprocedural();
  return 0;
}
``` 
And executed following commands:

```
root@3ffffbcd94b9:/examples# infer --compute-analytics --bufferoverrun --biabduction -- gcc fb_buffer_overrun2.c
Capturing in make/cc mode...
Found 1 source file to analyze in /examples/infer-out
Starting analysis...

legend:
  "F" analyzing a file
  "." analyzing a procedure

F....

  No issues found  
```

```
root@3ffffbcd94b9:/examples# infer -- gcc fb_buffer_overrun2.c
Capturing in make/cc mode...
Found 1 source file to analyze in /examples/infer-out
Starting analysis...

legend:
  "F" analyzing a file
  "." analyzing a procedure

F....

  No issues found  
```

Can you please suggest how to activate bufferoverrun checker?

Thanks,
Gunjan

**Comment by skcho** [comment]
The `--bufferoverrun` option activates the bufferoverrun checker as you did.

Unfortunately, there are some issues of dealing with type castings in the current Inferbo. (we are working on them) As of now, changing the array assignment to `int *arr = (int*)malloc(9*sizeof(int));` would raise a bufferoverrun issue. 😅

**Comment by gunjanaggarwal** [comment]
@skcho, thanks for the reply. Buffer-overrun error is reported after changing the assignment as you suggested.

**Comment by mbouaziz** [comment]
Please keep in mind that Inferbo is still experimental
