### ISSUE TITLE
CFG infos

### ISSUE THREAD

**Issue by crikapa7** [facebook/infer#896]
How to get main infos about Control Flow Graph? Especially nodes and edges numbers

**Comment by ezgicicek** [comment]
Hi,
In the directory where you run infer, CFG will be output to `infer-out/captured/$test_file/icfg.dot` where $test_file is the name of the file you run infer on.

**Comment by crikapa7** [comment]
I asked for the details/stats of the CFG, not for the CFG itself. However, no matter, i solved the problem in another way.

**Comment by j3rry0610** [comment]
> infer-out/captured/$test_file/icfg.dot

Could you kindly tell me how you get the control flow graph by infer?
