### ISSUE TITLE
Support xctool as a build tool

### ISSUE THREAD

**Issue by loufranco** [facebook/infer#9]
I tried adding it myself, but I am running into the `@import` issue reported elsewhere.

**Comment by triage** [comment]
this sounds like the better option... I certainly see why they specifically excluded options not supported by the open source compiler, but Infer is basically unusable to most of us using xcode and `@import`

**Comment by loufranco** [comment]
xctool still uses clang -- which needs their plugin, which enabled by the open source clang, so ... still won't work unfortunately.

I got pretty far adding xctool myself, but was stopped by the `-fmodules` issue

**Comment by wzpan** [comment]
+1 . xctool is better than xcodebuild.

**Comment by irpap** [comment]
Thanks for reporting this. I think this should be doable, we'll take a look.

**Comment by Githubcatadmin** [comment]
Ye

**Comment by jvillard** [comment]
@loufranco FYI the `@import` issue has been fixed in the latest version of Infer (v0.1.1).

**Comment by skyuplam** [comment]
+1

**Comment by xilin** [comment]
+1

**Comment by daneov** [comment]
+1

**Comment by daneov** [comment]
Workaround
--- 

### Generate a json compilation database
If you add the [following parameter](http://oclint-docs.readthedocs.io/en/stable/guide/xctool.html#running-xctool-with-json-compilation-database-reporter) to 
* `xctool`: `-reporter json-compilation-database:compile_commands.json` 
* `xcpretty`:  `-r json-compilation-database -o compile_commands.json`

#### This'll enable you to use one of the following commands: 
Depending on how you generate this file you use one of the following options:
*  `xcpretty` and `xctool`: `--clang-compilation-db-files-escaped` 
    * reason: the files in the json are escaped : 'file\\ with\\ spaces'
* `cmake`: `--json-compilation-database`

Granted, it'd be a 2 step process, but it'll work 👍 

**NB** Commonly, the build output will be stored in a file called 'xcodebuild.log'. If you need a different reporter for e.g. your test, you can still do that, generate the `compile_commands.json` using that log file, and launch infer using that generated `compile_commands.json`

Concretely:
1. `xctool.sh --<whatever parameters you need>` or `xcodebuild --<whatever parameters> | tee xcodebuild.log | xcpretty -r junit -o junit.xml` as usual
2. `cat xcodebuild.log | xcpretty -r json-compilation-database -o compile_commands.json &> /dev/null`
    * the last part pipes the output  to `/dev/null`, as otherwise it'd be displayed on screen again, convoluting your build log.
3. `infer --skip-analysis-in-path Pods --json-compilation-database compile_commands.json`

**Comment by jvillard** [comment]
Closing as the compilation database approach is the best option there. This workflow has been documented on [the infer website](http://fbinfer.com/docs/analyzing-apps-or-projects.html).

**Comment by lichanghong** [comment]
bash-3.2$ infer run --skip-analysis-in-path Pods --compilation-database-escaped compile_commands.json
Capturing using compilation database...
Starting translating and linting 45 files
error: error reading '/Users/ziroom/Library/Developer/Xcode/DerivedData/Example-ghajruwcoslwhscqfuynkquodwys/Index/DataStore'
error: error reading '/Users/ziroom/Library/Developer/Xcode/DerivedData/Example-ghajruwcoslwhscqfuynkquodwys/Index/DataStore'
error: error reading '/Users/ziroom/Library/Developer/Xcode/DerivedData/Example-ghajruwcoslwhscqfuynkquodwys/Index/DataStore'
1 error generated.
1 error generated.
error: error reading '/Users/ziroom/Library/Developer/Xcode/DerivedData/Example-ghajruwcoslwhscqfuynkquodwys/Index/DataStore'
1 error generated.
1 error generated.
Uncaught Internal Error: (Bi_inbuf.End_of_input)
Error backtrace:
Raised at file "src/bi_inbuf.ml", line 49, characters 6-24
Called from file "src/bi_io.ml" (inlined), line 508, characters 12-35
Called from file "atd/clang_ast_b.ml", line 27643, characters 7-24
Called from file "clang/Capture.ml", line 56, characters 8-39
Called from file "clang/Capture.ml" (inlined), line 101, characters 6-35
Called from file "clang/Capture.ml", line 170, characters 26-73
Re-raised at file "istd/IExn.ml" (inlined), line 18, characters 15-63
Called from file "clang/Capture.ml" (inlined), line 102, characters 4-60
