### ISSUE TITLE
Fails to detect some linked lists in C code

### ISSUE THREAD

**Issue by bacam** [facebook/infer#90]
When analysing some simple linked list C code I found that infer would either fail to generate any specs for some functions, or would only provide specs for short, fixed-length lists.  After some debugging, I found that the backend sometimes fails to detect recursive fields in `struct`s because the type comparison relies on the fields in the struct type having the same order.  The clang frontend produces `struct` types with the fields in the declared order, but parts of the backend sort them and `sil.mli` says they should always be sorted.

For example, in the following code

    struct l1 {
      int a;
      struct l1 *b;
    };

    int add1(struct l1 *l) {
      int r =0;
      for (; l; l=l->b) {
        r += l->a;
      }
      return r;
    }

    struct l2 {
      int b;
      struct l2 *a;
    };

    int add2(struct l2 *l) {
      int r =0;
      for (; l; l=l->a) {
        r += l->b;
      }
      return r;
    }
I get specs for `add1` where the fields are in alphabetical order, but not for `add2`.

**Comment by dulmarod** [comment]
Hi Bryan, 
thanks so much for reporting this issue. Yes, it seems that the frontend is not sorting the fields and it should. I'll work on it.
