### ISSUE TITLE
Can I pass inferconfig file location as parameter?

### ISSUE THREAD

**Issue by OzanAlpay** [facebook/infer#900]
Hi,

First of all thanks a lot for your effort for building this great static-analyzer.

My question is, is there a way to pass inferconfig file location as a parameter from command line, for example infer capture --inferconfig=home/x/y -- make. Then infer will use given inferconfig file for its capture phase.

I looked at infer --help and try to read some source code , but couldn't find an argument that matches to my need.

Thanks in advance

**Comment by jvillard** [comment]
For the record, you can control where infer looks for ".inferconfig" with the `INFERCONFIG` environment variable: `INFERCONFIG="/some/file" infer ...`.
