### ISSUE TITLE
Infer site broken over HTTPS

### ISSUE THREAD

**Issue by Daniel15** [facebook/infer#903]
GitHub now support HTTPS for custom domains (see https://blog.github.com/2018-05-01-github-pages-custom-domains-https/).

Currently, the Infer site is broken over HTTPS, as all the URLs in the HTML appear to be hard-coded to use "http://": https://fbinfer.com

I'd suggest changing everything to use HTTPS, and then enable the "Enforce HTTPS" option in the GitHub settings.

**Comment by jeremydubreil** [comment]
Thanks @Daniel15 for reporting this.

**Comment by Daniel15** [comment]
Awesome! This looks fixed, however HTTPS is still not enforced. We're trying to enforce HTTPS across all Facebook sites. @jeremydubreil or @theopolis would you please be able to enable "Enforce HTTPS" in the repo settings?

**Comment by theopolis** [comment]
I’ll create a task for the Open Source team oncall. We don’t have admin access to the repo to enable enforce.
