### ISSUE TITLE
Not working with CMake and make

### ISSUE THREAD

**Issue by tcullum-gpsw** [facebook/infer#909]
There's something wrong with my infer trying to work with CMake/make.

I've read the previous issue where a solution is to use something like:

`CC=/usr/local/lib/infer/infer/lib/wrappers/clang cmake .`

Followed by `infer -- make`

also did `make clean` in between tries...

Also did `infer -- cmake` in the dir.

Every single time I get the same message:
```
Nothing to compile. Try running `make clean` first.
There was nothing to analyze.


  No issues found
```

Same result. Also tried make clean in between steps.

infer works when I use it directly with a compiler like `infer -- gcc mysource.c -o mysource -g`

However, it does not work with build tools. I'm working on a medium sized codebase with 9 or so libraries.

Infer version v0.13.1
cmake version 3.11.1
GNU Make 3.81
Apple LLVM version 9.0.0 (clang-900.0.39.2)

**Comment by jeremydubreil** [comment]
@tcullum-gpsw, did you try also specifying the project root?

It may be that the paths of the source files manipulated by the `cmake` command are not relative the to the directory `infer` is run from.

**Comment by tcullum-gpsw** [comment]
@jeremydubreil thanks, I think you are onto something..

I tried `infer -- cmake /full/path/to/CMakeLists.txt` and that worked.

However, I then had to do `infer -- make -C /full/path/to/makefile` and it seemed to work at first, but then errored out with the same issue [mentioned here.](https://github.com/facebook/infer/issues/839) which is:
```
Error backtrace:
Raised at file "base/Die.ml" (inlined), line 25, characters 6-36
Called from file "base/Logging.ml", line 281, characters 58-80
Called from file "backend/infer.ml", line 23, characters 2-36
Called from file "backend/infer.ml", line 112, characters 6-52
External Error: *** capture command failed:
*** make -C /Users/me/projects/myproject
*** exited with code 2
```

**Comment by jvillard** [comment]
There are two ways to integrate infer with cmake projects.

1. Use `cmake` as normal, with a twist:
```
mkdir build && cd build
infer compile -- cmake ..
infer capture -- make
```

2. Have `cmake` generate a compilation database:
```
mkdir build && cd build
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 ..
infer capture --compilation-database compile_commands.json
```

(These two scenarios are well hidden in the help of `infer-compile` :/ `infer compile --help`)

Does any of these work for you? You may need to pass `--project-root ..` to infer too. Let me know what worked for you.

**Comment by tcullum-gpsw** [comment]
@jvillard ho boy, I just tried both and the first one gave the same error as earlier, the second option threw me into an infite loop of these types of errors:

```
7 errors generated.
Error: the following clang command did not run successfully:
  '/usr/local/Cellar/infer/0.13.1/lib/infer/facebook-clang-plugins/clang/install/bin/clang++' "@/var/folders/vm/krq3n7ws1wq1h9hnny85c6psfkb2wf/T/clang_command_.tmp.a82e52.txt"

!In file included from /Users/tcullum/projects/gpr/source/lib/xmp_core/XMPUtils-FileInfo.cpp:9:
In file included from /usr/local/Cellar/infer/0.13.1/lib/infer/facebook-clang-plugins/clang/install/include/c++/v1/algorithm:640:
In file included from /usr/local/Cellar/infer/0.13.1/lib/infer/infer/models/cpp/include/memory:15:
/usr/local/Cellar/infer/0.13.1/lib/infer/facebook-clang-plugins/clang/install/include/c++/v1/memory:5531:50: error: unknown type name 'memory_order'
atomic_load_explicit(const shared_ptr<_Tp>* __p, memory_order)
                                                 ^
/usr/local/Cellar/infer/0.13.1/lib/infer/facebook-clang-plugins/clang/install/include/c++/v1/memory:5549:66: error: unknown type name 'memory_order'
atomic_store_explicit(shared_ptr<_Tp>* __p, shared_ptr<_Tp> __r, memory_order)
                                                                 ^
/usr/local/Cellar/infer/0.13.1/lib/infer/facebook-clang-plugins/clang/install/include/c++/v1/memory:5568:69: error: unknown type name 'memory_order'
atomic_exchange_explicit(shared_ptr<_Tp>* __p, shared_ptr<_Tp> __r, memory_order)
                                                                    ^
/usr/local/Cellar/infer/0.13.1/lib/infer/facebook-clang-plugins/clang/install/include/c++/v1/memory:5605:62: error: C++ requires a type specifier for all declarations
                                        shared_ptr<_Tp> __w, memory_order, memory_order)
                                                             ^
/usr/local/Cellar/infer/0.13.1/lib/infer/facebook-clang-plugins/clang/install/include/c++/v1/memory:5605:76: error: unknown type name 'memory_order'
                                        shared_ptr<_Tp> __w, memory_order, memory_order)
                                                                           ^
/usr/local/Cellar/infer/0.13.1/lib/infer/facebook-clang-plugins/clang/install/include/c++/v1/memory:5614:60: error: C++ requires a type specifier for all declarations
                                      shared_ptr<_Tp> __w, memory_order, memory_order)
                                                           ^
/usr/local/Cellar/infer/0.13.1/lib/infer/facebook-clang-plugins/clang/install/include/c++/v1/memory:5614:74: error: unknown type name 'memory_order'
                                      shared_ptr<_Tp> __w, memory_order, memory_order)
```



I'm going to keep trying a few things and let you know if I can get it to work with these commands or not. Thanks.

**Comment by tcullum-gpsw** [comment]
Still no luck. Also tried specifying gcc and gcc++ to CMake instead of Clang to test a different compiler.


Question. Is [this information](https://github.com/facebook/infer/issues/50) still valid?

**Comment by jeremydubreil** [comment]
Another thing to try is compile the project using the version of Clang shipped with Infer, but without using Infer at all. Something like:
```
export PATH=/usr/local/Cellar/infer/0.13.1/lib/infer/facebook-clang-plugins/clang/install/bin:$PATH
cmake
```
The goal is to make sure the project compiles with Clang 7 in the first place.

**Comment by jvillard** [comment]
@jeremydubreil this is not clang7 but an older clang (infer 0.13.1 from Homebrew). It might be that upgrading to the latest infer would solve this issue once https://github.com/Homebrew/homebrew-core/pull/27263 is resolved.

@tcullum-gpsw can you share the contents of an argument file that fails? For instance in your post above the contents of /var/folders/vm/krq3n7ws1wq1h9hnny85c6psfkb2wf/T/clang_command_.tmp.a82e52.txt would be helpful. `memory_order` is plain C++11 so should be supported by clang (even the one from infer 0.13.1).

**Comment by tcullum-gpsw** [comment]
@jvillard 

I still need to reproduce that exact error, I was able to get past that but now just showing no issues at all again.

But I have a question for you. Is the infer clang it's completely own separate stand-alone compiler or is it relying on AppleClang in some fashion? The reason I ask is because I had recently been having some problems with other static analyzers and it ended up being because Mac defaults to "AppleClang" even when the "gcc" or "g++" commands are issued. Does Infer support "AppleClang" or do I need to get another version of Clang to start with?

**Comment by jvillard** [comment]
Infer's clang is the open-source version of clang, pinned at some particular revision: https://github.com/facebook/facebook-clang-plugins/blob/master/clang/src/checksums.txt

**Comment by jvillard** [comment]
I think upgrading infer to the latest version should fix this issue: the problem was that the clang in infer was too old in 0.13.1 and there's a newer one in 0.15.0. Please re-open if there is still an issue.

**Comment by tcullum-gpsw** [comment]
@jvillard I can confirm that cmake will work with infer now with 0.15.0 . I used this method:

`cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1`
`infer run --compilation-database compile_commands.json`

**Comment by jvillard** [comment]
Thanks for reporting back @tcullum-gpsw!
