### ISSUE TITLE
Easy install from npm

### ISSUE THREAD

**Issue by sindresorhus** [facebook/infer#91]
I made a binary wrapper that makes it installable from npm and runnable in one line:

```
$ npm i -g infer-bin && infer
```

https://github.com/sindresorhus/infer-bin

This lowers the time from discovering Infer to having it running in your terminal.

You might find it useful :)

-

I previously [did the same](https://github.com/sindresorhus/flow-bin) for Flow and it's used by a lot of people.

-

Just wanted to let you know in you case you wanted to document it somewhere. Feel free to close.

**Comment by mokagio** [comment]
Nice one :+1: although I prefer the Homebrew way, see https://github.com/facebook/infer/issues/36

**Comment by sindresorhus** [comment]
> Nice one :+1: although I prefer the Homebrew way, see #36.

Yup, that's a good solution too, but this is available *now*. I would also bet there are more people on Node.js than Homebrew because a lot of popular front-end tools are built on Node.js. Choice doesn't hurt either.

> does your nmp install work on both OS X and Linux

Yes. It works on any Node.js supported platform (meaning most, including Windows), but only binaries for OS X and Linux are officially available for now, so it's limited to those platforms.

**Comment by mokagio** [comment]
Thanks for your answer. Good stuff 😊:beers:

**Comment by sblackshear** [comment]
Cool, thanks!
