### ISSUE TITLE
False Alarm - ERADICATE_NULL_METHOD_CALL

### ISSUE THREAD

**Issue by mohammed-safiq** [facebook/infer#910]
In class1.java, I have a local member:

```
@Nullable
private List<T> mObjList;
```

and a method,

```
private T getFoo()
{
return class2.notEmpty(mObjList) ? mObjList.get() : null;
}
```

In class2.java, I have a util method,

```
public static boolean notEmpty(@Nullable List<T> list)
{
return list != null && !list.isEmpty();
}
```

But the problem is, eventhough I call notEmpty() in getFoo() method which checks for null internally, i am getting the call to .. .get() could be null error. But when i convert the getFoo() to as follows, i am not getting this error. 
 
```
private T getFoo()
{
return mObjList != null && !mObjList.isEmpty() ? mObjList.get() : null;
} 
```

What could be the problem here???

Immediate help is highly appreciated.

**Comment by jeremydubreil** [comment]
Hi @mohammed-safiq, in that case, you can annotate `notEmpty` with `@FalseOnNull` to add the contract that `notEmpty` will return `false` when the parameter is `null`.

Example: https://github.com/facebook/infer/blob/master/infer/tests/codetoanalyze/java/eradicate/CustomAnnotations.java#L31

**Comment by mohammed-safiq** [comment]
Thanks it worked.
