### ISSUE TITLE
 infer-linux64-v0.14.0 build error in Ubuntu 16.04.3

### ISSUE THREAD

**Issue by acekingke** [facebook/infer#919]
I use vmware machine to build the infer-linux64-v0.14.0
$ cat /etc/issue
Ubuntu 16.04.3 LTS \n \l

run as
`./build-infer.sh`
 
[*ERROR**][47539] *** ERROR 'Building native(opt) Infer'

[*ERROR**][47539] File "atd/clang_ast_j.ml", line 1:
[*ERROR**][47539] Error: I/O error: as -o 'atd/.InferGenerated.objs/InferGenerated__Clang_ast_j.o' '/tmp/camlasm02a83c.s': Cannot allocate memory
[*ERROR**][47539] make[1]: *** [_build/opt/infer.exe] Error 1
Makefile:172: recipe for target 'src_build' failed

**Comment by jvillard** [comment]
See #914, which looks similar. It looks like you're running out of memory. In particular you can try the workaround suggested [here](https://github.com/facebook/infer/issues/914#issuecomment-387678785).
