### ISSUE TITLE
`make uninstall` deletes too much

### ISSUE THREAD

**Issue by TomMD** [facebook/infer#920]
The uninstall target in `Makefile` has a line:

    $(REMOVE) $(DESTDIR)$(bindir)/infer*

Which results in non-infer binaries being deleted from my system.  I suggest we tighten that up using an explicit list of binaries installed by infer.

**Comment by TomMD** [comment]
It isn't that DESTDIR is incorrect, assuming "correct" is `/usr/local/bin`.  I can give you a concrete example:

```
tommd@ubuntu1604-xenial tommd/infer% sudo touch /usr/local/bin/infer-thing
[sudo] password for tommd:
tommd@ubuntu1604-xenial tommd/infer% sudo make uninstall
rm -rf /usr/local/lib/infer/
rm -f /usr/local/bin/infer*
rm -f /usr/local/bin/infer-analyze /usr/local/bin/infer-capture /usr/local/bin/infer-compile /usr/local/bin/infer-explore /usr/local/bin/infer-report /usr/local/bin/infer-reportdiff /usr/local/bin/infer-run
rm -f  /usr/local/share/man/man1/infer-analyze.1.gz  /usr/local/share/man/man1/infer-capture.1.gz  /usr/local/share/man/man1/infer-compile.1.gz  /usr/local/share/man/man1/infer-explore.1.gz  /usr/local/share/man/man1/infer-report.1.gz  /usr/local/share/man/man1/infer-reportdiff.1.gz  /usr/local/share/man/man1/infer-run.1.gz  /usr/local/share/man/man1/infer.1.gz
tommd@ubuntu1604-xenial tommd/infer% ls -l /usr/local/bin/infer-thing
ls: cannot access '/usr/local/bin/infer-thing': No such file or directory
```

I have a binary with a name prefixed with `infer`, much as the `infer-thing` appears above.  It wasn't much of an issue for me either when I discovered it or moving forward now that I'm aware of this quirk, but I expect it could cause someone else a headache.

**Comment by jeremydubreil** [comment]
Yes, this isn't safe. We should store the list of binaries created and only remove the binaries from this list.

**Comment by jvillard** [comment]
FYI that list exists already: https://github.com/facebook/infer/blob/cac08598a027e689580705df97f85ef61c912c6b/Makefile.config#L58-L66

We should definitely fix this instance, but more generally I wonder how we can ensure that `make uninstall` never deletes too much, and doesn't leave files around either.
