### ISSUE TITLE
Bug types reported by experimental checkers

### ISSUE THREAD

**Issue by phillip-elliott** [facebook/infer#921]
Is there a list of all possible bug types reported by the experimental checkers listed on http://fbinfer.com/docs/experimental-checkers.html

**Comment by jeremydubreil** [comment]
Hi @phillip-elliott. The Infer help documentation for the `--disable-issue-type` and `--report-issue-type` command line option provides the list of available bug types that can be reported by Infer.

**Comment by phillip-elliott** [comment]
Thanks. I was able to find `--disable-issue-type` but I can't find any information about `--report-issue-type`.
I'm using the latest release version.

**Comment by phillip-elliott** [comment]
In #853 it's mentioned that most of the issue types get filtered out. Does the `--no-filtering,-F` option disabled that filtering. In other words, if i were to run Infer with that option, would it be possible for me to receive a report that lists all of the issue types defined in https://github.com/facebook/infer/blob/master/infer/src/base/IssueType.ml ?

**Comment by jeremydubreil** [comment]
Yes, enabling all the checkers (including the experimental ones) and passing the `--no-filtering` option would display all the warnings in the project being analyzed.
