### ISSUE TITLE
It occur error when I run 'make test'

### ISSUE THREAD

**Issue by acekingke** [facebook/infer#922]
[*ERROR**][54027] *** stderr:
[*ERROR**][54027] File "_build/.jbuilds/test/jbuild", line 28, characters 14-18:
[*ERROR**][54027] Error: Library "utop" not found.
[*ERROR**][54027] Hint: try: jbuilder external-lib-deps --missing _build/test/infer.bc _build/test/scripts/checkCopyright.bc _build/test/inferunit.bc _build/test/infertop.bc
[*ERROR**][54027] make[1]: *** [test] Error 1

**Comment by jvillard** [comment]
You need to install `utop` (`opam install utop`). This and more is done by `make devsetup` as listed in CONTRIBUTING.md.
