### ISSUE TITLE
SQL injection and XSS

### ISSUE THREAD

**Issue by phillip-elliott** [facebook/infer#923]
In https://github.com/facebook/infer/blob/v0.14.0/infer/src/base/IssueType.ml both `cross_site_scripting` and `sql_injection` are defined issue types, but I have not seen these issues appear in any reports. Is there a checker I need to enable to have these issues reported?

**Comment by ezgicicek** [comment]
[Quandary](http://fbinfer.com/docs/experimental-checkers.html) is the checker for detecting such information flow issues, and is enabled by default in v0.14.0. 

You can see examples of SQL injection in https://github.com/facebook/infer/blob/master/infer/tests/codetoanalyze/cpp/quandary/execs.cpp  and cross site scripting in https://github.com/facebook/infer/blob/master/infer/tests/codetoanalyze/java/quandary/UserControlledStrings.java.
