### ISSUE TITLE
ERROR: couldn't run compilation command

### ISSUE THREAD

**Issue by koichipan** [facebook/infer#926]
Hello, this is my first time to use infer on my android project,
but I got some error as below, please help:
Infer version v0.15.0-c84bf5959

```
[infer] Running shell script
infer run -- ./gradlew build -x lint

Capturing in gradle mode...
16:39:33.070 [ERROR] [org.gradle.api.Project] warning: string 'Challenge_action' has no default translation.

16:39:34.882 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:39:34.882 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:39:34.882 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
16:39:34.882 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
16:39:38.574 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:39:38.574 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:39:38.574 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
16:39:38.574 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
16:39:42.425 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:39:42.425 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:39:42.425 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
16:39:42.425 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
16:39:44.997 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:39:44.997 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:39:44.997 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
16:39:44.997 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
16:39:49.585 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:39:49.585 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:39:49.585 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
16:39:49.585 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
16:39:49.802 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
16:39:49.802 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:39:49.802 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
16:39:49.802 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
16:39:51.263 [ERROR] [org.gradle.api.Project] warning: string 'Challenge_action' has no default translation.

16:39:52.525 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
16:39:52.525 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
16:39:52.525 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
16:39:52.525 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
16:39:52.525 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':InfocLib:findbugs'.
16:39:52.525 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Failed to run Gradle FindBugs Worker
16:39:52.526 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > Process 'Gradle FindBugs Worker 3' finished with non-zero exit value 1
16:39:52.526 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
16:39:52.526 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
16:39:52.526 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
16:39:52.527 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
16:39:52.527 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
16:39:52.527 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] 
16:39:52.527 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 26s
ERROR: couldn't run compilation command `[u'./gradlew', '--debug', u'build', u'-x', u'lint']`
Running and capturing gradle compilation...
Internal Error: Error running '/usr/local/lib/infer/infer/bin/../lib/python/infer.py' 
  --analyzer checkers -j 8 --project-root
  /home/test/jenkinsagent/workspace/infer --out
  /home/test/jenkinsagent/workspace/infer/infer-out -- ./gradlew build -x
  lint
:
  exited with code 1
Error backtrace:
Raised at file "base/Die.ml" (inlined), line 27, characters 6-36
Called from file "base/Logging.ml", line 316, characters 58-80
Called from file "integration/Driver.ml", line 162, characters 2-16
Called from file "integration/Driver.ml", line 284, characters 6-420
Called from file "infer.ml", line 22, characters 2-36
Called from file "infer.ml", line 132, characters 8-54

Run the command again with `--keep-going` to try and ignore this error.
```

**Comment by jvillard** [comment]
The cause of the error doesn't appear in the console output. Is there anything useful in infer-out/logs? Maybe infer needs to log more to be able to debug crashes like this one.

**Comment by koichipan** [comment]
the following logs show in infer-out 

[8780][environment] CWD = /home/test/jenkinsagent/workspace/infer
[8780][environment] No .inferconfig file found
[8780][environment] Project root = /home/test/jenkinsagent/workspace/infer
[8780][environment] INFER_ARGS =   @/tmp/args.tmp.f57aad
[8780][environment]   ++Contents of '/tmp/args.tmp.f57aad':
[8780][environment]     run
[8780][environment]   
[8780][environment] command line arguments:   infer run -- ./gradlew build --stacktrace -x lint
[8780][environment] Analyzer: checkers
[8780][environment] Active checkers: annotation reachability (Java), biabduction (C/C++/ObjC, Java), fragment retains view (Java), immutable cast (Java), liveness (C/C++/ObjC), printf args (Java), ownership (C/C++/ObjC), RacerD (C/C++/ObjC, Java), SIOF (C/C++/ObjC), uninitialized variables (C/C++/ObjC)
[8780][environment] Infer log identifier is 
Infer version v0.15.0-c84bf5959
[8780][environment] Copyright 2009 - present Facebook. All Rights Reserved.
[8780][environment] 
[8780][   progress] Capturing in gradle mode...
[8780][ intern err] Error running '/usr/local/lib/infer/infer/bin/../lib/python/infer.py' 
  --analyzer checkers -j 8 --project-root
  /home/test/jenkinsagent/workspace/infer --out
  /home/test/jenkinsagent/workspace/infer/infer-out -- ./gradlew build
  --stacktrace -x lint
:
  exited with code 1
[8780][ intern err]

**Comment by jvillard** [comment]
Thanks. Looks like the actual error is missing from there too unfortunately.

**Comment by vbokan** [comment]
Got same issue but differen error. Here's the log.

[69425][environment] CWD = /Users/bkn/Development/Proc/main/
[69425][environment] No .inferconfig file found
[69425][environment] Project root = /Users/bkn/Development/Proc/main/
[69425][environment] INFER_ARGS =   @/var/folders/hj/ml5j2tzj4k98pl8ymr3wqjgc0000gn/T/args.tmp.f685b7
[69425][environment]   ++Contents of '/var/folders/hj/ml5j2tzj4k98pl8ymr3wqjgc0000gn/T/args.tmp.f685b7':
[69425][environment]     run
[69425][environment]   
[69425][environment] command line arguments:   infer run -- ./gradlew clean
[69425][environment] Analyzer: checkers
[69425][environment] Active checkers: annotation reachability (Java), biabduction (C/C++/ObjC, Java), fragment retains view (Java), immutable cast (Java), liveness (C/C++/ObjC), printf args (Java), ownership (C/C++/ObjC), quandary (C/C++/ObjC, Java), RacerD (C/C++/ObjC, Java), SIOF (C/C++/ObjC), uninitialized variables (C/C++/ObjC)
[69425][environment] Infer log identifier is 
Infer version v0.14.0
[69425][environment] Copyright 2009 - present Facebook. All Rights Reserved.
[69425][environment] 
[69425][   progress] Capturing in gradle mode...
[69425][ intern err] Error running '/usr/local/Cellar/infer/0.14.0/lib/infer/infer/bin/../lib/python/infer.py' 
  --analyzer checkers -j 8 --project-root
  /Users/bkn/Development/Proc/main/ --out
  /Users/bkn/Development/Proc/main/infer-out -- ./gradlew
  clean
:
  exited with code 66
[69425][ intern err]

**Comment by jvillard** [comment]
@koichipan It looks like gradle failed to run findBugs. Is there a way to build your project without running findBugs at the same time? I wonder if that's what causing issues but I'm just shooting in the dark here.

@vbokan Can you paste the console output as well?

**Comment by vbokan** [comment]
Sure, here you go.

Run the command again with `--keep-going` to try and ignore this error.
xxxx:main bkn$ infer run -- ./gradlew clean
Capturing in gradle mode...
Running and capturing gradle compilation...
Nothing to compile. Try running `./gradlew clean` first.

Error backtrace:
Raised at file "base/Die.ml" (inlined), line 27, characters 6-36
Called from file "base/Logging.ml", line 296, characters 58-80
Called from file "integration/Driver.ml", line 162, characters 2-16
Called from file "integration/Driver.ml", line 284, characters 6-420
Called from file "infer.ml", line 23, characters 2-36
Called from file "infer.ml", line 135, characters 6-52
Internal Error: Error running '/usr/local/Cellar/infer/0.14.0/lib/infer/infer/bin/../lib/python/infer.py' 
  --analyzer checkers -j 8 --project-root
  /Users/bkn/Development/Proc/main --out
  /Users/bkn/Development/Proc/main/infer-out -- ./gradlew
  clean
:
  exited with code 66

**Comment by jvillard** [comment]
@vbokan That result is expected since you are running `infer -- ./gradlew clean`: infer complains that there was nothing to analyse. What about `./gradlew clean && infer -- ./gradlew build`?

**Comment by liumingzhi** [comment]
same error

Internal Error:   /usr/local/Cellar/infer/0.15.0/lib/infer/infer/bin/../lib/python/infer.py
  -j 4 --project-root /Users/mingzhi.liu/Documents/Test --out
  /Users/mingzhi.liu/Documents/Test/infer-out -- xcodebuild -workspace
  Test.xcworkspace -scheme Test -configuration Debug -sdk iphonesimulator
  -arch i386:
  exited with code 65
Error backtrace:
Raised at file "base/Die.ml" (inlined), line 25, characters 6-36
Called from file "base/Logging.ml", line 314, characters 58-80
Called from file "integration/Driver.ml", line 159, characters 2-16
Called from file "integration/Driver.ml", line 280, characters 6-420
Called from file "infer.ml", line 20, characters 2-36
Called from file "infer.ml", line 130, characters 8-54

**Comment by jvillard** [comment]
@koichipan @vbokan please re-open with more information if there is still an issue after my 1 Jun suggestions.

@liumingzhi this issue is about gradle, not xcodebuild. Please open a separate issue for you problem. Note that the recommended way to run infer on xcodebuild projects is via a compilation database. See http://fbinfer.com/docs/analyzing-apps-or-projects.html#xcodebuild

**Comment by ravarora** [comment]
We are facing the exact same issue. 
1. Findbugs is not being run in the build. 
2. Ran the following commands
     a. ./gradlew clean then infer run -- ./gradlew assembleDebug
     b. ./gradlew clean then infer run -- ./gradlew assembleRelease
     c. ./gradlew clean then infer run -- ./gradlew build
All the above commands yield the same error

_Internal Error:   /usr/local/Cellar/infer/0.15.0/lib/infer/infer/bin/../lib/python/infer.py
  -j 8 --project-root /Users/ravisharora/KCInd/Android/app --out
  /Users/ravisharora/KCInd/Android/app/infer-out -- ./gradlew assembleDebug:
  exited with code 1
Error backtrace:
Raised at file "base/Die.ml" (inlined), line 25, characters 6-36
Called from file "base/Logging.ml", line 314, characters 58-80
Called from file "integration/Driver.ml", line 159, characters 2-16
Called from file "integration/Driver.ml", line 280, characters 6-420
Called from file "infer.ml", line 20, characters 2-36
Called from file "infer.ml", line 130, characters 8-54_

infer-out/logs has the following output
_[35572][environment] Analyzer: capture
[35572][environment] Active checkers: annotation reachability (Java), biabduction (C/C++/ObjC, Java), fragment retains view (Java), immutable cast (Java), liveness (C/C++/ObjC), printf args (Java), ownership (C/C++/ObjC), RacerD (C/C++/ObjC, Java), SIOF (C/C++/ObjC), uninitialized variables (C/C++/ObjC)
[35572][      debug] Current working directory: '/Users/ravisharora/KCInd/Android/app'
[35572][      debug] Trying to execute: javac '-J-Duser.language=en' '@/Users/ravisharora/KCInd/Android/app/infer-out/filelists/gradle_T9kqdf.txt' '@/var/folders/fc/hfpr883x57b0mbqdgk87454w0000gn/T/args_.tmp.3ff639' 2>'/var/folders/fc/hfpr883x57b0mbqdgk87454w0000gn/T/javac.tmp.ecfa89.out'
[35572][      debug] *** Success. Logs:
[35572][      debug] setting processing env to javac ProcessingEnvironment
Translating 1784 source files (5075 classes)
[35572][environment] Infer log identifier is 
[33285][ intern err]   /usr/local/Cellar/infer/0.15.0/lib/infer/infer/bin/../lib/python/infer.py
  -j 8 --project-root /Users/ravisharora/KCInd/Android/app --out
  /Users/ravisharora/KCInd/Android/app/infer-out -- ./gradlew assembleDebug:
  exited with code 1
[33285][ intern err]_ 

Any help here would be appreciated.

**Comment by jvillard** [comment]
@ravarora is there any error in the console before what you pasted? Usually when `gradlew` fails it is because some `javac` invocation failed and you should be able to see the `javac` command infer is trying to run. That command is extracted by infer from gradle's verbose output so sometimes it parses it incorrectly and the command doesn't make sense to `javac`.

**Comment by ravarora** [comment]
I tried it again after cleaning my local source code directories. It is working fine now.
