### ISSUE TITLE
Run infer on a custom build system

### ISSUE THREAD

**Issue by shivani-singhal** [facebook/infer#927]
#Hi 

I want to tweak infer to be able to run it on a custom build system that is a wrapper around ant.
How can I do that?
I tried changing the infer/lib/python/infer.py to add the new build system in the MODULE_TO_COMMAND dictionary, and added a file infer/lib/python/inferlib/capture/ with the same name as the value mapped to the new command in MODULE_TO_COMMAND but that doesn't make it work

Thanks

**Comment by jvillard** [comment]
Hi @shivani-singhal, if your script behaves like `ant` you should be able to use `infer --force-integration ant -- ./your_script`. It probably needs your changes to infer.py as well, I'm not entirely sure. Let me know if that helps.

**Comment by shivani-singhal** [comment]
I used the following fork to run infer with the required custom build system https://github.com/martinschaef/infer 
Here is a diff from infer https://github.com/martinschaef/infer/commit/593abac33475615eea1c4c29a465afec24de385e

when run infer with this fork, it gives me the following error 
Usage Error:
*** Failed to execute compilation command: exited with code 2
*** Command: javac '@/tmp/args_.tmp.89dbb0'
*** Output:
javac: invalid target release: 1.8
Usage: javac <options> <source files>
use -help for a list of possible options

*** Infer needs a working compilation command to run.

this build compiles correctly when not being compiled from infer. Is there any way to resolve this?

**Comment by shivani-singhal** [comment]
my build environment and desktop were consuming different java versions. The issue was resolved after changing the java version

**Comment by jvillard** [comment]
Thanks for the info! I'll try and make the python wrappers more resilient to build systems commands having different names so that the `--force-integration` option works as intended.
