### ISSUE TITLE
how to use the infer？

### ISSUE THREAD

**Issue by hhb19900618** [facebook/infer#93]
how to use the infer？i dont konw

**Comment by adityakasturi** [comment]
Have you downloaded clang and command line tools

**Comment by angusTao-cienet** [comment]
http://fbinfer.com/docs/getting-started.html

**Comment by angusTao-cienet** [comment]
应该是老乡吧~
我今天刚跟着上面的链接走完.也正好做了记录.你可以参考下~
https://ungacy.atlassian.net/wiki/display/PROG/facebook_infer

**Comment by angusTao-cienet** [comment]
应该是老乡吧~
我今天刚跟着上面的链接走完.也正好做了记录.你可以参考下~
https://ungacy.atlassian.net/wiki/display/PROG/facebook_infer

**Comment by martinoluca** [comment]
Please follow the instructions on http://fbinfer.com/docs/getting-started.html
