### ISSUE TITLE
infer-0.14.0 not generate a csv report?

### ISSUE THREAD

**Issue by cyw3** [facebook/infer#931]
I find that infer-0.14.0 can not generate a csv report while infer-0.13.0 can?
I think a very large csv report, such as 8Gb, can be handled with easily.

**Comment by jvillard** [comment]
What's the command you use that used to generate a CSV report but doesn't anymore?

**Comment by jeremydubreil** [comment]
The support for exporting the analysis results in the CSV format was removed recently. The code to create CSV reports in Infer was a little bit ad-hoc and not really maintained. The resulting CSV files were not necessarily containing all the fields available in the JSON reports. In the meantime, there are plenty of tools and libraries to convert JSON files into CSV which would offer more flexibility on the schema of the CSV rows, and a better compatibility with the format, encoding, etc, than the report files created directly by Infer.

**Comment by cyw3** [comment]
And the json format report can be beautified like below? not just all message in one line!
![image](https://user-images.githubusercontent.com/11549103/40963031-e1050376-68d9-11e8-9354-c19a8ccee434.png)

**Comment by jvillard** [comment]
Infer utputs the results without prettifying to save disk space. There are many tools available to pretty-print json (you must have used one to produce your image?). For example, [`jq`](https://stedolan.github.io/jq/) will let you print, but also filter and more generally post-process json objects in a powerful way. To pretty-print using `jq`: `jq . < infer-out/report.json`.

**Comment by DaveJarvis** [comment]
Here's a starting point for anyone looking to convert the JSON report to CSV 

``` bash
jq -j '.[] | .bug_type + ", " + .severity + ", " + .file + ", " + (.line|tostring) + ", " + (.procedure|gsub(","; ";")) + ", " + (.qualifier|gsub("[\\n\\t,]"; " ")) + "\n"' infer-out/report.json
```
