### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by mcandre** [facebook/infer#934]
Am I understanding this correctly, that Infer currently depends on Python 2.7? If so, it would be good to add support for Python 3, in order to run more easily in modern development environments, especially now that Python 2 will soon be dropped from receiving security updates.

**Comment by jvillard** [comment]
Yes infer needs python2.7 for some of its build system integrations (buck, ant, gradle, and xcodebuild). If I understand correctly, Python2.7 will be supported until 1 Jan 2020.

The Python code could be rewritten in OCaml to simplify way infer works (currently OCaml calls into Python for the integrations above, which calls back into OCaml), or else be ported to Python 3 as we near 2020.

**Comment by engineeringstuff032** [comment]
Integration

**Comment by XVilka** [comment]
Note, that 2020 will happen in a couple months, so it might be a good time to revisit this.

**Comment by XVilka** [comment]
I quickly skimmed through all python files in this repo - most of the code looks compatible with Python 3, you might just try it as is, there are couple errors, can't fix it myself until I am able to build it (see https://github.com/facebook/infer/issues/1194), but it's probably 15min maximum if you have a working build environment.

**Comment by XVilka** [comment]
Would be nice if you quickly check these, since Python 2 is officially dead now, and many distributions already started to work on its removal actively.

**Comment by XVilka** [comment]
Seems there is ongoing work to remove unnecessary Python code already:
- https://github.com/facebook/infer/commit/74e54575fac502f21bc0220703f57b15e62b82c8
- https://github.com/facebook/infer/commit/284c6fdb3b8533c1a1c6fcbddf0849f6bde231a2

**Comment by jvillard** [comment]
@XVilka yes we are finally working on migrating the Python code in infer to OCaml, or at least the files that we call into from OCaml (which is most of it). We'll migrate whatever is left to python 3. I think that will be only [infer/tests/testlock.py](https://github.com/facebook/infer/blob/95807702fc9dfe0ae87b9d0d86f33ac13ab7a94e/infer/tests/testlock.py).

**Comment by XVilka** [comment]
Can be closed since https://github.com/facebook/infer/commit/f867e14b89d3089bcab7f7d81e951af674e43183
Only Dockerfiles left to be updated. Maybe also switch to the Debian Buster as the base for these images?
