### ISSUE TITLE
Automatic clang compilation fails

### ISSUE THREAD

**Issue by farao** [facebook/infer#944]
Hi,

I want to use infer on (fedora) linux and thus the only available options seems to be building from source. Unfortunately, building from source apparently means that clang must be compiled as well.
1. When I choose this option, and wait a long time for clang to compile, linking of clang fails with a lot of error like this: 
- /usr/bin/ld: ../../lib/libLLVMAArch64CodeGen.a(AArch64TargetTransformInfo.cpp.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
- /usr/bin/ld: ../../lib/libLLVMAArch64CodeGen.a(AArch64SIMDInstrOpt.cpp.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
- ...
Why is this failing?

2. The clang version that is being compiled is the same as the clang on my system (6.0) - can I just tell the infer installation routine to use the system clang?

Thanks,
Marius

**Comment by jvillard** [comment]
1. Looks similar to #942. Can you try `NO_CMAKE_STRIP=1 ./build-infer.sh`?
2. I think it's possibly but would be non-trivial work. Note that the version in infer is clang 7, not 6. You can try by messing with the `CLANG_PREFIX`, `CLANG_INCLUDES`, and `CLANG` variables when building the plugin manually (`make -C facebook-clang-plugins/libtooling CLANG_PREFIX=... ...`), possibly with `LLVM_CXXFLAGS` and `LLVM_LDFLAGS` too. Check out this [`Makefile.config`](https://github.com/facebook/facebook-clang-plugins/blob/10eb1ac9bb9e94ae8332e84058f39699422a0e85/Makefile.config) in facebook-clong-plugins. The version on your system will need some symbols that are usually stripped by distributions though (in my experience). Also, clang 7 still being in development, it's unlikely that your distribution's version is at the same version exactly and some changing to the plugin may be necessary.

**Comment by ReapOmen** [comment]
@farao I had a similar problem, and I've done two things:
* built `infer` with `NO_CMAKE_STRIP=1 ./build-infer.sh`
* changed https://github.com/facebook/facebook-clang-plugins/blob/10eb1ac9bb9e94ae8332e84058f39699422a0e85/clang/setup.sh#L127 from `/tmp/` to `/home/my_username/` because I didn't have enough disk space

**Comment by farao** [comment]
Thanks, this is resolving my issue. And yes, choosing another CLANG_TMP_DIR was also very helpful - I think this should have another default than /tmp because /tmp is in most distributions now backed by ram and not disk.
