### ISSUE TITLE
False negative - `const` for array size in buffer overrun

### ISSUE THREAD

**Issue by skicombinator** [facebook/infer#948]
Hi,
for the below c++ source,
```cpp
#include <iostream>

const int SIZE = 50;
int main() {
  int *arr = new int[SIZE];
  for (int i = 0; i <= SIZE; ++i) { // bo
    arr[i] = 1;
  }
  delete[] arr;
  return 0;
}

```
`infer run -a checkers --bufferoverrun -- clang++ foo.cpp` cannot successfully generate buffer overrun alarm, even with `--debug` mode on.
However, when `const int SIZE=50;` replaced by `#define SIZE 50`, which is, I think, semantically identical, it generates positive alarm.

**Comment by skcho** [comment]
Hello safewalnuts,

I think this is the same issue with #949 : the bufferoverrun checker (still in experimental) cannot address global variables correctly as of now.

Sincerely,
Sungkeun

**Comment by skcho** [comment]
I close the issue, since the bufferoverrun checker understands global constants now. :blush:

**Comment by mbouaziz** [comment]
Note that it may not be available in the latest release yet but it is definitely in master.
Thanks for the report!
