### ISSUE TITLE
False negative - global array in buffer overrun

### ISSUE THREAD

**Issue by sangwoo-joh** [facebook/infer#949]
Hi,
for the below c++ source,

```cpp
#include <iostream>

#define SIZE 50

int arr[SIZE];
int main(){
  for(int i=0; i<=SIZE; ++i){ // bo
    arr[i] = 1;
  }
  return 0;
}
```

infer `run -a checkers --bufferoverrun -- clang++ foo.cpp` cannot successfully generate buffer overrun alarm, even with `--debug` mode on.
However, when the definition of `arr[SIZE]` is moved in `main()` body, it generates positive alarm.

**Comment by skcho** [comment]
Hello safewalnuts,

Unfortunately, the bufferoverrun checker (still in experimental) cannot address the global variables correctly as of now. Thank you for the report though.

Sincerely,
Sungkeun
