### ISSUE TITLE
Parsing non-type template arguments

### ISSUE THREAD

**Issue by ReapOmen** [facebook/infer#950]
Hi,

It seems that `infer` cannot parse some of the following code:

```
// test.cpp
template<int T>
struct X {
    bool isZero() {
        return T == 0;
    }
};

int main() {
    X<3> x;
    x.isZero();
    return 0;
}
```

```
infer run -- clang++ -std=c++11 -o test test.cpp
Capturing in make/cc mode...
test.cpp:4:16: ERROR translating statement 'SubstNonTypeTemplateParmExpr'
test.cpp:4:16-21: ERROR translating statement 'ConditionalOperator'
test.cpp:4:16-21: ERROR translating statement 'BinaryOperator'
test.cpp:4:9-21: ERROR translating statement 'ReturnStmt'
test.cpp:3:19-5:5: ERROR translating statement 'CompoundStmt'
test.cpp:4:16: ERROR translating statement 'SubstNonTypeTemplateParmExpr'
test.cpp:4:16-21: ERROR translating statement 'ConditionalOperator'
test.cpp:4:16-21: ERROR translating statement 'BinaryOperator'
test.cpp:4:9-21: ERROR translating statement 'ReturnStmt'
test.cpp:3:19-5:5: ERROR translating statement 'CompoundStmt'
Found 1 source file to analyze in /home/username/infer-out
Starting analysis...

legend:
  "F" analyzing a file
  "." analyzing a procedure

F..
```

More specifically, I don't think it can parse statements which contain non-type template parameters. 

```
infer --version
Infer version v0.15.0
Copyright 2009 - present Facebook. All Rights Reserved.
```

**Comment by dulmarod** [comment]
It probably can, those ERROR messages don't mean that, and they have been removed form the standard out in master.

**Comment by ReapOmen** [comment]
Consider the following program:
```
// test.cpp
template<int T>
struct X {
    bool isZero() {
        int unused = 1;
        return T == 0;
    }
};

int main() {
    X<3> x;
    x.isZero();
    int unused = 1;
    return 0;
}
```
and the output
```
infer run -- clang++ -std=c++11 -o test test.cpp
Capturing in make/cc mode...
test.cpp:5:16: ERROR translating statement 'SubstNonTypeTemplateParmExpr'
test.cpp:5:16-21: ERROR translating statement 'ConditionalOperator'
test.cpp:5:16-21: ERROR translating statement 'BinaryOperator'
test.cpp:5:9-21: ERROR translating statement 'ReturnStmt'
test.cpp:3:19-6:5: ERROR translating statement 'CompoundStmt'
test.cpp:5:16: ERROR translating statement 'SubstNonTypeTemplateParmExpr'
test.cpp:5:16-21: ERROR translating statement 'ConditionalOperator'
test.cpp:5:16-21: ERROR translating statement 'BinaryOperator'
test.cpp:5:9-21: ERROR translating statement 'ReturnStmt'
test.cpp:3:19-6:5: ERROR translating statement 'CompoundStmt'
Found 1 source file to analyze in /home/username/infer-out
Starting analysis...

legend:
  "F" analyzing a file
  "." analyzing a procedure

F..
Found 1 issue

test.cpp:12: error: DEAD_STORE
  The value written to &unused (type int) is never used.
  10.       X<3> x;
  11.       x.isZero();
  12. >     int unused = 1;
  13.       return 0;
  14.   }


Summary of the reports

  DEAD_STORE: 1
```

Shouldn't `infer` find two `DEAD_STORE`s?

In this case:
```
template<typename T> // notice that this is no longer a non-type parameter
struct X {
    bool isZero() {
        int unused = 1;
        return sizeof(T) == 0;
    }
};

int main() {
    X<int> x;
    x.isZero();
    int unused = 1;
    return 0;
}
```

`infer` outputs

```
infer run -- clang++ -std=c++11 -o test test.cpp
Capturing in make/cc mode...
Found 1 source file to analyze in /home/username/infer-out
Starting analysis...

legend:
  "F" analyzing a file
  "." analyzing a procedure

F...
Found 2 issues

test.cpp:4: error: DEAD_STORE
  The value written to &unused (type int) is never used.
  2.   struct X {
  3.       bool isZero() {
  4. >         int unused = 1;
  5.           return sizeof(T) == 0;
  6.       }

test.cpp:12: error: DEAD_STORE
  The value written to &unused (type int) is never used.
  10.       X<int> x;
  11.       x.isZero();
  12. >     int unused = 1;
  13.       return 0;
  14.   }


Summary of the reports

  DEAD_STORE: 2
```

If it isn't a parsing problem, then what does the error mean?

**Comment by dulmarod** [comment]
OK, that's a more compelling point that you mat be right. Tagging @da319 that may know more about this. 
Just to understand your issue better, is there a much C++ code which contain non-type template parameters without instantiation?

**Comment by ReapOmen** [comment]
On the project that I am running `infer` on there are many similar cases, and `infer` outputs the translating error quite often.

**Comment by ReapOmen** [comment]
I can't compile the master version for the same reason as in #944. Even if the errors are silenced, won't `infer` still skip the functions which triggered translation errors?

**Comment by dulmarod** [comment]
Yes, it's just in case the ERROR messages are polluting the output. But about the code coverage problem, are there instantiations of the code with concrete type as well?

**Comment by ReapOmen** [comment]
The project has multiple combinations of template parameters. Templates which only contain type parameters are correctly parsed and analyzed (`template<typename T, typename V, etc.>`), but if one of the parameters is a non-type one (`template<typename T, int N>`), and this non-type parameter is used in the code, the translation error is triggered, and the code is no longer analyzed. Only the function or class which uses the non-type parameter is skipped, the others are analyzed correctly.

**Comment by mbouaziz** [comment]
Indeed, it looks like we don't support non-type template parameter expressions ([SubstNonTypeTemplateParmExpr](https://clang.llvm.org/doxygen/classclang_1_1SubstNonTypeTemplateParmExpr.html) clang node).
The fix seems straightforward if I understand correctly, you can send a PR if you feel confortable, otherwise I can write it when I'll have a bit of time in a few days.

**Comment by ReapOmen** [comment]
@mbouaziz I am not sure how to do it, mainly because I am not familiar with OCaml. Thank you for looking into it!

**Comment by ReapOmen** [comment]
@mbouaziz I will attempt to fix this issue tomorrow, and if I am not able to do it, I will let you know.

**Comment by jvillard** [comment]
I have a patch ready, stay tuned.

**Comment by squinkylabs** [comment]
I am having the same error using the current release (0.15.0). At least it sounds like the same issue. Was this ever fixed in a release?
