### ISSUE TITLE
Java null-dereference error

### ISSUE THREAD

**Issue by ReapOmen** [facebook/infer#957]
Hi,

I was wondering if the following is a bug or not:

```
// Does not generate null_dereference error
String s = null;
if (s != null) {
    return s.length();
}
return 0;

// This generates null_dereference error
String s = null;
try {
    return s.length();
} catch (NullPointerException e) {
    return 0; 
}
```

Shouldn't the 2nd example behave the same as the first one? I know the error is called `NULL_DEREFERENCE`, and in the second example a null dereference happens, but I thought that if it is handled by a `try-catch` it is fine because it does not crash the program.

**Comment by jvillard** [comment]
This is a conscious decision not to silence warnings if the `NullPointerException` is caught, see for instance #423.
