### ISSUE TITLE
INSTALL.md is out of date with respect to facebook-clang-plugins

### ISSUE THREAD

**Issue by andrewvaughanj** [facebook/infer#959]
As of this commit: https://github.com/facebook/facebook-clang-plugins/commit/305d79cdda62e91e6713a83ce056c74821d9bb7e, it appears that `facebook-clang-plugins` requires C++14 support. C++14 support was only added to GCC 4.9/5.0: https://gcc.gnu.org/projects/cxx-status.html#cxx14

However, the building-from-source notes for `Infer` (https://github.com/facebook/infer/blob/master/INSTALL.md) state you can use GCC 4.7.2.

This is a conflict because 4.7.2 cannot build `facebook-clang-plugins`.

```
[avj@infer tmp]$ gcc -dumpversion
4.8.5
[avj@infer tmp]$ g++ -std=c++14 test.cpp
g++: error: unrecognized command line option ‘-std=c++14’
```

The easiest fix is probably just to modify the installation notes to require something like GCC 5.x (given that 4.9.x only has partial C++14 support).

**Comment by jvillard** [comment]
Good catch! The manual should be updated.

**Comment by ezgicicek** [comment]
Updated the manual on master. Closing the task.
