### ISSUE TITLE
error: PCH file uses an older PCH format that is no longer supported

### ISSUE THREAD

**Issue by sreeneel** [facebook/infer#96]
When running infer on an iOS project, I get the following error:

error: PCH file uses an older PCH format that is no longer supported

My env:
Xcode version: 6.3.2

clang version(that comes default with Xcode): 
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix

I tried compiling "infer" from scratch too, and still the same problem

**Comment by fangmobile** [comment]
+ 1.
Xcode version 6.3.2
Did anybody else try this on this Xcode version?

**Comment by martinoluca** [comment]
Hello @sreeneel and @fangmobile,
please make sure you use the latest version of Infer, and you run the compilation with `GCC_PRECOMPILE_PREFIX_HEADER=NO`

**Comment by jvillard** [comment]
@sreeneel, @fangmobile did @martinoluca's suggestion solve your issue?

**Comment by fangmobile** [comment]
yes! 
I do wonder should
````
GCC_PRECOMPILE_PREFIX_HEADER=NO
````
be default?

**Comment by jvillard** [comment]
Good question. @martinoluca, what do you think?
