### ISSUE TITLE
Running infer on linux kernel current and staging

### ISSUE THREAD

**Issue by tapasweni-pathak** [facebook/infer#983]
I was working on running infer on linux kernel, current and staging. I think infer only compiles with Clang, I was able to compile linux kernel current(not the llvm branch) with quite a few modules disabled with clang(6.0) on Ubuntu 17.04, it didn't work on 16.04 because of asm-goto even with gcc-8.1 not sure why.

When I run infer on a file and not a complete module, it seems to miss the header files searches. Let's say I would run something like `infer -- clang -c fs/file_table.c` or `infer -- gcc -c fs/file_table.c` (this will still parse with Clang). Basically I'm thinking there needs to be a Makefile to build the file(in this case `file_table.c`) only then infer would be able to successfully search the header files? Is there any work done on building kernel with infer? or if there are any instructions available that I have missed, any leads would be great.

**Comment by martintrojer** [comment]
Hello,

If additional include folders are needed to compile a .c file, simply use the `-I` compiler flag.

`infer -- clang -c fs/file_table.c -I <INCLUDE FOLDER>`.

As for running Infer on the Linux kernel modules, theoretically its possible. The problem you are facing (I assume) is getting the 'capture' phase to run correctly. This is when infer extracts all compiler flag information from the build-system (assuming Make in this case) and runs it through Infer's embedded clang compiler. I urge you to read the first couple of chapters of the user guide to get a better understanding of how this works. http://fbinfer.com/docs/infer-workflow.html

Please note that `-- clang` capture mode above is different from the `-- make` capture mode you are more likely to use for linux kernel modules.

**Comment by tapasweni-pathak** [comment]
Thanks for writing the info, do you mean that all `.c` file in kernel can be compiled using `-I <INCLUDE FOLDER>` compiler flag and all `.c` file in kernel would be having a `<INCLUDE FOLDER>` and having Makefile output to run with make to compile `.c` with infer is not needed? which I think would also mean that any `.c` file in kernel can be compiled independently with some `<INCLUDE FOLDER>` available without the need of the Makefile; leaving a kernel module or a non kernel c file here.

**Comment by tapasweni-pathak** [comment]
Thanks for writing the info, do you mean that all `.c` file in kernel can be compiled using `-I <INCLUDE FOLDER>` compiler flag and all `.c` file in kernel would be having a `<INCLUDE FOLDER>` and having Makefile output to run with make to compile `.c` is not needed? which I think would also mean that any `.c` file in kernel can be compiled independently with some `<INCLUDE FOLDER>` available without the need of the Makefile; leaving a kernel module or a non kernel c file here.

**Comment by jvillard** [comment]
I think the issue here is that `clang -c fs/file_table.c` doesn't work on its own either, is that right? Infer needs a working compilation command to run.

Normally the kernel's Makefiles would include the right compilation flags. Are you able to run infer on a make target instead with `infer -- make ...`? It should also be possible to run infer on a single file by asking `make` to build only that file, for instance `rm fs/file_table.o; infer -- make fs/file_table.o` (if fs/file_table.c compiles to fs/file_table.o; if not you need to adapt this command).

**Comment by tapasweni-pathak** [comment]
Thanks for writing the info, do you mean that all `.c` file in kernel can be compiled using `-I <INCLUDE FOLDER>` compiler flag with infer and all `.c` file in kernel would be having a `<INCLUDE FOLDER>` and having Makefile output to run with make to compile `.c` is not needed? which I think would also mean that any `.c` file in kernel can be compiled independently with some `<INCLUDE FOLDER>` available without the need of the Makefile; leaving a kernel module or a non kernel c file here.

**Comment by tapasweni-pathak** [comment]
Thanks for the pointers, ya _I think_ `infer -- clang` wouldn't work for kernel files even with `-I` compilation flag. I should be able to `make file.o` in kernel which is not working for `fs/`, could be my local settings. I think infer needs the project to be compiled with Clang so I need to make sure I run `infer -- make file.o` as I have a Clang compiled kernel. I'm not sure if I have to `infer -- make CC=clang file.o` or I think infer will always parse with Clang and `rm fs/file_table.o; infer -- make fs/file_table.o` would be same as a Clang compiled kernel file and running a `infer -- make file_table.o` on it.

**Comment by tapasweni-pathak** [comment]
Thanks for writing the info, ya _I think_ `infer -- clang` wouldn't work for kernel files even with `-I` compilation flag. I should be able to `make file.o` in kernel which is not working for `fs/`, could be my local settings. I think infer needs the project to be compiled with Clang so I need to make sure I run `infer -- make file.o` as I have a Clang compiled kernel. I'm not sure if I have to `infer -- make CC=clang file.o` or I think infer will always parse with Clang and `rm fs/file_table.o; infer -- make fs/file_table.o` would be same as a Clang compiled kernel file and running a `infer -- make file_table.o` on it.

**Comment by mbouaziz** [comment]
Hey @tapasweni-pathak, let us know how it went, whether it worked as intended and whether you find something interesting :)

**Comment by tapasweni-pathak** [comment]
yes sure, was thinking of updating the ticket with the commands, the `.inferconfig` and/or any infer models after a run on complete kernel.
Infer required to skip directories like `arch/`, `mm/`, `fs/`, `kernel/bpf`, `drivers/acpi`, `net/mac80211`, latest release. I think running infer on complete kernel would also require writing infer models in infer, surely will update about the findings after complete kernel analysis.

**Comment by tapasweni-pathak** [comment]
yes sure, was thinking of updating the ticket with the commands, the `.inferconfig` and/or any infer models after a run on complete kernel.
Infer required to skip directories like `arch/`, `mm/`, `fs/`, `kernel/bpf`, `drivers/acpi`, `net/mac80211`, latest release. I think running infer on complete kernel may also require writing infer models in infer, surely will update about the findings after complete kernel analysis.

**Comment by tapasweni-pathak** [comment]
Thanks for checking, was thinking of updating the ticket with the commands, the `.inferconfig` and/or any infer models after a run on complete kernel.
Infer required to skip directories like `arch/`, `mm/`, `fs/`, `kernel/bpf`, `drivers/acpi`, `net/mac80211`, latest release. I think running infer on complete kernel may also require writing infer models in infer, surely will update about the findings after complete kernel analysis.
