### ISSUE TITLE
Error while running the programme

### ISSUE THREAD

**Issue by Dhairya1734** [facebook/infer#984]
i got an error while running build-infer that dependency not found in opam.

**Comment by jvillard** [comment]
Please follow the instructions in the [INSTALL.md](https://github.com/facebook/infer/blob/master/INSTALL.md) file if you want to build infer from source. In particular, it will tell you how to get the dependencies.

You can also install infer without having to compile it, see http://fbinfer.com/docs/getting-started.html

**Comment by Dhairya1734** [comment]
Sorry, That was mistake by my part. i am sorry.
