### ISSUE TITLE
Infer build error

### ISSUE THREAD

**Issue by vnrajan** [facebook/infer#987]
Hi,
Downloaded the source and faced the following error during building;

ssseng@ssseng-Inspiron-5559:/media/Drive/test/infer$ make
[15:16:38][ 3734] Building clang plugin...
[      0s][ 3734] SUCCESS Building clang plugin
[15:16:38][ 3763] Building clang plugin OCaml interface...
[      0s][ 3763] SUCCESS Building clang plugin OCaml interface
[15:16:38][ 3809] Generating source dependencies...
[      0s][ 3809] SUCCESS Generating source dependencies
[15:16:38][ 3910] Building native(opt) Infer...
[*ERROR**][3910] *** ERROR 'Building native(opt) Infer'
[*ERROR**][3910] *** command: ' make INTERACTIVE=1 -C /media/Drive/test/infer/infer/src INFER_BUILD_DIR=_build/opt infer'
[*ERROR**][3910] *** CWD: '/media/Drive/test/infer'
[*ERROR**][3910] *** stdout:
[*ERROR**][3910] make[1]: Entering directory '/media/Drive/test/infer/infer/src'
[*ERROR**][3910] Makefile:109: recipe for target '_build/opt/infer.exe' failed
[*ERROR**][3910] make[1]: Leaving directory '/media/Drive/test/infer/infer/src'
[*ERROR**][3910] *** stderr:
[*ERROR**][3910] bash: dune: command not found
[*ERROR**][3910] make[1]: *** [_build/opt/infer.exe] Error 127
Makefile:170: recipe for target 'src_build' failed
make: *** [src_build] Error 2

Please support to build and install infer.

Thanks in advance for your support.

**Comment by vnrajan** [comment]
Thanks for your prompt feedback. I am sure that all the dependencies has been installed. Let me check once again and feedback you.

**Comment by vnrajan** [comment]
Hi Mr. @jvillard,

Faced errors when execute ./build-infer.sh. Please check the below logs;

ssseng@ssseng-Inspiron-5559:/media/Drive/infer$ git clone https://github.com/facebook/infer.git
Cloning into 'infer'...
remote: Counting objects: 87776, done.
remote: Compressing objects: 100% (134/134), done.
remote: Total 87776 (delta 80), reused 93 (delta 43), pack-reused 87599
Receiving objects: 100% (87776/87776), 84.90 MiB | 867.00 KiB/s, done.
Resolving deltas: 100% (68393/68393), done.
Checking connectivity... done.
ssseng@ssseng-Inspiron-5559:/media/Drive/infer$ 
ssseng@ssseng-Inspiron-5559:/media/Drive/infer$ 
ssseng@ssseng-Inspiron-5559:/media/Drive/infer$ ls
infer
ssseng@ssseng-Inspiron-5559:/media/Drive/infer$ cd infer/
ssseng@ssseng-Inspiron-5559:/media/Drive/infer/infer$ ls
autogen.sh          dependencies            INSTALL.md            opam
build-infer.sh      docker                  install-sh            opam.lock
CODE_OF_CONDUCT.md  dotbuckversion          LICENSE               README.md
configure.ac        examples                m4                    scripts
CONTRIBUTING.md     facebook-clang-plugins  Makefile              sledge
CONTRIBUTORS        FILES.md                Makefile.autoconf.in
DEFS                infer                   Makefile.config
ssseng@ssseng-Inspiron-5559:/media/Drive/infer/infer$ ./build-infer.sh clang
initializing opam... 
OPAM has already been initialized.
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

1. To configure OPAM in the current shell session, you need to run:

      eval `opam config env`

2. To correctly configure OPAM for subsequent use, add the following
   line to your profile file (for instance ~/.profile):

      . /home/ssseng/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

3. To avoid issues related to non-system installations of `ocamlfind`
   add the following lines to ~/.ocamlinit (create it if necessary):

      let () =
        try Topdirs.dir_directory (Sys.getenv "OCAML_TOPLEVEL_PATH")
        with Not_found -> ()
      ;;

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

# To setup the new switch in the current shell, you need to run:
eval `opam config env`

installing infer dependencies; this can take up to 30 minutes... 
[NOTE] Package ANSITerminal is already installed (current version is 0.8).
[NOTE] Package atd is already installed (current version is 2.0.0).
[NOTE] Package atdgen is already installed (current version is 2.0.0).
[NOTE] Package atdgen-runtime is already installed (current version is 2.0.0).
[NOTE] Package base is already installed (current version is v0.11.0).
[NOTE] Package base64 is already installed (current version is 2.2.0).
[NOTE] Package bin_prot is already installed (current version is v0.11.0).
[NOTE] Package biniou is already installed (current version is 1.2.0).
[NOTE] Package camlidl is already installed (current version is 1.05).
[NOTE] Package camlp4 is already installed (current version is 4.06+1).
[NOTE] Package camlzip is already installed (current version is 1.07).
[NOTE] Package camomile is already installed (current version is 1.0.1).
[NOTE] Package cmdliner is already installed (current version is 1.0.2).
[NOTE] Package conf-autoconf is already installed (current version is 0.1).
[NOTE] Package conf-m4 is already installed (current version is 1).
[NOTE] Package conf-perl is already installed (current version is 1).
[NOTE] Package conf-pkg-config is already installed (current version is 1.0).
[NOTE] Package conf-which is already installed (current version is 1).
[NOTE] Package conf-zlib is already installed (current version is 1).
[NOTE] Package configurator is already installed (current version is v0.11.0).
[NOTE] Package core is already installed (current version is v0.11.2).
[NOTE] Package core_kernel is already installed (current version is v0.11.1).
[NOTE] Package cppo is already installed (current version is 1.6.4).
[NOTE] Package cppo_ocamlbuild is already installed (current version is 1.6.0).
[NOTE] Package ctypes is already installed (current version is 0.14.0).
[NOTE] Package easy-format is already installed (current version is 1.3.1).
[NOTE] Package extlib is already installed (current version is 1.7.5).
[NOTE] Package fieldslib is already installed (current version is v0.11.0).
[NOTE] Package integers is already installed (current version is 0.2.2).
[NOTE] Package jane-street-headers is already installed (current version is
       v0.11.0).
[NOTE] Package javalib is already installed (current version is 2.3.5).
[NOTE] Package jbuilder is already installed (current version is transition).
[NOTE] Package menhir is already installed (current version is 20180703).
[NOTE] Package mtime is already installed (current version is 1.1.0).
[NOTE] Package num is already installed (current version is 1.1).
[NOTE] Package ocaml-compiler-libs is already installed (current version is
       v0.11.0).
[NOTE] Package ocaml-migrate-parsetree is already installed (current version is
       1.0.11).
[NOTE] Package ocamlbuild is already installed (current version is 0.12.0).
[NOTE] Package ocamlfind is already installed (current version is 1.8.0).
[NOTE] Package octavius is already installed (current version is 1.2.0).
[NOTE] Package ounit is already installed (current version is 2.0.5).
[NOTE] Package parmap is already installed (current version is 1.0-rc10).
[NOTE] Package parsexp is already installed (current version is v0.11.0).
[NOTE] Package ppx_assert is already installed (current version is v0.11.0).
[NOTE] Package ppx_base is already installed (current version is v0.11.0).
[NOTE] Package ppx_bench is already installed (current version is v0.11.0).
[NOTE] Package ppx_bin_prot is already installed (current version is v0.11.0).
[NOTE] Package ppx_compare is already installed (current version is v0.11.0).
[NOTE] Package ppx_custom_printf is already installed (current version is
       v0.11.0).
[NOTE] Package ppx_derivers is already installed (current version is 1.0).
[NOTE] Package ppx_deriving is already installed (current version is 4.2.1).
[NOTE] Package ppx_enumerate is already installed (current version is v0.11.0).
[NOTE] Package ppx_expect is already installed (current version is v0.11.0).
[NOTE] Package ppx_fail is already installed (current version is v0.11.0).
[NOTE] Package ppx_fields_conv is already installed (current version is
       v0.11.0).
[NOTE] Package ppx_hash is already installed (current version is v0.11.0).
[NOTE] Package ppx_here is already installed (current version is v0.11.0).
[NOTE] Package ppx_inline_test is already installed (current version is
       v0.11.0).
[NOTE] Package ppx_jane is already installed (current version is v0.11.0).
[NOTE] Package ppx_js_style is already installed (current version is v0.11.0).
[NOTE] Package ppx_let is already installed (current version is v0.11.0).
[NOTE] Package ppx_optcomp is already installed (current version is v0.11.0).
[NOTE] Package ppx_optional is already installed (current version is v0.11.0).
[NOTE] Package ppx_pipebang is already installed (current version is v0.11.0).
[NOTE] Package ppx_sexp_conv is already installed (current version is v0.11.1).
[NOTE] Package ppx_sexp_message is already installed (current version is
       v0.11.0).
[NOTE] Package ppx_sexp_value is already installed (current version is
       v0.11.0).
[NOTE] Package ppx_tools is already installed (current version is 5.1+4.06.0).
[NOTE] Package ppx_typerep_conv is already installed (current version is
       v0.11.0).
[NOTE] Package ppx_variants_conv is already installed (current version is
       v0.11.0).
[NOTE] Package ppxlib is already installed (current version is 0.2.1).
[NOTE] Package re is already installed (current version is 1.8.0).
[NOTE] Package result is already installed (current version is 1.3).
[NOTE] Package sawja is already installed (current version is 1.5.4).
[NOTE] Package seq is already installed (current version is 0.1).
[NOTE] Package sexplib is already installed (current version is v0.11.0).
[NOTE] Package sexplib0 is already installed (current version is v0.11.0).
[NOTE] Package spawn is already installed (current version is v0.12.0).
[NOTE] Package splittable_random is already installed (current version is
       v0.11.0).
[NOTE] Package stdio is already installed (current version is v0.11.0).
[NOTE] Package topkg is already installed (current version is 0.9.1).
[NOTE] Package typerep is already installed (current version is v0.11.0).
[NOTE] Package variantslib is already installed (current version is v0.11.0).
[NOTE] Package xmlm is already installed (current version is 1.3.0).
[NOTE] Package yojson is already installed (current version is 1.4.1).
[ERROR] The compilation of conf-sqlite3 failed at "pkg-config sqlite3".
[ERROR] The compilation of conf-gmp failed at "sh -exc cc -c $CFLAGS
        -I/usr/local/include test.c".

#=== ERROR while installing conf-gmp.1 ========================================#
# opam-version         1.2.2
# os                   linux
# command              sh -exc cc -c $CFLAGS -I/usr/local/include test.c
# path                 /home/ssseng/.opam/infer-4.06.1+flambda/build/conf-gmp.1
# compiler             4.06.1+flambda
# exit-code            1
# env-file             /home/ssseng/.opam/infer-4.06.1+flambda/build/conf-gmp.1/conf-gmp-2563-1872ec.env
# stdout-file          /home/ssseng/.opam/infer-4.06.1+flambda/build/conf-gmp.1/conf-gmp-2563-1872ec.out
# stderr-file          /home/ssseng/.opam/infer-4.06.1+flambda/build/conf-gmp.1/conf-gmp-2563-1872ec.err
### stderr ###
# + cc -c -I/usr/local/include test.c
# test.c:1:17: fatal error: gmp.h: No such file or directory
# compilation terminated.


#=== ERROR while installing conf-sqlite3.1 ====================================#
# opam-version         1.2.2
# os                   linux
# command              pkg-config sqlite3
# path                 /home/ssseng/.opam/infer-4.06.1+flambda/build/conf-sqlite3.1
# compiler             4.06.1+flambda
# exit-code            1
# env-file             /home/ssseng/.opam/infer-4.06.1+flambda/build/conf-sqlite3.1/conf-sqlite3-2563-d2c37b.env
# stdout-file          /home/ssseng/.opam/infer-4.06.1+flambda/build/conf-sqlite3.1/conf-sqlite3-2563-d2c37b.out
# stderr-file          /home/ssseng/.opam/infer-4.06.1+flambda/build/conf-sqlite3.1/conf-sqlite3-2563-d2c37b.err


The former state can be restored with:
    opam switch import
"~/.opam/infer-4.06.1+flambda/backup/state-20180724123900.export"
Exception:
Reqs_error
 (Process_error
   ("opam install -y ANSITerminal.0.8 apron.20160125 atd.2.0.0 atdgen.2.0.0 atdgen-runtime.2.0.0 base.v0.11.0 base64.2.2.0 bin_prot.v0.11.0 biniou.1.2.0 camlidl.1.05 camlp4.4.06+1 camlzip.1.07 camomile.1.0.1 cmdliner.1.0.2 conf-autoconf.0.1 conf-gmp.1 conf-m4.1 conf-mpfr.1 conf-perl.1 conf-pkg-config."... (* string length 1586; truncated *),
   Unix.WEXITED 4)).

*** `install_opam_deps` failed
*** Updating opam then retrying

=-=- Updating package repositories =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default] synchronized from https://opam.ocaml.org

=-=- Synchronizing development packages -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[lock] https://github.com/rgrinberg/opam-lock already up-to-date

Updates available for infer-4.06.1+flambda, apply them with 'opam upgrade':
===== 27 to recompile | 11 to upgrade =====
[NOTE] Package ANSITerminal is already installed (current version is 0.8).
[NOTE] Package atd is already installed (current version is 2.0.0).
[NOTE] Package atdgen is already installed (current version is 2.0.0).
[NOTE] Package atdgen-runtime is already installed (current version is 2.0.0).
[NOTE] Package base is already installed (current version is v0.11.0).
[NOTE] Package base64 is already installed (current version is 2.2.0).
[NOTE] Package bin_prot is already installed (current version is v0.11.0).
[NOTE] Package biniou is already installed (current version is 1.2.0).
[NOTE] Package camlidl is already installed (current version is 1.05).
[NOTE] Package camlp4 is already installed (current version is 4.06+1).
[NOTE] Package camlzip is already installed (current version is 1.07).
[NOTE] Package camomile is already installed (current version is 1.0.1).
[NOTE] Package cmdliner is already installed (current version is 1.0.2).
[NOTE] Package conf-autoconf is already installed (current version is 0.1).
[NOTE] Package conf-m4 is already installed (current version is 1).
[NOTE] Package conf-perl is already installed (current version is 1).
[NOTE] Package conf-pkg-config is already installed (current version is 1.0).
[NOTE] Package conf-which is already installed (current version is 1).
[NOTE] Package conf-zlib is already installed (current version is 1).
[NOTE] Package configurator is already installed (current version is v0.11.0).
[NOTE] Package core is already installed (current version is v0.11.2).
[NOTE] Package core_kernel is already installed (current version is v0.11.1).
[NOTE] Package cppo is already installed (current version is 1.6.4).
[NOTE] Package cppo_ocamlbuild is already installed (current version is 1.6.0).
[NOTE] Package ctypes is already installed (current version is 0.14.0).
[NOTE] Package dune is already installed (current version is 1.1.1).
[NOTE] Package easy-format is already installed (current version is 1.3.1).
[NOTE] Package extlib is already installed (current version is 1.7.5).
[NOTE] Package fieldslib is already installed (current version is v0.11.0).
[NOTE] Package integers is already installed (current version is 0.2.2).
[NOTE] Package jane-street-headers is already installed (current version is
       v0.11.0).
[NOTE] Package javalib is already installed (current version is 2.3.5).
[NOTE] Package jbuilder is already installed (current version is transition).
[NOTE] Package menhir is already installed (current version is 20180703).
[NOTE] Package mtime is already installed (current version is 1.1.0).
[NOTE] Package num is already installed (current version is 1.1).
[NOTE] Package ocaml-compiler-libs is already installed (current version is
       v0.11.0).
[NOTE] Package ocaml-migrate-parsetree is already installed (current version is
       1.0.11).
[NOTE] Package ocamlbuild is already installed (current version is 0.12.0).
[NOTE] Package ocamlfind is already installed (current version is 1.8.0).
[NOTE] Package octavius is already installed (current version is 1.2.0).
[NOTE] Package ounit is already installed (current version is 2.0.5).
[NOTE] Package parmap is already installed (current version is 1.0-rc10).
[NOTE] Package parsexp is already installed (current version is v0.11.0).
[NOTE] Package ppx_assert is already installed (current version is v0.11.0).
[NOTE] Package ppx_base is already installed (current version is v0.11.0).
[NOTE] Package ppx_bench is already installed (current version is v0.11.0).
[NOTE] Package ppx_bin_prot is already installed (current version is v0.11.0).
[NOTE] Package ppx_compare is already installed (current version is v0.11.0).
[NOTE] Package ppx_custom_printf is already installed (current version is
       v0.11.0).
[NOTE] Package ppx_derivers is already installed (current version is 1.0).
[NOTE] Package ppx_deriving is already installed (current version is 4.2.1).
[NOTE] Package ppx_enumerate is already installed (current version is v0.11.0).
[NOTE] Package ppx_expect is already installed (current version is v0.11.0).
[NOTE] Package ppx_fail is already installed (current version is v0.11.0).
[NOTE] Package ppx_fields_conv is already installed (current version is
       v0.11.0).
[NOTE] Package ppx_hash is already installed (current version is v0.11.0).
[NOTE] Package ppx_here is already installed (current version is v0.11.0).
[NOTE] Package ppx_inline_test is already installed (current version is
       v0.11.0).
[NOTE] Package ppx_jane is already installed (current version is v0.11.0).
[NOTE] Package ppx_js_style is already installed (current version is v0.11.0).
[NOTE] Package ppx_let is already installed (current version is v0.11.0).
[NOTE] Package ppx_optcomp is already installed (current version is v0.11.0).
[NOTE] Package ppx_optional is already installed (current version is v0.11.0).
[NOTE] Package ppx_pipebang is already installed (current version is v0.11.0).
[NOTE] Package ppx_sexp_conv is already installed (current version is v0.11.1).
[NOTE] Package ppx_sexp_message is already installed (current version is
       v0.11.0).
[NOTE] Package ppx_sexp_value is already installed (current version is
       v0.11.0).
[NOTE] Package ppx_tools is already installed (current version is 5.1+4.06.0).
[NOTE] Package ppx_typerep_conv is already installed (current version is
       v0.11.0).
[NOTE] Package ppx_variants_conv is already installed (current version is
       v0.11.0).
[NOTE] Package ppxlib is already installed (current version is 0.2.1).
[NOTE] Package re is already installed (current version is 1.8.0).
[NOTE] Package result is already installed (current version is 1.3).
[NOTE] Package sawja is already installed (current version is 1.5.4).
[NOTE] Package seq is already installed (current version is 0.1).
[NOTE] Package sexplib is already installed (current version is v0.11.0).
[NOTE] Package sexplib0 is already installed (current version is v0.11.0).
[NOTE] Package spawn is already installed (current version is v0.12.0).
[NOTE] Package splittable_random is already installed (current version is
       v0.11.0).
[NOTE] Package stdio is already installed (current version is v0.11.0).
[NOTE] Package topkg is already installed (current version is 0.9.1).
[NOTE] Package typerep is already installed (current version is v0.11.0).
[NOTE] Package variantslib is already installed (current version is v0.11.0).
[NOTE] Package xmlm is already installed (current version is 1.3.0).
[NOTE] Package yojson is already installed (current version is 1.4.1).
[ERROR] The compilation of conf-sqlite3 failed at "pkg-config sqlite3".
[ERROR] The compilation of conf-gmp failed at "sh -exc cc -c $CFLAGS
        -I/usr/local/include test.c".

#=== ERROR while installing conf-gmp.1 ========================================#
# opam-version         1.2.2
# os                   linux
# command              sh -exc cc -c $CFLAGS -I/usr/local/include test.c
# path                 /home/ssseng/.opam/infer-4.06.1+flambda/build/conf-gmp.1
# compiler             4.06.1+flambda
# exit-code            1
# env-file             /home/ssseng/.opam/infer-4.06.1+flambda/build/conf-gmp.1/conf-gmp-4339-05296d.env
# stdout-file          /home/ssseng/.opam/infer-4.06.1+flambda/build/conf-gmp.1/conf-gmp-4339-05296d.out
# stderr-file          /home/ssseng/.opam/infer-4.06.1+flambda/build/conf-gmp.1/conf-gmp-4339-05296d.err
### stderr ###
# + cc -c -I/usr/local/include test.c
# test.c:1:17: fatal error: gmp.h: No such file or directory
# compilation terminated.


#=== ERROR while installing conf-sqlite3.1 ====================================#
# opam-version         1.2.2
# os                   linux
# command              pkg-config sqlite3
# path                 /home/ssseng/.opam/infer-4.06.1+flambda/build/conf-sqlite3.1
# compiler             4.06.1+flambda
# exit-code            1
# env-file             /home/ssseng/.opam/infer-4.06.1+flambda/build/conf-sqlite3.1/conf-sqlite3-4339-1872ec.env
# stdout-file          /home/ssseng/.opam/infer-4.06.1+flambda/build/conf-sqlite3.1/conf-sqlite3-4339-1872ec.out
# stderr-file          /home/ssseng/.opam/infer-4.06.1+flambda/build/conf-sqlite3.1/conf-sqlite3-4339-1872ec.err

Exception:
Reqs_error
 (Process_error
   ("opam install -y ANSITerminal.0.8 apron.20160125 atd.2.0.0 atdgen.2.0.0 atdgen-runtime.2.0.0 base.v0.11.0 base64.2.2.0 bin_prot.v0.11.0 biniou.1.2.0 camlidl.1.05 camlp4.4.06+1 camlzip.1.07 camomile.1.0.1 cmdliner.1.0.2 conf-autoconf.0.1 conf-gmp.1 conf-m4.1 conf-mpfr.1 conf-perl.1 conf-pkg-config."... (* string length 1586; truncated *),
   Unix.WEXITED 4)).

*** ERROR: `install_opam_deps` failed
ssseng@ssseng-Inspiron-5559:/media/Drive/infer/infer$

**Comment by vnrajan** [comment]
Thanks.

SQLite is already the latest version;

ssseng@ssseng-Inspiron-5559:/media/Drive/infer/infer$ sudo apt-get install sqlite
Reading package lists... Done
Building dependency tree       
Reading state information... Done
sqlite is already the newest version (2.8.17-12fakesync1).
The following packages were automatically installed and are no longer required:
  libllvm5.0 libllvm5.0:i386 libmircommon5 libqmi-glib1 libqpdf17
  ubuntu-core-launcher
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.

Tried to install gmp libraries

ssseng@ssseng-Inspiron-5559:/media/Drive/infer/infer$ sudo apt-get install gmp
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package gmp

Is there any explicit/specific command need to be executed for below errors;

1. [ERROR] The compilation of conf-sqlite3 failed at "pkg-config sqlite3".
2. [ERROR] The compilation of conf-gmp failed at "sh -exc cc -c $CFLAGS

Kindly support to resolve this failure.

**Comment by jvillard** [comment]
I think on ubuntu the packages you need are named "libsqlite3-dev" and "libgmp-dev".

**Comment by vnrajan** [comment]
Thanks Mr. @jvillard 

All the errors has been resolved and i could build and run "infer" now on my Ubutu PC.

Infer is working fine and its a good tool to avoid manual mistakes (including coder and reviewer) in coding especially resource leak, null dereference and so on. I will work more and contact you if any help/support required.

I will also try it on the Fedora and ask incase of any help.

Thanks once again.
